projects/bs4/Dockerfile
```
Step #1: Step 3/5 : RUN pip3 install soupsieve html5lib lxml
Step #1:  ---> Running in 95c0ff529f3c
Step #1: Collecting soupsieve
Step #1:   Downloading https://files.pythonhosted.org/packages/4c/f3/038b302fdfbe3be7da016777069f26ceefe11a681055ea1f7817546508e3/soupsieve-2.5-py3-none-any.whl
Step #1: Collecting html5lib
Step #1:   Downloading https://files.pythonhosted.org/packages/6c/dd/a834df6482147d48e225a49515aabc28974ad5a4ca3215c18a882565b028/html5lib-1.1-py2.py3-none-any.whl (112kB)
Step #1: Collecting lxml
Step #1:   Downloading https://files.pythonhosted.org/packages/2b/b4/bbccb250adbee490553b6a52712c46c20ea1ba533a643f1424b27ffc6845/lxml-5.1.0.tar.gz (3.8MB)
Step #1:   Installing build dependencies: started
Step #1:   Installing build dependencies: finished with status 'done' …
```
=> Fix bs4 build

projects/jackson-dataformats-binary/CborParserFuzzer.java
This PR fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=65748 in `CborParserFuzzer` by wrapping an expected exception.
=> jackson-dataforamts-binary: Wrap expected exceptions

projects/arrow/project.yaml
Felipe Oliveira Carvalho is a committer on Apache Arrow and works actively on Arrow C++ maintenance. He would like to be involved in handling issues detected by OSS-Fuzz.
=> arrow: Add Felipe Oliveira Carvalho to ccs

projects/bignum-fuzzer/Dockerfile, projects/bignum-fuzzer/build.sh, projects/cryptofuzz/Dockerfile, projects/cryptofuzz/build.sh
mpdecimal-4.0.0 has been released:
https://www.bytereef.org/mpdecimal/changelog.html
It would be nice to update the fuzzer.
=> [bignum-fuzzer] Update mpdecimal to version 4.0.0

projects/protobuf-python/Dockerfile, projects/protobuf-python/build.sh
We have merged the upb repo into the main protobuf repo, so the reference to `@upb` is no longer valid. This change should fix the protobuf-python build.
=> protobuf-python: Fix build

projects/nokogiri/Dockerfile, projects/nokogiri/build.sh
Without these flags being set properly, the build has been failing, see https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=65904
Also: use a shallow git clone when building the container
(Solves issue introduced in #11494 /cc @fuzzy-boiii23a)
=> fix(nokogiri): pass CFLAGS and CXXFLAGS to the make command

infra/build/functions/build_lib.py, infra/build/functions/target_experiment.py
Instead of relying on `gcloud builds submit` to poll the status of the build for us, we poll ourselves.
This is because `gcloud builds submit` has a fixed poll interval of 1 second.
=> target_experiment: Avoid rate limiting issues with cloudbuild get.

projects/cryptofuzz/build.sh
Start fuzzing the new (since 2018) crypto API in Mbed TLS, before the old API becomes deprecated and partly removed in 2024. See https://github.com/guidovranken/cryptofuzz/issues/47
=> Cryptofuzz: add Mbed TLS PSA Crypto API module

projects/icu/build.sh
Our fuzzer try to use out of bound enum to make sure the API will not crash so we like to turn that enum check off to avoid noise.
=> Turn off ubsan enum check for ICU project

projects/ostree/Dockerfile
Recently glib's build process changed as it integrates parts of gobject-introspection. The only reason to build glib at all is because the version in the base image is a bit too old. Rather than building glib main, use a tagged version. 2.78.4 is a very recent stable release that satisfies ostree's 2.66.0 requirement.
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=64890
=> ostree: Build with stable glib

projects/date/project.yaml
This PR proposes integrating `date` into OSSFuzz. 
I believe that this repository is security-relevant due to its high star-count and its being a dependency in various large projects, some of which are under OSSFuzz already (such as arrow). This library also parses user-input in order to convert date strings into various formats, thus exposing itself to potential exploitation. 
Thank you for your review!
=> Initial project skeleton: date

projects/aptos-core/build.sh, projects/aptos-core/project.yaml
This Pull Request introduces significant updates to our project's build process. The changes are twofold:
- Refactoring Build Process: In alignment with our internal design choices, this PR shifts the majority of the logic previously encapsulated within build.sh to our own fuzzer build script. This move is aimed at improving the modularity and maintainability of our build process.
- Updating 'auto_ccs': This PR includes an update to the auto_ccs section of our project, so we can sign in on the Dashboard.
Thanks.
=> Refactoring Build Logic and Updating 'auto_ccs' with New Contributors Aptos-Core

projects/cbor2/Dockerfile, projects/cbor2/build.sh, projects/cbor2/loads_fuzzer.py, projects/cbor2/project.yaml
`cbor2` is a Python CBOR (de)serializer with extensive tag support.
It has nearly [2,000 dependents](https://github.com/agronholm/cbor2/network/dependents) on GitHub. It's used by many large blockchain projects, such as:
- https://github.com/bitcoin-core/HWI
- https://github.com/Blockstream/Jade
- https://github.com/vyperlang/vyper
- https://github.com/lidofinance/lido-dao
- https://github.com/fetchai/cosmpy
- https://github.com/OpShin/opshin
And other non-blockchain projects, such as:
- https://github.com/project-chip/connectedhomeip
- https://github.com/pritunl/pritunl
- https://github.com/amazon-ion/ion-python
I received approval from this project here: https://github.com/agronholm/cbor2/pull/204#issuecomment-1874467670
=> Proposing new project: Python cbor2

infra/cifuzz/example_cifuzz.yml
When tried to enable CI fuzzing for md4c project as described at https://google.github.io/oss-fuzz/getting-started/continuous-integration/, encountered some issues:
- Broken indentation.
- The step "Upload Sarif" fails (and I'm not the 1st one to encounter it: See #10915)
These changes seem to fix it for me.
=> Few fixes to infra/cifuzz/example_cifuzz.yml.

projects/mp4san/Dockerfile, projects/mp4san/project.yaml
The mp4san project has been moved to the Signal Messenger organization (signalapp on github).
- Updated repo URLs: repo was moved to `signalapp` organization on github
- Added Signal employees to `auto_ccs`
=> mp4san: project moved to Signal org

projects/typst/project.yaml
It looks like when Google switch over from googlemail.com to gmail.com they didn't do this across the board i.e. with bugs.chromium.com, this means that @laurmaedje currently can't access the bug tracker.
=> typst: Change primary author email

projects/libxlsxwriter/Dockerfile
This PR introduces the Dockerfile to build the libXLSXwriter harnesses, which are hosted upstream
=> LibXLSXWriter Dockerfile

infra/build/fuzz-introspector-webapp/cloudbuild.yaml
Explicitly set CPUs. 4 CPUs are required for > 8 GiB. Also bump memory to 16GiB just in case for now. 
Also increase build timeout to 6 hours.
=> More fuzz introspector webapp build fixes

infra/base-images/base-builder/Dockerfile
See discussion in issue #10564. Upstream UBSan intentionally does not enable float-divide-by-zero by default. On all Clang platforms, and indeed all IEEE floating point platforms, including all the ones that OSS-Fuzz fuzzes on, the operation is defined. OSS-Fuzz should avoid making every project rediscover this build quirk themselves each time.
While a project that wishes to support non-IEEE floating point may want this behavior, it would need to do that fuzzing on said non-IEEEE platform anyway, because the rest of floating point will be different too. OSS-Fuzz (and indeed Clang) does not provide such things, so that's out of scope here.
=> Don't enable float-divide-by-zero by default

infra/base-images/base-builder/compile, projects/surrealdb/Dockerfile
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=65817
=> infra/rust/coverage: copy right toolchain sources

projects/lua/build.sh
Paths were changed after reorganization in tests [1]
1. https://github.com/ligurio/lua-c-api-tests/commit/e0216377d7502230e76d572f9344109406b1a95c
=> lua: update introspector paths

projects/abseil-cpp/project.yaml
I was alerted via b/323340435 that the current primary contact is a public Google Group. Changing the contact to myself to prevent early disclosure of detected vulnerabilities.
=> abseil-cpp: Make myself the primary contact

projects/libxslt/project.yaml
This was causing issues when parsing the `project.yaml` files:
```sh
File "/home/dav/code/2024/fuzz-introspector-14/fuzz-introspector/tools/web-fuzzing-introspection/.venv/lib/python3.10/site-packages/yaml/parser.py", line 98, in check_event
self.current_event = self.state()
File "/home/dav/code/2024/fuzz-introspector-14/fuzz-introspector/tools/web-fuzzing-introspection/.venv/lib/python3.10/site-packages/yaml/parser.py", line 392, in parse_block_sequence_entry
raise ParserError("while parsing a block collection", self.marks[-1],
yaml.parser.ParserError: while parsing a block collection
in "<unicode string>", line 5, column 3:
- "ddkilzer@apple.com"
^
expected <block end>, but found '<scalar>'
in "<unicode string>", line 15, column 6:
- "albassam@apple.com"
^
```
fyi @oliverchang
=> libxslt: fix quote in project.yaml

projects/inchi/Dockerfile, projects/inchi/build.sh, projects/inchi/project.yaml
Fixes: https://github.com/google/oss-fuzz/issues/11591
=> inchi: adjust build to latest upstream

projects/igraph/project.yaml
[We compile libxml2 together with igraph](https://github.com/igraph/igraph/blob/master/fuzzing/build.sh) for two reasons:
- Disable ICU support in libxml2 to work around [a still-existing ICU crash bug](https://unicode-org.atlassian.net/browse/ICU-21932) that the igraph fuzzer was hitting
- MSan support requires compiling all dependencies
This PR tries to ensure that coverage is only measured for igraph, not for libxml2.
=> igraph: exclude external libxml2 from coverage measurements

projects/jsonnet/project.yaml
Add @johnbartholomew (both corp and non-corp) addresses so I can get access to test cases. @sparkprime remains the primary contact/owner.
=> jsonnet: Add myself as a second contact

projects/cert-manager/Dockerfile, projects/cert-manager/build.sh, projects/cert-manager/pki_fuzzer.go, projects/cert-manager/project.yaml
Cert-Manager is a cloud-native tool for provisioning and maintaining certficates in an automatic manner. Cert-Manager is often used to secure ingress cluster traffic, but is at its core a more general tool to secure traffic between any cluster asset.
Its users include the following companies:
- JFrog: https://jfrog.com/
- URSSAF (A provider to Frances national health system): https://www.urssaf.fr/portail/home.html
- Diagrid: https://www.diagrid.io/
Source: https://github.com/cert-manager/community/blob/main/USERS.md
=> cert-manager: initial integration

projects/ion-java/project-parent/fuzz-targets/src/test/java/com/example/IonReaderFuzzer.java
Fixes build failure for `ion-java`: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=63457
`withAnnotationIteratorReuseEnabled` was removed from `IonReaderBuilder`. Removing this will cause the build to succeed.
`NullPointerException`, `ArrayIndexOutOfBoundsException`, and `AssertionError` should not leak from the library; such leaks would be useful to find during fuzzing.
=> ion-java: fix build

projects/immer/Dockerfile, projects/immer/build.sh
immer's fuzzers do not depend on Catch2 anymore
This change is triggered by `immer` moving to use Catch2 v3, so the current build script will break.
=> Remove Catch2 dependency from `immer`'s fuzzers

infra/base-images/base-builder/install_java.sh
Ref: https://github.com/google/oss-fuzz/issues/11613
For some reason this dependency in jazzer's WORKSPACE:
```sh
http_archive(
name = "com_grail_bazel_toolchain",
sha256 = "da607faed78c4cb5a5637ef74a36fdd2286f85ca5192222c4664efec2d529bb8",
strip_prefix = "bazel-toolchain-0.6.3",
urls = ["https://github.com/grailbio/bazel-toolchain/archive/refs/tags/0.6.3.tar.gz"],
)
```
is no longer valid. The URL now downloads `toolchains_llvm-0.6.3` instead, and this looks to be because they renamed the repo https://github.com/grailbio/bazel-toolchain which now redirects to https://github.com/bazel-contrib/toolchains_llvm
=> infra: hotfix java base builder

projects/litmuschaos/Dockerfile, projects/litmuschaos/project.yaml
[Litmus](https://litmuschaos.io/) is an open source Chaos Engineering platform that enables teams to identify weaknesses & potential outages in infrastructures by inducing chaos tests in a controlled way.
Developers & SREs can simply execute Chaos Engineering with Litmus as it is easy to use, based on modern chaos engineering practices & community collaborated. Litmus is 100% open source & CNCF-incubated.
Github repo: https://github.com/litmuschaos/litmus
Documentation: https://docs.litmuschaos.io/
=> [Litmus]: Added initial integration 

projects/openssl/build.sh
The docker image that runs the openssl build goes
quickly out of disk space, because 4 different versions are built and since a while all CIFuzz builds started to fail, since the disk space is used up when the last openssl version is built.
Mitigate that problem by deleting the source directory after the fuzzer build is complete, since that source tree is no longer needed at this time.
=> Avoid openssl build errors due to out of disk space

projects/apache-commons-compress/ArchiverDumpFuzzer.java, projects/apache-commons-compress/CompressorPack200Fuzzer.java, projects/apache-commons-compress/Dockerfile
This PR adds support for DUMP and COMPRESS formats. This work is being tracked on the project side here:
https://issues.apache.org/jira/browse/COMPRESS-632
=> apache-commons-compress: Adding coverage for DUMP and Pack200 formats (COMPRESS-632)

projects/pcre2/build.sh, projects/pcre2/project.yaml
This corresponds to an issue on PCRE2 regarding fuzzer improvements w.r.t. JIT: https://github.com/PCRE2Project/pcre2/pull/317
=> Enable jitting in pcre2

projects/iverilog/project.yaml
I am requesting permission to integrate [iverilog](https://github.com/steveicarus/iverilog) into OSSFuzz. I believe that this project is a good candidate for OSS-Fuzz integration as it serves as a preeminent compiler for Verilog HDL. As such, it directly preprocesses, parses, and compiles user-inputted VHDL programs, opening it up to a wide array of edge cases in capturing a complex language grammar and the potential for memory vulnerabilities (being written in C++).
=> Project Request: iverilog

projects/ffmpeg/build.sh
because of "error while loading shared libraries: libdrm.so.2: cannot
open shared object file: No such file or directory"
Alternatively we can copy that to the lib directory like it seems done with libz/bz2
https://github.com/google/oss-fuzz/pull/11629 depends on this but it seems even on its own some things seem to fail without this
=> [FFmpeg] disable libdrm

projects/pest/build.sh
this should hopefully resolve the recent build issue:
```
Step #5: warning: /workspace/out/libfuzzer-coverage-x86_64/dumps/parser.14845295624977050394_0.profraw: unsupported instrumentation profile format version
Step #5: error: no profile can be merged
Step #5: [2024-02-28 06:09:14,766 INFO] Finding shared libraries for targets (if any).
Step #5: [2024-02-28 06:09:14,775 INFO] Finished finding shared libraries for targets.
Step #5: error: parser: Failed to load coverage: No such file or directory
Step #5: error: Could not load coverage information
Step #5: error: No such file or directory: Could not read profile data!
Step #5: Traceback (most recent call last):
Step #5:   File "/usr/local/bin/profraw_update.py", line 129, in <module>
Step #5:     sys.exit(main())
Step #5:   File …
```
=> pest: remove +nightly from cargo fuzz build

projects/libyang/build.sh
=> libyang: standard CMake var for static build is now used

projects/libjxl/build.sh
This reverts #6837, since it seems to have been fixed in the meantime, see also https://github.com/libjxl/libjxl/issues/858
=> re-enable SSSE3 target for libjxl

projects/golang/build.sh
Since we're operating inside of the main Go tree, we end up using the tip go.mod file, which typically defines a Go toolchain version which is not available yet. Explicitly setting GOTOOLCHAIN to "local" tells the toolchain to use the right (available) version, instead of trying to download the tip version.
This should fix the build... I think.
=> [golang] explicitly set toolchain version

projects/golang/project.yaml
We've had multiple security reports originating from crashes discovered by oss-fuzz. I was unaware that the results were entirely public.
Restrict access to issues to the Go Security team.
**Note:** It's unclear to me if this actually accomplishes what I want. `view_restrictions` seems entirely undocumented. From contextual clues from other projects it _seems_ that removing the field causes restriction, but that is entirely a guess.
=> [golang] restrict access to golang issues

projects/libjxl/Dockerfile
revert #7063, since it is no longer needed, see
https://github.com/libjxl/libjxl/pull/1588.
=> remove unused gflags dependency for libjxl

projects/quickjs/fuzz_compile.c, projects/quickjs/fuzz_eval.c, projects/quickjs/fuzz_regexp.c
Google's internal fuzzers found tests that make `fuzz_regexp.c` exceed stack memory. Turns out, QuickJS already has built-in mechanism for tracking that stack size doesn't exceed a given limit - it's just that limit isn't set for fuzzer tests by default
Setting the limit to 64kb as a reasonable default setting
=> [quickjs] Set max stack limit.

projects/td-shim/Dokerfile, projects/td-shim/build.sh, projects/td-shim/project.yaml
TD Shim is a simplified [TDX virtual firmware](https://github.com/confidential-containers/td-shim/blob/main/doc/tdshim_spec.md#vfw) for the simplified kernel for TD container.
=> td-shim: Initial integration

projects/bazel-rules-fuzzing-test-java/build.sh, projects/bazel-rules-fuzzing-test/build.sh
Work around https://github.com/bazelbuild/bazel/issues/21592 as discovered in https://github.com/bazelbuild/rules_fuzzing/pull/242#issuecomment-1974913042.
=> Fix rules_fuzzing presubmit

projects/fastcsv/CsvReaderFuzzer.java
This PR fixes a false positive issues reported in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=67386.
=> fastcsv: Catch CsvParseException

projects/libxml2/build.sh
build.sh is now maintained in the upstream libxml2 repo to facilitate changes.
=> libxml2: Move build.sh to upstream repo

projects/cras/Dockerfile
ladspa-sdk support removed in https://crrev.com/c/5369016.
=> projects/cras: Remove unused deps

projects/igraph/project.yaml
This is to give @GroteGnoom access to igraph crash reports, as they'll be helping with fixing issues and adding new fuzz targets.
=> igraph: provide access for an additional team member

projects/systemd/project.yaml
monorail keeps updating every open issue every other day and also keeps sending notifications to everyone.
To judge from https://github.com/google/oss-fuzz/issues/6825 it happens due to inactive addresses and the only way to fix it is to remove addresses like that.
=> [systemd] drop address confusing monorail

projects/bignum-fuzzer/Dockerfile, projects/cryptofuzz/Dockerfile
Fix the mbedtls build in bignum-fuzzer and cryptofuzz. (mbedtls and ecc-diff-fuzzer still had `--recursive` from earlier days.)
=> mbedtls now has a submodule (again)

projects/spdm-rs/Dockerfile, projects/spdm-rs/build.sh, projects/spdm-rs/project.yaml
The `spdm-rs` provides a Rust language implementation of [SPDM](https://www.dmtf.org/standards/spdm) which is used to for Trusted Execution Environment I/O (TEE-I/O) in Confidential Computing.
Project repo: https://github.com/ccc-spdm-tools/spdm-rs
=> [spdm-rs]: add initial integration for spdm-rs

infra/build/functions/target_experiment.py
Helps https://github.com/google/oss-fuzz-gen/issues/156:
1. `target_experiment.py` takes a new parameter, `upload_reproducer_path`.
2. `target_experiment.py` saves crash reproducer  to `local_artifect_path`.
3. `target_experiment.py` uploads the fuzz target binary, the crash reproducer, and stacktrace to bucket directory `upload_reproducer_path`.
=> `target_experiment.py`  uploads reproducer and binary in target_experiment.py 

infra/build/functions/target_experiment.py
Related: https://github.com/google/oss-fuzz-gen/pull/172, #11700.
This simplifies the link generation in benchmark `JSON`.
Previously, the binary directory name matches the binary name, now it is always called `target_binary/`.
=> Unify the bucket directory name for target binary in `target_experiment.py`

projects/fastcsv/Dockerfile, projects/fastcsv/build.sh
This PR fixes a Coverage build failure reported in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=67425.
The failure is due to missing Java 21 support in the coverage container when running JaCoCo:
```
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 65
```
Unfortunately, I couldn't find a way to add Java 21 support. As a workaround, I've downgraded the Java version to 17 when building the project.
I've tested the changes locally and the Coverage build is now passing.
If you have an idea how to add Java 21 support instead of downgrading to 17, please let me know.
=> fastcsv: Fix Coverage build failure

projects/xpdf/fuzz_pdfload.cc
The number of pages is starting at `1`, and not at `0`
This should fix #11711
=> Fix the xpdf fuzzer

infra/base-images/base-builder/bazel_build_fuzz_tests
This does the same as https://github.com/google/oss-fuzz/pull/11715 which seems to be stuck in the CI
=> infra: bazel_build_fuzz_tests: do not force O0 (second try)

projects/lua/build.sh
OSS Fuzz documentation says that default name of dictionary file is the same as fuzzer filename:
> If the dict filename is the same as your target binary name
> (i.e. `%fuzz_target%.dict`), it will be automatically used.
The patch fixes `build.sh` accordingly.
=> lua: fix .dict and .options filenames

infra/build/functions/build_lib.py
The GCE metadata server can be unresponsive sometimes, resulting in this exception.
This should address the  root cause of the stack trace pointed out in https://github.com/google/oss-fuzz/pull/11727
=> Handle BrokenPipeError in wait_for_build

projects/quickjs/fuzz_compile.c, projects/quickjs/fuzz_eval.c
LibFuzzer reads input corpus as binary data and it doesn't ensure it to be zero-terminated. Since quickjs expects receiving zero-terminated input, only those tests were enabled in the fuzz targets. However, this condition discards many useful tests, the whole input corpus among others. The patch ensures to zero-terminate all inputs properly.
=> [quickjs] Ensure input data is zero-terminated

infra/build/functions/build_lib.py
This reverts commit a80fd730e4b7ac89726055894c746b674fbe2370.
The investigation shows that the slowness issues and `BrokenPipe` error mentioned in https://github.com/google/oss-fuzz/pull/11727#issue-2205034022 are not caused by #11701, so this PR reverts #11727.
Queued cloud builds of a full experiment likely caused the slowness.
Specifically, some cloud builds' `BrokenPipe` error caused them to queue forever, which blocks other cloud builds and causes the slowness.
This should have been solved by #11729, I will start another full experiment shortly and verify that.
=> Reapply "target_experiment: don't use gcloud. (#11701)" (#11727)

projects/servo/project.yaml
@emilio is the primary maintainer of rust-cssparser, so he should have access to the issues reported for it.
=> Add Emilio to CC list for rust-cssparser

projects/apache-httpd/build.sh, projects/apache-httpd/fuzz_request.c
This is needed for compilers after clang-16. Otherwise, there are errors, such as:
```
/src/fuzz_request.c:59:3: error: call to undeclared function 'ap_hook_http_scheme'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
59 |   ap_hook_http_scheme(http_scheme2, NULL, NULL, APR_HOOK_REALLY_LAST);
|   ^
/src/fuzz_request.c:92:5: error: call to undeclared function 'ap_method_registry_init'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
92 |     ap_method_registry_init(conn.pool);
|     ^
=> apache-httpd: Add missing includes

projects/s2opc/Dockerfile, projects/s2opc/build.sh
To fix clang-18 errors:
```
/work/mbedtls-2.28.0/library/bignum.c:1395:29: error: variable 't' set but not used [-Werror,-Wunused-but-set-variable]
1395 |     mbedtls_mpi_uint c = 0, t = 0;
|                             ^
make[2]: *** [library/CMakeFiles/mbedcrypto.dir/build.make:174: library/CMakeFiles/mbedcrypto.dir/bignum.c.o] Error 1
=> s2opc: Bump mbedtls

projects/hdf5/h5_extended_fuzzer.c, projects/hdf5/h5_read_fuzzer.c
To fix a clang-18 error:
```
/src/h5_read_fuzzer.c:27:44: error: call to undeclared function 'getpid'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
27 |     sprintf(filename, "/tmp/libfuzzer.%d", getpid());
|                                            ^
ERROR:__main__:Building fuzzers failed.
=> hdf5: Add mising include

projects/alembic/Dockerfile
This is required to allow newer compilers, such as clang-18.
=> alembic: Bump OpenEXR

projects/libressl/Dockerfile, projects/libressl/build.sh
Split out from https://github.com/google/oss-fuzz/pull/11741, to test the fix https://github.com/google/oss-fuzz/pull/11741#issuecomment-2024925131 independently.
=> libressl: Bump Boost download URL

projects/bearssl/Dockerfile, projects/bearssl/build.sh, projects/bitcoin-core/Dockerfile, projects/bitcoin-core/build_cryptofuzz.sh, projects/bls-signatures/Dockerfile, projects/bls-signatures/build.sh
Split out from https://github.com/google/oss-fuzz/pull/11741 to allow CI to not timeout
=> Bump Boost download URL in Cryptofuzz-related projects (part 2)

projects/ntopng/Dockerfile, projects/ntopng/build.sh
Also, suppress the missing-braces error. Both are done to fix issues with clang-18.
=> ntopng: Bump dependecies

projects/quickjs/fuzz_eval.c
This is required for modern compilers to be able to compile it. Otherwise:
```
fuzz_eval.c:61:9: error: call to undeclared library function 'memcpy' with type 'void *(void *, const void *, unsigned long)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
61 |         memcpy(NullTerminatedData, Data, Size);
|         ^
fuzz_eval.c:61:9: note: include the header <string.h> or explicitly provide a declaration for 'memcpy'
ERROR:__main__:Building fuzzers failed.
=> quickjs: Add missing include to fuzz_eval.c

projects/circl/Dockerfile, projects/circl/build.sh, projects/cryptofuzz/Dockerfile, projects/cryptofuzz/build.sh
Split out from https://github.com/google/oss-fuzz/pull/11741 to allow CI to not timeout
=> Bump Boost download URL in Cryptofuzz-related projects (part 3)

projects/haproxy/fuzz_cfg_parser.c
Needed for clang-18:
```
fuzz_cfg_parser.c:29:41: error: call to undeclared function 'getpid'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
29 |         sprintf(filename, "/tmp/libfuzzer.%d", getpid());
|                                                ^
fuzz_cfg_parser.c:38:2: error: call to undeclared function 'readcfgfile'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
38 |         readcfgfile(filename);
|         ^
fuzz_cfg_parser.c:40:2: error: call to undeclared function 'unlink'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
40 |         unlink(filename);
|         ^
3 errors generated.
ERROR:__main__:Building fuzzers failed.
=> haproxy: Add missing includes

projects/kcodecs/build.sh
As soon as selecting C++17, at least in clang-18, it will fail:
```
./getline.cc:58:7: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
58 |       register int c = getc (stream);
|       ^~~~~~~~
=> kcodecs: Avoid clang-18 error

projects/libecc/Dockerfile, projects/libecc/build.sh, projects/nettle/Dockerfile, projects/nettle/build.sh, projects/num-bigint/Dockerfile, projects/num-bigint/build.sh, projects/relic/Dockerfile, projects/relic/build.sh
For some reason GitHub closed  #11741 without merge. So this is the same changes, reopened.
=> Bump Boost download URL in Cryptofuzz-related projects (part 1)

projects/sharp/build.sh
Manually installs the `emnapi` dependency without running scripts to workaround an upstream npm registry data problem.
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=67706
Upstream report https://github.com/toyobayashi/emnapi/issues/112
=> sharp: fix build

projects/xz-java/project.yaml, projects/xz/project.yaml
In light of https://www.openwall.com/lists/oss-security/2024/03/29/4 we will change the contact of the xz projects back to the original maintainer.
Related:
https://github.com/google/oss-fuzz/issues/11760
=> Replace xz contributor with project owner.

projects/dropbear/Dockerfile, projects/dropbear/build.sh
hg.ucc.asn.au was intermittently unavailable it's available now.
This reverts commit 10b8aeddd7380fe6f10927fffb495ea020f9b867.
It would be good to CC project maintainers when merging something like #8183 (I didn't realise the corpus had been removed, I could have moved the server if needed)
=> Revert "dropbear: fix broken build (#8183)"

projects/hpn-ssh/project.yaml
Request to add the HPN-SSH project to CIFuzz. HPN-SSH is a soft fork of OpenSSH that provides significantly improved performance and functionality. It's relatively widely used and we'd like to make sure that our changes pass fuzz tests.
=> HPN-SSH Initial Request for New Project

projects/igraph/project.yaml
Ignore vendored sources in igraph, as these are (mostly) used only when an external version of the respective library is not available.
=> igraph: ignore vendored code in coverage

projects/libvips/Dockerfile
In favor of libspng, which is preferred by libvips.
Depends on: https://github.com/libvips/libvips/pull/3919.
=> libvips: remove redundant libpng dependency

projects/crosvm/Dockerfile
Using `apt upgrade` without `-y` is problematic, because it may fail:
```
Step #17: Step 3/4 : RUN apt-get upgrade && apt-get install --yes --no-install-recommends     libclang-dev     pkg-config     libcap-dev
Step #17:  ---> Running in 4fd961f9329f
Step #17: Reading package lists...
Step #17: Building dependency tree...
Step #17: Reading state information...
Step #17: Calculating upgrade...
Step #17: The following packages will be upgraded:
Step #17:   bsdutils fdisk libblkid1 libfdisk1 libmount1 libsmartcols1 libuuid1 mount
Step #17:   util-linux
Step #17: 9 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Step #17: Need to get 1901 kB of archives.
Step #17: After this operation, 4096 B of additional disk space will be used.
Step #17: Do you want to continue? [Y/n] Abort. …
```
=> crosvm: Fix apt-get command

projects/bitcoin-core/build.sh
Can be dropped after https://github.com/bitcoin/bitcoin/pull/29803.
Equivalent in our CI is https://github.com/bitcoin/bitcoin/pull/29742.
=> bitcoin-core: remove --with-asm=no from MSAN job

projects/lua/build.sh
=> lua: enable Leakanitizer debug mode

projects/suricata/build.sh
As done by openssl in https://github.com/google/oss-fuzz/pull/11618
Is there a way from build.sh to know if we are built by CIFuzz ? Like environment variable `CFL_PLATFORM` ?
Because I do not think we want to build other branches than master for CIFuzz
=> suricata: clean some disk space while building

projects/lua/build.sh
When using `-fanitize=address`, we consistently get spurious build failures on ARM64 due to some issue with the leak detection pass at the end of execution:
```
==2413==AddressSanitizer: failed to intercept '__isoc99_printf'
==2413==AddressSanitizer: failed to intercept '__isoc99_sprintf'
==2413==AddressSanitizer: failed to intercept '__isoc99_snprintf'
==2413==AddressSanitizer: failed to intercept '__isoc99_fprintf'
==2413==AddressSanitizer: failed to intercept '__isoc99_vprintf'
==2413==AddressSanitizer: failed to intercept '__isoc99_vsprintf'
==2413==AddressSanitizer: failed to intercept '__isoc99_vsnprintf'
==2413==AddressSanitizer: failed to intercept '__isoc99_vfprintf'
==2413==AddressSanitizer: failed to intercept 'xdr_destroy'
==2413==AddressSanitizer: failed to intercept 'crypt' …
```
=> lua: work around LeakSanitizer internal errors

infra/base-images/base-builder/jcc/jcc.go, infra/build/functions/target_experiment.py
Upload `JCC`'s error log to assist `OSS-Fuzz-Gen` analyzing and classifying build errors:
1. Change JCC `err.log` location, because`/out` was removed before `compile` by default and `err.log` cannot be saved there.
2. Add a step in `target_experiment.py` to upload `err.log` to gcloud bucket.
=> Change JCC error log location and upload

projects/cloud-hypervisor/project.yaml
The current 'primary_contact' email is no longer invalid. Update it with my contact information.
=> [cloud-hypervisor] Update primary_contact

projects/pygments/Dockerfile, projects/pygments/build.sh
It looks like the `pygments` build has the same toml parsing issue as I described in c3bedd8ccc24468e9c414be96e9f7cb4746aed21, i.e. the outdated `pip` was unable to parse `pyproject.toml` syntax.
But curiously, the this hasn't been an issue until the most recent (at the time of writing) build on 2024-03-30 [log](https://oss-fuzz-build-logs.storage.googleapis.com/log-8bec1e41-343e-4d95-ae29-6341c23e27af.txt) and prior builds (e.g. 2024-03-29 [log](https://oss-fuzz-build-logs.storage.googleapis.com/log-9a057fc1-c280-44d3-808f-5069c35af146.txt)) listed on https://oss-fuzz-build-logs.storage.googleapis.com/index.html#pygments seem to have been fine?
I wonder if something changed somewhere and more projects that don't upgrade pip will begin failing?
In any case, this fixes the build. Tested …
=> [pygments] Upgrade pip to fix broken build

projects/binutils/fuzz_windres.c
To prevent "file truncated" errors and resulting bfd_fatal exit, it's necessary to check both section filepos and sections size.
=> Properly check windres .rsrc section size

projects/libyaml/yaml_write_handler.h
See #11811
libyaml expects 1 for success and 0 for failure.
https://github.com/yaml/libyaml/blob/master/src/writer.c#L53-L62
if (emitter->write_handler(emitter->write_handler_data, ...) {
...
}
else {
return yaml_emitter_set_writer_error(emitter, "write error");
}
The logic is currently reverse, which (in combination of the failing check for the yaml_emitter_dump return value) caused several wrong bug reports and a CVE.
The fuzzer programs just ignore the failing yaml_emitter_dump, and so I assume it never appeared as a problem. Only in the cases where the wrongly called yaml_emitter_close ran into a case where it popped from an empty stack an overflow was detected.
The input YAML in question just had a lot of nested sequences in the form
- - - - -
which in canonical output mode resulted …
=> libyaml: Fix yaml_write_handler return values

projects/xpdf/fuzz_pdfload.cc
Currently the xpdf fuzz_pdfload fuzzer fails because the harness tries to display page zero. 
Issue #11711 highlighted this but the merged fix #11716 only fixes the first of the two loops, when both need to start at 1.
=> Fix xpdf fuzz_pdfload fuzzer

infra/build/functions/target_experiment.py
Some project (e.g. [civetweb)](https://github.com/civetweb/civetweb/blob/88dad2f6ef3857802b2aa09a3a2195d5571935bf/Makefile#L84) does not use jcc to build fuzz targets.
This pr:
1. Prevents cloud build fail at upload jcc err step.
2. Add hint text in err.log for uploading.
=> Add hint text when jcc err.log does not get created

projects/libyaml/libyaml_dumper_fuzzer.c
This is about https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=68171 and https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=68178
In both cases we have a circular reference, e.g. `&a { *a: 1 }`, which leads to a missing cleanup.
In case documents_equal returns false, the current document needs to be deleted.
This is an issue when having cyclic documents, because documents_equal calls nodes_equal, and this will recurse until a level of 1000 and then just return false.
Instead it should detect that it is processing the same node(s) over and over again, but I don't know right now how to detect this in the fuzzer code. I guess one has to keep a list somewhere.
But the memory leak can be fixed by deleting the document.
Also I moved the deletion of the document list into the error …
=> libyaml: Fix error handling

projects/libyaml/libyaml_deconstructor_alt_fuzzer.c, projects/libyaml/libyaml_deconstructor_fuzzer.c, projects/libyaml/libyaml_dumper_fuzzer.c, projects/libyaml/libyaml_emitter_fuzzer.c, projects/libyaml/libyaml_reformatter_alt_fuzzer.c, projects/libyaml/libyaml_reformatter_fuzzer.c, projects/libyaml/yaml_write_handler.h
This is about https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=68147 and https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=68320
In some testcases, the resulting output can be large.
When the output buffer is only increased by the smallest necessary amount (16384 for libyaml), that can cause a lot of calls to realloc, which gets expensive the bigger the buffer gets.
This commit will double the allocated space when it's too small, resulting in much faster processing, where previously the fuzzer ran into a 25s timeout (e.g. only 1.5s now for issue 68147).
=> libyaml: Improve buffer efficiency

projects/libredwg/build.sh
The goal is to enable fuzz introspector so further analysis can be done on libredwg.
=> libredwg: harden build in introspector mode

projects/suricata/Dockerfile, projects/suricata/build.sh
after clang update in https://github.com/google/oss-fuzz/pull/11714
Let's see how CI goes...
=> suricata: remove temporary workarounds for suricata

projects/libstdcpp/build.sh
Closes #11827
Closes #11546
Closes #11731
=> libstdcpp: Use -cxx-isystem wildcard

projects/connectedhomeip/build.sh
The clang compiler in use does not support compiling some of the thread-specific files in the SDK. However for fuzzing specifically, we are agnostic on transport at this point, so thread vs ble vs tcp/udp and others does not make a difference.
Changes:
- set `chip_enable_openthread` to false for fuzz compilation.
This should fix the build failure reported at https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=68371
=> [connectedhomeip] disable thread file compilation

projects/tinyusb/Dockerfile, projects/tinyusb/build.sh
After https://github.com/hathach/tinyusb/commit/40319ccf9de0e2981b1714c2925ca7657aecec7b
=> tinyusb: Use latest builder

projects/bignum-fuzzer/Dockerfile, projects/cryptofuzz/Dockerfile, projects/mbedtls/Dockerfile
The `development` branch of Mbed TLS will have some API-breaking changes in the next few months, in preparation for the next major release (see
https://lists.trustedfirmware.org/archives/list/mbed-tls@lists.trustedfirmware.org/thread/RHZSQLKCBOPDXS7NFKY5FATMTBYV7D5J/). To avoid breaking fuzzers, temporarily point them at the `mbedtls-3.6` long-term support branch. We will go back to fuzzing the `development` branch before the 4.0 release (https://github.com/Mbed-TLS/mbedtls/issues/9071).
Do not change ecc-diff-fuzzer because https://oss-fuzz-build-logs.storage.googleapis.com/index.html#ecc-diff-fuzzer shows that its build has been broken since 2024-01-13.
=> Switch Mbed TLS to stable branch

projects/qpid-proton/Dockerfile
This is to resolve
* https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=68175
* https://issues.apache.org/jira/browse/PROTON-2819
When trying this out locally, I noticed symptoms of https://github.com/google/oss-fuzz/issues/11698, so I also tried adding
```
RUN apt-get install -y lld && \
ln --force -s /usr/bin/lld /usr/local/bin/ld
```
In the end I noticed the following, which made me realize I am running out of disk space for docker. After redownloading docker images, the local build started working for me both with and without the above change, so for now I am not including that one
```
ld: error: /usr/local/lib/clang/15.0.0/lib/linux/libclang_rt.msan-x86_64.a: failed to parse archive: truncated or malformed archive (terminator characters in archive member "\000\000" not the correct …
```
=> qpid-proton: install python3.9 as it is required by the project

projects/inih/Dockerfile, projects/inih/build.sh, projects/inih/inihfuzz.c, projects/inih/project.yaml
Fix issue [68332](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=68332) .
=> [inih] Fix  Issue 68332 

projects/edk2/Dockerfile, projects/edk2/build.sh, projects/edk2/project.yaml
EDK2 forms the bases of the TianoCore UEFI BIOS reference implementation. Host Based Firmware Analyser (HBFA) is a build-system extension to EDK2 to allow building select code-segments for user-space fuzzing via libfuzzer, available at https://github.com/intel/hbfa-fl. We are enabling all currently functional HBFA EDK2 harnesses in this oss-fuzz integration.
=> EDK2 oss-fuzz integration with HBFA

projects/spirv-tools/Dockerfile, projects/spirv-tools/build.sh, projects/spirv-tools/generate_spirv_corpus.py
This bash script depends on src/tint/fuzzers/generate_spirv_corpus.py in the dawn repo, which was deleted with: https://dawn-review.googlesource.com/c/dawn/+/186049/5/src/tint/fuzzers/generate_spirv_corpus.py
Copy this file to the oss-fuzz repo to fix the build.
=> [spirv-tools] Fix build.sh script

infra/base-images/base-builder/jcc/jcc.go
This pr prints out the command executed with `jcc` right before the relevant error lines, if there are any, into `err.log`.
Having this extra info will help:
- oss-fuzz-gen code fixer precisely extract target error messages
- debug compile failure in more general cases
=> Write build command before error messages in jcc err.log

projects/mongo-go-driver/project.yaml
Add Steve Silvester (@blink1073), the Go Driver lead. Remove Kevin Albertson (@kevinAlbs), who is now on a different team.
=> mongo-go-driver: Add Steve and remove Kevin from CC list.

projects/gdal/Dockerfile
Not needed, as oss-fuzz ships with the current cmake
=> gdal: Remove temporary cmake workaround

projects/graphicsmagick/project.yaml
msan *is* enabled. ubsan was removed in commit https://github.com/google/oss-fuzz/commit/806d1a06206a5f6d81d5f1dc4949682dbcee30ad#diff-13a77fec79966170f568afd947cc722e3ac35a76f5159e96e051cc5eb3f24cde about three years ago.
=> graphicsmagick: Remove outdated comment

projects/libbpf/project.yaml
Hello oss-fuzz maintainers,
My name is Eduard Zingerman, I'm one of the maintainers for libbpf (see [here](https://github.com/torvalds/linux/blob/0106679839f7c69632b3b9833c3268c316c0a9fc/MAINTAINERS#L3898)).
Could you please add me to `auto_cc` list for libbpf project, the reason I'm asking: need to see details for the following two reports: [1](https://github.com/libbpf/libbpf/issues/802), [2](https://github.com/libbpf/libbpf/issues/803). As-is I get an "Access denied" page from oss-fuzz.com when I try to open the "detailed report" links.
(I am following procedure suggested [here](https://github.com/google/oss-fuzz/issues/4511), apologies if this is not the correct way to ask for access).
Best regards,
Eduard
=> Add Eduard Zingerman (eddyz87@gmail.com) to auto CC list for libbpf

projects/readstat/Dockerfile
=> readstat: Use latest builder

projects/lzma/Dockerfile, projects/lzma/build.sh, projects/lzma/project.yaml
This reverts commit ae9dd26d624ec2cd2ae1d277d62ce30e2a70e798.
There is no evidence that the LZMA SDK in 7zip was affected at all - the issue in xz was a rogue co-maintainer.
I have also fixed the copyright headers, per CI.
--
See also the discussion at https://github.com/google/oss-fuzz/pull/11805#discussion_r1565324089. I don't have an association with LZMA SDK, but noticed this when fixing up xz (for which I do have an association).
=> Revert "Disable liblzma (#11762)"

projects/edk2/project.yaml
To be able to access clusterfuzz reports fully and not just see summary emails.
=> Update primary contact email of edk2

projects/librsvg/project.yaml
- GNOME and GTK ([source](https://archlinux.org/packages/extra/x86_64/librsvg/))
- Wikipedia ([source](https://en.wikipedia.org/wiki/Librsvg#Adoption))
- I have received permission to integrate librsvg into OSS-Fuzz from a maintainer: https://gitlab.gnome.org/GNOME/librsvg/-/issues/1070#note_2078036
- The maintainer's `primary_contact` email can be seen in the commit history: https://gitlab.gnome.org/GNOME/librsvg/-/commit/ed7b9fda3dd22b4a46723b3cae7a5c9e47bd9316.patch
- I have committed to the librsvg repository: https://gitlab.gnome.org/GNOME/librsvg/-/merge_requests/954
=> librsvg: add project.yaml

projects/dulwich/Dockerfile, projects/dulwich/build.sh, projects/dulwich/project.yaml
Dulwich is a Git implementation written in Python with native extensions written with Rust. From [the Dulwich README](https://github.com/jelmer/dulwich/blob/5f0497de9c37ac4f4e8f27bed8decce13765d3df/README.rst):
> It aims to provide an interface to git repos (both local and remote) that doesn't call out to git directly but instead uses pure Python.
@jelmer is the project's maintainer and approved of this integration proposal here:  https://github.com/jelmer/dulwich/issues/1302#issuecomment-2093114061. My email is in the `auto_ccs` list so I can assist with bug triage as discussed in that same thread.
At the time of this PR, [pypistats.org](https://pypistats.org/packages/dulwich) lists the following:
- Downloads last day: 1,432,072
- Downloads last week: 7,864,024
- Downloads last month: …
=> Dulwich: Initial integration

projects/scapy/pcap_fuzzer.py, projects/scapy/project.yaml
When scapy reads pcap/pcapng files it extracts link layer types from
headers and tries to match them with classes representing those layers.
Those classes are registered in conf.l2types.num2layer when they are
imported so if no layers are imported the only known layer is Raw and it
isn't very interesting in terms of fuzzing because it just wraps bytes
without parsing anything. Apart from populating l2types when the layers
are imported they are bound to make it possible for scapy to guess
payloads and move from lower layers all the way up.
The coverage went from 24% to 39%. It can be bumped further but I think
it would be better to roll out those changes gradually.
* [scapy] fix indentation
Fixes:
```sh
projects/scapy/pcap_fuzzer.py:21:3: E111 indentation is not a multiple of 4 …
```
=> [scapy] actually fuzz protocol dissectors

infra/base-images/base-builder/jcc/jcc.go
Observing failure on building `libtasn1` with jcc, suspect this flag used in clang caused the issue.
=> Add c++ stdlib flag for clang++ only

infra/cifuzz/fuzz_target.py
It causes false positives.
Related: https://github.com/google/oss-fuzz/issues/11915
=> [cifuzz] Don't use jobs with MSAN.

projects/gnucobol/project.yaml
Note: previous fuzzing to GnuCOBOL was on invalid COBOL source files (that did found some issues that crash the parser/lexer)
That is already useful, but because the only thing that happens is that instead of a compile error the compiler crashes I didn't see a security issue there.
Much more interesting would be using input files to a COBOL program and by that either create a crash (potential denial of service) or overflow in the runtime (that would be likely a real problem).
... but in both cases I'd have no idea how to setup that for fuzzing; the only thing that is "easy" to do is to run the internal testsuite with a bunch of sanitizers.
=> new project: gnucobol

projects/igraph/project.yaml
I originally added this to make it easier to reproduce issues with Docker on Apple Silicon machines, but it broke the build. It seems OSS-Fuzz uses cross-compilation? It's possible to make this work for igraph, but I'm not ready to do it now given that aarch64 support is not even finalized in OSS-Fuzz.
=> igraph: disable aarch64

projects/cras/project.yaml
Our MSan fuzzers are falling apart. This is a result of our increased mix C + Rust usage, combined with potentially incompatible C + Rust toolchains from oss-fuzz's docker image:
> root@5d91b39ca4c8:/src# clang --version
> clang version 18.0.0 (https://github.com/llvm/llvm-project.git > d50b56d18c96e0ce462d7236eb268c54098cbaf9)
> Target: x86_64-unknown-linux-gnu
> Thread model: posix
> InstalledDir: /usr/local/bin
> root@5d91b39ca4c8:/src# rustc --version --verbose
> rustc 1.77.0-nightly (89e2160c4 2023-12-27)
> binary: rustc
> commit-hash: 89e2160c4ca5808657ed55392620ed1dbbce78d1
> commit-date: 2023-12-27
> host: x86_64-unknown-linux-gnu
> release: 1.77.0-nightly
> LLVM version: 17.0.6
Example of broken MSan builds include b/336202938 and https://crrev.com/c/5528486/4.
Let's disable MSan …
=> cras: Disable MSan

projects/nettle/Dockerfile
This ensures that the build doesn't fail due to an out of date cache.
=> Use apt-get update before installing

projects/mpv/Dockerfile, projects/mpv/build.sh, projects/mpv/project.yaml
Build all dependencies and enable memory sanitizer. With experimental flag for now, in case there are false-positives.
=> mpv: enable MSAN

projects/containerd/Dockerfile
The github.com/AdamKorcz/instrumentation package is used as part of the oss-fuzz implementation for containerd, however the dev branch is missing commits that add support for Go 1.22.
=> containerd: use main branch of instrumentation

projects/cert-manager/build.sh, projects/cert-manager/pki_fuzzer.go
This function was removed in https://github.com/cert-manager/cert-manager/pull/6994.
=> cert-manager: replace removed ParseSubjectStringToRawDERBytes function

projects/inih/inihfuzz.c
I learned a very important lesson after hours of debugging; that return value does not influence the random data generator. Instead, it influences the fuzzer core to accept the malformed data as corpus or not.
Documentation https://llvm.org/docs/LibFuzzer.html#rejecting-unwanted-inputs
=> [inih] remove fuzz blocker

projects/lxml/fuzz_html_parse.py, projects/lxml/fuzz_schematron.py, projects/lxml/fuzz_xmlschema.py, projects/lxml/test_utils.py
The fuzzer is crashing because of known exception cases which seems to be preventing Fuzz Introspector from running successfully, and making the tests less effective.
I hope the commit messages adequately describe the changes, but they should be pretty self evident from the diff regardless.
=> lxml: Update Known Exception Handling in Tests to Prevent False Positives

projects/mpv/build.sh
Should fix arbitrary DNS resolutions.
I think this is the root cause of #11958, so let's fix it. Although I'm only guessing. Everything is stuck, even sanitizer that cannot trigger DNS doesn't run, so there might be more to it.
It wasn't clear that this error causes so much trouble. There is https://oss-fuzz.com/testcase-detail/6494370936193024, but on crash statistic it says
```
Time to crash: 5916.00s
Total count: 1 
```
but if we dig into the statistic table on the actual testcase-detail page, I can see a lot of crashes. Which make sense of course.
What is little bit puzzling is that on the one log that is there, I can see it gone all the way
```
INFO: fuzzed for 5916 seconds, wrapping up soon
```
and apparently reported error after doing whole 6000 seconds. There is no detail, no more …
=> mpv: disable network

projects/connectedhomeip/project.yaml
Adding a few more CC e-mails to extend the team available to review/triage/fix these issues.
I also expect we may add a few more in time as folks responsible with matter fuzzing are ramping up.
=> Add additional CCs for accessing connectedhomeip reports

projects/connectedhomeip/project.yaml
This adds folks that are in the security incident report team outside of google - they should also have access to fuzzing reports.
=> Add additional reviewers for OSS-fuzz reports for CHIP

infra/build/functions/target_experiment.py
Add a 3-hour timeout to `target_experiment.py`, which should be more than enough given fuzzing timeout is 30 minutes and most successful cloud builds finish in 2.5 hours empirically.
=> Add timeout for `target_experiment.py`

projects/coveragepy/project.yaml
Ref: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=69058#c5
=> coveragepy: set no view restrictions

projects/envoy/build.sh
Envoy's UBSAN build current fails with the following error:
```
[1A[K[31m[1mERROR: [0m/src/envoy/test/common/router/BUILD:233:21: Linking test/common/router/config_impl_test_static failed: (Exit 1): clang-18 failed: error executing command (from target //test/common/router:config_impl_test_static) 
Step #23 - "compile-libfuzzer-undefined-x86_64":   (cd /root/.cache/bazel/_bazel_root/4e9824db8e7d11820cfa25090ed4ed10/execroot/envoy && \
Step #23 - "compile-libfuzzer-undefined-x86_64":   exec env - \
Step #23 - "compile-libfuzzer-undefined-x86_64":     BAZEL_COMPILER=clang \
Step #23 - "compile-libfuzzer-undefined-x86_64":     BAZEL_CXXOPTS='-stdlib=libc++' \
Step #23 - "compile-libfuzzer-undefined-x86_64":     BAZEL_LINKLIBS=-l%:libc++.a:-l%:libc++abi.a \
Step #23 - …
```
=> [envoy] fix clang18 libclang_rt linkage issue

projects/speex/project.yaml
@jmvalin is the original author of speex so should have access to oss-fuzz issues.
=> speex: add cc

projects/libvips/Dockerfile
This became redundant after a2c60af93357f2053a45816fcdefdfc02206b64f.
---
Note that the failing introspector build was fixed via these commits:
https://github.com/libvips/libvips/commit/ee482ca49caafba89abe60fd8d361d0a00355096
https://github.com/libvips/libvips/commit/a9e161f04aae213e113e6ea551c704d5420cfd90
https://github.com/libvips/libvips/commit/18031970f70c00fe1ed56d85270ff80b454dfd71
6e1045e09968c5b45c08656bc669d5a20d205ea1
=> libvips: remove OLD_LLVMPASS variable

projects/lxml/fuzz_sax.py, projects/lxml/fuzz_schematron.py
The changes here update the `fuzz_sax` test harness to gracefully handle a documented exception so the fuzzer will not exit when the exception is raised. This PR also removes the special case handling in `fuzz_schematron.py` for a bug in `lxml.isoschematron.Schematron` that has been fixed.
The `IndexError` raised in `src/lxml/sax.py` is a known bug with an issue marked as low priority in lxml's bug tracker since  2023-03-14: https://bugs.launchpad.net/lxml/+bug/2011542
The unhandled `KeyError`  bug in the `lxml.isoschematron.Schematron` class that was previously identified by fuzzing has been fixed upstream via: https://github.com/lxml/lxml/pull/423.
=> [lxml] Update Known Exception Handling to Unblock Fuzzing

projects/g-api-python-tasks/Dockerfile, projects/g-api-python-tasks/build.sh, projects/g-api-python-tasks/fuzz_cloudtask_client.py, projects/g-api-python-tasks/project.yaml
Fixes [Monorail Issue 62914][Monorail-issue]. The
https://github.com/googleapis/python-tasks repository was archived on
2024-02-01 and the project was moved to the `google-cloud-tasks` package
in the https://github.com/googleapis/google-cloud-python repository.
The upstream migration removed the source code from the original repo,
resulting in the broken build.
[Monorail-issue]: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=62914
See a3f475e91fcd730b889d5f6204751a5ca813897b
See 275368c90813e33e5e2c8bd4d78ed5394d4a7da6
- #12014
- #12015
=> [g-api-python-tasks] Update Project Repo to Fix Build

projects/gc-iam/Dockerfile, projects/gc-iam/build.sh, projects/gc-iam/fuzz_credentials.py, projects/gc-iam/project.yaml
Fixes [Monorail Issue 61581][Monorail-issue].
The https://github.com/googleapis/python-iam repository was archived on 2023-10-26 and the project was moved to the `google-cloud-iam` package in the https://github.com/googleapis/google-cloud-python repository.
The upstream migration removed the source code from the original repo, resulting in the broken build.
[Monorail-issue]: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=61581
- #12015
- #12016
Native extensions used by this project were not being instrumented despite the environment variables set in `build.sh` because `pip` was downloading prebuilt binaries instead of building them with appropriate flags. The result was reduced fuzzer efficacy for ASAN runs and little to no value for UBSAN runs.
This is fixed by building …
=> [gc-iam] Update Project Repo & Fix Build Issues

projects/g-api-resource-manager/Dockerfile, projects/g-api-resource-manager/build.sh, projects/g-api-resource-manager/fuzz_tag_values_client.py, projects/g-api-resource-manager/project.yaml
Fixes [Monorail Issue 59721][Monorail-issue]. The
https://github.com/googleapis/python-resource-manager repository was archived on
2023-09-05 and the project was moved to the `google-cloud-resource-manager` package
in the https://github.com/googleapis/google-cloud-python repository.
The upstream migration removed the source code from the original repo,
resulting in the broken build.
[Monorail-issue]: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=59721
See 9a8989bf73899b232ac16f970dfa9bf72a8904bb
See d33e0a4156132bbc4293f8169aba415cd21bd075
- #12014
- #12016
=> [g-api-resource-manager] Update Project Repo to Fix Build

projects/libxml2/Dockerfile
Try to fix build failure on aarch64.
=> libxml2: Don't install i386 packages on aarch64

projects/mpv/project.yaml
According to the documentation [1] and oss-fuzz source [2] it should be
enabled by default. But in fact it is not enabled by default on the
ClusterFuzz [3] and only projects that explicity enable Centipede are using
this engine.
[1] https://google.github.io/oss-fuzz/getting-started/new-project-guide/#fuzzing_engines
[2] https://github.com/google/oss-fuzz/blob/b07cc908abf97529a95a4dd9b3d152bf4f101e71/infra/build/functions/build_project.py#L47
[3] https://github.com/google/clusterfuzz/blob/22e11083b540518248d512141c45c25c7f560f2e/src/clusterfuzz/_internal/cron/project_setup.py#L204
See-Also: https://github.com/google/oss-fuzz/issues/11964
=> mpv: explicitly enable Centipede

projects/cpython3/project.yaml, projects/python3-libraries/project.yaml
@sethmlarson - Seth is the security developer in residence for CPython at the PSF.  He makes sense as the primary contact.
Stop using my former employers account as my oss-fuzz address given that they kicked our team out for being too valuable.
=> Make Seth the primary cpython3 oss-fuzz contact.

projects/mdbook-i18n-helpers/project.yaml
[mdbook-i18n-helpers](https://github.com/google/mdbook-i18n-helpers/) is a plugin for [mdbook](https://rust-lang.github.io/mdBook/) which enables localization support.
According to [crates](https://crates.io/crates/mdbook-i18n-helpers), it was downloaded ~100k times.
The project already defines [several fuzzers within its repo](https://github.com/google/mdbook-i18n-helpers/tree/main/fuzz).
I am one of the maintainers of the project. The main maintainer @mgeisler  approves of this request as can be seen from https://github.com/google/mdbook-i18n-helpers/issues/83.
=> mdbook-i18n-helpers: Initial integration

infra/base-images/base-runner/jacoco_report_converter.py
There are 2 bugs in the jacoco_report_converter.py in which the src_file and src_path are redefined and overwritten in the loop. These bugs cause both of them to empty after the first iteration. This makes the resulting JSON report summary only contain the first filename to process. This has been mentioned in #11966.
This PR proposes a fix by changing the name of the needed variables. Also, this PR adds in a filter to exclude fuzzer classes in the coverage information as they are not part of the projects. The updated script will include the coverage information for each class that existed in the project source directory (`/out/src`) in the summary tag of the resulting summary.json report.
=> [infra] Fix jacoco_report_converter.py

projects/libcups/Dockerfile, projects/libcups/build.sh, projects/libcups/project.yaml
The OpenPrinting Team is integrating C-based projects into the OSS-Fuzz Framework. The maintaining fuzz harnesses locate in OpenPrinting project [fuzzing](https://github.com/OpenPrinting/fuzzing). 
This PR contains the initial integration config for OpenPrinting project libcups.
CC: @tillkamppeter @iosifache
=> [libcups] Init integration

docs/getting-started/continuous_integration.md, infra/cifuzz/external-actions/run_fuzzers/action.yml
=> Fix doc timeouts and ooms and allow these options in GH Action

projects/libtorrent/Dockerfile, projects/libtorrent/build.sh
as newer compilers have deprecated some features used by old boost. Specifically:
```
/src/boost/boost/container_hash/hash.hpp:131:33: error: no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
131 |         struct hash_base : std::unary_function<T, std::size_t> {};
|                            ~~~~~^~~~~~~~~~~~~~
|                                 __unary_function
```
=> use `apt` boost package to build libtorrent

projects/lxml/build.sh, projects/lxml/fuzz_sax.py, projects/lxml/fuzz_schematron.py
Adds additional handling for shallow errors that prematurely halt fuzzer runs.
Fixes an issue preventing Pyinstaller from properly bundling `lxml.isoschematron`. The issue fixed here can be seen in the build logs (e.g, [the most recent one](https://oss-fuzz-build-logs.storage.googleapis.com/log-c5377ff0-29ca-4541-bda2-1159016ec4a6.txt)) by `grep`ing for the string `Failed to collect submodules`
---
More details about these changes can be found in their respective commit messages.
=> [lxml] Fix Pyinstaller Bundling Error & Add More Graceful Handling for Shallow Errors

projects/scapy/pcap_fuzzer.py
It's kind of a follow-up to https://github.com/secdev/scapy/pull/4381 ans should help to catch issues like that going forward.
@gpotter2 @guedou @p-l- could you take a look?
(I think ideally it would be nice to move the fuzz target to the scapy repository where it could be changed and reviewed without having to open PRs here)
=> [scapy] poke Packet.summary()

infra/cifuzz/actions/run_fuzzers/action.yml
With disabled option `report-oom` in GH Action Github reports a warning:
"Unexpected input(s) 'report_ooms', valid inputs are ['entryPoint', 'args', 'language', 'fuzz-seconds', 'dry-run', 'sanitizer', 'mode', 'github-token', 'storage-repo', 'storage-repo-branch', 'storage-repo-branch-coverage', 'report-unreproducible-crashes', 'minimize-crashes', 'parallel-fuzzing', 'output-sarif']".
The patch follows up commit a7c524dca08b ("Fix doc timeouts and ooms and allow these options in GH Action (#12003)").
=> Allow timeout and OOMs options in GH Action (#12003)

projects/bc-gh/project.yaml
The FAQ [says][1] that projects can be accepted if they "have a critical impact on infrastructure and user security," with the following two explicit criteria:
* Exposure to remote attacks
* Number of users/other projects depending on this project.
This bc/dc is locked down, and the exposure to remote attacks should be extremely low. So I understand if this project is not accepted.
However, it is shipped by default in [Android][2], [FreeBSD][3], and [macOS][4], so it is critical to other projects that are used widely.
It is already [set up for fuzzing][5], but as a single maintainer, I do not have the resources to fuzz it all of the time and ask for Google's help since Google ships this bc/dc in Android.
[1]: https://google.github.io/oss-fuzz/faq/#what-kind-of-projects-are-you-accepting …
=> Add Gavin Howard's bc/dc as bc-gh

projects/scapy/project.yaml
to let the latest builds be more or less in sync with the upstream repository. It should help CIFuzz to detect known issues better among other things.
=> [scapy] build it more often

infra/base-images/base-builder/Dockerfile, infra/base-images/base-builder/jcc/build_jcc.bash, infra/base-images/base-builder/jcc/jcc.go, infra/base-images/base-builder/jcc/jcc2.go, projects/skcms/Dockerfile
Instead of rebuilding the entire project every time we want to compile a single fuzz target, a better workflow is to build the project once and somehow compile the target against the already compiled project code.
This POC does that by interrupting building in when it detects it is compiling the fuzz target.
On detection it does the following:
1. Writes the command to /out/statefile TODO: write the cwd.
2. Commits the current container as "frozen" for use later. TODO: make this changeable.
3. Returns 1 so compilation stops. TODO: It would be better to exit the container.
This step may be important to prevent clean up of the environment.
Then the frozen container can be used to compile fuzz targets against the project without recompiling the project in its entirety.
TODO:
1. Support this …
=> POC: Speed up compilation by freezing container during compilation.

projects/mpv/build.sh
Workarounds the issue where compile tests would fail with
`-Werror=ignored-optimization-argument` because Meson doesn't allow
linker flags in `CFLAGS` or `CXXFLAGS`.
See: https://github.com/mesonbuild/meson/issues/6377#issuecomment-575977919
Thanks to @evverx for the idea:
https://github.com/google/oss-fuzz/pull/7583#issuecomment-1104011067
This is a fragile workaround, but it looks like there isn't much else we
can do.
=> mpv: fix introspector build

projects/cairo/Dockerfile
The build currently fails with the following error:
```
+ meson setup --prefix=/work/prefix --libdir=lib --default-library=static _builddir
The Meson build system
Version: 1.2.0
Source dir: /src/cairo
Build dir: /src/cairo/_builddir
Build type: native build
meson.build:2:17: ERROR: Meson version is 1.2.0 but project requires >= 1.3.0
A full log can be found at /src/cairo/_builddir/meson-logs/meson-log.txt
```
=> [cairo] Use meson 1.3 to fix build

projects/hdf5/Dockerfile, projects/hdf5/project.yaml
Work around:
```
+ /src/aflplusplus/afl-clang-fast++ -O1 -fno-omit-frame-pointer -gline-tables-only -Wno-error=enum-constexpr-conversion -Wno-error=incompatible-function-pointer-types -Wno-error=int-conversion -Wno-error=deprecated-declarations -Wno-error=implicit-function-declaration -Wno-error=implicit-int -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -stdlib=libc++ /usr/lib/libFuzzingEngine.a h5_read_fuzzer.o ./build-dir/bin/libhdf5.a -lz -o /out/h5_read_fuzzer
/usr/bin/ld: /usr/bin/ld: DWARF error: invalid or unhandled FORM value: 0x25
./build-dir/bin/libhdf5.a(H5Tconv_integer.c.o): in function `H5T__conv_schar__Float16':
H5Tconv_integer.c:(.text.H5T__conv_schar__Float16[H5T__conv_schar__Float16]+0xe77): undefined reference to …
```
=> hdf5: Use latest builder / Temp disable afl

infra/base-images/base-clang/Dockerfile, infra/base-images/base-clang/checkout_build_install_llvm.sh
clang/llvm are only bumped on a manual basis, due to requiring a full infra build. Thus, remove the code to support the rolling chromium nightly clang.
Also, extend the docs around `CMAKE_VERSION`. The removal of the docs around `FORCE_OUR_REVISION` also remove the mention of https://github.com/google/oss-fuzz/issues/7273, so this also fixes https://github.com/google/oss-fuzz/issues/7273.
=> infra: [NFC] Consolidate LLVM_REVISION and OUR_LLVM_REVISION

projects/bc-gh/Dockerfile, projects/bc-gh/build.sh, projects/bc-gh/project.yaml
I set `disabled` to true because LeakSanitizer claims the fuzzers have leaks. However, this is not true because bc and dc run without leaks under Valgrind.
After some debugging, I can cause them to free the memory by putting an `assert(false);` after all of the frees [1] [2], and it trips. But if I remove it, LeakSanitizer sees leaks.
Whether it's PEBKAC (probably) or miscompilation (unlikely), I don't know, but I figured I'd commit the necessary stuff for the project.
I'll try to figure out the problem later.
[1]: https://github.com/gavinhoward/bc/blob/master/src/bc_fuzzer.c#L110
[2]: https://github.com/gavinhoward/bc/blob/master/src/dc_fuzzer.c#L110
=> bc-gh: Add Dockerfile and build.sh

projects/quickjs/Dockerfile, projects/quickjs/build.sh
The original corpus of QuickJS consisted of a few large files that were too complex; some contained benchmarks, others had tests spread across multiple files or were scattered with assertions. The new corpus was created by breaking down and transforming these tests into smaller, fuzzing-optimized pieces.
=> QuickJS: Switch to a corpus optimized for fuzzing

projects/libavif/Dockerfile
Fixed by https://github.com/AOMediaCodec/libavif/commit/3dee1bb26136a1327966fcf40034d53053b2d3b0 Fixes https://github.com/AOMediaCodec/libavif/issues/2207
=> libavif: unpin base builder

projects/libwebp/project.yaml
This is because tests have been migrated to fuzztest
=> libwebp: restrict fuzzers to libfuzzer

infra/base-images/base-builder-rust/Dockerfile, infra/base-images/base-builder/install_rust.sh, projects/crosvm/build.sh, projects/gitoxide/build.sh, projects/linkerd2-proxy/build.sh, projects/naga/build.sh, projects/opendal/build.sh, projects/opensk/build.sh, projects/wasmtime/build.sh
This commit updates the default version of Rust installed for fuzzing to
the last nightly of Rust that used LLVM 17. The next version uses LLVM
18.1.7 which is incompatible with the fuzz infrastructure's own LLVM
which is currently 18.0.0. This is intended to update the Rust toolchain
as far as possible without causing coverage incompatibilities.
This additionally updates a few pinned projects to all use this nightly
as well. Furthermore the containers are now configured to by-default
ignore `rust-toolchain` and `rust-toolchain.toml` files which will force
this particular toolchain to be used.
=>  Update default Rust to nightly-2024-02-12 

projects/librsvg/Dockerfile, projects/librsvg/build.sh
This bump fixes the leak reported in OSS-Fuzz issue 69700.
Previously, libxml2 2.12.6 was being pulled in as a subproject of Fontconfig (via Cairo).
=> librsvg: bump libxml2 to 2.13.1

projects/libavif/project.yaml
This is because tests will be fully migrated to fuzztest
=> libavif: restrict fuzzers to libfuzzer

projects/libxls/build.sh
The `bootstrap` script has been moved to `autogen.sh`
https://github.com/libxls/libxls/commit/c1efc44e09bb49894c2199b7cc3262b61885a2ef
=> libxls: Update build.sh

infra/base-images/base-builder/jcc/jcc.go
Some projects failed to compile because its compilation command escalates warnings into errors (e.g., [`bind9`](https://llm-exp.oss-fuzz.com/Result-reports/scheduled/2024-06-21-weekly-all/benchmark/output-bind9-dns_view_asyncload/index.html)). This is particularly problematic for C projects because `JCC` assumes these errors are due to C/C++ compatibility issues and then compiles these projects with `clang++`, which causes different failures that LLM cannot fix (e.g., in `bind9`, the error is caused by other files using C symbols that are not available in C++).
This PR removes all flags that may cause this problem in all compilation commands.
When tested locally, it fixed the compilation error in `bind9` (with some manual fix on the fuzz target).
----
Here is the command that contains …
=> Remove flags that may escalate warnings to errors

docs/advanced-topics/code_coverage.md
Some example Rust projects that are already using this functionality:
https://github.com/google/oss-fuzz/blob/7dc680836c9d99a5e1839ca07f60874654727bc8/projects/askama/project.yaml#L11-L13
https://github.com/google/oss-fuzz/blob/7dc680836c9d99a5e1839ca07f60874654727bc8/projects/gitoxide/project.yaml#L12-L13
https://github.com/google/oss-fuzz/blob/7dc680836c9d99a5e1839ca07f60874654727bc8/projects/wasmer/project.yaml#L15-L16
=> doc: add rust to list of languages that support llvm-cov arguments

projects/librsvg/project.yaml
Example report that would be improved:
https://storage.googleapis.com/oss-fuzz-coverage/librsvg/reports/20240625/linux/report.html
=> librsvg: exclude third-party code from coverage reports

projects/mpv/build.sh
Micro optimization, we don't need them in build dir anymore.
=> mpv: move artifacts to $OUT, instead of copying

projects/capstone/Dockerfile, projects/capstone/build.sh
Upstream has ended python2 support. When removing python2 compatibility code, it was noticed that oss-fuzz was still utilizing this support. This fixes that by moving to a supported version of python3.
See this PR: https://github.com/capstone-engine/capstone/pull/2378
=> Upgrade capstone to use python3

projects/mpv/project.yaml
Also remove experimental flag for MSAN.
=> mpv: ignore third-party dependencies in the coverage report

projects/librsvg/build.sh
This should reduce the frequency of OSS-Fuzz issue 69462.
=> librsvg: build dependencies with -O1 to avoid fuzzer timeouts

projects/libarchive/build.sh, projects/libarchive/libarchive_fuzzer.cc
This fixes a major harness issue in the `libarchive` fuzzer and resolves a fuzzing roadblock issue related to the build setup.
All calls after `archive_read_add_passphrase` currently exit early because the decoder state is marked as invalid due to incorrect API usage.
When combined with https://github.com/libarchive/libarchive/pull/2229, this should improve coverage from ~15% to >45%.
While the harness issue [regressed](https://github.com/google/oss-fuzz/pull/9452#issue-1538189000) at some point, it seems like the CRC build flag issue was always present in oss-fuzz's libarchive setup.
Thanks!
=> libarchive: fix harness and improve build setup

projects/wasmer/Dockerfile, projects/wasmer/build.sh
Reverting rust pin as  https://github.com/wasmerio/wasmer/issues/4445 has been fixed.
=> wasmer: revert rust pin

projects/sound-open-firmware/Dockerfile, projects/sound-open-firmware/build.sh, projects/sound-open-firmware/fetch-sdk.sh
This doesn't get as much attention as it should, fixups to recover oss-fuzz output:
1. The Zephyr SDK 0.16.1 probably still works from a year ago, but the fetch URL scheme changed so we'll never know.  Implement some horrible hackery to extract the "latest" version of the SDK at docker time so (absent more changes to the releases URLs) we stay current.
2. The build.sh was my original hack with manual kconfig settings, which have skewed vs. the app as it evolved and don't build anymore.  SOF has fuzzing implemented as a first class tool now (and even run it in their CI), so just use the official script which we can rely on being maintained.
=> sound-open-firmware: SOF integration has bitrotten.  Revive it.

infra/base-images/all.sh, infra/base-images/base-builder-ruby/Dockerfile, infra/base-images/base-builder-ruby/ruzzy-build, infra/base-images/base-builder/Dockerfile, infra/base-images/base-builder/install_ruby.sh, infra/base-images/base-runner/Dockerfile, infra/base-images/base-runner/run_fuzzer, infra/base-images/base-runner/ruzzy, infra/constants.py, projects/ox-ruby/Dockerfile, projects/ox-ruby/build.sh, projects/ox-ruby/fuzz_parse.rb, projects/ox-ruby/fuzz_sax_parse.rb, projects/ox-ruby/project.yaml
This is a follow-up to the discussions held during our Monthly Fuzzing Collaboration meetings and directly relates to issue #11967.
This Pull Request integrates Ruzzy support for Ruby fuzzing into OSS-Fuzz. Ruzzy is a coverage-guided fuzzer for pure Ruby code and Ruby C extensions, developed by Matt (@mschwager) at Trail of Bits. More information on Ruzzy can be found in the blog post titled "[Introducing Ruzzy, a coverage-guided Ruby fuzzer](https://blog.trailofbits.com/2024/03/29/introducing-ruzzy-a-coverage-guided-ruby-fuzzer/)".
The first commit of this PR integrates Ruby support into the OSS-Fuzz project via Ruzzy, while the second one includes the Ox project as an example of its usage.
The first commit introduces changes in the infra directory, most notably by adding the …
=> Adding Ruby Support into OSS-Fuzz via Ruzzy

projects/ndpi/project.yaml
=> nDPI: exclude custom mutator code from coverage report

.github/workflows/codeql-analysis.yml, .github/workflows/infra_tests.yml, .github/workflows/pr_helper.yml, .github/workflows/presubmit.yml, .github/workflows/project_tests.yml
When my other pr was running i noticed 
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v3, actions/setup-go@v4, actions/github-script@v6. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
At the end of the Summary.  I have updated those actions in all workflows using them.
=> Update several github action to node20 verisons

projects/xbps/project.yaml
The xbps project's homepage and main_repo entries were previously listed as https://github.com/voidlinux/xbps, which leads to a 404 page. This commit changes them to instead point to https://github.com/void-linux/xbps, which is correct.
=> Update xbps homepage and main_repo in project.yaml

infra/base-images/base-clang/Dockerfile
Various improvements focused on oss-fuzz-gen
=> infra: update fuzz introspector

projects/leveldb/build.sh, projects/leveldb/fuzz_db.cc
`std::filesystem` is only guaranteed to be in C++17, so select that consistently for this project.
Ref: https://oss-fuzz-gcb-logs.storage.googleapis.com/log-e7599eac-65b6-45fd-bc0d-1deec0235cea.txt
```
Step #21 - "compile-afl-address-x86_64": [100%] Built target leveldbutil
Step #21 - "compile-afl-address-x86_64": + for fuzzer in fuzz_db
Step #21 - "compile-afl-address-x86_64": + /src/aflplusplus/afl-clang-fast++ -O1 -fno-omit-frame-pointer -gline-tables-only -Wno-error=enum-constexpr-conversion -Wno-error=incompatible-function-pointer-types -Wno-error=int-conversion -Wno-error=deprecated-declarations -Wno-error=implicit-function-declaration -Wno-error=implicit-int -Wno-error=vla-cxx-extension …
```
=> leveldb: consistently use c++17

projects/pcl/Dockerfile
(See https://oss-fuzz-gcb-logs.storage.googleapis.com/log-c8129390-51e0-43e3-9c21-3952f5592a17.txt for the full failing log)
=> pcl: Bump boost

projects/monero/Dockerfile
=> monero: Use latest builder

projects/suricata/Dockerfile, projects/suricata/build.sh
cf https://oss-fuzz-build-logs.storage.googleapis.com/log-15fe5b44-39aa-4f14-86e8-11086ea4c4f1.txt
=> suricata: use latest jansson release from github

projects/openweave/build.sh
See https://oss-fuzz-gcb-logs.storage.googleapis.com/log-7213ec9e-cac7-4eec-bd21-472547b52220.txt
```
Step #21 - "compile-libfuzzer-coverage-x86_64":   CXXLD    TestBinding
Step #21 - "compile-libfuzzer-coverage-x86_64":   CXXLD    TestEventLogging
Step #21 - "compile-libfuzzer-coverage-x86_64":   CXXLD    TestInetLayer
Step #21 - "compile-libfuzzer-coverage-x86_64": clang++: [0;1;31merror: [0m[1munable to execute command: Killed[0m
Step #21 - "compile-libfuzzer-coverage-x86_64": clang++: [0;1;31merror: [0m[1mlinker command failed due to signal (use -v to see invocation)[0m
Step #21 - "compile-libfuzzer-coverage-x86_64": make[4]: *** [Makefile:4371: TestWeaveCert] Error 1
Step #21 - …
```
=> openweave: Avoid OOM in make -j

projects/qemu/Dockerfile, projects/qemu/build.sh
qemu requires a newer version of glib than that which is packaged with oss-fuzz' version of Ubuntu
=> qemu: build glib manually

infra/base-images/base-builder/install_rust.sh
Helps pin dependencies at the time of when `cargo-fuzz` itself was published to avoid dependency updates breaking builds. This fixes a current issue where all Rust projects using `cargo fuzz` are broken due to the installation of `cargo-fuzz` failing due to failing to build a newer dependency with an older nightly.
Closes #12168
=> Add `--locked` to installation of `cargo fuzz`

projects/librsvg/Dockerfile
The nightly in the base image is too old to compile serde.
This change will break coverage reports until LLVM is updated on the base image.
=> librsvg: use a recent nightly compiler to fix the build

projects/lima/Dockerfile, projects/lima/FuzzLoadYAMLByFilePath.go, projects/lima/build.sh, projects/lima/project.yaml
Lima is a CNCF-hosted project with nearly 15k stars. Lima is a core component in several open-source alternatives to Docker Desktop including:
- Rancher Desktop. Rancher is widely used by many enterprises including T Mobile, Home Depot, Intel, Samsung and Siemens. Rancher has an open source product called Rancher Desktop that allows users to manage containers and Kubernetes on their desktop.
- Finch: An open source client for container development [released by AWS](https://aws.amazon.com/blogs/opensource/introducing-finch-an-open-source-client-for-container-development/). 
- Podman: Podman is a popular alternative to Docker, and Lima is a core component of their desktop product Podman Desktop.
____________________________
This PR adds initial fuzzing integration for the Lima project: …
=> lima: initial integration

projects/arrow/Dockerfile, projects/arrow/build.sh
=> arrow: Use latest builder

projects/python-multipart/Dockerfile, projects/python-multipart/build.sh, projects/python-multipart/multipart.patch
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=67660 (Fuzz-Blocker)
This is a temp fix, till https://github.com/Kludex/python-multipart/pull/141 lands.
=> python-multipart: fix fuzz blocker

projects/libhtp/Dockerfile, projects/libhtp/multiple.txt
Cf https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=70200#c2
Found with `git grep RUSTUP_TOOLCHAIN`
=> Libhtp rust build fix

projects/giflib/project.yaml
This is to direct OSS-Fuzz-gen away from non-interesting targets
=> giflib: ignore LPM coverage

projects/xerces-c/project.yaml
This is causing deflection for oss-fuzz-gen
=> xerces-c: ignore LPM in coverage reports

projects/binutils/fuzz_disas_ext.c, projects/binutils/fuzz_disassemble.c
private_data is supposed to be private to the disassembler.  It isn't valid to supply random private_data as an input, as was done in commit c7f7c24040.  One other reason for that change was presumably so that the arm disassembler took notice of the "mach" value supplied.  The correct way to do that is by setting USER_SPECIFIED_MACHINE_TYPE in disassemble_info.flags, which is what this patch does both for fuzz_disas_ext.c and fuzz_disassemble.c.  I've also removed random bytes_per_chunk input, also not a valid input, and corected the offset in Data for the start of insns.
=> Fix issue 59779

infra/helper.py
`coverage_extra_args` are currently only used in cloud builds e.g. https://github.com/google/oss-fuzz/blob/7db2eae0b12d30e14112a1b41aada627dd6de0a0/infra/build/functions/build_and_run_coverage.py#L128 and not locally. Besides being confusing, this can cause some issues with e.g. OSS-Fuzz-gen which relies on the `coverage` command to extract coverage reports, as it may end up comparing apples to oranges.
This commit fixes it by applying the coverage extra args when coverage is run by way of `infra/helper.py coverage`.
=> infra: apply coverage ignores when running locally

infra/helper.py
There's a bit more to reading the coverage extra args in https://github.com/google/oss-fuzz/pull/12229. We need to essentially pass the whole yaml value. This fixes it.
Fixes: https://github.com/google/oss-fuzz/issues/12251
Fixes: https://github.com/google/oss-fuzz/issues/12252
=> helper: fix coverage extra args reading

projects/cilium/Dockerfile, projects/cilium/build.sh
Files copied to /out during image creation seem to get hidden by a volume mounted at /out when building the fuzzers.
Similar issues:
- https://github.com/google/oss-fuzz/pull/12254
- https://github.com/google/oss-fuzz/pull/12250
- https://github.com/google/oss-fuzz/pull/12259
=> cilium: fix seed corpus placement

projects/llvm/build.sh
This was disabled in d154d875ada04e4edeb1f9a9f1f13f1f826c11ff to fix a build issue in LLVM. That build issue was just
[fixed](https://github.com/llvm/llvm-project/pull/99871) and this patch reenables the dict generation.
=> llvm: Re-enable dictionary builder

projects/pygments/Dockerfile, projects/pygments/build.sh
Files copied to /out during image creation seem to get hidden by a volume mounted at /out when building the fuzzers.
Similar issues:
- https://github.com/google/oss-fuzz/pull/12254
- https://github.com/google/oss-fuzz/pull/12250
=> pygments: fix dictionary placement

projects/connectedhomeip/Dockerfile
- this fixes docker build failure, due to bug introduced by update of [setuptools](https://pypi.org/project/setuptools/) python package to version 71
- the bug is described here: https://github.com/pypa/setuptools/issues/4483
- fix involves upgrading `packaging` to latest possible version, which fixes issue
=> [CHIP project] fix setuptools bug

projects/wasmtime/Dockerfile
The build of Wasmtime failed last night due to changes in the upstream installation script of OCaml so attempt to resolve the issues with the installation of `pkg-config`. I've tested locally that the build fails before this was installed and passes after it's installed.
=> wasmtime: Install `pkg-config` in build container

projects/rnp/build.sh, projects/rnp/project.yaml
This PR updates used Botan version to 3.5.0 and limits number of built modules for performance reasons.
=> [rnp] Update to Botan 3.5.0

projects/solidity/Dockerfile
See https://oss-fuzz-gcb-logs.storage.googleapis.com/log-97a29aa7-6149-4c95-8428-5de204bd2214.txt
```
Step #21 - "compile-afl-address-x86_64": + cd /src/solidity/build
Step #21 - "compile-afl-address-x86_64": + CXXFLAGS='-O1   -fno-omit-frame-pointer   -gline-tables-only   -Wno-error=enum-constexpr-conversion   -Wno-error=incompatible-function-pointer-types   -Wno-error=int-conversion   -Wno-error=deprecated-declarations   -Wno-error=implicit-function-declaration   -Wno-error=implicit-int   -Wno-error=vla-cxx-extension   -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope  -stdlib=libc++ -I/usr/local/include/c++/v1'
Step #21 - "compile-afl-address-x86_64": + cmake …
```
=> solidity: Bump boost

projects/librsvg/Dockerfile, projects/librsvg/build.sh
.options files copied to /out during image creation seem to get hidden by a later volume mount to /out.
=> librsvg: fix leak suppression

projects/bleach/Dockerfile, projects/bleach/build.sh
Files copied to /out during image creation seem to get hidden by a volume mounted at /out when building the fuzzers.
I noticed this general issue while testing https://github.com/google/oss-fuzz/pull/12250.
=> bleach: fix dictionary copying

projects/boost/Dockerfile, projects/boost/build.sh
Full log: https://oss-fuzz-gcb-logs.storage.googleapis.com/log-49527212-a452-4fff-aaa5-293bf0924395.txt
=> boost: Use latest builder

projects/prost/project.yaml
Fixes #12209
Updated the information in  https://github.com/google/oss-fuzz/blob/master/projects/prost/project.yaml
=> (Fixed) Prost information out of date

projects/ffmpeg/Dockerfile, projects/ffmpeg/build.sh, projects/ffmpeg/project.yaml
Numerous changes and improvements have been made:
- Build zlib and bzip2 instead of bundling .so files
- Remove no longer needed patchelf
- Build libass and its dependencies
- Remove libva and libvdpau; they are not tested and are unlikely to be tested without a mock driver
- Clean installed apt packages in the build image. Remove duplicated packages and unnecessary libraries
- Add meson CFLAGS workaround for #12167
- Disable ASM as the code cannot be instrumented
- Use the latest build image, possible after the above changes
- Enable Centipede
=> ffmpeg: enable MSAN

projects/neomutt/build.sh
This is to make the process faster for oss-fuzz-gen
=> neomutt: speed up build

projects/librsvg/render_document.options
libFuzzer is still reporting leaks when run with -detect_leaks=0, so we now set ASAN_OPTIONS="detect_leaks=0" as well.
=> librsvg: set detect_leaks=0 in ASAN_OPTIONS

projects/gitpython/project.yaml
Removed a dot (`.`) from @EliahKagan's Gmail address that we suspect is preventing him from being able to properly authenticate on Monorail, thus blocking his access to undisclosed bugs he should be able to view for the GitPython project.
Ref: https://github.com/gitpython-developers/GitPython/discussions/1947
=> [GitPython] Update Project Contributor's Email in Auto-CC List

projects/pacemaker/build.sh
Pacemaker recently added support for OSS-Fuzz. This PR updates `projects/pacemaker/build.sh` to handle a change in where the project keeps fuzzer source.
=> Update fuzzer source location for Pacemaker

projects/opentelemetry/Dockerfile, projects/opentelemetry/build.sh, projects/opentelemetry/project.yaml
OpenTelemetry is a collection of APIs, SDKs, and tools to instrument, generate, collect, and export telemetry data (metrics, logs, and traces). It is a CNCF-hosted project that is adopted by companies like eBay, GitHub, Shopify, Skyscanner [and many others](https://opentelemetry.io/ecosystem/adopters/).
=> opentelemetry: initial integration

projects/ffmpeg/project.yaml
It is not stable, there are multiple bus errors:
Step #22 - "build-check-centipede-none-x86_64":
/usr/local/bin/run_fuzzer: line 227: 172132 Bus error (core dumped) bash -c "$CMD_LINE"
Disable it for now, to let other recent changes take effect, we can revisit it later.
Fixes: 0318a945e1399771083778242866db369ad06900
=> ffmpeg: disable Centipede again

projects/bitcoin-core/build_cryptofuzz.sh
This option was renamed in https://github.com/bitcoin-core/secp256k1/pull/1058, resulting in `configure: WARNING: unrecognized options: --with-ecmult-gen-precision`.
Update the option and change the values.
Also add `--enable-option-checking`, so that it'll be harder for this to happen in future. See:
https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.72/html_node/Option-Checking.html.
=> bitcoin-core: fix seccp256k1 configure option

projects/xen/Dockerfile, projects/xen/build.sh, projects/xen/project.yaml
The [Xen Hypervisor Project ](https://xenproject.org) is a type-1 VMM that's fairly popular and is widely deployed. It currently implements a libfuzzer harness for its core x86 instruction emulator code which is build-compatible with oss-fuzz. In this PR we pull in the Xen build to start continuous fuzzing for this critical piece of code, and potentially additional harnesses in the future.
=> [initial integration] Add Xen Hypervisor Project

projects/simdutf/build.sh
I recently made changes to the fuzzer build script in the simdutf repo. The CIfuzz job failed.
The reason is that CIfuzz checks out the default branch when building the docker image.
The current dockerfile copied the build script into the docker image.
This means the build script is used from the default branch, while doing CIfuzz on the PR branch. This broke when I made changes to the build script.
With the changes in this PR, the build script from the checked out code (the PR to run CIfuzz on) is executed instead. That should make it more robust, and make it possible to work with improvements in the build script without having to merge first.
Ping @lemire
=> [simdutf] make cifuzz work better for pull requests

projects/cairo/Dockerfile, projects/cairo/build.sh
The cairo project has several fuzzers which parse PNG files. It also has one SVG renderer fuzzer that is hosted in the cairo project. This SVG fuzzer currently does no actual testing as it's given the same PNG seeds and dictionaries as the other fuzzers.
Some short testing shows that the fuzzer currently reaches about 340 edges (as reported by AFL++), while with actual SVG seeds/dict reaching 5000+ edges immediately. The usual fuzzer tricks for bypassing any of the early parser checks also fail (which is another story), so the coverage with PNG seeds/dict doesn't catch up to the fuzzer with the SVG seeds.
This patch gives the SVG fuzzer the standard SVG dict and the SVG test files from the cairo test folder.
Note that the cairo build also fails because of an outdated meson install, but …
=> [cairo] Use SVG seeds/dict for svg-render-fuzzer

projects/xs/Dockerfile, projects/xs/build.sh, projects/xs/project.yaml, projects/xs/xst.options
Updating XS project:
* Removing experimental from MSAN.
* Updating auto ccs
Additionally, we update the build to :
- Reduce the number of metering units. This should fix timeouts -- the majority are test cases that run for too long and do not hit the meter limit.
- Re-enable `leak_check_at_exit`. We have a custom allocator for fuzzing, so we force purging memory in abort paths (to avoid "leaks" that are transient allocations expected to clean up at exit, which is imminent). As a result, we only report leaks that would have been long-lived, survived VM destruction, and therefore true memory leaks.
- Remove sleep functions from the seed corpus. This should fix timeouts caused by the fuzzer calling functions that sleep indefinitely.
=> xs: project updates and fixes

projects/bitcoin-core/build_cryptofuzz.sh
`bitcoin-core` patch extracted from #12300
=> bitcoin-core: Compile Botan with --disable-asm in MSAN builds

projects/mpv/build.sh, projects/mpv/project.yaml
Fixes timeouts and OOMs on huge scaling sizes. It is not mpv filter anyway, so we can skip testing it.
=> mpv: disable scale filter in ffmpeg build

projects/connectedhomeip/project.yaml
Amine is part of the CSA staff that maintains the testing and automation and in particular fuzz tests and build health for them.
=> Add Amine Alami to CCs for connectedhomeip fuzzing

projects/capstone/Dockerfile, projects/capstone/build.sh
The `base-builder-python` docker image installs `setuptools v42.0`. This is very likely the reason why Capstone's `setup.py` fails.
@DavidKorczynski Is there any reason why it is set to this (very old) version? The [docs](https://google.github.io/oss-fuzz/getting-started/new-project-guide/python-lang/#dockerfile) recommend this one.
=> Ensure up-to-date dependencies for Capstone Python bindings

projects/bind9/build.sh, projects/bind9/project.yaml
The libdns now has constructors and destructors too, we need to add them to the linker list of undefined symbols to keep otherwise they will be removed when statically linked to the fuzz binaries.
=> bind9: Add libdns constructor and destructor symbols

projects/arrow/build.sh
This may allow to find potentially more issues inside the Arrow C++ codebase.
=> arrow: Enable more compression libraries for Arrow

projects/sound-open-firmware/Dockerfile
We are hitting a BackendUnavailable bug due to pep517. Upgrading pip fixes the issue.
=> sound-open-firmware: fix python installs

projects/trust-dns/Dockerfile, projects/trust-dns/project.yaml
This corrects the repository used for the `trust-dns` project. It has since been rebranded to Hickory DNS, and the old URL now points to a stub repository, with just a README directing readers to the new one. This fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=71005.
=> Fix trust-dns clone

projects/libvips/project.yaml
This should improve coverage reports, for example:
https://introspector.oss-fuzz.com/project-profile?project=libvips
=> libvips -- exclude dependencies from coverage

projects/connectedhomeip/build.sh
Fuzz Introspector build is failing with error:
```
/usr/bin/ld.gold: internal error in read_header_prolog, at ../../gold/dwarf_reader.cc:1678
```
- I have tried solutions mentioned here #https://github.com/google/oss-fuzz/pull/10891 and saw this issue #https://github.com/google/oss-fuzz/issues/10237 but doesnt seem to be the same cause.
- so instead i will just build it with `lld` instead of the `gold` linker supplied by the environment
=> [Connectedhomeip] fix for Fuzz Introspector build

projects/pistache/build.sh
Error:
```
GoogleTest not found. Consider installing it on your system. Downloading it from source...
CMake Error at /usr/local/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR)
Call Stack (most recent call first):
/usr/local/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
/usr/local/share/cmake-3.29/Modules/FindCURL.cmake:196 (find_package_handle_standard_args)
tests/CMakeLists.txt:5 (find_package)
-- Configuring incomplete, errors occurred!
```
https://oss-fuzz-build-logs.storage.googleapis.com/log-82eaa7c0-9aaa-42c3-bea0-26dde478d2e2.txt
=> pistache: fix build error

projects/ffmpeg/build.sh
Avoids false positives as the assembly code is not instrumented.
Bug: https://crbug.com/oss-fuzz/70943
Bug: https://crbug.com/oss-fuzz/70950
Bug: https://crbug.com/oss-fuzz/71085
Bug: https://crbug.com/oss-fuzz/71093
=> ffmpeg/build.sh: disable libvpx asm w/msan or centipede

projects/ox-ruby/project.yaml
It's broken and causing noise on oss-fuzz when we are debugging some big changes.
=> disable ox-ruby temporarily

projects/ffmpeg/build.sh
+ --disable-docs --disable-tools to remove a few unnecessary
generation/compile steps
=> ffmpeg/build.sh: add --enable-vp9-highbitdepth to libvpx

projects/xs/project.yaml
Accidentally used an alias rather than the email. Fixing mistake made in #12360
=> fix(xs): correct email for collaborators

projects/cosign/Dockerfile, projects/cosign/build.sh, projects/cosign/project.yaml
Cosign was removed in https://github.com/google/oss-fuzz/pull/6838 because its harness got removed upstream. With new fuzzers ready in https://github.com/sigstore/cosign/pull/3834, Cosign can re-integrate into OSS-Fuzz.
@codysoyland @haydentherapper @bobcallaway @davidkorczynski for info
=> re-integrate cosign

infra/experimental/chronos/README.md
By passing `SANITIZER` env to the container when compiling the fuzz target.
=> Add the commands to build for coverage measurement

projects/tinyxml2/project.yaml
Builds don't contain binaries and cause exceptions
=> Remove centipede from tinyxml2

projects/astroid/Dockerfile, projects/astroid/project.yaml
I have received permission to update the maintainers list here: https://github.com/pylint-dev/astroid/issues/2511#issuecomment-2297611878
This commit also fixes the build by pinning astroid to the latest version with Python 3.8 support.  This will allow the corpus to grow until Python 3.9+ is supported on OSS-Fuzz.
=> astroid: fix build and update maintainers

projects/arrow/build.sh
In PR #12320, we enabled more compression algorithms for Arrow C++, but had to disable Snappy because of build issues.
Since then, the Arrow project merged a PR (https://github.com/apache/arrow/pull/43706) which enables RTTI when building Snappy.
Therefore, we can now enable Snappy in the OSS-Fuzz builds of Arrow C++ as well.
=> arrow: Enable Snappy compression

projects/starlark-rust/Dockerfile, projects/starlark-rust/build.sh
Closes: https://github.com/facebook/starlark-rust/issues/128
=> starlark-rust: fix rustc version issues

projects/memcached/project.yaml
As it reads on the tin. Add my alt email to auto CC's.
=> [memcached] Update CC's list to include bxa alt email

projects/suricata/project.yaml
This reverts commit 85f1bf4f9d9fdd2ab2c7af87b52150fa1165ac0b.
Would fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=71329
=> Revert "suricata: fuzz also on aarch64 (#12366)"

projects/cups-filters/Dockerfile, projects/cups-filters/project.yaml
This PR includes the integration for project cups-filters from OpenPrinting into OSS-Fuzz workflow. The harness repo is maintained seperately here [OpenPrinting fuzzing](https://github.com/OpenPrinting/fuzzing).
All harness building related changes has been locally tested and verified.
=> [cups-filters] Init integration

projects/xmlsec/Dockerfile
See https://github.com/google/oss-fuzz/issues/12335 and https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=47959
=> xmlsec requires automake 1.16.3 or greater

projects/suricata/Dockerfile, projects/suricata/build.sh
as it reached its end of life
Also, remove a temporary workaround for cbindgen (which will not be fixed in version 6)
=> suricata: do not fuzz version 6 anymore

projects/apache-logging-log4cxx/Dockerfile, projects/apache-logging-log4cxx/README.adoc, projects/apache-logging-log4cxx/build.sh, projects/apache-logging-log4cxx/project.yaml
[Log4cxx](https://logging.apache.org/log4cxx) is a widely<sup>1</sup> used logging framework for C++. It is developed and maintained by [Apache Logging Services](https://logging.apache.org) next to [Log4j](https://logging.apache.org/log4j) and [Log4Net](https://logging.apache.org/log4net). This PR integrates Log4cxx to OSS-Fuzz.
<sup>1</sup> While it is difficult to assess the usage of C++ libraries, according to [the ASF statistics](https://infra-reports.apache.org/#downloads&project=logging) (requires an ASF account), it had 1299 downloads in the last two months [until today, i.e., 2024-08-15].
=> Add Log4cxx integration

projects/pillow/Dockerfile
Pillow's oss-fuzz is currently failing, because Pillow main has [dropped support for Python 3.8](https://github.com/python-pillow/Pillow/pull/8183).
#12027 attempts to resolve this by upgrading the base builder to Python 3.10, but the [latest status update](https://github.com/google/oss-fuzz/pull/12027#issuecomment-2278901499) over there says that Pillow [fails in that branch with](https://oss-fuzz-gcb-logs.storage.googleapis.com/log-e19625fb-a984-47b1-be32-f92b4c76fc7f.txt)
> Step 17: Step 6/11 : RUN ln -s /usr/local/bin/python3 /usr/local/bin/python     && ln -s /bin/true /usr/local/bin/yum_install     && ln -s /bin/true /usr/local/bin/yum     && cd $SRC/Pillow     && git submodule update --init wheels/multibuild     && bash $SRC/build_depends.sh
Step 17:  ---> Running in 932abd1dc89a …
=> [Pillow] Removed python symlink

projects/bitcoin-core/build.sh
This PR migrates to the new CMake-based build system.
=> bitcoin-core: Migrate to CMake

infra/base-images/base-builder/bazel_build_fuzz_tests
The current bazel builds change the owner of the $OUT directory due to `tar`. This can cause some issues depending on how Docker is run, but, this is ultimately annoying since e.g. OSS-Fuzz-gen and end-to-end OSS-Fuzz runs relies on reading the files in the OUT directory, which is not possible when the owner changes. Furthermore, it's inconsistent with the existing `compile_*` scripts to change the owner of $OUT/
This fixes it by not changing the owner.
=> infra: bazel_build_fuzz_tests: avoid change of OUT ownership

projects/pem/Dockerfile, projects/pem/build.sh, projects/pem/fuzz_pem.py
Fixes broken fuzzer builds that have been failing since Jul 30, 2024.
- **Pyinstaller Upgrade**: Updated Pyinstaller to version 3.10.0, which is the minimum version supporting setuptools >= 71.0.0. This upgrade addresses the build failures caused by the new dependency vendoring approach in setuptools.
- **Dictionary Addition**: Added a dictionary for setuptools fuzz harnesses.
- **Fuzzer Optimization**: Improved fuzzer cold-start time by using `atheris.instrument_imports` instead of `atheris.instrument_all`. This significantly speeds up the time it takes for the fuzzer to start running.
=> [pem] Fix Broken Build & Improve Fuzz Harness

projects/clamav/Dockerfile
Pip from base image no longer works to install mussels dependency.
=> [clamav] upgrade pip before using it

projects/git/Makefile.diff, projects/git/fuzz-cmd-apply-check.c, projects/git/fuzz-cmd-bundle-verify.c, projects/git/fuzz-cmd-diff.c, projects/git/fuzz-cmd-status.c, projects/git/fuzz-cmd-tag-create.c, projects/git/fuzz-cmd-unpack-objects.c, projects/git/fuzz-command.c, projects/git/fuzz-parse-attr-line.c
Due to various changes in the upstream Git repo, both build_images and build_fuzzers have been failing for Git in oss-fuzz. These commits collect a few fixes to successfully build against Git's 'next' branch.
=> Fix git builds

projects/hdf5/Dockerfile, projects/hdf5/build.sh, projects/hdf5/project.yaml
See also https://github.com/HDFGroup/hdf5/issues/4586
=> fix(hdf5): remove options and run h5_read_fuzzer

projects/simdutf/project.yaml
simdutf has run clean for double digit days now. It is time to extend the fuzzing to also cover arm and msan. I enabled centipede as well, I see no reason to exclude it.
=> [simdutf] enable aarch64, centipede and memory sanitizer

projects/teleport/project.yaml
@jentfoo and I have departed @gravitational, so removing ourselves and making @zmb3 the primary contact.
=> teleport: Update contacts to remove departed individuals

projects/mpv/project.yaml
It is unstable. Likely due to storage limitations. Works locally correctly. Disable it and let other fuzzing engines work.
See: #12429
=> mpv: disable Centipede

projects/msgpack-python/Dockerfile, projects/msgpack-python/build.sh
Fixes [Monorail Issue 68724: msgpack-python: Fuzzing build failure](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=68724)
Resolves two issues that were causing the fuzzer build to fail:
1. An outdated `pip` was failing to parse the `pyproject.toml` file, and failing with a `TomlError`.
Upgrading `pip` resolved this.
2. Cython was not installed & the prerequisite Cython build step was not run before the install step resulting in failure with the message: 
> clang: error: no such file or directory: 'msgpack/_cmsgpack.c'
Installing Cython via the version specified in the upstream requirements file, and running the build step in the upstream makefile resolved this.
Also adds `--depth 1` to the Dockerfile's `git clone` to make the checkout slightly more efficient.
=> [msgpack-python] Fix Broken Build

projects/bind9/build.sh
The `dns_message_checksig_fuzzer` was failing because the `dns_tsigkey_create` function, called during `LLVMFuzzerInitialize`, returned a `DST_R_UNSUPPORTEDALG` error. This issue was caused by incorrect library initialization.
Two functions, `dst__lib_init` and `isc__initialize`, are marked with the `ISC_CONSTRUCTOR` attribute (`__attribute__((constructor))`), and `isc__initialize` must be called before `dst__lib_init`. However, due to an incorrect linker argument order, `isc__initialize` was not called before `dst__lib_init` as required, causing the issue.
This fix resolves the issue by using a linker group, which ensures that (a) `libisc.a` is passed before `libdns.a`, and (b) unresolved symbol errors are avoided, as `libdns.a` depends on `libisc.a`.
=> bind9: fix dns_message_checksig_fuzzer

projects/connectedhomeip/Dockerfile, projects/connectedhomeip/build.sh, projects/connectedhomeip/project.yaml
This fixes two build failures:
1. Zap generation failure due to not finding zap-cli
2. Fixing linking errors such as:
```
ld.lld: error: undefined symbol: is_selinux_enabled
>>> referenced by glocalfileinfo.c.o:(set_selinux_context) in archive /lib/x86_64-linux-gnu/libgio-2.0.a
>>> referenced by glocalfileinfo.c.o:(_g_local_file_info_get) in archive /lib/x86_64-linux-gnu/libgio-2.0.a
>>> referenced by glocalfileinfo.c.o:(_g_local_file_info_get_from_fd) in archive /lib/x86_64-linux-gnu/libgio-2.0.a
>>> referenced 1 more times
```
- This got fixed by explicitly linking some libs, which are transitive dependencies of libgio-2.0
=> [connectedhomeip] Adding zap-cli to PATH and statically linking some libs

projects/tailscale/Dockerfile
tailscale requires Go 1.23: https://github.com/tailscale/tailscale/blob/98f4dd9857b4128c2569a2f2157d0bb8325262fa/go.mod#L3 and OSS-Fuzz uses a lower one per default.
=> tailscale: fix broken build

projects/xmlsec/build.sh
See build failure: https://oss-fuzz-build-logs.storage.googleapis.com/log-49081235-d5d8-4447-bc70-a32b48c39f0d.txt
=> XMLSec requires push functionality in LibXML2

projects/lldb-eval/project.yaml
It was enabled by accident and never worked.
=> Disable honggfuzz and AFL on lldb-eval

projects/gitoxide/Dockerfile, projects/gitoxide/build.sh
Since around https://github.com/Byron/gitoxide/pull/1536, fuzzing is broken for `gitoxide` due to an error related to `serde`. As shown there and in https://github.com/Byron/gitoxide/pull/1596, the error is:
error[E0658]: `#[diagnostic]` attribute name space is experimental
--> /rust/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.210/src/de/mod.rs:536:5
|
536 |     diagnostic::on_unimplemented(
|     ^^^^^^^^^^
|
= note: see issue #111996 <https://github.com/rust-lang/rust/issues/111996> for more information
= help: add `#![feature(diagnostic_namespace)]` to the crate attributes to enable
= note: this compiler was built on 2024-02-11; consider upgrading it if it is out of date
Since https://github.com/rust-lang/rust/issues/111996 is closed as completed, and similar errors appear …
=> gitoxide: Use updated nightly to fix serde error

projects/log4j2/build.sh
In #12304, we used `fuzzing` branch of the `apache/logging-log4j2` repository while developing the Log4j 2 integration. This work was successful and we eventually merged the `fuzzing` branch to `2.x`<sup>1</sup> in apache/logging-log4j2#2949. Now we can point OSS-Fuzz to the permanent location of the Log4j 2 fuzz tests.
<sup>1</sup> [`2.x` is the main branch where Log4j 2 development takes place.](https://logging.apache.org/log4j/2.x/development.html#branching)
=> log4j2: Switch to the Log4j 2 development branch

projects/glaze/Dockerfile, projects/glaze/build.sh, projects/glaze/project.yaml
This adds glaze, a C++ json library which is very relevant because it is extremely fast (on par with simdjson) while offering both read and write. It is also nice to work with, so I expect it to increase in popularity over time.
It currently has over 1000 stars on github.
Upstream is happy to get onto ossfuzz: https://github.com/stephenberry/glaze/pull/1222#issuecomment-2258334280 
I have worked with adding fuzzers to it recently, and a lot of bugs have been promptly fixed by upstream. So, at least most of the shallow bugs are gone already.
=> [initial integration] add glaze json library

infra/build/functions/target_experiment.py
This helps us to identify and debug cloud build from OFG.
=> Add tags to cloud build from target_experiment.py

infra/build/functions/target_experiment.py
This caused a regression for experiments in OFG.
```sh
2024-09-20 22:39:56.906 INFO models - do_generate: vertex_ai_gemini-1-5 generating response with config: {'temperature': 0.6, 'max_output_tokens': 8192}
2024-09-20 22:39:57.088 ERROR builder_runner - _run_with_retry_control: Failed to evaluate /experiment/results/output-htslib-hfile_list_plugins/fixed_targets/02.c on cloud, attempt 1:
Traceback (most recent call last):	  File "/tmp/tmp5dlnpp7z/infra/build/functions/target_experiment.py", line 339, in <module>	    main()	  File "/tmp/tmp5dlnpp7z/infra/build/functions/target_experiment.py", line 332, in main	    run_experiment(args.project, args.target, args.args, args.upload_output_log,	  File "/tmp/tmp5dlnpp7z/infra/build/functions/target_experiment.py", line 288, in run_experiment …
```
=> infra: build: functions: add default empty list for tags

projects/connectedhomeip/Dockerfile
- OSS-Fuzz builds are failing after pigweed was rebased in https://github.com/project-chip/connectedhomeip/pull/35644
- One of the failures is related to pigweed becoming incompatible with python <3.9. Such as using subscript notation in the type hints.
- Fix: Base images in OSS-Fuzz use python 3.8, This PR aims to force the usage of python3.10 instead
```
Step #1: Traceback (most recent call last):
Step #1:   File "../../third_party/pigweed/repo/pw_build/py/pw_build/python_runner.py", line 38, in <module>
Step #1:     import gn_resolver  # type: ignore
Step #1:   File "/src/connectedhomeip/third_party/pigweed/repo/pw_build/py/pw_build/gn_resolver.py", line 319, in <module>
Step #1:     _Actions = Iterator[tuple[_ArgAction, str]]
Step #1: TypeError: 'type' object is not subscriptable
Step …
```
=> [connectedhomeip] Upgrade python version to 3.10

projects/poco/Dockerfile, projects/poco/build.sh, projects/poco/http_message_fuzzer.cc, projects/poco/mail_message_fuzzer.cc
Two new fuzzing targets:
- HTTP messages (request/response/authorization) parsing
- Mail message parsing
=> poco: Net library fuzzing

projects/pillow/Dockerfile
Pillow's oss-fuzz is currently failing, because Pillow main has [dropped support for Python 3.8](https://github.com/python-pillow/Pillow/pull/8183).
Until a global solution is provided for #11419, this installs Python 3.9 to allow Pillow to work again.
cc @hugovk
=> [Pillow] Use Python 3.9

projects/connectedhomeip/project.yaml
- Reactivating UndefinedBehaviorSanitizer after having fixed UBSan issue: https://github.com/project-chip/connectedhomeip/pull/35777
- MemorySanitizer can not be activated due to false positives showing for `glib`. Apparently all dependencies including glib will need to be re-compiled with MSan to avoid these false-positives.
=> [connectedhomeip] Reactivate UndfinedBehaviorSanitizer

projects/apache-logging-log4cxx/build.sh
In #12352, we used the `fuzzing` branch of the `apache/logging-log4cxx` repository while developing the Log4cxx integration. This work was successful and we eventually merged the `fuzzing` branch to `master` in apache/logging-log4cxx#411. Now we can point OSS-Fuzz to the permanent location of the Log4cxx fuzz tests.
=> apache-logging-log4cxx: Switch to the main branch

projects/textdistance/Dockerfile
This pull requests integrates the Dockerfile needed to build the fuzzers for textdistance, as merged into upstream here -  https://github.com/life4/textdistance/pull/94
=> textdistance Initial Integration

infra/base-images/base-builder-rust/Dockerfile, infra/base-images/base-clang/Dockerfile, infra/base-images/base-clang/checkout_build_install_llvm.sh, infra/base-images/base-runner/coverage, infra/base-images/base-runner/profraw_update.py, projects/elfutils/Dockerfile, projects/envoy/Dockerfile, projects/icu/project.yaml, projects/librawspeed/build.sh, projects/rust-lexical/Dockerfile, projects/samba/build.sh, projects/suricata/Dockerfile, projects/suricata/build.sh, projects/wasmer/Dockerfile
Follow-up on #12077 by @alexcrichton cc @maflcko 
Main difference is to update infra/base-images/base-runner/profraw_update.py so that oss-fuzz converts profraw version 8 to 9 (and llvm-cov seems more tolerant in older version reading cf llvm/lib/ProfileData/Coverage/CoverageMappingReader.cpp
This way, it should be more transparent for projects, that can be updated individually or not
=> Update Clang toolchain from 18.0.0 to 18.1.8 

infra/experimental/chronos/Dockerfile, infra/experimental/chronos/build_all.sh, infra/experimental/chronos/build_on_cloudbuild.sh, infra/experimental/chronos/cloudbuild.yaml, infra/experimental/chronos/cloudbuild_all.yaml
Once this is merged, we just need to set up an automated trigger to run this daily.
=> Add cloudbuild for building chronos images for all C++.

infra/experimental/chronos/build_on_cloudbuild.sh, infra/experimental/chronos/cloudbuild.yaml
=> Fix service account for chronos build.

projects/elfutils/Dockerfile, projects/elfutils/build.sh
* [elfutils] unpin the base-builder image
* [elfutils] show clang version
to make it a bit easier to figure out what's going on.
* [elfutils] no longer compile srcfiles.cxx
srcfiles.cxx started failing to compile with the OSS-Fuzz toolchain
when it was switched from clang-18.0.0 to clang-18.1.8 in
https://github.com/google/oss-fuzz/pull/12365.
https://github.com/google/oss-fuzz/pull/12365#discussion_r1784702452
It's probably an OSS-Fuzz toolchain bug but it doesn't matter much
because the srcfiles binary isn't relevant in terms of fuzzing and
can safely be excluded.
=> [elfutils] unpin the base-builder image

projects/askama/build.sh, projects/bson-rust/build.sh, projects/libhtp/Dockerfile, projects/librsvg/build.sh, projects/opensk/build.sh, projects/ron/build.sh, projects/servo/build.sh, projects/toml_edit/build.sh
A draft following https://github.com/google/oss-fuzz/pull/12365 and plan to cherry-pick https://github.com/google/oss-fuzz/pull/12077/commits/e0d68756883ad3017640c8896212d9aee0c518e8
=> Clang 18.1 remove rust pins

projects/wasmtime/project.yaml
Remove some contributors who are no longer working on the project, and additionally update the primary contact to the TSC of the Bytecode Alliance which is the umbrella organization owning the project.
=> Update project contact information for Wasmtime

projects/opencv/Dockerfile, projects/zeek/Dockerfile
Following https://github.com/google/oss-fuzz/pull/12365 : only zeek and opencv seem fixed
=> Remove some `@sha256:...` pins in Dockerfiles

projects/astroid/Dockerfile
This is a temporary fix until Python 3.9+ is supported.
=> astroid: fix coverage builds

projects/rust-lexical/Dockerfile
This unpins the image for `rust-lexical`, due to patches in the fuzz targets Cargo.toml to remove LTO from the release profile.
Related to:
- Alexhuszagh/rust-lexical/issues/164
- Alexhuszagh/rust-lexical/issues/166
- #12365
=> Unpin rust-lexical image version.

projects/ghostscript/project.yaml
kdlee (that's me) has since moved to a different project and no longer watches over the fuzzer bugs.
(For internal pings, I've got the same username, and my avatar provides a loose confirmation that this is in fact me)
=> ghostscript: Remove kdlee

projects/typing_extensions/fuzz_typing_extensions.py
Fixes this error during coverage builds:
```
=== Uncaught Python exception: ===
NameError: name 'isinsance' is not defined
File "fuzz_typing_extensions.py", line 65, in TestOneInput
NameError: name 'isinsance' is not defined
```
=> typing_extensions: Fix "isinsance" typo

infra/base-images/base-runner/coverage
This will make it easier to debug coverage failures that are not reproducible locally.
The failure that I am trying to debug:
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=62231
- https://oss-fuzz-build-logs.storage.googleapis.com/log-c420cf0c-f073-4c42-b75c-422971ef272e.txt
```
Step #5: Already have image (with digest): gcr.io/oss-fuzz-base/base-runner
Step #5: Entering python fuzzing
Step #5: Error happened getting coverage of fuzz_parse
Step #5: This is likely because Atheris did not exit gracefully
```
Similar log data is displayed in other blocks:
https://github.com/google/oss-fuzz/blob/f7165902492d5cff5ee23c018875395061a3bd2b/infra/base-images/base-runner/coverage#L101-L105
https://github.com/google/oss-fuzz/blob/f7165902492d5cff5ee23c018875395061a3bd2b/infra/base-images/ba …
=> infra: print log data when Python fuzz_target fails

projects/zip/project.yaml
I am requesting permission to integrate [zip](https://github.com/kuba--/zip) into OSSFuzz. I believe that this project is a good candidate for OSS-Fuzz integration as it serves as a preeminent file compression / decompression library used by many prominent projects (Windows [PowerToys](https://github.com/microsoft/PowerToys), The [Ring Programming Language](https://ring-lang.github.io/), and the [V Programming Language](https://github.com/vlang/v) to name a few). In addition to the possibility of uncovering edge-cases and bugs in the decompression of zip files, there is the possibility of a malicious actor crafting a corrupted zip file that could achieve DoS or, in an extreme case, privilege escalation and RCE. 
EDIT: Please see upstream approval for integration (and listing me as the …
=> Zip: Initial Project Proposal

projects/systemd/project.yaml, projects/util-linux/project.yaml
It seems notifications are no longer sent there.
It would be great to make it work for other email addresses like the elfutils mailing list because it's the only way to notify the upstream project.
=> [systemd],[util-linux] remove evverx's non-gmail address

projects/bearssl/Dockerfile, projects/bls-signatures/Dockerfile, projects/cmake/Dockerfile, projects/firestore/Dockerfile, projects/flatbuffers/Dockerfile, projects/json/Dockerfile, projects/libecc/Dockerfile, projects/nettle/Dockerfile, projects/opencv/Dockerfile, projects/perfetto/Dockerfile
Following https://github.com/google/oss-fuzz/pull/12365
cc @maflcko
=> remove usage of OLD_LLVMPASS

infra/experimental/chronos/cloudbuild.yaml
It seems to be causing congestion that is breaking oss-fuzz builds.
Fixes: https://github.com/google/oss-fuzz/issues/12573
=> Use a seperate pool for Chronos

projects/apache-poi/pom.xml
Apache POI seems to depend on a newer version of Log4j now.
Also update main version and jazzer-api to latest
=> apache-poi: Update dependencies for Apache POI to fix broken build

infra/build/build_status/update_build_status.py, infra/build/functions/build_lib.py, infra/build/functions/trial_build.py
Avoids hardcoding cloud build region to `us-central1`, so that users (e.g., `target_experiment.py`) can define their own region.
=> Customize cloud build region

infra/base-images/base-builder/compile, infra/base-images/base-clang/Dockerfile
This enables a light version of introspector, which performs analysis prior to compilation, i.e. without use of LTO. At the current stage light FI has implemented features to support test-to-harness migration on OFG including harness source/executable pairing. Once this has been rolled out in full the light analysis will continue to support more interesting logic related to program analysis, all purely static.
=> infra: enable introspector light

projects/containerd/project.yaml
Vinayak is a containerd [security advisor](https://github.com/containerd/project/blob/6d5d6d4908802608d7ba29c9a3e5e3aaccc14390/SECURITY_ADVISORS#L17C2-L17C18); access will allow him to help triage reports.
cc @vinayakankugoyal
=> containerd: add additional security advisor

infra/build/functions/build_and_run_coverage.py, infra/build/functions/build_project.py
Upload introspector report even when build fails. This is to ensure artifacts from FI light is uploaded for each build.
=> infra: build: introspector: upload artifacts in all cases

projects/serenity/project.yaml
I am no longer involved with this project, so let's make @gmta the primary contact since he's the chief admin of SerenityOS now. :)
=> serenity: Transfer ownership to current project admin

projects/zstd-safe/Dockerfile, projects/zstd-safe/build.sh, projects/zstd-safe/project.yaml
This PR initialises OSS-Fuzz integration for the zstd-safe project in Rust. New fuzzers have been created, and a PR (https://github.com/gyscos/zstd-rs/pull/308) has been submitted upstream to merge the fuzzers.
=> Zstd-safe: project initialisation

projects/lz4_flex/project.yaml
([Approved by the maintainer](https://github.com/PSeitz/lz4_flex/issues/171#issuecomment-2418767064))
[`lz4_flex`](https://github.com/PSeitz/lz4_flex/) is a ridiculously fast compression library for rust implementing LZ4. It has a prevalent use of unsafe in its faster variant (which could mean not just denial of service, but potential RCE vulnerabilities) , has a high chance of taking in user input, used in large open-source projects:
Its used in [bevy](https://github.com/bevyengine/bevy), [polars](https://github.com/pola-rs/polars), [wasmer](https://github.com/wasmerio/wasmer), [chroma](https://github.com/chroma-core/chroma), [FiloDB](https://github.com/filodb/FiloDB), [SlateDB](https://github.com/slatedb/slatedb), and [many other …
=> [lz4_flex] project proposal

infra/build/functions/request_introspector_build.py
This was caused by a very old refactor, but we never deployed the introspector scheduler since then so we didn't run into this until now.
=> Fix introspector scheduling exception.

projects/scrypt/Dockerfile, projects/scrypt/build.sh, projects/scrypt/project.yaml
This PR initialises OSS-Fuzz integration for the scrypt project in Rust. New fuzzers have been created, and a PR (https://github.com/RustCrypto/password-hashes/pull/534) has been submitted upstream to merge the fuzzers.
=> scrypt: initial integration

projects/nss/Dockerfile
We recently moved the repo for the NSS fuzzing corpus from github.com/mozilla to github.com/MozillaSecurity. The old URL is redirected and still works, but we should update it to reflect that change.
=> [nss] update corpus url

projects/apache-commons-collections/project.yaml
An anonymous attentive audience of our fuzzing workshop at Ubuntu Summit 2024 noticed this outdated URL and kindly informed me.
The old URL is not available anymore.
The new URL can be confirmed on the [project's homepage](https://commons.apache.org/proper/commons-collections/).
=> Update `main_url` of `apache-commons-collections`

projects/wasmtime/project.yaml
Try adding a few ignores for dependencies that we're not interested in to help improve the quality of the coverage reports coming out of fuzzing for Wasmtime.
=> Improve Wasmtime's coverage reports

projects/graphicsmagick/Dockerfile
Pull from stable branch of x265 project for builds.  Default repository content does not seem to be fully populated for use.
=> graphicsmagick: Pull stable branch of x265 project

projects/libxml2/project.yaml
In the last days, this seems to cause build failures like:
"compile-libfuzzer-address-aarch64": exec /usr/bin/bash: exec
format error
=> libxml2: Disable aarch64

projects/wasmtime/project.yaml
This fixes a mistake in #12661 to improve the coverage reports for Wasmtime.
=> Fix a typo in Wasmtime's coverage regex

projects/keycloak/Dockerfile
This PR fixes the issue https://issues.oss-fuzz.com/u/7/issues/369683281 which has missing native library.
=> Keycloak: Add missing native library

infra/experimental/chronos/cloudbuild.yaml
Make these match the formatting conventions oss-fuzz already uses (i.e. "address" instead of "asan").
=> Update sanitizer strings for chronos builds.

infra/base-images/base-builder/Dockerfile
This installs clang wrappers at /ccache/bin, and sets up a build cache at /ccache/cache. To use this, inside the project container we just need to do:
```
export PATH=/ccache/bin:$PATH
```
In another PR, we can store the /ccache/cache somewhere we can pull down at runtime.
Some results:
Fresh compile:
real	0m49.249s
user	10m41.818s
sys	1m2.097s
With ccache cache:
real	0m9.877s
user	0m6.278s
sys	0m19.966s
Fresh compile:
real	1m17.214s
user	0m49.454s
sys	0m27.963s
With ccache:
real	0m34.962s
user	0m18.092s
sys	0m17.083s
=> Add ccache to base-builder.

projects/samba/project.yaml
As requested in https://github.com/google/oss-fuzz/pull/12605 Sorry for the spam. It happened by accident when migrating bug trackers. It should no longer be an issue. Let me know if you want more emails again :-)
=> Remove abartlett work email address

projects/lua/project.yaml
See also [1] and [2].
1. https://github.com/google/oss-fuzz/issues/12670
2. https://github.com/ligurio/lua-c-api-tests/issues/108
=> [lua] Disable building Aarch64

projects/exprtk/exprtk_fuzzer.cpp
- Additional RTCs:
1. Compilation time-out RTC
2. Vector access RTC
3. Assert handler
- Set maximum vector size (#64099)
- Ensure tests don't exceed 60sec time limit (#56181, #38029, #44308)
=> Update ExprTk Fuzzer

infra/base-images/base-builder/Dockerfile, infra/build/functions/target_experiment.py
Create ccache wrappers for clang[++]-jcc, and remove the explicit path from the CC/CXX variables in target_experiment.py.
Note: this is not fully tested end to end yet.
Part of https://github.com/google/oss-fuzz-gen/issues/682.
=> Make ccache work with jcc.

projects/kimageformats/Dockerfile, projects/kimageformats/build.sh, projects/kimageformats/kimgio_fuzzer.cc
Apply the following changes to the KImageFormats project:
- Moved EXR lib to branch 3.3
- Update AVIF lib to latest patch release
- Added SCITEX plugin to fuzzer test
- Fixed KDE/extra-cmake-modules build error
=> KImageFormats: Added SCITEX plugin and updated libraries

projects/javy/project.yaml
Add Javy project according to instructions provided in https://google.github.io/oss-fuzz/getting-started/accepting-new-projects/.
=> Add javy project

projects/kimageformats/Dockerfile
The previous version does not accept changes and is compiled by default without the NDEBUG option.
=> KImageFormats: JXR library modified with a patched one

projects/sound-open-firmware/project.yaml
Changed the main contact of project/sound-open-firmware to johnylin@ and moved andyross@ to cc.
=> sound-open-firmware: change main contact to johnylin

projects/llvm_libcxxabi/build.sh
This PR fixes a build error by adding `src/abort_message.cpp` to the linker. It requires because [DEMANGLE_ASSERT](https://github.com/llvm/llvm-project/blob/230946fad69c952dc434aa3e2f92853c1ee8d304/libcxxabi/src/cxa_demangle.cpp#L14) is used in the demangling module.
```
cxa_demangle.cpp:(.text._ZNK12_GLOBAL__N_116itanium_demangle4Node5visitINSt3__117reference_wrapperINS_11DumpVisitorEEEEEvT_[_ZNK12_GLOBAL__N_116itanium_demangle4Node5visitINSt3__117reference_wrapperINS_11DumpVisitorEEEEEvT_]+0xfcd): undefined reference to `__abort_message'
/usr/bin/ld: /tmp/cxa_demangle-39bd04.o: in function `__cxa_demangle':
cxa_demangle.cpp:(.text.__cxa_demangle[__cxa_demangle]+0x192c): undefined reference to `__abort_message'
/usr/bin/ld: /tmp/cxa_demangle-39bd04.o: in function `(anonymous …
```
=> llvm_libcxxabi: fix build

projects/cubefs/project.yaml
This typo is breaking oss_fuzz_apply_ccs.
=> Fix typo on cubefs project.yaml

projects/php/project.yaml
As explained by Jonathan, non-google accounts are no longer supported.
Fixes #12717
=> Switch to gmail account

infra/base-images/base-builder-jvm/Dockerfile
This PR reduces the final `base-builder-jvm` image by 9GB.
Careful review and full integration testing across oss-fuzz projects are required before merging, obviously. 
This worked on two projects I was interested in. One that used `@FuzzTest` and one that used `fuzzerTestOneInput`
=> Build in stages to shed 9gb from the jvm base builder image

projects/cups-filters/Dockerfile, projects/cups-filters/project.yaml
The originally integrated fuzz harnesses of cups-filters are developed for cups-filters 2.x, which require numerous dependencies not supported by the OSS-Fuzz base image (Ubuntu 20.04). The missing dependencies resulted in consistent build failures and the project was temporarily removed in #12501. We have replaced them with new harnesses for fuzzing cups-filters 1.x, which developers still use widely.
=> [cups-filters] re-init integration

projects/minizip/Dockerfile, projects/minizip/build.sh
```
[ 71%] Building C object CMakeFiles/minizip.dir/compat/unzip.c.o
/src/minizip-ng/compat/unzip.c:687:16: error: use of undeclared identifier 'Z_ERRNO'
687 |         return UNZ_ERRNO;
|                ^
/src/minizip-ng/compat/unzip.h:51:34: note: expanded from macro 'UNZ_ERRNO'
51 | #define UNZ_ERRNO               (Z_ERRNO)
|                                  ^
```
https://oss-fuzz-build-logs.storage.googleapis.com/log-9d4da045-29d1-4b5f-b65b-1c3ac84b00a9.txt
=> minizip: fix build

projects/envoy/build.sh
A recent upgrade of Envoy' abseil library (https://github.com/envoyproxy/envoy/pull/36317) enabled `layering_check` ([imported commit](https://github.com/abseil/abseil-cpp/commit/143e983739333ce4b30320d26bce8594bd24b5f3#diff-8498e61ae6ae818e1ee9bcefffd37b44a3a596e63d1de03c58087299ccbe7a22)) when building abseil (as part of Envoy).
Here's an example of the failure during the build:
```
[1A[K[31m[1mERROR: [0m/root/.cache/bazel/_bazel_root/4e9824db8e7d11820cfa25090ed4ed10/external/com_google_absl/absl/types/BUILD.bazel:178:11: Compiling absl/types/bad_variant_access.cc failed: undeclared inclusion(s) in rule '@com_google_absl//absl/types:bad_variant_access':
Step #3 - "compile-honggfuzz-address-x86_64": this rule is missing dependency declarations for the following files included by …
```
=> [envoy] disable layering_check from bazel build

projects/graphicsmagick/Dockerfile
Add the OpenH264 and OpenJPEG libraries needed by libheif in order to make the libheif build more complete.
=> graphicsmagick: Add OpenH264 and OpenJPEG libraries needed by libheif

projects/cups-filters/project.yaml
The building with AFL engine works properly during local testing but continuously fails in ClusterFuzz. Temporarily remove it to ensure at least one successful build of cups-filters.
=> [cups-filters] update due to failed building with afl

projects/rustls/Dockerfile, projects/rustls/build.sh
This reverts commit 3199a09d0c0df2aeb34d8a34ce7e12b1e080d679.
The corpus repo has unfortunately been deleted by the original contributor.
=> Revert "[rustls] Add seed corpus (#10179)"

projects/surrealdb/build.sh
After https://github.com/surrealdb/surrealdb/pull/4933 the fuzzing crate is under `crates` rather than `sdk`.
=> surrealdb: update build script

projects/proton-bridge/Dockerfile, projects/proton-bridge/build.sh
This uses a WIP branch of go-118-fuzz-build that fixes the exact problem that proton-bridge is facing in its build.
cc @pkillarjun for highlighting this in https://github.com/google/oss-fuzz/pull/12752
=> proton-bridge: fix broken build

projects/sound-open-firmware/build.sh
Zip up corpus and add it to $OUT.
Blocked by https://github.com/thesofproject/sof/pull/9673
=> sound-open-firmware: add corpus install to script

projects/astroid/Dockerfile
Now that Python 3.10 is supported, pinning is no longer necessary.
=> astroid: fuzz against the main branch instead of the v3.2.4 tag

projects/tinysparql/Dockerfile, projects/tinysparql/build.sh, projects/tinysparql/project.yaml
Finish integration of the TinySPARQL project, and provide the plumbing to run the recently added fuzzing targets.
=> tinysparql: Provide Dockerfile and build script

infra/base-images/base-builder/sanitizers/pysecsan/pysecsan/redos.py
To detect Regex DoS, PySecSan installs pre_hook and post_hook of re.pattern.findall.
However, due to typo, it installs `hook_pre_exec_re_pattern_findall` as pre_hook and post_hook.
This leads to failure of detecting Regex DoS bugs.
=> [PySecSan] Fix a bug in Regex DoS detector due to typo

projects/cert-manager/Dockerfile, projects/cert-manager/build.sh
Bump go and use different branch of go-118-fuzz-build.
=> cert-manager: fix broken build

projects/javy/Dockerfile, projects/javy/build.sh, projects/javy/project.yaml
Adds `Dockerfile`, `build.sh`, and updates `project.yaml` for Javy.
When running fuzzing locally, I keep seeing unbounded memory growth when using the address sanitizer and disabling the sanitizer results in steady state memory usage. Using the undefined sanitizer seems to result in linking errors when I try to build the project due to missing `__sancov_gen_` symbols. I'm not clear on how best to resolve those. In any case, for the `json-differential` target, we're trying to ensure correctness of our implementation first and foremost.
=> Configure Javy project

projects/micronaut/project.yaml
The micronaut framework is a Java application framework focused on HTTP applications. The [core repository](https://github.com/micronaut-projects/micronaut-core):
- Has 6k stars on GitHub
- A criticality score of 0.69541 in the latest public data run, 0.70123 in the October run
- \>1M monthly downloads on maven central
I believe that should qualify for oss-fuzz.
All contacts listed are project contributors and oracle employees. I also used some personal emails associated with google accounts for clusterfuzz access.
=> micronaut: New project submission

projects/pillow/Dockerfile
Now that #12027 has been merged to update the base image to Python 3.10, the work from #12546 of upgrading Python to something above 3.8 for Pillow is no longer needed.
cc @hugovk
=> [Pillow] Revert "Install Python 3.9"

projects/wuffs/Dockerfile
https://github.com/guidovranken/rapidjson-fuzzers has disappeared.
Fixes https://issues.oss-fuzz.com/issues/380676571
=> [wuffs] remove rapidjson corpus

projects/typst/Dockerfile, projects/typst/build.sh
The existing toolchain is unable to build the current Typst.
=> typst: Bump Rust toolchain

projects/kubevirt/Dockerfile, projects/kubevirt/build.sh, projects/kubevirt/fuzz_test.go, projects/kubevirt/project.yaml
Kubevirt is a virtualization API for Kubernetes. It allows its users to manage virtual machines for workloads that are hard to containerize. It is widely used in industry by users like:
1. Arm
2. ByteDance
3. Cloudflare
4. Intel
5. Nvidia
See more users at https://kubevirt.io/
=> kubevirt: initial integration

projects/netty/pom.xml, projects/netty/project.yaml, projects/netty/src/main/java/io/netty/handler/BaseHandlerFuzzer.java, projects/netty/src/main/java/io/netty/handler/HandlerFuzzerBase.java, projects/netty/src/main/java/io/netty/handler/codec/http/HttpRequestDecoderFuzzer.java
This is my initial PR to get my feet wet, sort out the CLA, so it's just a small change.
The main change is a fuzzer for HttpRequestDecoder. This fuzzer reproduces the bug fixed by https://github.com/netty/netty/pull/13735 .
I also added myself to the contact list of the netty project. This was approved by @normanmaurer in January: https://github.com/netty/netty/issues/13033#issuecomment-1911318993 – unfortunately it took me until now to get corp approval for the CLA.
=> netty: Add fuzz test for HttpRequestDecoder

projects/roughtime/Dockerfile, projects/roughtime/build.sh, projects/roughtime/project.yaml
Follow up on https://github.com/cloudflare/roughtime/pull/65.
> why this is important?
It's in Cloudflare production [source](https://blog.cloudflare.com/roughtime/)
=> roughtime: initial integration

projects/mdbook-i18n-helpers/project.yaml
Adding the group which manages the project to `auto_ccs` so that they have access to the filed bugs.
=> Update auto_ccs list for mdbook-i18n-helpers

projects/micronaut/Dockerfile, projects/micronaut/project.yaml
Initial fuzz build with the existing targets we have at https://github.com/micronaut-projects/micronaut-fuzzing . I tried to keep as much of the build infra in our repos as possible, including the build.sh.
I've tested locally (build_image, build_fuzzers, check_build, run_fuzzer) and it works.
=> micronaut: Build with existing fuzz tests

projects/python3-libraries/Dockerfile, projects/python3-libraries/project.yaml
The fuzzer repo https://github.com/guidovranken/python-library-fuzzers was deleted for the owners own reasons so the project is now failing; #12746.  We've restored a fork of that repo and would like to keep this fuzzing running for the CPython project for ourselves.
_(we may choose to move the repo to under the /python/ GitHub org in the future, if so, that's just another followup PR)_
=> Reclaim the python3-libraries fuzzer (repo change)

projects/vulkan-loader/fuzzers/json_load_fuzzer.c
loader_cJSON_Delete needs to be called to delete all subobjects correctly.
@DavidKorczynski
=> Vulkan-Loader: Fix json_loader_fuzzer.c memory leak

infra/base-images/base-builder/precompile_centipede
supersedes: https://github.com/google/oss-fuzz/pull/12838 with a less intrusive approach
=> infra: fix precompile_centipede

projects/binutils/fuzz_objdump.c
The display_file() signature has changed, update fuzz_objdump to suit.
=> Update to suit upstream binutils

infra/experimental/chronos/prepare-ccache
Currently the $PATH bit is expanded, i.e. the ENV string becomes the PATH of the host system, as opposed to the docker container's PATH. We should escape the `$` to ensure we don't overwrite the full PATH
=> chronos: fix PATH setting

projects/boost/boost_regex_pattern_fuzzer.cc
In future versions of Boost, this fuzzing test will throw unconditionally because it's erroneously mixing two different matching modes (`match_perl | match_posix`).
Right now, the test is fine but eventually, it will be broken and no longer function as it should.
You can see the new behavior being tested on the develop branch here:
https://github.com/boostorg/regex/blob/0cbaa4ef1740c88106337cf0ba5bf5c73b62863c/test/issue232.cpp#L58
By splitting the regex calls here into their own try-catch blocks, we also ensure a more robust test of the regex matching code by ensuring that both modes are always called always.
The other tests seemed unaffected by this change.
@jzmaddock might have some opinions on this too, as he's the primary Regex author.
=> update boost regex test for new behavior

projects/vulkan-loader/fuzzers/settings_fuzzer.c
Commit e17999e "fixed" the settings_fuzzer.c test by cleaning up memory, but did not pass in the correct variable. It would reinterpret a pointer to memory as a `loader_layer_list` struct, which is all sorts of wrong. It doesn't help that I forcibly cast the memory pointer to the loader_layer_list struct type, causing any warnings to be surpressed.
@DavidKorczynski 
2nd tries the charm hopefully.
=> vulkan-loader: Use correct variable in destroy function

projects/pulldown-cmark/Dockerfile, projects/pulldown-cmark/build.sh
continues https://github.com/google/oss-fuzz/pull/12594. thin is used to counter [build errors](https://github.com/pulldown-cmark/pulldown-cmark/blob/db58c3153dff847e74c3ffd403bcf9b1a2e04839/fuzz/README.md#L17).
=> [pulldown-cmark] finalize

projects/zip/Dockerfile, projects/zip/project.yaml
This pull requests integrates the Dockerfile needed to build the fuzzers for zip, as merged into upstream [here](https://github.com/kuba--/zip/pull/365).
=> zip: Updated Dockerfile for initial integration

infra/presubmit.py, projects/apache-poi/Dockerfile, projects/apache-poi/pom.xml
* Update JDK 8 and 11 to latest patch-levels
* Add temporary work around for invalid dependency on log4j-bom introduced via recent XmlBeans
* Fix presubmit-checks for Apache POI
* Print out which file fails checks in presubmit.py to aid in finding the culprit
=> Apache poi various smaller changes

projects/envoy/build.sh
Fixes a build issue:
```
[1A[K[31m[1mERROR: [0m/root/.cache/bazel/_bazel_root/4e9824db8e7d11820cfa25090ed4ed10/external/com_google_absl/absl/types/BUILD.bazel:178:11: Compiling absl/types/bad_variant_access.cc [for tool] failed: undeclared inclusion(s) in rule '@@com_google_absl//absl/types:bad_variant_access':
Step #3 - "compile-honggfuzz-address-x86_64": this rule is missing dependency declarations for the following files included by 'absl/types/bad_variant_access.cc':
Step #3 - "compile-honggfuzz-address-x86_64":   'bazel-out/k8-opt-exec-ST-13d3ddad9198/bin/external/com_google_absl/absl/base/core_headers.cppmap'
Step #3 - "compile-honggfuzz-address-x86_64":   'bazel-out/k8-opt-exec-ST-13d3ddad9198/bin/external/com_google_absl/absl/base/atomic_hook.cppmap'
```
This seems to be due …
=> [envoy] fix build failure due to bazel issue

projects/cppcheck/build.sh
this did not have any effect back when it was integrated but the Makefile has been refactored since to leverage this.
=> cppcheck: build with all available processes

projects/libtheora/Dockerfile
The original has since been deleted and this was breaking the build.
Fixes https://issues.oss-fuzz.com/issues/380409700
=> libtheora: change oss-fuzz-fuzzers fork

projects/struts/build.sh, projects/struts/struts2-fuzzer/fuzzer/pom.xml, projects/struts/struts2-fuzzer/pom.xml, projects/struts/struts2-fuzzer/webapp/pom.xml, projects/struts/struts2-fuzzer/webapp/src/main/java/org/apache/struts/test/TestAction.java
PR updates oss-fuzz to support the latest Struts 7 which uses Java 17 and JakartaEE 6.0
=> Upgrades to support Struts 7

projects/pillow/Dockerfile
https://github.com/google/oss-fuzz/blob/2ef5c1fd8bb77f86866069ddf063e9b0efcc7256/projects/pillow/Dockerfile#L32-L33
These lines can be removed. Pillow no longer needs to suppress errors when calling yum.
They would have been there originally because
- multibuild called `yum_install` for installing [zlib](https://github.com/multi-build/multibuild/blob/42d761728d141d8462cd9943f4329f12fe62b155/library_builders.sh#L144) and [`cmake`](https://github.com/multi-build/multibuild/blob/42d761728d141d8462cd9943f4329f12fe62b155/library_builders.sh#L217), but https://github.com/python-pillow/pillow-wheels/pull/204 and https://github.com/python-pillow/Pillow/pull/8593 mean that those are used anymore.
- Pillow called `yum` to remove zlib-devel, but that is no longer the case after …
=> [Pillow] Removed yum symlinks

projects/apache-poi/pom.xml, projects/apache-poi/src/main/java/org/apache/poi/EncryptDecryptFuzzer.java, projects/apache-poi/src/main/java/org/apache/poi/POIFuzzer.java
Issue https://issues.oss-fuzz.com/issues/42537716 is caused by a missing lower limit which we adjust for other fuzz-targets already to adjust for the available memory which oss-fuzz uses.
This PR applies the limit in two more places and removes a workaround for a version-incompatibility in log4j 2.24.1 and an issue with pom-dependencies in XMLBeans.
=> Apache poi add missing limits and revert log4j workaround

projects/arrow/project.yaml
Matt Topol (GitHub id "zeroshade") is a Apache Arrow PMC member and committer.
=> arrow: Add Matt Topol to ccs

projects/unsafe-libyaml/Dockerfile, projects/unsafe-libyaml/build.sh, projects/unsafe-libyaml/project.yaml
This PR initialises OSS-Fuzz integration for project unsafe-libyaml in Rust, adopting the existing fuzzers from upstream repository.
=> Unsafe-libyaml: project integration

projects/cockroachdb/Dockerfile
Fixes https://github.com/google/oss-fuzz/pull/12912#issuecomment-2577401661
=> cockroachdb: use go 1.22

projects/speex/build.sh
Before this was issuing:
> configure: WARNING: unrecognized options: --enable-fixed
=> speex: fix configure option for fixed-point

projects/llhttp/Dockerfile, projects/llhttp/build.sh
Fixes several issues in the build which have been breaking the runtime code coverage collection since at least 2024-11-24.
- Upgraded Node.js to the latest LTS release via the base image `install_javascriot.sh` script for compatibility with the upstream project's requirements.
- Refined the build commands to prefer the upstream project's documentation.
- Adjusted compiler flags to ensure only the executable fuzzing harness is placed in the `$OUT` directory so unnecessary build artifacts can't break anything in unexpected ways.
- Resolves the broken coverage collection.
- Marginally improves overall build times (see note below.)
---
The Dockerfile, both before and after this PR, uses a script hosted by https://deb.nodesource\.com to install a more recent version of Nodejs than the …
=> [llhttp] Fix Build Issues & Coverage Failure

projects/wasmtime/Dockerfile
The default Rust toolchain use to build Rust projects on OSS-Fuzz, `nightly-2024-07-12`, is too old to build Wasmtime at this time. This toolchain is held back to match the LLVM version that Clang is using (18) and is one of the last Rust nightly builds that still uses LLVM 18 (`nightly-2024-07-30` is the last Rust nightly using 18, `nightly-2024-08-01` uses LLVM 19).
In lieu of updating the toolchain for all projects I've opted to only update Wasmtime at this time. I believe this means that Wasmtime will lose coverage information for fuzzing because LLVM tooling is at version 18 whereas Wasmtime will be producing coverage files from LLVM 19. For Wasmtime this is ok as we rely on the fuzzers themselves much more than the retrospective coverage information.
=> Update Wasmtime's Rust toolchain

projects/pigweed/build.sh
Sapphire's fuzzers use a set of test fakes that depend on gTest. This PR adds a Bazel flag to include gTest instead of the "light" pw_unit_test framework.
Bug: 382721836
=> pigweed: Fix sapphire fuzzers

projects/jbig2dec/Dockerfile
This will resolve the currently failing builds since the project files are still referring to the old git server.
=> [jbig2dec] Update addresses to new upstream git server.

projects/wasmtime/build.sh
This commit is an attempt to disable the use of ASAN for the Wasmtime project. Historically ASAN has not provided the project much benefit and ends up having the net effect of making fuzzing ~2x slower than it would be otherwise. Wasmtime is a WebAssembly runtime written in Rust, and while it has a nontrivial amount of `unsafe` code it's all primarily interacting with un-instrumented JIT code. This means that ASAN, even when enabled, is of little benefit as it's already not checking some of the most critical parts of Wasmtime.
In addition to causing a slowdown we also have a history in Wasmtime of fighting ASAN about signal handlers. Just recently we found that attempting to destroy a `sigaltstack` in a TLS destructor was (presumably) corrupting internal ASAN state. This took a number of …
=> wasmtime: Disable ASAN in fuzzing

infra/build/functions/build_and_run_coverage_test.py, infra/build/functions/build_lib.py, infra/build/functions/build_project.py, infra/build/functions/test_data/expected_build_steps.json, infra/build/functions/test_data/expected_centipede_build_steps.json, infra/build/functions/test_data/expected_coverage_build_steps.json, infra/build/functions/test_data/expected_trial_build_steps.json
This reverts commit be6c9296814d2b4655a5f938509714b6281c661f.
=> Reapply "Save docker images for C/C++" (#12876)

projects/libconfig/Dockerfile, projects/libconfig/project.yaml
This pull requests integrates the Dockerfile needed to build the fuzzers for libconfig, as merged into upstream [here](https://github.com/hyperrealm/libconfig/pull/251).
=> Libconfig: Updated Dockerfile for Initial Integration

projects/lcms/Dockerfile
The image for lcms fails to build: https://oss-fuzz-build-logs.storage.googleapis.com/log-288a8d76-2e99-4e63-90aa-e3d769a57d21.txt
The error is because the file `TestCLT.icc` is removed in this commit: https://github.com/mm2/Little-CMS/commit/08f4abb92df247ffa03fd740a31c2c496fa52de3
This PR removes the copy for this removed file.
=> [lcms] fix lcms dockerfile

infra/experimental/chronos/build_all.sh
Follow up: Don't build projects which are known to be failing builds.
=> chronos: Don't build projects with incomplete integrations.

infra/base-images/base-builder/bash_parser.py, infra/experimental/chronos/README.md, infra/experimental/chronos/build_cache_local.sh, infra/experimental/chronos/cloudbuild.yaml
Also make some changes:
1. Support coverage builds by parameterising the sanitizer.
2. Build a total of 2 images: 
- us-central1-docker.pkg.dev/oss-fuzz/oss-fuzz-gen/${_PROJECT}-ofg-cached-${_SANITIZER}
- us-central1-docker.pkg.dev/oss-fuzz/oss-fuzz-gen/${_PROJECT}-ofg-ccache-${_SANITIZER}
The "cached" image will be different depending on whether replay worked or not. The "ccache" image will always use ccache.
3. Fix an incorrect exception path in bash_parser.py
=> chronos: Run build_cache_local.sh on cloud build

projects/go-git/Dockerfile, projects/go-git/build.sh
Main changes are:
- Dynamically find and build all fuzzing targets.
- Fix current build issues.
- Cache go dependencies when cloning repositories.
- Clean up test files by removing structs, global values and comments which were leading to some errors.
- Expand scope to `go-git/go-billy`.
The logic for dynamic finding and building fuzzing targets is largely the same as for the fluxcd project.
Requires https://github.com/go-git/go-git/pull/1404 to be merged for building to work again.
=> go-git: Fix build issue and auto-discover targets

projects/libressl/Dockerfile, projects/libressl/build.sh
cryptofuzz has been removed, but a copy exists here: https://github.com/MozillaSecurity/cryptofuzz
=> libressl: fix build

projects/relic/Dockerfile, projects/relic/project.yaml
Cryptofuzz has been removed, but is revived here:
https://github.com/MozillaSecurity/cryptofuzz
=> relic: fix build

projects/tmux/build.sh
Quick fix preventing the building process to break in case the corpus was already created (leading to a lack of coverage data in introspector).
=> tmux: fix build issue

projects/sleuthkit/project.yaml
Adding @simsong as new maintainer for the Sleuthkit, given @bcarrier lacks the time to look at the OSSFuzz reports
=> Added new maintainer to Sleuthkit project

projects/tarantool/Dockerfile
Seed corpus has been moved to a separate Git repository, see [1].
1. https://github.com/tarantool/tarantool/pull/11042
=> tarantool: fix seed corpus

projects/data-encoding/build.sh
The unpublished v3-preview feature has been removed by https://github.com/ia0/data-encoding/pull/120. The v3 development version will be added in a separate folder. I'll update the build script to add the fuzzing for v3 once that's done.
=> Update build script for data-encoding to fix broken build

projects/pdfplumber/Dockerfile
This pull request integrates the Dockerfile needed to build the fuzzers for pdfplumber.
Note: The fuzzers were NOT merged upstream following discussion with the project maintainer [here](https://github.com/jsvine/pdfplumber/pull/1245#issuecomment-2581682100) and with the precedence for out-of-repo fuzzers established [here](https://github.com/google/oss-fuzz/issues/12467)
=> Pdfplumber: Integration

projects/flask/fuzz_werkzeug_url.py
Werkzeug used by Flask experienced a major cleanup in 2023 https://github.com/pallets/werkzeug/pull/2768.
Multiple functions tested by OSS-Fuzz were deleted since they were available in the Python standard library. Because of this, Flask OSS-Fuzz builds have been failing since August 14, 2023.
=> flask: drop checks of deleted functions

infra/base-images/base-builder/compile, infra/base-images/base-clang/Dockerfile
Adds a light version of FI that should work on all projects. This will only be used if the existing FI does not work, e.g. due to failures around LTO.
Also starts using the CLI version of fuzz-introspector as opposed to calling `main.py`.
=> infra: update introspector and add new light version

projects/tarantool/build.sh
If the dict filename is the same as your target binary name
(i.e. `%fuzz_target%.dict`), it will be automatically used.
If the name is different (e.g. because it is shared by several
targets), specify this in `.options` file.
1. https://google.github.io/oss-fuzz/getting-started/new-project-guide/#dictionaries
Needed for https://github.com/tarantool/tarantool/pull/10911
=> tarantool: use libfuzzer options

projects/numpy/Dockerfile
Upgrade Python to 3.11, as it's the minimum requirement for numpy.
Fixes: https://issues.oss-fuzz.com/issues/382554731
=> numpy: Fix build

infra/experimental/chronos/build_cache_local.sh
- Improve logging to make it easier to derive log-based metrics on GCP.
- Compare compile times between replay and ccache and pick the better one.
=> chronos: Some fixes.

projects/wasmtime/build.sh
Wasmtime's initial corpus repository hasn't been updated in years. Many of its files are entirely unused at this time. Other preexisting corpus files no longer test what they originally did as Wasmtime's fuzzing relies on interpreting the input as a "DNA string" where the exact meaning of the DNA changes over time as we change fuzz targets. We concluded recently in Wasmtime to archive/delete the repository we were previously using to avoid confusion so this change follows-up on the OSS-Fuzz side of thing to remove usage of this outdated corpus.
cc @fitzgen
=> wasmtime: Remove usage of initialized corpus

projects/surrealdb/project.yaml
Tidy up of the surrealdb project.yaml to remove inactive email addresses of former SurrealDB employees or project contributors.
=> Remove former SurrealDB employee from auto-ccs

projects/vlc/project.yaml
We handle all security issues through security@videolan.org exclusively now and want to limit the scope.
=> vlc: update primary contact and drop external CCs

projects/libxml2/Dockerfile
There's a (seemingly harmless) bug in glibc's iconv() which makes one of our assertions fail.
=> libxml2: Disable TSCII charset in glibc

projects/apache-commons-collections/CollectionsBidiMapFuzzer.java
PR Description:
In this PR  improve fuzzing coverage handle more diverse input sizes, and ensure the `BidiMap` is freshly initialized for each test. The changes focus on improving the randomness of the fuzzed input, ensuring that each test runs with an independent map instance, and making the fuzzing more comprehensive by introducing variable-length strings.
Changes Done in this:
1. **BidiMap Initialization Inside `runTest` Method**:
- The `BidiMap` (`m_bidiMap`) is now instantiated inside the `runTest` method, ensuring that each fuzzing test operates on a fresh map instance. This avoids potential issues where the map state is carried over between tests, ensuring more accurate results.
2. **Handling Variable Size Strings**:
- The fuzzed input strings are now consumed with random lengths …
=> Update CollectionsBidiMapFuzzer.java Enhance Fuzzing Coverage and Input Variability for CollectionsBidiMapFuzzer

projects/gast/fuzz_api.py
Test basic api
Test basic invariant
=> gast: improve api coverage

projects/numpy/Dockerfile, projects/numpy/build.sh, projects/numpy/fuzz_binary_loader.options, projects/numpy/fuzz_binary_loader.py
This requires changing the amount of memory made available to the fuzzer, so also add the logic to copy fuzzer option files.
=> numpy: Fuzz binary matrix loader

projects/kubevirt/Dockerfile, projects/kubevirt/build.sh
Adds 5 fuzzers that are in PRs upstream.
=> kubevirt: run new fuzzers

projects/vlc/Dockerfile, projects/vlc/build.sh
- Remove useless vlc-demux-libfuzzer output target
- Use the official VideoLAN/vlc repository
- Add seeds and dicts: create one output target per format
- Add mkv, ogg, xml support
=> vlc: use official repo + add seeds and dicts + add demuxers

projects/libxml2/Dockerfile
This reverts commit e007cb7be3868cb4f55e030c6c2a4199ca750bb6.
This change didn't affect the base-runner image where it would be needed.
=> Revert "libxml2: Disable TSCII charset in glibc (#13003)"

projects/zlib/gzio_fuzzer.c
Otherwise gzio_fuzzer is blocked, while it does increase the number of functions statically reachable, see
https://storage.googleapis.com/oss-fuzz-introspector/zlib/inspector-report/20250211/fuzz_report.html
=> gzip: constrain input_buffer size

projects/kubevirt/Dockerfile, projects/kubevirt/build.sh
Adds another fuzzer to Kubevirt
=> Kubevirt: add fuzzer

infra/experimental/chronos/build_cache_local.sh
Creates chrono images in a way where entrypoint is not set in the resulting docker image. This makes them equivalent from an entrypoint perspective to non-chronos images.
=> experimental: fix chronos entrypoint setting

projects/apache-commons-codec/build.sh, projects/calcite-avatica/build.sh, projects/docker-client/build.sh, projects/graphql-java/build.sh, projects/java-diff-utils/build.sh, projects/java-uuid-generator/build.sh, projects/jolt/build.sh, projects/ohc/build.sh, projects/twelve-monkeys/build.sh, projects/twitter4j/build.sh
This PR fixes build script for some JVM projects. The purpose is to avoid compiling wrong fuzzers when copying is done in FI light analysis.
=> JVM: Fix build script for some jvm projects

infra/base-images/base-builder/compile
This PR fixes the compile script in the base-builder to make the introspector build of JVM and rust project follow new route that has been bumped in #12983.
=> infra: Fix the compile script to match new FI frontend

projects/gson/build.sh, projects/junrar/build.sh, projects/rome/build.sh
The general `find` command is causing some friction in fuzz introspector projects. This PR makes sure the projects only build the fuzzing harnesses that are meant to be build.
=> gson,junrar,rome: refine build scripts

projects/sketches-core/Dockerfile, projects/sketches-core/build.sh
This PR fixes the build for sketches-core when the updated upstream repository requires JDK17 to build.
=> sketches-core: Fix build

projects/gnutls/Dockerfile, projects/gnutls/build.sh
1. gnutls: Fix build failure related to gnulib specific commit reference
Fix build failure caused by libtasn1 (a dependency of gnutls) bootstrap process that sets the gnulib git checkout to a specific commit ID. The commit ID must be present in the local checkout to succeed otherwise an error like "fatal: reference is not a tree: <commit hash ID>". A depth of 500 was chosen as a compromise to make it likely that the commit will be present as long as libtasn1 pulls in a fairly recent version and cloning the whole gnulib repo which is quite large.
2. gnutls: Fix build failure due to newer required autoconf and cleanup
Fix a build failure for GNUTLS caused by GNUTLS requiring a minimum version of autoconf 2.71 but the fuzzer base image is Ubuntu 20 based which has 2.6x. Also fix some …
=> gnutls: Fix build

projects/pdfplumber/Dockerfile
Rather than fuzzing main, this PR changes the fuzz build to use the develop branch
=> Pdfplumber: Update Target Branch for Fuzzing

projects/vlc/build.sh, projects/vlc/project.yaml
Setting env from a script does not work from oss-fuzz, so append the target to the binary name, cf. https://code.videolan.org/videolan/vlc/-/merge_requests/6879
=> vlc: add a cc and fix targets

projects/caffeine/CaffeineSpecFuzzer.java, projects/caffeine/Dockerfile, projects/caffeine/build.sh, projects/caffeine/project.yaml
[Caffeine Cache](https://github.com/ben-manes/caffeine) is the [successor](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/cache/CacheBuilder.html#prefer-caffeine-over-guava-s-caching-api-heading) to Google Guava's Cache. It had 250M downloads from Maven Central in 2024.
I have tested this locally based on your documented steps.
/cc @cpovirk
=> caffeine: Initial integration

projects/fips203/project.yaml
This Rust crate fully implements the recently finalized version of the FIPS 203 spec at https://csrc.nist.gov/pubs/fips/203/final
It is the post-quantum crypto Module-Lattice-Based Key-Encapsulation Mechanism Standard.
The code is a freely available open source library intended for general use.
=> Init FIPS 203 Post-quantum crypto in Rust

projects/kubevirt/Dockerfile, projects/kubevirt/FuzzAdmitter.options, projects/kubevirt/FuzzWebhookAdmitters.options, projects/kubevirt/FuzzWebhookMutators.options, projects/kubevirt/build.sh
Adds three fuzzers. These take a long time (about 2 minutes) to start, so we need to increase the timeout for all three fuzzers.
=> kubevirt: add more upstream fuzzers

projects/numpy/Dockerfile
This is missing to gather proper coverage info. Without this package the introspector page for numpy is no longer updated.
=> numpy - Add missing coverage package

projects/haproxy/build.sh
HAProxy's Makefile changed years ago, causing the sed pattern to no longer apply. As a result, the build flags were not forwarded, and the fuzzer ran without instrumentation or feedback. This patch updates the patterns to ensure proper flag forwarding.
=> [haproxy] Fix HAProxy build issue

projects/protobuf-python/Dockerfile, projects/protobuf-python/build.sh
//python/dist currently does not build with bzlmod, since we don't support system_python in bzlmod yet.
```
Skipping '//python/dist:binary_wheel': error loading package 'python/dist': Unable to find package for @@[unknown repo 'system_python' requested from @@]//:version.bzl: The repository '@@[unknown repo 'system_python' requested from @@]' could not be resolved: No repository visible as '@system_python' from main repository.
Step #1: [0m[91mERROR: error loading package 'python/dist': Unable to find package for @@[unknown repo 'system_python' requested from @@]//:version.bzl: The repository '@@[unknown repo 'system_python' requested from @@]' could not be resolved: No repository visible as '@system_python' from main repository.
```
=> Update protobuf-python bazel build to set --noenable_bzlmod

infra/base-images/base-builder/jcc/jcc.go
Code fixing features are no longer required, but its main structure may be reused later.
=> Remove code fixing features in JCC

projects/jsoncpp/build.sh
This patch ensures that jsoncpp is consistently built with C++17 by modifying CMakeLists.txt to replace CMAKE_CXX_STANDARD 11 with CMAKE_CXX_STANDARD 17.
=> jsoncpp: Fix build

projects/unblob/Dockerfile, projects/unblob/build.sh
We recently merged⁰ the Rust part of unblob (so called 'unblob-native') into unblob and re-organized the repository structure in the process.
This broke OSS-fuzz integration for unblob since the bash script that installs dependencies no longer lives at this address.
[0] https://github.com/onekey-sec/unblob/pull/1096/
=> unblob: fix dependency install

projects/libprotobuf-mutator/build.sh
.. to keep examples `expat_example` and `libxml2_example` that are fuzzed in OSS-Fuzz using latest libexpat and libxml2
Related: https://github.com/google/libprotobuf-mutator/pull/273
CC @vitalybuka
=> libprotobuf-mutator: Start using `-DLIB_PROTO_MUTATOR_EXAMPLES_USE_LATEST=ON`

projects/juju/Dockerfile, projects/juju/build.sh, projects/juju/devices_fuzzer.go
The parse constraint function was moved to a better location, but the fuzzer wasn't updated.
This fixes: https://issues.oss-fuzz.com/issues/42538415
=> fix: juju build failure

projects/xmldom/build.sh
it was [dropped from `devDependencies` in xmldom](https://github.com/xmldom/xmldom/pull/845), since it can no longer be installed reliably on all machines.
=> xmldom: install @jazzer.js/core as part of build.sh

projects/behaviortreecpp/Dockerfile, projects/behaviortreecpp/build.sh, projects/behaviortreecpp/project.yaml
This is an initial integration for BehaviorTree.CPP ([website](https://www.behaviortree.dev/), [repo](https://github.com/BehaviorTree/BehaviorTree.CPP)) a popular library that allows to e.g., structure the switching between different tasks in an autonomous agent, such as a robot or a virtual entity in a computer game.
This PR can be reviewed but needs to wait until the https://github.com/BehaviorTree/BehaviorTree.CPP/pull/925 PR is merged and the harnesses land upstream.
Also, @facontidavide or @miccol either of you as a core-maintainer need to agree on this onboarding of the project here, so if you do, please just ACK this.
=> feat: initial integration behaviortreecpp

projects/expr/project.yaml
Hello,
I've recently switched off my G-Suite on `anton@medv.io` and do not use Google account any more.
I create a new google account to access OSS-Fuzz: `antonmedvio@gmail.com`. 
Thanks!
=> Change Expr email

projects/karchive/karchive_fuzzer.cc
Implemented functionality in the PR to not only handle archive opening and closing operations but also traverse its contents to retrieve file metadata including names, dates, sizes, etc. for all files within the specified archive. Assigned by @tsdgeos. 🎉
=> KArchive: traverse the contents of the archive

projects/libtheora/build.sh
gcr.io/oss-fuzz-base/base-builder is using an older autoconf version, so we can relax this requirement which is just to avoid warnings.
=> libtheora: patch configure to allow older autoconf

projects/mpv/Dockerfile, projects/mpv/build.sh
- Switch to base-builder-rust
- Create venv for pip installed packages
- Set rustc target explicity, needed for i386 build
- Don't fail if subprojects directory already exists
- Don't compress Matroska files to speed zip creation, they are not really compressible anyway.
=> mpv: add support for Rust

projects/geos/Dockerfile, projects/geos/build.sh, projects/mysql-server/Dockerfile, projects/mysql-server/build.sh, projects/ntp/Dockerfile, projects/ntp/build.sh
There are some projects that add fuzz targets via a diff file applied in the `build.sh`.
This is incompatible with OSS-Fuzz-Gen, because OSS-Fuzz-Gen injects targets via a Dockerfile `COPY`. When the patch is later applied in the build process, this causes a conflict.
Instead, we do the patching as a `RUN` step in the Dockerfile to avoid this.
Note: mysql-server and ntp are currently broken because the patch no longer applies. This needs to be fixed in a followup.
=> Various projects: run `git apply` in Dockerfile instead.

infra/build/functions/build_project.py
This is likely breaking any project that has a relative WORKDIR set.
=>  Fix WORKDIR parsing for OSS-Fuzz-Gen.

projects/mpv/Dockerfile, projects/mpv/build.sh
Apparently, the Docker version on build machines is older and doesn't support heredoc. It differs from the ones tested on CI before the merge.
Also, set RUSTC directly with the target because Meson doesn't append rust_args in all invocations. This is mostly a cosmetic change, as it was already appended where needed in our case.
Fixes: 44b432da8f057230a3efca529b6739cdbb373b70
=> mpv: Don't use heredoc in Dockerfile

projects/libass/Dockerfile, projects/libass/build.sh, projects/libass/libass_fuzzer.options
The value was chosen based on research don in
https://github.com/libass/libass/pull/854 and
will hopefully avoid further timeout cases
and increase fuzzing efficacy.
While all currently used fuzzing engnes support flags to limit
the input length (-G for AFL and -max_file_size for honggfuzz),
there appears to be no way to set them via the options file.
It seems only the "libfuzzer" section is parsed and then incompletely
translated to other engines.
Thus the limit is also enforced by the fuzzer itself via
a build time toggle (as recommended in OSS Fuzz docs).
Note: the current corpus contains >200 samples larger than
the chosen limit and should be dropped. They don't
significantly contribute to coverage anyway.
=> libass: limit max input length

projects/bitcoin-core/Dockerfile
Skip installing CMake from the base image repository for the following reasons:
1. The base image is based on Ubuntu Focal 20.04, whose repository provides CMake version 3.16.3, which is incompatible with Bitcoin Core's minimum requirements.
2. The base image [installs](https://github.com/google/oss-fuzz/blob/b4c1a273955cf84b991be6e39038c485c0b93560/infra/base-images/base-clang/Dockerfile#L25-L34) a newer CMake version specified by the `CMAKE_VERSION` variable, which is currently set to 3.29.2.
---
Additionally, other dependency packages have been updated after migration to CMake.
=> bitcoin-core: Update dependency packages

projects/circl/Dockerfile, projects/circl/build.sh
Build is failing since it cannot fetch the corpus from an empty bucket.
https://issues.oss-fuzz.com/issues/399183983
=> circl: Removing fetch from empty bucket.

infra/build_specified_commit.py
`distutils` is deprecated and removed in Python 3.12 (this has broken osv.dev).
The [migration advice](https://peps.python.org/pep-0632/#migration-advice) says to replace `distutils.spawn.find_executable` with `shutil.which`.
`distutils.dir_util.copy_tree` is still used in [`infra/cifuzz/filestore/filesystem`](https://github.com/google/oss-fuzz/blob/72c3485bfd7eb0456646c51cf24879d3e7f5742a/infra/cifuzz/filestore/filesystem/__init__.py#L21), but I'm not sure what the correct replacement for that is.
=> use `shutil.which` instead of `distutils.spawn.find_executable`

projects/powsybl-java/DeserializeFuzzer.java, projects/powsybl-java/LoadFlowFuzzer.java, projects/powsybl-java/ParseFuzzer.java, projects/powsybl-java/build.sh
This PR adds and fixes fuzzers for powsybl-java project. This PR also fixes the build script to prepare corpus for the new DeserializeFuzzer.
=> powsybl-java: fix and add fuzzers

projects/powsybl-java/ParseFuzzer.java
This PR fixes the ParseFuzzer by adding more parsing method in the powsybl-java module.
This PR also fixes the extraction of random data to ensure both the byte array and switch choice must have data to process.
=> powsybl-java: Fix ParseFuzzer

infra/build/functions/target_experiment.py
1. Insufficient timeout. Cloud Build Timeout = waiting time + execution time. Some executions timed out because they waited for too long. Since Cloud Build does not have an execution-only timeout config, the new 12 hour overall time out should be sufficient.
2. Cleanup JCC. We have to do this because some projects are not even compatible with the current minimum scaffold. This mostly happens when they identifying which CC is being used, and is likely because of the way they read/expect stdout/stderr from commands.
BTW, we can further simplify this script. E.g., no need to save build log as compilation is done within agents.
But it's not a high priority at this point. We can do it in GSoC.
=> Fixes 2 problems in target_experiment.py

projects/bitcoin-core/build.sh
This PR is required following the merge of https://github.com/bitcoin/bitcoin/pull/31849.
Additionally, the path workaround has been removed.
Fixes https://github.com/bitcoin/bitcoin/issues/32167.
=> bitcoin-core: Fix build for `i386`

projects/karchive/Dockerfile, projects/karchive/build.sh, projects/karchive/karchive_fuzzer.cc, projects/kcodecs/Dockerfile, projects/kimageformats/Dockerfile
- Added OpenSSL to fix failing KArchive fuzzer build.  
- Used absolute paths to remove Docker warnings.  
- Fixed `b.reset()` failing when the device is closed, preventing unnecessary error messages.  
@tsdgeos (Let me know if any changes are needed!)
=> karchive, kcodecs, kimageformats: Add openssl and remove docker warnings

projects/xz/build.sh, projects/xz/project.yaml
Lasse and I were discussing this in the context of CVE-2025-31115, and really, it seems like we want to fuzz with assertions enabled to better catch edge-cases (not that it would've found this, but we added a bunch more because of it).
The encoder has more coverage than the decoder at least right now.
=> xz: enable assertions; more fuzzing engines; i386

infra/build/functions/build_project.py, infra/build/functions/request_build.py
Previously this failed because only local builds were considered "fuzzing builds".
Fixes: b/409630399
=> Push images in C/C++ builds.

infra/build/functions/build_project.py
get_build_steps_for_project is used in
https://github.com/google/oss-fuzz/blob/a15eb3e87a6623b2fdcd26cee04eb5720deaa22a/infra/build/functions/target_experiment.py#L77
=> Partialy revert https://github.com/google/oss-fuzz/pull/13207

projects/karchive/karchive_fuzzer.cc
Set a dummy password on k7zip handler to trigger decryption code for encrypted archives.
=> KArchive: Set dummy password to force K7Zip decryption

infra/base-images/base-clang/Dockerfile, infra/base-images/base-clang/README.md, infra/base-images/base-clang/checkout_build_install_llvm.sh
This build will contain all binaries/libraries.
Additionally, libcxx is bootstrapped and LLVM/clang is built with llvm in this mode. This is useful for building tools which link against LLVM/clang, because otherwise they'd have to link both libstdc++ and libc++.
=> Support a "full" base-clang build.

projects/askama/Dockerfile
The next version of askama (v0.14) will need at least rust 1.83 to compile. The current toolchain shipped in docker is rust 1.81, so the project could not get fuzzed anymore.
This PR sets the used toolchain to 1.83.
Cc @GuillaumeGomez
Related issue: <https://github.com/askama-rs/askama/pull/405>
=> askama: update used rust toolchain

projects/connectedhomeip/Dockerfile
- After PR https://github.com/project-chip/connectedhomeip/pull/38410
- we need to have environment variable `PW_PROJECT_ROOT`  pointing to CHIP_ROOT
=> [connectedhomeip][Fix ] Adapt OSS-Fuzz Dockerfile to changes in requirements.build.txt

infra/build/functions/request_build.py
This was removed in https://github.com/google/oss-fuzz/pull/13207, but we still need it in:
https://github.com/google/oss-fuzz/blob/84ff40bf62048901b6935eaa1f9664d76d5833eb/infra/build/functions/request_coverage_build.py#L30
and
https://github.com/google/oss-fuzz/blob/84ff40bf62048901b6935eaa1f9664d76d5833eb/infra/build/functions/request_introspector_build.py#L31
=> Restore request_build.get_empty_config

infra/base-images/base-builder/Dockerfile, infra/base-images/base-builder/indexer/fuzzing_engine.cc, infra/base-images/base-builder/indexer/index_build.py, infra/helper.py
1. Mark indexer executable after download
2. Support linking against LLVMFuzzerMutate (upstreamed)
3. Use real project name when making snapshot.
4. Handle projects that don't save their source to a directory with the same name as their project.
5. Handle partial failures.
6. Don't accidentally include other snapshots in snapshots.
7. Support indexing in helper.py
8. Provide PROJECT_NAME in helper.py shell command.
9. Remove trailing whitespace.
=> Fix problems indexing

projects/msquic/Dockerfile, projects/msquic/build.sh
The build.sh script for msquic assumes an output path with a configurable name, set during the build.  If that name changes, then the build breaks when the fuzzer attempts linkage, as the libmsquic.a library path is hard coded.
instead, pull the name from the cmake configuration and just use that, so we don't have to hard code it here
=> Improve output path resolution during build

infra/cifuzz/actions/run_fuzzers/action.yml, infra/cifuzz/config_utils.py, infra/cifuzz/external-actions/run_fuzzers/action.yml, infra/cifuzz/fuzz_target.py
Although the `parallel-fuzzing` input parameter is documented `to use all available cores for fuzzing` it is not how it currently works because as it is written in libfuzzer documentation [`These jobs will be run across a set of worker processes, by default using half of the available CPU cores;`](https://llvm.org/docs/LibFuzzer.html#:~:text=These%20jobs%20will%20be%20run%20across%20a%20set%20of%20worker%20processes%2C%20by%20default%20using%20half%20of%20the%20available%20CPU%20cores%3B)
I.e. currently when `parallel-fuzzing` is set to `true` it uses for example 1 core on a 2 cores machine.
The PR makes jobs number always match the workers number. Additionally a user may specify the number of cores to use manually.
=> [infra] Match workers and jobs per core

projects/spicy/project.yaml, projects/zeek/project.yaml
This adds a new team member the user lists for the zeek and spicy projects.
=> zeek/spicy: Add team member to user list

projects/opentelemetry-go-contrib/build.sh
Fix build errors https://oss-fuzz-build-logs.storage.googleapis.com/index.html#opentelemetry-go-contrib
Per https://github.com/open-telemetry/opentelemetry-go-contrib/pull/6796 which moved config directory to otelconf
=> Fix build for opentelemetry-go-contrib

infra/build/fuzz-introspector-webapp/cloudbuild.yaml
Running into OOMs again.
24Gi also requires 6 CPUs instead of 4.
=> Bump introspector webapp memory

projects/gitoxide/project.yaml
Fixes #13282
This updates `project.yaml` for `gitoxide`:
- The project was moved into the `GitoxideLabs` organization a while ago. This updates the URL.
- As described in [#13282](https://github.com/google/oss-fuzz/issues/13282), it is intended that I be able to access reports, but I cannot yet do so. This adds me to `auto_ccs`.
See the commit messages for more information including how to confirm that each of the changes are accurate/authorized.
cc @Byron
=> Update gitoxide repo URL and auto_ccs list

projects/quickjs/build.sh
Workers are not suitable for testing with libFuzzer due to their multi-file nature: each libFuzzer corpus item is independent and processed in isolation. As a result, it's not feasible to ensure that any referenced worker file is available or remains accessible during a fuzzing session.
Additionally, if the fuzz target references a nonexistent worker file and any handler is attached to it, it can cause the process to hang indefinitely.
This patch disables worker support during fuzzing to avoid such issues.
=> QuickJS: disable workers

infra/base-images/base-builder/indexer/fuzzing_engine.cc
This breaks projects like OpenSSL, which always return 1: https://github.com/openssl/openssl/blob/af5952d533b772ef8a3d7c666ed918acfc1dd911/fuzz/asn1.c#L302
libFuzzer doesn't do it either:
https://github.com/llvm/llvm-project/blob/f39696e7dee4f1dce8c10d2b17f987643c480895/compiler-rt/lib/fuzzer/FuzzerDriver.cpp#L651
=> Don't check return result of LLVMFuzzerInitialize.

projects/volcano/Dockerfile, projects/volcano/build.sh, projects/volcano/project.yaml
This PR adds initial integration of Volcano.
Volcano is a cloud-native batch scheduling system for Kubernetes hosted by the CNCF. It is used by companies such as Huawei, Baidu, JD.com.
=> Add initial integration of Volcano

infra/build/functions/fuzzbench.py, infra/build/functions/ood_upload_testcase.py, infra/build/functions/ood_upload_testcase_test.py
Add build steps to generate an access token and use it to upload a testcase if OSS-Fuzz on Demand found crashes.
- Add `ood_upload_testcase.py` script to which upload a testcase on ClusterFuzz External upload testcase endpoint.
- Add a build step to generate the access token using `gcloud auth print-access-token`.
- Add a build step to run  `ood_upload_testcase.py`  in Google Cloud Build.
Related to b/401215144 .
=> Add OSS-Fuzz on Demand build steps to upload testcases

infra/base-images/base-builder/indexer/clang_wrapper.py, infra/build/functions/build_project.py
- Handle duplicate invocations of the linker on the same binary.
- Handle `-fsanitize=address,fuzzer`
- Improve linker detection.
- Upload srcmap.json last, so we have don't end up with builds that just
upload a srcmap.json.
- Account for relative paths in `parse_dependency_file`
=> Indexer fixes

projects/poppler/Dockerfile, projects/poppler/build.sh
- Fix same issue as https://github.com/google/oss-fuzz/pull/13325.
- Pin libpng to avoid a build failure.
=> Fix poppler build.

infra/base-images/base-builder/indexer/index_build.py
Only archive the relevant target binary, in an attempt to save some disk space for projects with lots of targets (e.g. Imagemagick which has close to 150).
=> index_build: Don't archive all target binaries.

infra/base-images/base-builder/indexer/index_build.py
We didn't properly account for variations of .so extensions (e.g. .so.1, .so.2).
Split from https://github.com/google/oss-fuzz/pull/13342.
=> indexer: Fix .so copying

infra/helper.py
Replace this with an outer abspath call on the result to ensure the result is still absolute.
(In Python 3.9+, `__file__` is guaranteed to be absolute anyway).
=> helper: remove inner realpath call in calculating OSS_FUZZ_DIR.

projects/ossf-scorecard/probes_fuzzer.go
Ignore nil branch names for probes that process branches.
=> oss-scorecard: ignore nil branch names

infra/base-images/base-builder/indexer/README.md, infra/helper.py
- Add a passthrough for arguments to `index_build.py`.
- Add a `--docker_args` argument to add pass through args to docker.
- Add `--shell` to drop into a shell instead of running the indexer automatically.
=> helper: Add additional index arguments.

projects/clamav/Dockerfile
The oss-fuzz base-builder-rust image uses a specific version of Rust that is updated occasionally. During feature development, sometimes the ClamAV project requires a newer version of Rust.
This commit:
- Updates to the latest nightly toolchain.
- Changes the RUSTUP_TOOLCHAIN environment variable from the specific- version to the updated version.
=> [clamav] Fix build when newer Rust version required

projects/tarantool/build.sh
An input data for fuzzing tests can contain a LuaJIT cdata objects (1LL, 1ULL, etc) that triggers arithmetic operations in LuaJIT, UBSan handlers use FPR registers, and are called in the functions of purely GPR registers. This is fraught with inconsistence on LuaJIT traces and can lead to false positives crashes.
Important detail: these crashes cannot be reproduced without OSS Fuzz environment in Docker containers.
Examples of false positive reports:
- https://issues.oss-fuzz.com/issues/420248727
- https://issues.oss-fuzz.com/issues/393404275
Investigated by Sergey Kaplun (@Buristan).
=> tarantool: disable unsigned-integer-overflow

projects/varnish/Dockerfile
varnish-cache is now using vtest as a submodule and hence needs a recursive clone. Ref: https://github.com/varnishcache/varnish-cache/pull/4333
=> varnish: now needs recursive clone

projects/libhtp/project.yaml
This extra space is causing build status to fail
=> Fix typo on email from auto_ccs in libhtp

projects/graphicsmagick/Dockerfile
The GraphicsMagick build includes libxml2, and libxml2 now requires Automake 1.16.3 or later. Install Automake 1.16.5 in order to satisfy build requirements.
=> graphicsmagick: Add automake 1.16.5 since libxml2 build requires it.

projects/guava/build.sh
This is necessary because of something about our cross-module
dependencies.
See:
- https://github.com/google/guava/issues/2193
- https://g-issues.oss-fuzz.com/issues/396460407
=> Use `mvn install` for Guava instead of `mvn package`.

projects/golang/tiff_fuzzer.go
A small tiff can decode into a large image.
Users who want to limit memory consumption need to validate images prior to decompression.
Skip decompressing tiffs larger than 16k in either dimension.
=> golang: limit size of decoded tiffs

projects/golang/fuzz_webp_decode.options
We see a not insignificant number of timeout issues when running the fuzz_webp_decode target, which appear to magically resolve themselves despite the underlying code not changing.
I expect that running the target under ASAN, with limited resources, is just a little slow.
Bump the timeout from the default (60s) to 120s. I expect this will just silence the timeouts.
=> golang: increase timeout for webp decoding target

projects/ffmpeg/Dockerfile, projects/ffmpeg/build.sh, projects/ffmpeg/replay_build.sh
This is meant to be a manual override over what chronos (https://github.com/google/oss-fuzz/tree/master/infra/experimental/chronos) generates.
The idea is we'll snapshot the ffmpeg build container after running compile into a new Docker image. This image will have build artifacts saved so that subsequent `make` calls only trigger on changed files.
This makes rebuilding a specific target **a lot** faster (From 2600 seconds down to instantaneous).
This does change the `build.sh` -- merging the two ./configure calls down to one in order to faciliate this.
=> Add a `replay_build.sh` for ffmpeg.

infra/base-images/base-builder/Dockerfile, infra/base-images/base-builder/make_build_replayable.py
Add a Python script which stubs out build configure steps, build cleaning, and makes various commands (e.g. mkdir) repeatable.
=> Implement a new approach to making recompile faster.

projects/glaze/Dockerfile
I missed to point the repository to upstream after the initial integration was done.
=> [glaze] use upstream repository

projects/js-yaml/fuzz.js
There were three issues with the fuzz driver for js-yaml:
1. With `catch (YAMLException)` I believe the intent was to ignore instances of `YAMLException` only. However, catch statements like these would ignore _all_ exceptions in JavaScript. Added an explicit `instanceof` check.
2. `getSchema` does not have the intended `options` object in scope. Instead, it sets `schema` on the _global_ options object that Jazzer.js [defines](https://github.com/CodeIntelligenceTesting/jazzer.js/blob/592be5c6d7f453e96822be41fe3f2a1351b8fd96/packages/core/core.ts#L129). Return a schema from `getSchema` instead.
3. Schemas are supposed to be instances of the `Schema` class, not strings. Replace string values with the constants this library [exports](https://github.com/nodeca/js-yaml/blob/0d3ca7a27b03a6c97479 …
=> js-yaml: fix driver

projects/postgresql/build.sh, projects/postgresql/fuzzer/simple_query_fuzzer.c
This PR fixes the simple_query_fuzzer and reactive it from the build script.
=> postgresql: Fix fuzzer

projects/goipp/Dockerfile, projects/goipp/build.sh, projects/goipp/project.yaml
This PR adds initial integration for the [goipp](https://github.com/OpenPrinting/goipp) project - a Go implementation of the Internet Printing Protocol (IPP) core.
All fuzz harnesses are maintained externally in the [OpenPrinting/fuzzing](https://github.com/OpenPrinting/fuzzing) repository.
CC: @tillkamppeter @iosifache @fish98
=> [goipp] Initial integration

projects/golang/Dockerfile
Follow-up to #13426, in which I didn't realize I needed to add the options file to the Dockerfile.
=> golang: add options to Dockerfile

infra/base-images/base-builder/make_build_replayable.py
/bin/sh is already copied earlier in the script after being overwritten. We don't need to do the copy twice.
=> make_build_replayable: avoid copying /bin/sh twice

projects/ffmpeg/Dockerfile, projects/ffmpeg/build.sh, projects/ffmpeg/name_mappings.py, projects/ffmpeg/replay_build.sh
Add a name_mapping.py to compute mappings and use that everywhere we need to map between OSS-Fuzz target binary name / FFmpeg make target name.
This preserves existing binary names to avoid mass migrations. New decoder fuzzers will have the name format `ffmpeg_AV_CODEC_ID_<ID>_DEC_fuzzer` and new encoder fuzzers where there was previously a decoder fuzzer only
will have the format `ffmpeg_AV_CODEC_ID_<ID>_ENC_fuzzer`. All other encoder fuzzers will keep the current format
`ffmpeg_AV_CODEC_ID_<ID>_fuzzer`
Fixes #13472.
=> ffmpeg: Differentiate decoder fuzzers.

projects/opus/build.sh
Before:
```
opus: Compile times: Vanilla=185; Replay=67;
```
After:
```
opus: Compile times: Vanilla=81; Replay=20;
```
=> opus: improve build performance

infra/base-images/base-builder/make_build_replayable.py
Re-running these should not necessary.
=> make_build_replayable: stub out `git submodule`.

infra/build/functions/build_project.py
These are necessary after https://github.com/google/oss-fuzz/pull/13512, which unfortunately broke a lot of projects.
=> Add more cflags.

projects/jsonnet/build.sh, projects/jsonnet/run_tests.sh
```
$ docker run --rm -ti us-central1-docker.pkg.dev/oss-fuzz/oss-fuzz-gen/jsonnet-ofg-cached-address /src/run_tests.sh
Test project /src/jsonnet/build
Start  1: unicode_test
1/10 Test  #1: unicode_test .....................   Passed    0.06 sec
Start  2: lexer_test
2/10 Test  #2: lexer_test .......................   Passed    0.01 sec
Start  3: parser_test
3/10 Test  #3: parser_test ......................   Passed    0.02 sec
Start  4: libjsonnet_test
4/10 Test  #4: libjsonnet_test ..................   Passed    0.25 sec
Start  5: libjsonnet_test_file
5/10 Test  #5: libjsonnet_test_file .............   Passed    0.31 sec
Start  6: libjsonnet_test_snippet
6/10 Test  #6: libjsonnet_test_snippet ..........   Passed    0.23 sec
Start  7: jsonnet_test_snippet
7/10 Test  #7: …
```
=> jsonnet: add run_tests.sh

infra/experimental/chronos/check_tests.sh
jsonnet:
```
./infra/experimental/chronos/check_tests.sh jsonnet c++
...
...
Test project /src/jsonnet/build
Start  1: unicode_test
1/10 Test  #1: unicode_test .....................   Passed    0.06 sec
Start  2: lexer_test
2/10 Test  #2: lexer_test .......................   Passed    0.01 sec
Start  3: parser_test
3/10 Test  #3: parser_test ......................   Passed    0.03 sec
Start  4: libjsonnet_test
4/10 Test  #4: libjsonnet_test ..................   Passed    0.26 sec
Start  5: libjsonnet_test_file
5/10 Test  #5: libjsonnet_test_file .............   Passed    0.32 sec
Start  6: libjsonnet_test_snippet
6/10 Test  #6: libjsonnet_test_snippet ..........   Passed    0.23 sec
Start  7: jsonnet_test_snippet
7/10 Test  #7: jsonnet_test_snippet .............   Passed …
```
=> chronos: add helper script for quickly testing run_test.sh

projects/tink-cc/Dockerfile, projects/tink-cc/build.sh, projects/tink-cc/fuzzing_CMake, projects/tink-cc/project.yaml, projects/tink-cc/tink_encrypt_decrypt_fuzzer.cc
Tink has been split into projects for the respective implementation languages. This was part of the reason that the build was broken.
This PR renames the project and fixes a few other nits to fix the build.
=> tink: rename and fix broken build

projects/libssh/build.sh, projects/libssh/run_tests.sh
Output from `infra/experimental/chronos/check_tests.sh libssh c`:
```
Test project /work/build
Start  1: torture_bignum
1/40 Test  #1: torture_bignum ......................   Passed    0.01 sec
Start  2: torture_buffer
2/40 Test  #2: torture_buffer ......................   Passed    0.79 sec
Start  3: torture_bytearray
3/40 Test  #3: torture_bytearray ...................   Passed    0.01 sec
Start  4: torture_callbacks
4/40 Test  #4: torture_callbacks ...................   Passed    0.01 sec
Start  5: torture_crypto
5/40 Test  #5: torture_crypto ......................   Passed    0.01 sec
Start  6: torture_init
6/40 Test  #6: torture_init ........................   Passed    0.01 sec
Start  7: torture_list
7/40 Test  #7: torture_list ........................   Passed …
```
=> libssh: add run_tests.sh

infra/build/functions/build_project.py
These are no longer necessary. We can just use
https://github.com/google/oss-fuzz/commit/0714250242802f265ff62bef1ed2f058abdf7436
=> Remove hacks in index image building.

projects/glslang/build.sh, projects/glslang/run_tests.sh
```
$ ./infra/experimental/chronos/check_tests.sh glslang c++
...
...
+ cd build                                                                                                                                                                                                                                                         
+ make test                                                                                                                                                                                                                                                         …
```
=> glslang: add run_tests.sh

projects/quickjs/run_tests.sh, projects/quickjs/run_tests_patch.diff
Adds `run_tests.sh` for the quickjs project.
output from `infra/experimental/chronos/check_tests.sh quickjs c`
```
./qjs tests/test_closure.js
./qjs tests/test_language.js
./qjs --std tests/test_builtin.js
./qjs tests/test_loop.js
./qjs tests/test_bigint.js
./qjs tests/test_cyclic_import.js
./qjs tests/test_std.js
./qjs tests/test_bjson.js
./qjs examples/test_point.js
```
=> quickjs: add run_test.sh

projects/haproxy/build.sh, projects/haproxy/run_tests.sh
Adds run_tests.sh the haproxy project.
Output from `infra/experimental/chronos/check_tests.sh haproxy c`:
```
########################## Preparing to run unit tests ##########################
Testing with haproxy version: 3.3-dev2-378c18-74
Target : generic
Options : -51DEGREES -ACCEPT4 -BACKTRACE -CLOSEFROM -CPU_AFFINITY -CRYPT_H -DEVICEATLAS -DL -ENGINE -EPOLL -EVPORTS -GETADDRINFO -KQUEUE -LIBATOMIC -LI
BCRYPT -LINUX_CAP -LINUX_SPLICE -LINUX_TPROXY -LUA -MATH -MEMORY_PROFILING -NETFILTER -NS -OBSOLETE_LINKER -OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT
-PCRE -PCRE2 -PCRE2_JIT -PCRE_JIT +POLL -PRCTL -PROCCTL -PROMEX -PTHREAD_EMULATION -QUIC …
```
=> haproxy: add run_tests.sh

projects/cert-manager/Dockerfile
cert-manager has bumped go to 1.24.0.
=> cert-manager: bump go

projects/spirv-cross/build.sh, projects/spirv-cross/patch.diff, projects/spirv-cross/run_tests.sh
```
$ ./infra/experimental/chronos/check_tests.sh spirv-cross c++
...
...
Testing MSL shader: shaders-ue4-no-opt/asm/tese/ds-texcoord-array.asm.tese
Reference shader path: reference/shaders-ue4-no-opt/asm/tese/ds-texcoord-array.asm.tese
metal toolkit does not exist, ignoring further attempts to use it.
Testing MSL shader: shaders-ue4-no-opt/asm/frag/array-copy-error.asm.invalid.frag
Reference shader path: reference/shaders-ue4-no-opt/asm/frag/array-copy-error.asm.invalid.frag
Testing MSL shader: shaders-ue4-no-opt/asm/frag/accesschain-invalid-expression.asm.invalid.frag
Reference shader path: …
```
=> spirv-cross: add run_tests.sh

projects/jsoncpp/Dockerfile, projects/jsoncpp/build.sh, projects/jsoncpp/run_tests.sh
Adds `run_tests.sh` to the jsoncpp project.
Output of ./infra/experimental/chronos/check_tests.sh jsoncpp c++:
```
Test project /src/jsoncpp/build
Start 1: jsoncpp_readerwriter
1/3 Test #1: jsoncpp_readerwriter ................   Passed    4.95 sec
Start 2: jsoncpp_readerwriter_json_checker
2/3 Test #2: jsoncpp_readerwriter_json_checker ...   Passed    6.45 sec
Start 3: jsoncpp_test
3/3 Test #3: jsoncpp_test ........................   Passed    0.05 sec
100% tests passed, 0 tests failed out of 3
Total Test time (real) =  11.46 sec
```
=> jsoncpp: add run_tests.sh

projects/json-c/Dockerfile, projects/json-c/run_tests.sh
Adds `run_tests.sh` to the jsonc project.
Output of `./infra/experimental/chronos/check_tests.sh jsoncpp c++`:
```
Test project /src/json-c/json-c-build
Start  1: test1
1/25 Test  #1: test1 ............................   Passed    0.22 sec
Start  2: test2
2/25 Test  #2: test2 ............................   Passed    0.15 sec
Start  3: test4
3/25 Test  #3: test4 ............................   Passed    0.05 sec
Start  4: testReplaceExisting
4/25 Test  #4: testReplaceExisting ..............   Passed    0.04 sec
Start  5: test_cast
5/25 Test  #5: test_cast ........................   Passed    0.05 sec
Start  6: test_charcase
6/25 …
```
=> jsonc: add run_tests.sh

projects/yaml-cpp/Dockerfile, projects/yaml-cpp/run_tests.sh
Adds `run_tests.sh` to the expat project.
Output of ./infra/experimental/chronos/check_tests.sh yaml-cpp c++:
```
Test project /src/yaml-cpp/build
Start 1: yaml-cpp::test
1/1 Test #1: yaml-cpp::test ...................   Passed    1.32 sec
100% tests passed, 0 tests failed out of 1
Total Test time (real) =   1.32 sec
```
=> yaml-cpp: add run_tests.sh

projects/libsrtp/Dockerfile, projects/libsrtp/run_tests.sh
`infra/experimental/chronos/check_tests.sh libsrtp c`
```
...
Build done. Please run 'make runtest' to run self tests.                                                                                                   
running libsrtp3 test applications...                                                                                                                      
crypto/test/cipher_driver -v >/dev/null                                                                                                                    
crypto/test/kernel_driver -v >/dev/null                                                                                                                    
test/test_srtp >/dev/null …
```
=> libsrtp: add run_tests.sh

projects/fio/build.sh, projects/fio/run_tests.sh
Adds run_tests.sh to the fio project.
`infra/experimental/chronos/check_tests.sh fio c`
```
...
Run Summary:    Type  Total    Ran Passed Failed Inactive                                                                                                 
suites      7      7    n/a      0        0                    
tests     16     16     16      0        0                    
asserts     63     63     63      0      n/a                    
Elapsed time =    0.000 seconds
```
=> fio: add run_tests.sh

projects/mbedtls/Dockerfile, projects/mbedtls/build.sh, projects/mbedtls/run_tests.sh
Adds run_tests.sh to the mbedtls project.
`infra/experimental/chronos/check_tests.sh mbedtls c`
```
...
test_suite_ssl_decrypt.misc ....................................... PASS     
test_suite_test_helpers ........................................... PASS
test_suite_timing ................................................. PASS                                                                                   
test_suite_version ................................................ PASS                                                                                   
test_suite_x509parse .............................................. PASS …
```
=> mbedtls: add run_tests.sh

projects/yoga/run_tests.sh
Adds run_tests.sh to the yoga project.
`infra/experimental/chronos/check_tests.sh yoga c`
```
[==========] Running 823 tests from 15 test suites.                                                                                                        
[----------] Global test environment set-up.                                                                                                               
[----------] 2 tests from YogaDeathTest                                                                                                                    
[ RUN      ] YogaDeathTest.cannot_add_child_to_node_with_measure_func …
```
=> yoga: add run_tests.sh

projects/lcms/Dockerfile, projects/lcms/run_tests.sh
Adds run_tests.sh to the lcms project.
`infra/experimental/chronos/check_tests.sh lcms c`
```
8 bits on SAME Matrix-Shaper profiles        : 45.6 MPixel/sec.              
16 bits on SAME Matrix-Shaper profiles       : 45.0 MPixel/sec.                                                                                            
32 bits on SAME Matrix-Shaper profiles       : 1.49 MPixel/sec.              
8 bits on Matrix-Shaper profiles (AbsCol)    : 28.7 MPixel/sec.              
16 bits on Matrix-Shaper profiles (AbsCol)   : 19.1 MPixel/sec.              
32 bits on Matrix-Shaper profiles (AbsCol)   : 1.68 MPixel/sec.              
8 bits on …
```
=> lcms: add run_tests.sh

projects/snappy/Dockerfile, projects/snappy/run_tests.sh
Adds `run_tests.sh` to the snappy project.
Output of ./infra/experimental/chronos/check_tests.sh snappy c++:
```
Test project /src/snappy/build
Start 1: snappy_unittest
1/1 Test #1: snappy_unittest ..................   Passed   27.88 sec
100% tests passed, 0 tests failed out of 1
Total Test time (real) =  27.88 sec
```
=> snappy: add run_tests.sh

projects/fmt/Dockerfile, projects/fmt/run_tests.sh
Adds `run_tests.sh` to the fmt project.
Output of ./infra/experimental/chronos/check_tests.sh fmt c++:
```
[0/1] Running tests...
Test project /src/fmt/build
Start  1: args-test
1/21 Test  #1: args-test ........................   Passed    0.07 sec
Start  2: base-test
2/21 Test  #2: base-test ........................   Passed    0.11 sec
Start  3: assert-test
3/21 Test  #3: assert-test ......................   Passed    0.40 sec
Start  4: chrono-test
4/21 Test  #4: chrono-test ......................   Passed    0.45 sec
Start  5: color-test
5/21 Test  #5: color-test .......................   Passed    0.07 sec
Start  6: gtest-extra-test
6/21 …
```
=> fmt: add run_tests.sh

projects/tinyobjloader/Dockerfile, projects/tinyobjloader/run_tests.sh
Adds run_tests.sh to the tinyobjloader project.
`infra/experimental/chronos/check_tests.sh tinyobjloader c`
```
...
SUCCESS: All unit tests have passed.
```
=> tinyobjloader: add run_tests.sh

projects/muparser/Dockerfile, projects/muparser/run_tests.sh
Adds `run_tests.sh` to the muparser project.
Output of ./infra/experimental/chronos/check_tests.sh muparser c++:
```
Test project /src/muparser
Start 1: ParserTest
1/1 Test #1: ParserTest .......................   Passed    0.68 sec
100% tests passed, 0 tests failed out of 1
Total Test time (real) =   0.69 sec
```
=> muparser: add run_tests.sh

projects/libsodium/run_tests.sh
Adds `run_tests.sh` to the libsodium project.
Output of ./infra/experimental/chronos/check_tests.sh libsodium c++:
```
make  check-TESTS
make[3]: Entering directory '/src/libsodium/test/default'
make[4]: Entering directory '/src/libsodium/test/default'
PASS: aead_aegis128l
PASS: aead_aegis256
PASS: aead_aes256gcm
PASS: aead_aes256gcm2
PASS: aead_chacha20poly1305
PASS: aead_chacha20poly13052
PASS: aead_xchacha20poly1305
PASS: auth
PASS: auth2
PASS: auth3
PASS: auth5
PASS: auth6
PASS: auth7
PASS: box
PASS: box2
PASS: box7
PASS: box8
PASS: box_easy
PASS: box_easy2
PASS: box_seal
PASS: box_seed
PASS: chacha20
PASS: codecs
PASS: core1
PASS: core2 …
```
=> libsodium: add run_tests.sh

projects/valijson/run_tests.diff, projects/valijson/run_tests.sh
Adds run_tests.sh to the valijson project.
`infra/experimental/chronos/check_tests.sh valijson c`
```
Running main() from /src/valijson/thirdparty/googletest/googletest/src/gtest_main.cc                                                                       
[==========] Running 125 tests from 16 test suites.                                                                                                        
[----------] Global test environment set-up.                                                                                                               
[----------] 21 tests from TestAdapterComparison …
```
=> valijson: add run_tests.sh

projects/openbabel/run_tests.sh
```
$ ./infra/experimental/chronos/check_tests.sh openbabel c++
...
...
13..24
ok 13 # wrapped cartesian x
ok 14 # wrapped cartesian y
ok 15 # wrapped cartesian z
ok 16 # wrapped fractional x
ok 17 # wrapped fractional y
ok 18 # wrapped fractional z
ok 19 # cart2frac x
ok 20 # cart2frac y
ok 21 # cart2frac z
ok 22 # frac2cart x
ok 23 # frac2cart y
ok 24 # frac2cart z
```
=> openbabel: add run_tests

projects/h3/build.sh, projects/h3/run_tests.sh
```
$ infra/experimental/chronos/check_tests.sh h3 c++
277/283 Test #277: testCliUncompactCellsStdin3_test139 ..............   Passed    0.01 sec                                                                     
Start 278: testCliUncompactCellsArg1_test139                                                                                                           
278/283 Test #278: testCliUncompactCellsArg1_test139 ................   Passed    0.01 sec                                                                     
Start 279: testCliUncompactCellsArg2_test139    
279/283 Test #279: testCliUncompactCellsArg2_test139 ................ …
```
=> h3: add run_tests.sh

projects/utf8proc/run_tests.sh
```
$ infra/experimental/chronos/check_tests.sh utf8proc c++
...
...
Test project /src/utf8proc/build
Start  1: utf8proc.testcase
1/10 Test  #1: utf8proc.testcase ................   Passed    0.07 sec
Start  2: utf8proc.testcustom
2/10 Test  #2: utf8proc.testcustom ..............   Passed    0.01 sec
Start  3: utf8proc.testiterate
3/10 Test  #3: utf8proc.testiterate .............   Passed    0.01 sec
Start  4: utf8proc.testmisc
4/10 Test  #4: utf8proc.testmisc ................   Passed    0.01 sec
Start  5: utf8proc.testprintproperty
5/10 Test  #5: utf8proc.testprintproperty .......   Passed    0.00 sec
Start  6: …
```
=> utf8proc: add run_tests.sh

projects/ffmpeg/build.sh
This is so we include the fate suite in the cached image.
=> ffmpeg: stop build script a bit later when CAPTURE_REPLAY_SCRIPT is set

projects/icu/run_tests.sh
Adds run_tests.sh to the ICU project.
`infra/experimental/chronos/check_tests.sh icu c`
```
...
[All tests passed successfully...]                                                                                                                         
Elapsed Time: 00:00:50.444                                                   
make[2]: Leaving directory '/work/icu/test/cintltst'                                                                                                       
---------------                                                                                                                                            
ALL TESTS …
```
=> icu: add run_tests.sh

projects/bind9/Dockerfile, projects/bind9/build.sh, projects/bind9/patch.diff, projects/bind9/project.yaml
bind9 now relies on meson.
The names of the fuzzers have been set to match before build broke.
=> bind9: fix build

projects/skcms/Dockerfile, projects/skcms/build.sh
corpus url is no longer accessible. Blocking e.g. https://github.com/google/oss-fuzz/pull/13642
=> skcms: fix build

projects/wolfssl/Dockerfile, projects/wolfssl/build.sh
guidovranken/wolf-ssl-ssh-fuzzers has an issue with using an older OCSP function declaration. This updates the Docker image to look at JacobBarthelmeh/wolf-ssl-ssh-fuzzers which contains a fix for the following error.
```
E_FOR_PRODUCTION -fsanitize=memory -fsanitize-memory-track-origins -fsanitize=fuzzer-no-link -DWOLFSSL_STATIC_PSK -I .. -I /src/wolf-ssl-ssh-fuzzers/oss-fuzz/projects/wolf-ssl-ssh/fuzzers/include ocsp.c -c -o ocsp.o
ocsp.c:14:47: warning: passing 'const uint8_t *' (aka 'const unsigned char *') to parameter of type 'byte *' (aka 'unsigned char *') discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
14 |     InitOcspResponse(&resp, &single, &status, data, size, NULL);
|                                               ^~~~ …
```
=> wolfssl: fix build

projects/args/Dockerfile, projects/args/run_tests.sh
Adds `run_tests.sh` to the args project.
Output of ./infra/experimental/chronos/check_tests.sh args c++:
```
Test project /src/args/build
Start 1: test
1/2 Test #1: test .............................   Passed    0.27 sec
Start 2: test-multiple-inclusion
2/2 Test #2: test-multiple-inclusion ..........   Passed    0.06 sec
100% tests passed, 0 tests failed out of 2
Total Test time (real) =   0.34 sec
```
=> args: add run_tests.sh

projects/pcre2/build.sh, projects/pcre2/run_tests.sh
Adds run_tests.sh to the pcre2 project. 
The PR changes the max match limit. Otherwise the tests fail.
`infra/experimental/chronos/check_tests.sh pcre2 c`
```
...
PASS: pcre2posix_test                                                        
PASS: pcre2_jit_test                                                                                                                                       
PASS: RunTest                                                                
PASS: RunGrepTest                                                            
============================================================================ 
Testsuite summary …
```
=> pcre2: add run_tests.sh

projects/wasmtime/Dockerfile
This updates Wasmtime's pinned nightly version to a more recent version to match what the codebase now requires.
=> wasmtime: Update Rust toolchain used to build

projects/libxslt/Dockerfile, projects/libxslt/run_tests.sh
Adds run_tests.sh to the libxslt project.
Output of `infra/experimental/chronos/check_tests.sh libxslt c`
```
Total 748 tests, no errors
make[3]: Leaving directory '/src/libxslt/tests'
make[2]: Leaving directory '/src/libxslt/tests'
make[1]: Leaving directory '/src/libxslt/tests'
make[1]: Entering directory '/src/libxslt'
make[1]: Leaving directory '/src/libxslt'
```
=> libxslt: add run_tests.sh

projects/botan/run_tests.sh
```
python3 infra/experimental/chronos/manager.py check-test botan
...
INFO:__main__:Test completion succeessful: True. Duration of run_tests.sh: 615.37 seconds
```
=> botan: add run_tests.sh

projects/c-blosc2/run_tests.sh
```
python3 infra/experimental/chronos/manager.py check-test c-blosc2
...
INFO:__main__:Test completion succeessful: True. Duration of run_tests.sh: 0.47 seconds
```
=> c-blosc2: add run_tests.sh

projects/phmap/Dockerfile, projects/phmap/run_tests.sh
`infra/experimental/chronos/check_tests.sh phmap c`
```
Test project /src/parallel-hashmap/build
Start  1: test_container_memory
1/17 Test  #1: test_container_memory ...............   Passed    0.01 sec
Start  2: test_hash_policy_testing
2/17 Test  #2: test_hash_policy_testing ............   Passed    0.01 sec
Start  3: test_node_hash_policy
3/17 Test  #3: test_node_hash_policy ...............   Passed    0.01 sec
Start  4: test_raw_hash_set
4/17 Test  #4: test_raw_hash_set ...................   Passed    0.74 sec
Start  5: test_raw_hash_set_allocator
5/17 Test  #5: test_raw_hash_set_allocator .........   Passed    0.02 sec
Start  6: …
```
=> phmap: add run_tests.sh

projects/librsvg/Dockerfile
Fixes: https://oss-fuzz-build-logs.storage.googleapis.com/log-2aee0274-4aad-43b8-8ba3-f3974dccceef.txt
=> librsvg: fix build

projects/glaze/Dockerfile, projects/glaze/run_tests.sh
`infra/experimental/chronos/check_tests.sh glaze c`
```
Test project /src/glaze/build
Start  1: api_test
Start  2: beve_test
Start  3: compare_test
Start  4: csv_test
Start  5: eigen_test
Start  6: example_json
Start  7: exceptions_test
Start  8: inplace_vector_test
1/28 Test  #1: api_test ...........................   Passed    0.01 sec
Start  9: inplace_vector_test_noexceptions
2/28 Test  #3: compare_test .......................   Passed    0.01 sec
Start 10: int_parsing
3/28 Test  #8: inplace_vector_test ................   Passed    0.01 sec
Start 11: jmespath
4/28 Test  #6: example_json .......................   Passed    0.02 sec
Start …
```
=> glaze: add run_tests.sh

projects/lighttpd/run_tests.sh
```
./infra/experimental/chronos/check_tests.sh lighttpd c++
....
....
make  check-TESTS
Testing in build directory: '..' and cwd: '/src/lighttpd1.4/tests'
preparing infrastructure                PASS: prepare.sh
./core-condition.t .. ok     
./mod-fastcgi.t ..... ok     
./mod-scgi.t ........ ok     
./request.t ......... ok       
All tests successful.
Files=4, Tests=231,  1 wallclock secs ( 0.04 usr  0.01 sys +  0.39 cusr  0.23 csys =  0.67 CPU)
Result: PASS
PASS: run-tests.pl
cleaning up                             PASS: cleanup.sh
==================
All 3 tests passed
==================
make[1]: Nothing to be done for 'check-am'. …
```
=> lighttpd: add run_tests.sh

projects/libpsl/Dockerfile, projects/libpsl/run_tests.sh
```
./infra/experimental/chronos/check_tests.sh libpsl c++
...
...
make  check-TESTS
make[2]: Entering directory '/src/libpsl/fuzz'
make[3]: Entering directory '/src/libpsl/fuzz'
============================================================================
Testsuite summary for libpsl 0.21.5
============================================================================
============================================================================
make[3]: Leaving directory '/src/libpsl/fuzz'
make[2]: Leaving directory '/src/libpsl/fuzz'
make[1]: Leaving directory '/src/libpsl/fuzz'
Making check in tests
make[1]: Entering directory '/src/libpsl/tests' …
```
=> libpsl: add run_tests.sh

projects/wpantund/run_tests.sh
```
./infra/experimental/chronos/check_tests.sh wpantund c++
...
ake[5]: Leaving directory '/src/wpantund/src/missing/strlcpy'
make  check-TESTS                                             
make[5]: Entering directory '/src/wpantund/src/missing/strlcpy'
make[6]: Entering directory '/src/wpantund/src/missing/strlcpy'
PASS: strlcpy_test        
============================================================================                                                       
Testsuite summary for wpantund 0.08.00d 
============================================================================                                                       
============================================================================                                                       
make[6]: Leaving …
```
=> wpantund: add run_tests.sh

projects/ninja/run_tests.sh
`infra/experimental/chronos/check_tests.sh ninja c`
```
[----------] Global test environment tear-down
[==========] 410 tests from 31 test suites ran. (733 ms total)
[  PASSED  ] 410 tests.
```
=> ninja: add run_tests.sh

projects/tpm2-tss/Dockerfile, projects/tpm2-tss/run_tests.sh
```
./infra/experimental/chronos/check_tests.sh tpm2-tss c++
...
PASS: test/fuzz/Tss2_Sys_CreateLoaded_Complete.fuzz
PASS: test/fuzz/Tss2_Sys_PolicyAuthorizeNV_Prepare.fuzz
PASS: test/fuzz/Tss2_Sys_PolicyAuthorizeNV_Complete.fuzz
============================================================================
Testsuite summary for tpm2-tss 15abbfc
============================================================================
============================================================================
make[2]: Leaving directory '/src/tpm2-tss'
make[1]: Leaving directory '/src/tpm2-tss'
--------------------------------------------------------
Total time …
```
=> tpm2-tss: add run_tests.sh

projects/libcoap/Dockerfile, projects/libcoap/run_tests.sh
```
./infra/experimental/chronos/check_tests.sh libcoap c++
...
...
Test: t_session5 ...passed
Test: t_session6 ...passed
Suite: sendqueue
Test: t_sendqueue1 ...passed
Test: t_sendqueue2 ...passed
Test: t_sendqueue3 ...passed
Test: t_sendqueue4 ...passed
Test: t_sendqueue5 ...passed
Test: t_sendqueue6 ...passed
Test: t_sendqueue7 ...passed
Test: t_sendqueue8 ...passed
Test: t_sendqueue9 ...passed
Test: t_sendqueue10 ...passed
Suite: .well-known/core
Test: t_wellknown1 ...passed
Test: t_wellknown2 ...passed
Test: t_wellknown3 ...passed
Test: t_wellknown4 ...passed
Suite: TLS
Test: t_tls1 ...passed
Test: t_tls2 ...passed
Run Summary:    Type …
```
=> libcoap: add run_tests.sh

projects/gss-ntlmssp/run_tests.sh
```
./infra/experimental/chronos/check_tests.sh gss-ntlmssp c++
...
...
make[2]: Leaving directory '/src/gss-ntlmssp'                                                                                                                                                               
make  check-TESTS                                                                                                                                                                                           
make[2]: Entering directory '/src/gss-ntlmssp' …
```
=> gss-ntlmssp: add run_tests.sh

projects/tidy-html5/Dockerfile, projects/tidy-html5/build.sh, projects/tidy-html5/run_tests.sh
```
./infra/experimental/chronos/check_tests.sh tidy-html5 c++
...
...
PASSED | status 0 expected 0 | /src/tidy-html5/regression_testing/cases/xml-cases/case-540045@0.xhtml 
PASSED | status 1 expected 1 | /src/tidy-html5/regression_testing/cases/xml-cases/case-542029@1.html
PASSED | status 1 expected 1 | /src/tidy-html5/regression_testing/cases/xml-cases/case-586555@1.html
PASSED | status 0 expected 0 | /src/tidy-html5/regression_testing/cases/xml-cases/case-616744@0.xml
PASSED | status 1 expected 1 | /src/tidy-html5/regression_testing/cases/xml-cases/case-634889@1.html
PASSED | status 0 expected 0 | /src/tidy-html5/regression_testing/cases/xml-cases/case-640474@0.xml
PASSED | status 0 expected 0 | /src/tidy-html5/regression_testing/cases/xml-cases/case-646946@0.xml
Ran 401 tests, of …
```
=> tidy-html5: fix so run_tests.sh work without network

projects/bluez/build.sh, projects/bluez/run_tests.sh
Improves build performance and restores removed files when running `run_tests.sh`
```
$ ./infra/experimental/chronos/check_tests.sh bluez c
...
...
AICS/SR/CP/BV-01-C                                   Passed       0.011 seconds
AICS/SR/SPE/BI-01-C                                  Passed       0.001 seconds
Total: 20, Passed: 20 (100.0%), Failed: 0, Not Run: 0
Overall execution time: 0.0363 seconds
+ mv /tmp/test-mesh-crypto.c unit/test-mesh-crypto.c
+ mv /tmp/test-midi.c unit/test-midi.c
--------------------------------------------------------
Total time taken to replay tests: 71
```
=> bluez: fix run_tests.sh modifications and parallelise build

projects/frr/Dockerfile, projects/frr/build.sh, projects/frr/run_tests.sh
`infra/experimental/chronos/check_tests.sh frr c`
```
------------------------------------------------------ generated xml file: /src/frr/tests/tests.xml -------------------------------------------------------
============================================================= 208 passed, 5 skipped in 20.13s =============================================================
```
=> frr: add run_tests.sh

projects/pcapplusplus/Dockerfile
```
Step #1 - "build-bb7d6cb6-a60e-4204-802d-41c0dbaa661c": Step 7/7 : COPY *.sh pcapplusplus_enable_tests.diff $SRC
Step #1 - "build-bb7d6cb6-a60e-4204-802d-41c0dbaa661c": When using COPY with more than one source file, the destination must be a directory and end with a /
```
=> fix pcapplusplus build

projects/frr/run_tests.sh
In case the tests fail, ensure that we still move back the ignored test files.
=> frr: ensure cleanup in case tests fail

infra/base-images/base-builder/indexer/fuzzing_engine.cc
ASan can't catch overflows within the mmap'ed page boundaries, nor does it support catching overflows after the mmap'ed regions: https://github.com/google/sanitizers/issues/348.
=> indexer fuzzing_engine: Use malloc instead of mmap for the input buffer.

projects/cloud-hypervisor/Dockerfile
This should address the recent building errors [1].
[1] https://issues.oss-fuzz.com/issues/422421343
=> cloud-hypervisor: Use the latest nightly toolchain

projects/openssh/build.sh
OpenSSH a8c0e5c87 refactored some things in the PKCS#11 code which necessitates a new build-time dependency
=> Fix openssh fuzzers after recent PKCS#11 changes

projects/kubernetes/Dockerfile
Kubernetes uses 1.24. [Ref](https://github.com/kubernetes/kubernetes/blob/f9ed14bf9b1119a2e091f4b487a3b54930661034/go.mod#L9)
=> kubernetes: bump go version

projects/wavpack/run_tests.sh
```
$ ./infra/experimental/chronos/check_tests.sh wavpack c++
...
...
*** 32-bit integer, 5.1 channels ***
test 0153...pass (   -fb4c, 87.25%, 4.08 bps, 2b7608040e81390e6926c39c94d3086d)
test 0154...pass (    -b4c, 87.16%, 4.11 bps, 74033ecd1a0cd518f851649e530a3164)
test 0155...pass (   -hb4c, 87.11%, 4.12 bps, 9ad5ef53970867690665ca3301ea3199)
test 0156...pass (  -hhb4c, 87.04%, 4.15 bps, 62ba102f67a46d57bb394c8b6f43640d)
*** 32-bit float stored as integer (pathological), 5.1 channels ***
test 0157...pass (   -fb4c, 83.68%, 5.22 bps, d4b5d5c7245183123af355ed90f58c5f)
test 0158...pass (    -b4c, 83.41%, 5.31 bps, …
```
=> wavpack: add run_tests.sh

projects/php/build.sh
opcache is now mandatory and no longer optional:
https://github.com/php/php-src/commit/7b4c14dc10167b65ce51371507d7b37b74252077
=> php: fix build

projects/exiv2/build.sh
This adds a second fuzz target for [Exiv2](https://github.com/Exiv2/exiv2). It will help to find bugs in the `writeMetadata` function. See also: https://github.com/Exiv2/exiv2/pull/3313
=> Add new fuzz target to Exiv2

projects/ffmpeg/build.sh
- ffmpeg: parallelize build
Instead of building everything individually, gather all targets and make
them. This significantly speeds-up the build process.
- ffmpeg: remove all redundant make clean/build calls
=> ffmpeg: parallelize build

projects/dbus-broker/project.yaml
Currently it fails to build so it can be disabled until https://github.com/bus1/dbus-broker/issues/408 is addressed one way or another.
=> [dbus-broker] disable it for now

projects/libmicrohttpd2/fuzz_daemon.cpp, projects/libmicrohttpd2/mhd_helper.cpp, projects/libmicrohttpd2/mhd_helper.h
This PR adds the final batch of targets for request handling in daemon for project libmicrohttpd2.
=> libmicrohttpd2: Add third set of targets for daemon fuzzing

projects/bitcoin-core/build.sh
https://github.com/bitcoin/bitcoin/pull/31802 builds libmultiprocess and enables IPC by default, but my understanding is that this breaks oss-fuzz. One proposed solution is https://github.com/google/oss-fuzz/pull/13018.
This PR builds depends with `NO_IPC=1`, which disables the feature, for now while we work on an actual fix.
=> bitcoin-core: temporarily disable IPC build

projects/libmicrohttpd2/build.sh, projects/libmicrohttpd2/fuzz_connection.cpp
This PR adds a new fuzzers, crafting a manual MHD_Connection with random data and fuzz target functions that takes in the MHD_Connection object to process.
=> libmicrohttpd2: Add new fuzzers targeting MHD_Connection related functions

infra/helper.py
The introspector command supports generating coverge + introspector reports in one go. Sometimes it's nice only to generate coverage reports. This commit adds a flag for doing that.
=> helper: add ability to easily generate coverage

projects/kmime/Dockerfile, projects/kmime/project.yaml
KMime is a library for handling MIME messages, used by KDE applications such as KMail.
Corresponding MR: https://invent.kde.org/pim/kmime/-/merge_requests/126
CC @tsdgeos
=> Add new project KMime

projects/vulkan-loader/fuzzers/instance_enumerate_fuzzer.c
Uses the 2-call pattern to first get the count, then allocate a buffer in order to query the data.
=> vulkan-loader: Fix uninitialized memory

infra/base-images/all.sh, infra/base-images/base-builder/precompile_honggfuzz, infra/base-images/base-clang/Dockerfile, infra/base-images/base-clang/checkout_build_install_llvm.sh
Reverts google/oss-fuzz#13848
Unfortunately, this breaks the indexer for many projects that are still building on clang 18 with errors like:
```
Step #23: fatal error: too many errors emitted, stopping now [-ferror-limit=]
Step #23:       |                                         ^~~~~~~~~~~~
Step #23:   422 |     return (__m64)__builtin_ia32_paddsb((__v8qi)__m1, (__v8qi)__m2);
Step #23: /usr/local/lib/clang/18/include/mmintrin.h:422:41: error: cannot initialize a parameter of type 'unsigned int' with an rvalue of type '__v8qi' (vector of 8 'char' values)
Step #23:       |                   ^~~~~~~~~~~~~~~~~~~~~
Step #23:   422 |     return (__m64)__builtin_ia32_paddsb((__v8qi)__m1, (__v8qi)__m2);
Step #23: /usr/local/lib/clang/18/include/mmintrin.h:422:19: error: use of undeclared …
```
=> Revert "infra: bump indexer to llvm-21"

projects/libmicrohttpd2/fuzz_str.cpp
This PR fixes the fuzz_str harness to add missed function target from libmicrohttpd2 project related to string and int processing.
=> libmicrohttpd2: Fix fuzz_str

projects/libmicrohttpd2/build.sh, projects/libmicrohttpd2/connection_helper.cpp, projects/libmicrohttpd2/connection_helper.h, projects/libmicrohttpd2/fuzz_connection.cpp
This PR extract helper functions for MHD_Connection object preparation to a separate helper class and fixes certain blockers for stream processing functions.
=> libmicrohttpd2: Revamp fuzz_connection

projects/kde-thumbnailers/Dockerfile, projects/kde-thumbnailers/build.sh, projects/kde-thumbnailers/project.yaml
KDE thumbnailers generate previews for various file formats across KDE Plasma and Apps (like Dolphin).
Corresponding MR: https://invent.kde.org/network/kio-extras/-/merge_requests/441
=> Add new project KDE-Thumbnailers

projects/kde-thumbnailers/build.sh
The build fails at the `check_build` step due to running out of storage. 
This change cleans up $WORK after the build to free up space.  
https://oss-fuzz-build-logs.storage.googleapis.com/log-150d58fe-14f9-41cc-ac9c-1ae491fe4556.txt
=> KDE-Thumbnailers: Cleanup $WORK data after build

projects/kubeflow-spark-operator/Dockerfile, projects/kubeflow-spark-operator/build.sh, projects/kubeflow-spark-operator/parseSecret_fuzzer.go, projects/kubeflow-spark-operator/project.yaml
Adds initial integration of Kubeflow Spark Operator which is [adopted](https://github.com/kubeflow/spark-operator/blob/master/ADOPTERS.md) by companies such as Alibaba, Carrefour, CERN, Lyft and Salesforce.
=> kubeflow spark-operator: initial integration

projects/kubeflow-pipelines/Dockerfile, projects/kubeflow-pipelines/build.sh, projects/kubeflow-pipelines/expr_fuzzer.go, projects/kubeflow-pipelines/project.yaml
Adds initial integration of Kubeflow Pipelines which is [adopted](https://github.com/kubeflow/pipelines/blob/master/ADOPTERS.md) by companies such as Capital One, IBM, Reh Hat and Sophotec.
=> kubeflow pipelines: initial integration

projects/kubeflow-katib/Dockerfile, projects/kubeflow-katib/build.sh, projects/kubeflow-katib/generateNNImage_fuzzer.go, projects/kubeflow-katib/project.yaml
Adds initial integration of Kubeflow Katib which is [adopted](https://github.com/kubeflow/katib/blob/master/ADOPTERS.md) by companies such as Canonical, CERN and Cisco.
=> kubeflow katib: initial integration

projects/lxc/build.sh
ref:
https://github.com/google/oss-fuzz/pull/13915#issuecomment-3250384177
=> lxc: prepare for llvm 21

infra/build/functions/build_project.py
This will create a separate build to allow tracing function calls when running the harness on testcases.
=> Extend indexer build steps to also build and upload tracer image

infra/base-images/base-runner/bad_build_check, infra/base-images/base-runner/run_fuzzer
Some harnesses won't recognise the flags if `--` is not supplied, causing the bad build check to run the fuzzers forever or until they crash. This happens for Envoy.
Tested this works on other projects as well, but will do a bit more testing before it's ready.
=> infra: fix flag recognition in bad build checks

projects/zlib/build.sh
to make it easier to debug issues like
https://github.com/madler/zlib/issues/1084 and
https://github.com/google/oss-fuzz/issues/13969.
With this patch applied it shows
```
...
Checking for obsessive-compulsive compiler options...
=== ztest14.c ===
int foo() { return 0; }
===
/src/aflplusplus/afl-clang-fast -c -O1 -fno-omit-frame-pointer -gline-tables-only -Wno-error=incompatible-function-pointer-types -Wno-error=int-conversion -Wno-error=deprecated-declarations -Wno-error=implicit-function-declaration -Wno-error=implicit-int -Wno-error=unknown-warning-option -Wno-error=vla-cxx-extension -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope ztest14.c
error: unable to load plugin '/src/aflplusplus/SanitizerCoveragePCGUARD.so': 'Could not load …
```
=> [zlib] show configure.log when configure fails

projects/distribution/Dockerfile
This is required for https://github.com/google/oss-fuzz/pull/13875. Making this PR to pre-emptively fix the broken distribution build.
=> distribution: use go 1.23.4

projects/blackfriday/Dockerfile
This is required for https://github.com/google/oss-fuzz/pull/13875. Making this PR to pre-emptively fix the broken blackfriday build.
=> blackfriday: use go 1.23.4

projects/prometheus/Dockerfile, projects/prometheus/build.sh
This is required for https://github.com/google/oss-fuzz/pull/13875. Making this PR to pre-emptively fix the broken prometheus build.
=> prometheus: use go 1.24.6

projects/mxj/Dockerfile, projects/mxj/build.sh
This is required for https://github.com/google/oss-fuzz/pull/13875. Making this PR to pre-emptively fix the broken mxj build.
=> mxj: use go 1.24.6

projects/juju/Dockerfile
This is required for https://github.com/google/oss-fuzz/pull/13875. Making this PR to pre-emptively fix the broken juju build.
=> juju: use go 1.23.4

projects/opentelemetry-go/Dockerfile, projects/opentelemetry-go/build.sh
=> opentelemtry-go: use compile_native_go_fuzzer_v2

projects/go-attestation/Dockerfile
This is required for https://github.com/google/oss-fuzz/pull/13875. Making this PR to pre-emptively fix the broken go-attestation build.
=> go-attestation: use go 1.24.6

projects/moby/Dockerfile, projects/moby/build.sh, projects/moby/daemon_fuzzer.go
1. Fix broken build.
2. Remove dependency on `github.com/AdamKorcz/go-118-fuzz-build/testing`
The `FuzzDisplayJSONMessagesStream` is giving me some trouble. I have commented it out for now and will follow up with a fix.
=> moby: fix broken build

projects/nss/Dockerfile, projects/nss/build.sh
The latest NSS build broke due to missing boost library headers: https://oss-fuzz-build-logs.storage.googleapis.com/log-b9fec823-082c-46fa-88a8-d49fccc0e459.txt
=> nss: fix broken build

projects/igraph/Dockerfile
We are preparing for a big release, renamed some branches and moving development primarily to the `main` branch.
=> igraph: use 'main' branch

infra/base-images/base-builder/compile_go_fuzzer, infra/base-images/base-runner/coverage
This PR does so that the go coverage build only runs the coverage test in the compiled binary. It does so by adding the `-test.run` flag when running go-fuzz fuzzers and by also storing the function name of go-fuzz fuzzers in `$OUT/fuzzer_function_names.json`.  Also, it limits the function name in `-test.run` to be specific to the actual name, since this is a regex and can include other functions depending on how they are named.
This PR also sets the go-fuzz fuzzers' covermode to `atomic` so that all coverage binaries are atomic. This avoids this failure: https://github.com/wadey/gocovmerge/blob/b5bfa59ec0adc420475f97f89b58045c721d761c/gocovmerge.go#L18.
This PR also removes `-run Test${function}Corpus` from `compile_go_fuzzer` since it doesn't do anything. Adding the flag when compiling …
=> go coverage: align covermode and run only coverage test

projects/wasmtime/build.sh
This change coordinates a name change to `regalloc2`'s fuzz targets introduced in [#244]. The `ion_checker` target is now simply named `ion`.
[#244]: https://github.com/bytecodealliance/regalloc2/pull/244
=> wasmtime: change the name of the `regalloc2` fuzzer

infra/base-images/base-builder/compile, infra/build/functions/build_project.py, infra/presubmit.py, projects/v8/project.yaml
=> Enable incremental indexing.

projects/dbus-broker/Dockerfile, projects/dbus-broker/build.sh, projects/dbus-broker/project.yaml
Now that LLVM and RUSTUP_TOOLCHAIN are bumped it should work.
Closes https://issues.oss-fuzz.com/issues/432299042
=> [dbus-broker] bring rustc and bindgen
