pcre2/Dockerfile, pcre2/Jenkinsfile, pcre2/build.sh, pcre2/pcre2_fuzzer.cc
My first attempt with oss-fuzz.
Note that I had a problem with LDFLAGS and had to do a little hack to make things work.
=> pcre2 fuzzer

targets/README.md, targets/openssl/Dockerfile, targets/openssl/Jenkinsfile, targets/openssl/build.sh
I was unable to test this because of various issues.
=> Add OpenSSL

targets/README.md, targets/libarchive/Dockerfile, targets/libarchive/Jenkinsfile, targets/libarchive/build.sh, targets/libarchive/libarchive_fuzzer.cc
=> Add fuzzer for libarchive

docs/new_target.md
Missing targets folder directory
=> Correcting doc link for expat Dockerfile

projects/node.js/project.yaml
I'd love to see the Node.js project included in OSS Fuzz :)
=> Submitting Node.js to OSS Fuzz

projects/pidgin/project.yaml
The email address in project.yaml is my google account, but my email address in the hg log is grim@reaperworld.com.
=> Add pidgin as a project

projects/tor/project.yaml
Should I include Dockerfile and build.sh in the same pull request or is this fine?
=> Nominating Tor

projects/libreoffice/project.yaml
We've been fuzzing somewhat adhoc for a while, but lack good infrastructure to manage it properly.
=> Add libreoffice as a project

projects/postgresql/project.yaml
This is a pull request to add the PostgreSQL project to OSS-Fuzz
submitted by a long-time PostgreSQL Major Contributor and PostgreSQL
Committer who is also a member of the PostgreSQL Security team:
Stephen Frost
sfrost@snowman.net
sfrost@postgresql.org
Google account: frost.stephen.p@gmail.com
Github: sfrost
=> Add the PostgreSQL Project

projects/json/project.yaml
I am the maintainer of [JSON for Modern C++](https://github.com/nlohmann/json). I just wanted to open a pull request to add my project, and now I am thrilled that it is already here :-)
=> added contact email

projects/botan/project.yml
This is a pull request to add Botan TLS library to OSS-Fuzz submitted by primary maintainer. Two colloborating developers CCed.
Jack Lloyd
jack@randombit.net
Google Account: jack.lloyd@gmail.com
GitHub: randombit
=> Add Botan TLS library

infra/base-images/base-libfuzzer/Dockerfile, infra/base-images/base-libfuzzer/README.md, infra/base-images/base-libfuzzer/compile, infra/libfuzzer-pipeline.groovy
The variable picks one of the predefined flags configuration.
=> [infra] SANITIZER environment variable

projects/dropbear/project.yaml
I'd like to add Dropbear SSH to oss-fuzz.
=> Add Dropbear SSH

projects/openssl/build.sh
=> Use libFuzzingEngine instead of libfuzzer

projects/gnutls/Dockerfile, projects/gnutls/build.sh
and add OpenSSL's corpus for client transcripts
=> [gnutls] use an initial corpus for x509

projects/harfbuzz/Dockerfile, projects/harfbuzz/build.sh
This reverts commit e72ae23208d5487b40b2cc6370823bd8137be05c.
=> Revert "Use Google Fonts in Harfbuzz's seed corpus."

projects/openssl/build.sh
@kroeckx this version seem to work
=> [openssl] use clang++ for linking #195

projects/gnutls/project.yaml
That is, in order to be able to access the issues opened.
=> [gnutls] updated primary contact email

projects/wireshark/project.yaml
Add Dario Lombardo to the CC list as wireshark core developer.
=> Add new email to wireshark.

projects/wireshark/project.yaml
Add Roland Knall to the CC list as wireshark core developer
=> Add new email to wireshark project config

infra/helper.py
The options is useful when changing base-images.
@inferno-chromium you have had this problem too
=> [infra] --nopull option for helper.py

projects/libass/project.yaml
Corresponding to GitHub users @wm4, @astiob and @MrSmile (all in the GitHub organization @libass), with their consent.
=> [libass] adding more developer emails

infra/helper.py
Can be used to switch sanitizer or fuzzing engine.
=> [infra] -e build_fuzzers flag to set environment variable

projects/libreoffice/Dockerfile, projects/libreoffice/build.sh
and change CC address for reporting finds
=> [libreoffice] prepare for adding more fuzzers

projects/gnutls/project.yaml
Now that we've fixed most of the ASAN discovered bugs, let's have some fun with UBSAN
=> [gnutls] use ubsan as well

projects/libreoffice/Dockerfile, projects/libreoffice/project.yaml
and sync dependency cache, etc
=> [libreoffice] add initial xbm corpus

projects/boringssl/project.yaml
=> Add BoringSSL contact info.

projects/arduinojson/Dockerfile, projects/arduinojson/build.sh, projects/arduinojson/project.yaml
https://github.com/bblanchon/ArduinoJson
=> Add project ArduinoJson

projects/libxml2/project.yaml
I maintain libxml in Chromium and would like to see what oss-fuzz finds in libxml.
=> Add me to auto_ccs for libxml2 fuzzing.

infra/base-images/base-clang/Dockerfile, infra/base-images/base-clang/checkout_build_install_llvm.sh
I will hold off submitting this until I am sure #84 works.
=> [infra] using lld. Fixes #295.

projects/libreoffice/Dockerfile, projects/libreoffice/build.sh
=> add psd corpus

projects/libreoffice/project.yaml
As stated in issue 326, I am trying to get access to LibreOffice's security reports and sample files, so I can fix any common issues in Apache OpenOffice. Here is a pull request with my email address.
=> Add myself to the libreoffice project.yaml.

projects/nghttp2/project.yaml
Please add nghttp2 HTTP/2 C library to oss-fuzz.
=> Add nghttp2

infra/libfuzzer-pipeline.groovy
I'm not sure how well this works in our case when the build is stuck.
https://jenkins.io/doc/pipeline/steps/workflow-basic-steps/#code-timeout-code-enforce-time-limit
Issue #366
=> [infra] specifying timeout for a job

projects/grpc/Dockerfile, projects/grpc/build.sh, projects/grpc/project.yaml
=> Add gRPC to oss-fuzz projects

projects/grpc/build.sh
=> Fix typo in gRPC build.sh

projects/opus/Dockerfile, projects/opus/build.sh, projects/opus/project.yaml
This adds the files needed to start fuzzing the Opus decoder.
=> [opus] Add Dockerfile and build.sh for decoder

infra/base-images/base-builder/compile_libfuzzer, projects/ffmpeg/build.sh, projects/ffmpeg/project.yaml
=> Enable UBSan without vptr for ffmpeg, disable vptr for libFuzzer.

projects/libreoffice/Dockerfile
=> add hwp and 602 corpus

projects/libreoffice/Dockerfile
update libreoffice dependency cache
=> add lwp and ppt corpus

projects/woff2/build.sh
=> Disable noisy logging in woff2

projects/harfbuzz/project.yaml
=> enable msan for harfbuzz

projects/libreoffice/build.sh
to make it easier to keep it in sync with what it builds
=> move build script into libreoffice git

infra/gcb/.gitignore, infra/gcb/build.py, infra/gcb/requirements.txt
Doesn't perform the upload, but is supposed to build all
sanitizer configuration.
I was primarily testing it on json.
=> [infra] v0 gcb building script

projects/libreoffice/Dockerfile
=> add rtf corpus

projects/expat/project.yaml
As requested by @kcc...
The other three addresses here are @hannob, @RMJ10 and an alternative of mine, last.
@kwaclaw, it don't want you to be spammed unasked. Please speak up if you do want to be in auto-cc for bugs/results related to fuzzing of Expat by Google as well. I would make another pull request on top I guess, no big deal.
Best, Sebastian
=> Update metadata of Expat project

projects/grpc/build.sh
=> Add c-ares to libraries to compile gRPC fuzzers with

projects/guetzli/project.yaml
All spotted implementation-specific/undefined behaviour has been fixed:
google/guetzli#142, google/guetzli#144, google/guetzli#154.
=> Guetzli: enable UBSAN, add Zoltan to auto_ccs.

projects/libreoffice/Dockerfile
=> add cgm corpus

infra/helper.py
I often use `shell` for local testing and debugging. Sometimes I want to work through things with a sanitizer besides ASAN.
=> Added environment and sanitizer flag support to shell command

projects/libyaml/project.yaml
As the lead maintainer of libyaml, it would be helpful to get CC'd on
any findings of OSS Fuzz.
=> Add myself to the list of auto CCs for libyaml

projects/wireshark/build.sh
As requested in https://github.com/google/oss-fuzz/pull/532#issuecomment-294542663
=> Wireshark: disable building with fortify

projects/libssh/Dockerfile, projects/libssh/build.sh, projects/libssh/libssh_server_fuzzer.cc
Do not merge yet! Putting this here so the libssh team can take a look. There's still a few outstanding things:
=> [WIP] Added libssh fuzzer

projects/grpc/build.sh
=> Fix gRPC build

projects/libreoffice/Dockerfile
=> add ww6 and ww8 corpuses

projects/jsoncpp/project.yaml
Internal (YouTube) bug tracking adding this: b/37561473
See also: https://github.com/open-source-parsers/jsoncpp/pull/610
=> Add JsonCpp as a project, with @cdunn2001 as the contact.

infra/base-images/base-builder/Dockerfile
Please don't land until #569 gets fixed.
=> [infra] Extend set of UBSan checks enabled.

projects/xbps/project.yml
XBPS is the Void package manager.
Void is a general purpose operating system, based on the monolithic Linux® kernel.
Its package system allows to quickly install, update and remove software in binary form.
=> New project: xbps

projects/skia/build.sh
=> [skia] fix build

projects/openssl/build.sh, projects/openssl/project.yaml
This isn't tested, but I think it should do the right thing.
=> openssl: add msan support

projects/libxslt/project.yaml
If libxslt is accepted, I plan to integrate a couple of fuzz targets and corpora that I wrote last year to find and fix
- CVE-2016-4607
- CVE-2016-4609
- CVE-2016-4610
- CVE-2016-4614
- CVE-2016-4615
- CVE-2016-4658
- CVE-2016-4738
- CVE-2016-5131
and numerous other issues.
=> Add project.yaml for libxslt

projects/libprotobuf-mutator/build.sh
=> Fix build coverage of libprotobuf-mutator

infra/base-images/base-clang/checkout_build_install_llvm.sh
=> Use chromium clang revision for base-clang image.

projects/libxml2/project.yaml
Add myself to libxml2 auto_ccs.
=> Update libxml2 auto_ccs

projects/libreoffice/Dockerfile
=> add quattro pro corpus

projects/wget2/build.sh
Upstream now has a dedicated make target for creating oss-fuzz targets.
=> [wget2] Reflect better upstream integration

projects/freetype2/project.yaml
Adding my gmail address to the list of people receiving freetype2's fuzzing results.
=> Adding myself to access freetype2's fuzzing results

projects/libidn/Dockerfile, projects/libidn/build.sh
Removed some packages for installation, moved building to build.sh
=> [libidn] Cleanup build

projects/fidl/project.yaml
=> request for adding fidl to OSS-Fuzz

projects/postgis/project.yaml
Per his request https://lists.osgeo.org/pipermail/postgis-devel/2017-July/026228.html
=> Add Mateusz Loskot to cc list

projects/libpsl/build.sh
Libicu has problems with UBSAN that I can't easily solve (project/icu/project.yaml also excludes UBSAN).
This PR fixes the build by skipping libicu/UBSAN combination.
It also fixes iconv() detection in ./configure runs by disabling asan/ubsan leak check.
=> [libpsl] Fix libicu+undefined build

projects/tensorflow/project.yaml
TensorFlow (https://www.tensorflow.org) is an open source software library for numerical computation using data flow graphs, primarily used for machine learning systems.
=> Add TensorFlow to OSS Fuzz

projects/open62541/Dockerfile, projects/open62541/build.sh, projects/open62541/project.yaml
Would be nice if we can add our project to oss-fuzz.
Let me know if you need more infos.
More fuzzing targets will follow.
=> Add open62541 project

projects/open62541/Dockerfile, projects/open62541/build.sh, projects/open62541/project.yaml
- Fix year in copyright
- Increase Loglevel to Trace, to avoid ERROR logging outputs which are not errors when fuzzing
- Use gmail account
=> Minor fixes. Addresses comments from PR #721

projects/openthread/Dockerfile, projects/openthread/build.sh, projects/openthread/project.yaml
Related PR: https://github.com/openthread/openthread/pull/2014
=> Adds the OpenThread project.

projects/libprotobuf-mutator/build.sh
New cmake option required due to change in default configuration.
=> Auto-download protobuf.

projects/gnutls/project.yaml
Signed-off-by: Nikos Mavrogiannopoulos <nmav@gnutls.org>
=> [gnutls] added Tim Ruehsen to CCS list

projects/librawspeed/project.yaml
Yes, i did check locally. It does build and function.
Refs. https://github.com/google/oss-fuzz/issues/776
=> RawSpeed: enable Memory sanitizer

projects/gnutls/build.sh
This fixes the build for latest GnuTLS.
=> [gnutls] Fix build

infra/gcb/build.py
Need to take a closer look at the following issues:
- https://github.com/google/oss-fuzz/issues/815
- https://github.com/google/oss-fuzz/issues/816
- https://github.com/google/oss-fuzz/issues/817
- https://github.com/google/oss-fuzz/issues/818
- https://github.com/google/oss-fuzz/issues/819
- https://github.com/google/oss-fuzz/issues/820
- https://github.com/google/oss-fuzz/issues/821
- https://github.com/google/oss-fuzz/issues/822
- https://github.com/google/oss-fuzz/issues/823
- https://github.com/google/oss-fuzz/issues/824
- https://github.com/google/oss-fuzz/issues/825
- https://github.com/google/oss-fuzz/issues/826
- https://github.com/google/oss-fuzz/issues/827
- https://github.com/google/oss-fuzz/issues/828
- https://github.com/google/oss-fuzz/issues/829
- …
=> [infra] Temporary revert bad_build_check until most of the targets get fixed.

projects/openssh/Dockerfile, projects/openssh/build.sh, projects/openssh/project.yaml
This includes fuzzers for public key parsing and signature verification
so far, as well as seed corpora.
=> Add openssh project

projects/libreoffice/Dockerfile
=> add fods, fodg, fodp corpuses

projects/wpantund/project.yaml
Adds @abtink to the `auto_ccs` list.
=> [wpantund] Update auto_cc in project.yaml

projects/brotli/build.sh
=> Update build script

projects/llvm/build.sh
Note: Do not submit until https://reviews.llvm.org/D38855 has been patched into LLVM successfully.
=> Add llvm-demangle-fuzzer to oss-fuzz.

projects/dlplibs/Dockerfile, projects/dlplibs/build.sh
This "fixes" ofz#3631, ofz#3632 and ofz#3644.
=> update bundled ICU

projects/libreoffice/Dockerfile, projects/libreoffice/project.yaml
=> enable ubsan for LibreOffice

projects/irssi/project.yaml
I would like to be added as an auto_cc for irssi. I'm a member of the irssi org on GitHub now and the addition of myself to auto_ccs has been discussed among the dev team, but if approval is needed from one of the existing contacts, @dequis or @ahf can stop by and comment here.
=> [irssi] Add myself to auto_ccs

projects/libreoffice/Dockerfile
and update build dependency cache
=> add xls corpus

projects/llvm/Dockerfile, projects/llvm/build.sh
This requires also checking out clang-tools-extra.
=> Add clangd-fuzzer to llvm's fuzz targets

projects/openssl/build.sh
This at least seems to give good results for the asn1 and x509 fuzzers.
=> Use OIDs as the dictionary for the ASN1 and X509 fuzzers

projects/gstreamer/Dockerfile, projects/gstreamer/build.sh
Should help detect leaks better and adds a new simple(r) target
=> gstreamer: several updates

projects/openssl/build.sh
=> Exclude perl scripts

projects/libreoffice/Dockerfile
=> add calc rtf corpus

projects/chakra/project.yaml
add chakracore@microsoft.com in place of ochang@google.com
=> Add central ChakraCore contact

projects/libreoffice/Dockerfile
=> add dif corpus

projects/grpc/build.sh
Fixes #969
We recently made a transition from C to C++ in our core directories.
=> Convert .c files to .cc

projects/libreoffice/Dockerfile, projects/libreoffice/project.yaml
=> Enable AFL engine for libreoffice

projects/wget2/Dockerfile
Add two tools needed for building the latest wget2.
=> [wget2] Install lzip and rsync

infra/base-images/base-builder/Dockerfile
Tested with tor project, seems working fine. I'll probably test more with something else and then land it next week when be able to keep a closer eye on all of the builds.
=> [infra] Use "-fsanitize=fuzzer-no-link" instead of coverage flags.

projects/unrar/Dockerfile
Here's the email to get permission from them to put the source code on Github:
http://shortn/_73UyNddJwi
=> Use github repo to fetch code and remove extra dependencies

projects/gnutls/project.yaml
Signed-off-by: Nikos Mavrogiannopoulos <nmav@redhat.com>
=> added Niels from nettle, to be able to inspect logs

projects/unrar/unrar_fuzzer.cc
See https://github.com/google/oss-fuzz/pull/951#discussion_r151293708 for a detailed discussion.
=> Use temp-PID.rar as the name of the input file created on disk

projects/libreoffice/Dockerfile
=> add docx corpus

projects/librawspeed/build.sh
As discussed in https://github.com/google/oss-fuzz/issues/682#issuecomment-347236010
=> RawSpeed: Undefined Sanitizer: unsigned-integer-overflow

projects/libreoffice/Dockerfile
=> add xlsx corpus

projects/libreoffice/Dockerfile
=> add pptx corpus

projects/grpc/build.sh
=> [gRPC] Update Bazel submodules

projects/llvm/build.sh
This change adds separate build step for the llvm-opt-fuzzer which generates corpus input from the
llvm lit tests.
=> [llvm][opt-instcombine] Generate corpus out of the llvm-lit tests for the instcombine

projects/knot-dns/project.yaml
Hello,
I'd like to submit an integration for [knot-dns](https://www.knot-dns.cz/). It is used by .cz, fastly.com (CDN), and I believe many other orgs. 
I've gotten a +1 from the maintainers to develop this (chat logs [here](https://gitter.im/CZ-NIC/knot) if it makes it easier). /cc @salzmdan. 
Thanks,
Jon
=> Submit knot-dns

infra/base-images/base-builder/Dockerfile, infra/gcb/build.py, infra/helper.py
FYI, I'd like to land this now and see how many builds get broken. Right now I see the following breakages at https://oss-fuzz-build-logs.storage.googleapis.com/index.html:
```
freetype2
Last built 12/27/2017, 10:39:52 PM
fuchsia_fidl
Last built 12/27/2017, 9:17:56 PM
gstreamer
Last built 12/27/2017, 11:14:22 PM
openssh
Last built 12/27/2017, 9:25:05 PM
```
If we get any new breakages, I'll either fix them or revert the change again.
=> [infra] Reland profile configuration needed for new code coverage.

projects/imagemagick/Dockerfile, projects/imagemagick/build.sh, projects/imagemagick/crop_fuzzer.cc, projects/imagemagick/encoder_fuzzer.cc, projects/imagemagick/encoder_list.cc, projects/imagemagick/enhance_fuzzer.cc, projects/imagemagick/huffman_decode_fuzzer.cc, projects/imagemagick/project.yaml, projects/imagemagick/rotate_fuzzer.cc
Some initial fuzzers. We've ended up building it as a lot of fuzzers (nearly 200) so that there's a fuzzer per encoder. If this is a bad approach let me know and we can change it 😄 
Primary contact, etc should still be sorted out since I am not directly associated with the imagemagick project.
Refs #430 
cc @dlemstra
=> Imagemagick support

projects/imagemagick/build.sh
We decided to move the files in the project (touches #1056 and https://github.com/ImageMagick/ImageMagick/issues/933)
=> Files were moved in the ImageMagick project.

projects/irssi/build.sh
This corresponds to irssi/irssi#780, which was recently merged. As I state over there, I doubt this will actually find anything. More interesting fuzz targets are in the works. But this should increase coverage a little.
=> [irssi] Add event-get-params-fuzz

projects/systemd/Dockerfile, projects/systemd/build.sh, projects/systemd/project.yaml
Add the tooling for systemd fuzzing.
The reference to my git fork is temporary and will be changed before this is merged (once I get https://github.com/systemd/systemd/pull/7876 with the fuzzing code merged upstream).
CCing @poettering (who doesn't know this is coming) for feedback. Who else should be copied on fuzzer bugs?
=> [systemd] Add initial systemd integration

projects/llvm/build.sh
Adding new pass to the llvm-opt-fuzzer.
=>  [llvm][opt-fuzzer] Add early-cse pass as a new fuzzing target

projects/radare2/project.yaml
Thanks to @revskills for his tips and advice
=> Added radare2 as new project

projects/libreoffice/Dockerfile
=> add sft corpus

projects/skcms/project.yaml, projects/skia/project.yaml
Set UBSAN on SKCMS/Skia to non-experimental
Add Mike to be able to view Skia's fuzz results.
=> Tweak Skia/SKCMS project configs

projects/gnutls/build.sh
Signed-off-by: Nikos Mavrogiannopoulos <nmav@redhat.com>
=> [gnutls] unconditionally disable assembler in gmp

projects/libssh/build.sh
=> [libssh] The ssh_server_fuzzer code is in the source directory

projects/harfbuzz/hb-fuzzer.options, projects/harfbuzz/project.yaml
Not sure if the file name is correct. I couldn't find what it needs to be named. Assumed it's the same as the binary.
=> [harfbuzz] Add timeout / adjust project location

projects/llvm/build.sh
Perhaps I should invent less verbose way for adding passes but current situation seems fine for now.
=> [llvm][opt-fuzzer] Fuzz loop vectorize, loop predication and guard widening passes

projects/wuffs/Dockerfile, projects/wuffs/build.sh, projects/wuffs/project.yaml
CLA submission is not necessary. I am also nigeltao@google.com.
=> Add projects/wuffs

projects/gstreamer/project.yaml
Add myself to the GStreamer project list
=> [gstreamer]: add Jan Schmidt for access

projects/envoy/Dockerfile
=> Envoy needs Python for its C/C++ compiler wrapper.

projects/open62541/Dockerfile
=> Update missing dependencies

projects/envoy/build.sh
This lets `-stdlib=libc++` propagate only to C++ sources, avoiding BoringSSL compilation errors seen in https://github.com/google/oss-fuzz/issues/1184#issuecomment-368277513.
This might work better than https://github.com/envoyproxy/envoy/pull/2681.
=> In the Envoy build, use `$CXXFLAGS` only for C++ sources.

projects/dropbear/Dockerfile
Fuzzing changes have been merged to the main Dropbear branch now
=> Use Dropbear main branch

projects/knot-dns/build.sh
See https://gitlab.labs.nic.cz/knot/knot-dns/commit/bd394005
=> [knot-dns] update git submodules with corpora

projects/libssh/build.sh
=> [libssh] Fix include path

projects/skia/BUILD.gn.diff, projects/skia/build.sh, projects/skia/skia.diff
Refactoring in https://skia-review.googlesource.com/c/skia/+/113165 needed to be sorted out
skbug.com/7491 was resolved, so fuzz target can be enabled
=> Fix Skia build and enable set_region fuzzer

infra/gcb/templates/src/build-status/build-status.html
=> Add timezone and mouseover to build-status page

projects/postgis/project.yaml
Darafei is one of the PostGIS core devs and he'd like to be notified of these to help fix issues.
=> Use Darafei's gmail account instead

projects/vorbis/Dockerfile, projects/vorbis/build.sh, projects/vorbis/decode_fuzzer.cc, projects/vorbis/project.yaml
I've contacted one of the maintainers (@tdaede) and he is enthusiastic about having libvorbis added to oss-fuzz. After this initial integration lands I'll migrate the fuzzer upstream and we can remove it from this repository.
=> Integration for libvorbis

projects/imagemagick/Dockerfile
Continuing the process of adding the many delegate libraries ImageMagick supports so we can exercise more corners of IM's codebase.
=> Add more IM delegates

projects/grpc/build.sh
=> Add address sorting submodule to gRPC build.sh

projects/wuffs/build.sh
Fixes #1272
The wuffs directory layout changed with
https://github.com/google/wuffs/commit/d1399fac
=> Fix projects/wuffs build failure

projects/net-snmp/Dockerfile, projects/net-snmp/agentx_parse_fuzzer.c, projects/net-snmp/build.sh, projects/net-snmp/project.yaml, projects/net-snmp/snmp_pdu_parse_fuzzer.c
I started with the fuzzer snippet that you provided to the net-snmp project, expanded it with some experience (for debugging during replication), and added another packet parser fuzzer.
=> Add net-snmp project

projects/skia/skia.diff
See https://bugs.chromium.org/p/chromium/issues/detail?id=829149#c3
=> [skia] Reverse condition in SkScan_Hairline

projects/libtiff/build.sh, projects/libtiff/tiff_read_rgba_fuzzer.cc
=> Revert "[WIP] move libtiff build scripts and fuzzers to the libtiff repo"

projects/gnutls/project.yaml
=> [gnutls] added Ander Juaristi

projects/skia/build.sh
This and https://skia-review.googlesource.com/c/skia/+/121354 should fix the new compile warnings that cropped up recently.
=> [skia] Refactor build.sh for easier silences

projects/envoy/build.sh
This avoids needing to manually add targets as we grow them in the Envoy
repo.
=> envoy: automatically discover fuzz targets.

projects/qubes-os/Dockerfile, projects/qubes-os/build.sh
Add fuzzing of qubes input proxy
=> qubes-os: add app-linux-input-proxy fuzzer

projects/imagemagick/Dockerfile
We need libde265 to build libheif
=> [imagemagick] re-add libde265

CONTRIBUTING, docs/faq.md
Hi. I use Google services frequently.
I'm a favorite company and I hope to contribute to Google. This time, I will send you PR because I found a point that I can correct about the notation of `Github` .
Other projects use the notation `GitHub` , but this project was fixed as `Github`
thank you.
=> Other projects use the notation GitHub, but this project was fixed as Github.

docs/new_project_guide.md
=> Document help_url in new project guide

projects/libidn/Dockerfile
package autoconf-archive is needed
=> Fix libidn build

projects/mbedtls/Dockerfile, projects/mbedtls/build.sh, projects/mbedtls/project.yaml
Found only one memory leak so far :
https://github.com/catenacyber/mbedtls/commit/0f905e58bfe65a618c16fb14a5cea04e62e0f7d5
=> MbedTLS integration

projects/skia/README.md, projects/skia/build.sh, projects/skia/skia.diff
See https://skia-review.googlesource.com/c/skia/+/128301 and https://skia-review.googlesource.com/c/skia/+/128309 for when the checks got integrated from Skia.
=> [skia] Move textblob_deserialize back to mem constraint build

projects/qcms/Dockerfile, projects/qcms/build.sh
Small corpus with just a few manually-made files that covers all profile types (and tags) qcms supports.
=> qcms corpus

projects/opendnp3/Dockerfile, projects/opendnp3/build.sh, projects/opendnp3/project.yaml
See as well https://github.com/automatak/dnp3/pull/234
=> Adds project openDNP3 (ICS protocol)

projects/vorbis/Dockerfile
should fix the current build failure
=> remove dockerfile entry for vorbis that's no longer needed

projects/libpsl/config.site
This should fix the libpsl build (forgot the file in the last MR).
=> [libpsl] Add config.site

projects/skcms/iccprofile.dict
=> [skcms] Remove GIF tokens from ICC dictionary.

projects/nestegg/project.yaml
Nestegg is the WebM demuxer used in Firefox.
=> [nestegg] Add project.yaml

projects/opendnp3/Dockerfile
After merge of #1440 and https://github.com/automatak/dnp3/pull/234
=> Use main branch for opendnp3 project

projects/libwebp/build.sh
=> libwebp: set max image size to reduce OOMs

projects/capstone/Dockerfile, projects/capstone/build.sh, projects/capstone/project.yaml
I thought it was here already
see https://github.com/aquynh/capstone/pull/1145
Do you think a corpus is relevant here ? (we deal with short inputs, and almost everything is a valid input)
=> Adds capstone project

projects/opendnp3/project.yaml
After #1440 
is this the right way to do ?
I testées locally and memory sanitizer seems to be working with this project
=> Adds memory sanitizer to opendnp3 project

projects/skia/build.sh
Don't forget to guard the build products as well on the afl build.
=> [skia] Fix afl build

projects/libcoap/Dockerfile, projects/libcoap/build.sh, projects/libcoap/pdu_parse_target.c, projects/libcoap/project.yaml
This pull request adds a new project called libcoap to OSS-Fuzz. It's author and maintainer Mr.Olaf Bergmann (CC @obgm) has authorized me to send this pull request.
=> libcoap: OSS-Fuzz integration

projects/libwebp/Dockerfile, projects/libwebp/build.sh, projects/libwebp/fuzz.h, projects/libwebp/fuzz_simple_api.c
I'm submitting it ahead for easier review.
=> libwebp: preparation for more fuzz targets

projects/harfbuzz/project.yaml
For https://github.com/google/oss-fuzz#accepting-new-projects
cc @khaledhosny
=> [harfbuzz] Update Khaled's address to his gmail

projects/elliptic-curve-differential-fuzzer/build.sh
@kcc is this the right way to use a dictionary ?
And I do not have access to this project on my oss-fuzz dashboard
Did I do something wrong in project.yaml ? Should I auto_ccs myself ?
=> Adds a dictionary for elliptic curve diff fuzzing

projects/capstone/Dockerfile, projects/capstone/build.sh, projects/capstone/project.yaml
Adds memory sanitizer
Adds next branch (current development with new architectures)
Remove tshark from capstone downloads
+ I will test a corpus
=> Better fuzzing for capstone project

projects/libaom/project.yaml
Hui has been looking at bugs found by fuzzer elsewhere, so adding him to CC list here too.
=> Add Hui to auto-ccs.

projects/mercurial/project.yaml
=> Enable msan for mercurial

projects/varnish/project.yaml
As per instructions. CLA signed.
=> Add varnish cache

projects/brotli/build.sh
Brotli fuzzer is being converted to C99 in google/brotli#686
=> Update brotli build script

projects/grpc/build.sh
https://github.com/grpc/grpc/pull/15595
=> Add nanopb includes after grpc/grpc#15595

infra/base-images/base-builder/Dockerfile, infra/base-images/base-builder/compile_perffuzz, infra/base-images/base-runner/run_fuzzer, infra/helper.py
https://github.com/carolemieux/perffuzz
=> Add support for running perffuzz in infra/helper.py

projects/capstone/build.sh
=> Right path for capstone directory

projects/nss/project.yaml
Unfortunately Tim left the NSS team.
=> updating primary contact for NSS

projects/unrar/build.sh
-DSILENT is already used in Chromium and -DRAR_NOCRYPT will be added soon.
=> Add -DSILENT -DRAR_NOCRYPT defines when compiling unrar

projects/libaom/project.yaml
Adding @jaikrishnan to auto_ccs so he can potentially triage the issues.
=> libaom: Add Jai to CC list.

projects/capstone/build.sh
To build standalone shared library for python bindings
Following #1527 
See https://github.com/aquynh/capstone/pull/1188 as well
@jonathanmetzman what do you think ?
=> Cancel CFLAGS temporarly for capstone

projects/capstone/build.sh
=> Right path for capstone corpus

projects/capstone/build.sh
@Dor1s this is what you asked in #1561
=> Absolute paths for capstone build

projects/capstone/build.sh
Finally fixing the build after #1527 
I got my machine back and tested it locally and it works
=> Fix use of variables in capstone build.sh

projects/knot-dns/build.sh
Relates to https://gitlab.labs.nic.cz/knot/knot-dns/commit/6536d71bdf590c8
=> [knot-dns] Add dname to/from string tests

projects/bignum-fuzzer/Dockerfile, projects/bignum-fuzzer/build.sh
Differential bignum fuzzing of OpenSSL vs libgmp.
I will be reaching out to the libgmp mailing list to collect CC addresses.
=> GNU multiprecision (libgmp) fuzzer

projects/skcms/build.sh
Slight change to how skcms is being built.  This now works locally.
@inferno-chromium @jonathanmetzman
=> [skcms] Fix skcms build

projects/skia/skia.diff
Just required a simple rebasing.
=> [skia] Fix Skia Build

projects/envoy/project.yaml
I'm in need of access to project envoy to view the testcases.
=> Added my email to envoy CC list

projects/freetype2/Dockerfile
These libraries could become interesting in the future which is why we want to add them already and activate them as soon as we see fit:
- libpng-dev
- zlib1g-dev
=> [FreeType2] Add libraries for future use

projects/firefox/build.sh
Please read [this comment](https://github.com/google/oss-fuzz/issues/1462#issuecomment-407993586).
=> firefox: rust PATH fix

projects/skia/skia.diff
=> [skia] Fix build breakage.

infra/base-images/base-clang/checkout_build_install_llvm.sh
The original issue should be fixed now as per https://github.com/google/oss-fuzz/issues/1560#issuecomment-400046510
=> [infra] Do not force our LLVM revision.

projects/harfbuzz/build.sh
=> [harfbuzz] Fix incorrect source file for hb-subset-get-codepoints-fuzzer.

projects/usbguard/Dockerfile, projects/usbguard/build.sh, projects/usbguard/project.yaml
USBGuard is a project that provides policy enforcement for attached
USB device to protect against malicious on unauthorized USB devices.
This adds initial support for the USBGuard project.
This should not be merged before this pull request is executed:
https://github.com/USBGuard/usbguard/pull/244
I wanted to start the review process in case I need to make changes to the USBGuard pull request.
=> [projects] Added USBGuard.

projects/skia/skia.diff
Should be landed after https://github.com/google/oss-fuzz/pull/1677 and then reverted after verifying ASAN correctly finds and files a bug.
=> Intentional bug for verifying ASAN

projects/skia/skia.diff
This reverts commit e6673eada5c75c59f3c27506c20593dfadbc0011.
=> Revert "[skia] Intentional bug for verifying ASAN (#1678)"

projects/gnupg/Dockerfile, projects/gnupg/build.sh
So that we will no longer need pull requests on oss-fuzz
when one new fuzz target is added in gnupg code
And there is new fuzz target : fuzz_list
=> Generic listing of fuzz targets for project gnupg

projects/firestore/Dockerfile, projects/firestore/build.sh, projects/firestore/project.yaml, projects/firestore/project.yml
This is a pull request to add the Firestore SDK project to OSS-Fuzz.
* Submitted by a contributor who is working on fuzz-testing the SDK.
* Google accounts provided in the `auto_ccs`.
=> Add Firestore sdk project

projects/ecc-diff-fuzzer/Dockerfile, projects/ecc-diff-fuzzer/build.sh
Also adds corpus to the project
Any better idea than my ugly hack as both gcrypt and openssl export a function named `poly1305_blocks` ?
=> Adds gcrypt to elliptic curve diff fuzzer

projects/ecc-diff-fuzzer/Dockerfile, projects/ecc-diff-fuzzer/build.sh
Looks like this cpp library is used by ethereum
=> Adds cryptopp module to ecc-diff-fuzzer

projects/skia/BUILD.gn.diff
=> [skia] Fix build after picture_utils went away

infra/base-images/base-runner/Dockerfile, infra/base-images/base-runner/download_corpus
Needed to make https://github.com/google/oss-fuzz/pull/1547 work with projects that have 90+ fuzz targets.
=> [infra] Add script for downloading a batch of corpus backups (for #1547).

projects/envoy/build.sh
Do the path mangling and symlink resolution needed to deal with Bazel.
=> envoy: profile coverage support.

infra/base-images/base-runner/Dockerfile, infra/base-images/base-runner/coverage, infra/base-images/base-runner/coverage_helper, infra/base-images/base-runner/coverage_helper.py
This seems to be working well. As for the directory view, I'm trying to refactor the Chromium script right now. If it goes well, we'll borrow `coverage_utils.py` script from Chromium, but still would use this `coverage_helper` as a wrapper that imports `coverage_utils` (it's a new file where I'm refactoring the existing APIs to).
=> [infra] Coverage: handle shared libraries via coverage_helper script.

infra/gcb/build_and_run_coverage.py, infra/gcb/jenkins_config/coverage_job.xml
This should resolve a bunch of failures mentioned in #1743.
=> [infra] Skip coverage job for projects w/o fuzz targets (fix #1743, follow-up #1547).

infra/gcb/build_and_run_coverage.py, infra/gcb/build_project.py
=> [infra] Skip code coverage job for projects that are disabled (#1743, #1547).

projects/ecc-diff-fuzzer/Dockerfile, projects/ecc-diff-fuzzer/build.sh
And I am changing the input format after reading from @hanno https://github.com/hannob/bignum-fuzz/blob/master/point-fuzz.c 
Instead of having only scalars, input is composed of a compressed point (x coordinate and y bit), and one scalar
=> Adds nettle to ecc-diff-fuzzer

projects/envoy/project.yaml
* Remove Anirudh (end of GSoC)
* Add groebert@google.com.
=> envoy: auto-cc update.

projects/firefox/build.sh
=> firefox: copy ContentParentIPC.options to $OUT

projects/envoy/project.yaml
=> envoy: remove groebert@google.com from auto_ccs.

projects/envoy/build.sh
=> envoy: recover more artifacts for coverage build.

projects/glib/Dockerfile
Can be reverted with the next stable `meson` release.
=> Glib: fix profile build

projects/skia/BUILD.gn.diff, projects/skia/Dockerfile, projects/skia/build.sh, projects/skia/skia.diff
DO NOT LAND until https://skia-review.googlesource.com/c/skia/+/150560 lands.
This times out some, but https://skia-review.googlesource.com/c/skia/+/150465 has fixes for those.
=> [skia] Add Pathop fuzzer

projects/mupdf/pdf_fuzzer.cc
If mupdf throws an exception (extremely likely in when fuzzing),
none of the resources such as the rendered pixmap, document or
stream were reclaimed before exiting causing memory leaks. These
leaks were blamed on the software itself, when it actually was
the fuzzer implementation that leaked.
Fix this by always cleaning up all resources.
=> [mupdf] Plug memory leaks in fuzzer itself. (oss-fuzz #5497)

projects/qt/project.yaml
Adding project.yaml with basic info.
=> Add the Qt Project

projects/pffft/Dockerfile, projects/pffft/build.sh, projects/pffft/generate_seed_corpus.py
This patch adds a Python seed corpus generator which creates 3 different types of input arrays for a number of predetermined (valid) lengths.
=> Adding PFFFT seed corpus generation.

infra/gcb/build_and_run_coverage.py
PTAL. Addressing the comments from https://github.com/google/oss-fuzz/pull/1781
=> [infra] Add report date to the latest report info + fix format strings (follow-up #1547).

projects/gnupg/Dockerfile, projects/gnupg/build.sh
And patch in build.sh
As in #1793
=> Use main repo for Gnupg

projects/gnupg/Dockerfile, projects/gnupg/fuzzgnupg.diff
@jonathanmetzman following #1794
=> Adds diff file for gnupg in oss-fuzz repo

projects/gnupg/Dockerfile, projects/gnupg/project.yaml
Cf https://dev.gnupg.org/T4093
=> Change mail address for gnupg project

projects/unicorn/build.sh, projects/unicorn/project.yaml
Following #1725 
@inferno-chromium I tested with `python infra/helper.py check_build unicorn` to make sure that all the targets are good to fuzz
=> Enables unicorn project

projects/libwebp/Dockerfile, projects/libwebp/build.sh, projects/libwebp/fuzz.dict, projects/libwebp/fuzz.h, projects/libwebp/fuzz_advanced_api.c, projects/libwebp/fuzz_animation_api.c, projects/libwebp/fuzz_demux_api.c, projects/libwebp/fuzz_simple_api.c, projects/libwebp/fuzz_webp_enc_dec.cc
- Add fuzz_webp_enc_dec and adapt Dockerfile, build.sh
- Lint existing targets
- Add license headers
- Increase fuzz.dict
=> Add new fuzz target for encoding and misc

projects/keystone/Dockerfile, projects/keystone/build.sh, projects/keystone/project.yaml
Following https://github.com/keystone-engine/keystone/pull/371 and https://github.com/keystone-engine/keystone/pull/375
It will be ok when https://github.com/keystone-engine/keystone/pull/376 is merged
=> Adds project Keystone

projects/openvswitch/project.yaml
This PR enables MSan support for Open vSwitch. All integration guidelines have been followed.
=> OvS: Add MSan

projects/mupdf/pdf_fuzzer.cc
This fixes oss-fuzz #5679 and oss-fuzz #7803 for the mupdf project.
I have tested this locally and works fine; detecting 
allocations that in total are above 1Gbyte.
=> [mupdf] Add custom allocator to avoid having fuzzer kill process (#1830)

projects/openvswitch/Dockerfile, projects/openvswitch/build.sh
This PR refactors build script of Open vSwitch:
- Creates a zip of seed corpus only if such a corpus exists
- Creates a temp place holder for corpus dir name
=> OvS: Refactor build.sh

projects/tensorflow/project.yaml
We're restarting the process of integrating tensorflow in OSSFuzz. First step is the very easy one of editing the yaml file to change contact addresses.
=> Update contact list for tensorflow

projects/dav1d/Dockerfile, projects/dav1d/build.sh, projects/dav1d/project.yaml
dav1d is an AV1 decoder
http://www.jbkempf.com/blog/post/2018/Introducing-dav1d
Mozilla is planning to use the decoder in Firefox
https://bugzilla.mozilla.org/show_bug.cgi?id=1493397
=> [dav1d] add dav1d project

projects/bignum-fuzzer/project.yaml
This should fix https://github.com/google/oss-fuzz/issues/1834
Please let me know if it doesn't..
=> [bignum-fuzzer] Add ARM e-mail address. Disable AFL

infra/base-images/base-builder/Dockerfile
Similar to https://github.com/llvm-mirror/clang/blob/47b01c3d4b1906279589b36af1d38ee3b29fe3ae/lib/Driver/ToolChains/CommonArgs.cpp#L563
=> [infra] Fix missing linking dependencies for coverage build (#1858).

infra/gcb/build_and_run_coverage.py
Pretty minor change (similar to existing steps build_project.py), tested manually. TBR.
=> [infra] Add srcmap step to code coverage job (follow-up #1547).

docs/code_coverage.md
=> code_coverage.md: fix coverage tool invocations

projects/libpcap/Dockerfile, projects/libpcap/build.sh, projects/libpcap/project.yaml
Asked in #402 
See https://github.com/the-tcpdump-group/libpcap/pull/748 for discussion with project maintainers
=> adds libpcap project

projects/libpcap/project.yaml
@guyharris @infrastation are there more people's google account to be added ?
(this PR follow discussion in #1756)
=> Adds people to libpcap ccs

projects/harfbuzz/build.sh
Regarding https://github.com/harfbuzz/harfbuzz/pull/1258
=> [harfbuzz] Add a new place for looking for seeds

projects/dav1d/Dockerfile, projects/dav1d/build.sh, projects/dav1d/project.yaml
This pull request
- adds more people to the auto_cc list
- adds undefined behavior sanitizer
- changes the build to debugoptimized
- switches one seed corpus URL to https
=> dav1d updates

projects/grpc/build.sh
Was looking through this script to see what needs to be done for tensorflow and found this typo. Small fix, just to improve readability of script (or being too pedantic)
=> Fix typo in build.sh for grpc

projects/firefox/project.yaml
Reverts f68ff24a4f3379599728d506a82bbfcc73229da1. It's stable now.
=> firefox: unsubscribe myself

projects/gnupg/Dockerfile, projects/gnupg/build.sh
@Dor1s Sorry, this fixes a bug induced by #1871 
I tested it locally (after doing all the changes)
=> Gnupg uses separate fuzz targets

projects/libpcap/project.yaml
This is a follow-up to pull request #1756.
=> change my Google account address

projects/envoy/project.yaml
=> envoy: add jbuckland@google.com to project.yaml.

projects/unrar/Dockerfile
Source: https://rarlab.com/rar/unrarsrc-5.6.8.tar.gz
=> Fuzz unrar v5.6.8 before merging that to master

infra/gcb/requirements.txt
Reverts google/oss-fuzz#1913
Speculative fix for autosetup failure.
=> Revert "Update requests version 2.2.0"

projects/libpsl/build.sh
I don't wait any longer for 'publicsuffix' upstream to accept my patch / suggestions.
See also
- https://github.com/publicsuffix/list/issues/715
- https://github.com/publicsuffix/list/pull/720
=> [libpsl] Fix build: convert PSL to NFC

projects/dav1d/build.sh
Use the multi-threaded fuzzing target and share the seed corpus.
=> dav1d: build fuzzing binaries with meson

projects/yara/build.sh
yara: enable dotnet module for fuzzing
=> yara: enable dotnet module for fuzzing

projects/mandelbulber/project.yaml
Greetings,
Looking forward to our collaboration.
Thanks,
Coast
=> Add the mandelbulber project

projects/minizip/Dockerfile, projects/minizip/build.sh, projects/minizip/project.yaml
This pull request adds the minizip project to oss-fuzz. #1940
=> Fuzz minizip

projects/harfbuzz/build.sh
Reverts google/oss-fuzz#1950
Recommend building statically
=> Revert "[harfbuzz] Copy shared libraries to out"

projects/harfbuzz/build.sh
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=11384
https://github.com/google/oss-fuzz/pull/1950
=> [harfbuzz] Build static libraries

projects/envoy/build.sh
=> envoy: fix non-referrant symlinks in coverage build.

projects/zlib/checksum_fuzzer.c
Add a check for the recently added routines to combine crc32 checksums.  This
change adds more code coverage, however the checksum_fuzzer still does not pass
the complexity check: (the threshold is at 100)
oss-fuzz$ build/out/zlib/checksum_fuzzer -runs=10 2>&1 | grep -Po "INFO: Loaded [[:digit:]]+ module.*\(.*(counters|guards)\):[[:space:]]+\K[[:digit:]]+"
92
=> projects/zlib: add test for fast crc32

projects/harfbuzz/build.sh
See also https://github.com/harfbuzz/harfbuzz/pull/1395
=> [harfbuzz] Add new seeds path

projects/firestore/Dockerfile
This should fix recent build failures.
=> [firestore] add build dependency on Python

infra/base-images/base-builder/Dockerfile, infra/base-images/base-builder/write_labels.py, infra/gcb/build_project.py, projects/libxml2/project.yaml
Also add "sundew" label to libxml2_xml_reader_for_file_fuzzer.
These add additional labels in filed bugs.
=> Add support for tags field in project.yaml (#1974)

projects/tpm2/project.yaml
I no longer work on this project (and have changed usernames)
=> Remove old username from tpm2 fuzzer subscription

infra/gcb/build_project.py, projects/tensorflow/project.yaml
=> [tensorflow] Speculative fix to get at least one successful build.

projects/perfetto/Dockerfile
=> Revert "[perfetto] Do not do shallow checkout."

infra/helper.py
This partly addresses https://github.com/google/oss-fuzz/issues/2006.
=> infra: add a command for downloading all corpora for a project from GCS

projects/libvpx/Dockerfile, projects/libvpx/build.sh
Add zip file for fuzzer seed file
Modify build.sh to copy file to output for processing
=> Add seed file for libvpx

projects/libhtp/project.yaml
As requested by @victorjulien in https://github.com/google/oss-fuzz/pull/1949#issuecomment-448588500
=> Change email address for primary contact of libhtp

projects/mpg123/Dockerfile, projects/mpg123/build.sh, projects/mpg123/byte_stream.h, projects/mpg123/decode_fuzzer.cc, projects/mpg123/project.yaml
See description of 7793f27 for some more background on why this was written the way it is.
=> Add mpg123_decode fuzzer

projects/leptonica/Dockerfile, projects/leptonica/build.sh, projects/leptonica/pix_rotate_shear_fuzzer.cc, projects/leptonica/project.yaml
Leaving myself as the primary contact for now.
=> [leptonica] Initial integration for leptonica

projects/wget/build.sh
Should fix the build (made some fixes upstream as well).
=> [wget] Fix order of link libraries

projects/gnutls/build.sh
=> [gnutls] use bootstrap before build

projects/giflib/Dockerfile, projects/giflib/build.sh, projects/giflib/dgif_target.c, projects/giflib/dgif_target.options, projects/giflib/gif.dict, projects/giflib/project.yaml
This PR:
Adds the giflib library to oss-fuzz (CC #402)
Adds target out-of-source to seek feedback from maintainer team
CC @bshastry 
CC @eric-s-raymond
=> Add giflib

projects/bignum-fuzzer/Dockerfile, projects/bignum-fuzzer/build.sh
Implemented suggested changes: https://github.com/google/oss-fuzz/pull/2061#issuecomment-450608906
It ought to work now.
=> [bignum-fuzzer] Fix Rust nightly installation, attempt #2

projects/opensc/project.yaml
OpenSC provides a set of libraries and utilities to work with smart
cards. Its main focus is on cards that support cryptographic operations,
and facilitate their use in security applications such as
authentication, mail encryption and digital signatures. OpenSC
implements the standard APIs to smart cards, e.g. PKCS#11 API, Windows’
Smart Card Minidriver and macOS Tokend.
=> Add OpenSC

projects/tensorflow/build.sh
Coverage build progressed and got a [new error](https://oss-fuzz-build-logs.storage.googleapis.com/log-d4d5c858-8908-406e-9923-c960408cba85.txt). This should fix it
=> Add missing directory to the rsync path

projects/tidy-html5/Dockerfile
The 'next' branch is the one that gets the latest features and fixes in practice.
=> Check out tidy-html5 from the 'next' branch, instead of the default 'master'.

projects/tensorflow/build.sh
Following [the new failure](https://oss-fuzz-build-logs.storage.googleapis.com/log-ad5cbca9-720e-4ce1-ab0b-eb3fdcc5c5f9.txt), this should make progress and hopefully should be the last PR here.
=> Copy more files on coverage runs

projects/solidity/project.yaml
=> solidity: Add Martin Swende to auto_ccs

projects/libspng/Dockerfile, projects/libspng/build.sh
This commit adds @kcc's custom PNG mutator metioned in https://github.com/google/oss-fuzz/pull/1664#issuecomment-457786528.
=> [libspng] add structure aware fuzzer

projects/kimageformats/Dockerfile, projects/kimageformats/build.sh, projects/kimageformats/kimgio_fuzzer.cc, projects/kimageformats/project.yaml
I'm part of the KDE security team
https://www.kde.org/info/security/
This works fine in my local tests
=> Add new project: kimageformats

projects/graphicsmagick/project.yaml
Remove Glenn Randers-Pehrson who sadly passed away last year.
=> Add a new person to GraphicsMagick issues

projects/icu/build.sh
New ICU fuzzer targets were added in PR https://github.com/unicode-org/icu/pull/371.
=> Adds build instructions for recently added ICU fuzzer targets

projects/icu/project.yaml
Also re-establish history between icu_fuzz branch and master.
=> Add team member email to notification list in icu/project.yaml

README.md, docs/clusterfuzz.md
Also remove trailing whitespace.
=> Link to CF Repo

projects/unbound/Dockerfile, projects/unbound/build.sh, projects/unbound/fuzztest.c, projects/unbound/parse_packet_fuzzer.c, projects/unbound/project.yaml
Seed corpus is derived from testdata/test_packets.*.bin in Unbound repo.
=> Add fuzzer for Unbound's parse_packet.

projects/proj4/Dockerfile
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=12964
=> proj.4 project: build requires pkg-config

projects/knot-dns/Dockerfile, projects/knot-dns/build.sh
Signed-off-by: Daniel Salzman <daniel.salzman@nic.cz>
=> [knot-dns] fix issue 13050 + tiny script cleanup

projects/opencv/project.yaml
@vpisarev , please don't hesitate to add yourself or anybody from your team. Thx !
=> Add myself as a cc

projects/opencv/project.yaml
=> [opencv] add email to "OpenCV" CCs

projects/opencv/project.yaml
Closes https://github.com/google/oss-fuzz/pull/2166/
=> Adding @garybradski to OpenCV

projects/libsrtp/Dockerfile, projects/libsrtp/build.sh, projects/libsrtp/project.yaml
I created this fuzzer last year and it found a bunch of memory bugs.
Cisco showed interest but communication with them has been difficult, but I'll be pinging them in https://github.com/cisco/libsrtp/issues/393 and request them to take command of this project.
=> Add libsrtp fuzzer

projects/casync/Dockerfile, projects/casync/build.sh, projects/casync/project.yaml
The necessary counterpart in casync:
https://github.com/systemd/casync/pull/193.
=> Add casync project

projects/tpm2-tss/Dockerfile, projects/tpm2-tss/build.sh, projects/tpm2-tss/project.yaml
Fuzzers were upstreamed in https://github.com/tpm2-software/tpm2-tss/pull/1225
=> [tpm2-tss] Integrate tpm2-tss

projects/libressl/build.sh
@thypon 
Build is failing, causing exceptions on our infra. 
Trying this fix, if this doesn't work, I will need to revert unless you can fix soon.
=> [libressl] Speculative build fix

projects/tpm2-tss/build.sh
Fixes: #2219
Signed-off-by: John Andersen <john.s.andersen@intel.com>
=> [tpm2-tss] Change targets from .fuzz to _fuzz

docs/new_project_guide.md
=> docs: Require no extention in new_project_guide.md

projects/tesseract-ocr/Dockerfile, projects/tesseract-ocr/build.sh
Per @stweil 's request: https://github.com/tesseract-ocr/tesseract/issues/2300#issuecomment-471057721
=> [tesseract-ocr] Use Leptonica master branch

projects/picotls/Dockerfile, projects/picotls/build.sh
Hello,
Following up on https://github.com/google/oss-fuzz/pull/2218, this PR adds an initial integration for [picotls](https://github.com/h2o/picotls).
Thanks,
Jon
=> [picotls] Initial picotls integration

projects/bignum-fuzzer/project.yaml, projects/libsrtp/project.yaml
Per https://github.com/google/oss-fuzz/pull/2183#discussion_r260027873
=> [bignum-fuzzer, libsrtp] Enable AFL

projects/skia/BUILD.gn.diff, projects/skia/Dockerfile, projects/skia/build.sh
Like the other sksl fuzzers, this may crash shortly after startup due to https://bugs.chromium.org/p/skia/issues/detail?id=8876
Requires https://skia-review.googlesource.com/c/skia/+/201645 to land first
=> [skia] add sksl2pipeline

projects/libressl/Dockerfile, projects/libressl/bignum.options, projects/libressl/build.sh, projects/libressl/project.yaml
This reverts commit 098760e6dfe1fc1d8d368b499be3d9b6c748bb07.
Cc: @inferno-chromium @jonathanmetzman
=> New project: libressl (v2)

projects/libressl/project.yaml
Remove the distribution list and split out individual contributors instead.
=> add libressl fuzz contacts

projects/cppcheck/Dockerfile, projects/cppcheck/build.sh, projects/cppcheck/project.yaml
I am the maintainer for Cppcheck and would like to improve the fuzz testing of this project.
=> Add project Cppcheck

projects/kimageformats/Dockerfile, projects/kimageformats/build.sh, projects/kimageformats/kimgio_fuzzer.cc
This pulls karchive that pulls, ecm and libzip and libzip pulls zlib
=> kimageformats: Include ora and kra handlers

projects/firestore/Dockerfile, projects/firestore/project.yaml
=> Fix Firestore build by adding missing build dependencies

projects/libtorrent/project.yaml
see https://github.com/google/oss-fuzz/issues/2261#issuecomment-479085906
Thanks!
=> [libtorrent] add address for google account

projects/bignum-fuzzer/Dockerfile, projects/bignum-fuzzer/build.sh
=> Revert "Remove mbed TLS fuzzer"

projects/libxslt/Dockerfile, projects/libxslt/build.sh
Integrate the first fuzz targets from libxslt.
Closes #2192.
=> [libxslt] Start with integration

projects/karchive/Dockerfile, projects/karchive/build.sh, projects/karchive/karchive_fuzzer.cc, projects/karchive/project.yaml
karchive is KDE's library to access compressed files, i.e. zip/gz/tar/bz/xz
so need to compile all those and Qt
I'm part of KDE's security team
=> New project: karchive

projects/kimageformats/build.sh, projects/kimageformats/kimgio_fuzzer.cc
oss-fuzz devels say this is optimal
=> kimageformats: Split fuzzer into 9 fuzzers

projects/graphicsmagick/Dockerfile
This will give us more information if the clone fails (which it does sometimes, probably due to sourceforge infra issues)
=> [graphicsmagick] Added --time flag to clone

projects/libpcap/Dockerfile, projects/libpcap/build.sh, projects/libpcap/patch.diff
See https://github.com/the-tcpdump-group/libpcap/pull/777
=> Custom patch for libpcap to avoid infinite loop

projects/llvm/build.sh
Addresses https://github.com/google/oss-fuzz/issues/2317
=> [llvm] Switch to LIB_FUZZING_ENGINE.

infra/base-images/base-clang/checkout_build_install_llvm.sh
This reverts commit 8b34fd89d24551a2268099a6213a6152922cb601.
=> Revert "[infra] Revert the recent clang roll to fix some builds (#2315) (#2316)

projects/cryptofuzz/build.sh, projects/freeimage/build.sh, projects/jsonnet/build.sh, projects/libsass/build.sh, projects/opencv/build.sh
Now that #2328 is solved, migrate the projects that had trouble with exceptions so we can verify the fix.
=> Migrate projects with trouble with exceptions to $LIB_FUZZING_ENGINE

projects/gfwx/Dockerfile, projects/gfwx/build.sh, projects/gfwx/project.yaml
=> [gfwx] Add gfwx fuzzers

projects/libxslt/build.sh, projects/yajl-ruby/build.sh
These projects caused some issues last time I tested migrating them but I think the problems may have been flukes. Try migrating them again. Will revert if build fails.
=> Try migrating yajl-ruby+libxslt to LIB_FUZZING_ENGINE

projects/libpcap/build.sh, projects/unicorn/build.sh
This is a speculative workaround for #2369
=> [unicorn][libpcap] Try using -lFuzzingEngine to fix MSAN issue

projects/llvm/build.sh
=> [llvm] Update clangd test path.

projects/envoy/build.sh
=> envoy: fix build after recent clang update.

projects/libxslt/build.sh
- Link targets with fuzz.o
- Move code block for readability
=> [libxslt] Adjust build script

projects/neomutt/project.yaml
Adding @gahr to auto_ccs for bug report access and notifications.
=> Add @gahr to neomutt auto_ccs

projects/unrar/unrar_fuzzer.cc
This should fix https://crbug.com/oss-fuzz/14669
=> [unrar] Use std::error_code in calls to fs::current_path and fs::remove_all

projects/libressl/project.yaml
Please add an additional LibreSSL fuzz contact. Thanks!
=> add libressl fuzz contact

infra/travis/travis_build.py
Improve print statements and handling of projects that do not list sanitizers in project.yaml.
=> [travis] Improve build script

infra/base-images/base-clang/checkout_build_install_llvm.sh
Roll clang to r360398 to uptake fixes to #2369 and to unblock #2347
=> [infra] Roll clang to r360398

projects/envoy/project.yaml
=> envoy: add new project auto CCs.

infra/base-images/base-clang/checkout_build_install_llvm.sh
=> Revert "[infra] Roll clang to r360398"

projects/cryptofuzz/Dockerfile, projects/cryptofuzz/build.sh, projects/cryptofuzz/project.yaml
Crypto++ has been asked but have not responded yet: https://github.com/weidai11/cryptopp/issues/833
The CC added to the project file is of the libgcrypt maintainer, with his permission.
=> [cryptofuzz] Add Crypto++ and libgcrypt

infra/base-images/base-builder/compile, infra/base-images/base-runner/bad_build_check, infra/gcb/build_project.py, infra/helper.py, infra/travis/travis_build.py
* Fix check_build for i386 and add architecture check.
* Change method for linking against i386 libc++.
* Make check_build work for i386 on travis.
=> [i386] Improve linking and bad build check

infra/base-images/base-runner/bad_build_check
Make fuzzers fail checks for the wrong engine.
=> [infra] Fix check_instrumentation in bad_build_check

infra/base-images/base-runner/bad_build_check
Also change error message and comment.
=> Nonfunctional name change of check_instrumentation

.travis.yml, infra/travis/travis_build.py
=> [travis] Use job matrix to split up builds to avoid timeout

projects/mruby/project.yaml
=> mruby: Update primary email

projects/skcms/project.yaml
Approved by @kjlubick offline.
=> [i386] Do i386 builds of skcms

projects/karchive/karchive_fuzzer.cc
and also reset (i.e. seek to the beginning) the buffer to the start each loop
=> karchive: Also exercise the compressed tar codepaths

projects/icu/build.sh
detection of these files using wildcards.
=> Replaces explicit listing of fuzzer target and corpus files with generic

projects/dav1d/build.sh
Requires https://code.videolan.org/videolan/dav1d/merge_requests/714
=> dav1d: fix afl build by using $LIB_FUZZING_ENGINE

projects/ecc-diff-fuzzer/Dockerfile, projects/mbedtls/Dockerfile
Cf https://github.com/ARMmbed/mbedtls#getting-files-form-git-the-crypto-submodule
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=14970
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=14973
=> Mbedtls needs recusive clone now

projects/ecc-diff-fuzzer/build.sh, projects/mbedtls/build.sh
=> Fixes path for mbedtls crypto library

projects/gnupg/project.yaml
=> Revert "[AFL][gnupg] Disable AFL to stop exceptions"

projects/njs/Dockerfile, projects/njs/build.sh, projects/njs/njs_process_script_fuzzer.c, projects/njs/project.yaml
Hey @xeioex @hongzhidao @drsm ,
would you guys be interested in fuzzing njs continuously on OSS-Fuzz? This fuzz target finds at least a couple bugs just in seconds.
I've taken a bunch of boilerplate stuff from njs_shell, so long term it would be better to reuse that code rather than duplicate it, but should be fine for now.
=> [njs] Add nginx/njs project and njs_process_script_fuzzer.

projects/ffmpeg/build.sh
A step toward better coverage of Fuzzing in FFmpeg.
=> projects/ffmpeg/build: Add Demuxer fuzzer

projects/envoy/project.yaml
=> Update Envoy configuration

projects/tpm2-tss/Dockerfile, projects/tpm2-tss/project.yaml
@AndreasFuchsSIT I've added you on the CC list (Sorry it took me so long)
Also, this should fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=14839#c2
=> [tpm2-tss] Add Andreas to CC list and sync Dockerfile

projects/cpython3/build.sh
The MSan build for cpython is currently failing: https://oss-fuzz-build-logs.storage.googleapis.com/log-b615b2a6-cc02-4c57-b878-748d3c45aa2c.txt
It seems like it's because python creates a symlink from `bin/2to3 -> bin/2to3-3.9` which ends up becoming invalid somewhere in the docker image change. Using `altinstall` causes python to not create these symlinks.
=> [cpython] Use altinstall to avoid creating symlinks

README.md, docs/corpora.md, docs/new_project_guide.md
This adds to the documentation information that I would have found
helpful when I was doing my integration.
Whoever reviews this should make sure the changes I made to the docs are in fact correct.
=> Clarifications to the documentation

projects/uwebsockets/build.sh
~~This adds more targets to raise the total coverage~~
This moves building rules out of oss-fuzz repo so that I can add more fuzz targets without merging anything here
=> [uwebsockets] Hold building script at main repo

projects/piex/Dockerfile, projects/piex/build.sh, projects/piex/project.yaml
As requested in https://github.com/google/oss-fuzz/issues/402.
Finds one crash (recursion stack overflow) so far, which I work around in my fuzzer: https://github.com/guidovranken/piex/blob/fuzzers/fuzzers/tiff_parser.cpp#L121
If you have somebody who will fix it, I will remove the workaround.
More to come but you may already merge.
=> [piex] Add piex fuzzer

projects/php/project.yaml
=> [php] Enable undefined sanitizer configuration (#1984).

projects/libcbor/project.yaml
cbor is a new serialization protocol (RFC 7049), it's used by things such as webauthn. libcbor is a popular implementation in C.
I've spoken with @PJK, the author, off list. Once this is merged I'll follow up with PRs to libcbor for the fuzzer and build script.
=> New project: libcbor

projects/qubes-os/Dockerfile, projects/qubes-os/build.sh, projects/qubes-os/project.yaml
Integration for an additional Qubes component: qubesdb daemon used for communication between VMs.
=> Added integration for qubes-core-qubesdb

projects/libcbor/Dockerfile, projects/libcbor/build.sh
=> Integrate libcbor fuzzer

projects/ghostscript/project.yaml
The upstream maintainer asked me to add them to the cc list.
=> Add upstream maintainer for ghostscript

projects/cpython3/build.sh
Python invokes some python build scripts during its `install` step which causes some uninstrumented libraries to throw MSAN errors. 
I added `halt_on_error=0` in a [previous commit](https://github.com/google/oss-fuzz/commit/9a67b6be92066449dfe223324c700539c9cc5c02#diff-6bf0d2cda961aa5902d6825590c8a5f9) but it seems like this is not all that's required to get MSAN to ignore errors. The binary also has to be compiled with `-mllvm -msan-keep-going=1`
=> [cpython] Fix MSAN build

projects/gnupg/fuzz_decrypt.c, projects/gnupg/fuzz_import.c, projects/gnupg/fuzz_list.c, projects/gnupg/fuzz_verify.c
Adding an argument to `public_key_list`
=> Updates fuzz targets for gnupg

projects/opencv/project.yaml
=> Added myself to opencv project

projects/libsrtp/Dockerfile, projects/libsrtp/build.sh
See also https://github.com/cisco/libsrtp/issues/393#issuecomment-509318348
=> [libsrtp] Use upstream libsrtp

projects/libssh/Dockerfile, projects/libssh/build.sh
This adds the libssh client fuzzer to oss-fuzz.
=> Add the libssh client fuzzer

projects/systemd/project.yaml
@ssahani generally I can't seem to make my "ya.ru" account work (even though I heard it's possible) so should something go wrong we can always replace it with your gmail account.
@cdown after I invited you to the systemd organization on Coverity I was going to ask whether you were interested in also viewing issues reported by OSS-Fuzz but probably got distracted and forgot. While I'm at it I can add you to the list as well. Is it OK?
=> [systemd]: add Susant Sahani and Chris Down

projects/envoy/build.sh
=> [envoy] define force_libcpp=enabled

projects/lz4/project.yaml, projects/zstd/project.yaml
* Add new team members
* Switch primary contact for zstd to my @fb.com email
=> [zstd] Update contacts

projects/jsonnet/Dockerfile, projects/jsonnet/build.sh, projects/jsonnet/convert_jsonnet_fuzzer.cc, projects/jsonnet/project.yaml
Reverts google/oss-fuzz#2595
Looks like it was actively finding bugs.
=> Revert "Remove unmaintained jsonnet."

projects/cryptofuzz/project.yaml
See https://github.com/openssl/openssl/issues/8827#issuecomment-511374563
=> [cryptofuzz] Add Richard of OpenSSL to auto_ccs

projects/strongswan/build.sh
=> [strongswan] Switch back to LIB_FUZZING_ENGINE

projects/solidity/Dockerfile, projects/solidity/build.sh
This PR
- instruments evmone and its dependencies
- enables abiv2 proto fuzzer
CC @chriseth
=> Solidity: Enable abiv2 proto fuzzer

projects/envoy/build.sh
@htuch @asraa
Signed-off-by: Lizan Zhou <lizan@tetrate.io>
=> [envoy] fix envoy fuzz build

projects/gnutls/build.sh
=> gnutls: use new method to boostrap libtasn1

projects/cryptofuzz/project.yaml
See https://github.com/openssl/openssl/issues/9359#issuecomment-513068102
=> [cryptofuzz] Add Pauli Dale

projects/ots/build.sh
Helps quickly debugging build failures.
=> [ots] Show meson log on setup failure

projects/cryptofuzz/build.sh
This didn't work a few months ago, but it looks like it does now.
This enables MSAN fuzzing of LibreSSL.
=> [cryptofuzz] LibreSSL noasm target

projects/cryptofuzz/Dockerfile, projects/cryptofuzz/build.sh
Enable module for Golang crypto
both x86 and i386 supported.
=> [cryptofuzz] Golang

projects/aspell/Dockerfile, projects/aspell/build.sh
Switch over to aspell-fuzz, which is a new repository to allow easier fuzzing fixes to be made.
---
WIP to verify this works in the CI. Tagging @kevina.
=> Switch from aspell to aspell-fuzz

projects/ntp/Dockerfile, projects/ntp/build.sh, projects/ntp/patch.diff, projects/ntp/project.yaml
Comments are welcome
Any idea on how to use bit keeper to get latest sources ?
=> Adds ntp project with ntpd fuzz target

projects/lame/project.yaml, projects/libsrtp/project.yaml, projects/rapidjson/project.yaml
=> [lame, libsrtp, rapidjson] Enable i386 builds

projects/django/Dockerfile, projects/django/build.sh, projects/django/project.yaml
Initial OK from devs here: https://groups.google.com/d/msg/django-developers/-WweB07YiVQ/uCu23CnZCQAJ
Awaiting further response from devs and resolution of some (security) bugs this fuzzer found. Do not merge yet (main fuzzing repository is still private).
=> [django-fuzzers]

README.md
Edits for clarity and added process diagram, to see how it looked.
=> Docs: Edit OSS-Fuzz landing page.

projects/libvips/project.yaml
=> [libvips] Add myself to auto_ccs

projects/spidermonkey-ufi/Dockerfile, projects/spidermonkey-ufi/build.sh, projects/spidermonkey-ufi/project.yaml, projects/spidermonkey-ufi/target.c
Adds project for Spidermonkey UFI (Universal Fuzzing Interface). LibFuzzer's which run inside of the JS Shell.
=> Add spidermonkey-ufi project

projects/libvips/project.yaml
=> [libvips] Add lovell to auto_ccs

projects/django/build.sh, projects/django/project.yaml
See also https://github.com/google/oss-fuzz/pull/2661
Should also fix coverage build
=> [django] No ASAN

projects/flac/Dockerfile, projects/flac/build.sh, projects/flac/project.yaml
https://github.com/xiph/flac/issues/125
=> [FLAC] FLAC fuzzers

projects/flac/build.sh
Also enables some additional memory checks
=> [FLAC] Encoder fuzzer

projects/postgis/Dockerfile, projects/postgis/build.sh
Closes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=15625
=> Fix PostGIS fuzzers build

projects/syzkaller/Dockerfile, projects/syzkaller/build.sh
=> [syzkaller] Make report_fuzzer build successfully and move deps to the Dockerfile.

projects/libavc/Dockerfile, projects/libavc/avc_dec_fuzzer.dict, projects/libavc/build.sh
avc_dec_fuzzer.dict is now picked from upstream project
=> [libavc] Move dictionary file to upstream project

projects/libgd/build.sh
- Add more formats to libgd's fuzzer
- Reorder the fuzzer's names
- Add some corpus for the new fuzzers
=> Add more fileformats to libgd's fuzzer

projects/golang/Dockerfile, projects/golang/build.sh
=> [golang] Use pre-installed go-fuzz dependencies (#2714).

infra/gcb/builds_status.py
Should fix https://github.com/google/oss-fuzz/issues/2755.
=> Create storage client only once for build status updates.

projects/unicorn/project.yaml
=> Adds one people for unicorn project

projects/usrsctp/Dockerfile, projects/usrsctp/build.sh, projects/usrsctp/project.yaml
Hi,
we would like to integrate our existing fuzzer suite into the OSS-FUZZ system.
=> Add usrsctp project

projects/opensc/project.yaml
By the way, is there an other way of letting people see the fuzzing results instead of adding them to CCs with a PR?
=> [opensc] added more CCs people

projects/matio/matio_fuzzer.cc
See #2761 for https://github.com/tbeu/matio/issues/124.
=> Add more API calls for matio

projects/skia/build.sh
We may want to do this to librawspeed/ntp depending on how long the clang fix/roll takes.
=> [skia] Temporarily use gold to hack around clang regression

projects/cryptofuzz/Dockerfile, projects/cryptofuzz/build.sh, projects/cryptofuzz/project.yaml
Also disabling libsodium because it currently produces crashing builds.
=> [cryptofuzz] Add Botan

projects/matio/Dockerfile, projects/matio/build.sh, projects/matio/project.yaml
Let's see if configure finds them...
=> [matio] Build with hdf5 and zlib support

projects/lz4/project.yaml, projects/zstd/project.yaml
=> zstd: lz4: Update auto_ccs

docs/getting-started/new_project_guide.md
=> [docs] Document shiny new badge in the docs

projects/openssh/build.sh
another new fuzzer, just added upstream
=> enable (brand new) sshsig options parsing fuzzer

projects/open62541/project.yaml
This adds an additional maintainer to the open62541 project
=> [open62541] Add additional maintainer

projects/libhtp/Dockerfile, projects/libhtp/build.sh
Cf https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=16988
=> Adds dependency to libhtp project : liblzma

projects/irssi/Dockerfile, projects/irssi/build.sh
Now irssi builds with the newer meson based build system.
server-fuzz is leak free now
=> Fix irssi build

projects/ecc-diff-fuzzer/Dockerfile, projects/ecc-diff-fuzzer/build.sh
Already found one bug before oss-fuzz integration :
https://github.com/randombit/botan/pull/2102
cc @randombit
=> Adds botan to ecc differential fuzzer

projects/solidity/Dockerfile, projects/solidity/build.sh
This PR
- Links solidity against z3 so that queries are actually solved and the result is propagated through to the output
CC @leonardoalt
=> solidity: Add and link solc against z3

projects/golang/project.yaml
I already got reports vis golang-fuzz@googlegroups.com, but this way I'll be able to see the details in the issue tracker.
Updates #2825
cc @Dor1s
=> [golang] add my email to project.yaml

projects/solidity/Dockerfile, projects/solidity/build.sh
Fixes #2834 and a z3 build failure that was silently ignored.
=> solidity: Use cmake toolchain file

projects/libhtp/project.yaml
=> Adds people to libhtp project

projects/libtheora/Dockerfile, projects/libtheora/build.sh, projects/libtheora/project.yaml
Green-lighted per https://github.com/google/oss-fuzz/issues/2790#issuecomment-528694725
I've sent a message to the theora-dev list,  awaiting reply.
@posidron I added you to vendor_ccs, please confirm that this is ok.
This fuzzer finds some bugs. @posidron If I get no reply from Xiph or they are not interested, is Mozilla willing to fix bugs and upstream patches?
=> [libtheora]

projects/graphicsmagick/project.yaml
I'm not 100% certain that this will work, but I don't see any reason it shouldn't either!
=> [graphicsmagick] build for i386

projects/xvid/project.yaml
Maintainer couldn't log in with existing e-mail -- this should resolve it.
=> [xvid] Add e-mail

.travis.yml
It seems to be causing the travis failure in #2852
=> don't use travis_wait

projects/libzip/build.sh
An upstream code cleanup broke the build, this should fix it.
=> [libzip] Fix build

projects/libtheora/project.yaml
=> [libtheora] Add vendor CC

projects/ibmswtpm2/Dockerfile, projects/ibmswtpm2/build.sh, projects/ibmswtpm2/fuzzer.cc, projects/ibmswtpm2/no_writes.patch, projects/ibmswtpm2/project.yaml
Signed-off-by: John Andersen <john.s.andersen@intel.com>
=> [ibmswtpm2] Integrate ibmswtpm2

projects/php/build.sh, projects/php/runtime.options
This enables the fuzzer for the `unserialize()` function. Additionally I have removed the `detect_leaks=0` option, as the fuzzers are no longer supposed to leak.
=> [php] Enable unserialize fuzzer

projects/php/build.sh
This enables the fuzzer for the PHP lexer and parser.
=> [php] Enable parser fuzzer

docs/further-reading/fuzzer_environment.md
I think @kcc recommended against this because it will probably encourage more people to use dynamic linking.
=> Add instructions on dynamic linking

projects/gnupg/Dockerfile, projects/gnupg/build.sh
And fix latest build failure https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=17307
=> use git for all gnupg dependencies

projects/gnupg/build.sh, projects/gnupg/fuzzgnupg.diff
This should fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=17307 if something does not break it meanwhile (cf #2894 worked when I tested it)
=> Fixes gnupg patch with conflict

projects/libavc/Dockerfile, projects/libavc/build.sh, projects/libhevc/Dockerfile, projects/libhevc/build.sh, projects/libmpeg2/Dockerfile, projects/libmpeg2/build.sh
Add seed corpus for libavc, libhevc and libmpeg2 fuzz targets
=> [libavc, libhevc, libmpeg2] Add seed corpus

projects/ecc-diff-fuzzer/Dockerfile, projects/ecc-diff-fuzzer/build.sh, projects/ecc-diff-fuzzer/project.yaml
Cf https://google.github.io/oss-fuzz/getting-started/new-project-guide/#architectures
=> Adds i386 architecture to ecc-diff project

projects/proxygen/project.yaml
Ideally we could add our mailing list but this will do for now.
=> Add some more CCs for proxygen

CONTRIBUTING.md
fix incorrectly typed markdown for creating hyperlinks
=> Fix hyperlink markdown

projects/go-attestation/Dockerfile, projects/go-attestation/build.sh, projects/go-attestation/project.yaml
Depends on google/go-attestation#125 for the target. Since this one of the first golang oss-fuzz projects and also my first, I'd appreciate a review of that PR as well. :)
=> [go-attestation] Add project

projects/binutils/Dockerfile, projects/binutils/build.sh, projects/binutils/fuzz_disassemble.c, projects/binutils/patch.diff, projects/binutils/project.yaml
With only one target for now for disassembly.
This pull request is meant to get feedback.
=> Adds project binutils

projects/binutils/project.yaml
cc @nickclifton
Should we add other people ?
=> Adds people to project binutils

projects/oak/Dockerfile, projects/oak/build.sh, projects/oak/project.yaml
This is done as part of the Google-internal go/fuzzit effort.
Ref https://github.com/project-oak/oak/issues/261
=> Add Oak project

projects/grpc/build.sh
Cleaning up the grpc target after the discussion in https://github.com/google/oss-fuzz/pull/2954#discussion_r335580871 .
cc @yang-g (who should probably also review, if available)
=> grpc target cleanup

projects/osquery/project.yaml
Per https://github.com/osquery/osquery/issues/5905 - @theopolis can confirm.
=> Add tom@ritter.vg to auto_ccs for osquery

projects/kubernetes/build.sh
Follow up for https://github.com/kubernetes/kubernetes/pull/83750, once that's submitted this should be good to go.
=> Added kubernetes json fuzz targets

projects/oak/project.yaml
cc @daviddrysdale @anghelcovici @michael-kernel-sanders
=> Add Project Oak team members

projects/catapult/project.yaml
This PR is a new project request for fuzzing of the Catapult server.  Catapult have been developed by several core developers and we are getting ready to release a new version.  
I am the test lead and will be setting up the project fuzzing targets.  On the cc list are couple of core developers who worked on the catapult server.  
All commits to the public repo is made by a catapultbot from a private repo but one of the devs on the cc list own this bot.  Please let us know if you have any question.
=> New project request for Catapult Server

projects/mysql-server/targets/fuzz_docommand.cc, projects/mysql-server/targets/fuzz_initfile.cc, projects/mysql-server/targets/fuzz_mysqld.cc
This should help having a more stable build for mysql project, see
https://github.com/google/oss-fuzz/pull/2922#issuecomment-544550442
=> Uses different directories for different mysql fuzz targets

projects/osquery/build.sh
Upstream changes: https://github.com/osquery/osquery/commit/1642382ff92bcbc33eb2d754b22a0776eb4646c7 cc @theopolis
=> Update osquery's build.sh for upstream changes

projects/skia/BUILD.gn.diff, projects/skia/Dockerfile, projects/skia/build.sh, projects/skia/skdescriptor_deserialize.options
Won't work until https://skia-review.googlesource.com/c/skia/+/249776 lands
=> [skia] Add skdescriptor

projects/ffmpeg/Dockerfile, projects/ffmpeg/build.sh
=> [ffmpeg] Drop mesa/drm, it does not build due to changes to its buildsys

projects/libxls/Dockerfile
=> [libxls] Build requires autoconf-archive

projects/ndpi/Dockerfile, projects/ndpi/build.sh, projects/ndpi/project.yaml
=> Adds ndpi project

projects/librawspeed/Dockerfile
As per https://apt.kitware.com/
I have tried locally, and it does fix the build.
=> [LibRawSpeed] Pull in newer cmake to fix the build

projects/go-json-iterator/Dockerfile, projects/go-json-iterator/build.sh, projects/go-json-iterator/fuzz_json.go, projects/go-json-iterator/project.yaml
This is my first contribution with a golang project and it seems interesting.
Already reported to author first runtime error :
https://play.golang.org/p/LYvQIQIzEzr
There are more found bugs from differential fuzzing...
I am not sure about the license as the fuzz target is heavily inspired by the Apache licensed https://github.com/dvyukov/go-fuzz-corpus/blob/master/json/json.go
=> Adds golang project json-iterator

projects/simdjson/Dockerfile
Upstream has merged fuzz support now. Thanks!
=> [simdjson] repoint to upstream repository

infra/base-images/base-builder/Dockerfile, infra/base-images/base-builder/compile_honggfuzz
These will be statically linked into the hongfuzz binary.
=> Add additional build deps for honggfuzz.

projects/bignum-fuzzer/build.sh
I don't know how to fix Rust right now.
=> [bignum-fuzzer] Disable Rust

projects/ecc-diff-fuzzer/Dockerfile, projects/ecc-diff-fuzzer/build.sh
With latest libgpg-error use
Should fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=18789
=> Fixes ecc-diff-fuzzer build

projects/mysql-server/targets/CMakeLists.txt, projects/mysql-server/targets/fuzz_docommand.cc, projects/mysql-server/targets/fuzz_initfile.cc, projects/mysql-server/targets/fuzz_mysqld.cc, projects/mysql-server/targets/util_fuzz.cc, projects/mysql-server/targets/util_fuzz.h
Cf https://github.com/google/oss-fuzz/pull/2922#issuecomment-555080111
Now the server fuzz targets should be able to run in minijail environment
=> mysql fuzz targets use custom rm and cp

projects/mysql-server/targets/util_fuzz.cc
Should fix build from and get #3046 going
=> Fix fuzz targets in mysql

projects/njs/build.sh
As it changed reproducibility of existing issues.
=> [njs] Reverting --debug=YES introduced in c16cf5a2.

projects/proxygen/Dockerfile
I have not yet tested this locally as my current laptop doesn't have a set up environment. Putting this up to see if Travis finds a green build, otherwise I'll set this up tomorrow.
=> [proxygen] Fix build by importing `fmt` in Dockerfile

infra/base-images/base-builder/Dockerfile
=> Enable UBSan's builtin, null, and unreachable checks.

projects/cras/Dockerfile, projects/cras/build.sh
We now use some rust code in CRAS, fix the fuzzer build so that code is
compiled as well.
=> [cras] fix build

infra/base-images/base-clang/checkout_build_install_llvm.sh, infra/helper.py
This should fix the latest build breakage in base-clang.
=> Install clang using git

infra/base-images/base-builder/Dockerfile
=> Revert "Enable UBSan's builtin, null, and unreachable checks."

infra/base-images/base-builder/Dockerfile
PTAL. Based on our discussion earlier, we can plan to land this some time on Sunday.
=> Enable UBSan builtin, null, returns-nonnull-attribute, and unreachable checks.

projects/ndpi/project.yaml
To have a google account
cc @lucaderi
=> Changes ndpi email address

projects/osquery/project.yaml
Adding myself as a contact for osquery project too.
@theopolis or @directionless can confirm.
=> Update osquery contact

projects/skia/skia.diff
=> [skia] Rebase memory-reducing fuzz patch

projects/go-attestation/build.sh
Builds on new methods in https://github.com/google/go-attestation/pull/141
=> Add new fuzzing methods to go-attestation config.

projects/cryptofuzz/Dockerfile, projects/cryptofuzz/build.sh, projects/cryptofuzz/project.yaml
Kevin Jacobs of Mozilla is aware of this integration and has supplied the CC list.
=> [cryptofuzz] NSS

projects/oak/project.yaml
=> Add more Oak team members

projects/samba/Dockerfile, projects/samba/project.yaml
We would like to add Samba to oss-fuzz.
=> Add stub project.yaml for Samba

projects/ffmpeg/build.sh
Enable fuzzing of bitstream filters using target_bsf_fuzzer
=> [FFmpeg] Add fuzzing for bitstream filters

projects/binutils/project.yaml
Alan Modra fixed https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=18675 for instance
=> Adds people to binutils project

projects/solidity/Dockerfile
This should fix ossfuzz issues numbered 19056 and 19116
=> solidity: Upgrade to evmone v0.4.0

projects/brotli/project.yaml, projects/freetype2/project.yaml, projects/harfbuzz/project.yaml, projects/libpng/project.yaml, projects/libwebp/project.yaml, projects/opus/project.yaml, projects/ots/project.yaml, projects/skia/project.yaml, projects/woff2/project.yaml
* Update and add Mozilla employees to existing projects
=> Update multiple vendor_ccs lists

projects/samba/Dockerfile, projects/samba/build.sh, projects/samba/project.yaml
The previous PR had the wrong WORKDIR, this one has been tested.
=> Fix WORKDIR for Samba

projects/gonids/build.sh
=> Fix gonids target name to match seed corpus

projects/llvm_libcxx/Dockerfile, projects/llvm_libcxx/build.sh
=> [llvm_libcxx] switch to the new github repo

projects/llvm_libcxx/project.yaml, projects/llvm_libcxxabi/project.yaml
@kcc Could you please take a look.
=> Add myself to libc++ and libc++abi project files.

projects/karchive/build.sh, projects/kcodecs/build.sh
I'm being a bit naughty building Qt so this is mostly my fault
=> Fix build of karchive and kcodecs

infra/base-images/base-builder/Dockerfile
=> Enable UBSan's object-size check.

projects/wxwidgets/build.sh
This will make it simpler to extend and maintain the script, e.g. by
adding more fuzz targets.
---
There are no changes yet, but we plan to add another fuzz target for image-reading code in wxWidgets soon. TIA for merging this!
=> Run the fuzzing script from the main wxWidgets repository

projects/osquery/project.yaml
=> Updated contacts for osquery project

projects/binutils/Dockerfile, projects/binutils/build.sh, projects/binutils/fuzz_bfd.c
=> Adds a new target to binutils project

projects/kubernetes/build.sh
This depends on https://github.com/kubernetes/kubernetes/pull/84168
//cc @BrendanSChang @mikedanese please ping this issue when the upstream PR is merged
=> [kubernetes] Enable three new fuzz targets (Duration, MicroTime, Time).

projects/xerces-c/xmlProtoConverter.cpp, projects/xerces-c/xmlProtoConverter.h
Fixes xerces-c ossfuzz issue 19507
CC @viniul
=> xml proto converter: Fix ossfuzz issue 19507 (no return value).

projects/tesseract-ocr/Dockerfile, projects/tesseract-ocr/build.sh, projects/tesseract-ocr/project.yaml
Fixes https://github.com/google/oss-fuzz/issues/3176
=> [tesseract-ocr] Fix build

projects/qt/build.sh
Qt: Use dictionary from AFL for XML
=> Use dictionary from AFL for XML

projects/freetype2/project.yaml
Rationale: I am maintaining the inclusion and rolling of FreeType into
Chromium and have been fixing bugs found by pdfium and chromium fuzzing
in FreeType.
=> Add myself to auto_ccs for FreeType

projects/ots/Dockerfile
Pin meson version to the latest working version.
=> [ots] Fix build

projects/wabt/Dockerfile, projects/wabt/project.yaml
I'm back from leave, so I'll take over maintenance of wabt fuzz bugs.
=> Update wabt maintainer

infra/helper.py
Arguments for reproduce_impl were incorrect.
=> [infra] helper.py repoduce fix

infra/helper.py
Format and fix most pylint complaints. Disable a few.
=> Make helper.py presubmit-clean

projects/arrow/project.yaml
I'd like to be able to see these bugs.
=> Add Micah Kornfield to AutoCC for Apache Arrow

infra/helper.py
=> Fix regression introducing attribute error when reproducing crashes

infra/gcb/build_project.py
This is running as https://console.developers.google.com/logs/viewer?resource=build%2Fbuild_id%2Fa25be6cb-e295-448c-9c39-9233e0de8cf2&project=oss-fuzz, will let it finish first before merging.
=> [infra] Add env variable to the DF collection GCB step (#1632).

projects/xz/build.sh
Upstreaming is somewhat hard (although in process), this shouldn't harm to have.
=> [xz] Apply a harmless local patch to migrate to $LIB_FUZZING_ENGINE.

projects/harfbuzz/project.yaml
Calder likes to get CC'd to recent fuzzer failures and
plans to develop more subset features so let's update the CC list.
=> [harfbuzz] Add ckitagawa

projects/qt/build.sh
This will make it easier to add further fuzz targets and to change the naming schemes.
=> [qt] Add bash function for building fuzz targets

projects/openthread/project.yaml
Tested with https://pantheon.corp.google.com/logs/viewer?resource=build%2Fbuild_id%2F38c41d0b-330c-402b-9fb4-6a040ad837a7&project=oss-fuzz&minLogLevel=0&expandAll=false&timestamp=2020-01-21T23:46:37.290000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeEnd=2020-01-21T23:43:15.644Z&interval=PT1H&dateRangeUnbound=backwardInTime&scrollTimestamp=2020-01-21T19:56:32.094905881Z
=> [openthread] enable dataflow config (#1632).

projects/wuffs/project.yaml
Tested with https://pantheon.corp.google.com/logs/viewer?resource=build%2Fbuild_id%2Fb5b0bd85-2754-4b7e-b388-e0e9615023a8&project=oss-fuzz&minLogLevel=0&expandAll=false&timestamp=2020-01-21T23:46:40.714000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeEnd=2020-01-21T23:43:30.052Z&interval=PT1H&dateRangeUnbound=backwardInTime&scrollTimestamp=2020-01-21T18:53:52.366704300Z
=> [wuffs] enable dataflow config (#1632).

projects/libplist/project.yaml
Tested with https://pantheon.corp.google.com/logs/viewer?resource=build%2Fbuild_id%2F122eb1f3-a362-4767-9d30-b4a0eb1a00fc&project=oss-fuzz&minLogLevel=0&expandAll=false&timestamp=2020-01-21T23:39:24.329000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeStart=2020-01-21T22:39:24.581Z&dateRangeEnd=2020-01-21T23:39:24.581Z&interval=PT1H
=> [libplist] enable dataflow config (#1632).

projects/libpcap/project.yaml
Tested with https://pantheon.corp.google.com/logs/viewer?resource=build%2Fbuild_id%2F1dd2ae2d-de8e-473a-be47-f5a4d8b91250&project=oss-fuzz&minLogLevel=0&expandAll=false&timestamp=2020-01-21T23:37:48.115000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeEnd=2020-01-21T23:37:46.301Z&interval=PT1H&dateRangeUnbound=backwardInTime&scrollTimestamp=2020-01-21T19:04:23.178909352Z
=> [libpcap] enable dataflow config (#1632).

projects/libwebp/project.yaml
Tested as https://pantheon.corp.google.com/logs/viewer?resource=build%2Fbuild_id%2F8b9c16ef-8238-44c1-817c-03602fff5583&project=oss-fuzz&minLogLevel=0&expandAll=false&timestamp=2020-01-21T23:43:43.816000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeEnd=2020-01-21T23:43:11.054Z&interval=PT1H&dateRangeUnbound=backwardInTime&scrollTimestamp=2020-01-21T19:46:16.396688731Z
=> [libwebp] enable dataflow config (#1632).

projects/zlib-ng/project.yaml
Tested with https://pantheon.corp.google.com/logs/viewer?resource=build%2Fbuild_id%2F1890c88d-999b-4a95-9d21-20fa60f33e59&project=oss-fuzz&minLogLevel=0&expandAll=false&timestamp=2020-01-21T23:46:42.489000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeEnd=2020-01-21T23:43:33.616Z&interval=PT1H&dateRangeUnbound=backwardInTime&scrollTimestamp=2020-01-21T20:51:17.760469836Z
=> [zlib-ng] enable dataflow config (#1632).

projects/gnutls/project.yaml
=> [gnutls] updated maintainers

projects/envoy/build.sh
Moves dictionary with form <fuzz_target>.dict to /out/, oss-fuzz automatically picks up dictionaries of this form.
@htuch 
=> [envoy] Add support for dictionaries 

infra/presubmit.py, projects/wolfssl/project.yaml
Also slightly refactor `print_error` method to work without extra arguments and prefer `.format()` for strings.
=> [infra] Make presubmit script handle experimental flag in project.yaml (#3277).

infra/bisector.py, infra/bisector_test.py, infra/build_specified_commit.py, infra/build_specified_commit_test.py, infra/cifuzz.py
Previously it was a class that accepeted no arguments, requiring attributes to be set later.
=> Make BuildData a namedtuple

projects/mysql-server/fix.diff
Hope to fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=20174
=> Rebased patch for mysql

projects/cmark/project.yaml
Approved by @jgm here:
https://github.com/commonmark/cmark/pull/326#issuecomment-578393351
=> [cmark] Add myself to auto_ccs

projects/ecc-diff-fuzzer/build.sh
=> Updates project ecc-diff-fuzzer build

projects/libexif/exif_loader_fuzzer.cc, projects/libexif/project.yaml
This will fuzz EXIF MakerNotes, a huge sub-tree of EXIF data.
=> also fuzz exif makernotes

infra/base-images/base-builder/detect_repo.py, infra/bisector.py, infra/build_specified_commit.py
@jonathanmetzman requested to change print statements to logging statements in the previous pull request.
=> [Infra] Updating print statements

projects/wasmtime/project.yaml
Let's get Alex access to the console and on the email list :)
cc @jfoote
=> wasmtime: Add Alex Crichton to the auto cc list

infra/build_specified_commit.py, infra/repo_manager.py, infra/utils.py
The execute function nolonger belongs in the build_specified_commit.py module and fits better in the utils.py module. Also alphabetizes functions in utils.py
=> [Infra] Moving execute to utils.py

infra/cifuzz/actions/entrypoint.py, infra/cifuzz/cifuzz.py, infra/cifuzz/cifuzz_test.py, infra/repo_manager.py, infra/repo_manager_test.py
CIFuzz can now be triggered from both pushes and pull requests.
This allows users to configure a workflow for both events using the CIFuzz action.
=> [Infra] CIFuzz - commit and pull request hook functionality

projects/binutils/fuzz_disassemble.c
Compiler warnings
And undefined behavior against alignment
Credits to @amodra
=> Fix binutils fuzz target

projects/wavpack/project.yaml
Looks like a good candidate, let's see if Travis approves.
=> [wavpack] Enabe dataflow build config.

projects/janus-gateway/project.yaml
Add Lorenzo to cc'ed project owners.
=> [janus-gateway] Expand auto_css.

projects/unbound/build.sh
Inspired by https://github.com/google/oss-fuzz/pull/3318
=> [unbound] Fix the build.

projects/stb/Dockerfile, projects/stb/build.sh, projects/stb/project.yaml
[Previous PR](https://github.com/google/oss-fuzz/pull/2715), upstream PR: https://github.com/nothings/stb/pull/737
=> [stb_image] initial integration

projects/golang-protobuf/project.yaml
=> golang-protobuf: add user to auto_ccs

infra/cifuzz/actions/build_fuzzers/Dockerfile
Merged incorrectly. Fixing entrypoint.py bug.
=> [CIFuzz] Fixing entrypoint

infra/gcb/build_and_run_coverage.py, infra/gcb/build_lib.py, infra/gcb/build_project.py
Accidentally broke this in https://github.com/google/oss-fuzz/pull/3238, messed up the indentation :|
=> [infra] Fix broken batching in the corpora download helper (#3351).

projects/qt/Dockerfile
The proper fix was merged upstream.
=> [qt] Remove temporary compile fix

projects/binutils/fuzz_disassemble.c
Should fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=20558
which is a bug in the target, not the project...
=> Fixes target for binutils project

projects/stb/project.yaml
https://github.com/nothings/stb/pull/737#issuecomment-583732733
=> [stb] Change primary contact to a gmail address

projects/binutils/fuzz_disassemble.c
=> Revert "Fix overflow in binutils fuzz target"

infra/gcb/build_and_run_coverage.py, infra/gcb/build_lib.py, infra/gcb/build_project.py
Draft for now, I'll probably move the curl step into a helper function (to avoid duplication with the coverage job).
=> [infra] Upload latest.version metadata file for most recent build.

projects/qt/Dockerfile, projects/qt/build.sh
Don't change the names of resulting
executables to keep track of open issues.
=> [qt] Change pro-file names to lower case

projects/mupdf/project.yaml
We have a new member with a Google Account that wants access to the OSS-Fuzz bug list for mupdf.
=> [mupdf] Add @julians to auto_ccs

infra/cifuzz/fuzz_target.py
Quick fix to a logging bug that I noticed.
=> [CIFuzz] log bug fix

projects/solidity/build.sh
I am not sure https://github.com/google/oss-fuzz/issues/3370#issuecomment-584893074 is having the desired effect.
Here we force a seed corpus update with every build
=> solidity: Update seed corpus

projects/jbig2dec/jbig2_fuzzer.cc
This custom allocator limits the memory usage to the limit used by oss-fuzz. If the memory usage exceeds this limit, then jbig2dec should error out. If jbig2dec end up hitting the oss-fuzz memory limit, then jbig2dec has a genuine bug.
=> [jbig2dec] Fixes for bugs in the custom allocator

docs/getting-started/continuous_integration.md, infra/cifuzz/example_main.yml
Small change to example file to reflect the current action state.
=> [CIFuzz] Fix example_main.yml

projects/qt/Dockerfile
=> [qt] Remove cherry-picking of renaming files

projects/envoy/project.yaml
=> [envoy] Add skerner@ to Envoy project

projects/harfbuzz/build.sh, projects/harfbuzz/hb-draw-fuzzer.options
https://github.com/harfbuzz/harfbuzz/pull/2192 for more info
=> [harfbuzz] Setup a new target, hb-draw-fuzzer.

projects/arrow/Dockerfile
This will allow us to enhance the seed corpuses.
=> [Arrow] Also checkout git submodules

projects/ecc-diff-fuzzer/Dockerfile, projects/ecc-diff-fuzzer/build.sh
As fuzzer is blocked by crytpopp bugs for now
=> Adds a target to ecc diff fuzzer without cryptopp

projects/wuffs/Dockerfile
This commit is the first half of a multi-repository change. The second
half will touch https://github.com/google/wuffs/tree/master/fuzz/c/std
=> [wuffs] Add more seed corpora

infra/cifuzz/actions/build_fuzzers/build_fuzzers_entrypoint.py, infra/cifuzz/cifuzz.py, infra/cifuzz/cifuzz_test.py, infra/helper.py
Checks that the fuzzer build was a success in the build action.
=> [CIFuzz] Check fuzzers

infra/base-images/base-runner/reproduce, infra/cifuzz/fuzz_target.py
This patch should fix the reproduce bug that has been occurring.
=> [CIFuzz] Reproduce bug fix

infra/cifuzz/actions/build_fuzzers/build_fuzzers_entrypoint.py, infra/cifuzz/actions/run_fuzzers/run_fuzzers_entrypoint.py
Prevents crash from surfacing when dry run mode is enabled and check fuzzers fails.
=> [CIFuzz] Adding dry_run mode to check_build

projects/esp-v2/Dockerfile, projects/esp-v2/build.sh, projects/esp-v2/project.yaml
Copy most configs from envoy
Signed-off-by: Teju Nareddy <nareddyt@google.com>
=> Add project: ESPv2

projects/qt/build.sh
The first fuzzer to follow the new naming scheme.
=> [qt] Add fuzzer for QCborValue

projects/gnupg/Dockerfile, projects/gnupg/build.sh, projects/gnupg/fuzz_decrypt.c, projects/gnupg/fuzz_import.c, projects/gnupg/fuzz_list.c, projects/gnupg/fuzz_verify.c
Should fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=19806
=> [gnupg] Adds sqlite as gnupg dependency

projects/libspng/Dockerfile, projects/libspng/project.yaml
CIFuzz integration is failing with the old mirror.
=> [libspng] Update repository URL

projects/quickjs/Dockerfile, projects/quickjs/build.sh, projects/quickjs/fuzz_compile.c, projects/quickjs/fuzz_eval.c, projects/quickjs/fuzz_regexp.c, projects/quickjs/project.yaml
As I have been using it with eco-differential-fuzzer
=> Adds project quickjs

projects/xz/build.sh
As suggested in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=20619#c8
=> [xz] Fix fuzzing build.

projects/libfido2/Dockerfile, projects/libfido2/build.sh
Fixes fuzzing build failure #21144
=> [libfido2] Corpus seed moved outside of repo, update build.sh.

infra/helper.py
When debugging various issues, I found it handy to be able to have also sources inside of the container, similarly as we can do local builds of fuzzers to verify the bug is fixed, to get reasonable backtraces and sources for gdb to step through the code.
=> helper: Add possibility to pass source directory to gdb/shell commands to ease local debugging

infra/gcb/build_and_run_coverage.py, infra/gcb/build_project.py
Should've done this in https://github.com/google/oss-fuzz/pull/3477. Good news is that nothing failed, the coverage job was just skipped for pretty much all projects.
=> [infra] Change language attribute from "cpp" to "c++" in build scripts.

infra/cifuzz/cifuzz.py
Fixing json decode error with affected fuzzer functionality.
=> [CIFuzz] Affected fuzzer fix

projects/libavif/Dockerfile
=> [libavif] Switch to nasm 2.14 as dav1d 0.6.0 requires it

infra/cifuzz/cifuzz.py, infra/cifuzz/cifuzz_test.py
=> Reland of [CIFuzz] Affected fuzzers

docs/getting-started/continuous_integration.md
Just fixing a few spelling mistakes and added some features to the description.
=> [CIFuzz] Documentation update

infra/base-images/base-builder/Dockerfile, projects/binutils/project.yaml, projects/cjson/project.yaml, projects/jbig2dec/project.yaml, projects/lcms/project.yaml, projects/libfdk-aac/project.yaml, projects/libidn2/project.yaml, projects/libldac/project.yaml, projects/libspectre/project.yaml, projects/libteken/build.sh, projects/libteken/project.yaml, projects/nanopb/project.yaml, projects/ndpi/project.yaml, projects/nghttp2/project.yaml, projects/opus/project.yaml, projects/qcms/project.yaml, projects/qubes-os/project.yaml, projects/speex/project.yaml, projects/stb/project.yaml, projects/tidy-html5/project.yaml, projects/tremor/project.yaml, projects/unicorn/project.yaml, projects/usrsctp/project.yaml, projects/yajl-ruby/project.yaml
Also enabled MSan for a few cases where seemed appropriate.
Tested all these on GCB, all passed bad build check and produced valid builds with dataflow traces.
Travis will probably fail to build and test that many projects at once, should be fine to skip.
=> Enable dataflow build config for 22 more projects (#1632).

projects/qt/Dockerfile
=> [qt] Remove cherry-picking of ssl fuzz target

projects/binutils/fuzz_bfd.c
=> Use mkstemp in binutils fuzz target

projects/poppler/Dockerfile, projects/poppler/build.sh
There's quite some code hidden behind
#ifdef USE_CMS
so better to fuzz that code too
=> Build lcms2 for poppler

projects/qemu/project.yaml
Hello,
We added fuzzing support to QEMU along with some virtual device fuzzers. Recently, our changes have been merged, and we would love to integrate them into OSS-Fuzz. 
I am the maintainer for device fuzzing in QEMU and have worked closely with the folks in the auto_ccs to add this support. Let me know if I can provide any additional info.
Thanks
-Alex
=> Add QEMU Project

projects/clickhouse/project.yaml
It'll be nice to implement and continuously run fuzzing for some input parsers.
=> Propose ClickHouse to oss-fuzz

infra/helper.py, infra/utils.py, infra/utils_test.py
Changing the helper variable OSSFUZZ_DIR name to OSS_FUZZ_DIR as per request in #3516.
=> [Infra] Change OSSFUZZ _DIR to OSS_FUZZ_DIR

projects/quickjs/fuzz_compile.c
Follows #3540 to fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=21396
=> Fix behavior in quickjs fuzz target

projects/graphicsmagick/Dockerfile, projects/imagemagick/Dockerfile
=> [imagemagick+graphicsmagick] Install po4a, which is now needed by xz

projects/suricata/project.yaml
With emails linked to google accounts cc @victorjulien
=> Adds people to suricta project

projects/qubes-os/Dockerfile, projects/qubes-os/build.sh, projects/qubes-os/project.yaml
Qrexec [1] is a secure communication channel between virtual
machines in Qubes OS. We have fuzzers for some parts of its message
parsing code [2].
[1] https://www.qubes-os.org/doc/qrexec/
[2] https://github.com/QubesOS/qubes-core-qrexec/tree/master/fuzz
=> qubes-os: add fuzzers, update contact emails

projects/augeas/Dockerfile, projects/augeas/augeas_fa_fuzzer.cc, projects/augeas/build.sh, projects/augeas/project.yaml
Added a new fuzzer for the Augeas project.
=> New fuzzer for Augeas

projects/quickjs/project.yaml
Asked by Fabrice Bellard to have a mail address with a google account to access the reports
=> Change mail address for QuickJS project

projects/qt/Dockerfile, projects/qt/build.sh
=> [qt] Use dictionaires and testcases from AFL's repo

infra/utils.py, infra/utils_test.py
Removing useless os.walk from utils.py.
=> Remove walk from utils.py

projects/xpdf/Dockerfile, projects/xpdf/build.sh, projects/xpdf/fuzz_zxdoc.cc, projects/xpdf/project.yaml
I added the xpdf project, which is a pdf viewer that has been around for around 25 years and is actively maintained. Another project in OSS-Fuzz "Poppler" originated out of xpdf.
I have talked to Derek Noonburg who is the maintainer of the project and he is happy to have it integrated and will fix the bugs that are found.
=> Added xpdf project.

projects/pcl/project.yaml
Maintainer of PCL here. Moving ahead with [the issue](https://github.com/PointCloudLibrary/pcl/issues/3850) as reported on our bug-tracker and [this page](https://google.github.io/oss-fuzz/getting-started/accepting-new-projects/)
=> Adding PCL

projects/libra/build.sh
After many days banging my head on FFI issues in rust,
I hereby present a fix to the issue.
Note that I've got some help, and I'm not sure I understand everything here.
But this is my understanding of what was not working, and how we fixed it.
The **problem** is that on Ubuntu 16 with llvm/clang 10,
we were **statically linking libc++** in [rocksdb][1]:
```rust
let stdlib = if tool.is_like_gnu() {
"libstdc++.a"
} else if tool.is_like_clang() {
"libc++.a"
} else {
// Don't link to c++ statically on windows.
return;
};
// ...
// remove lib prefix and .a postfix.
println!(
"cargo:rustc-link-lib=static={}",
&stdlib[3..stdlib.len() - 2]
);
```
This means that during building, when we reach building of rocksdb,
we import a number of symbols from libc++ (like [__muloti4][2])
that end up in the …
=> [libra] Fix building failure

projects/grok/Dockerfile, projects/grok/build.sh, projects/grok/project.yaml
@Dor1s I put your two commits together and got the build working.
=> grok: add dataflow support

projects/jsoncons/Dockerfile, projects/jsoncons/build.sh, projects/jsoncons/project.yaml
I added the jsoncons json library. Am waiting for the accept by the jsoncons maintainters here https://github.com/danielaparker/jsoncons/pull/219 and following this I will update the email.
=> Added jsoncons project. 

infra/gcb/wait_for_build.py
=> [infra] Add build retry logic inside wait_for_build.py (#419).

projects/jsoncons/build.sh
Added two more fuzzers that have all been merged upstream.
=> Added more fuzzers for jsoncons.

projects/jsoncons/project.yaml
Changed the primary contact address as request by the maintainers https://github.com/danielaparker/jsoncons/pull/221#issuecomment-610964397
=> Update project.yaml for jsoncons

projects/qt/Dockerfile
We use the minimal plugin instead.
=> [qt] Don't install xcb

projects/jsoncons/build.sh
Added three more fuzzers to jsoncons
=> Three more fuzzers to jsoncons

projects/suricata/build.sh
=> Adds more asserts to project suricata build

infra/base-images/base-builder/Dockerfile
See https://github.com/mdempsky/go114-fuzz-build
=> Add native go fuzzing module go114-fuzz-build to builder image

projects/libcbor/project.yaml
//cc @PJK
fixes https://github.com/google/oss-fuzz/issues/3613
=> [libcbor] Disable dataflow config.

projects/simdjson/Dockerfile, projects/simdjson/project.yaml
simdjson has become a github organization and changed address
=> [simdjson] change of upstream address

infra/bisector.py, infra/build_specified_commit.py, infra/build_specified_commit_test.py, infra/helper.py, infra/repo_manager.py
- Copy /src from host instead of checking out repo on host. This fixes
issues with dependencies in the main repo.
- Add some more logging.
=> Bisector fixes.

projects/pigweed/Dockerfile, projects/pigweed/build.sh, projects/pigweed/extract_pw_fuzzers.py, projects/pigweed/filter_cipd.py, projects/pigweed/project.yaml
- Adds Pigweed to projects
- Builds using hermetic GN/Ninja
- Modified upstream build to override defaults with env vars
- Uses Python script to locate fuzzers from GN metadat
=> Add Pigweed project

projects/http-parser/Dockerfile, projects/http-parser/build.sh, projects/http-parser/project.yaml
Fuzzer is merged into upstream - CF: https://github.com/nodejs/http-parser/pull/506
=> Initial integration of http-parser of nodejs.

infra/bisector.py, infra/repo_manager.py, infra/repo_manager_test.py
=> Allow bisecting with no old commit.

projects/fluent-bit/Dockerfile, projects/fluent-bit/build.sh, projects/fluent-bit/project.yaml
Added an initial set up for fluent-bit. Waiting for maintainers to accept and give an email (https://github.com/fluent/fluent-bit/pull/2090), then I will update here.
=> Added initial set up for fluent-bit.

projects/miniz/project.yaml
This is a work in progress but I figured it should be announced ahead of time.
=> miniz integration

projects/myanmar-tools/Dockerfile
=> Speculative fix for myanmar-tools CI breakage

projects/libarchive/Dockerfile, projects/libarchive/build.sh, projects/libarchive/project.yaml
=> Added a seed corpus to libarchive fuzzer

projects/gstreamer/Dockerfile
- update glib built to 2.64.2
- point to gitlab.fd.o
=> [gstreamer] update build for meson and autotool removal

projects/libarchive/build.sh
A suggestion to fix the broken build of Libarchive.
I am not able to reproduce the broken build, so this PR is merely a try.
=> [Libarchive] Suggested fix for broken build

projects/janet/Dockerfile, projects/janet/build.sh, projects/janet/project.yaml
Link to target project: https://github.com/janet-lang/janet
=> Added the Janet project

projects/cryptofuzz/build.sh
Apparently building with --disable-asm only applies to its bignum library and not to the crypto code. This has lead to ClusterFuzz finding some false positives. libgcrypt's assembly apparently can not be turned off completely, so I'm excluding libgcrypt from msan builds.
=> [cryptofuzz] Don't build libgcrypt with MemorySanitizer

projects/tpm2-tss/project.yaml
Bill (@williamcroberts) is a maintainer of the TSS repo, adding him to the `auto_cc` list so he has access.
=> projects: tpm2-tss: Add Bill to auto_cc

projects/pcapplusplus/project.yaml
Reverts google/oss-fuzz#3695.
Misclicked merge.
=> Revert "Initial integration for PcapPlusPlus"

projects/pcapplusplus/project.yaml
Accidentally merged this before, recreating PR to assess inclusion in OSS-Fuzz.
=> Initial integration for PcapPlusPlus

projects/leptonica/Dockerfile, projects/leptonica/build.sh, projects/leptonica/pixa_recog_fuzzer.cc
1: Added fuzzer for recogTrainFromBoot()
2: Added seed_corpus to this new fuzzer
=> [Leptonica] Added fuzzer with seed corpus

infra/build_specified_commit.py
Some builds won't work if there are remaining artifacts in /src.
Also use rsync instead of cp, and fix a bug from last commit.
=> bisector: Re-copy /src in between runs.

projects/libssh/build.sh
Tested locally with helpers.
Adding Andreas for reference @cryptomilk 
Can be merged as it is. Changes and corpus files will be landing in libssh repository after cleanup (I will cross-link it as I will have the PR numbers).
=> libssh: Build all fuzzers, do build in WORK directory and prepare for corpus inclusion

docs/getting-started/continuous_integration.md, infra/cifuzz/example_main.yml
Closes https://github.com/google/oss-fuzz/issues/3711
=> cifuzz: upload artifacts only when the "run fuzzers" step fails

projects/leptonica/project.yaml
By agreement with the author.
@timothy-king should have been informed about this.
=> [Leptonica] Update to auto-cc list

projects/wuffs/Dockerfile
Add more json corpus, taken from https://github.com/minio/simdjson-fuzz (contains 8024 json seeds)
=> [wuffs] Add more json corpus

infra/bisector.py, infra/helper.py, infra/utils.py
Return codes are not reliable.
=> Add a better check for crash during bisection.

infra/bisector.py
Adopt a similar start/end marker approach to CF.
=> bisector: Properly detect MSan issues as well.

projects/wuffs/build.sh
=> [wuffs] Skip dupe files when building seed corpus

projects/gopacket/Dockerfile, projects/gopacket/build.sh, projects/gopacket/project.yaml
Replaces #3110 now that fuzz target got merged in upstream repository 
=> Adds project gopacket

projects/pcapplusplus/Dockerfile, projects/pcapplusplus/build.sh, projects/pcapplusplus/default.options, projects/pcapplusplus/project.yaml
Final integration for PcapPlusPlus
Changes required on the project have already been [merged](https://github.com/seladb/PcapPlusPlus/pull/422)
=> Full integration for PcapPlusPlus

projects/haproxy/project.yaml
In agreement with maintainers of the project, this PR updates the email addresses in project.yaml.
@TimWolla please confirm the changes.
=> [haproxy] Updated contacts in project.yaml

projects/libtasn1/project.yaml
Add another two maintainers to CC
=> [libtasn1] Add maintainers to CC

projects/fastjson/Dockerfile, projects/fastjson/build.sh, projects/fastjson/project.yaml
Resubmitting project as requested in https://github.com/google/oss-fuzz/pull/3772
=> [fastjson] Resubmitted for initial integration

projects/mysql-server/targets/CMakeLists.txt
Should fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=21922
=> Fix libraries needed for mysql fuzz targets

projects/envoy/project.yaml
=> [envoy] Add Envoy security team member to auto_ccs

projects/rdkit/Dockerfile, projects/rdkit/build.sh, projects/rdkit/project.yaml
Integrates rdkit into oss-fuzz.
This is currently waiting for https://github.com/rdkit/rdkit/pull/3128 getting merged.
=> Rdkit oss fuzz

projects/vitess/Dockerfile, projects/vitess/build.sh, projects/vitess/project.yaml
This PR adds initial integration of [Vitess](https://github.com/vitessio/vitess).
Vitess is a database clustering system that has been a key component of YouTubes infrastructure since 2011 while [many other large organizations](https://github.com/vitessio/vitess/blob/master/ADOPTERS.md) have adopted Vitess as well.
@systay is the primary contact, while @sougou is in the loop of the integration as well.
We are currently waiting for the fuzzer to be merged upstream.
=> [vitess] Initial integration
