google/oss-fuzz

- projects/graphicsfuzz-spirv/Dockerfile
- projects/graphicsfuzz-spirv/build.sh
- projects/graphicsfuzz-spirv/project.yaml
Reenable GraphicsFuzz
Also, revert f98bd5289a4cba30149baebaa75127bd0ff9b565.
We can't use the bundled Java and GraphicsFuzz because ClusterFuzz doesn't tell a blackbox fuzzer what is the path to the target during the input generation phase. Instead I will bundle Java/GraphicsFuzz with my fuzzer script and use those.
> Reenable GraphicsFuzz

- projects/php/build.sh
- projects/php/project.yaml
And disable the PCRE JIT, which is incompatible with the memory sanitizer.
> [php] Enable memory sanitizer

- projects/oak/Dockerfile
This change fixed Bazel version (1.1.0) used in Docker by Project-Oak.
Orginated from https://github.com/google/oss-fuzz/issues/3093#issuecomment-564752335
> Add a fixed Bazel version for Project-Oak

- projects/grpc/Dockerfile
> [grpc] Workaround bazel issue

- projects/nanopb/Dockerfile
- projects/nanopb/build.sh
- projects/nanopb/project.yaml
Nanopb is a protobuf encoder/decoder library designed for embedded systems, which is used in e.g. many Android phones. I was invited to participate in OSSFuzz here: https://github.com/nanopb/nanopb/issues/409
This commit adds basic fuzzing that achieves ~85% coverage on decoder side. I've tested that the fuzzer works with address, memory and undefined sanitizers.
In the future I'll expand the fuzz target in nanopb repository to cover also `syntax="proto3"` and also other corner cases that are not getting covered currently. I'll also see about adding extra fuzz targets to cover different `#ifdef` compilation options, but I'll make a separate pull request adding those later.
> Added nanopb project

- projects/mysql-server/build.sh
This should fix 
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=19490
But I do not understand why it worked in the first place...
This build change enables macro `SUPPRESS_UBSAN` which avoids triggering known bugs
> Project mysql with ubsan build

- projects/mtail/Dockerfile
- projects/mtail/build.sh
- projects/mtail/project.yaml
This project doesn't go-get well so git clone it, then set up the GOPATH, and                                                                                                                                        
as go-fuzz-build doesn't like modules (which some of the dependencies are)                                                                                                                                           
vendor them and then build the fuzzer and dictionary.
> [mtail] Fuzz the github.com/google/mtail project.

- projects/libzip/Dockerfile
This reenables lzma support which was disabled due to a linking issue, ~~it also installs bz2.~~
edit: it can't link libbz2, but at least it can link against lzma again.
> [libzip] enable lzma support

- projects/boost/Dockerfile
- projects/boost/boost_regex_fuzzer.cc
- projects/boost/build.sh
- projects/boost/project.yaml
This PR
- changes the logic of applying a regular expression against itself (which is non intuitive) to a new scheme where the regular expression and text to be matched are separated by a white space
- adds post conditions as assertions that must hold when text fully matches regular expression
P.S. Boost's build was broken. The second commit in this PR fixes this.
> boost: Assert post conditions for match

- projects/golang-protobuf/build.sh
Only build fuzzers under internal/fuzz. Assume a fuzzer is a directory
with a corpus/ subdirectory.
Include the contents of corpus/ as the seed corpus.
> golang-protobuf: include seed corpus(es)

- projects/mysql-server/targets/fuzz_real_query.cc
Should fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=19586
I did not know about this kind of bug... I may have written more in the past...
http://pzemtsov.github.io/2016/11/06/bug-story-alignment-on-x86.html
> Fix misalign in mysql fuzz target

- projects/envoy/Dockerfile
Fixes Envoy build failure by pinning bazel verison to the version specified in Envoy's `.bazelversion`. 
> envoy: pin bazel version by using bazelisk

- infra/base-images/base-builder/precompile_honggfuzz
> Run apt-get autoremove after removing honggfuzz dependencies.

- projects/qt/Dockerfile
- projects/qt/build.sh
- projects/qt/project.yaml
This builds Qt and a first fuzz target for it. Qt's sources contain further fuzz targets already, but I'd like to start with one to see if and how this all works. If it does, I'll add the others one by one.
Improvements I'd like to do soon, i.e. not in this change:
- further fuzz targets
- dictionaries
- add proper parameters to Qt's configure instead of editing the mkspec files in build.sh
In case I made any mistakes, please let me know and I'll happily fix them.
A healthy, happy new year to all of you. :-)
> Add the first fuzz target for Qt

- projects/pillow/Dockerfile
- projects/pillow/build.sh
- projects/pillow/project.yaml
Placeholder, do not merge yet.. It's been finding a whole bunch of bugs locally that I am currently reporting. Publishing the fuzzer and corpus right now would divulge these bugs ahead of the release, so we will need to wait for fixes first.
> [pillow] Pillow fuzzers

- projects/pillow/Dockerfile
- projects/pillow/build.sh
- projects/pillow/project.yaml
Disable AFL because the build log at https://oss-fuzz-build-logs.storage.googleapis.com/index.html  says it hangs
Add corpus
Update CPython version
Remove redundant code
The seed corpus finds a Pillow bug (https://github.com/python-pillow/Pillow/issues/4329) so maybe that needs to be fixed first.
> [pillow] Fixes

- projects/osquery/Dockerfile
- projects/osquery/build.sh
This changes the osquery build to use the `oss-fuzz`-provided LLVM/clang toolchain. Previously the build was using osquery's custom toolchain.
This should fix coverage builds.
Fixes #3081.
> [osquery] Use platform toolchain and fix coverage builds

- projects/openvswitch/build.sh
Attempt to fix build failure because fuzzing binary depended on libunwind which is no longer available in fuzzing machines.
I suspect `libunwind` is necessary for some debugging feature that this PR disables.
Depends on https://github.com/google/oss-fuzz/issues/3165
> ovs: Disable debug features in fuzzing build.

- projects/wget/build.sh
- projects/wget2/build.sh
Both projects build GnuTLS from git master which now has a default dependency on libev. This is only used by a single test in gnutls, which we don't run anyways.
This PR adds a gnutls configure option to not fail in this case.
> Fix build issue for wget & wget2 

- projects/qt/build.sh
Qt: Link statically
This will generate much larger but also faster fuzz targets. It also allows running the fuzz target from outside the docker image, see https://github.com/google/oss-fuzz/pull/3171#issuecomment-570668436
> Link statically

- projects/gnutls/build.sh
The full test suite is not necessary for this build and this
disablement avoids any dependencies required by it.
> [gnutls] disable the full test suite

- infra/base-images/base-runner/Dockerfile
- infra/base-images/base-runner/bad_build_check
- infra/base-images/base-runner/test_all
- infra/base-images/base-runner/test_one
- infra/helper.py
Loading dynamic libraries/files or anything else from /out breaks on CF. It doesn't break in the "runner" because as we've already seen the runner is not used on CF.
Rather than hack OSS-Fuzz's fake runner to be more like ClusterFuzz's real runner I'm fixing the issue closer to where it is actually causing an issue, bad_build_check.
Long term we should get rid of the runner and replace it with CF's image rather than deal with these issues again and again.
> Make bad_build_check more likely to catch hardcoding /out

- projects/tpm2-tss/build.sh
The new API introduced in https://github.com/tpm2-software/tpm2-tss/commit/6da95b04b4f22284d5b40cc03fa19e6dc514339f pulls in additional build dependencies like json-c and is currently not part of the fuzz testing, so disable it.
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=19639
> [tpm2-tss] disable building the Feature API (FAPI)

- projects/knot-dns/Dockerfile
The knot-dns fuzz target build is broken due to gnutls (a dependency) requiring libev4. This adds the associated packages to the Dockerfile.
/cc @salzmdan
> [knot-dns] add libev4 dep for gnutls

- infra/base-images/base-runner/Dockerfile
- infra/base-images/base-runner/test_all
- infra/base-images/base-runner/test_one
- infra/helper.py
This reverts commit 689c3f4b65b77ca27e882de828b4e741121238fc.
> Reland Make bad_build_check more likely to catch hardcoding /out (#3180)

- infra/base-images/base-runner/run_fuzzer
- infra/base-images/base-runner/test_all
- infra/base-images/base-runner/test_one
Set `$OUT` to the `not-out` directory before running `run_fuzzer` so that `afl-fuzz` and `honggfuzz` can be used by `run_fuzzer`.
Also unset the `$OUT` environment variable in `run_fuzzer` just in case any fuzz targets use it at run time.
Fixes #3194
> Fix issue running AFL targets with run_fuzzer

- projects/proxygen/Dockerfile
This should fix the build since libunwind was removed from the base image in https://github.com/google/oss-fuzz/pull/3031/files and we need it in this case.
I have not tested this yet, and will wait on Travis to confirm that this works.
> [proxygen] Install libunwind8 in Dockerfile

- projects/binutils/build.sh
This should fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=19679
Is this the right way to do it ? cf https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html#silencing-unsigned-integer-overflow
cc @amodra
> Silence unsigned integer overflows in binutils project

- infra/gcb/build_and_run_coverage.py
- infra/gcb/build_project.py
Haven't tested yet, will do before landing.
Inspired by https://github.com/GoogleCloudPlatform/cloud-builders/issues/253, as it seems like there doesn't exist a better mechanism for this.
> [infra] Print additional information for build/coverage failures on GCB (#3104).

- infra/gcb/build_and_run_coverage.py
- infra/gcb/build_project.py
Minor fixes to ensure the faulting command (`false` or `exit 1`) does not execute in a successful build.
> [infra] Add parens to ensure correct execution order (#3104).

- projects/binutils/build.sh
Fixes #3178 which meant to silence unsigned integer overflow, not enable them.
cf https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=19993
So, there seems to be a bug with https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=19679
This was first an undefined shift which got fixed but the bug remained open as en unsigned integer overflow with the same stack trace.
Should not the bug have been closed ? And a new one with a new title created instead ?
> Silence unsigned overflow

- projects/harfbuzz/build.sh
Not very different from ones we have already, for the sake of completeness
Wish we could do some **/*.{otf,otc,ttf,ttc,dfont} instead here.
> [harfbuzz] Add another location of fonts

- infra/base-images/base-builder/compile_dataflow
- infra/base-images/base-runner/bad_build_check
This was changed in https://github.com/llvm/llvm-project/commit/679669a77e5bbd7451f4c482ec1996b0649f65d0, and besides the speedup, it seems like tracing didn't work on OSS-Fuzz since then. Maybe it stopped working some time later, but it definitely doesn't work right now.
Also added a bad build check for the current existing interface.
> [infra] Fix dataflow engine compilation for a runtime speed up (#1632).

- projects/unbound/Dockerfile
- projects/unbound/build.sh
- projects/unbound/fuzz_1.c
- projects/unbound/fuzz_2.c
- projects/unbound/fuzz_3.c
- projects/unbound/fuzz_4.c
We at X41 D-Sec published several fuzzers as part of the OSTIF-sponsored audit of Unbound (see https://ostif.org/our-audit-of-unbound-dns-by-x41-d-sec-full-results/).
This PR includes the published fuzzers in oss-fuzz.
Comments?
> [unbound] add fuzzers written for OSTIF audit

- projects/qt/Dockerfile
- projects/qt/build.sh
- dev will change the build system to cmake. When I stay on 5.15,
I can choose when to port the fuzzing.
- Submodules are currently outdated in dev. On 5.15, changes in
stable branch will be tested earlier and additions for fuzzing
can be used earlier.
> Qt: Test on branch 5.15 instead of dev

- projects/arrow/Dockerfile
- projects/arrow/build.sh
- projects/arrow/project.yaml
Arrow is both an efficient in-memory format for tabular data, an IPC format with zero-copy capabilities, and a set of interoperable language implementations (~10 languages currently: C++, Python, Java, Rust, Go...).
This submission is for fuzzing the Arrow C++ IPC reader. If accepted, we plan to add other fuzz targets, for example for reading Parquet files.
> Submit Apache Arrow for inclusion

- infra/gcb/build_and_run_coverage.py
- infra/gcb/build_project.py
This also includes some formatting changes. Sorry I didn't realize that these scripts were not formatted. I can separate formatting and the actual change, but that would have to be done manually, as I don't have a non-formatted commit even locally.
> [infra] Print exact reproduction commands in build failures (#3104).

- projects/xz/build.sh
Reverts google/oss-fuzz#3252.
This should be fixed upstream now.
> Revert "[xz] Apply a harmless local patch to migrate to $LIB_FUZZING_ENGINE."

- infra/base-images/base-runner/dataflow_tracer.py
Some targets may not process all the corpus in the given time. Prioritizing shorter inputs lets us maximize the number of inputs traced.
> [infra] Prioritize short files when collecting dataflow traces (#1632).

- projects/json-c/project.yaml
Should work based on https://pantheon.corp.google.com/logs/viewer?resource=build%2Fbuild_id%2F3fc8371d-951a-4003-9ce5-97d4adaf449c&project=oss-fuzz&minLogLevel=0&expandAll=false&timestamp=2020-01-21T22:54:26.943000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeEnd=2020-01-21T22:54:25.085Z&interval=PT1H&dateRangeUnbound=backwardInTime&scrollTimestamp=2020-01-21T18:50:28.370948047Z, double checking with Travis.
> [json-c] enable dataflow config (#1632).

- projects/cmark/project.yaml
Should work based on https://pantheon.corp.google.com/logs/viewer?resource=build%2Fbuild_id%2Ffd035ed9-bbd9-4371-98ec-20d651567cee&project=oss-fuzz&minLogLevel=0&expandAll=false&timestamp=2020-01-21T22:47:00.300000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeEnd=2020-01-21T22:46:58.339Z&interval=PT1H&dateRangeUnbound=backwardInTime&scrollTimestamp=2020-01-21T19:28:33.870235967Z, but letting Travins double check.
> [cmark] Enable dataflow config (#1632).

- projects/pcre2/project.yaml
Tested with https://pantheon.corp.google.com/logs/viewer?resource=build%2Fbuild_id%2F9ca139cf-c469-4916-b304-d17859ebc392&project=oss-fuzz&minLogLevel=0&expandAll=false&timestamp=2020-01-21T23:36:36.516000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeEnd=2020-01-21T22:57:17.770Z&interval=PT1H&dateRangeUnbound=backwardInTime&scrollTimestamp=2020-01-21T19:09:03.422310359Z, but letting Travis to verify.
> [pcre2] enable dataflow config (#1632).

- projects/harfbuzz/project.yaml
Should work based on https://pantheon.corp.google.com/logs/viewer?resource=build%2Fbuild_id%2F3312be9f-7e2e-45c4-9544-eb432eba8c2e&project=oss-fuzz&minLogLevel=0&expandAll=false&timestamp=2020-01-21T22:51:43.343000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeEnd=2020-01-21T22:51:41.725Z&interval=PT1H&dateRangeUnbound=backwardInTime&scrollTimestamp=2020-01-21T21:13:26.578865217Z, but double checking with Travis.
> [harfbuzz] enable dataflow config (#1632).

- projects/capstone/project.yaml
Should work based on https://pantheon.corp.google.com/logs/viewer?resource=build%2Fbuild_id%2Fb106a717-7725-44c6-81a5-e196300b9401&project=oss-fuzz&minLogLevel=0&expandAll=false&timestamp=2020-01-21T22:41:43.490000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeEnd=2020-01-21T22:41:40.447Z&interval=PT1H&dateRangeUnbound=backwardInTime&scrollTimestamp=2020-01-21T19:58:48.579291555Z, but uploading as an explicit PR to let Travis double check me.
> [capstone] enable dataflow config (#1632).

- projects/mupdf/project.yaml
Tested with https://pantheon.corp.google.com/logs/viewer?resource=build%2Fbuild_id%2F9e804198-492a-4762-8551-928c66a8b4e1&project=oss-fuzz&minLogLevel=0&expandAll=false&timestamp=2020-01-21T23:45:43.424000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeEnd=2020-01-21T23:43:14.050Z&interval=PT1H&dateRangeUnbound=backwardInTime&scrollTimestamp=2020-01-21T20:24:16.755968968Z
> [mupdf] enable dataflow config (#1632).

- projects/wolfssl/project.yaml
Tested with https://pantheon.corp.google.com/logs/viewer?resource=build%2Fbuild_id%2Fe577cd61-fcc2-42bd-90ec-b199371d2682&project=oss-fuzz&minLogLevel=0&expandAll=false&timestamp=2020-01-21T23:46:39.985000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeEnd=2020-01-21T23:43:32.057Z&interval=PT1H&dateRangeUnbound=backwardInTime&scrollTimestamp=2020-01-21T19:05:52.366118139Z
> [wolfssl] enable dataflow config (#1632).

- projects/wavpack/project.yaml
Note that we are excluding signed-integer-overflow in our build file, but everything else is good.
> wavpack: add undefined behavior sanitizer

- projects/ghostscript/Dockerfile
- projects/ghostscript/build.sh
Looks like we were getting system freetype libraries on some systems.  Change our dependency to an internally compiled version synced from upstream.
> Switch Ghostscript to upstream freetype

- projects/rapidjson/project.yaml
Detected this while working on #3280.
> [rapidjson] Fix the indentation in project.yaml.

- projects/tor/build.sh
Libevent's build is failing because it can't find openssl.  We could
try to fix this, but instead let's disable it: Tor doesn't actually
use Libvent's openssl support.
> [Tor] Build libevent with --disable-openssl

- projects/wasmtime/project.yaml
Hello,
[Bytecode Alliance](https://bytecodealliance.org/) projects are developed in the open, largely in Rust. As part of designing continuous fuzzing for Bytecode Alliance projects we are evaluating how we might integrate Rust fuzz targets with oss-fuzz. (some background: [Bytecode Alliance discussion issue](https://github.com/bytecodealliance/wasmtime/issues/611), [oss-fuzz PR for an unrelated Rust fuzz target from last year](https://github.com/google/oss-fuzz/pull/2533)).
This PR is for project acceptance for Rust fuzzing targets for [wasmtime](https://github.com/bytecodealliance/wasmtime). @fitzgen and I did some analysis and made a few modifications to Rust's [libfuzzer wrapper](http://github.com/rust-fuzz/libfuzzer) and [cargo-fuzz](https://github.com/rust-fuzz/cargo-fuzz) to …
> Acceptance for wasmtime project and Rust fuzz targets

- projects/wasmtime/Dockerfile
- projects/wasmtime/build.sh
This is an attempt to fixup the errors found on #3292. Although I'm not
certain where the error was coming from this switches the Rust
installation to being in `PATH` by default so there's no need to
`source` any scripts to get access to the Rust compiler.
cc @fitzgen, @jfoote, y'all are likely interested in this!
> Try to fix the wasmtime Rust build

- projects/proj4/Dockerfile
Previously we linked against the dynamic libtiff library, but this
didn't work when running the fuzzers.
This time, actually tested by launching
python infra/helper.py run_fuzzer $PROJECT_NAME proj_crs_to_crs_fuzzer
> [PROJ4] Build libtiff from source to create a static archive

- projects/clamav/build.sh
ClamAV's mempool feature uses mmap to improve performance for some
memory allocations. As currently implemented, on systems that support
mmap's MAP_ANONYMOUS flag, fmaps are backed by mmap'd memory.
Valgrind and ASan can't track mmap-backed memory, though, so it's more
difficult to track down fmap-related memory errors.
The changes in this commit to clamav's build script should disable mmap
usage, and hopefully allow oss-fuzz to catch more bugs.
> [ClamAV] Disable mempool at compile time

- projects/wasmtime/project.yaml
I accidentally typed the wrong TLD in the initial commit -- apologies
> [wasmtime] fix security@bytecodealliance.org alias

- projects/qt/build.sh
I only moved away the executable but not the object files, so
I still used the same object file when building the next fuzzer.
Now that all fuzzers are actually being built, this reveals a problem with setHtml.
Disabling it until I have a fix for that.
> [qt] Delete fuzzer's artifacts after building one

- projects/wasmtime/build.sh
This commit does for Rust code what the `CFLAGS` are configured to do
for C++ code, which is to enable debuginfo (but line tables only) as
well as forcing frame pointer generation to all assist in generating
stack traces.
> wasmtime: Enable debuginfo/frame pointers

- infra/cifuzz/actions/action.yml
- infra/cifuzz/actions/entrypoint.py
- infra/cifuzz/cifuzz_test.py
- infra/helper.py
- infra/repo_manager_test.py
Gives the user the option prevent the action from failing. This will not raise a red badge even if the the action detects a bug or has an error. It will help with the dogfood process.
> [CIFuzz] Prevent action from failing option 

- infra/cifuzz/fuzz_target.py
Adds seed number and length control arguments when calling running a fuzz target. These two arguments are added to optimize for time constrained fuzzing.  Detailed info about the arguments can be found here: https://llvm.org/docs/LibFuzzer.html#options
> [CIFuzz] Add seed and len control to fuzzer arguments

- projects/wavpack/project.yaml
Reverts google/oss-fuzz#3324
That was a mistake, Travis tricked me, it actually skipped the project because it follows ideal integration guidelines and doesn't even have build.sh in OSS-Fuzz repo.
> Revert "[wavpack] Enabe dataflow build config."

- infra/base-images/base-runner/coverage
- infra/gcb/build_and_run_coverage.py
Needed for https://github.com/google/oss-fuzz/pull/3306 and better analysis automation. When there is a coverage improvement reported in BigQuery stats, I'm pulling up coverage reports and try to compare them. Full JSONs would make it more advanced, as right now the best I can get is something like:
```
filename: abc.cc, coverage diff: +5 regions
```
and then I have to manually diff HTML reports for that file, which doesn't scale.
With full JSONs, coverage diff will be more granular without any manual work.
This will make coverage job slower for the affected projects, but I don't expect anything to go out of hand on the dataflow enabled projects.
> [infra] Generate full coverage JSONs for dataflow enabled targets (#1632).

- projects/wasmtime/project.yaml
Following up on internal bytecodealliance/wasmtime discussion, this removes the security@bytecodealliance.org alias from the wasmtime notification list and adds @tschneidereit.
> [wasmtime] update auto_ccs

- infra/travis/travis_build.py
Projects may not have build.sh in OSS-Fuzz, but they must have Dockerfile in order to be built and fuzzed by OSS-Fuzz. This has bitten me in https://github.com/google/oss-fuzz/pull/3327
> [infra] Travis: rely on the presence of Dockerfile to identify buildable projects.

- projects/wasmtime/Dockerfile
- projects/wasmtime/build.sh
- projects/wasmtime/default.options
This is an attempt to apply the suggestions from #3316 to the fuzzing
infrastructure for the `wasmtime` target. This will hopefully allow the
delivery of SIGSEGV and SIGILL signals to the `wasmtime` program itself.
These are expected signals when executing wasm code so we don't want the
fuzzer to treat all forms of the signal as a fatal error.
Unfortunately I'm not entirely sure how to test this locally, using the reproduction workflow this doesn't seem to have any effect, but it looks like this `*.options` file may not be picked up during the `reproduce` workflow? I figure a shot in the dark could hopefully help here and I'm trusting @Dor1s as well :)
> [wasmtime] Try fixing delivery of SIGILL/SIGSEGV to JIT

- projects/libtheora/project.yaml
Just noticed that `dataflow` sanitizer is enabled while `fuzzing_engine` is not. Let's see if it works or should be removed.
> [libtheora] Remove unused dataflow sanitizer.

- infra/base-images/base-builder/Dockerfile
- infra/build_specified_commit.py
At @jonathanmetzman request, switching the detect_repo.py script from /src to /opt.
> Switching detect_repo.py script into /opt

- projects/wasmtime/project.yaml
I had used a site-specific alias for @tschneidereit in my last commit; he is unable to login to monorail with it. This corrects to an alias that should work. Apologies for the oversight.
> [wasmtime] correct auto_ccs

- projects/binutils/fuzz_disassemble.c
Support disassembly of testcases containing more than one instruction
cc @amodra
> Improves binutils fuzz target

- projects/wasmtime/default.options
This fixes typo mistakes from #3335 where we actually want the opposite
of the current defaults, not the current set of defaults!
> [wasmtime] Fix default asan options

- projects/golang-protobuf/build.sh
Move the core of the build script into the fuzzed repo, where it's easier
for us to manage.
> golang-protobuf: use build script in protobuf repo

- infra/cifuzz/actions/build_fuzzers/Dockerfile
- infra/cifuzz/actions/build_fuzzers/action.yml
- infra/cifuzz/actions/build_fuzzers/build_fuzzers_entrypoint.py
- infra/cifuzz/actions/run_fuzzers/Dockerfile
- infra/cifuzz/actions/run_fuzzers/action.yml
- infra/cifuzz/actions/run_fuzzers/run_fuzzers_entrypoint.py
- infra/cifuzz/cifuzz-base/Dockerfile
- infra/cifuzz/cifuzz.py
- infra/cifuzz/cifuzz_test.py
- infra/cifuzz/example_main.yml
- infra/cifuzz/fuzz_target.py
Separates the current GitHub actions into two. The build_fuzzer actions will only work for OSS-Fuzz repositorys. The separation of the run_fuzzers action will allow for non-OSS-Fuzz repos to use the action. There is also an included example action.yml file to help projects configure an effective workflow.
> [CIFuzz] Separate build and run actions

- infra/base-images/base-runner/coverage
Apparently python is way to hungry on full JSONs (from relatively small fuzz targets) and our cron dies with `Exceeded soft memory limit of 2048 MB with 2712 MB after servicing 5 requests total. Consider setting a larger instance class in app.yaml.`.
OTOH it's just safer to leave the summary only stuff as-if, and any temporary extra stuff I need store separately.
> [infra] Dump full coverage JSONs separately (#1632).

- infra/presubmit.py
- projects/glib/build.sh
- projects/glib/project.yaml
In GLib master commit b220033c we changed the `libmount` option from a
`boolean` to a `feature`, which means it now takes
`enabled`/`disabled`/`auto` rather than `true`/`false`.
Signed-off-by: Philip Withnall <philip@tecnocode.co.uk>
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=20552
> glib: Fix build due to Meson option changing type

- projects/binutils/fuzz_disassemble.c
Should fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=20602 and such
`snprintf` returns the number of needed spaces in the buffer (not the number of printed ones)
> Fix overflow in binutils fuzz target

- projects/karchive/Dockerfile
Fixes https://oss-fuzz-build-logs.storage.googleapis.com/log-8701517e-ce60-406d-93d1-a0acf29a2391.txt
> karchive: xz now needs po4a, install it

- projects/mp4parse-rust/Dockerfile
- projects/mp4parse-rust/build.sh
- projects/mp4parse-rust/project.yaml
Initial integration for https://github.com/mozilla/mp4parse-rust, a pure-Rust MP4 parser used inside Firefox.
This is based on the integration work done for another Rust project that was recently included, wasmtime.
> [mp4parse-rust] Initial integration

- projects/iroha/Dockerfile
this change fixes the build after vcpkg version bump and completes the migration started in #2986
> [iroha] fix build after vcpkg migration

- infra/cifuzz/actions/run_fuzzers/run_fuzzers_entrypoint.py
- infra/cifuzz/cifuzz.py
- infra/cifuzz/example_main.yml
example_main.yml is outdated. This will make example_main.yml in sync with the current CIFuzz actions on master.
> [CIFuzz] Change 'bug_report' directory to 'artifacts'.

- projects/dav1d/Dockerfile
- projects/dav1d/bionic.list
- projects/dav1d/nasm.list
- projects/dav1d/nasm_apt.pin
> dav1d: use nasm from ubuntu eoan since dav1d needs nasm-2.14

- projects/arrow/Dockerfile
- projects/arrow/build.sh
The Parquet C++ reader is part of the Arrow project but needs to be enabled
explicitly.  This is required so that we can add a fuzz target for Parquet files.
> [arrow] Enable Parquet build

- infra/cifuzz/cifuzz_test.py
- infra/cifuzz/fuzz_target.py
- infra/cifuzz/fuzz_target_test.py
Addes functionality and tests so that CIFuzz will only report errors that can be consistently reproduced.
> [CIFuzz] Only report reproducible crashes

- projects/libra/project.yaml
Hey!
I'd like to add [libra](https://libra.org/en-US/) to oss fuzz. Here is the [project repository](https://github.com/libra/libra/).
Thanks!
> adding libra to list of projects

- projects/libspectre/Dockerfile
libspectre's fuzz target takes a long time to rebuild over a slow connection, moving these lines from the build script to the Dockerfile will cache the download + extraction step. The upstream build script has already been modified.
> [libspectre] Fetch ghostscript before building

- infra/gcb/build_and_run_coverage.py
Without this, if we re-run coverage job for a project, gsutil will create redundant subdirectory inside e.g. `logs` directory so it will look like:
```
logs/
fuzzer1.log
fuzzer2.log
logs/
fuzzer1.log
fuzzer2.log
```
and that would confuse coverage cron that iterates through the files in `fuzzer_stats` dir, for example
> [infra] Use wildcard in gsutil cp command as it lacks -T option.

- infra/gcb/build_and_run_coverage.py
- infra/gcb/build_lib.py
The workaround in https://github.com/google/oss-fuzz/pull/3396 worked for the logs and stats dirs, but didn't quite work for the HTML report dir (as it has subdirs and gsutil exhibits yet another weird behavior there).
https://console.cloud.google.com/errors/CI_aqYOjjdDauQE?time=P30D&project=clusterfuzz-external should go away after this.
> [infra] Perform "gsutil rm -rf" if we need to overwrite coverage data.

- infra/gcb/build_lib.py
Workaround for yet another specific behavior by gsutil. Apparently, it reports an error even with `-f` flag (e.g. deleting a non existent object).
Not sure if this works, testing on GCB right now.
> [infra] GCB: ignore failing "gsutil rm -rf" step.

- infra/base-images/base-runner/collect_dft
- infra/gcb/build_project.py
All 30 projects that have dataflow enabled have green builds (except xz, there is an unrelated breakage). However, over the past 5-6 days the average performance of dataflow strategy looks worse than it looked before. Trying to loose the restrictions for the traces collection (increasing everything by ~2x) in order to collect even more traces.
> [infra] Loose the limits for dataflow traces collection (#1632).

- projects/qt/build.sh
Not change any output files yet to avoid accidentally closing bug reports. When they are properly closed, it's easy to switch to the new output file names one by one.
> [qt] Make using longer names for fuzz targets possible

- projects/ghostscript/gstoraster_fuzzer.cc
The first element in the argument array to gsapi_new_instance()
is ignored since it normally is the program name. This means that
the commit introducing the "-K" argument to limit memory usage did
not have its intended effect since the "-K" argument was ignored.
Moreover, prior to that the resolution argument "-r200x200" was
being unintentionally ignored. By introducing a place holder program
name all arguments are taken into account and the reader is reminded
that the first argument is the program name.
I'm hoping this will improve the situation with ghostscript oss-fuzz issue #15650.
> [ghostscript] Add place holder program name.

- infra/repo_manager.py
- infra/repo_manager_test.py
This adds the functionality of git diff --name-only to the repo manager module. This functionality will be used for the affected fuzzer feature of CIFuzz. Associated tests have also been added.
> [Infra] Add git diff to repo manager class

- projects/ecc-diff-fuzzer/Dockerfile
- projects/ecc-diff-fuzzer/build.sh
This follows #3408 
Even if the CI was green, the build on oss-fuzz does not work 
Error logs are
```
Step #4: + source /builder/home/.cargo/env
Step #4: /src/build.sh: line 130: /builder/home/.cargo/env: No such file or directory
Step #4: ********************************************************************************
Step #4: Failed to build.
Step #4: To reproduce, run:
Step #4: python infra/helper.py build_image ecc-diff-fuzzer
Step #4: python infra/helper.py build_fuzzers --sanitizer address --engine libfuzzer --architecture x86_64 ecc-diff-fuzzer
Step #4: ********************************************************************************
```
So, I guess this is because the user is not root here but builder and `/builder/home/.cargo/env` does not exist even if `/root/.cargo/env` does …
> Right handling for rust path for ecc-diff-fuzzer

- projects/ghostscript/gstoraster_fuzzer.cc
When contributed to OSS-fuzz the Ghostscript target fuzzer was
licensed under a "BSD-style" license, referring to a LICENSE file
that actually contained an Apache 2.0 license! Recently the OSS-fuzz
project has added a presubmit check that validates the license of
each project's target fuzzer, causing the Ghostscript target fuzzer
to now fail the test. The Ghostscript target fuzzer therefore needs
to be relicensed under Apache 2.0.
This commit relicenses the existing target fuzzer code under
Apache 2.0 so that the Ghostscript target fuzzer code will pass
OSS-fuzz's presubmit checks allowing for further development.
> [ghostscript] Relicense target fuzzer under Apache 2.0 license.

- projects/libtorrent/Dockerfile
- projects/libtorrent/build.sh
This disables code in libtorrent that causes clang 10 to ICE, specifically [this issue](https://bugs.llvm.org/show_bug.cgi?id=43814). Hopefully restoring fuzzing.
> disable logging support in libtorrent, to avoid clang 10 ICE

- infra/base-images/base-builder/compile
Plan is to fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=20755
I am not sure this is the best way, but this should work.
ecc differential fuzzer now compiles and installs the different crypto libraries.
Before, it used to compile them, but not install them.
This is meant to have a simpler compilation scheme...
But then, it looks like the coverage build cannot find the installed header files for the coverage report :
```
Step #5: [0m[0;31merror: /workspace/out/coverage/usr/local/include/botan-2/botan/ec_group.h: No such file or directory
Step #5: [0m[0;31mwarning: The file '/usr/local/include/botan-2/botan/ec_group.h' isn't covered.
...
Step #5: Traceback (most recent call last):
Step #5:   File "/opt/code_coverage/coverage_utils.py", line 825, in <module>
Step #5: …
```
> Adds locally installed includes for coverage build

- projects/hunspell/Dockerfile
- projects/hunspell/build.sh
- projects/hunspell/project.yaml
I would like to add Hunspell (hunspell.github.io) to oss-fuzz
> [hunspell] Add project to oss-fuzz

- projects/cryptofuzz/Dockerfile
- projects/cryptofuzz/build.sh
Currently the coverage reports don't work for NSS: https://storage.googleapis.com/oss-fuzz-coverage/cryptofuzz/reports/20200303/linux/src/nss-nspr/nss/report.html
This PR should fix that
> [cryptofuzz] Fix NSS coverage

- projects/esp-v2/build.sh
Don't assume correlation between file name and bazel target name.
Signed-off-by: Teju Nareddy <nareddyt@google.com>
> Fix ESPv2 build

- projects/qt/build.sh
They made the build output too long. Without these
warnings, I don't need to send it to /dev/null anymore.
> [qt] Don't show warnings about deprecated API

- projects/grok/Dockerfile
- projects/grok/build.sh
- projects/grok/project.yaml
grok is a jpeg 2000 codec, one of only two actively-developed OSS jpeg 2000 toolkits, the other one being OpenJPEG.
> Add Grok JPEG 2000 toolkit to oss-fuzz

- projects/qt/build.sh
There are no open bugs for this fuzzer.
I'm aware that I will lose corpus and statistics for it.
> [qt] Move beginLayout to the new naming scheme

- projects/esp-v2/build.sh
[Example failure](https://oss-fuzz-build-logs.storage.googleapis.com/log-8eabbac0-bb8f-4f90-a840-f23efe427e0e.txt)
This only occurs on the fuzzers for some reason, not on Travis CI. Error is similar to https://github.com/bazelbuild/bazel/issues/5640.
Change spawn strategy to `sandboxed` to work around this. Not sure why it was `local` to begin with (other than a slight performance improvement).
Tested locally to ensure this spawn strategy will work.
```
python infra/helper.py build_fuzzers --sanitizer address --engine libfuzzer --architecture x86_64 esp-v2
```
Signed-off-by: Teju Nareddy <nareddyt@google.com>
> [esp-v2]: Fix broken builds by changing spawn strategy

- projects/libcacard/Dockerfile
- projects/libcacard/build.sh
- projects/libcacard/project.yaml
This finally (after #3019) adds the dockerfile and build.sh script to start fuzzing. It depends on merging the fuzzers into libcacard source tree so marking as WIP, but generally, the concept should be done (after fixing the URL to the upstream repository instead of my fork).
The ugly thing is a rebuild of NSS, which is needed for statically compiled fuzzer binary (as Ubuntu does not ship static nss libraries nor any pkg-config information about linking). Tested locally with helper scripts. Comments welcomed.
[1] https://gitlab.freedesktop.org/spice/libcacard/-/merge_requests/14/
> libcacard: Add fuzzing scripts

- projects/libfido2/Dockerfile
- projects/libfido2/build.sh
CIFuzz was failing and not finding the downloaded corpus, looking
at the logs show:
2020-03-12T15:15:53.2454777Z Running: docker run --rm --privileged --cap-add SYS_PTRACE -e
FUZZING_ENGINE=libfuzzer -e SANITIZER=address -e ARCHITECTURE=x86_64 -e OUT=/github/workspace/out
--volumes-from aaad25ec2b6d gcr.io/oss-fuzz/libfido2 /bin/bash -c 'rm -rf /src/libfido2/* && cp -r
/github/workspace/storage/libfido2 /src && compile'
Note the the rm -rf /src/libfido/* bit.
> [libfido2] CIFuzz workaround, put seed corpus outside of cloned libfido2 repo

- projects/envoy/build.sh
We had a build issue where CLI bazel flags override the copts set by the bazel build targets. We had unit tests running as a precursor to one fuzz test (that updates the corpus on the fly), and the test fails because a library RE2 modifies it's behavior in fuzz build mode.
This prevents CLI passing of `FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION`, leaving it to the build targets.
Ideally this is not what we should do, and find some way to wrap / ignore this option when building the dependency.
Testing: Ran build locally with updated script.
> [envoy] fix build

- infra/cifuzz/cifuzz.py
Fix bug in affected fuzzer caused by miss matched naming. The git diff was returning file paths relative to the root of the project and the coverage files was returning file paths relative to one directory above the project directory.
> [CIFuzz] Affected fuzzer fix

- projects/libra/build.sh
Release mode runs faster than debug mode
> [libra] build fuzzers in release mode

- projects/wasmtime/build.sh
Accounts for changes in
https://github.com/bytecodealliance/wasmtime/pull/1343 where
compilation of all the fuzzers now requires extra features to be
enabled.
> Update wasmtime's build script

- README.md
- docs/faq.md
- docs/index.md
- projects/guetzli/Dockerfile
- projects/imagemagick/Dockerfile
- projects/libgd/Dockerfile
- projects/libjpeg-turbo/Dockerfile
- projects/libreoffice/Dockerfile
- projects/libtiff/Dockerfile
- projects/libvips/Dockerfile
The lcamtuf.coredump.cx hostname has been accepting HTTPS connections only since around the 13th or 14th March.
This fix will allow the builds for the affected projects to succeed again as they will have been failing for the last week.
> Upgrade lcamtuf.coredump.cx requests to use HTTPS, fixes builds for guetzli, libjpeg-turbo, libtiff, libvips

- projects/spidermonkey-ufi/build.sh
- projects/spidermonkey/build.sh
This PR changes the following things about Spidermonkey builds:
1) Don't use `--disable-shared-js` as it's currently broken and unsupported.
2) Use `-gline-tables-only` when building to save some disk space
3) Use `--enable-debug` also in the ufi build, so we have assertions enabled.
With these changes, all local builds succeed.
> Fix SM builds and use -gline-tables-only for building

- projects/tpm2-tss/build.sh
We need to disable all supported tctis for fuzzing.
This includes recently added swtpm.
Also switch the option from --enable-<module>=no
to preferred --disable-<module>
> [tpm2-tss] disable swtpm tcti

- projects/suricata/Dockerfile
- projects/suricata/build.sh
- projects/suricata/project.yaml
Asked in #624
The code is not yet merged in suricata main repository cf https://github.com/OISF/suricata/pull/3914
MSAN is not yet enabled because of Rust and C interactions cf https://github.com/google/oss-fuzz/issues/2145#issuecomment-485781098
@victorjulien could you ack ?
cc @kcc as you seemed interested in rust targets
> Adds project suricata

- projects/ghostscript/gstoraster_fuzzer.cc
Previously raster output data was printed on stdout. While this
is similar to how Ghostscript is run by CUPS's gstoraster filter it
unnecessarily prolongs execution time for many files.
Changing the output file still means that CUPS will be sent the
rasterized page and will be asked to convert it to a PWG raster which
it then dutifully writes to /dev/null. Thus no major difference is
expected in what code is executed in Ghostscript (or CUPS).
When run locally on a testcase found among the problematic files here:
gs://ghostscript-corpus.clusterfuzz-external.appspot.com/libFuzzer/
fuzzer target reported a timeout after 120 seconds before this commit.
After this commit the fuzzer target succeeded after about 3 seconds.
> [ghostscript] Avoid printing raster output to stdout.

- projects/bignum-fuzzer/Dockerfile
- projects/bignum-fuzzer/build.sh
Mbed TLS has gone back to being self-contained, without a separate
submodule for the cryptography part of the library. Revert the
bignum-fuzzer build scripts accordingly.
This reverts commit 54733ddc84ec73e3c21d6fffc446dbd0fa7a2c5e.
> [bignum-fuzzer] Mbed TLS no longer has an mbed-crypto submodule

- projects/ffmpeg/build.sh
This should add the fate samples as seeds for the libavformat test, iam not 100% sure that works as the
local docker seems not to use the seed corpus locally specified and there
are options to stop it from downloading from google cloud and specifying a local
directory, which is how it was tested.
Another problem could be docs/getting-started/new_project_guide.md which says
"Seed corpus files will be used for cross-mutations and portions of them might appear
in bug reports or be used for further security research. It is important that corpus
has an appropriate and consistent license."
Now google themselfs added the original code using this and then
disabled it because of space. But yeah i dunno if this is ok or not.
> [FFmpeg] Add fate samples for demuxer tests

- projects/ghostscript/Dockerfile
- projects/ghostscript/build.sh
The previous configuration tried to use the system tiff library with
the bundled jpeg library. That configuration is not supported by
Ghostscript.
> [ghostscript] Build using the bundled tiff and jpeg libraries.

- projects/xmlsec/Dockerfile
- projects/xmlsec/build.sh
Fixes xmlsec build failure flagged in https://github.com/google/oss-fuzz/issues/3479#issue-577288248
Turns out xmlsec now depends on liblzma.
> xmlsec: Install and link xmlsec against it

- projects/ghostscript/Dockerfile
This is the correct URL according to https://www.freetype.org/developer.html
This resolves the HTTP 502 error from the git server.
> [ghostscript] Use official git server URL.

- projects/libucl/Dockerfile
- projects/libucl/build.sh
- projects/libucl/project.yaml
Have talked with the maintainers of Libucl,  which is a popular universal configuration library parser, and they are happy to integrate with OSS-fuzz.
The fuzzer for this project has been committed to the upstream repository and the pull request can be found here: https://github.com/vstakhov/libucl/pull/214
Waiting for email address of the maintainers for bug reports and once I get it I will commit it.
> Adding Libucl project

- projects/jbig2dec/jbig2_fuzzer.cc
Apparently the maximum memory usage is 2.5Gbyte so a limit of 3Gbyte
is to liberal. Set limit to 1Gbyte to make sure that any extra memory
used by the fuzzer is allowed. 1Gbyte ought to be enough for most real
world images decoded by jbig2dec.
> [jbig2dec] Limit allocations to 1Gbyte.

- projects/ghostscript/gstoraster_fuzzer.cc
- projects/ghostscript/project.yaml
Several flags for Ghostscript should be updated, and we also want to enable the memory sanitizer to see what falls out.
> Update flags and enable new sanitizer

- infra/base-images/base-runner/bad_build_check
Matches AFL, also should fix some project failures like mbedtls with many targets.
> Skip seed corpus unpack for Honggfuzz in bad build check

- infra/base-images/base-clang/checkout_build_install_llvm.sh
Some project may prefer using LLD. I'm not sure this is 100% safe, but should be fine to try on per project basis.
We did try it a while ago but ended up reverting: https://github.com/google/oss-fuzz/issues/295
I suspect that things should've changed by now, as Chromium is using LLD.
@kcc @morehouse do you anticipate any issues?
> [infra] Build LLD inside base-clang image.

- projects/systemd/project.yaml
It doesn't seem to make much sense to keep non-gmail addresses there.
https://github.com/google/oss-fuzz/issues/3576
https://bugs.chromium.org/p/monorail/issues/detail?id=7461
> [systemd] remove my non-gmail address

- projects/qt/Dockerfile
Seems to be needed on Windows only.
> [qt] Don't install python

- projects/brotli/project.yaml
- projects/bzip2/project.yaml
- projects/django/project.yaml
- projects/dropbear/project.yaml
- projects/firefox/project.yaml
- projects/fuzzing-puzzles/build.sh
- projects/fuzzing-puzzles/project.yaml
- projects/libexif/project.yaml
- projects/libucl/project.yaml
- projects/libyaml/project.yaml
- projects/llvm/project.yaml
- projects/mysql-server/project.yaml
- projects/nss/project.yaml
- projects/openjpeg/project.yaml
- projects/perfetto/project.yaml
- projects/pffft/project.yaml
- projects/pillow/project.yaml
- projects/python3-libraries/project.yaml
- projects/samba/project.yaml
- projects/tesseract-ocr/project.yaml
- projects/xz/project.yaml
Also enabled msan for openjpeg and re-enabled fuzzing-puzzles project to see if honggfuzz could crack it. I may need to remove the existing corpora though.
Travis will likely time out so I'll just TBR this later today.
I've built all these projects on GCB and they have at least one build archived now.
> [honggfuzz] Enable honggfuzz for 19 more projects (fixes #3591).

- infra/base-images/base-builder/Dockerfile
Reverts google/oss-fuzz#3614
Not needed, we should just export the flags via an ENV variable.
> Revert "Add native go fuzzing module go114-fuzz-build to builder image"

- projects/ghostscript/build.sh
Valgrind may complain when software reads out partially uninitialized data
and stores it elsewhere, but only reads the initialized parts from this
latter location. The flag enables code that initializes all the data to
avoid valgrind reporting false positives. Presumably MSAN suffers from
similar issues so, try enabling this flag.
> [ghostscript] Enable flag also used in valgrind builds.

- projects/ghostscript/gstoraster_fuzzer.cc
The default setting allows for state to be temporarily saved to disk.
This is likely to interfere with the fuzzer's knowledge about state of data.
> [ghostscript] Make sure that all state kept in memory.

- projects/libpsl/Dockerfile
Link to libicu tarball didn't work any more. Updated and tested locally.
> [libpsl] Update libicu to fix the build

- projects/json-c/Dockerfile
- projects/json-c/build.sh
This fixes a recent build failure. Upstream has moved to using cmake and the fuzzers in oss-fuzz were still using the autogen.sh build.
> switch to cmake, find new headers

- projects/cryptofuzz/Dockerfile
- projects/cryptofuzz/build.sh
This was broken previously but it should work now: https://github.com/google/oss-fuzz/issues/2836#issuecomment-538480084
> [cryptofuzz] Enable libsodium again

- projects/nanopb/Dockerfile
- projects/nanopb/build.sh
This PR fixes the docker image which wasn't building.
Switched to pip3 in the process.
> Fixed broken build of nanopb and switched to pip3

- projects/esp-v2/Dockerfile
No need for workaround since ESPv2 was updated to Bazel 3.0.0
Ref: #3093
Signed-off-by: Teju Nareddy <nareddyt@google.com>
> [ESPv2] Use latest base-builder image

- projects/suricata/build.sh
So, we can change configure options without making PRs to oss-fuzz each time
> Builds suricata with configure script from upstream repo

- projects/esp-v2/project.yaml
Coverage reports previously included external dependencies. But some bazel directories have symlinks that cause lcov to check invalid directories.
Remove reports for external files. We only want reports for the files in our repository.
Verified with the following command:
```
python infra/helper.py coverage esp-v2 -- -ignore-filename-regex='.*\.cache.*' -ignore-filename-regex='.*bazel-out.*'
```
> [ESPv2] Fix coverage build

- projects/go-json-iterator/Dockerfile
- projects/go-json-iterator/build.sh
- projects/syzkaller/Dockerfile
- projects/syzkaller/build.sh
> Fix syzkaller to use go-fuzz.

- projects/eigen/basicstuff_fuzzer.cc
Don't want to have that misleading example committed by a Google account in https://github.com/google/oss-fuzz/pull/3563
> [eigen] Remove unnecessary static_cast from FDP calls (follow up for #3563).

- infra/build_specified_commit.py
Otherwise changed timestamps may cause build issues.
> bisector: Preserve file metadata when copying /src to host.

- infra/bisector.py
- infra/build_specified_commit.py
Let build failures continue during the actual bisection for now to keep
the bisection going. A future PR can improve the logic of that when it
happens.
> bisector: raise exceptions when building new or old commit fails.

- projects/cryptofuzz/build.sh
This builds the BoringSSL [decrepit](https://boringssl.googlesource.com/boringssl/+/refs/heads/master/decrepit/) part of the library, which implements some additional ciphers I want to test with Cryptofuzz.
> [cryptofuzz] BoringSSL: Build 'decrepit'

- docs/getting-started/new-project-guide/go_lang.md
- projects/go-attestation/build.sh
- projects/go-dns/build.sh
- projects/go-json-iterator/build.sh
- projects/golang/build.sh
- projects/gonids/Dockerfile
- projects/gonids/build.sh
- projects/kubernetes/build.sh
- projects/syzkaller/build.sh
Looks like it isn't needed anymore, or maybe it was never needed and I mistakenly added it in the first place.
Also fixed `gonids` and `go-dns` builds, they had import errors.
> [Go] remove "-lpthread" flag from "compile_fuzzer" and fix comments (#2714).

- projects/envoy/Dockerfile
Fixes for Envoy: https://github.com/google/oss-fuzz/issues/3157
> Revert clang workaround for Envoy

- infra/base-images/base-builder/srcmap
- infra/gcb/build_and_run_coverage.py
- infra/gcb/build_lib.py
- infra/gcb/build_project.py
Haven't properly tested this yet, please consider it as a draft, but should be fine to review.
I also wanted to pass `FUZZING_LANGUAGE` to the `helper.py shell`, but we can't parse yaml without installing `pyyaml` module, so not sure about that, probably not necessary, as users don't typically run `srcmap` command.
> [infra] Improve srcmap support for Go projects (#3355, #2714).

- projects/libcacard/Dockerfile
Fuzzers are already merged in the upstream project [1] so this updates the link to the correct repository.
Tested locally with `check_build`:
```
$ python infra/helper.py check_build libcacard
Running: docker run --rm --privileged -i -e FUZZING_ENGINE=libfuzzer -e SANITIZER=address -e ARCHITECTURE=x86_64 -v /home/jjelen/devel/oss-fuzz/build/out/libcacard:/out -t gcr.io/oss-fuzz-base/base-runner test_all
INFO: performing bad build checks for /tmp/not-out/fuzz_xfer.
1 fuzzers total, 0 seem to be broken (0%).
Check build passed.
```
[1] https://gitlab.freedesktop.org/spice/libcacard/-/merge_requests/14
> libcacard: Reference upstream repository with merged fuzzers

- infra/bisector.py
- infra/build_specified_commit.py
- infra/repo_manager.py
When the build fails against HEAD OSS-Fuzz, we find the date of the
commit for the project, and use the latest revision of OSS-Fuzz before
it to rebuild the project builder container.
Subsequent runs will use the last built container, and if that fails
that will again find the closest revision of OSS-Fuzz.
Also factor BaseRepoManager out of RepoManager to provide a generic repo
manager class for dealing with existing checkouts (which don't need a
clone).
> Bisector: Be a bit smarter about picking which OSS-Fuzz commit to build with.

- projects/nanopb/Dockerfile
- projects/nanopb/build.sh
[As suggested by Abhishek](https://github.com/google/oss-fuzz/pull/3637#issuecomment-616705946), let's see if it helps to move the installation of Anaconda to the docker file.
(I am unable to reproduce the broken build locally, so this PR is merely a try)
> [nanopb] Suggested fix for broken build

- infra/build_specified_commit.py
Submodules weren't working correctly due to absolute paths being set.
We add a step to turn those paths to relative after copying them to
host.
> build_specified_commit: Make submodules work.

- projects/binutils/fuzz_readelf.c
Upstream binutils commit 978c4450511 broke this target.  What's more,
the use-after-free issue had been fixed quite some time ago.  So,
don't reference symtab_shndx_list.
> Fix fuzz_readelf.c compile error (#3705)

- projects/hostap/Dockerfile
- projects/hostap/build.sh
Recent builds have started failing due to libssl-dev missing --
presumably the base image no longer includes this. Fix this by
installing libssl-dev.
> [hostap] Add missing libssl-dev dependency

- projects/libzmq/build.sh
- projects/libzmq/decode_fuzzer.cc
- projects/libzmq/project.yaml
- projects/libzmq/socket_bind_fuzzer.cc
- projects/libzmq/socket_connect_fuzzer.cc
zeromq is a networking framework, so the most relevant way to receive untrusted data (that would be good to fuzz) is via the network.
Add 2 simple tests to start exercising the internal engine, via loopback ipv4 tcp sockets. If these work I can add more, and then there's also a few APIs that take in free-form data that would be good to fuzz as well.
If using TCP sockets in these tests is frowned upon, I could switch to AF_UNIX with minimal changes - the code paths internally are _mostly_ the same between them anyway. I took care of using ephemeral and dynamically allocated free ports in both cases, which is usually the first objection for these kind of tests.
This is the first time I work with fuzzing, so please bear with me if I'm doing something not quite right. Also for some reason …
> libzmq: update maintainers, add network tests

- projects/nanopb/Dockerfile
- projects/nanopb/build.sh
This pull request fixes a python2 vs. python3 version conflict that caused nanopb build to fail. This remaps `/usr/bin/python` to python3 to make sure everything runs with the same version.
There were previous pull requests #3637 and #3693 that attempted to fix this, but there still remained some scripts that got run with Python 2. As a workaround for that Anaconda was used for protobuf installation, but now that is unnecessary also.
> nanopb: Fix build error, remove anaconda dependency

- projects/haproxy/Dockerfile
- projects/haproxy/build.sh
- projects/haproxy/fuzz_cfg_parser.c
- projects/haproxy/fuzz_hpack_decode.c
- projects/haproxy/project.yaml
Inspired by this Tweet https://twitter.com/_fel1x/status/1252502296661016576 from Felix Wilhelm I thought it would be worth integrating Haproxy with OSS-Fuzz. @AdamKorcz reached out to the maintainers who are happy to have Haproxy integrated with OSS-Fuzz as long as we keep the fuzzers in the OSS-Fuzz repo. If you are happy integrating it then I would be glad to add more fuzzers for it.
> Added initial integration of haproxy

- projects/binutils/Dockerfile
- projects/binutils/build.sh
- projects/binutils/fuzz_readelf.options
Per https://github.com/google/oss-fuzz/pull/2617 the maintainers of binutils are not interested in memory leaks from the binutils tools, e.g. Readelf. These applications are transient in that they run and terminate without staying alive for long. Therefore, forcing Readelf fuzzer to avoid leak detection.
> [Binutils] Avoid detecting memory leaks in readelf fuzzer 

- projects/cryptofuzz/Dockerfile
On PR #3735 Travis found that libgcrypt clone git cmd in Dockerfile stop to work.
This PR is to return "green" checks done by Travis only.
> cryptofuzz: fix Dockerfile

- projects/oniguruma/.gitignore
- projects/oniguruma/Dockerfile
- projects/oniguruma/build.sh
- projects/oniguruma/fuzzer.options
- projects/oniguruma/project.yaml
This adds the project.yaml, Dockerfile and build.sh for Oniguruma.
Oniguruma is a regular expressions library under the BSD license.
I don't know how much of it is used, but it was bundled with PHP before, so there are a lot of bugs in the CVE list. (Fixed)
> Add project oniguruma

- projects/libarchive/build.sh
The recently added seed corpus [has been uploaded](https://github.com/libarchive/libarchive/pull/1365) to the upstream repository.
I am updating the build script accordingly by removing the creation of the seed corpus and using the .zip file in Libarchives own repository.
> [Libarchive] Removed creation of corpus from build script

- infra/bisector.py
Ignoring it and trying to bisect the entire range up to new_commit is
too slow and does not work well in practice.
> Raise exception if old_commit has the same behaviour as new_commit.

- projects/jsoncons/build.sh
To simplify things from an OSS-Fuzz point of view we have moved all work related to building fuzzers in Jsoncons to upstream.
> [jsoncons] All work in building fuzzers has been moved to upstream.

- projects/cryptofuzz/build.sh
I recently merged libtomcrypt into the project, but it turns out it has symbol collisions with OpenSSL/LibreSSL/BoringSSL, leading to false positive bugs like https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=21898.
This patch builds libtomcrypt together only with NSS, with which it should have no symbol collisions.
> [cryptofuzz] Move libtomcrypt to NSS-based binary

- projects/ipfs/Dockerfile
- projects/ipfs/build.sh
- projects/ipfs/project.yaml
Submitting [IPFS](http://github.com/ipfs/go-ipfs) for initial integration.
This initial fuzz testing validates the interface of the multiple
[datastores](http://github.com/ipfs/go-datastore) backing of IPFS. A fuzzer for the protocol between nodes will follow.
> [IPFS] Initial fuzzing of datastore consistency

- projects/clamav/Dockerfile
- projects/clamav/build.sh
Flex & Bison are needed to generate source files for yara syntax
support. While the generated source are currently in the clamav-devel
repo, the build system sometimes thinks the files must be regenerated.
In the future, these and the autotools generated files will be removed
from the clamav-devel repo and will need to be generated for every
build.
We're also planning to add CMake tooling (still a work in progress).
Once the generated files are removed, we'll either have ot build the
fuzz targets with CMake or bring in autoconf, automake, m4, libtool, and
pkg-config to generate the files in build.sh. At that time, we should
also update build.sh to build the dependencies statically, many of which
are missing at present meaning we're not getting great code coverage.
We'll also want to load …
> [clamav] Add flex, bison to Dockerfile

- infra/base-images/base-runner/Dockerfile
- infra/bisector.py
Using whether or not the target crashed is not sufficient. There are
numerous cases where the state changes.
> Use dedup_token_length in bisector.

- projects/go-coredns/Dockerfile
- projects/go-coredns/build.sh
- projects/go-coredns/project.yaml
@miekg do you approve integration into oss-fuzz for coredns ?
As this is project using go modules, I had to use `go-fuzz-build` instead of `go-fuzz` as is done on go-dns project...
> Adds golang project coredns

- infra/base-images/base-builder/Dockerfile
Remove it now to avoid people using it.
> Remove deprecated go-fuzz-build

- projects/opensc/build.sh
This changeset improves fuzzing of OpenSC project:
* Disable optimization when building to get nicer traces
* Add corpus files for first fuzzers (which is already available in repository for some time)
Please, do not merge yet. There are few bugs that need to be fixed first in OpenSC side in OpenSC/OpenSC#2012. With these changes, I am able to build fuzzers successfully:
```
$ python infra/helper.py build_fuzzers opensc ~/devel/OpenSC
$  python infra/helper.py check_build opensc
Running: docker run --rm --privileged -i -e FUZZING_ENGINE=libfuzzer -e SANITIZER=address -e ARCHITECTURE=x86_64 -v /home/jjelen/devel/oss-fuzz/build/out/opensc:/out -t gcr.io/oss-fuzz-base/base-runner test_all
INFO: performing bad build checks for /tmp/not-out/fuzz_asn1_sig_value.
INFO: performing bad build …
```
> Improve OpenSC fuzzing

- projects/libvpx/build.sh
This adds coverage for 10/12-bit paths.
> libvpx,build.sh: enable vp9 high-bitdepth

- projects/cascadia/Dockerfile
- projects/cascadia/build.sh
- projects/cascadia/project.yaml
This PR adds [cascadia](https://github.com/andybalholm/cascadia) to oss-fuzz. 
cascadia is used by [goquery](https://github.com/PuerkitoBio/goquery) of which there is an example [here](https://github.com/PuerkitoBio/goquery/blob/master/type.go#L9).
> [cascadia] initial integration

- projects/dragonfly/Dockerfile
- projects/dragonfly/build.sh
- projects/dragonfly/project.yaml
This PR provides initial integration of [Dragonfly](https://github.com/dragonflyoss/Dragonfly).
Dragonfly is part of the [Cloud Native Computing Foundation](https://landscape.cncf.io/selected=dragonfly), and a [1-year-old tweet](https://twitter.com/dragonfly_oss/status/1151852499659190272) reveals a part of their userbase.
@lowzj Is the contact person of the oss-fuzz integration, and currently we are waiting for the fuzzers to be merged upstream.
> [dragonfly] initial integration

- docs/getting-started/continuous_integration.md
- infra/cifuzz/actions/build_fuzzers/action.yml
- infra/cifuzz/cifuzz.py
- infra/cifuzz/cifuzz_test.py
- infra/presubmit.py
Allow users to set this value in the config files and then use it
during check_build.
Fixes https://github.com/google/oss-fuzz/issues/3429
> [CIFuzz] Support ALLOWED_BROKEN_TARGETS_PERCENTAGE

- infra/base-images/base-clang/checkout_build_install_llvm.sh
This commit fixes bugs so that commit OSS-Fuzz builds clang from will track
Chrome's instead of being pinned to e84b7a5fe230e42b8e6fe451369874a773bf1867.
With this commit, clang (llvm-project) will be updated from:
e84b7a5fe230e42b8e6fe451369874a773bf1867
to Chrome's current version:
99ac9ce7016d701b43b8f0c308dc3463da57d983.
This commit fixes two bad bugs:
1. Using the output of a command instead of the return code.
2. Using "!" to determine whether the command succeeded. "!" in bash
will do the same thing for 0 and 1.
These bugs were hidden by OUR_LLVM_REVISION which we traditionally
set to the last commit we rolled back to. If this were set to nothing and
the last commit stored as a comment
instead of stored as a variable that is not supposed to be used
unless FORCE_OUR_REVISION is set, …
> Fix clang updating script to actually track Chrome's

- projects/libspectre/Dockerfile
Also removes the version suffix for the extracted directory to minimize changes to the build script, this is already accounted for upstream.
> [libspectre] update to ghostscript-9.52

- projects/cryptofuzz/project.yaml
Thyla and Ben also need access to the NSS-side of OSS fuzz for their work.
> Add Thyla and Ben to NSS OSS-Fuzz results

- projects/rdkit/Dockerfile
Build was failing on GCB because WORKDIR is parsed, and restored
by gcb build script because GCB unsets it. Parsing assumed that only one WORKDIR call is made.
> [rdkit] Speculative fix for build.

- projects/prometheus/Dockerfile
- projects/prometheus/build.sh
- projects/prometheus/project.yaml
This PR adds initial integration of the Cloud Native Computing Foundation graduated project, [Prometheus](https://github.com/prometheus/prometheus). 
A selection of the projects users can be found on [the Prometheus website](https://prometheus.io/).
@juliusv is in the loop as well for this integration application.
> [Prometheus] Initial integration

- projects/cryptofuzz/Dockerfile
- projects/cryptofuzz/build.sh
Microsoft Symcrypt: https://github.com/microsoft/SymCrypt
This also fetches a recent CMake because SymCrypt requires that. Based on https://github.com/google/oss-fuzz/commit/06cd6f44311cdf3e114463bfd670b5e1ca30fbd8.
Currently not including SymCrypt in UBSAN builds to prevent a deluge of alerts for bugs already reported: https://github.com/microsoft/SymCrypt/issues/8
> [cryptofuzz] Add Microsoft SymCrypt

- projects/grpc-gateway/Dockerfile
- projects/grpc-gateway/build.sh
- projects/grpc-gateway/project.yaml
This PR provides initial integration of [grpc-gateway](https://github.com/grpc-ecosystem/grpc-gateway).
Adopters include:
- [Ad Hoc](https://adhocteam.us/) uses the gRPC-Gateway to serve millions of API requests per day.
- Chef uses gRPC-Gateway to provide the user-facing API of Chef Automate. Furthermore, the generated OpenAPI data serves as the basis for its API documentation. An example can be seen [here](https://github.com/chef/automate/tree/master/vendor/github.com/grpc-ecosystem/grpc-gateway).
- [Argo](https://github.com/argoproj/argo-cd/blob/master/Gopkg.toml#L11)
- [Azure](https://github.com/Azure/open-service-broker-azure/tree/master/vendor/github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway)
- [Scaleway](https://www.scaleway.com/en/) uses the gRPC-Gateway since 2018 …
> [grpc-gateway] Initial integration

- projects/knot-dns/Dockerfile
- projects/knot-dns/build.sh
Relates to https://gitlab.labs.nic.cz/knot/knot-dns/-/commit/d4ec3a3aa8b7e2ba4d196e2f7984173069e3d91b
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=22191
> [knot-dns] add liblmdb dependency

- projects/solidity/Dockerfile
As per title. Z3 is no longer required to be instrumented since it is not part of solidity's attack surface.
> solidity: Disable Z3 build in dockerfile

- projects/wasmtime/build.sh
This enables not only the binaryen-using fuzz targets, but also the peepmatic fuzz targets (which is necessary after https://github.com/bytecodealliance/wasmtime/pull/1727).
> wasmtime: build fuzz targets with --all-features

- infra/helper.py
This is necessary for the bisector to be able to build older revisions.
Print a warning instead.
> Relax project language requirement.

- projects/tidb/Dockerfile
- projects/tidb/build.sh
- projects/tidb/project.yaml
This PR adds initial integration of [TiDB](https://github.com/pingcap/tidb).
The storage layer of TiDB, named TiKV, became a CNCF member in 2018, and many large companies rely on TiDB, including Bank of Beijing, Industrial and Commercial Bank of China, China Telecom Shanghai.
An extensive but not exhaustive list of adopters can be found [here](https://pingcap.com/docs/dev/adopters/).
> [TiDB] initial integration

- infra/base-images/base-builder/compile
This is needed for projects that mix both rust and c/c++.
> Set rust flags always in compile step.

- projects/fasthttp/Dockerfile
- projects/fasthttp/build.sh
- projects/fasthttp/project.yaml
This PR adds initial integration of [fasthttp](https://github.com/valyala/fasthttp), an http implementation up to 10 times faster than [net/http](https://golang.org/pkg/net/http/). 
The library is widely adopted in both open source software and closed source software that serve hundreds of thousands of rps in production.
[According to a contributor](https://github.com/valyala/fasthttp/issues/777#issuecomment-615973513), fasthttp is used by one of the largest media companies in the world for critical services.
It is used by [VertaMedia](https://adtelligent.com/) to handle 200k rps in production.
Below are some examples of open source libraries that have adopted fasthttp:
[Dragonfly](https://github.com/dragonflyoss/Dragonfly/blob/master/pkg/httputils/http_util.go#L40) …
> [fasthttp] Initial integration

- infra/base-images/base-builder/compile
Rust sanitizer flags are not supported for these configs.
Fixes Cras and ecc-diff-fuzzer builds.
> Don't add Rust sanitizer flags when using ubsan or i386.

- infra/build_specified_commit.py
rsync seems to have disappeared in the latest images somehow, and we
can't rely on it always existing.
> build_specified_commit: revert to using cp.

- projects/stb/Dockerfile
- projects/stb/build.sh
This PR adds a generic image read fuzzer with a gif+png dictionary and gif+png+jpg seed corpus.
I think this should be merged after https://github.com/nothings/stb/pull/960 which contains a lot of fixes, PR's are only getting merged every 4-6 months so it might take a while. Should the build script be upstreamed in this case?
> [stb] extend code coverage for stb_image

- projects/hermes/build.sh
Coverage builds are failing because `CONFIGURE_FLAGS` is not set to anything.
> [hermes] Fix coverage build

- projects/ipfs/Dockerfile
- projects/ipfs/project.yaml
was previously an alias, which received notifications but couldn't see details
> [IPFS] Update email address

- projects/qt/Dockerfile
> [qt] Don't install build-essential

- infra/base-images/base-builder/Dockerfile
Address review comment in https://github.com/google/oss-fuzz/pull/3890#pullrequestreview-419693856
> Set up python in one docker layer.

- projects/suricata/Dockerfile
- projects/suricata/build.sh
Needs https://github.com/OISF/suricata/pull/4986
And then, should fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=22429
Discussed in https://github.com/google/oss-fuzz/issues/3469#issuecomment-632410321
> Makes suricata work with rust sanitizers

- projects/firefox/build.sh
This fixes the problems that we're recently introduced when adding git support and patches to the libFuzzer cloning script. For now, the patches are not relevant to oss-fuzz and since only `HEAD` is built on oss-fuzz, we can use `--depth` instead of `--shallow-since` for speeding up the git clone.
> [firefox] Fix libFuzzer cloning process

- projects/nanopb/Dockerfile
After the addition of Python 3.8 in #3874, the default python3 is
now /usr/local/bin/python3. The nanopb Dockerfile hardcoded a path
of /usr/bin/python3, causing again problems of Python packages being
installed for different version than attempting to run with.
> [nanopb] Use $(which python3) instead of hardcoding /usr/bin/python3

- .travis.yml
- infra/cifuzz/cifuzz_test.py
- infra/cifuzz/fuzz_target.py
- infra/cifuzz/fuzz_target_test.py
- infra/dev-requirements.txt
- infra/presubmit.py
- infra/travis/requirements.txt
This breaks when a new fuzz target is added to a project.
Intstead, always report the crash unless we can run the OSS-Fuzz build of the target and
repro the crash.
Also, make some other changes:
1. Refactor fuzz_target.py and fuzz_target_test.py
2. Introduce pyfakefs and parameterized as dependencies and use them
in tests.
Fixes https://github.com/google/oss-fuzz/issues/3813.
> Fix CIFuzz issue where targets assumed in OSS-Fuzz build if exists

- projects/jsoncpp/project.yaml
cdunn2001 had asked to be removed as a primary contact for jsoncpp oss-fuzz, a while back.
Discussion of maintainers: https://github.com/open-source-parsers/jsoncpp/pull/1047
@dota17
> [jsoncpp] Update primary contact

- projects/php/build.sh
This fixes the build failure. The `--enable-json` option no longer exists, and is promoted to an error due to `--enable-option-checking=fatal`.
> [php] Remove --enable-json

- infra/base-images/base-runner/coverage
- infra/base-images/base-runner/download_corpus
> Don't create empty corpus archive as it wont unpack.

- projects/prometheus/project.yaml
All of these people are active Prometheus Team members (though it's only a subset of team members).
Signed-off-by: Julius Volz <julius.volz@gmail.com>
> Update email addresses for Prometheus

- projects/systemd/project.yaml
Reverts google/oss-fuzz#3606
Looks like it was addressed in https://bugs.chromium.org/p/monorail/issues/detail?id=7461
> Revert "[systemd] remove my non-gmail address"

- projects/libtorrent/Dockerfile
update libtorrent version to fuzz, from branch `RC_1_2` to `RC_2_0`. Also updates boost version.
> bump libtorrent to fuzz the 2.0 release branch

- infra/gcb/builds_status.py
When build log is not found, skip it and avoid 404.
Fixes exception
```
File "oss-fuzz/infra/gcb/builds_status.py", line 243, in <module>
main()
File "oss-fuzz/infra/gcb/builds_status.py", line 228, in main
status_filename='status.json')
File "oss-fuzz/infra/gcb/builds_status.py", line 159, in update_build_status
last_build = find_last_build(builds, project, build_tag_suffix)
File "oss-fuzz/infra/gcb/builds_status.py", line 102, in find_last_build
log.download_to_filename(f.name)
File "/var/jenkins_home/workspace/infra/builds_status/ENV/local/lib/python2.7/site-packages/google/cloud/storage/blob.py", line 565, in download_to_filename
file_obj, client=client, start=start, end=end)
File "/var/jenkins_home/workspace/infra/builds_status/ENV/local/lib/python2. …
```
> Fix builds_status cron exception.

- projects/prometheus/Dockerfile
This makes build_fuzzers work with local checkouts.
Without this, it complains with 'Cannot use local checkout with "WORKDIR
/src".'
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
> Prometheus: Don't use WORKDIR $SRC

- projects/esp-v2/Dockerfile
Our coverage reports started failing recently with `rsync: command not found`. Install `rsync` to solve.
Similar to #3912
> [espv2] Install rsync

- projects/ecc-diff-fuzzer/build.sh
Should fix build failure 
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=22819
> ecc-diff-fuzzer buils nettle without openssl

- projects/qt/build.sh
To handle PDFs, QImage requires qtwebengine
which doesn't build statically.
This reverts commit 934c770abb932629da5c53af594bbe785964c7fb.
> Revert "[qt] Add pdf to image corpus (#3926)"

- projects/tensorflow/Dockerfile
- projects/tensorflow/build.sh
- projects/tensorflow/project.yaml
Apparently as TF moved to stable Bazel releases the build became even more broken.
This PR should make TF use Bazel from `.bazelversion`, via Bazelisk. So we install Bazelisk in `Dockerfile` and then remove the workarounds for getting the Bazel binary that we had in `build.sh`. Since those were causing the [recent build failure](https://oss-fuzz-build-logs.storage.googleapis.com/log-12d36a9a-0ce0-45c8-8887-a39ecfb5f344.txt) this should fix that.
I am currently compiling in the container. First try resulted in a need to also install `numpy`.
Finally, since `dga@` left Google, remove address from cc list
> Fix TensorFlow build

- projects/muparser/build.sh
Fix [this build failure](https://oss-fuzz-build-logs.storage.googleapis.com/index.html#muparser).
Related to https://github.com/google/oss-fuzz/pull/3814
> [muparser] set open_mp not required

- projects/html5ever/Dockerfile
- projects/html5ever/build.sh
- projects/html5ever/project.yaml
[html5ever](https://github.com/servo/html5ever) is a Rust project and html5ever is a HTML parser developed as part of the [Servo](https://github.com/servo/servo) browser engine.
This has been discussed with @jdm
> Added the html5ever project.

- projects/serde-yaml/Dockerfile
- projects/serde-yaml/build.sh
- projects/serde-yaml/project.yaml
Integrated another Rust project similar to serde-json that was integrated [here](https://github.com/google/oss-fuzz/pull/3785) but now for yaml. 
The project has been downloaded 3 million times [here](https://crates.io/crates/serde_yaml) and more than 400 projects depend on it as show [here](https://crates.io/crates/serde_yaml/reverse_dependencies) 
The fuzzers are merged upstream and maintainer is @dtolnay
> Added initial integration of serde-yaml.

- projects/jsonparser/build.sh
Having moved the build script upstream, this PR updates `build.sh` accordingly.
> [jsonparser] Updated build script

- projects/spidermonkey-ufi/build.sh
This copies all required dependencies for the `js` and `fuzz-tests` binaries. Note that we can't just copy `*.so` because the build also produces a `libjs` that we don't need.
> [spidermonkey-ufi] Copy additional dependency libraries

- projects/html5ever/project.yaml
The current primary contact email goes to a group address, so I'm not able to view reports for the project.
> Add me to html5ever CCs.

- projects/ffmpeg/build.sh
Network protocols are disabled during build so it makes no sense to
enable these
> [FFmpeg] projects/ffmpeg/build: disable demuxers only used for network protocols

- projects/nodejs/Dockerfile
- projects/nodejs/build.sh
- projects/nodejs/fuzz_url.cc
- projects/nodejs/project.yaml
Fuzzing for nodejs core. Notice that the build time here can take quite some time ~10/15 minutes, since we need to build v8 first.
The `project.yaml` file has been here since December 2016 so I am not sure if the same information is valid anymore. The original `project.yaml` was added by @oliverchang so perhaps you might have an idea here? I have not reached out to the security people at Nodejs as I assume if the contact information is accurate, if not then please do tell me.
> [Nodejs] initial integration.

- infra/bisector.py
- infra/build_specified_commit.py
- infra/helper.py
Some projects keep build.sh upstream, and copy it to $SRC/ during image
build.
This is a best effort attempt to parse the relevant copy command from
the Dockerfile.
Also add a main function to build_specified_commit to make it easier to
test.
> build_specified_commit: Handle build.sh which are part of upstream repo.

- projects/skia/build.sh
By default a cmake based build puts user provided flags at the beginning
of a compiler invocation, giving them lowest priority. This makes it
quite difficult to add the required -fno-sanitize=vptr flag since it
will be placed before -fsanitize=undefined in a SWIFTSHADER_UBSAN build.
To make this work will require upstream changes to SwiftShader's build.
However, it is not necessary to build SwiftShader with the undefined
behavior sanitizer in order to fuzz Skia for issues. (This is only
required for the memory sanitizer which fortunately works.) As a result,
build SwiftShader without the sanitizer in the Skia undefined sanitizer
fuzzer build.
> [skia] Build SwiftShader without UBSAN.

- docs/getting-started/new-project-guide/rust_lang.md
- docs/getting-started/new_project_guide.md
This is a follow-up to [this comment][1] which provides some intro docs
for how to get started quickly with a Rust project, explaining `cargo
fuzz` and some basic setup steps.
[1]: https://github.com/google/oss-fuzz/issues/3383#issuecomment-642137449
> Add Rust-specific setup instructions

- projects/skia/build.sh
Ninja monitors the load and not just the number of processes, so can
hopefully build faster without overloading.
> [skia] Build SwiftShader with Ninja.

- projects/mercurial/Dockerfile
- projects/mercurial/build.sh
There's some extra tidiness along for the ride here, but nothing I felt
merited a separate change.
> mercurial: move fuzzing build to Python 3

- projects/libplist/build.sh
The latest release of libplist has a library rename (added API version). This PR will make it work with the latest codebase. Please merge.
> libplist: Update for new release

- projects/xpdf/Dockerfile
- projects/xpdf/build.sh
- projects/xpdf/fuzz_pdfload.options
Due to longer release schedule of xpdf and the rather transient nature of the tool we disable leak checking as it is currently blocking the fuzzer.
> [xpdf] Disable leak check

- projects/h2o/project.yaml
The oss-fuzz documentation states that listing supported sanitizers in a project's yaml [is optional](https://google.github.io/oss-fuzz/getting-started/new-project-guide/#sanitizers). It appears that CIFuzz requires supported sanitizers to be included in this file ([ref](https://github.com/google/oss-fuzz/blob/26e8d7c7728096edf55a1fb6d0ecbc4b2dae6afa/infra/cifuzz/cifuzz.py#L508-L529)). I believe this causes the CIFuzz Github Action to fail for projects that have not listed support for address sanitizer explicitly in their respective project YAML.
This PR explicitly defines support for asan and ubsan with a goal of fixing h2o's CIFuzz build
> [h2o] Explicitly define sanitizer support

- docs/getting-started/continuous_integration.md
Just a follow-up to https://github.com/google/oss-fuzz/pull/3984 that
should address https://github.com/google/oss-fuzz/pull/3984#discussion_r440951881.
According to https://jekyllrb.com/docs/liquid/tags/#code-snippet-highlighting,
another option would be to add `render_with_liquid: false` in your front matter to
disable Liquid entirely for a particular document.
> docs: guard curly braces with {% raw %} .. {% endraw %}

- projects/tensorflow/build.sh
- projects/tensorflow/project.yaml
This should enable fuzzing with `ubsan` and `msan` as well as supporting all fuzzing engines.
This is possible after https://github.com/tensorflow/tensorflow/commit/950cffcd8deb881dcbfdf92f22c37eaa36f61e04 since now TensorFlow's `.bazelrc` has a config option to link against `libc++`.
While doing this PR, I'm also cleaning up the log by removing verbosity from the `rsync` command used to copy the files needed for coverage build.
> Enable more fuzzing for TensorFlow

- infra/cifuzz/cifuzz.py
- infra/cifuzz/cifuzz_test.py
Our sanitizer validation is hacky and isn't using pyyaml to actually
parse the project.yaml file. Temporarily work around #3996 by not
validating sanitizers if no sanitizers are specified in project.yaml.
> [cifuzz] Temporary fix for sanitizer validation.

- projects/opus/build.sh
Without this, a silk_memcpy call could resolve to __memcpy_chk, which does not have an msan intercept, leading to false use-of-uninitialized-value errors.
> [opus] Build with -D_FORTIFY_SOURCE=0 to avoid msan false positives

- projects/haproxy/project.yaml
This was asked for by the maintainers here https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=23653#c5 where the reasoning for having no restrictions are also found.
> [Haproxy] Updated settings in project yaml so there are no restrictions on who can view bugs.

- projects/zetasql/Dockerfile
- projects/zetasql/build.sh
- projects/zetasql/project.yaml
This PR includes basic files required for Fuzzing integration (Dockerfile, build.sh, and project.yaml). Current pipeline only contains a primitive fuzz target that tries to evaluate raw fuzzing input as a SQL expression. See pull request of the fuzz target [here](https://github.com/googleinterns/zetasql-fuzzing/pull/3)
This PR is subject to following changes before merging:
> [zetasql] Initial onboarding of ZetaSQL

- projects/giflib/Dockerfile
- projects/libpng-proto/Dockerfile
- projects/xerces-c/Dockerfile
Building the Docker image failed for the projects that use LPM. This is because the Dockerfile for those projects (libpng-proto, xerces-c, and giflib) do not grab the correct prereqs to compile LPM (such as liblzma-dev), so compiling LPM was failing.
I used the [LPM guide](https://github.com/google/libprotobuf-mutator) to find and add the appropriate prereqs. Building and fuzzing for those projects are now working again.
PTAL @sleevi @Dor1s
> Fixing Dockerfile for fuzzers that use LPM

- projects/oak/build.sh
- projects/oak/project.yaml
Temporarily disable fuzzing for [project Oak](https://github.com/project-oak/oak). 
We are currently making changes to the codebase, and migrating from C++ to Rust. Until we have fuzzing for Rust the fuzzing should be disabled. 
Ref https://github.com/project-oak/oak/issues/539.
> Temporarily disable fuzzing for project Oak

- infra/base-images/base-runner/coverage
- infra/base-images/base-runner/download_corpus
Reverts google/oss-fuzz#3903
This masks other failures e.g. if a fuzz target is so broken that it doesn't have a corpus backup available.
See more reasoning in https://github.com/google/oss-fuzz/issues/4039#issuecomment-651418789
The proposed solution to the original issue (#3902) is https://github.com/google/oss-fuzz/issues/4046
> Revert "Don't create empty corpus archive as it wont unpack."

- projects/envoy/build.sh
n1-highcpu-32 has 28.8 GB RAM. Choosing 16  per a thread on envoy slack:
> mklein  5:04 PM
I think it takes around 2GB per CPU to not OOM is my guess in the worst case
yeah I think you would have to limit jobs to around 2GB per CPU
for now
is my guess
maybe 1.5
There's also a Bazel option to estimate memory here: https://docs.bazel.build/versions/master/command-line-reference.html#flag--experimental_local_memory_estimate that I could use an alternative, but I'm not sure if that works well.
> [envoy] lower CPU more

- projects/syzkaller/Dockerfile
- projects/syzkaller/build.sh
The way to checkout the repo has changed.
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=21994
> syzkaller: update go get invocation

- projects/esp-v2/build.sh
Currently, coverage builds fail on step 3 with:
```
Step #3: + rsync -avLkR --include '*.h' --include '*.cc' --include '*.hpp' --include '*.cpp' --include '*.c' --include '*/' --exclude '*' /tmp /workspace/out/coverage
Step #3: sending incremental file list
Step #3: symlink has no referent: "/tmp/tmp.BOH6TAB62E/ares/include/ares_build.h"
Step #3: symlink has no referent: "/tmp/tmp.BOH6TAB62E/ares/include/ares_dns.h"
Step #3: symlink has no referent: "/tmp/tmp.BOH6TAB62E/ares/include/ares.h"
Step #3: symlink has no referent: "/tmp/tmp.BOH6TAB62E/ares/include/ares_rules.h"
Step #3: symlink has no referent: "/tmp/tmp.BOH6TAB62E/ares/include/ares_version.h"
Step #3: symlink has no referent: "/tmp/tmp.BOH6TAB62E/include/sha1.c"
Step #3: symlink has no referent: …
```
> [ESPv2] Attempt to fix coverage build

- projects/libspng/Dockerfile
CIFuzz is overwriting $SRC/libspng after executing the Dockerfile before running build.sh which means $SRC/libspng/zlib is lost:
https://github.com/randy408/libspng/runs/830380355#step:4:549
> [libspng] extract zlib to separate directory

- projects/qt/Dockerfile
Now that stable caught up with master, we
can use the clone from base-builder image.
> [qt] Don't clone AFL

- projects/envoy/Dockerfile
- projects/envoy/build.sh
Another iteration. 
Normal builds look good!
Coverage builds still OOM, so increasing per thread memory to 2 GB.
Testing that out revealed missing rsync, local coverage build now work for me all the way through.
> [envoy] fixup coverage build

- projects/wasmtime/build.sh
This will prevent build failures like
https://oss-fuzz-build-logs.storage.googleapis.com/log-5a0b58fe-4a35-46d5-b4d2-221905e7d208.txt
in the future.
> wasmtime: Create an empty corpus for newly-defined fuzz targets

- projects/ndpi/build.sh
cc @lucaderi @lnslbrty
Should fix oss-fuzz ndpi build failure
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=23752
Problem arises because there is now a binary `fuzz_ndpi_reader_with_main` which does not use the libFuzzer driver...
> excludes builds artifacts from ndpi project

- infra/base-images/base-msan-builder/patch_build.py
open() should not be called on symlinks.
Should fix https://github.com/google/oss-fuzz/issues/4003
> Don't traverse symlinks in patch_build.py

- infra/utils.py
Closes https://github.com/google/oss-fuzz/issues/4093
> CIFuzz: switch to systemd-detect-virt to detect docker

- infra/cifuzz/cifuzz_test.py
These were causing utils.get_fuzz_targets tests to fail.
> Fix infra tests.

- infra/utils.py
"check" is omitted intentionally there.
A follow-up to https://github.com/google/oss-fuzz/pull/4101
> utils: ignore subprocess-run-check

- projects/wasmtime/Dockerfile
- projects/wasmtime/build.sh
This commit expands the fuzzers run under the Wasmtime project to
include those in the https://github.com/bytecodealliance/wasm-tools
repository. This includes various parsing for utilities used by Wasmtime
itself but also generally useful for other Rust projects! The
maintainers of the wasm-tools repository are also all currently all on
the notification list for Wasmtime fuzz bugs as well.
> Add wasm-tools repository to wasmtime project

- infra/gcb/build_and_run_coverage.py
- infra/gcb/build_lib.py
- infra/gcb/build_project.py
-Added license headers
-Fixed all pylint errors
-Refactored get_build_steps() to just be passed the results of project_yaml file and workdir from dockerfile
-Pre requisites for project_yaml and dockerfile, to set defaults of project yaml file and retrieve workdir from dockerfile is done from main() now and the results are passed to get_build_steps
-build_and_run_coverage changed accordingly.
-Changed some imports to be compatible with both py2 and py3
-removed unused imports
-Remove unnecessary lines from build_and_run_coverage related to build.sh
@oliverchang 
> Refactoring gcb libraries for external use by Cloud functions

- infra/gcb/build_and_run_coverage.py
- infra/gcb/build_lib.py
- infra/gcb/build_project.py
Reverts google/oss-fuzz#4103
Please see https://github.com/google/oss-fuzz/issues/4116 for the failure details.
I'll be great to test this change on a project that does a variety of builds, e.g. `zlib` seems to be utilizing all available configurations and it's very small.
@kabeer27 in case you don't have the OSS-Fuzz builder key, you should be able to test the build scripts by commenting out `GoogleCredentials` and `cloudbuild` calls and just printing the build steps in the console to review manually that they look correctly (can even compare to the steps printed without the patch).
> Revert "Refactoring gcb libraries for external use by Cloud functions"

- projects/influxdb/Dockerfile
- projects/influxdb/build.sh
- projects/influxdb/project.yaml
- Updates project.yaml to specify libfuzzer as fuzzing engine
- Adds a basic Dockerfile
- Add a build.sh script that defines the compile_fuzzer function ~, but does not call it. (Fuzz tests still to be written and committed.)~
> Add initial influxdb integration

- projects/binutils/Dockerfile
- projects/binutils/build.sh
- projects/binutils/fuzz_demangle.c
Adding the binutils fuzzer from [security-research-pocs](https://github.com/google/security-research-pocs/blob/master/autofuzz/demangle_fuzzer.cc). Converted the fuzzer to C for the purposes of this project, as that is what the build file currently supports.
> [binutils] Add new fuzzer

- infra/cifuzz/cifuzz.py
- infra/cifuzz/cifuzz_test.py
Sanitizer validation is not needed and it is hacky code with
no proper yaml parsing. sanitizer attribute is properly
documented.
Fixes #3996.
> Remove sanitizer validation checks in CIFuzz,

- projects/envoy/build.sh
Build complains about deprecated warnings for C++17 when using inlined vector from absl
```
external/com_google_absl/absl/container/inlined_vector.h:246:3: note: in instantiation of member function 'absl::inlined_vector_internal::Storage<Envoy::Buffer::RawSlice, 16, 
[...]
Step #4: #  define _LIBCPP_DEPRECATED_IN_CXX17 _LIBCPP_DEPRECATED
```
Coverage also needs to map third_party/ code (which contains a copy of absl::StatusOr before release)
Tested with:
```
python infra/helper.py pull_images
python infra/helper.py build_fuzzers --sanitizer=coverage --clean envoy
```
> [envoy] fix coverage and c++ 17 issues

- projects/skia/BUILD.gn.diff
This leads to multiple definitions of everything defined in
SkSVGCanvas.cpp since it will be compiled into the api_svg_canvas target
directly as well as the Skia xml target.
> Remove SkSVGCanvas.cpp from api_svg_canvas.

- projects/skia/build.sh
The gold linker was forced then the system linker stopped linking the
Skia build. It seems that the gold linker is now running into issues, so
attempt to switch back.
> [skia] Stop using gold.

- projects/uriparser/uri_dissect_query_malloc_fuzzer.cc
There was an issue in uri_dissect_query_malloc_fuzzer where our destination buffer has a size of 0, resulting in a [null-dereference](https://oss-fuzz.com/testcase-detail/5085315342270464). To fix this, I've included a check to ensure we only use the second half of our fuzzer if the buffer will have positive size.
> [uriparser] Fix null dereference in uri_dissect_query_malloc_fuzzer

- projects/radon/Dockerfile
- projects/radon/build.sh
- projects/radon/project.yaml
This PR adds [RadonDB](https://github.com/radondb/radon), an open source, Cloud-native MySQL database for unlimited scalability and performance.
According to its maintainers, RadonDB is used by Qingcloud to provide production-ready distributed database-products to their customers. More info on this can be found [here](https://www.qingcloud.com/products/radondb/).
Qingcloud is a cloud computing provider in China with [~50 million USD (CNY 377 million) in sales in 2019](https://equalocean.com/analysis/2020041313880#:~:text=When%20QingCloud%20grew%20its%20sales,98%25%20increase%20compared%20with%202017.) and customers from [industries like finance, healthcare, manufacturing, government and energy](https://www.prnewswire.com/news-releases/cloud-computing-technology-leader-qingcloud-expands-int …
> [Radon] Added project

- projects/clamav/Dockerfile
- projects/clamav/build.sh
ClamAV recently removed autotools generated materials (configure,
Makefile.in, etc) from the git repo. This commit adds tools and calls
necessary to generate those files if autogen.sh is present.
> [clamav] Add optional autogen.sh step; fix build

- infra/build/functions/datastore_entities.py
- infra/build/functions/deploy.sh
- infra/build/functions/project_sync.py
- infra/build/functions/project_sync_test.py
- Add some more logging.
- Use GitHub client ID/secret rather than personal access token.
- Fix function deploy wrt "--project" argument.
> build: Project sync fixes.

- projects/monero/build.sh
- projects/monero/project.yaml
Monero
- fix typo ensuring the corpus zip file is created anew
- enable honggfuzz and afl
> Monero: fix corpus zip file creation anew; enable honggfuzz&afl

- projects/rnp/build.sh
- projects/rnp/project.yaml
Undefined sanitizer should now work, and the honggfuzz engine as well.
Upstream changes supported enabling these, and when I did so I
renamed one of the variables.
> Fuzzer fixes and improvements for rnp

- infra/gcb/requirements.txt
New builds status not ready to be migrated to yet, as that depends on all the builds being migrated first.
> Fix builds status requirements.txt

- projects/spanner_emulator/project.yaml
Two changes:
- Removing an email that no longer points to an active user.
- Removing MSAN as it is failing due to the MSAN + LPM incompatability (see issue 864)
> Removing no-longer valid email and updating sanitizer definitions

- projects/postgresql/project.yaml
This is to add my (Stephen Frost's) gmail.com account to the PostgreSQL
project to allow me to view the issues that are being opened by the fuzz
tool.
> Add gmail.com account to PostgreSQL project

- infra/build/functions/base_images.py
- infra/build/functions/datastore_entities.py
- infra/build/functions/deploy.sh
- infra/build/functions/request_build.py
- infra/build/functions/request_build_test.py
- infra/build/functions/request_coverage_build.py
- infra/build/functions/update_build_status.py
- infra/build/request_all_builds.sh
- infra/build/request_build.sh
- Remove base image project argument from deploy.sh. Deploy all
functions to the main oss-fuzz image.
- Reduce max instances of functions to 1 to avoid rate limiting issues.
- Fix missing ndb context initialization in request_build.py
- Fix incorrect tags in BuildHistory entities. "-" was doubled.
- Fix base build deployment with incorrect schedule variable.
- Add scripts for requesting builds locally.
> Many build infra fixes.

- infra/gcb/build_project.py
To prevent expiry of queued builds.
> Add queueTtl argument to cloud build request.

- projects/skia/build.sh
The number of link build steps in the Skia build is currently not
limited and may be leading to the current failures where the linker is
killed with a signal. This changes that to limit the number of
concurrent linker steps to the number of cpus available. If there
continue to be issues it may be necessary to implement a hard limit.
Bug: oss-fuzz:23438,oss-fuzz:24345
> [skia] Limit concurrent link steps.

- infra/build/functions/update_build_status.py
Check for valid statuses rather than only excluding the WORKING status.
There are other failure statuses that need to be accounted for (e.g.
EXPIRED).
> Fix build status update.

- projects/skia/build.sh
Reducing the number of concurrent link steps to the number of cpus does
not appear to have made much difference to the success of the Skia
project build. Limit the number of concurrent links to one in an attempt
to avoid running out of memory. If issues persist it is likely the bot
running this simply does not have enough memory to run the linker step.
This change is speculative since these builds have been working on the
CI bots and only failing on the oss-fuzz build.
Bug: oss-fuzz:23438,oss-fuzz:24345
> [skia] Further limit number of concurrent links.

- projects/bignum-fuzzer/project.yaml
- projects/mbedtls/project.yaml
Update the primary contact addresss and website in the Mbed TLS
project file.
Also update the Mbed TLS cc address in the bignum-fuzzer project
file.
Signed-off-by: Dan Handley <dan.handley@arm.com>
> Update Mbed TLS contact address and website

- projects/quic-go/project.yaml
[quic-go](https://github.com/lucas-clemente/quic-go/) is an implementation of the QUIC protocol (currently support IETF QUIC [working group draft-29](https://tools.ietf.org/html/draft-ietf-quic-transport-29)), including HTTP/3.
quic-go is used as the default transport in [IPFS](https://github.com/ipfs/go-ipfs/) and it powers HTTP/3 support in the [Caddy webserver](https://caddyserver.com/).
> add project quic-go

- projects/openexr/openexr_deepscanlines_fuzzer.cc
- projects/openexr/openexr_deeptiles_fuzzer.cc
- projects/openexr/openexr_exrenvmap_fuzzer.cc
- projects/openexr/openexr_exrheader_fuzzer.cc
The purpose of the fuzzer is to very that an exception is thrown, not to validate that the correct *type* of exception is thrown. That is the responsibility of the project's traditional test suite. Therefore, the exception type is inconsequential.
Signed-off-by: Cary Phillips <seabeepea@gmail.com>
> Catch all exceptions via (...) rather than by explicit type

- docs/reference/useful_links.md
@oliverchang is this fine to remove or should it be replaced with anything else?
> [docs] Remove link to the old builder (#3538).

- .dockerignore
- infra/cifuzz/actions/build_fuzzers/build_fuzzers_entrypoint.py
- infra/cifuzz/cifuzz-base/Dockerfile
- infra/cifuzz/cifuzz.py
The issue with 55d9a81 that caused it to be reverted by 3370f8f
was probably due to the build trigger on GCB being stale. I've
updated it so this commit should stick.
> Reland 55d9a81.

- projects/firefox/Dockerfile
- projects/firefox/build.sh
- projects/firefox/mozconfig.coverage
This greatly reduces the time required to rebuild the fuzzers locally.
> [firefox] Install dependencies in Dockerfile

- projects/nanopb/build.sh
This should improve fuzzing performance.
> [nanopb] Split fuzztest to separate test cases.

- projects/nanopb/build.sh
As noted in #4276, feed the seed corpus for all of the separate fuzzer test cases.
The nanopb reposity contains a copy of the corpus for the combined fuzzer, so it works as a good base also.
> [nanopb] Update seed corpus handling for separate test cases

- projects/fuzzing-puzzles/project.yaml
@robertswiecki looks like honggfuzz wasn't able to crack it, so this might be of interest to you
This is the target: https://github.com/llvm/llvm-project/blob/master/compiler-rt/test/fuzzer/MultipleConstraintsOnSmallInputTest.cpp
Here are some notes on how libFuzzer dealt with it: https://github.com/google/sanitizers/issues/964
libFuzzer on ClusterFuzz managed to crash it in 2-3 days. The conclusion was that corpus subset strategy did really help like a backtracking mechanism.
> [fuzzing-puzzles] Disable the project for now.

- projects/dav1d/Dockerfile
- projects/dav1d/build.sh
a meson change broke the build. The build directories holding the objects for the fuzzing binaries matched the patter used for copying the fuzzing binaries to the output dir.
> fix dav1d build

- projects/uwebsockets/Dockerfile
I was installing zlib from ubuntu.com and got msan false positives. Now zlib is cloned/built as part of building the fuzz targets.
> [uwebsockets] Don't install zlib from apt

- projects/boringssl/build.sh
The upstream LPM-based fuzzer changed its layout, so update the build
files to reflect this. This may make sense as a separate .a file in
the future to avoid these breaks.
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=24776
> [boringssl] Fix BoringSSL build break

- infra/build/functions/deploy.sh
- infra/build/functions/project_sync.py
The previous implementation of updating a scheduler was completely wrong.
Also upgrade runtime to python38 due to b/155215191.
> More project_sync fixes.

- projects/cryptofuzz/build.sh
I recently added bignum support to the wolfCrypt module. This uses the functions ```mp_gcd``` and ```mp_exch```. This PR builds wolfCrypt with those functions enabled by adding the ```--enable-keygen``` switch.
> [cryptofuzz] Enable wolfSSL keygen

- projects/libavif/avif_decode_fuzzer.cc
This is to add some coverage for the code in libavif's reformat.c.
Context: https://bugs.chromium.org/p/chromium/issues/detail?id=1113226
> [libavif] add bidirectional RGB conversion paths to the fuzzer

- projects/bind9/project.yaml
//cc @oerdnj
please see the failure with AFL here: https://github.com/google/oss-fuzz/runs/977415892?check_suite_focus=true
you should be able to reproduce it locally by running:
```
Running command: python /home/runner/work/oss-fuzz/oss-fuzz/infra/helper.py build_fuzzers bind9 --engine afl --sanitizer address --architecture x86_64
Running command: python /home/runner/work/oss-fuzz/oss-fuzz/infra/helper.py check_build bind9 --engine afl --sanitizer address --architecture x86_64
```
> [bind9] Temporarily disable AFL fuzzing engine.

- projects/cras/Dockerfile
- projects/cras/build.sh
- Fix build error by installing 1.8.x gtest and using `make install` to
install gtest pc file for pkg-config
- Build and add new fuzzer `cras_hfp_slc`
BUG=oss-fuzz:24744
> [CRAS] Fix build error and build new fuzzer

- projects/libavif/avif_decode_fuzzer.cc
This should bring down the time of a fuzz by _quite_ a bit without sacrificing much coverage.
Context:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=24838
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=24836
> [libavif] Cut down on post-decode combinations to avoid timeouts

- projects/bind9/Dockerfile
- projects/bind9/build.sh
This is the slight update of the bind9 fuzzing project:
* Uses main/HEAD branch (we merged the necessary changes on our side)
* Uses upstream-integrated support for ossfuzz
> [bind9] Adjust the Dockerfile and build.sh for main branch

- projects/systemd/project.yaml
- projects/util-linux/project.yaml
Hopefully this should prevent OSS-Fuzz from reporting bugs that
have alread been fixed. Though I'm not sure how stable it's going to be
given that https://github.com/google/oss-fuzz/issues/4083 is still
open. Let's see.
> [systemd,util-linux] build more often

- projects/bind9/project.yaml
+ change the primary contact to the BIND 9 developers group alias,
instead of security-officer
> [bind9] Adjust the emails, so everybody on the team has access

- infra/base-images/base-clang/checkout_build_install_llvm.sh
Since https://github.com/google/oss-fuzz/pull/4311 succeeded, now it's time to do some binary search in production!
> [infra] Use 16 threads when building LLVM (#4270).

- projects/nodejs/Dockerfile
- projects/nodejs/build.sh
- projects/nodejs/project.yaml
The building process of nodejs fuzzers has been upstream (CR https://github.com/nodejs/node/pull/34761), in particular we now have a `--with-ossfuzz` configuration in Nodejs. 
This PR adjusts the oss-fuzz build for that.
> [nodejs] Simplify build process as most work is now upstreamed.

- projects/quic-go/Dockerfile
- projects/quic-go/build.sh
[qpack](https://tools.ietf.org/html/draft-ietf-quic-qpack-16) is the protocol that HTTP/3 uses to compress request and response headers.
[marten-seemann/qpack](https://github.com/marten-seemann/qpack) is the library that powers qpack support in quic-go.
> [quic-go] add qpack

- projects/quic-go/build.sh
https://github.com/lucas-clemente/quic-go/pull/2713 added a fuzzer for testing the parsing and the serialization of [QUIC transport parameters](https://tools.ietf.org/html/draft-ietf-quic-transport-29#section-7.4).
This PR adds the fuzz target to quic-go's build script.
> [quic-go] add a fuzz target for QUIC transport parameters

- infra/base-images/base-clang/checkout_build_install_llvm.sh
As discussed in https://github.com/google/fuzzbench/issues/646
LLVMgold.so is already built by default with the clang target, however the binutil includes must be installed.
This requirement is well hidden in the LLVM documenation ...
> Compile + install LLVMgold.so so -flto works

- projects/ghostscript/project.yaml
This change adds me (Kalvin) to the list of contributors allowed
to view Ghostscript issues on OSS-Fuzz.
> projects/ghostscript: add contributor

- projects/openexr/openexr_scanlines_fuzzer.cc
`return` was exiting `readMulti` without cleaning up, causing a memory leak (e.g. https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=25148)
> [openexr] fix memleak in scanlinefuzzer with wide images

- infra/base-images/base-runner/reproduce
- infra/base-images/base-runner/run_fuzzer
```
$ python infra/helper.py reproduce lz4 decompress_fuzzer ~/Downloads/clusterfuzz-testcase-minimized-decompress_fuzzer-5720493764378624
Running: docker run --rm --privileged -i -v /usr/local/google/home/mmoroz/projects/oss-fuzz/build/out/lz4:/out -v /usr/local/google/home/mmoroz/Downloads/clusterfuzz-testcase-minimized-decompress_fuzzer-5720493764378624:/testcase -t gcr.io/oss-fuzz-base/base-runner reproduce decompress_fuzzer -runs=100
+ FUZZER=decompress_fuzzer
+ shift
+ '[' '!' -v TESTCASE ']'
+ TESTCASE=/testcase
+ '[' '!' -f /testcase ']'
+ export RUN_FUZZER_MODE=interactive
+ RUN_FUZZER_MODE=interactive
+ export FUZZING_ENGINE=libfuzzer
+ FUZZING_ENGINE=libfuzzer
+ export DO_NOT_USE_CORPUS=1
+ DO_NOT_USE_CORPUS=1
+ run_fuzzer decompress_fuzzer -runs=100 /testcase …
```
> [infra] Fix reproduce command invoking run_fuzzer for a single testcase (#4338).

- projects/quic-go/build.sh
1. Add a fuzz target for [address validation token](https://tools.ietf.org/html/draft-ietf-quic-transport-29#section-8) parsing / encryption.
2. Generate seed corpora in the build script.
> [quic-go] add fuzz targets for tokens, generate seed corpora

- projects/graphicsfuzz-spirv/project.yaml
It's broken now because ClusterFuzz's blackbox fuzzer model can't
support it.
> [graphicsfuzz-spirv] Disable project.

- projects/openexr/openexr_scanlines_fuzzer.cc
(resubmitting under personal github account)
As in #4356, wide images were causing an early return which bypassed the delete.
Refactoring out the new from readSingle should fix the issue.
> [openexr] fix memleak in readSingle with wide images

- projects/pffft/Dockerfile
This patch fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=25071.
> Fix pffft build

- projects/orbit/project.yaml
Adding basic `project.yaml` file to request project acceptance.
Orbit (https://github.com/google/orbit) is an open-source CPU profiler
with special integration for the Stadia platform.
> [orbit] Initial integration

- projects/php/build.sh
This adds an end-to-end fuzzer that executes arbitrary PHP code on a step-limited VM. I hope I don't drown in the number of issues this finds...
I'm also enabling debug assertions for the fuzzing builds. The execute fuzzer needs this because PHP may intentionally "leak" in non-assert builds. I think having the assertions would also be useful in general.
> [php] Add execute fuzzer

- projects/eigen/Dockerfile
This patch fixes build failure of `eigen`: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=25063
`Eigen` is now on GitLab.com as a git repository: http://eigen.tuxfamily.org/index.php?title=News:Eigen_is_now_on_GitLab.com
> FIX: build failure of eigen

- projects/envoy/build.sh
Fix envoy build. A recent bump in our absl library along with changing to C++17 caused a build failure.
Tested this locally with undefined sanitizer, hoping to wait for address/undefined to pass on CI.
> [envoy] fix envoy build

- projects/libsndfile/Dockerfile
- projects/libsndfile/build.sh
- projects/libsndfile/project.yaml
This adds libsndfile support to ossfuzz.
libsndfile is a C library for reading and writing sound files containing sampled audio data. OSS-Fuzz support was requested in https://github.com/erikd/libsndfile/issues/476.
> [libsndfile] Add libsndfile support

- projects/rnp/Dockerfile
- projects/rnp/build.sh
This PR adds support for more fuzzers, added recently to rnp codebase.
Also it updates build script with following changes:
- remove some unneeded verbosity
- disable building of some modules in Botan
- stick to the $SRC folder when running commands
- detect fuzzers automatically instead of using hardcoded list
- use all available cores during make
@tomrittervg Could you please take a look whether it's ok?
Also I removed fuzzers building from the Botan, was it really needed?
> [rnp] add more fuzzers and update build script.

- infra/presubmit.py
- projects/graphicsfuzz-spirv/project.yaml
- projects/jsc/project.yaml
- projects/quickjs/project.yaml
- projects/spidermonkey/project.yaml
This is needed for CF to determine whether or not to allocate the
project on a higher end bot to run the blackbox fuzzer.
Previously this was keyed on the "none" entry under fuzzing_engines,
which wasn't very descriptive. This change also lets us do both blackbox
and greybox fuzzing in the same project using the engine (i.e. libFuzzer)
build, which wasn't possible before as the "none" engine does not link with
any engines.
The "none" entries and any other dependencies can be removed in a future PR,
to avoid complications with migration.
> Add a blackbox field to project.yaml

- projects/quic-go/build.sh
https://github.com/lucas-clemente/quic-go/pull/2733 added a fuzzing target for the QUIC handshake. This will be a very important fuzzing target, as it fuzzes both the TLS library in use as well as its integration into quic-go, both of which contain a fair amount of complexity.
> [quic-go] add fuzzing for the handshake

- projects/orbit/Dockerfile
- projects/orbit/build.sh
I added the wrong header in the last commit. This will be fixed by this
commit.
Furthermore it seems to run as a different user in ClusterFuzz. So this
should be fixed as well.
> [orbit] Fix build issues

- projects/libyuv/project.yaml
Adding Microsoft email as vendor_ccs to view libyuv bugs
> Adding Microsoft email to view libyuv bugs

- projects/mdbtools/project.yaml
I recently took over maintenance of MDB Tools, a open-source C library for reading Microsoft Access files. The library is packaged in Debian, Homebrew, and other distributions, and I would like to see it included in OSS-Fuzz.
The (outdated) MDB Tools home page can be found here:
http://mdbtools.sourceforge.net
This page will soon redirect to the GitHub project home, which is here:
https://github.com/mdbtools/mdbtools
I maintain a couple of other projects already in OSS Fuzz (libxls and readstat) and I would like to see this library enjoy the same security benefits. Thank you for your consideration and ongoing support.
> Add MDB Tools project

- projects/rnp/Dockerfile
- projects/rnp/build.sh
C++ fuzzers are linked without rpath, so chrpath wasn't able to change it, while patchelf does.
> [rnp] Use patchelf instead of chrpath to add/change RPATH for fuzzers.

- projects/opencv/build.sh
It is not part of the oss-fuzz docker image anymore as it has been removed from Debian.
> Remove libjasper from OpenCV dependencies

- projects/orbit/project.yaml
This CL adds more team members to `auto_css` for getting access to the
ClusterFuzz dashboard and the bugtracker.
> [orbit] Grant more team members access to oss-fuzz

- infra/base-images/base-clang/checkout_build_install_llvm.sh
I've tested it locally and everything seems to work now (see https://github.com/google/oss-fuzz/issues/4348#issuecomment-689138828). Chromium coverage bots have also recovered.
> [infra] Re-enable clang/LLVM auto-updating (#4348).

- projects/pugixml/Dockerfile
- projects/pugixml/build.sh
- projects/pugixml/project.yaml
Pugixml is a light-weight C++ XML processing library and is extremely fast. It has been developed since 2006 and is still active. You can get it from package managers for most Linux distributions and the library is also available for Windows and OSx. 
You can ready more about it on its website: https://pugixml.org/
The project has 2.3K stars on Github and according to the maintainers on Github pugixml "is used by a lot of projects, both open-source and proprietary, for performance and easy-to-use interface."
The core maintainer @zeux is happy to have the projected integrated.
> [Pugixml] Initial integration

- projects/gstreamer/Dockerfile
GStreamer requires a newer verison of meson (>= 0.54) to build now.
Fixed build error:
meson.build:1:0: ERROR: Meson version is 0.53.2 but project requires >= 0.54
> [gstreamer] update meson version in docker image

- projects/c-ares/build.sh
- projects/c-ares/project.yaml
Upstream https://github.com/c-ares/c-ares/pull/349 re-organized the
c-ares source tree, so update build.sh to find things in their new
places.
Also remove the CFLAGS workaround, which seems to be no longer needed
(and also seems to result in a malformed test/Makefile being generated).
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=25566
> [c-ares] Update build script for upstream changes

- projects/inchi/Dockerfile
- projects/inchi/build.sh
- projects/inchi/inchi_input_fuzzer.c
- projects/inchi/inchi_input_fuzzer.cc
- projects/inchi/project.yaml
Initial integration for [InChI](https://www.inchi-trust.org/), using [this](https://github.com/google/security-research-pocs/blob/master/autofuzz/inchi_fuzzer.cc) fuzzer.
@inferno-chromium any idea who we can add as the primary contact? I couldn't find contact information for the InChI development team online.
@alsophian @spq requesting review.
> [inchi] Initial Integration

- projects/openexr/openexr_deepscanlines_fuzzer.cc
- projects/openexr/openexr_deeptiles_fuzzer.cc
- projects/openexr/openexr_scanlines_fuzzer.cc
Some tests for OpenEXR have a 'readSingle' followed by a 'readMulti', but the stream pointer is not reset between reads, so readMulti tries to read  OpenEXR data directly after the data read by readSingle. Presumably the intention is that the stream only contains a single OpenEXR file, which should be read by readSingle, then again by readMulti. Re-initializing the input stream between calls should achieve that.
> [openexr] rewind streams between readSingle and readMulti

- projects/cryptofuzz/Dockerfile
- projects/cryptofuzz/build.sh
- projects/cryptofuzz/xxd.c
These are popular JavaScript bignum libraries.
Execution of JavaScript code happens through QuickJS.
This commit adds xxd.c to the project directory because
it's needed to build modules and the distribution doesn't
provide it.
> [cryptofuzz] Add bn.js and bignumber.js

- projects/cryptofuzz/project.yaml
Subscribe Mbed TLS maintainers to cryptofuzz reports [at the invitation of Guido Vranken](https://github.com/ARMmbed/mbedtls/issues/3665#issuecomment-691302875-).
> [cryptofuzz] Subscribe mbed-tls-security

- projects/openexr/openexr_scanlines_fuzzer.cc
Address timeout in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=25677: speed up read by skipping scanlines. Also extend `readMulti()` to read all channels present in file, as well as RGBA.
> [openexr] speed up scanline reading, read all channels in readMulti

- infra/bisector.py
But do this after computing repo_url as that's still useful information.
> bisector: early exit when old_commit == new_commit.

- projects/openexr/openexr_scanlines_fuzzer.cc
copy/paste error causes segfaults when 'dataWindow.min.x' is negative
(temporary fix while fuzzer integration continues)
> [openexr] fix reading extra EXR channels in readMulti

- projects/libressl/Dockerfile
- projects/libressl/build.sh
- projects/libressl/project.yaml
The LibreSSL team and I have decided to
- Integrate a standalone version of Cryptofuzz into the OSS-Fuzz libressl project
- Add me to the CC list of this project
Reasons for this are:
- Unlike https://github.com/guidovranken/cryptofuzz , which sends a report for every bug in any library to each of the subscribers, this will only send a report if there is a bug in LibreSSL, so no "false positives"
- While https://github.com/guidovranken/cryptofuzz has to divide its CPU time between 10+ libraries, this standalone integration can focus entirely on LibreSSL, probably resulting in a more code coverage (and likelihood of finding bugs)
I will not apply to receive any integration reward for this PR or subsequent maintenance.
Can someone from LibreSSL please confirm this to the OSS-Fuzz team?
> [libressl] Add standalone Cryptofuzz instance

- projects/libvips/Dockerfile
- projects/libvips/build.sh
> [libvips] Add aom/libheif as dependencies to enable AVIF fuzzing

- projects/skia/Dockerfile
Fix found from https://stackoverflow.com/questions/3373995/usr-bin-ld-cannot-find-lz
> [skia] Remove pinned swiftshader hack

- projects/wolfssl/Dockerfile
- projects/wolfssl/build.sh
- projects/wolfssl/project.yaml
This adds the targets residing in https://github.com/guidovranken/wolf-ssl-ssh-fuzzers
The following targets are built:
```
fuzzer-wolfssh-client
fuzzer-wolfssh-client-randomize
fuzzer-wolfssh-server
fuzzer-wolfssh-server-randomize
fuzzer-wolfssl-client
fuzzer-wolfssl-client-randomize
fuzzer-wolfssl-crl
fuzzer-wolfssl-misc
fuzzer-wolfssl-ocsp
fuzzer-wolfssl-rsa
fuzzer-wolfssl-server
fuzzer-wolfssl-server-randomize
fuzzer-wolfssl-srp
fuzzer-wolfssl-x509
```
The `*-randomize` client/server targets emulate allocation and IO failures, whereas those without `*-randomize` do not. This is a trade-off between rate of code coverage increase and catching corner cases. Both have their merits, hence two targets for each client and server.
These scripts will be fetched and executed during the build: …
> [wolfssl] Add more wolfSSL and wolfSSH fuzzers

- projects/sound-open-firmware/project.yaml
Sound open firmware is audio firmware for Intel and NXP systems and
therefore is safety critical for systems everywhere
Fixes https://github.com/thesofproject/sof/issues/3388
> SOF: add project yaml

- projects/usrsctp/Dockerfile
@weinrank's fork was being used while the fuzzers were being developed, however now that they are more stable it makes sense to switch to the main repo.
> [usrsctp] Switch to main sctplab repository.

- projects/proxygen/Dockerfile
proxygen recently switched to building with -std=c++17 
gperf < 3.1 emits code with the `register` keyword that has been retired
> [proxygen] require gperf 3.1

- infra/base-images/base-builder/Dockerfile
- projects/suricata/build.sh
- projects/suricata/project.yaml
Will work when https://github.com/OISF/suricata/pull/5422 gets merged
> Enables MSAN for Suricata

- projects/envoy/build.sh
- projects/envoy/project.yaml
Envoy's coverage works locally for me (pull_images, build --sanitizer coverage), but fails upstream. Provision more memory as a fix.
Also remove interns/old hosts
> [envoy] fix envoy coverage

- projects/cryptofuzz/Dockerfile
- projects/cryptofuzz/build.sh
[crypto-js](https://github.com/brix/crypto-js) is a widely used (10K+ GH stars, 4K+ first-grade reverse NPM dependencies) JavaScript cryptographic library.
> [cryptofuzz] Add crypto-js

- docs/advanced-topics/reproducing.md
The change was proposed by @pauldreik in https://github.com/google/oss-fuzz/issues/4497#issuecomment-703075579
> [docs] Reproducing: clarify that reproduce command works only with libfuzzer (#4497).

- projects/openexr/build.sh
OpenEXR master now has its own integrated tester, [openexr_exrcheck_fuzzer.cc](https://github.com/AcademySoftwareFoundation/openexr/tree/master/OpenEXR/IlmImfFuzzTest/oss-fuzz). It also compiles a binary, [exrcheck](https://github.com/AcademySoftwareFoundation/openexr/tree/master/OpenEXR/exrcheck), that should help to debug issues without needing the oss-fuzz framework.
This changes build.sh to build that the integrated tester as well the existing ones. As exrcheck is intended to be a fairly complete single test, so in theory the other tests could be removed
> [openexr] add support for integrated openexr_exrcheck_fuzzer

- projects/libavif/avif_decode_fuzzer.cc
avifDecoderSetIOMemory() has been changed to take the buffer data
pointer and buffer size as input parameters.
Fix https://crbug.com/oss-fuzz/26235.
> Update to new prototype of avifDecoderSetIOMemory

- infra/cifuzz/fuzz_target.py
- infra/cifuzz/fuzz_target_test.py
Skia has seen some handled connection reset errors.
When we see these when downloading old OSS-Fuzz retry downloading since error is likely transient.
If retrying fails, simply return since this error isn't a showstopper.
Fixes #44477
CC @kjlubick
> [CIFuzz] Retry HTTP requests on certain errors

- projects/rust-regex/Dockerfile
- projects/rust-regex/build.sh
- projects/rust-regex/project.yaml
Cross-referencing [PR](https://github.com/rust-lang/regex/pull/679) 
@BurntSushi is one of the maintainers of rust-lang Regex and his email is in the project.yaml. 
The repository has more than 19 million downloads [here](https://crates.io/crates/regex) and more than 2000 projects depend on it shown [here](https://crates.io/crates/regex/reverse_dependencies)  
The library is in the top 15 most downloaded Rust projects [here](https://crates.io/crates?sort=downloads) 
Waiting for the merge upstream.
> Added the rust-lang regex project.

- infra/base-images/base-sanitizer-libs-builder/packages/openssl.py
Python 3 SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers.
This PR required an alarming number of changes just to add a single `o` from `0755` --> `0o755`.
> openssl.py: SyntaxError leading zeros in decimal integer literals

- infra/base-images/base-sanitizer-libs-builder/packages/nettle.py
Python 3 SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers.
This PR required an alarming number of changes just to add a single `o` from `0755` --> `0o755`.
> nettle.py: SyntaxError leading zeros in decimal integer literals

- infra/base-images/base-sanitizer-libs-builder/packages/nettle.py
Reverts google/oss-fuzz#4522
We should take a closer look at the original change before landing this. I didn't realize that this code wasn't tested by CI when merging. We can reland after Oliver has a chance to review.
> Revert "nettle.py: SyntaxError leading zeros in decimal integer literals"

- infra/base-images/base-sanitizer-libs-builder/packages/openssl.py
Reverts google/oss-fuzz#4523
We should take a closer look at the original change before landing this. I didn't realize that this code wasn't tested by CI when merging. We can reland after Oliver has a chance to review.
> Revert "openssl.py: SyntaxError leading zeros in decimal integer literals"

- projects/cpp-httplib/project.yaml
Hey, @inferno-chromium  @yhirose 
Added two email ids to gain access to oss-fuzz build interface.
> [yhirose/cpp-httplib] Add email ids to get build visibility. 

- projects/openvswitch/project.yaml
William and Ilya are both upstream maintainers of Open vSwitch, as one
can see from:
https://github.com/openvswitch/ovs/blob/master/MAINTAINERS.rst
They have both expressed interest in getting early access to allow
them to fix problems before public release.
> [openvswitch] Add William Tu and Ilya Maximets to autoccs list.

- projects/libsndfile/Dockerfile
The libsndfile repo got moved to https://github.com/libsndfile/libsndfile. Make the Dockerfile reflect that.
> Switch libsndfile repository to the updated repository

- infra/cifuzz/cifuzz.py
- infra/cifuzz/cifuzz_test.py
- infra/cifuzz/fuzz_target.py
- infra/cifuzz/fuzz_target_test.py
This is wrong because the output can be arbitrary. Instead change
code that deals with the output to deal with bytes. The testcase,
which is derived from the output can be decoded as UTF-8 since it
will be a unix path.
Fixes https://github.com/google/oss-fuzz/issues/4526
> [CIFuzz] Don't assume fuzzer output is ASCII

- projects/qemu/Dockerfile
QEMU builds are currently broken.
As of QEMU's 09e93326e4 ("build: replace ninjatool with ninja"), QEMU
now requires ninja instead of ninjatool for builds.
> qemu: add ninja to the build image

- projects/harfbuzz/project.yaml
I am responsible for rolling HarfBuzz into Chromium. I would like
to stay on top of oss-fuzz issues for HarfBuzz as they are reported.
> Add myself as auto CC for HarfBuzz

- projects/libass/Dockerfile
- projects/libass/build.sh
libass made HarfBuzz a required dependency the other day, which broke its OSS-Fuzz build. This fixes it.
Building libass with HarfBuzz also ensures more libass code is covered with the fuzzing.
The system package of HarfBuzz cannot be used as it’s too old on Ubuntu 16.04, which OSS-Fuzz [seems to use](https://github.com/google/oss-fuzz/blob/master@{2020-10-22}/infra/base-images/base-image/Dockerfile#L19). The HarfBuzz build code is based on the OSS-Fuzz module for HarfBuzz itself. I have no idea why that module defines `HB_NO_VISIBILITY`, but I figured it might be safer to omit it when building it as a library dependency for another library.
> [libass] Build with HarfBuzz

- projects/envoy/build.sh
Envoy builds have failed for two reasons. 
(1) libc++ linkage here and 
(2) an upstream change compiling WASM with clang at head required a change to ignore a compiler error (https://github.com/envoyproxy/envoy/pull/13765).
They are orthogonal, so builds won't succeed until both these PRs are merged.
> [envoy] add libc++

- projects/esp-v2/build.sh
- projects/esp-v2/project.yaml
- ESPv2 builds have been failing with OOM since we updated our envoy dependency. Example error is below. Copy relevant portions from Envoy's build script to workaround this issue.
- Fix ubsan and coverage build by moving a `--copt` to only be defined in address builds.
- Update primary contact for the project due to a change in team members.
```
Step #13: (11:02:55) [3,248 / 3,318] Compiling external/envoy/test/mocks/router/mocks.cc; 2034s linux-sandbox ... (32 actions running)
Step #13: 
Step #13: Server terminated abruptly (error code: 14, error message: 'Socket closed', log file: '/builder/home/.cache/bazel/_bazel_root/28d323c1ffc0c0ec503bc89d22bdf549/server/jvm.out')
Step #13: 
Step #13: rules_foreign_cc: Cleaning temp directoriesrules_foreign_cc: Cleaning temp …
```
> [espv2] Fix build failures due to OOM

- projects/nettle/Dockerfile
- projects/nettle/build.sh
- projects/nettle/project.yaml
This is an isolated instance of Cryptofuzz fuzzing Nettle against Botan.
Reasons for not adding the maintainer to the existing Cryptofuzz project:
- he wants to receive no irrelevant bug reports (eg. bugs in other libraries than Nettle)
- he wants to test two versions of the library (requires building two separate targets)
By the maintainer's request, this project builds two targets:
- cryptofuzz-nettle-with-libgmp: Nettle using libgmp
- cryptofuzz-nettle-with-mini-gmp: Nettle using its internal mini gmp library
> [nettle] Add project

- projects/ecc-diff-fuzzer/Dockerfile
- projects/ecc-diff-fuzzer/build.sh
by using a more recent npm version
This should fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=26286
With this patch, I get `npm -v 6.14.8` when before I had `npm  v3.5.2`
> Fix ecc-diff-fuzzer build

- projects/ffmpeg/Dockerfile
Fixes build failure after github.com/01org/libva disappeared/moved
> [FFmpeg] update git link to libva

- projects/skia/build.sh
This should fix the build errors and make CI fuzz work faster because we use beefier machines than those that GitHub checks uses.
> [skia] Fix MSAN build and remove link limit for CIFuzz

- projects/freetype2/Dockerfile
The upstream build of the fuzzer currently builds freetype --without-zlib
and --without-png so these are not needed. In addition, because of the
way these dependencies are used they must be built with the sanitizer in
order to detect interesting issues like CVE-2020-15999, where FreeType
may call into libpng incorrectly but it is libpng which actually does
the reads and writes. This has been proposed upstream at
https://github.com/freetype/freetype2-testing/pull/86 which uses
prefixes to ensure that the system symbols are never used, but it would
be beneficial to not have them available at all.
> [freetype] Remove zlib and libpng dev packages.

- projects/suricata/build.sh
Bash magic transforms
```
=====Supported keywords=====
- sid
- priority
- rev
- classtype
...
```
into 
```
"sid"
"priority"
"rev"
"classtype"
```
> Adds one dictionary for suricata

- projects/libssh2/Dockerfile
Point the Dockerfile at the correct place now
> Move libssh2 to point at the correct repository

- projects/suricata/Dockerfile
- projects/suricata/build.sh
CIFuzz integration for Suricata failed at first cf
https://github.com/OISF/suricata/pull/5538
This is because suricata uses embedded libhtp
and cifuzz.py removes the whole suricata directory to replace it with the one from the PR cf
```
bash_command = 'rm -rf {0} && cp -r {1} {2} && compile'.format(
os.path.join(src_in_project_builder, project_repo_name, '*'),
os.path.join(git_workspace, project_repo_name), src_in_project_builder)
```
Workaround is to clone libhtp in another directory, and move it in suricata directory during the build
> Compatible build for Suricata with CIFuzz

- infra/base-images/base-runner/coverage
As per @Dor1s, some projects had sources outside of $SRC, so this is not a good workaround.
Reverts google/oss-fuzz#4610
> Revert "Use symlink instead of broken -path-equivalence"

- projects/tmux/Dockerfile
- projects/tmux/build.sh
- projects/tmux/project.yaml
Depends on: tmux/tmux#2448.
tmux is a terminal multiplexer widely used by engineers. It ranked as [2602](https://qa.debian.org/popcon.php?package=tmux) across all debian packages by number of installs. It is even [used](https://cloud.google.com/shell/docs/configuring-cloud-shell#tmux_support) in Google Cloud Shell by default.
The essential part of tmux is escape sequence parser. It accepts input from arbitrary sources, like remote ssh stream or docker sandbox, and converts them into formatted symbol grid. This could be dangerous since the same process handles user interaction and so it has full capabilities.
The work on this fuzzer has already helped to uncover [CVE-2020-27347](https://seclists.org/oss-sec/2020/q4/100) ([OpenBSD 6.8 errata …
> [tmux] Initial integration

- projects/capstone/project.yaml
- projects/keystone/project.yaml
- projects/unicorn/project.yaml
Follow-up to #4451, I was just working on a couple reports for https://github.com/aquynh/capstone
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=14912 fixed by aquynh/capstone#1684 & aquynh/capstone#1685
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=22236 potential fix by aquynh/capstone#1687 & aquynh/capstone#1688
But I couldn't access the report because of permission denied:
> Detailed Report: https://oss-fuzz.com/testcase?key=5666610666012672
Adding to capstone but also related keystone/unicorn that I've been looking at.
I don't know what are the restrictions to be added to projects, so I'm trying this pull request.
Using my GSuite account (stalkr@stalkr.net), let's see if it works otherwise I also have a Gmail account (@gmail.com).
My Google CLA is up to date. …
> capstone/keystone/unicorn: add to auto_ccs

- projects/cryptofuzz/project.yaml
Temporarily disable the i386 build
The i386 fuzzers contain too much code now and this frequently causes false positives. Some examples:
https://oss-fuzz.com/testcase-detail/5448129780121600
https://oss-fuzz.com/testcase-detail/4775822470414336
https://oss-fuzz.com/testcase-detail/5766529993670656
https://oss-fuzz.com/testcase-detail/6016977623318528
https://oss-fuzz.com/testcase-detail/5736577529282560
https://oss-fuzz.com/testcase-detail/5638214188269568
I need to split this up into multiple binaries, but I need some time for that.
The x64 fuzzers still work fine despite the amount of code they run.
> [cryptofuzz] Disable i386 build

- projects/lz4/project.yaml
There are 3 open LZ4 i386 issues. Each claims to be reliably reproducible. We've never been able to reproduce any of them. At this point it is just causing noise. So we want to disable i386 fuzzing until these issues have been sorted out.
OSS-Fuzz claims the latest tested revision is https://github.com/lz4/lz4/commit/664427aa8f6808411a2c04f003a9b364bdebe578 from 5 days ago. Does that mean it was able to successfully reproduce then? If so, why can't I reproduce with docker locally on the same commit?
> [lz4] Disable i386 fuzzing

- projects/go-ethereum/project.yaml
The email address for one of our maintainers was an alias, which doesn't seem to work for signing in to oss-fuzz.
> project/go-ethereum: use canon address instead of vanity-alias

- projects/teleport/Dockerfile
- projects/teleport/build.sh
- projects/teleport/project.yaml
This PR adds initial integration of [teleport](https://github.com/gravitational/teleport).
The following maintainers have been added to receive potential bug reports: @awly. And I am just tagging @webvictim and @benarent as well to keep you in the loop.
A selection of teleports users can be found [here](https://gravitational.com/teleport#customerlist).
**A few notes for the teleport maintainers:**
1. Upon integration, you will get access to the dashboard to monitor performance of the fuzzers. If bugs are found, you will receive emails with links to detailed bug reports.
2. I have added myself as cc for the bug reports. This means that I will have access to all reports for bugs and vulnerabilities found by the fuzzers through oss-fuzz. The reason I have added myself is to keep an eye on …
> [teleport] Initial integration

- projects/zeek/build.sh
I don't know if this PR is actually the best fix, but the underlying issue was that the `cp -L` of this:
https://github.com/google/oss-fuzz/blob/a7a973458c9fae6b1ea600810de528069654245a/infra/base-images/base-builder/compile#L95
will omit this symlink in our source tree:
https://github.com/zeek/zeek/blob/a6a4b976ecc59ed7a5ce1b8dc8c2a30568043364/src/zeek
and we have various `#include`s that resolve header files via that symlink resulting in a broken oss-fuzz coverage build with example error output shown here:
https://github.com/zeek/zeek/issues/1260
By changing our build script to preemptively do a `cp -r` of the source tree, the symlink seemed to be preserved and coverage build worked again when I tested locally.
> projects/zeek: update build script to fix coverage build

- projects/nanopb/build.sh
As suggested by rewards panel:
> Move the build.sh script to the upstream repo, so that the build
script in OSS-Fuzz can be a one liner and not depend on the project's
specific details (e.g. fuzz targets names, or relative paths -- all of
that can be stored in the upstream repo).
This should make future maintenance easier by not requiring pull requests to oss-fuzz repository when fuzz targets change.
> [nanopb] Move build script to project repository

- projects/snappy/Dockerfile
- projects/snappy/build.sh
- projects/snappy/project.yaml
This PR adds initial integration of [snappy](https://github.com/google/snappy).
For maintainers of Snappy:
@pwnall
Following integration, oss-fuzz will run Snappys fuzzers continuously. If a bug is discovered, all maintainers get notified by email with a link to a detailed bug report.
To complete this integration, the email addresses of maintainers to receive bug reports are to be added to the contact list, and for that I kindly ask you to write those email addresses in this PR and I will then add them to the list. Note that I have added my own email address to keep an eye out for any breakages, and this means that I will be able to see all bugs including security critical bugs. If you are opposed to having me on the list for a few weeks, please let me know and I will remove myself. …
> [snappy] Initial integration

- projects/bearssl/Dockerfile
- projects/bearssl/build.sh
- projects/bearssl/project.yaml
This tests BearSSL crypto primitives against Botan using Cryptofuzz.
Author of BearSSL (in `auto_ccs`) is aware of this and agrees to this integration.
> [bearssl] Add project

- projects/libphonenumber/Dockerfile
- projects/libphonenumber/build.sh
- projects/libphonenumber/phonefuzz.cc
- projects/libphonenumber/project.yaml
URL to upstream project: https://github.com/google/libphonenumber/
@penmetsaa or @lararennie Could you take a look at this? I believe libphonenumber is important to Google and it would be nice to have it fuzzed. OSS-Fuzz is a service run by Google that performs continuous fuzzing of a given project. It would be nice to merge the fuzzer of this PR as well as some additional build changes to the upstream libphonenumber later on. If you are happy to have the project fuzzed, could you provide me with an email that will received updates, e.g. bug-reports, about the fuzzing. I will also take care of the failures in the CI.
> [libphonenumber] Initial integration

- projects/nats/Dockerfile
- projects/nats/build.sh
- projects/nats/project.yaml
This PR adds initial integration of NATS, an incubating CNCF project.
For oss-fuzz maintainers: Please await fuzzers to be merged upstream as well as NATS maintainers to add their email addresses in this PR. 
The name of the directory is nats and not nats-server, as I intend to integrate the nats-client into this directory as well.
For NATS maintainers:
@matthiashanel and @derekcollison
I have taken the liberty to add an integration application of NATS. When the fuzzers are merged in upstream, I will finish the build so it works. The fuzzers will then run continuously and all maintainers on the contact list will receive email notifications with links to bug reports, should a bug be found. If you would like to add yourself or anyone else onto the list to receive potential bug reports, …
> [NATS] initial integration

- infra/base-images/base-clang/checkout_build_install_llvm.sh
Haven't tested locally, but checked that the current version newer than the follow up fix that was landed for #4608.
> [infra] Unfreeze LLVM updating that was stopped due to #4608.

- infra/base-images/base-builder/Dockerfile
- infra/base-images/base-builder/compile
- infra/base-images/base-builder/ossfuzz_coverage_runner.go
- infra/base-images/base-runner/Dockerfile
- infra/base-images/base-runner/coverage
- infra/helper.py
- projects/go-dns/build.sh
- projects/gonids/Dockerfile
- projects/gonids/build.sh
This is a draft, not to be merged yet, following the discussion in #2817
The result now is that 
`python infra/helper.py build_fuzzers --sanitizer coverage gonids`
builds a coverage report named `build/out/gonids/covfuzzparserule.html`
There is still a big list of points to address :
- We need to have the corpus directory when running `python infra/helper.py build_fuzzers`. For now, the directory is hardcoded to `$OUT/corpus/$fuzzer/` . Is this possible and the right thing to do ?
- There is no need to run `python infra/helper.py coverage gonids` because this relies on go testing which needs the source code. I guess that there is somewhere where we should add a test like if we already have some html report, no need to launch this...
- should ossfuzz_test.go be part of the docker image …
> Golang coverage report test

- infra/presubmit.py
- projects/ujson/Dockerfile
- projects/ujson/build.sh
- projects/ujson/json_differential_fuzzer.py
- projects/ujson/project.yaml
- projects/ujson/ujson_fuzzer.py
This adds the fuzzers and builds ujson in the correct format for Atheris to use it. It doesn't yet copy the fuzzers to the archive (pending whatever we decide for how we want to bundle things together). I'm going to hold off a little bit on reaching out to the maintainers, but it looks like the project is well-maintained and we should be able to add a reasonable primary contact when we're ready.
> Initial support for ujson (as a Python fuzzing sample).

- infra/base-images/base-builder/Dockerfile
- infra/base-images/base-builder/compile_go_fuzzer
- projects/cascadia/build.sh
- projects/dragonfly/build.sh
- projects/fasthttp/build.sh
- projects/fastjson/build.sh
- projects/gcloud-go/build.sh
- projects/go-attestation/build.sh
- projects/go-coredns/build.sh
- projects/go-dns/build.sh
- projects/go-json-iterator/build.sh
- projects/golang/build.sh
- projects/gonids/build.sh
- projects/gopacket/build.sh
- projects/grpc-gateway/build.sh
- projects/influxdb/build.sh
- projects/kubernetes/build.sh
- projects/nats/build.sh
- projects/p9/build.sh
- projects/prometheus/build.sh
- projects/quic-go/build.sh
- projects/radon/build.sh
- projects/syzkaller/build.sh
- projects/teleport/build.sh
- projects/tidb/build.sh
- projects/vitess/build.sh
Following #3142, and as request in #2187
Here is the generic `compile_go_fuzzer` and the migration of projects to use it
24 projects in this PR
go-dns and gonids were already using this script
golang and kubernetes were specially handcrafted (golang has seed_corpus in its build script, and kubernetes has an automatic way of naming the fuzzer)
20 projects were automated (see dummy python script below)
5 projects to go :
ipfs has a specific build script I did not dare to touch
golang-protobuf, jsonparser, minify, mtail build scripts seem to be hosted in upstream repos
Plus excelize and go-ethereum which have project.yaml but no build.sh
cc @Dor1s
How do you want to test this ?
Script to automate
```
import sys
comp="""function compile_fuzzer {
path=$1
function=$2
fuzzer=$3
go-fuzz -func …
```
> Use generic compile_go_fuzzer for golang projects

- projects/envoy/build.sh
Build logs for coverage failure
```
Step #3: rsync: link_stat "/src/envoy/third_party" failed: No such file or directory (2)
```
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=25808
(at least tested locally. I think there may be some problems with space on coverage builds, will check next logs)
> [envoy] remove third_party

- projects/wasmtime/Dockerfile
- projects/wasmtime/build.sh
Wasmtime uses [regalloc.rs](https://github.com/bytecodealliance/regalloc.rs), a
register allocator written in Rust that was developed for use in
Cranelift (but is also an independently-usable crate). While it will be
indirectly fuzzed by wasmtime itself once we start fuzzing the new
backends that use it, we should also fuzz it directly, since it exposes
targets just for this. The regalloc fuzzing makes use of a symbolic
checker as an oracle for allocation results, so should be relatively
high-quality. This PR enables the `bt` (backtracking) allocator's fuzz
target, as this is the default allocator.
> wasmtime: add register allocator to fuzz targets.

- infra/ci/build.py
Build a specific project, sckms, that does msan, ubsan, asan, i386
builds quickly, when infra/ code is changed. This can let us know
when infra/ changes break proper functioning of OSS-Fuzz.
For this to work more thoroughly we also need to rebuild images.
Notice how CI failed in https://github.com/google/oss-fuzz/pull/4674
Building a single project would have prevented https://github.com/google/oss-fuzz/issues/4672#issuecomment-731231518 from landing (though in this case it wouldn't have blocked the CIFuzz bug).
> Build a canary project on infra/ changes.

- infra/ci/build.py
- infra/helper.py
This will help us catch breaking changes to the base-images.
Unfortunately caching seems to fail here when I expect it to pass. For example, base-builder doesn't build from cache when I do it locally. This means that every other image I try to build doesn't use the cache. That means that base-clang would take forever to rebuild. So to compromise, I don't rebuild base-clang here.
This means that this PR won't catch breaking changes to base-image or base-clang that break in base-builder.
But it will catch breaking changes to base-image that break in base-runner and it will catch breaking changes to base-runner and base-builder.
> Build base-images before building projects in CI

- docs/getting-started/new-project-guide/go_lang.md
- infra/base-images/base-runner/coverage
Cf #2817 cc @Dor1s 
The one-liner to generate summary.json files for every single fuzz target is adding the new call to `gocovsum`
But then, I created `run_go_fuzz_target` so that targets are run in parallel
> Golang coverage summary for each fuzz target

- projects/kubernetes/Dockerfile
Fixes
```
+ compile_go_fuzzer k8s.io/kubernetes/test/fuzz/yaml FuzzDurationStrict yaml_FuzzDurationStrict
cp: cannot stat '/gopath/ossfuzz_coverage_runner.go': No such file or directory
********************************************************************************
```
> Fix kubernetes coverage build.

- infra/base-images/base-builder/compile_go_fuzzer
- projects/go-json-iterator/Dockerfile
- projects/go-json-iterator/build.sh
- projects/go-json-iterator/fuzz_json.go
Place target in right directory for project go-json iterator so as to get right coverage information
Also fixes coverage fuzz target for golang modules cf go-coredns
cc @Dor1s @inferno-chromium
> Go json coverage

- infra/base-images/base-builder/compile_go_fuzzer
- projects/go-coredns/Dockerfile
- projects/go-coredns/build.sh
such as coredns
cloning into GOPATH
cc @Dor1s @inferno-chromium 
I am not sure this is the perfect way for projects with go modules, but at least it should work...
This somehow adds the constraint that fuzzed projects must be located in `GOPATH/src`
Any better ideas ?
> Golang coverage reports for projects with modules

- projects/hugo/Dockerfile
- projects/hugo/build.sh
- projects/hugo/project.yaml
This PR adds [Hugo](https://github.com/gohugoio/hugo) to oss-fuzz.
**Message for Hugo maintainers:**
@bep
I assume you are one maintainer to receive potential bug reports. I have not added your email address to `project.yaml`, but if you would like to be added, please let me know. I have also added myself to receive reports about the integration failing. This means that I can view all bug reports including potential security vulnerabilities. If you prefer that I am not on this list, please let me know in this thread and I will remove my email address.
Any number of maintainers can be added to the list. All email addresses are public and the list can be changed at any time.
**Message for oss-fuzz maintainers:**
The fuzzer has currently not been merged upstream.
> [hugo] initial integration

- infra/cifuzz/cifuzz.py
- infra/cifuzz/cifuzz_test.py
- infra/cifuzz/fuzz_target.py
Do this so that build.sh can behave differently under CIFuzz.
> Set CIFUZZ env var when building/checking/running CIFuzz fuzzers.

- projects/ipfs/build.sh
The custom build script meant this wasn't transitioned in #4656 
It appears to build and function correctly with the new script.
cc @catenacyber
> Use compile_go_fuzzer for IPFS

- projects/libjpeg-turbo/project.yaml
This will enable the libjpeg-turbo maintainer to see oss-fuzz bug reports.
> [libjpeg-turbo] DRC’s Google acct—>primary_contact

- projects/poppler/Dockerfile
- projects/poppler/build.sh
The memory sanitizer doesn't build the glib part because it fails, but the cpp and qt5 fuzzers are still built
Code based on code by ecalp-tps from bc358f33ad3243e06c3c9934b54561d31a2aee6b
> [poppler] Build the new fuzzers

- projects/zydis/Dockerfile
- projects/zydis/build.sh
- projects/zydis/project.yaml
This PR implements the initial integration of [Zydis](https://zydis.re) into OSS-Fuzz.
Zydis is, to my best knowledge, the second most popular disassembler library around after Capstone, which is already being fuzzed by OSS-Fuzz. Notable projects that depend on it are x64dbg and Mozilla Firefox. I'm a maintainer of this library.
Since OSS-Fuzz requires a Google account on the mail and I usually don't commit using such an address, I created a commit with the primary mail specified in `project.yaml` for verification purposes here: https://github.com/zyantific/zydis/commit/84ae0d5b98e5e5dc6295a27cdd4b6eb1dc9c5aae
The `auto_ccs` mail belongs to @flobernd, the other primary maintainer of Zydis.
We tried following the provided documentation closely and tested ASAN, MSAN and UBSAN builds with …
> [zydis] Initial integration

- projects/mtail/Dockerfile
- projects/mtail/build.sh
Per email discussion we can enable coverage on mtail by using the provided compile method from https://github.com/google/oss-fuzz/pull/4659.
Additionally per same discussion use the full GOPATH form for Go projects with modules.
Finally remove most of the dependence on the upstream Makefile for the fuzz build as a result of the above changes.
> Update mtail fuzzing to use compile_go_fuzzer.

- infra/templates.py
This reflects the current style:
https://opensource.google/docs/copyright/#the-year
> [helper] Change generate command to use "LLC" instead of "Inc."

- docs/getting-started/new_project_guide.md
Asked for by https://github.com/google/oss-fuzz/pull/4653#discussion_r531531162
> [docs] Fix docs to use "LLC" instead of "Inc."

- projects/ujson/json_differential_fuzzer.py
This change removes two lines that prevent a known bug from being found, for the purpose of testing OSS-Fuzz's ability to find interesting test cases with Atheris.
> Make json_differential_fuzzer produce known bugs

- infra/helper.py
As discussed recently in the containers/podman#8513, there is deliberate difference in the CLI of podman and docker in context of creation of missing directories passed as `-v` arguments. While docker happily creates these, podman is not that generous requires the directory structure to be ready in advance.
This PR makes sure directories are in place before invoking podman (symlinked from `docker` by default).
I am running oss-fuzz with podman for several years, reproducing issues and all works fine aside of couple of quirks that I would like to capture in this and probably some more PRs, if they will be acceptable.
> helper: Make sure directories are created before they are passed to container engine (podman)

- projects/libspng/project.yaml
The fuzz target using the external [png_mutator](https://github.com/google/fuzzer-test-suite/blob/master/libpng-1.2.56/png_mutator.h) is causing coverage/build issues with msan and I'm not sure how to fix it, this looks like the lowest-impact solution, will rely on unit tests built with msan for the time being.
<details>
<summary>Expand for error message</summary>
```
Step #33: INFO: performing bad build checks for /tmp/not-out/spng_read_fuzzer_structure_aware.
Step #33: Broken fuzz targets (1):
Step #33: spng_read_fuzzer_structure_aware:
Step #33: BAD BUILD: /tmp/not-out/spng_read_fuzzer_structure_aware seems to have either startup crash or exit:
Step #33: /tmp/not-out/spng_read_fuzzer_structure_aware -rss_limit_mb=2560 -timeout=25 -seed=1337 -runs=4 < /dev/null
Step #33: INFO: found …
```
> libspng: disable msan temporarily

- projects/wasmtime/build.sh
- projects/wasmtime/project.yaml
In [Wasmtime](https://github.com/bytecodealliance/wasmtime), we're
planning to transition eventually to a new x86 backend. We recently
added a fuzz target for this backend that differentially fuzzes against
a Wasm interpreter.
This PR adds the new backend's fuzz target and adds a contact (me) to
the notification list.
> wasmtime: add new codegen backend, and add contact for it.

- infra/build_specified_commit.py
When we fail a build, we attempt to identify the first OSS-Fuzz commit
prior to the upstream commit date.
If this does not exist, we bailed out. This commit changes it such that
we at least try on the oldest integration commit.
> build_specified_commit: fallback to oldest integration commit.

- projects/ghostscript/Dockerfile
The reported build failures in the Ghostscript project are because freetype recently changed their git hosting - this changes the ghostscript Dockerfile to point at the new freetype upstream repo.
> Fix Freetype upstream repo address.

- projects/exprtk/exprtk_fuzzer.cpp
Enable loop upper-bound runtime checks in the fuzzer
--------------
On another note, I'm not sure what to do about these cases:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=28195
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=28169
They are both syntactically valid expressions, yet they trigger the fuzzers due to invalid/bad memory accesses during the evaluation part of the test.
- **Issue 28195:**  'e'[y:3427z]+'e'
- **Issue 28169 :** ''<''[y:z]
**Note:**  Not saying the result is incorrect, just that the exprtk can't do anything about that - like most other languages.
The options I see going forward are:
1. Ignore such testcases as false positives
2. Disable the expression evaluation part
I would rather not do **[2]** as I'd very much like the evaluation part be fuzzed …
> [exprtk] Enable loop upper-bound runtime checks in the fuzzer

- infra/helper.py
https://github.com/google/oss-fuzz/pull/4774 added python3-only code. 
This PR makes code compatible with Python2. 
Fixes https://github.com/google/oss-fuzz/issues/4792
> Fix helper.py

- projects/cilium/project.yaml
Cilium provides eBPF-based Networking, Observability, and Security, is widely used (with [over 7K stars on GitHub](https://github.com/cilium/cilium/stargazers)), including by Google as its [GKE Dataplane V2](https://cloud.google.com/blog/products/containers-kubernetes/bringing-ebpf-and-cilium-to-google-kubernetes-engine).
Hopefully it meets the [new OSS-Fuzz project requirements](https://google.github.io/oss-fuzz/getting-started/accepting-new-projects/) of " a significant user base and/or be critical to the global IT infrastructure". We'd love for Cilium to be supported by OSS-Fuzz.
cc @sharlns @AdamKorcz refs https://github.com/cilium/cilium/pull/14202
> [cilium] Add Cilium project

- projects/mongoose/Dockerfile
- projects/mongoose/build.sh
- projects/mongoose/project.yaml
PR in upstream to fuzzer addition: https://github.com/cesanta/mongoose/pull/1162
mongoose is an embedded networking library. From the upstream repo: "On the market since 2004, used by vast number of open source and commercial products - it even runs on the International Space station!"
> [mongoose][draft: waiting for upstream] initial integration 

- infra/cifuzz/cifuzz.py
- infra/utils.py
- infra/utils_test.py
This makes stacktrace more legible.
Fixes https://github.com/google/oss-fuzz/issues/4649
> Use print for printing stacktrace instead of using log.

- projects/flatbuffers/build.sh
This commit adds copies of dictionaries and auxiliary files to the $OUT folder.
CC: @aardappel
> [flatbuffers] Copy dictionaries and schemas to the OUT directory

- infra/cifuzz/cifuzz.py
- infra/cifuzz/cifuzz_test.py
Make sure the cloned repo is copied correctly to the docker container
E.g. https://github.com/OpenSC/OpenSC should be coiped to $SRC/opensc.
Fixes #4810
> [CIFuzz] Fix issue where copied repo is named incorrectly. 

- projects/pygments/Dockerfile
- projects/pygments/build.sh
- projects/pygments/project.yaml
- projects/pygments/pygments_fuzzer.py
While pygments doesn't use native code for fuzzing,
it's the defacto solution to highlight (untrusted) code,
so unexpected exceptions and timeouts are important.
> Add a fuzzer for Pygments

- projects/osquery/build.sh
Soon osquery will require that the version of CMake
is not equal or higher than 3.18.0.
We can ignore such requirement since we are not making packages.
See osquery/osquery#6801
Also remove unused sed replacements. Those settings are now the default
when not using the osquery toolchain.
> Ignore osquery cmake max version check

- projects/fwupd/project.yaml
The fwupd daemon is a firmware installer deployed onto tens (hundreds?) of
millions of devices. It parses untrusted firmware blobs from OEMs, ODMs and
IHVs writing using dozens of different protocols.
See https://fwupd.org/ for a whole ton more details about the project.
Using the LVFS we've deployed at least 22 million updates in the last few years,
although that number could be a lot higher in reality as we allow the LVFS to
be anonymously mirrored and for fwupd to be run without phoning home.
We used to fuzz with afl but recently switched to honggfuzz which found an
additional 17 critical warnings or crashes. Hence my interest in oss-fuzz!
My actual email address richard@hughsie.com is aliased to the email address
given here, and I can confirm I'm the upstream maintainer. The github …
> fwupd: Initial integration for possible acceptance

- projects/leveldb/build.sh
- projects/leveldb/fuzz_db.cc
* Stop when opening a database fails. This will avoid null pointer
dereferences.
* Use C++11 smart pointers for leveldb::DB and leveldb::Iterator. This
makes it easier to ensure the fuzzer doesn't leak memory. No leak was
detected while applying this fix.
* Use the FuzzedDataProvider API exclusively for consuming data. This
makes it easier to ensure maximum fuzzer coverage.
* Avoid building unnecessary code (tests, benchmarks). This slightly
reduces oss-fuzz resource usage.
* Use an enum class and FuzzedDataProvider::ConsumeEnum() instead of
reimplementing it. This makes it easier to extend the fuzzer with new
operations in the future.
* Use meaningful names (key, value, name) instead of tmp* for local
variables storing leveldb API inputs.
> leveldb: Fuzzer improvements.

- projects/sound-open-firmware/Dockerfile
- projects/sound-open-firmware/build.sh
- projects/sound-open-firmware/project.yaml
Initial build files for sound open firmware fuzzer
https://github.com/thesofproject/sof/pull/3505 needs to merge first
TODO
> sound-open-firmware: add build files

- projects/dav1d/nasm.list
- projects/dav1d/nasm_apt.pin
Fixes broken dav1d build due EOL for for eoan
> dav1d: fetch nasm from Ubuntu 20.04 LTS (focal)

- projects/kimageformats/Dockerfile
- projects/kimageformats/build.sh
- projects/kimageformats/kimgio_fuzzer.cc
[AVIF](https://aomediacodec.github.io/av1-avif/) image format is now supported by KDE in kimageformats project.
This change enables building of the AVIF plug-in fuzzer and link statically with its dependencies (libavif and libaom). yasm is used to build faster libaom.
@tsdgeos FYI
> Add AVIF format to kimageformats project

- projects/tensorflow/build.sh
Fix the build breakage caused by the AttrValues fuzzer in OSS. The target requires large artifacts to link against which are not optimal for OSS fuzzing.
> Ignore the AttrValues fuzzer for tensorflow

- projects/htslib/Dockerfile
In anticipation of samtools/htslib#929 merge, which will add a submodule, among other changes.  This will ensure fuzzing continues to work both before and after the update.
> Add recurse-submodules to htslib clone

- projects/exprtk/exprtk_fuzzer.cpp
Some of the test cases are failing due to timeouts. Limiting the number of loop iterations should resolve this issue.
> [exprtk] Decrease loop runtime check upper-bound

- projects/bs4/Dockerfile
No need to do convert the source to python3 ourself,
since pip can do it itself.
> Fix the build for beautifulsoup's fuzzer

- projects/pillow/fuzz_pillow.py
By default, pygments is lazy, and won't decode/ratser/encode
things if not explicitly needed. Using a rotation and a filter
should force it to do it.
> Force pillow to do more operations on the input

- projects/go-ethereum/Dockerfile
This PR depends on https://github.com/ethereum/go-ethereum/pull/22029 , and makes it possible to fix https://github.com/google/oss-fuzz/issues/4847.
> go-ethereum: install go-ethereum in go-path

- projects/wolfssl/Dockerfile
- projects/wolfssl/build.sh
wolfCrypt contains several separate bignum implementations. The OSS-Fuzz Cryptofuzz project fuzzes one of them. This PR adds a fuzzer for the other two.
> [wolfssl] Build fuzzers for two bignum implementations

- projects/rnp/build.sh
RNP soon would require Botan 2.16.0 as minimum version, so updating `build.sh` here as well.
> [rnp] Update used Botan version to 2.16.0.

- projects/pillow/Dockerfile
- projects/pillow/build.sh
Prepatch on master:
```
(vpy38-dbg) erics@wf:~/src/oss-fuzz$ python infra/helper.py run_fuzzer pillow fuzz_pillow --sanitizer=address
/home/erics/vpy38-dbg/lib/python3.8/site.py:165: DeprecationWarning: 'U' mode is deprecated
f = open(fullname, "rU")
Running: docker run --rm --privileged -i -e FUZZING_ENGINE=libfuzzer -e SANITIZER=address -e RUN_FUZZER_MODE=interactive -v /home/erics/src/oss-fuzz/build/out/pillow:/out -t gcr.io/oss-fuzz-base/base-runner run_fuzzer fuzz_pillow --sanitizer=address
/out/fuzz_pillow -rss_limit_mb=2560 -timeout=25 --sanitizer=address /tmp/fuzz_pillow_corpus < /dev/null
INFO: Configured for Python tracing with opcodes.
INFO: libFuzzer ignores flags that start with '--'
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 2472509883
INFO: Loaded 3 …
```
> [pillow] Fix pillow corpus file name

- projects/qt/Dockerfile
- projects/qt/project.yaml
Removing i386 because it fails with:
../bootstrap/libBootstrap.a(qdatetime.cpp.o): In function `qMulOverflow<long long>':
/work/qtbase/include/QtCore/../../../../src/qt/qtbase/src/corelib/global/qnumeric.h:122: undefined reference to `__mulodi4'
> [qt] Build from the dev branch

- projects/nats/project.yaml
@inferno-chromium for your consideration
We have received several bug reports but had issues logging in.
We presume this is due to security@nats.io only being an alias.
Because of this I want to add my email so I can check out the bug reports.
I am a member of the nats organization that maintains the nats-server repo.
- Thanks, Matthias
> include extra email in auto_ccs

- projects/powerdns/Dockerfile
Hello,
This PR moves to a newer (third party) boost lib, and supersedes #4924 (CLA issue). The provided boost by Xenial is too old to be compiled in C++17 mode.
Thanks!
> PowerDNS: Move to a newer boost in preparation for the move to C++17

- projects/tensorflow/build.sh
Remove the bfloat fuzzer from open source fuzzing due to linking issues.
> Remove bfloat fuzzer from tensorflow

- infra/base-images/base-builder/compile_go_fuzzer
cc @inferno-chromium 
- One fix (did not break the projects already there but broke go-ethereum which had a package named bus in a directory named bls1321)
- One improvement to get the report over all the repository (and not restricted to the subdirectory/package where the target resides)
This should be tested as it concerns all golang projects
> Golang coverage improvements

- projects/pillow/Dockerfile
- projects/pillow/build.sh
- projects/pillow/build_depends.sh
~This depends on https://github.com/python-pillow/Pillow/pull/5189, which sets the zipsafe flag to false in setup.py.~ Merged
There are several things going on here, and I'm willing to split them into issue specific changes if required. (btw, I'm an owner of pillow)
* make install-req is only for development dependencies -- test runners and doc builders. It's not required here. 
* Test using the library versions built for binary distribution, built with the same scripts as for releases.  Out of the box, oss-fuzz installs libraries from ubuntu 16.04, and we're using the latest patch releases of the upstream sources for these dependencies. The distribution manylinux wheels are built on centos, so there's a bit of tweaking to make them build here.  (e.g., linking yum to /bin/true, while …
> [pillow] Pillow build improvements

- projects/scapy/project.yaml
It cannot use my main email address to access the bug report. I would like to use my main gmail address instead.
> [scapy] Change primary contact

- projects/matio/Dockerfile
This updates hdf5 1.8.16 (of xenial) to latest hdf5 1.12.0.
> [matio] Build hdf5 1.12.0

- projects/selinux/project.yaml
James Carter (@jwcart2) is a member of the team of people who develop and maintain SELinux.
> [selinux] add James Carter's email

- projects/tensorflow/build.sh
We are adding a `tf.constant` fuzzer for Python in oss-fuzz. We do not want it to run on oss-fuzz yet until we are confident it works. Sorry for the repeated PRs into the oss-fuzz directory. Working to alleviate this.
@mihaimaruseac
> Remove the constant fuzzer from oss-fuzz.

- projects/qt/Dockerfile
- ninja is the preferred build tool
- 32-bit libraries are no longer needed
> [qt] Update package installation

- projects/mdbtools/Dockerfile
- projects/mdbtools/build.sh
Per #4928, external files are overwritten by CIFuzz if they have been checked out into the main source tree.
> [mdbtools] Move test files out of the checkout tree

- projects/pillow/Dockerfile
Fix recent build failure by running apt-get update. 
(https://oss-fuzz-build-logs.storage.googleapis.com/log-e79c5d64-5cf0-4f78-b4be-bf7c182a308f.txt)
```
Step #1: Get:91 http://archive.ubuntu.com/ubuntu xenial/main amd64 xterm amd64 322-1ubuntu1 [607 kB]
Step #1: Err:22 http://security.ubuntu.com/ubuntu xenial-security/main amd64 tzdata all 2020d-0ubuntu0.16.04
Step #1:   404  Not Found [IP: 91.189.88.142 80]
Step #1: Err:22 http://security.ubuntu.com/ubuntu xenial-security/main i386 tzdata all 2020d-0ubuntu0.16.04
Step #1:   404  Not Found [IP: 91.189.88.142 80]
Step #1: Err:22 http://security.ubuntu.com/ubuntu xenial-security/main i386 tzdata all 2020d-0ubuntu0.16.04
Step #1:   404  Not Found [IP: 91.189.88.142 80]
Step #1: [91mE: Failed to fetch …
```
> [pillow] Fix recent build failure

- infra/repo_manager.py
Unshallow can fail in a submodule, even if the unshallow succeeded for
the main repo.
> repo_manager: Allow unshallow to return non-zero.

- projects/mdbtools/build.sh
Intended to resolve issue described here: https://github.com/google/oss-fuzz/issues/4956
> [mdbtools] Remove path components from zipped corpus

- infra/base-images/base-builder/Dockerfile
- infra/base-images/base-clang/Dockerfile
Fixes broken base-clang build in https://github.com/google/oss-fuzz/pull/4930#issuecomment-760308849
```
-- Looking for os_signpost_interval_begin - not found
CMake Error at /usr/local/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
Could NOT find Python3 (missing: Python3_EXECUTABLE Interpreter)
Call Stack (most recent call first):
/usr/local/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
/usr/local/share/cmake-3.19/Modules/FindPython/Support.cmake:3148 (find_package_handle_standard_args)
/usr/local/share/cmake-3.19/Modules/FindPython3.cmake:398 (include)
CMakeLists.txt:711 (find_package)
-- Configuring incomplete, errors occurred!
See also "/work/llvm-stage1/CMakeFiles/CMakeOutput.log".
See also …
```
> Move python 3 install to base-clang, needed for clang build.

- projects/relic/Dockerfile
- projects/relic/build.sh
- projects/relic/project.yaml
relic is a cryptographic library.
Some projects that use relic:
https://github.com/imichaelmiers/libforwardsec
https://github.com/zeutro/openabe
https://github.com/vmware/concord-bft
https://github.com/JHUISI/charm
https://github.com/Chia-Network/bls-signatures/
https://gitlab.com/neucrypt/anonize2
https://github.com/encryptogroup/OPPRF-PSI
The relic maintainer is aware of this integration, see also https://github.com/relic-toolkit/relic/issues/171
> [relic] Add project relic

- infra/helper.py
Otherwise when I run
```
python infra/helper.py shell project
compile
```
I get the following error : `/usr/local/bin/compile: line 25: FUZZING_LANGUAGE: unbound variable`
> Sets language env variable when running shell

- infra/build_specified_commit.py
Return None rather than exceptioning out when a suitable base-builder
cannot be found to allow more graceful error handling.
> build_specified_commit: Remove an exception.

- projects/cairo/project.yaml
This is what upstream wants: https://gitlab.freedesktop.org/cairo/cairo/-/merge_requests/69#note_768642
> Make cairo's issues public by default

- projects/cryptofuzz/Dockerfile
- projects/cryptofuzz/build.sh
Cryptofuzz was using an older version of xxHash. This PR ensures the latest version is fetched from the repository and fuzzed.
> [cryptofuzz] Use latest version of xxHash

- projects/binutils/fuzz_readelf.c
Clear static vars after freeing, to prevent a double-free on the next
test iteration.
> Issue 27734: binutils:fuzz_readelf: Abrt with empty stacktrace

- infra/base-images/base-builder/Dockerfile
**Reviewers**: What would be the best way to test this change? I'm particularly interested in making sure that the existing Docker files for Bazel projects won't fail now that Bazel would already be available in the base image.
> Add the Bazel dependencies to the base builder image.

- infra/base-images/base-builder/Dockerfile
Save 177Mb.
```
root@eca2ea09a598:/src/honggfuzz/examples# du -h
16K	./glibc
8.0K	./libxml2
2.4M	./openssl/corpus_privkey
5.1M	./openssl/corpus_x509
18M	./openssl/corpus_client
27M	./openssl/corpus_server
52M	./openssl
16K	./externalfuzzers
12K	./libpng
25M	./bind/corpus
25M	./bind
29M	./linux_kernel_ip/corpus
30M	./linux_kernel_ip
16K	./libjpeg
20K	./terminal-emulators
33M	./apache-httpd/corpus_http1
39M	./apache-httpd/corpus_http2
72M	./apache-httpd
12K	./file
16K	./badcode/targets
8.0K	./badcode/inputfiles
36K	./badcode
177M	.
```
> Remove unneeded honggfuzz examples from base-builder.

- infra/cifuzz/cifuzz.py
1. Add a get_affected_fuzzers function.
2. Add comments explaining rationales.
3. Fix logging so that each affected fuzzer is only logged once.
4. Don't put each file affecting each fuzzer on its own line, this makes logs unreadable.
5. Improve logging wording.
> [CIFuzz][NFC] Refactor affected fuzzers and improve logging

- infra/base-images/base-builder/Dockerfile
Remove docs and other unneeded stuff.
https://blog.rust-lang.org/2019/10/15/Rustup-1.20.0.html
> Install rust in base-builder with minimal profile.

- projects/serenity/Dockerfile
- projects/serenity/build.sh
With this, can build fuzzers against a local checkout with:
python3 infra/helper.py build_fuzzers serenity $HOME/src/serenity
Similar to 14452cfb3d87f3f54ced75b9d5dd67b1470f2080
> Fix workdir for serenity project

- infra/base-images/base-builder/compile_go_fuzzer
- projects/teleport/build.sh
`go list` will fail if all files in the fuzzed package use a build tag restriction (like the common `gofuzz` tag).
Also, pass the `gofuzz` tag in the teleport build to plumb it through.
> compile_go_fuzzer: pass build tags to `go list`

- projects/tensorflow/build.sh
Specify only C++ fuzzers using [bazel query filters for C++](https://docs.bazel.build/versions/master/query-how-to.html#Which_of_those_are_C_tests_). This will also allow us to submit Python fuzzers without a modification to oss-fuzz code.
@mihaimaruseac
> Select only C++ fuzzers

- .pylintrc
- infra/base-images/base-builder/bisect_clang.py
- infra/base-images/base-builder/bisect_clang_test.py
- infra/base-images/base-builder/write_labels.py
- infra/base-images/base-runner/dataflow_tracer.py
- infra/bisector_test.py
- infra/cifuzz/build_fuzzers_entrypoint.py
- infra/cifuzz/run_fuzzers_entrypoint.py
- infra/presubmit.py
Run lint on all python files. Linting only changed files is incorrect.
This is because an unchanged file can have a linting error from depending on a changed file.
We should do the same for tests as well. But we will skip this for now because:
1. Some tests have weird path hacks and need to be blocklisted.
2. We currently run tests using integration tests which take pretty long (~6 minutes on my desktop, probably longer on CI).
3. Even the unittests are not that fast to run (take about 30 seconds locally, 8 from CIFuzz, ~20 from build).
For now, allow all tests to be run if specified.
Also, lint all files so that presubmit passes.
Fixes https://github.com/google/oss-fuzz/issues/3320
> Run lint on all python files

- .github/workflows/infra_tests.yml
- infra/presubmit.py
The previous approach of only running tests in changed directories is broken.
Tests can fail even when files outside of their directory are modified.
Also blocklist failing tests (see https://github.com/google/oss-fuzz/issues/5025) for why build tests are blocklisted.
> Run all tests when infra-tests is run from presubmit

- projects/mruby/build.sh
Building mruby is done with `make clean all -j$(nproc)`, but build fails
randomly because `clean` and `all` run in parallel, and `clean` may be
executed after `all` starts.
Therefore, change it as follows.
* Remove `clean` because it seems to be unneeded in the first place.
* Use `rake` command because mruby uses Rake for builds (`Makefile` is a
limited wrapper for calling `rake`).
* Use `-m` option to run builds in parallel.
* Remove `-j` option because build time seems to be almost the same even
if `-j` option is specified.
> Fix building mruby fails randomly

- .pylintrc
- infra/build/functions/project_sync_test.py
- infra/build/functions/request_build_test.py
- infra/build/functions/request_coverage_build_test.py
- infra/build/functions/update_build_status_test.py
- infra/retry.py
This check is super useful. It can catch use of misspelled functions in other modules and use of misspelled attributes.
> [pylint] Enable no-member check

- projects/bazel-rules-fuzzing-test/build.sh
This avoids any conflict with the compiler configuration used in the rules_fuzzing development.
> Explicitly use the compiler toolchain provided by the OSS-Fuzz environment.

- projects/exprtk/exprtk_fuzzer.cpp
Timeouts are causing test failures. To prevent such failures, during the evaluation phase will only consider expressions of size 64KB and less.
> [exprtk] Set maximum expression size during evaluation phase

- projects/hermes/build.sh
A recent commit in Hermes to add Fuzzilli support requires us to distinguish between the OSS-Fuzz and Fuzzilli fuzzing modes. Update the CMake flag in our build script to reflect the new flag for building in OSS-Fuzz.
> [Hermes] Update CMake flag

- projects/tmux/project.yaml
_Requested by by @nicm (tmux project's maintainer) in https://github.com/google/oss-fuzz/issues/4593#issuecomment-768161872_
> tmux: take openbsd security list off from CC

- projects/orbit/Dockerfile
- projects/orbit/build.sh
This change is necessary to reflect the recent branch renaming on
github.com/google/orbit from master to main.
I tested this via
```
python infra/helper.py build_image orbit
```
> Project Orbit: Fix Dockerfile

- projects/perfetto/project.yaml
Built and ran `python infra/helper.py check_build --engine afl perfetto ...` on all our fuzzers successfully.
> Run fuzzers using AFL now we have fixed the build.

- projects/sudoers/fuzz_iolog_json_parse.c
- projects/sudoers/fuzz_sudoers_parse.c
This changes the fuzzers of sudoers, in particular to using `mkstemp` as per request from the maintainer here https://github.com/google/oss-fuzz/pull/5052#discussion_r565796971
> sudoers: update fuzzers

- projects/openssh/build.sh
This enables fuzzing of the key exchange process, using a fuzzer already shipped in Portable OpenSSH.
It also enables the null cipher for fuzzing builds, as this is faster and allows for better coverage.
> Enable fuzzing of key exchange

- infra/cifuzz/cifuzz.py
- infra/cifuzz/config_utils.py
- infra/cifuzz/config_utils_test.py
1. ssh url.
This only affects external (non-oss-fuzz) users.
Since there are none, it doesn't affect anyone.
Even if it did, exploitation would require owning the network
Github actions runs on.
This is to prevent MITM attacks.
2. Unaffected bug.
We accidentally were skipping the remove unaffected functionality.
> [cifuzz][external] Use ssh_url and fix affected fuzzers

- projects/utf8proc/Dockerfile
- projects/utf8proc/build.sh
- projects/utf8proc/project.yaml
utf8proc is a small, clean C library that provides Unicode normalization, case-folding, and other operations for data in the UTF-8 encoding.
utf8proc is used for basic Unicode support in the [Julia language](http://julialang.org/).
I intend to integrate this project.
> Add project utf8proc

- projects/ecc-diff-fuzzer/build.sh
Should fix build failure
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=30001
Otherwise, lib gcrypt compilation got to fail with
```
keccak.c:907:23: error: use of undeclared identifier 'HWF_INTEL_FAST_SHLD'
else if (features & HWF_INTEL_FAST_SHLD)
```
> No longer disables asm for gcrypt in ecc-diff-fuzzer

- infra/base-images/base-builder/Dockerfile
- infra/base-images/base-builder/compile_afl
Reverts google/oss-fuzz#5074
Revert due to issues cited in https://github.com/google/oss-fuzz/issues/4280#issuecomment-770949515
> Revert "Switch to using afl-clang-fast for afl++."

- projects/prometheus/project.yaml
Dear OSS-Fuzz maintainers,
Brian Brazil has resigned from the Prometheus project, and we have
decided to put Björn Rabenstein in place for the OSS-Fuzz reports.
cc @beorn7
Thanks
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
> Update Prometheus team members

- projects/nodejs/build.sh
`--experimental-quic` was removed in nodejs (https://github.com/nodejs/node/pull/37067) and thus we remove it when building nodejs
> nodejs: fix build after experimental-quic flag removed.

- projects/pigweed/build.sh
- projects/pigweed/extract_pw_fuzzers.py
Fuzzing was broken due to toolchain refactoring. This change brings
things back.
Test: Locally built and run the example toy_fuzzer per
https://google.github.io/oss-fuzz/getting-started/new-project-guide/#testing-locally
> pigweed: Restore fuzzing

- infra/base-images/base-builder/Dockerfile
- projects/envoy/Dockerfile
- projects/envoy/build.sh
We should wait for envoyproxy/envoy#14834 to be submitted first. CC @asraa @htuch
> Simplify the Envoy integration by using the new rules_fuzzing primitives.

- infra/cifuzz/affected_fuzz_targets_test.py
- infra/cifuzz/clusterfuzz_deployment_test.py
- infra/cifuzz/coverage_test.py
- infra/cifuzz/fuzz_target_test.py
- infra/cifuzz/run_fuzzers_test.py
- infra/cifuzz/stack_parser_test.py
1. Use pyfakefs when possible instead of tempdir
2. Favor decorators instead of contextmanagers when mocking for less indentation and greater consistency.
> [cifuzz][NFC] Refactor tests

- infra/cifuzz/build_fuzzers_test.py
This ensures that the test doesn't modify the repo.
> [cifuzz][NFC] Use a temporary directory in a test of check_fuzzer_build

- infra/cifuzz/build_fuzzers_test.py
Ensure more tests dont modify the repo by using a temporary directory.
Also, use setUp to create a tempdir to save code repitition.
> [CIFuzz][NFC] Ensure more tests don't modify the repo

- projects/relic/build.sh
Before this PR, relic was built to use stack allocations. Now that all bugs arising from that configuration have been found and fixed, we're activating dynamic allocations, which is expected to find more bugs, like memory leaks.
> [relic] Build relic with dynamic allocator

- .github/workflows/infra_tests.yml
- infra/ci/build_test.py
- infra/ci/requirements.txt
- infra/presubmit.py
- infra/pytest.ini
1. Allow running tests in parallel. Locally this takes the time for running all tests (including integration tests) from 6 minutes to ~50 seconds. We don't do parallel by default since it doesn't really save any time unless running integration tests on my machine (probably due to overhead of starting ~70 processes). This also speeds up CI from about 12 minutes to 6 minutes  (since github actions has 2 cores per machine).
2. Fix how we run tests. I'm not exactly sure why, but the method we used for discovering tests, recursing through every directory and passing to unittest caused the build/infra tests to execute twice. Fixing this makes running unittests take ~20 seconds instead of ~35.
This change also uses pytest for running tests since it's easy to use it to run tests in parallel.
This …
> Improve test speed

- infra/base-images/base-builder/Dockerfile
- infra/base-images/base-runner/run_fuzzer
- projects/libavif/build.sh
- projects/libcacard/build.sh
- projects/libxml2/build.sh
- projects/openssl/build.sh
- projects/skia/build.sh
- projects/wireshark/build.sh
Selected targets: livavif, libcacard, libxml2, openssl, skia and wireshark
Tested: libcacard and skia.
I do not expect any issues as this has been running fine with all 33 fuzzbench targets.
I wanted to test the running as well as I modified the run_fuzzer but couldn't figure out how ;-)
```
[...]
afl does not seem to exist. Please run build_fuzzers first.
afl does not seem to exist. Please run build_fuzzers first.
usage: helper.py run_fuzzer [-h]
[--engine {libfuzzer,afl,honggfuzz,dataflow,none}]
[--sanitizer {address,memory,undefined,coverage,dataflow}]
[-e E] [--corpus-dir CORPUS_DIR]
project_name fuzzer_name ...
helper.py run_fuzzer: error: the following arguments are required: fuzzer_name, fuzzer_args
```
> afl++ CMPLOG test

- projects/pigweed/build.sh
Pigweed python env setup now uses the "arm-none-eabi-gcc" toolchain
to derive some flags for the newly added clang for ARM toolchain.
Bug: https://crbug.com/oss-fuzz/30513
> pigweed: Fix build failure

- projects/fwupd/Dockerfile
- projects/fwupd/build.sh
- projects/fwupd/project.yaml
INFO: performing bad build checks for /tmp/not-out/wac_fuzzer
INFO: performing bad build checks for /tmp/not-out/synaptics-rmi_fuzzer
INFO: performing bad build checks for /tmp/not-out/dfuse_fuzzer
INFO: performing bad build checks for /tmp/not-out/bcm57xx_fuzzer
INFO: performing bad build checks for /tmp/not-out/ihex_fuzzer
INFO: performing bad build checks for /tmp/not-out/fmap_fuzzer
INFO: performing bad build checks for /tmp/not-out/cros-ec_fuzzer
INFO: performing bad build checks for /tmp/not-out/solokey_fuzzer
INFO: performing bad build checks for /tmp/not-out/srec_fuzzer
INFO: performing bad build checks for /tmp/not-out/ebitdo_fuzzer
INFO: performing bad build checks for /tmp/not-out/synaprom_fuzzer
Check build passed.
> fwupd: Include fuzz targets

- projects/dragonfly/build.sh
- projects/gitea/build.sh
- projects/go-redis/build.sh
- projects/grpc-gateway/build.sh
- projects/hugo/build.sh
- projects/istio/build.sh
- projects/loki/build.sh
- projects/lotus/build.sh
- projects/nats/build.sh
- projects/prometheus/build.sh
- projects/radon/build.sh
- projects/teleport/build.sh
- projects/tidb/build.sh
- projects/vitess/build.sh
Using "#/bin/bash" instead of "#!/bin/bash" only seems to work because the file is often treated as a script by default when there is no "#!" on the top line. The "-eu" options to Bash are ignored, however, and on some systems and OS configurations the files might not default to being executed as scripts.
> "#/bin/bash" is just a comment; change "#/" to "#!/"

- infra/base-images/base-runner/bad_build_check
It should make the script compatible with binutils-2.36.1 (where
"callq" is no longer present in the output of objdump)
It was spotted in https://github.com/systemd/systemd/pull/18528
> bad_build_check: also look for call on x86_64

- projects/wolfssl/build.sh
Add fuzzers for
- SP math
- SP-math-all 8bit
These are distinct configurations the wolfSSL SP bignum implementation that can contain unique bugs, and the wolfSSL bignum maintainer suggested I test these.
> [wolfssl] Add more bignum fuzzers

- infra/presubmit.py
Previously "and" shortcircuiting caused the build tests not to be
run if the non-build tests (which are run first) failed.
> [presubmit] Make sure to run build tests even if nonbuild tests fail

- projects/libsodium/project.yaml
Access to oss-fuzz requires an exact match, so remove the suffix from the address.
Fixes #5158
> Update contact address for libsodium

- projects/golang/project.yaml
This way I can help coordinate and fix found bugs for the Go project. Following up on the conversation started at https://github.com/google/oss-fuzz/pull/2188#issuecomment-777998105.
> projects/golang: add Emmanuel Odeke as a Go maintainer

- projects/bignum-fuzzer/Dockerfile
- projects/bignum-fuzzer/build.sh
- projects/cryptofuzz/Dockerfile
- projects/cryptofuzz/build.sh
Build Golang with regular clang.
For instrumentation it doesn't matter because this is the Golang compiler, which isn't part of the output binaries.
> [cryptofuzz, bignum-fuzzer] Fix AFL++ builds

- projects/pillow/Dockerfile
- projects/pillow/build.sh
Pillow now has support (https://github.com/python-pillow/Pillow/pull/5199) for properly linking the fuzzers in the core setup.py build script. 
This change 
* removes the manual linking step from build.sh 
* explicitly includes some of the external libraries in the pyinstaller build
* removes the libraries for the currently un-fuzzed raqm/fribidi/harfbuzz font stack, which are optional pillow dependencies.
> [Pillow] Use upstream support for fuzzing build

- projects/qemu/Dockerfile
In qemu/qemu@fff7111 we added configurations for fuzzing virtio-9p
devices. However, these fuzzers are presently stalled on oss-fuzz,
because the build image doesn't have the necessary libattr, and
libcap-ng libraries. Fix that.
> qemu: Add necessary dependencies for 9p fuzzing

- projects/systemd/Dockerfile
Apparently the latest version of meson (0.57.0) somehow broke systemd
OSS-Fuzz builds. Since it was released systemd has been failing to compile
with
```
2021-02-14T21:23:53.3854577Z [481/664] clang++  -o fuzz-compress fuzz-compress.p/src_fuzz_fuzz-compress.c.o -L/usr/lib/clang/12.0.0/lib/linux -Wl,--as-needed -Wl,--allow-shlib-undefined '-Wl,-rpath,$ORIGIN/src/shared' -Wl,-rpath-link,/work/build/src/shared -Wl,--start-group src/shared/libsystemd-shared-247.so -lFuzzingEngine -Wl,--end-group
2021-02-14T21:23:53.3856578Z FAILED: fuzz-compress
2021-02-14T21:23:53.3858714Z clang++  -o fuzz-compress fuzz-compress.p/src_fuzz_fuzz-compress.c.o -L/usr/lib/clang/12.0.0/lib/linux -Wl,--as-needed -Wl,--allow-shlib-undefined '-Wl,-rpath,$ORIGIN/src/shared' -Wl,-rpath-link,/work/build/src/shared …
```
> [systemd] roll back to meson-0.56.2

- projects/go-sqlite3/Dockerfile
Now that fuzz target got merged upstream cf https://github.com/mattn/go-sqlite3/pull/908
> Use upstream repo for go-sqlite3 project

- projects/sudoers/build.sh
Now that fuzzers are integrated into sudo's build system the build.sh script no longer needs to build the fuzz targets itself.  This will avoid bit rot and inconsistencies between sudo's build config and build.sh in oss-fuzz.  Fuzzer options are passed in via configure arguments, just as they would be when building with fuzzing support outside of oss-fuzz.  Multiple fuzzing engines are supported.
This PR also adds additional fuzzers, including one for the policy module that catches CVE-2021-3156.
> sudoers: fuzz targets are now integrated into sudo's build system

- infra/base-images/base-builder/Dockerfile
- infra/base-images/base-builder/compile
- infra/base-images/base-runner/Dockerfile
Jazzer is built from HEAD using Bazel and the clang toolchain provided by base-clang. While it could be built with OpenJDK 8, which is available as a package, JVM fuzz targets should not be forced to be compatible with Java 8. For this reason, the official binary release of OpenJDK 15 is pulled into both base-builder and base-runner and set as JAVA_HOME.
Jazzer consists of the following four components:
* The API (`jazzer_api_deploy.jar`), which is required for fuzz targets that use FuzzedDataProvider or custom method hooks, is made available in /usr/local/lib in base-builder.
* The driver (`jazzer_driver`), which links in libFuzzer and is reused across fuzz targets. Since it is used to run fuzz targets, it is included into base-runner.
* The agent (`jazzer_agent_deploy.jar`), which …
> [jazzer-1] Add Jazzer to base-builder and base-runner

- infra/base-images/base-builder/compile
- infra/base-images/base-runner/bad_build_check
- infra/base-images/base-runner/test_all.py
- infra/presubmit.py
compile, bad_build_check, and presubmit.py require small tweaks to
support JVM fuzz targets, most of which are similar to those required
for Python. The following additional changes are required:
* Since the Jazzer driver binary already links in libFuzzer, it should
not be built as a static library.
* It is not clear how to do architecture checks as JVM fuzz targets can
load their native dependencies dynamically at runtime. For now, the
check is disabled.
> [jazzer-2] Adapt infra scripting to JVM fuzz targets

- projects/json-sanitizer/DenylistFuzzer.java
- projects/json-sanitizer/Dockerfile
- projects/json-sanitizer/IdempotenceFuzzer.java
- projects/json-sanitizer/ValidJsonFuzzer.java
- projects/json-sanitizer/build.sh
- projects/json-sanitizer/project.yaml
json-sanitizer uses Maven and has no native dependencies.
The build file is loosely divided into two parts. The first part is project-specific, the second one can serve as a template for JVM fuzz targets without native dependencies.
The following three fuzz targets are added to OSS-Fuzz and can later be moved into the json-sanitizer tree:
* DenylistFuzzer verifies that the output of json-sanitizer never contains certain substrings that can lead to HTML or XML injections.
* IdempotenceFuzzer verifies that json-sanitizer is idempotent.
* ValidJsonFuzzer verifies that the output of json-sanitizer is valid JSON by passing it into gson.
> [jazzer-3] Add json-sanitizer as the first JVM project

- projects/tensorflow/build.sh
Remove manual denylisting of fuzzing targets using bazel query via tags. Excluding the `no_oss` tag targets.
@mihaimaruseac @pak-laura
> Remove manual denylisting in tensorflow

- projects/json-sanitizer/build.sh
This is a speculative fix for an issue we've seen where the class
fails to load.
A simpler approach I did not use is cd-ing into $this_dir. I didn't
use this approach because it will break things if relative paths
are passed to the fuzzer by ClusterFuzz.
The other reason that I think could be responsible for the missing
class issues is not unpacking the zipfile fully.
Related: https://github.com/google/oss-fuzz/issues/5178
> [json-sanitizer][jazzer] Don't assume that fuzzer is run from its dir

- infra/base-images/base-clang/Dockerfile
This should reduce the image layer size from 127 MB to 57 MB
> [infra] Remove unneeded binaries, docs from CMake install

- projects/openjpeg/build.sh
Seems that some bugs in openjpeg can be triggered only in release mode.
More specifically, @elManto and I were trying to reproduce https://github.com/uclouvain/openjpeg/issues/1228 using the OSS-Fuzz harness and we failed.
I figured out that the bug is indeed reachable by the harness, but can be uncovered only in Release mode, otherwise, an assertion error blocks it.
I guess that they use assertions only in Debug mode (WTF) and remove them in Release.
So, IMO openjpeg should be fuzzed in Release mode as the configuration used in production is the one relevant for security.
> [openjpeg] Release cmake build type

- infra/base-images/base-builder/Dockerfile
- infra/base-images/base-builder/compile_afl
- infra/base-images/base-runner/run_fuzzer
- projects/libavif/build.sh
- projects/libcacard/build.sh
- projects/libxml2/build.sh
- projects/openssl/build.sh
- projects/skia/build.sh
- projects/wireshark/build.sh
If the 5 CMPLOG test targets produced no issues - then this is the final afl++ integration PR.
It randomly enables CMPLOG and/or LAF, plus documents the options in $OUT/afl_options.txt
I also included two configurable options - for world-wide or per project configuration:
`LLVM_MODE_WORKAROUND` - if set to "yes" then a fallback to clang + -fsanitize-coverage is performed, in case afl-clang-fast ever breaks and this becomes a major issue.
`WANT_DICTIONARY` - if set to "yes" this will generate a dictionary based on comparisons extracted at compile time.  run_fuzzer + clusterfuzz will check for this file and if present load+use it.
> Final afl++ integration

- projects/java-example/build.sh
The same speculative fix as in #5217.
The current working directory "." should have no reason to be in the
classpath if it is not equal to "$this_dir", hence it is removed.
> [java-example] Don't assume that fuzzer is run from its directory

- docs/getting-started/continuous_integration.md
- infra/cifuzz/actions/build_fuzzers/action.yml
- infra/cifuzz/actions/run_fuzzers/action.yml
- infra/cifuzz/build_fuzzers.py
- infra/cifuzz/build_fuzzers_entrypoint.py
- infra/cifuzz/build_fuzzers_test.py
- infra/cifuzz/config_utils.py
- infra/cifuzz/config_utils_test.py
- infra/helper.py
Allow use of non-C++ projects by specifying the language in the workflow file.
Fixes #5195
> [CIFuzz] Support languages non-C++ projects (e.g. Python projects)

- infra/base-images/base-builder/compile_go_fuzzer
- projects/cascadia/Dockerfile
- projects/go-json-iterator/Dockerfile
- projects/go-redis/Dockerfile
- projects/go-redis/build.sh
Completes/fixes #5221 
Tested with go-coredns, prometheus, golang, golang-protobuf
For cilium, `go get` fails so I guess this is another specific problem not related to fuzzing...
For other projects, I did not find a good generic way
- go-redis : `go get` seems to get an old version (without fuzz targets), then I need a local build (ie `compile_go_fuzzer ./fuzz` instead of `compile_go_fuzzer github.com/go-redis/redis/fuzz`) otherwise I get `no required module provides package github.com/go-redis/redis/fuzz`
- cascadia : I get the error `missing go.sum entry; to add it: go mod download golang.org/x/net` So I added this command to the Dockerfile
- go-json-iterator : the fuzz target living in oss-fuzz repo was no longer copied in the right directory, looks like it was the only such project …
> Go 1.16 build fix with right parentheses

- infra/base-images/base-runner/run_fuzzer
This solves timeouts for various of the existing fuzzers. It would be nice to have AFL run on these as the fuzzers are working. The following projects are examples of where the timeout triggers:
https://github.com/google/oss-fuzz/pull/5152/
https://github.com/google/oss-fuzz/pull/5164
https://github.com/google/oss-fuzz/pull/5150
https://github.com/google/oss-fuzz/pull/5148
https://github.com/google/oss-fuzz/pull/5147
> infra: update the timeout of AFL

- infra/base-images/base-builder/Dockerfile
- infra/base-images/base-runner/run_fuzzer
fixes for afl++ (gdal, rocksdb, valijson, likely more)
> Fixes for afl++

- projects/git/build.sh
The oss-fuzz git ASAN build fails due to a leak inside git iself:
the build script builds a copy of git, and then uses that binary to
prepare the corpus - and although the git invocation itself
succeeds, ASAN causes the script to fail due to the leak:
https://oss-fuzz-build-logs.storage.googleapis.com/log-2eee2921-1b3f-4dd8-a902-50474e8fed55.txt
This was reproduced locally using:
$ python infra/helper.py build_fuzzers --sanitizer address git
Disabling leak checking for all invocations of git in the script
is enough to avoid this failure, and has been verified to fix
the build locally.
The leak itself is being fixed in git in the following commit (which
is now in next, which I believe is what oss-fuzz is building):
https://git.kernel.org/pub/scm/git/git.git/commit/?id=bf4bb9f9f5130a7b299f78 …
> Fix git build by ignoring leaks in build.sh

- projects/p11-kit/project.yaml
This changes my address to be the gmail one, so I can access the logs.
> [p11-kit] Use gmail address for the maintainer

- projects/md4c/project.yaml
The original e-mail address `martin.mitas@gmail.com` is associated with a gmail account which is unused and became sort of a zombie years ago, and I am not able even to login into it anymore. (But it still prevents me to use the e-mail as an alternative with my active google account.)
Consequently, I'm unable to get into the reports generated by the fuzz testing.
The `mity@morous.org` is actually an alias of the same mailbox but it was successfully used as an alternative in a newer and active gmail account.
Sorry for the inconvenience.
> Md4c: Update primary_contact e-mail address

- projects/java-example/ExampleFuzzer.java
- projects/java-example/ExampleFuzzerNative.java
- projects/java-example/ExampleValueProfileFuzzer.java
- projects/json-sanitizer/DenylistFuzzer.java
- projects/json-sanitizer/IdempotenceFuzzer.java
- projects/json-sanitizer/ValidJsonFuzzer.java
Jazzer has made fuzzerTestOneInput return void instead of boolean (see https://github.com/CodeIntelligenceTesting/jazzer/commit/541c5c63f1f1e3025da8073fc106a7ffe5ce73b2). This commit adapts the existing Jazzer fuzz targets to this change.
Previously, returning true from a fuzz target would be recorded as a crash. However, since there is no stack trace in that case, such crashes cause issues with deduplication. Additionally, the behavior is easy to replicate with assert or a an if with a throw statement.
> [jazzer] Migrate projects to new void fuzzerTestOneInput

- infra/base-images/base-builder/compile_libfuzzer
Instead of recompiling libFuzzer each time we do a libFuzzer
build of a project, use Clang's builtin version of libFuzzer.
Do this by copying the builtin libFuzzer to /usr/local/lib/FuzzingEngine.a.
This change improves fuzzing performance and developer experience.
1. It improves developer experience by saving time spent compiling libFuzzer
when recompiling fuzzers.
The time saved is about 25 seconds on my machine.
This will make iterating on fuzzer integration much easier.
2. It improves fuzzer performance. The builtin libFuzzer isn't sanitized so it is faster.
In some cases (see [here](https://bugs.chromium.org/p/chromium/issues/detail?id=934639))
sanitized libFuzzers can waste 37% of the time running non-performant implementations
of code that the builtin-libFuzzer can do almost …
> [base-builder] Use builtin libFuzzer instead of recompling.

- docs/getting-started/new-project-guide/python_lang.md
I've been writing up a comparison of test generation / fuzz-harness generation tools, and it occurred to me that the OSS-Fuzz docs should probably recommend using [the Ghostwriter](https://hypothesis.readthedocs.io/en/latest/ghostwriter.html) to generate harnesses if you're using Hypothesis.  TLDR: unlike FUDGE or FuzzGen, this is a fast+static analysis; and it provides useful template code even if the harness isn't complete.
Plus a typo fix.
> Docs: recommend "ghostwriting" Python harnesses

- infra/base-images/base-builder/Dockerfile
- infra/base-images/base-runner/run_fuzzer
among other fixes, this changes the -t + parameter to autodetect the timeout value to up to the specified value, depending on the slowest seed in the initial corpus.
maybe it is time now to switch to the stable branch of afl++ so the commit id doesnt need to be updated anymore?
> afl++ commit id update

- projects/java-example/Dockerfile
- projects/java-example/build.sh
- projects/java-example/default.options
- projects/json-sanitizer/build.sh
Prior to this change, native library loading failed for
two reasons:
1. Loading from current working directory instead of the fuzzer's
directory.
2. Using ASAN_OPTIONS=handle_segv=2.
Fix these issues by doing the following.
1. Adding the fuzzer's directory to LD_LIBRARY_PATH instead of "."
2. Specifying handle_segv=1 in ASAN_OPTIONS.
Related #5178.
> [jazzer][java-example] Fix native library loading.

- projects/libyang/project.yaml
Add a gmail account to get access to the detailed reports.
> libyang: give access to the bug reports

- projects/libredwg/build.sh
don't test unstable non-release preR13 paths.
add dwg specific memory options, as used locally. Those files get big.
> libredwg: update options

- projects/envoy/project.yaml
Adds Arquebus service to Envoy for auto-assigning bugs on monorail.
Also adds Chaoqin's Google username now that he has a LDAP
@chaoqin-li1123
> [envoy] add arquebus service for auto-assigning

- infra/base-images/base-clang/checkout_build_install_llvm.sh
- infra/ci/build.py
Reduce build time by doing the following:
1. Building the second stage clang build with a clang binary we download
from chromium.
2. Changing NPROC to be half of the cores instead of assuming it's 16
cores. This still addresses the OOM when building on GCB but speeds up
local building.
3. Don't install recommended packages and use --depth 1 when possible
(very minor improvements compared to the above).
In all this reduces local build time of base-clang from 32 minutes
to 11 minutes.
Because build times are improved so much, also build base-clang
when testing infra changes in CI.
Also because build times are reduced, it will be easier to
iteratively develop changes needed for #5170
> [base-clang] Reduce build time by ~65%

- infra/base-images/base-builder/Dockerfile
- infra/base-images/base-builder/compile_afl
- infra/base-images/base-builder/compile_honggfuzz
- infra/base-images/base-builder/precompile_afl
- infra/base-images/base-builder/precompile_honggfuzz
Precompile AFL like we already do for honggfuzz.
This saves about a minute in compilation time of AFL targets by doing it in base-builder
It only adds about 30 MB to the image size.
It may make debugging breakages somewhat harder for @vanhauser-thc, since it won't be so easy to interactively change the env vars that control AFL compilation.
I was able to run a lot of the tests which passed. However, the unittests require cmocka and failed.
I don't think we need to run these. Maybe we can get another make target that runs tests that don't require these and we can run them during build. We could also look into installing cmocka to run these tests but I think that is another discussion.
Related: #5275
> [AFL++][base-builder] Precompile afl++

- projects/openssh/build.sh
I recently added a ssh-agent fuzzer to OpenSSH and a corresponding seed corpus. This enables them in oss-fuzz.
> Enable ssh-agent fuzzer

- infra/base-images/base-runner/Dockerfile
Reduce image size by:
1. Not installing go toolchain in final image. Build go tools in
seperate image that doesn't become base-runner.
2. Download the JVM zip in the same step we remove it.
> [base-runner] Reduce image size by 45% (645 MB).

- projects/tensorflow/build.sh
It seems that due to some recent change in `BUILD` rules, `bazel` creates a copy of the code tree under `bazel-tensorflow/external/org_tensorflow` symlink. However, the tree contains a `bazel-tensorflow` symlink so we get to an infinite symlink expansion issue. This breaks coverage build.
The fix is simple: before copying `bazel-tensorflow/external` to `${OUT}` in coverage builds, remove `org_tensorflow` symlink. This is not an issue for the coverage build since we copy the entire source tree to the coverage directory in a previous step.
> Fix TensorFlow coverage build.

- projects/clamav/Dockerfile
- projects/clamav/build.sh
For the CMake build, build all dependencies as static libraries first.
To automate this, the Dockerfile uses the Mussels tool.
The HAVE_MMAP variable is explicitly disabled so that malloc is used in
place of mmap, which will yield better fuzzing results.
> [clamav] Switch from autotools to cmake

- projects/dropbear/Dockerfile
- projects/dropbear/project.yaml
Use the official Dropbear github mirror since cifuzz needs github
> dropbear: Use github so cifuzz might work

- projects/dropbear/Dockerfile
- projects/dropbear/build.sh
cifuzz replaces the dropbear source directory, which won't work if the corpus directory is within it
> dropbear: move corpus out of the source checkout

- projects/proj4/Dockerfile
Builds are currently broken since running libtiff ./autogen.sh requires
wget
```
autoconf
echo ./autogen.sh: getting config.guess...
./autogen.sh: getting config.guess...
wget -q --timeout=5 -O config/config.guess.tmp https://git.savannah.gnu.org/cgit/config.git/plain/config.guess
```
> proj4/Dockerfile: install wget

- infra/base-images/base-builder/Dockerfile
- infra/base-images/base-builder/cargo
- infra/base-images/base-builder/compile
- infra/base-images/base-clang/checkout_build_install_llvm.sh
- infra/base-images/base-runner/Dockerfile
- infra/base-images/base-runner/coverage
- infra/base-images/base-runner/rcfilt
- infra/build/functions/build_and_run_coverage.py
- infra/ci/build.py
- infra/helper.py
- projects/suricata/Dockerfile
- projects/suricata/build.sh
- projects/suricata/rustc.py
cc @inferno-chromium and @Dor1s 
Fixes #4637 
This will work when https://github.com/rust-lang/rust/pull/79365 gets merged into rust nightly compiler and gets shipped into oss-fuzz docker images (or if you recompile rustc)
This is a draft PR.
The right one will not use a custom patch for Suricata, but wait until https://github.com/OISF/suricata/pull/5595 is merged
Last, there is a question about the demangler
As some project may have both C++ and Rust, I think that the demangler should be a custom one basically doing `rustfilt | c++filt -n`
Do you have thoughts on that ?
> Rust coverage report (for Suricata)

- infra/base-images/base-runner/Dockerfile
Go needs the toolchain for now, so add it back to base-runner (Fixes #5316)
We don't actually need the rust toolchain so get rid of it,
saving about 1GB (related #5180 and #5170).
> [base-runner] Fix go issue and remove uneeded rust stuff.

- projects/libvips/Dockerfile
- projects/libvips/build.sh
This should fix the currently-failing libvips build - see https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=31530
> [libvips] Ensure linker is aware of selinux/resolv dependencies

- projects/gitea/project.yaml
The email should be sent to the security email address of Gitea but not the admin email address. For trust proof, I'm one of the Owners of Gitea. https://github.com/go-gitea/gitea/blob/master/CONTRIBUTING.md#owners
> Use a special email address to manage security

- projects/go-sftp/Dockerfile
- projects/go-sftp/build.sh
- projects/go-sftp/project.yaml
cc @drakkan
Would you be interested in continuous fuzzing for sftp ?
I see that you already have a fuzz target, and it quickly finds `panic: runtime error: index out of range [3] with length 1` in `sftp.unmarshalUint32`
> Adds go-sftp project

- projects/gpac/Dockerfile
- projects/gpac/build.sh
- projects/gpac/fuzz_parse.c
- projects/gpac/project.yaml
GPAC started more than 20 years ago to demonstrate the features of the MPEG-4 Standard which includes ISOBMFF. Soon, GPAC’s MP4Box became the MP4 swiss-army knife used worldwide by MP4 aficionados, by multimedia researchers and by media companies in production (Netflix uses it https://netflixtechblog.com/optimizing-the-aural-experience-on-android-devices-with-xhe-aac-c27714292a33 - the project is also called "MP4Box" which is referenced in the blog)
> gpac: initial integration

- projects/libfido2/Dockerfile
- projects/libfido2/build.sh
libfido2 now requires zlib. While here, also bump libcbor to v0.8.0.
> libfido2: update dependencies

- .dockerignore
- infra/.dockerignore
- infra/cifuzz/cifuzz-base/Dockerfile
Reduce cifuzz-base size from 846MB to 444MB.
1. Don't install parts of docker that aren't necessary.
2. Install docker-ce-cli via deb instead of apt.
3. Use .dockerignore properly.
Related to #5180 and #5170
> [CIFuzz][cifuzz-base] Slim down cifuzz-base

- infra/base-images/base-runner/Dockerfile
Don't install recommended packages if it means installing an
entire gcc toolchain. We don't need it in the runner.
> [base-runner] Reduce size by ~200 MB by using apt better

- infra/base-images/base-builder/cargo
cc @inferno-chromium 
Should fix #5341 
Rust cargo does not use absolute paths for the current crate being built
So we need to hack it with `RUSTFLAGS --remap-path-prefix`
As `cargo fuzz` works both in the `fuzz` directory and its parent (and is so used in oss-fuzz)
we change to the `fuzz` directory.
But we need to set the ` --remap-path-prefix` after changing the directory
Thanks @jrmuizel for the report
> Rust coverage : source remap after changing dir

- projects/json-sanitizer/DenylistFuzzer.java
- projects/json-sanitizer/IdempotenceFuzzer.java
- projects/json-sanitizer/ValidJsonFuzzer.java
Annotates the findings of the various json-sanitizer fuzzers with
severities as follows:
* XSS: High
* Comment injection: Medium
* Invalid JSON: Low
* Failure to be idempotent: Not a security issue
* Undeclared exceptions: Not a security issue
This commit takes advantage of the support for severity markers in stack
traces introduced in https://github.com/google/clusterfuzz/pull/2270.
> [json-sanitizer] Add severity markup

- projects/suricata/build.sh
Taken from libra and cargo fuzz
Rust coverage is pretty low for Suricata
Using env variable `FUZZ_APPLAYER=29` and running the target fuzz_applayerparserparse, I find in minutes paths that are not in the corpus
Have you any idea why ? Is this because of hash collision in this large target ?
> Use more RUSTFLAGS for Suricata

- .github/workflows/infra_tests.yml
- .github/workflows/presubmit.yml
- .github/workflows/project_tests.yml
👋 hello there! I'm a fellow Googler who works on projects that leverage GitHub Actions for CI/CD. Recently I noticed a large increase in our queue time, and I've tracked it down to the [limit of 180 concurrent jobs](https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration) for an organization. To help be better citizens, I'm proposing changes across a few repositories that will reduce GitHub Actions hours and consumption. I hope these changes are reasonable and I'm happy to talk through them in more detail.
- Only run GitHub Actions for pushes and PRs against the main branch of the repository. If your team uses a forking model, this change will not affect you. If your team pushes branches to the repository directly, this changes actions to only run against the …
> Improve Actions hygiene

- projects/protobuf-c/Dockerfile
- projects/protobuf-c/build.sh
- projects/protobuf-c/project.yaml
- Fix protobuf-c coverage builds (https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=27674)
- Use pkg-config for more readable dependency resolution
- Use the `next` branch in protobuf-c to test latest code
- Add myself to CCs
cc @guidovranken
> protobuf-c: fix coverage builds, use latest code

- projects/firefox/Dockerfile
- projects/spidermonkey-ufi/Dockerfile
- projects/spidermonkey/Dockerfile
For some reason, the presence of this wrapper breaks the build process of Firefox and Spidermonkey. I was not able to figure out so far why exactly this breaks, but I was able to confirm that this wrapper is the source of the problem and that we can get the builds back up and running my removing it in our images.
> [firefox/spidermonkey] Remove cargo wrapper in /usr/local/bin to fix builds

- infra/base-images/base-builder/cargo
cc @alexcrichton for the tip in https://github.com/google/oss-fuzz/pull/4697#discussion_r591889184
(just needed to add `-r` to jq)
This should fix wasmtime coverage build (works locally)
> More generic target directory for rust coverage

- projects/fastjson2/Dockerfile
- projects/fastjson2/JsonFuzzer.java
- projects/fastjson2/build.sh
- projects/fastjson2/project.yaml
@wenshao OSS-Fuzz uses [Jazzer](https://github.com/CodeIntelligenceTesting/jazzer) under the hood to test Java projects, which is the fuzzer that found the issues in https://github.com/alibaba/fastjson/issues/3631. It will continuously test the newest revision in the https://github.com/alibaba/fastjson repository and send actionable reports about bugs (OutOfMemoryError, undeclared exceptions) to your GitHub email (see [the project config](https://github.com/google/oss-fuzz/compare/master...CodeIntelligenceTesting:fastjson2?expand=1#diff-de1d9d931afd47b420363a2c5adcece244da7e22b1b01bcaaa7d116ceff3e660R3)). If you would like to use a different (or additional) email addresses or have any general questions about the OSS-Fuzz integration, let me know.
> [fastjson2] Initial integration of alibaba/fastjson

- projects/json5format/Dockerfile
- projects/json5format/build.sh
- projects/json5format/fuzz/.gitignore
- projects/json5format/fuzz/Cargo.toml
- projects/json5format/fuzz/fuzz_targets/fuzz_parse.rs
- projects/json5format/project.yaml
@richkadel - is it in the interest to enable fuzzing of json5format? There are already quite a few of Google's open source repositories on OSS-Fuzz and I thought it would be nice to get json5format on as well. The goal is to catch undesired panics - and the fuzzer I attached to this PR finds a panic instantly (check the failing test in the CI). Let me know! We can also move the fuzzers to the upstream json5format repository.
> json5format initial integration

- infra/base-images/base-builder/compile_go_fuzzer
- infra/base-images/base-runner/coverage
cf #5537
We can indeed build a golang test program in base-builder, so we do not any longer need gcc in base-runner
This also should help getting rid of the directory logic...
> Golang coverage: build binary instead of bash script

- infra/cifuzz/fuzz_target.py
Sometimes deleting the corpus in free_disk_if_needed exceptions.
Pass ignore_errors=True to fix this.
Related: https://github.com/google/oss-fuzz/issues/5383
> [CIFuzz] Fix issue deleting corpus

- projects/openexr/build.sh
OpenEXR 3.0, and the main branch, has accepted a PR to merge libIexMath
into libIex, to lower dependencies. Remove it from the list of libraries
and further sort by dependency order
Signed-off-by: Kimball Thurston <kdt3rd@gmail.com>
> Fix #32074 issue with oss-fuzz using old openexr library

- projects/go-snappy/Dockerfile
- projects/go-snappy/build.sh
- projects/go-snappy/fuzz.go
- projects/go-snappy/project.yaml
@nigeltao would you be interested in continuous fuzzing for snappy ?
This PR enables it on oss-fuzz.
The simple `Decode` fuzz target quickly runs out of memory
I think that there needs to wait a bit before allocating a big slice in https://github.com/golang/snappy/blob/196ae77b8a26000fa30caa8b2b541e09674dbc43/decode.go#L65
I have encountered the same problem with lzma in Suricata, ending up in customizing the lzma library so as not to get denial of service by memory exhaustion
cc @dgrinsky, as I see that you fuzzed snappy already
> Adds golang snappy project

- projects/cel-cpp/.bazelrc
- projects/cel-cpp/BUILD
- projects/cel-cpp/Dockerfile
- projects/cel-cpp/WORKSPACE
- projects/cel-cpp/build.sh
- projects/cel-cpp/fuzz_parse.cc
- projects/cel-cpp/project.yaml
@kyessenov would you be interested in continuous fuzzing for cel-cpp ?
This Pull Request enables it with oss-fuzz adding one simple fuzz target for `parser::Parse` which could be added to the upstream repository
This fuzz target quickly finds an unhandled exception
Should I wrap it into a `try catch (const std::exception& e)` ?
> Adds cel-cpp project

- infra/base-images/base-builder/compile_go_fuzzer
- infra/base-images/base-runner/coverage
- infra/base-images/base-runner/gocoverage/gocovsum/gocovsum.go
This should fix golang coverage build (and keep working for future go 1.17)
Core problem is that `go test -cover` does not output absolute paths in profile data, but golang-ish `pkg.Dir`
While building the fuzz targets, we can output a file containing the translation
And then use this translation in `run_go_fuzz_target` function when running coverage
> Golang coverage: use absolute paths

- infra/base-images/base-runner/gocoverage/gocovsum/gocovsum.go
cf #5337 cc @jonathanmetzman 
On gonids sample, I get
```
{"data":[{"totals":{"functions":{"count":105,"covered":52,"notcovered":53,"percent":49.523809523809526},"lines":{"count":942,"covered":578,"notcovered":364,"percent":61.3588110403397},"regions":{"count":670,"covered":388,"notcovered":282,"percent":57.91044776119403},"instantiations":{"count":0,"covered":0,"notcovered":0,"percent":0},"branches":{"count":0,"covered":0,"notcovered":0,"percent":0}},"files":[{"summary":{"functions":{"count":1,"covered":1,"notcovered":0,"percent":100},"lines":{"count":23,"covered":11,"notcovered":12,"percent":47.82608695652174},"regions":{"count":13,"covered":7,"notcovered":6,"percent":53.84615384615385},"instantiations":{"count":0,"covered":0,"notcovered":0,"percent":0},"branches":{"count":0,"covered":0, …
```
> Golang coverage summary updated to version 2.0.1

- infra/base-images/base-builder/compile_go_fuzzer
as is done by gofuzz build
cc @cyriltovena
Loki uses `gofuzz` tag which was not used by default for coverage.
And `go list -m` gives absolute path for /src/loki even if there are no Go files in it but there is a go.mod
> Go coverage : use gofuzz tag by default

- infra/cifuzz/run_fuzzers.py
- infra/cifuzz/run_fuzzers_test.py
Don't just call them $TARGET-$SANITIZER-testcase.
Instead include the real names.
Fixes: https://github.com/google/oss-fuzz/issues/5384
> [CIFuzz] Give testcases unique names.

- infra/base-images/base-clang/checkout_build_install_llvm.sh
Delete unneeded LLVM tools, clang libraries and testing tools.
This reduces the image size from 1.71 GB to 901 MB.
It may be possible to improve on this by deleting some LLVM +lld
libraries though I don't know which ones we should delete
(because AFL++ might use some). These are about 120 MB in size.
Related https://github.com/google/oss-fuzz/issues/5170
> [base-clang] Reduce base-clang size by deleting unneeded things

- infra/base-images/base-builder/compile_go_fuzzer
cc @inferno-chromium cc @jonathanmetzman 
Typo was introduced in #5425
> Fix typo in path equilavence for golang coverage

- projects/firefox/Dockerfile
- projects/firefox/build.sh
- projects/spidermonkey-ufi/Dockerfile
- projects/spidermonkey-ufi/build.sh
- projects/spidermonkey/Dockerfile
- projects/spidermonkey/build.sh
This should fix/unblock the spidermonkey build. There is an additional failure in the Firefox build but it is unclear what the problem is. Logged at https://bugzilla.mozilla.org/show_bug.cgi?id=1698626.
> [firefox/spidermonkey] Fix mach call and install dep

- projects/firefox/build.sh
- projects/firefox/mozconfig.address
While trying to get the Firefox build to work locally, I found 3 issues:
1) A recent change in our build system causes a particular binary used during the Rust build process to be built with ASan and it seems to have issues that LeakSanitizer detects and that fails the build.
2) Apparently we did not properly ignore the `CFLAGS` set in the environment and that caused another recent build problem.
3) It looks like the newest Rust Nightly doesn't build mozilla-central properly. It is never guaranteed that any newer Rust Nightly does build because we usually have a Rust Nightly version pinned in CI for sanitizers. I've modified the build to use the exact same version (I agree this is fragile, but it is probably more robust than simply using the newest version).
With these changes, the build …
> [firefox] Fix various build problems

- projects/nom/Dockerfile
- projects/nom/build.sh
- projects/nom/fuzz/.gitignore
- projects/nom/fuzz/Cargo.toml
- projects/nom/fuzz/fuzz_targets/fuzz_arithmetic.rs
- projects/nom/project.yaml
Nom is a library used for writing parsers in Rust. It is used in a *ton* of parsers written in Rust: https://github.com/Geal/nom#parsers-written-with-nom
@Geal would you be interested in integrating nom into oss-fuzz? By way of OSS-Fuzz we can add fuzzers to nom and run them continuously - you will then receive reports whenever crashes are found. If you would like to integrate, could you please provide a set of email(s) that will get access to the data produced by OSS-Fuzz, such as bug reports. The emails should be linked to a Google account in order to view the detailed reports and notice the emails affiliated with the project will be public in the OSS-Fuzz repo, as they will be part of a configuration file.
> nom: initial integration

- projects/wasmtime/build.sh
cc @alexcrichton cf https://github.com/google/oss-fuzz/pull/5366#issuecomment-799476131
This should fix wasmtime coverage build
> Wasmtime: remaps for coverage

- infra/base-images/base-builder/Dockerfile
The comment is meant to be on the line with the package removal.
> [NFC][base-builder] Fix order so comment is in right place

- projects/capstone/build.sh
Reverts google/oss-fuzz#5464
Looks like @vanhauser-thc has a better fix in https://github.com/google/oss-fuzz/pull/5462/files
> Revert "Capstone: do not use flags for corpus building"

- infra/base-images/base-builder/Dockerfile
This reduces base-builder size by about 100MB
> Delete unneeded files from cargo-fuzz install

- infra/bisector.py
- infra/repo_manager.py
Repos cloned with `--branch BRANCH` will only track that branch, even
when we unshallow. If we provide a git SHA from another branch, it will
not be recognized.
To fix, this, we update the remote tracking config and fetch them.
For https://github.com/google/osv/issues/88.
> Fix bisection when the original checkout is for a single branch.

- projects/suricata/Dockerfile
Cf https://github.com/google/oss-fuzz/issues/5479
pcre2 is not yet a dependency, but there is a PR about it cf https://github.com/OISF/suricata/pull/5991, so CIFuzz can get ready
> Adds pcre2 as suricata dependency

- infra/build_specified_commit.py
We need to redo fetch_all_remotes as we re-copy the repo from the docker
container.
> build_specified_commit: Add call to fetch_all_remotes on cleanup.

- projects/libfido2/Dockerfile
libfido2's fuzz corpora will soon have a new home; this PR reflects the change in the project's Dockerfile.
> libfido2: change location of fuzz corpora

- projects/qemu/project.yaml
We don't do any internal tests using honggfuzz, and our code is highly
unlikely to work with honggfuzz in the current shape. All of the
true-positive bugs seem to be libfuzzer bugs.
Lets disable honggfuzz, to avoid wasting resources. We will try to get
afl++ working, before taking another look at honggfuzz.
> qemu: disable honggfuzz fuzzing

- projects/tensorflow/build.sh
This should fix coverage build broken again today. It seems that a recent change in TF toolchains removed the creation of `org_tensorflow` but it is likely that this change will be rolled back in the future.
Hence, to keep OSSFuzz working, we conditionally remove this symlink at least until we fully stabilize the toolchains story.
> Only remove `external/org_tensorflow` if it exists

- projects/wuffs/build.sh
MAP_ANONYMOUS, getpagesize and strnlen do not mix with c99.
Updates #32432 "wuffs: Fuzzing build failure"
> [wuffs] Don't build with -std=c99

- projects/ghostscript/Dockerfile
- projects/ghostscript/build.sh
This makes it easier to build the fuzzer using a locally checked
out git repo without having to manually copy the fuzzer glue code
into the locally checked out git repo first.
> [ghostscript] Copy fuzzer glue code to dir outside of git repo

- projects/lxc/Dockerfile
- projects/lxc/build.sh
- projects/lxc/fuzz-lxc-config-read.c
- projects/lxc/project.yaml
It seems to be working in the sense that the fuzz target has found a bunch of issues like
```
==13==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7f90db82553f at pc 0x00000067ebde bp 0x7ffcfe224790 sp 0x7ffcfe224788
READ of size 1 at 0x7f90db82553f thread T0
SCARINESS: 27 (1-byte-read-stack-buffer-overflow)
#0 0x67ebdd in parse_byte_size_string /src/lxc/src/lxc/string_utils.c:926:24
#1 0x426525 in set_config_console_buffer_size /src/lxc/src/lxc/confile.c:2436:8
#2 0x5b2f04 in parse_line /src/lxc/src/lxc/confile.c:2953:9
#3 0x448691 in lxc_file_for_each_line_mmap /src/lxc/src/lxc/parse.c:125:9
#4 0x5b27e5 in lxc_config_read /src/lxc/src/lxc/confile.c:3024:9
#5 0x581c03 in LLVMFuzzerTestOneInput /src/fuzz-lxc-config-read.c:18:2
#6 0x484783 in …
```
> [lxc] initial integration

- projects/lxc/project.yaml
The other two mail addresses are aliases and so we can't use them to
access oss-fuzz.
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>
> projects/lxc: update mail addresses

- projects/wasmtime/build.sh
In bytecodealliance/rfcs#10, we have outlined a process by which we're
switching to a new compiler backend by default. The first step in this
process is to switch our fuzzing targets to use the new backend and wait
for any issues.
This PR adds the Cargo feature that enables the new backend in all
fuzzing targets.
> Update wasmtime config to use new x86-64 backend.

- projects/libjpeg-turbo/Dockerfile
libjpeg-turbo 2.1 now requires NASM 2.13 or later or YASM 1.2.0 or
later.  Since the Docker image is based on Ubuntu 16.04, NASM 2.13 isn't
available, so the easiest workaround is to use YASM instead.
Fixes #4931
> [libjpeg-turbo] Fix build with libjpeg-turbo 2.1.x

- projects/nom/Dockerfile
nom's build fails since #5499 because I forgot that the Dockerfile was trying to move the deleted repository
failing build log:
```
FETCHSOURCE
BUILD
Starting Step #0
Step #0: Already have image (with digest): gcr.io/cloud-builders/git
Step #0: Cloning into 'oss-fuzz'...
Finished Step #0
Starting Step #1
Step #1: Already have image (with digest): gcr.io/cloud-builders/docker
Step #1: Sending build context to Docker daemon   5.12kB
Step #1: Step 1/5 : FROM gcr.io/oss-fuzz-base/base-builder
Step #1: latest: Pulling from oss-fuzz-base/base-builder
Step #1: 4007a89234b4: Pulling fs layer
Step #1: c1de0f9cdfc1: Pulling fs layer
Step #1: c8ee6ca703b8: Pulling fs layer
[...]
Step #1: 1af9f6a7b423: Pull complete
Step #1: Digest: sha256:8cf82e8ef96b1d7d89360c40115207eceb8c317c16c1219bb5fe82522aacd3 …
```
> the fuzz directory was moved to nom's repository

- projects/skia/build.sh
Requires https://skia-review.googlesource.com/c/skia/+/389736 to land first.
> [skia] Add Region Op fuzzer

- projects/wasmtime/project.yaml
@inferno-chromium: sorry, I think this Gmail address should work better for me. The previous one is limited by the corporate account control.
> [wasmtime] Tweak member e-mail
