- projects/ffmpeg/Dockerfile
> projects/ffmpeg/Dockerfile: Update git URLs for xiph

- projects/serde_json/Dockerfile
- projects/serde_json/build.sh
- projects/serde_json/project.yaml
[serde-json](https://github.com/serde-rs/json) is a core library for working with json in Rust. 
[Cross-referencing](https://github.com/serde-rs/json/pull/668)
This has been coordinated with the authors of serde-json, in particular @dtolnay.
> [serde-json] initial integration.

- projects/solidity/build.sh
Fixes failing build (clusterfuzz id 22205)
> solidity: Fix solidity proto fuzzer failing build

- docs/getting-started/new_project_guide.md
For test locally - coverage sanity check support.
cc: @lszekeres
> [doc] Update new_project_guide.md

- infra/base-images/base-builder/Dockerfile
- infra/base-images/base-builder/compile
- projects/ecc-diff-fuzzer/Dockerfile
- projects/libra/Dockerfile
- projects/libra/build.sh
- projects/mp4parse-rust/Dockerfile
- projects/serde_json/Dockerfile
- projects/wasmtime/Dockerfile
- Add rust and cargo-fuzz in base builder.
- Set RUSTC_BOOSTRAP to make ASan available.
- Set RUSTFLAGS and C,CXXFLAGS properly.
> Simplify rust project setup.

- infra/cifuzz/actions/build_fuzzers/build_fuzzers_entrypoint.py
Closes https://github.com/google/oss-fuzz/issues/3732
> cifuzz: use pull_request.number instead of GITHUB_REF

- projects/minify/build.sh
The build script has been moved upstream. This PR updates the build script here accordingly.
> [minify] Moved build script upstream

- infra/base-images/base-builder/Dockerfile
Add features needed by firefox and spidermonkey-ufi builds.
> Use latest git version.

- infra/base-images/base-builder/Dockerfile
> Install Python 3.8.3 on builder image.

- projects/qt/Dockerfile
Reduces the size by nearly 200 MB
> [qt] Get a shallow clone of qtbase

- infra/build_specified_commit.py
> build_specified_commit: Don't replace gitdir if already relative.

- projects/envoy/project.yaml
Add Envoy interns and hosts to OSS-Fuzz.
> [envoy] add hosts and interns

- projects/hermes/project.yaml
Add an additional CC for issues
> [hermes] Add CC for issues

- projects/systemd/project.yaml
See https://github.com/google/oss-fuzz/issues/3887
> [systemd] turn off hongfuzz

- infra/base-images/base-builder/Dockerfile
> Remove libbz2-dev dependency installed in base-builder for python3

- projects/systemd/project.yaml
Reverts google/oss-fuzz#3889
Looks like I was too quick to open that PR. Sorry about that.
> Revert "[systemd] turn off hongfuzz"

- projects/libgd/Dockerfile
- projects/libgd/build.sh
- projects/libgd/gd_image_string_fuzzer.cc
Add another fuzz target for libgd.
> [libgd] Add another fuzzer to libgd

- projects/libzmq/project.yaml
honggfuzz selftest works now, enable it
> libzmq: enable honggfuzz

- projects/prometheus/Dockerfile
...to myself (Prometheus co-creator).
Signed-off-by: Julius Volz <julius.volz@gmail.com>
> Update Prometheus maintainer in Dockerfile

- projects/ffmpeg/Dockerfile
Fixes: Issue 22500 (build failure)
> [FFmpeg] install rsync as it is required for the seed corpus

- infra/build_specified_commit.py
To mitigate transient network issues.
> Retry building project images in build_specified_commit.

- projects/zlib-ng/project.yaml
Added myself to zlib-ng project. @Dead2
> Added contact to zlib-ng project auto_ccs.

- projects/envoy/project.yaml
> [envoy] add randy smith

- projects/xpdf/Dockerfile
- projects/xpdf/build.sh
Xpdf added support for a latest-version download link to support continuous fuzzing.
> Updated the docker and build of xpdf 

- infra/base-images/base-builder/Dockerfile
- projects/avahi/Dockerfile
- projects/dav1d/Dockerfile
- projects/gdal/Dockerfile
- projects/hostap/Dockerfile
- projects/hunspell/Dockerfile
- projects/imagemagick/Dockerfile
- projects/libxml2/Dockerfile
- projects/openh264/Dockerfile
- projects/proj4/Dockerfile
- projects/qt/Dockerfile
> Install latest cmake, make easy to install i386 packages

- projects/qt/Dockerfile
- projects/qt/build.sh
It turned out that QQmlComponent::create() is not suitable for fuzzing.
This mostly reverts commit 0e401be9deabf739a2ea34b98e044b17bf83026e.
> Remove qtdeclarative

- projects/monero/Dockerfile
- projects/monero/build.sh
- projects/monero/project.yaml
Add Monero.
Note we closed similar PR #3921.
> Add Monero project

- projects/draco/Dockerfile
- projects/draco/build.sh
- projects/draco/fuzz/draco_decoder_fuzzer.cc
- projects/draco/project.yaml
Draco project initial integration
> Draco integration

- docs/getting-started/continuous_integration.md
- infra/cifuzz/actions/build_fuzzers/action.yml
- infra/cifuzz/actions/build_fuzzers/build_fuzzers_entrypoint.py
- infra/cifuzz/actions/run_fuzzers/action.yml
- infra/cifuzz/actions/run_fuzzers/run_fuzzers_entrypoint.py
- infra/cifuzz/cifuzz.py
- infra/cifuzz/cifuzz_test.py
- infra/cifuzz/fuzz_target.py
It's basically https://github.com/google/oss-fuzz/pull/3516 with a one-line commit fixing https://github.com/google/oss-fuzz/issues/3727 on top.
It's being tested in https://github.com/systemd/systemd/pull/16150 at the moment.
v2: A bug causing CIFuzz to prepend `$` in front of `sanitizer` was fixed in the last commit. Hope it was the last one.
> [CIFuzz] Add support for different sanitizers

- projects/skia/Dockerfile
- projects/skia/build.sh
- projects/skia/skia.diff
Skia is changing its build a little bit. 'skia_enable_fontmgr_custom' has become 'skia_enable_fontmgr_custom_directory' (since that is what it actually did) and skia_enable_fontmgr_custom_embedded has been added.
> [skia] Build fix for upstream build changes.

- projects/jsonparser/project.yaml
> [jsonparser] Added maintainer to project.yaml

- projects/libraw/Dockerfile
- projects/libraw/build.sh
- projects/libraw/libraw_fuzzer.cc
This PR adds corpuses and wider coverage for LibRaw.
> Increase coverage of libraw fuzzing

- projects/skia/BUILD.gn.diff
- projects/skia/Dockerfile
- projects/skia/build.sh
- projects/skia/svg_dom.options
> [skia] add svg fuzzer

- projects/abseil-cpp/BUILD
- projects/abseil-cpp/Dockerfile
- projects/abseil-cpp/WORKSPACE
- projects/abseil-cpp/build.sh
- projects/abseil-cpp/project.yaml
- projects/abseil-cpp/string_escape_fuzzer.cc
- projects/abseil-cpp/string_utilities_fuzzer.cc
Initial integration of abseil-cpp, 
Coverage report after running locally for 30 minutes:
src/	        40.38% (1964/4864)	 28.94% (180/622)	 40.43% (950/2350)
TOTALS	 40.38% (1964/4864)	 28.94% (180/622)	 40.43% (950/2350)
Requesting @derekmauro or anyone from abseil-cpp to review code.
> [abseil-cpp] Initial Integration

- projects/tensorflow/Dockerfile
- projects/tensorflow/build.sh
Add new fuzzer and ensure that it builds successfully.
> Cleanup build script, fix tensorflow build

- docs/getting-started/continuous_integration.md
This was discussed in https://github.com/google/oss-fuzz/pull/3969#discussion_r439145136
> [docs] switch to a matrix in the "sanitizer" example

- projects/usrsctp/project.yaml
I am an intern working on fuzzing usrsctp part. Here I adding my host email and my email for fuzzing reports. Thank you!
> Adding auto-cc to project usrsctp

- projects/lodepng/project.yaml
Adding email address to Auto CC to lodepng project. I have already asked @lvandeve on chat for this.
Purpose: To check if any new vulnerabilities in lodepng.
> Added auto-cc to lodepng project

- projects/skia/build.sh
The other builds were moved to Ninja, this one needs to be as well.
Bug: oss-fuzz:23438
> [skia] Fix coverage build to use Ninja.

- projects/json/project.yaml
Hi, I added my email to get fuzzing reports for this project. Thank you
> added auto-cc to json project

- projects/envoy/build.sh
- projects/envoy/project.yaml
Add intern arthuryan@
Try to fix build https://docs.bazel.build/versions/master/memory-saving-mode.html
> [envoy] Add arthur and use less memory

- docs/further-reading/fuzzer_environment.md
> Updated fuzzer_environment.md

- projects/qemu/Dockerfile
- projects/qemu/project.yaml
> QEMU: Add fuzz target build scripts

- projects/usrsctp/build.sh
- projects/usrsctp/project.yaml
Improving fuzzing coverage by disabling auth check
> Yuquanw branch

- projects/libxml2/build.sh
Enable HTML and XML Schema fuzzers.
> [libxml2] Two new fuzz targets

- projects/haproxy/project.yaml
This is requested by Willy Tarreau, one of the core maintainers of Haproxy.
> [Haproxy] Added two contacts to project.yaml

- .github/workflows/presubmit.yml
- .gitignore
- infra/.gitignore
- infra/build/functions/main.py
- infra/build/functions/requirements.txt
- infra/build/functions/test_sync.py
Integrating the first cloud function i implemented which syncs the project list from github and uploads the list to cloud datastore, which will be used by another cloud function to request builds.
@oliverchang 
> Cloud function for syncing OSS-Fuzz projects (#3538).

- .github/workflows/project_tests.yml
- infra/ci/build.py
- projects/util-linux/Dockerfile
- projects/util-linux/build.sh
- projects/util-linux/project.yaml
Waiting for https://github.com/karelzak/util-linux/pull/1068
> [util-linux] cover mnt_table_parse_stream

- projects/c-blosc2/Dockerfile
- projects/c-blosc2/build.sh
- projects/c-blosc2/project.yaml
This PR adds version 2 of c-blosc to OSS-Fuzz. @FrancescAlted
A previous discussion located [here](https://github.com/Blosc/c-blosc2/commit/099db918ea1e0eea81dae205e3aed0f61064994f).
> Add c-blosc2 project

- projects/influxdb/project.yaml
Requesting that InfluxDB be added to this project! If approved, will start working on the integration.
> Add influxdb project for review

- projects/sentencepiece/Dockerfile
- projects/sentencepiece/build.sh
- projects/sentencepiece/project.yaml
- projects/sentencepiece/sample_encode_fuzzer.cc
This adds sentencepiece to OSS-Fuzz as a start. 
https://github.com/google/sentencepiece/issues/445#issue-551474933
> Add sentencepiece

- projects/envoy/build.sh
Try to see if lowering to 75% helps memory usage
> [envoy] set local_cpu_resources

- projects/php/build.sh
This enables an additional fuzzer for recently added hash context serialization support.
> [php] Enable unserializehash fuzzer

- projects/libspng/Dockerfile
This step has been moved from the build script: https://github.com/randy408/libspng/commit/c35e509f04e46c2393a147f69e98a197f7615843
> [libspng] Fetch zlib in Dockerfile

- projects/skia/BUILD.gn.diff
- projects/skia/build.sh
> Add SkSVGCanvas api Fuzzer

- projects/oak/build.sh
Temporarily disable fuzzing for [project Oak](https://github.com/project-oak/oak). 
Ref #4053 and https://github.com/project-oak/oak/issues/539.
> Update the build script for project oak to disable it temporarily

- infra/ci/build.py
- projects/wasmtime/build.sh
Fixes https://github.com/google/oss-fuzz/issues/4074
> Skip coverage build in CI for non C/C++ projects.

- projects/cryptofuzz/Dockerfile
- projects/cryptofuzz/build.sh
- projects/cryptofuzz/project.yaml
- Update mbed TLS repository location
- mbed TLS: Enable components disabled by default
- wolfCrypt: Build AES key wrap ciphers
> [cryptofuzz] Build script updates

- projects/miniz/Dockerfile
- projects/miniz/build.sh
The fuzz targets and build script has been upstreamed: https://github.com/richgel999/miniz/pull/161
> [miniz] add Dockerfile, build.sh

- projects/harfbuzz/Dockerfile
- projects/harfbuzz/build.sh
As our migration to meson, pretty much shaped after ots's, let's see how it goes
> [harfbuzz] Use meson port

- projects/openexr/Dockerfile
- projects/openexr/build.sh
- projects/openexr/openexr_deepscanlines_fuzzer.cc
- projects/openexr/openexr_deeptiles_fuzzer.cc
- projects/openexr/openexr_scanlines_fuzzer.cc
- projects/openexr/openexr_tiles_fuzzer.cc
- projects/openexr/project.yaml
This commit adds a working `build.sh` to build a basic OpenEXR fuzzer from https://github.com/google/security-research-pocs.  I lazily just used an `ADD` command in the Dockerfile to get one fuzzer from there; you'll probably want to import that fuzzer directly, and perhaps add a few more.
> [openexr] Initial integration of OpenEXR fuzzers.

- infra/build/functions/sync/main_test.py
Changing the way emulator is being cleaned/reset between tests.
@oliverchang
> Resetting emulators

- infra/build/functions/base_image/build_base_images.py
- infra/build/functions/base_image/deploy.sh
- infra/build/functions/base_image/main.py
- infra/build/functions/base_image/requirements.txt
- infra/build/functions/requirements.txt
- infra/gcb/build_base_images.py
Base image builder, re structured the existing jenkins base image builder into a cloud function with schedule 3:00 everyday.
deploy script.
@oliverchang 
> Base image builder

- infra/build/functions/sync/main.py
- infra/build/functions/sync/main_test.py
> Renaming schedule variable to builds_per_day for new feature

- projects/harfbuzz/build.sh
- projects/harfbuzz/project.yaml
Like to enable experimental APIs on fuzzers so we can freely test them without actually exposing them first.
> [harfbuzz] Enable testing of experimental APIs also

- projects/skia/BUILD.gn.diff
- projects/skia/Dockerfile
- projects/skia/build.sh
> [Skia] Add SkRuntimeEffect Fuzzer

- projects/tensorflow/build.sh
Added flag to enable assert builds @mihaimaruseac
> Add assert compilation flag

- docs/getting-started/continuous_integration.md
Fixes
https://github.com/google/oss-fuzz/issues/3725
> Add CIFuzz documentation on how to run jobs on certain branches, paths

- projects/ots/build.sh
- projects/ots/project.yaml
As https://github.com/google/oss-fuzz/pull/4076 was following ots approach, let me see if things are okay here or needs similar fixes also.
> [ots] Enable more fuzzers

- projects/zetasql/Dockerfile
- projects/zetasql/build.sh
- projects/zetasql/project.yaml
This PR contains
- one new structure aware fuzzer that fuzzes arithmetic expressions in ZetaSQL.
- fix for UBSAN error.
> Onboarding new ZetaSQL fuzzers

- projects/mercurial/project.yaml
Should help (maybe fix) #4003.
> mercurial: ignore our sanitizer-built Python for coverage purposes

- projects/libssh/project.yaml
Give Anderson access to the libssh tracker.
Thanks.
> [libssh] Give Anderson access

- projects/zetasql/Dockerfile
- projects/zetasql/build.sh
This PR introduce a general way to index all fuzzers, which is proposed in #4095
> [zetasql] Correct fuzzer indexing

- projects/expat/build.sh
> [expat] Fix AddressSanitizer link errors (fixes #4143)

- projects/skia/build.sh
The SwiftShader build seems to want SWIFTSHADER_EMIT_COVERAGE set or it
will do things that interfere with a coverage build. Use this to
simplify the SwuftShader build a bit and hopefully restore the coverage
build.
> [skia] Pass SWIFTSHADER_EMIT_COVERAGE for coverage.

- projects/msgpack-c/Dockerfile
- projects/msgpack-c/build.sh
msgpack-c is now header only, update to install boost as req as well
> [msgpack-c] fix build

- infra/build/functions/badge_images
- infra/build/functions/builds_status.py
- infra/build/functions/datastore_entities.py
- infra/build/functions/deploy.sh
- infra/build/functions/main.py
- infra/build/functions/request_build.py
- infra/build/functions/request_build_test.py
- infra/build/functions/requirements.txt
- infra/build/functions/update_build_status.py
- infra/gcb/builds_status.py
Changes
-added logs bucket to build_project/ request_build
-added new datastore entity for storing build history of projects
Added update_builds_status function:
-Changed functionality of get_last_build by using cloud datastore
-refactored existing code to make some of it reusable.
-fixed all linting errors for builds_status.py
-Badge images are now downloaded from github and stored in /tmp folder available in cloud function's runtime.
@oliverchang 
@Dor1s 
> Initial integration of builds_status

- infra/gcb/sync.py
Migrating to new infratructure for requesting coverage jobs.
> Disable coverage job sync.

- projects/skia/BUILD.gn.diff
- projects/skia/build.sh
@kjlubick @jonathanmetzman 
Added DDL Fuzzer
> [Skia] Add DDL Fuzzer

- projects/assimp/Dockerfile
- projects/assimp/build.sh
- projects/assimp/project.yaml
> Enable assimp-fuzzing test

- projects/dropbear/Dockerfile
The upstream repository URL has changed
> [dropbear] Change Mercurial repo to hg.ucc.asn.au

- projects/openexr/openexr_deepscanlines_fuzzer.cc
Signed-off-by: Cary Phillips <seabeepea@gmail.com>
> move Header constructor inside try/catch

- infra/build/functions/request_build.py
- infra/build/functions/request_build_test.py
Fixing the unit test to reflect new changes,
@oliverchang
> Fixing missing dash in datastore query

- projects/harfbuzz/build.sh
- projects/harfbuzz/project.yaml
the real intention isn't to add space on those lines!! (or maybe better to remove it from the other sections?) but to make sure everything is in set after the merge of failing allocator https://github.com/harfbuzz/harfbuzz/pull/2566 and if isn't I can read CI bots failures logs.
In short, just a null edit.
> [harfbuzz] minor

- projects/envoy/build.sh
Avoids grepping for filenames with "_fuzz_test.cc" pattern, and instead finds bazel targets with the `fuzz_target` tag. 
This avoids a case where a fuzz test was temporarily disabled (by removing the build target), and OSS-Fuzz build crashes because it still tries to build the fuzz target.
> [envoy] Simplify finding fuzz targets by using a bazel query

- infra/gcb/templates/src/build-status/build-status.html
> Fix builds status page.

- projects/util-linux/build.sh
to make it easier to use CIFuzz to make sure https://github.com/karelzak/util-linux/pull/1068
is more or less in good shape.
> [util-linux] run tools/oss-fuzz.sh if it exists

- projects/speex/Dockerfile
> [speex] Remove use of out-of-date branch

- infra/build/functions/deploy.sh
- infra/build/functions/project_sync.py
- infra/build/functions/project_sync_test.py
- infra/build/functions/request_build.py
- infra/build/functions/request_coverage_build.py
- infra/build/request_all_builds.sh
- infra/build/request_build.sh
The single function for requesting all coverage builds was timing out.
Fixes #4233
> Create individual schedulers for requesting coverage builds.

- infra/base-images/base-builder/Dockerfile
- infra/base-images/base-clang/Dockerfile
Clang now needs a newer cmake to build.
> Move cmake install to base-clang.

- infra/build/functions/request_build.py
- infra/build/functions/request_coverage_build.py
- infra/gcb/build_and_run_coverage.py
- infra/gcb/build_project.py
-Moved skip build to build_project since build_and_run_coverage imports build_project
-Added build skipping for fuzzing build when project is disabled.
Can close #4149 after merging
@oliverchang
> Skipping fuzzing build when project is disabled

- projects/skia/BUILD.gn.diff
- projects/skia/Dockerfile
- projects/skia/build.sh
https://skia-review.googlesource.com/c/skia/+/307177
> [skia] Remove API skdescriptor fuzzer

- projects/skia/BUILD.gn.diff
- projects/skia/Dockerfile
- projects/skia/build.sh
> [Skia] Update SKP Fuzzer

- docs/getting-started/new_project_guide.md
@oliverchang 
Take a look
After adding documentation to when should projects opt for more build frequency please close #2584
> Updating documentation to reflect new feature custom build frequency

- projects/wasmtime/default.options
This is an attempt to handle #4264
> Add `handle_sigsegv=1` to Wasmtime's options

- infra/base-images/base-clang/checkout_build_install_llvm.sh
Fix parse regex as per format change in
https://chromium.googlesource.com/chromium/src/tools/clang/+/e6863f878319bc31e7f454132b655251f9761fc2%5E%21/#F1
> Fix LLVM_REVISION parse regex

- projects/util-linux/project.yaml
This PR should be merged once https://github.com/karelzak/util-linux/pull/1114 is merged
> [util-linux] turn on MSan

- projects/cryptofuzz/Dockerfile
- projects/cryptofuzz/build.sh
[cryptofuzz] wolfCrypt: Add build options
- Enable SHAKE
- Enable additional curves
- Disable tests and examples for shorter build times
[cryptofuzz] Add Nettle
[cryptofuzz] Nettle: Fix 32 bit build
[cryptofuzz] Add libgmp
[cryptofuzz] Don't build libgmp with MSAN
[cryptofuzz] Add mpdecimal
[cryptofuzz] Fix libgmp, mpdecimal builds
> [cryptofuzz] Various updates

- projects/libyuv/project.yaml
request to accept a new project
> initial libyuv project.yaml

- projects/uwebsockets/project.yaml
I want more builds per day, and to use msan to file issues
> [uwebsockets] Increase builds per day, file msan issues

- projects/excelize/project.yaml
[Excelize](https://github.com/xuri/excelize) is a library written in pure Go providing a set of functions that allow you to write to and read from XLSX / XLSM / XLTM files.
> add project excelize

- projects/opusfile/Dockerfile
- projects/opusfile/build.sh
- projects/opusfile/opusfile_fuzzer.c
- projects/opusfile/opusfile_fuzzer.cc
- projects/opusfile/project.yaml
Initial integration PR for [opusfile](https://github.com/xiph/opusfile). Using the fuzzer located [here](https://github.com/google/security-research-pocs/blob/master/autofuzz/opusfile_fuzzer.cc). Requesting review from @alsophian and @spq.
> [opusfile] Initial integration

- projects/bind9/Dockerfile
- projects/bind9/build.sh
- projects/bind9/project.yaml
This is a new project proposal to start fuzzing BIND 9.
> Add bind9 as new proposed oss-fuzz target

- projects/sleuthkit/Dockerfile
- projects/sleuthkit/build.sh
- projects/sleuthkit/project.yaml
- projects/sleuthkit/sleuthkit_fls_fuzzer.cc
- projects/sleuthkit/sleuthkit_mem_img.h
- projects/sleuthkit/sleuthkit_mmls_fuzzer.cc
Integrate The Sleuth Kit (https://sleuthkit.org) digital forensics library with OSS-Fuzz.
@rjotwani : I've pushed just enough to get TSK building in the OSS-Fuzz build environment; can you handle the rest?  Thanks!
> Initial integration for Sleuthkit

- projects/skia/Dockerfile
- projects/skia/build.sh
> Move zip and json to data folder

- projects/envoy/project.yaml
We have a build breakage that I haven't been able to fix yet, so this might not pass CI
* Adds intern to cc's
> [envoy] Add Zach to project

- projects/libxml2/build.sh
- Add new XPath fuzz target
- Set V=1 globally
- Clean seed corpus to make sure it will be rebuilt
> [libxml2] Add another target, minor fixes

- infra/base-images/base-runner/reproduce
- infra/base-images/base-runner/run_fuzzer
seems to work and not break anything (tested locally)
> [infra] Upgrade reproduce command to re-use run_fuzzer functionality.

- projects/mp4parse-rust/project.yaml
> [mp4parse-rust] Add to vendor_ccs list

- projects/spidermonkey/Dockerfile
- projects/spidermonkey/build.sh
- projects/spidermonkey/project.yaml
I am adding the libc++ parts from spidermonkey-ufi.
> [spidermonkey] Fix issue 19014

- projects/samba/project.yaml
Volker is a core Samba developer.
> samba: add Volker Lendecke to CC list

- projects/orbit/Dockerfile
- projects/orbit/build.sh
- projects/orbit/project.yaml
That's a first shot of a build configuration.
Works on my machine so far (using `infra/helper.py`)
> [orbit] A first build configuration

- projects/postgresql/build.sh
- projects/postgresql/fuzzer/Makefile
- projects/postgresql/fuzzer/fuzzer_initialize.c
- projects/postgresql/fuzzer/json_parser_fuzzer.c
- projects/postgresql/fuzzer/simple_query_fuzzer.c
- Simple_query_fuzzer crashed at startup.
- Added initialization parts to the json_parser_fuzzer.
@spq Could you review the changes?
> [PostgreSQL] Fixed fuzzers

- projects/libheif/Dockerfile
- projects/libheif/build.sh
> [libheif] Add AOM as a dependency to enable AVIF fuzzing

- projects/postgresql/fuzzer/fuzzer_initialize.c
> [PostgreSQL] Fixing fuzzers - Remove get_username

- projects/gnutls/project.yaml
> gnutls: removed Nikos as primary contact and add Daiki

- projects/nginx/build.sh
- projects/nginx/fuzz/wrappers.c
> [Nginx] Add wrappers for getpwnam and getgrnam

- docs/getting-started/continuous_integration.md
Make the introduction more explicit about what CIFuzz does, how it helps users and how it works.
Also fix some language.
> [cifuzz] Improve docs

- projects/dovecot/project.yaml
> Adds a maintainer to dovecot ccs

- projects/libjpeg-turbo/project.yaml
I spoke to the maintainers of libjperg turbo and they would like to have this email added to the CC list of bug reports.
> [libjpeg-turbo] Update project contacts

- projects/fluent-bit/build.sh
- projects/fluent-bit/project.yaml
Refator of the fluent-bit build script as the upstream repo is about to manage the building of the fuzzers. 
Cross-referencing: https://github.com/fluent/fluent-bit/pull/2502
Waiting for the CR PR to be merged, only after then will this succeed.
> [Fluent-bit] Refactor build script 

- projects/dovecot/Dockerfile
- projects/dovecot/project.yaml
cc @cmouse
Should fix build failure 
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=25567
> Adds dovecot new compilation depedencies

- projects/ffmpeg/build.sh
This adds the 2nd libavformat fuzzer tool
Based on the existing one
> [FFmpeg] Add entry for tools/target_io_dem_fuzzer

- projects/openexr/openexr_exrenvmap_fuzzer.cc
This change adds an initial check for claimed image size before processing it via the exrenvmap functions.
exrenvmap loads the entire image into memory, so the 2.5GB memory limit imposed by oss-fuzz prevents it processing large images. 
> [openexr] skip reading large images in exrenvmap

- projects/postgresql/Dockerfile
- projects/postgresql/add_fuzzers.diff
- projects/postgresql/build.sh
- projects/postgresql/fuzzer/Makefile
- projects/postgresql/fuzzer/protocol_fuzzer.c
Newly written fuzzer for PostgreSQL protocol.
> [PostgreSQL] Add new protocol fuzzer

- projects/skia/build.sh
I believe this will make using CI fuzz easier.
> [skia] Use bin/gn

- infra/presubmit.py
- projects/clamav/project.yaml
CF's heuristic does not work for this (clamav-devel vs clamav-fuzz-corpus is too ambiguous)
> Set main repo for clamav.

- projects/ndpi/Dockerfile
Should fix build failure
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=25879
cc @lucaderi
> Adds ndpi dependency

- projects/libavif/avif_decode_fuzzer.cc
Fix a build failure.
BUG=oss-fuzz:25877
> libavif: Update to the new avifIO reader API

- projects/astc-encoder/build.sh
> [astc-encoder] Temporarily disable astc_encode_decode_ise_fuzzer.

- projects/c-ares/project.yaml
> [c-ares] Add more upstream maintainers to cc

- projects/servo/project.yaml
I no longer have access to my Mozilla email account but would like to continue receiving notifications.
> Update servo contact.

- projects/solidity/Dockerfile
- projects/solidity/build.sh
Install new dependencies for fuzzer build and minor refactor of build script
> Solidity: update docker image and build script

- projects/wolfssl/project.yaml
Requesting access to view wolfSSL reports.
> Add me please.

- projects/zstd/project.yaml
Tracking team membership changes.
> [zstd] Update auto_ccs

- projects/opus/build.sh
> opus: enable asserts

- projects/ffmpeg/build.sh
This should improve coverage of libavformat
> [FFmpeg] Add fuzzers for individual demuxers

- projects/cpp-httplib/Dockerfile
- projects/cpp-httplib/build.sh
- projects/cpp-httplib/project.yaml
- Depends on https://github.com/yhirose/cpp-httplib/pull/684
- Will change repo link in Dockerfile after above gets merged.
Testing locally: 
``` 
cd oss-fuzz
export PROJECT_NAME=cpp-httplib  
python infra/helper.py build_fuzzers --sanitizer address $PROJECT_NAME
python infra/helper.py run_fuzzer $PROJECT_NAME server_fuzzer
```
> [yhirose/cpp-httplib] Add to oss-fuzz 

- projects/cpp-httplib/project.yaml
@inferno-chromium  @yhirose Added email IDs to get access to bug reports.
> [cpp-httplib] Update email IDs to access bug reports

- projects/servo/project.yaml
> Update primary contact for Servo

- projects/samba/project.yaml
We are quite strictly and proudly a C project.
> Samba is C, not C++

- projects/go-ethereum/project.yaml
Update maintainers for go-ethereum.
> go-ethereum: update maintainers

- projects/cpp-httplib/project.yaml
> [yhirose/cpp-httplib] Add new email id to auto_cc list 

- projects/servo/project.yaml
This is an account I can actually log in with to see the issue tracker.
> Update servo email.

- projects/mruby/build.sh
Depends on https://github.com/mruby/mruby/pull/5110
> mruby: Fix build

- projects/cpp-httplib/Dockerfile
- projects/cpp-httplib/project.yaml
Hey @inferno-chromium 
Have enabled msan for the yhirose/cpp-httplib.
> [yhirose/cpp-httplib] Enable memory sanitizer 

- infra/base-images/base-runner/coverage
Fixes https://github.com/google/oss-fuzz/issues/4608
> Use symlink instead of broken -path-equivalence

- projects/solidity/Dockerfile
> Solidity: Fuzz breaking branch instead of develop

- projects/mysql-server/build.sh
- projects/mysql-server/fix.diff
Try to fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=26134
> Updates for mysql 8.22

- projects/flatbuffers/Dockerfile
- projects/flatbuffers/build.sh
- projects/flatbuffers/project.yaml
This PR is for initial integration of [Flatbuffers](https://github.com/google/flatbuffers).
Currently changes to the build system are pending upstream. 
Maintainers of Flatbuffers: Kindly provide the email addresses for potential bug reports. These will be publicly available in the `project.yaml` file and can be changed at any time.
For reference, we are working upstream to fit the build system to oss-fuzz's environment. I will add links to upstream PR's here as they happen:
https://github.com/google/flatbuffers/pull/6256
https://github.com/google/flatbuffers/pull/6259
> [flatbuffers] Initial integration

- projects/protobuf-c/Dockerfile
- projects/protobuf-c/build.sh
- projects/protobuf-c/project.yaml
Do you accept this project? If so, I will notify the maintainers.
> [protobuf-c] Initial integration

- infra/base-images/base-clang/Dockerfile
> Install Atheris in base-clang.

- projects/tensorflow/project.yaml
Removing Frank who was a temporary placeholder.
> Add amitpatankar@google.com to CCs.

- projects/librdkafka/Dockerfile
- projects/librdkafka/build.sh
- projects/librdkafka/project.yaml
This adds an initial integration of Librdkafka. 
PR for reference: https://github.com/edenhill/librdkafka/pull/3151
> [Librdkafka] Initial integration

- projects/leveldb/Dockerfile
- projects/leveldb/build.sh
- projects/leveldb/fuzz_db.cc
- projects/leveldb/fuzz_db.options
- projects/leveldb/project.yaml
Integrating the leveldb project.
> [leveldb] initial integration

- projects/librdkafka/project.yaml
CR: https://github.com/edenhill/librdkafka/pull/3151
> [Redis] update configuration

- projects/ujson/build.sh
Still ASAN lib preload is missing.
> Improve ujson build.sh to build fuzzers.

- infra/cifuzz/cifuzz.py
- infra/helper.py
> Fix test_all breakage

- infra/base-images/base-builder/compile_go_fuzzer
- infra/ci/build.py
- infra/ci/build_test.py
- projects/go-coredns/Dockerfile
- projects/go-coredns/build.sh
- projects/golang/build.sh
- projects/kubernetes/build.sh
And avoid infinite recursion from #4659
> Golang project uses compile_go_fuzzer script

- projects/libressl/Dockerfile
- projects/libressl/build.sh
Needs a newer version of Boost.
> [libressl] Fix Cryptofuzz build

- docs/getting-started/new-project-guide/python_lang.md
- docs/getting-started/new_project_guide.md
>  Add documentation for Python fuzzing.

- docs/getting-started/new-project-guide/go_lang.md
- projects/golang-protobuf/Dockerfile
Fixes golang-protobuf coverage build
And improves documentation for golang projects with modules
> Golang modules documentation

- projects/serenity/fuzz_CMakeLists.txt
fixes has been made in upstream Serenity on the Js fuzzer so it will compile https://github.com/SerenityOS/serenity/pull/4164
> [serenity] update build

- projects/stb/Dockerfile
These will be used in the upstream build script.
> stb: add more inputs

- projects/cairo/Dockerfile
- projects/cairo/build.sh
- projects/cairo/project.yaml
- projects/cairo/targets/fuzzer_temp_file.h
- projects/cairo/targets/pdf_surface_fuzzer.c
- projects/cairo/targets/raster_fuzzer.c
- projects/cairo/targets/surface_write_png_fuzzer.c
- projects/cairo/targets/text_glyphs_fuzzer.c
Hello,
I am a Software Engineering Intern at Google, working with the Third Party Security (TPS) team. As part of my internship I am working on fuzzing GNOME/freedesktop libraries and Cairo is one of the libraries that we have picked for this work.
You can find the MR for integrating my fuzzers into the main Cairo repository [here](https://gitlab.freedesktop.org/cairo/cairo/-/merge_requests/69). I've been in touch with the upstream about the OSS-Fuzz integration and their main concern is the lack of development staff on that end. For now I’m fetching the Cairo repo from my personal fork in the Dockerfile. I'm sending in the PR since my internship ends this week.
Thanks!
Ceyhun
ceyhunalp@google.com
> [Cairo] Initial integration

- projects/poppler/Dockerfile
- projects/poppler/build.sh
- projects/poppler/pdf_fuzzer.cc
- projects/poppler/project.yaml
> Revert "New fuzzers for Poppler"

- infra/base-images/base-runner/bad_build_check
Honggfuzz calls msan now:
https://github.com/google/honggfuzz/commit/e0670137531242d66c9cf8a6dee677c055a8aacb
Should address #4743.
> Increase threshold for msan calls check in bad_build_check.

- docs/getting-started/new-project-guide/python_lang.md
- projects/ujson/build.sh
Disable leak detection in python target execution wrapper since it
is not expected to work. Also, updated the documentation for python
-only code fuzzers to not use LD_PRELOAD.
> Leak detection is not expected to work with python targets, disable.

- projects/ndpi/Dockerfile
- projects/ndpi/build.sh
Should fix 
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=28201
> Compiles json-c in ndpi project

- infra/build/functions/build_project.py
- infra/build/functions/expected_build_steps.json
Fixes https://github.com/google/oss-fuzz/issues/4781
> s/test_all/test_all.py for google cloud build.

- infra/base-images/base-sanitizer-libs-builder/msan_build.py
- infra/base-images/base-sanitizer-libs-builder/packages/gnutls28.py
- infra/base-images/base-sanitizer-libs-builder/packages/libgcrypt20.py
- infra/base-images/base-sanitizer-libs-builder/packages/systemd.py
Regression from
https://github.com/google/oss-fuzz/pull/4694
> Fix msan build breakage.

- infra/bisector.py
- infra/build_specified_commit.py
This was renamed in b0b99d5ccdf5e2e49cfe3138fbcf64e6fef6ea7f
> Rename BaseRepoManager -> RepoManager.

- projects/envoy/project.yaml
Remove some folks who are not active in fuzzing, add @chaoqin-li1123.
> envoy: update Envoy bug ACL/notifications.

- projects/gdk-pixbuf/project.yaml
See https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/issues/129#note_980351
> Add a better point of content for gdk-pixbuf

- projects/dropbear/project.yaml
Trying to see if increasing the builds_per_day can improve my iteration cycle speed fixing new fuzzers
> dropbear: set 4 builds per day

- projects/bind9/project.yaml
- projects/boringssl/project.yaml
- projects/cairo/project.yaml
- projects/cjson/project.yaml
- projects/double-conversion/project.yaml
- projects/eigen/project.yaml
- projects/ffmpeg/project.yaml
- projects/gdk-pixbuf/project.yaml
- projects/gstreamer/project.yaml
- projects/karchive/project.yaml
- projects/libcacard/project.yaml
- projects/libidn/project.yaml
- projects/libldac/project.yaml
- projects/libssh/project.yaml
- projects/libtasn1/project.yaml
- projects/libwebp/project.yaml
- projects/opus/project.yaml
- projects/pigweed/project.yaml
- projects/powerdns/project.yaml
- projects/re2/project.yaml
- projects/skcms/project.yaml
- projects/skia/project.yaml
- projects/speex/project.yaml
- projects/tor/project.yaml
- projects/vorbis/project.yaml
- projects/wget/project.yaml
- projects/wxwidgets/project.yaml
- projects/xz/project.yaml
Needed for a scorecard check - https://github.com/ossf/scorecard and probably future bisection easier as well.
> Add main_repo for some remaining projects.

- projects/solidity/Dockerfile
CC @ekpyron
Installs libabicoder inside solidity docker image
> solidity: Install libabicoder

- docs/getting-started/new_project_guide.md
Fixes https://github.com/google/oss-fuzz/issues/4825
> Add docs for main_repo

- projects/qemu/project.yaml
> qemu: add Li to the auto_ccs

- projects/pygments/project.yaml
See https://github.com/pygments/pygments/issues/1628#issuecomment-743346621
> Add a proper contact for pygments' fuzzer

- projects/loki/project.yaml
Signed-off-by: Michel Hollands <michel.hollands@grafana.com>
> [loki] Add Michel to cc list

- projects/pillow/project.yaml
Update contact of pillow per https://github.com/python-pillow/Pillow/issues/5072
> pillow: update email

- projects/pillow/project.yaml
I'm a maintainer of the Pillow project, we'd like the notifications to go through Tidelift.
cc @DavidKorczynski @aclark4life
Thanks!
> Update Pillow contact email

- projects/wireshark/Dockerfile
- projects/wireshark/project.yaml
Wireshark's repository is at GitLab.
> Wireshark: Update the repo URLs.

- projects/rocksdb/build.sh
- projects/rocksdb/project.yaml
Changes has happened in upstream rocksdb which broke the build. This PR contains fixes.
> rocksdb: fix build

- projects/bs4/Dockerfile
- projects/bs4/bs4_fuzzer.py
- projects/bs4/build.sh
- projects/bs4/project.yaml
BeautifulSoup is the standard to parse untrusted/invalid/weird
html in Python, so fuzzing it for unexpected exceptions and
infinite loops makes sense. Moreover,
it's using various parsers, with some of them written in C.
> Add BeautifulSoup

- projects/pygments/pygments_fuzzer.py
See https://github.com/pygments/pygments/issues/1628#issuecomment-747259224
> Use only utf-8 for Pygments

- projects/cmark/cmark_fuzzer.options
- projects/cmark/project.yaml
Remove max_len and inactive auto_cc.
> [cmark] Update options and auto_ccs

- infra/helper.py
Fixes https://github.com/google/oss-fuzz/issues/4857
> Fix incorrect calculation with gcs path for backup corpus.

- projects/mdbtools/Dockerfile
- projects/mdbtools/build.sh
- projects/mdbtools/project.yaml
Project was previously approved in #4403.
> [mdbtools] Initial integration

- infra/base-images/base-runner/test_all.py
- projects/jsc/project.yaml
Regression from
https://github.com/google/oss-fuzz/pull/4769/files
> Fix broken blackbox fuzzer projects.

- projects/c-blosc2/build.sh
- We changed the `decompress_fuzzer` to be renamed to `decompress_chunk_fuzzer`.
- Added new `decompress_frame_fuzzer` along with a seed corpus specific to it.
> [c-blosc2] Update seed corpus for decompression fuzzers

- projects/pillow/Dockerfile
- projects/pillow/build.sh
> Fix workdir for Pillow project.

- projects/upb/Dockerfile
- projects/upb/build.sh
- projects/upb/project.yaml
@haberman 
I saw that there is already a fuzzer integrated into upb
Would you like to have it run continuously on oss-fuzz ?
PS : I used the cmake build
> Adds project upb (ie micro protobuf)

- projects/serenity/project.yaml
> serenity: Add myself and the mailing list to the cc list.

- projects/nats/project.yaml
Hi, adding myself as one of the maintainers for NATS to triage oss fuzz issues.
> Add to maintainers for NATS

- projects/selinux/project.yaml
@Wonder93 having come across https://lore.kernel.org/selinux/CAJfZ7==jHHhoSgciRP_3jynZr9kYDjcogaM_s8_edbQmv=kvPQ@mail.gmail.com/T/#t I took the liberty of adding you to the auto_ccs list. I hope that's OK.
cc @fishilico
> [selinux] add @ WOnder93's gmail address

- projects/ots/Dockerfile
Update OTS build to match new master branch requirements.
> Update OTS build

- projects/mongodb/project.yaml
This adds several maintainers to the project.
> mongodb: add several maintainer emails

- projects/pyyaml/fuzz_loader.py
> Adds target for pyyaml project

- projects/pyyaml/project.yaml
cf https://github.com/google/oss-fuzz/pull/4944#event-4191855245
> Adds people to project pyyaml ccs

- projects/bleach/Dockerfile
- projects/bleach/build.sh
- projects/bleach/linkify_fuzzer.py
- projects/bleach/project.yaml
- projects/bleach/sanitize_fuzzer.py
We just need an email address for the primary contact
> Add bleach

- projects/fio/Dockerfile
- projects/fio/build.sh
- projects/fio/project.yaml
Draft PR for demonstration
Needs to take the upstream repository (once the fuzz target will be merged there)
> Adds project fio

- projects/dovecot/Dockerfile
Should fix build failure https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=29552
> Use now main branch for dovecot project

- projects/tensorflow-py/Dockerfile
- projects/tensorflow-py/build.sh
- projects/tensorflow-py/project.yaml
Create a new Python fuzzer under `projects/tensorflow-py`. 
Based on the following [integration directions](https://google.github.io/oss-fuzz/getting-started/new-project-guide/python-lang/).
@mihaimaruseac
> Create a new Python fuzzing project for tensorflow

- projects/fio/project.yaml
@sitsofe is this email associated to a Google account, so that you can access oss-fuzz reports for fio project ?
> Adds people to fio project

- projects/tensorflow-py/build.sh
Move the TensorFlow Python project from tensorflow to tf-nightly to test the latest code. @mihaimaruseac
> Switch TensorFlow Python pip package

- projects/grpc-go/Dockerfile
- projects/grpc-go/build.sh
- projects/grpc-go/fuzz_hello.go
- projects/grpc-go/project.yaml
cc @menghanl
Would you be interested in continuous fuzzing for grpc-go ?
If so, I can make a Pull Request to merge the fuzz targets in grpc-go's repository
> Adds grpc-go project

- docs/getting-started/new-project-guide/python_lang.md
- projects/ujson/Dockerfile
- projects/ujson/build.sh
- projects/ujson/hypothesis_structured_fuzzer.py
Hypothesis makes fuzzing complex Python code fun, easy, and a lot more rewarding than constructing all your objects by hand.
CC @inferno-chromium; closes #4121.
> Show how to use Hypothesis to fuzz Python code

- projects/python-lz4/Dockerfile
- projects/python-lz4/build.sh
- projects/python-lz4/fuzz_lz4.py
- projects/python-lz4/project.yaml
Waiting for upstream to accept.
> python-lz4: initial integration

- infra/base-images/base-builder/Dockerfile
See https://github.com/google/oss-fuzz/issues/5012#issue-789981845
> Remove unneeded ADD layers in base-builder.

- projects/ecc-diff-fuzzer/build.sh
As of cryptopp8.4 which fixed its bug
> Ecc-diff-fuzzer is now ok with cryptopp

- infra/build/functions/project_sync_test.py
- infra/build/functions/request_build_test.py
- infra/build/functions/request_coverage_build_test.py
- infra/build/functions/update_build_status_test.py
- infra/presubmit.py
> Fix build functions tests when invoked from unittest.TestSuite.

- projects/arrow/project.yaml
Add Kenta Murata to the list of secondary contacts.
> [arrow] Add contact

- projects/django/Dockerfile
- projects/django/build.sh
Hi, we moved django-fuzzers to a new location. @guidovranken (the original author) can confirm that this change is intended.
I also updated the python version used while on it.
> Move django-fuzzers to a new location.

- infra/cifuzz/cifuzz.py
- infra/cifuzz/cifuzz_test.py
- infra/cifuzz/run_fuzzers.py
- infra/cifuzz/run_fuzzers_entrypoint.py
- infra/cifuzz/run_fuzzers_test.py
- infra/cifuzz/stack_parser.py
- infra/cifuzz/stack_parser_test.py
This will make the code easier to understand.
TODO: Rename cifuzz.py to build_fuzzers.py
> [CIFuzz] Seperate code for running fuzzers into own module: run_fuzzers.py

- projects/sudoers/Dockerfile
- projects/sudoers/build.sh
- projects/sudoers/fuzz_iolog_json_parse.c
- projects/sudoers/fuzz_sudoers_parse.c
- projects/sudoers/project.yaml
Cross-refencing https://github.com/google/oss-fuzz/issues/5050
I have added two fuzzers for now and am waiting for feedback from the authors.
> sudoers: initial integration

- projects/perfetto/project.yaml
Our build now supports this as well.
> perfetto: run fuzzers with UBSan

- infra/cifuzz/build_fuzzers_entrypoint.py
- infra/cifuzz/cifuzz.py
- infra/cifuzz/cifuzz_test.py
- infra/cifuzz/config_utils.py
- infra/cifuzz/config_utils_test.py
- infra/cifuzz/run_fuzzers.py
- infra/cifuzz/run_fuzzers_entrypoint.py
- infra/cifuzz/run_fuzzers_test.py
Also, decide is_github based on something not used/faked by Skia.
> [CIFuzz] Move run_fuzzers to new config system

- projects/civetweb/Dockerfile
- projects/civetweb/build.sh
- projects/civetweb/project.yaml
Initial integration
Cross referencing https://github.com/civetweb/civetweb/issues/893
> Civetweb: initial integration

- projects/inchi/Dockerfile
One of the InChI maintainers contacted me over email to inform us of the new release, so I'm updating the URL.
> Update download URL for InChI library.

- infra/cifuzz/actions/run_fuzzers/action.yml
- infra/cifuzz/config_utils.py
- infra/cifuzz/continuous_integration.py
- infra/cifuzz/fuzz_target.py
- infra/cifuzz/run_fuzzers.py
- infra/cifuzz/run_fuzzers_test.py
- infra/cifuzz/stack_parser.py
- infra/cifuzz/stack_parser_test.py
In this mode, CIFuzz will keep fuzzing until the time limit is reached, even if a crash was found.
> [cifuzz] Support a batch fuzzing mode

- infra/base-images/base-builder/Dockerfile
For https://github.com/google/oss-fuzz/issues/4280#issuecomment-771495411
> Update afl++ to 1f71b85426f837ebcae8381897d44a3a67c73a4f

- projects/brunsli/build.sh
Recent build commit has changed artifacts path.
> Fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=30030

- projects/selinux/project.yaml
It should help to prevent OSS-Fuzz from reporting bugs that
have already been fixed.
> [selinux] build the project more often

- projects/wolfssl/build.sh
Makes it more likely to find memory leaks and other bugs.
> [wolfssl] Use heap instead of stack allocations

- projects/systemd/project.yaml
I have recently joined the maintainers team. /cc @evverx for confirmation.
> [systemd]: add Luca Boccassi to cc

- infra/base-images/base-builder/Dockerfile
- infra/base-images/base-builder/compile_afl
- infra/base-images/base-runner/run_fuzzer
- projects/libreoffice/build.sh
better compilation and run defaults for afl++.
Also implements a workaround for libreoffice that makes it work for 40/45 fuzzers. that one also already has a roulette option :)
> optimal afl++ defaults

- infra/base-images/base-clang/checkout_build_install_llvm.sh
Needed due to
https://github.com/google/fuzzbench/issues/1077#issuecomment-774727055
> Downgrade llvm to clang-12 for a few weeks.

- projects/utf8proc/build.sh
> [utf8proc] remove workaround

- projects/cctz/Dockerfile
- projects/cctz/build.sh
- projects/cctz/fuzz_cctz.cc
- projects/cctz/project.yaml
Initial integration, waiting for acceptance from upstream.
> cctz: initial integration.

- projects/lighttpd/Dockerfile
- projects/lighttpd/build.sh
- projects/lighttpd/fuzz_burl.c
- projects/lighttpd/project.yaml
Motivation for this project is due to `lighttpd` having been mentioned on various security bulletins. 
https://www.lighttpd.net/ 
Some CVEs from the past:
https://www.openwall.com/lists/oss-security/2008/09/26/5
https://seclists.org/oss-sec/2014/q1/561
https://github.com/lighttpd/lighttpd1.4/commit/32120d5b8b3203fc21ccb9eafb0eaf824bb59354
https://github.com/lighttpd/lighttpd1.4/commit/2105dae0f9d7a964375ce681e53cb165375f84c1
> lighttpd: initial integration.

- projects/qt/project.yaml
It will take some time to make that build correctly.
> [qt] Disable afl for now

- projects/envoy/project.yaml
> [envoy] Add Yanjun to project

- projects/libsodium/fake_random.h
- projects/libsodium/secret_key_auth_fuzzer.cc
- projects/libsodium/secretbox_easy_fuzzer.cc
Also check return codes of verification functions, and properly check the random implementation name.
> libsodium: don't use the stack for potentially large data

- projects/envoy/project.yaml
https://github.com/google/oss-fuzz/pull/5187 has a typo
> [envoy] Add Yan

- projects/zlib-ng/build.sh
- projects/zlib-ng/project.yaml
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=29639
> Updated zlib-ng project

- projects/qt/Dockerfile
As instructed in https://github.com/google/oss-fuzz/pull/5087
> [qt] Have my own copy of afl's dictionaries and testcases

- projects/bs4/project.yaml
As requested privately by Leonard
> Change the primary_contact for bs4

- docs/getting-started/continuous_integration.md
> [CIFuzz] Note which languages are supported

- projects/p11-kit/Dockerfile
- projects/p11-kit/build.sh
- projects/p11-kit/project.yaml
Patch from @divergentdave. This should now build with the p11-kit master branch.
> New project: p11-kit

- infra/base-images/base-builder/compile_go_fuzzer
> golang: compatibility with go 1.16 modules

- projects/tarantool/Dockerfile
- projects/tarantool/build.sh
- projects/tarantool/project.yaml
How-To Build: https://www.tarantool.io/en/doc/latest/dev_guide/building_from_source/
> [tarantool] initial integration

- infra/base-images/base-builder/compile_go_fuzzer
- projects/cascadia/Dockerfile
> Fixes go coverage build with go 1.16

- projects/unrar/build.sh
This is based on a suggestion from @inferno-chromium in https://crbug.com/oss-fuzz/19333#c3
> Add '-fno-sanitize=enum' to CXXFLAGS for unrar

- projects/botan/build.sh
- projects/ecc-diff-fuzzer/build.sh
Taken from oss-fuzz botan configure line
Should fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=31133
not 31337 yet ;-)
> Fix ecc-diff-fuzzer build with right botan config

- projects/bind9/project.yaml
Update the bind9 authorized users.
> Remove wpk, add pspacek to auto_ccs

- projects/minify/build.sh
- projects/quic-go/build.sh
cc @inferno-chromium 
Fuzz targets got fixed, but the corpuses were not
> Fixes go-quic corpuses build

- projects/syzkaller/build.sh
- projects/teleport/Dockerfile
- projects/teleport/build.sh
By running go mod vendor after go mod tidy
cc @inferno-chromium more go 1.16
cc @mvdan following our discussion in another issue...
cc @awly for the fix about teleport
> Fixes teleport and syzkaller builds

- projects/kimageformats/Dockerfile
- projects/kimageformats/build.sh
- projects/kimageformats/kimgio_fuzzer.cc
> Add HEIF format to kimageformats project

- projects/lotus/build.sh
- projects/radon/Dockerfile
- projects/radon/build.sh
cc @inferno-chromium 
With this PR and https://github.com/tdewolff/minify/pull/384
there should only be lotus project remaining to fix
> Fixes radon build

- projects/qt/project.yaml
> [qt] Use default fuzzing engines again

- infra/base-images/base-builder/Dockerfile
- infra/base-images/base-runner/bad_build_check
- infra/helper.py
- projects/skia/build.sh
We aren't planning on suppoting TSAN on ClusterFuzz.
But we can support in CIFuzz since Skia wants it.
> [TSAN] Support TSAN

- projects/ujson/Dockerfile
The current hypothesis example is not actually copied into the container. This PR fixes it so the fuzzer builds.
> ujson: ensure hypothesis fuzzer is copied in

- infra/cifuzz/coverage.py
- infra/cifuzz/coverage_test.py
> [CIFuzz][coverage] Fix bug in getting coverage reports

- projects/jbig2dec/jbig2_fuzzer.cc
To make that possible these things were also done:
* Rename variables for clarity.
* Rename functions to separate them from jbig2dec's own allocator API.
* Consistently use size_t for all memory statistics.
* Add helper function for checking peak memory use.
* Add helper function for when limit is reached.
* Add helper function for when allocations fail.
* Add helper function for memory statis at end of run (including leak check).
This will help with fixing jbig2dec issue 21675 reported by OSS-fuzz.
> [jbig2dec] Custom allocator now supports test case being run more than once.

- infra/helper.py
I separated the parts into logical commits and tried to argue why they make sense in their respective commit messages.
These two resolved issue #5300 for me. Let me know if I can improve the commits in some way to make it easier for you guys to merge them.
> Fix for shell subcommand resulting in backtrace

- projects/freeimage/Dockerfile
- projects/freeimage/build.sh
Requested in https://github.com/google/oss-fuzz/pull/2606#issuecomment-588533038
> [freeimage] Use the SVN repo instead of the latest source archive.

- projects/ygot/Dockerfile
- projects/ygot/build.sh
- projects/ygot/fuzz.go
- projects/ygot/project.yaml
cc @robshakir
Would you be interested in continuous fuzzing for ygot ?
This PR enables it with oss-fuzz
Let me know if you have more questions
> Adds ygot project

- projects/gitea/project.yaml
And once the security team members changed, we have to send new PR to change this.
Follow https://github.com/google/oss-fuzz/pull/5334#issuecomment-793940817
> Allow security team of Gitea to access the issues

- infra/base-images/base-sanitizer-libs-builder/msan_build.py
Should fix https://github.com/google/oss-fuzz/issues/5349
> Don't rpath patch llvm-symbolizer.

- docs/getting-started/bug_disclosure_guidelines.md
- docs/oss-fuzz/architecture.md
> Modify deadline text to disclose immediately after fix is released.

- projects/envoy/project.yaml
> Envoy: Update project.yaml

- projects/image-png/Dockerfile
- projects/image-png/buf_independent.rs
- projects/image-png/build.sh
- projects/image-png/project.yaml
Integrates https://github.com/image-rs/image-png 
The PNG decoder/encoder of rust: [doc link](https://docs.rs/png/0.16.8/png/)
> image-png: initial integration

- infra/base-images/base-builder/cargo
Should fix #5380 cc @inferno-chromium @jrmuizel
> Rust coverage : do not trigger debug assertions

- projects/jackson-core/Dockerfile
- projects/jackson-core/JsonFuzzer.java
- projects/jackson-core/build.sh
- projects/jackson-core/project.yaml
@cowtowncoder signed off in https://github.com/FasterXML/jackson-core/issues/685#issuecomment-799630288
> [jackson-core] Initial integration

- projects/serenity/project.yaml
> serenity: Add myself to the mailing list

- projects/tpm2-tss/Dockerfile
Update docker file and add access control list tool dependency
> add acl dependency

- projects/jackson-dataformats-binary/CborFuzzer.java
- projects/jackson-dataformats-binary/Dockerfile
- projects/jackson-dataformats-binary/SmileFuzzer.java
- projects/jackson-dataformats-binary/build.sh
- projects/jackson-dataformats-binary/project.yaml
Signed off by @cowtowncoder in https://github.com/FasterXML/jackson-dataformats-binary/issues/254#issuecomment-798792202
> [jackson-dataformats-binary] Initial integration

- projects/pcl/Dockerfile
- projects/pcl/build.sh
- projects/pcl/project.yaml
This PR adds the build files for PCL and fixes https://github.com/google/oss-fuzz/pull/3575.
A fuzzer has been uploaded here: https://github.com/PointCloudLibrary/pcl/pull/4524
Tagging @kunaltyagi to let you know of the PR.
> Added build files for PCL

- projects/zeek/project.yaml
This adds Dominik to the list of users for the zeek project. Ping @jsiwek for approval.
> zeek: add user to mailing list

- projects/go-snappy/fuzz.go
Updates https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=32135
> [go-snappy] reject large inputs to avoid OOM

- infra/base-images/base-builder/Dockerfile
Add back what was accidentally removed before #5344 was committed.
> [base-builder] Fix temp dir removal

- docs/getting-started/new_project_guide.md
Mention that only some projects will benefit.
Fixes: #4752.
> [docs] Change wording regarding i386 fuzzing.

- projects/image-png/buf_independent.rs
Fixes https://github.com/google/oss-fuzz/issues/5378
> image-png: fix fuzzer

- projects/ibmswtpm2/no_writes.patch
Try to fix issue by using CC and CXX from env.
Fixes #5093
> [ibmswtpm2] Speculative fix for AFL++ issue.

- infra/build/functions/update_build_status.py
Generate badges also for projects with no coverage builds at all (e.g.
JVM and Python projects). For these projects, the badge only has the two
possible states "build passing" and "build failing".
Should fix https://github.com/google/oss-fuzz/issues/5178#issuecomment-803608414.
> Generate badges for projects without coverage

- projects/capstone/build.sh
Should fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=32174
> Capstone: do not use flags for corpus building

- projects/lighttpd/fuzz_burl.c
remove reference to removed interface
fixes oss-fuzz lighttpd build
> remove reference to removed interface

- projects/pcl/project.yaml
> PCL: add other maintainers as auto_ccs

- projects/pcl/project.yaml
Add @koide3 
Sorry for creating another PR like this so shortly after the last one was merged!
> PCL: add another maintainer under auto_ccs

- infra/helper.py
- infra/helper_test.py
Make sure shell-base-runner-debug works.
Fixes: #5303
> [infra/helper.py] Unittest shell base-runner-debug

- projects/ygot/build.sh
Should fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=32110
> Fixes ygot coverage build

- infra/cifuzz/actions/build_fuzzers/action.yml
- infra/cifuzz/build_fuzzers_entrypoint.py
- infra/cifuzz/config_utils.py
This will mainly be useful for non-OSS-Fuzz users.
Though it can also be used by OSS-Fuzz users to speed things
up (very slightly in most cases).
Fixes #4377
> [CIFuzz] Make it possible to skip bad build check.

- projects/grpc/Dockerfile
- projects/grpc/build.sh
Also, update base-builder version.
Fixes: #3157
> [grpc] Fix build

- infra/base-images/base-builder/detect_repo.py
- infra/base-images/base-builder/detect_repo_test.py
Superseeds: #5463
Fixes: #3670
> [CIFuzz] Fix repo detection for repos downloaded through "go get".

- projects/jbig2dec/jbig2_fuzzer.cc
Previously the allocator handled small pointer values incorrectly
and prevented multiple executions (unexpectedly used when OSS-fuzz
uses LSAN to look for memory leaks). More over there were cases
where too large allocations were not caught and the allocator
needlessly kept track of peak allocation statistics.
> [jbig2dec] Improve custom allocator

- projects/unbound/build.sh
> Fix build failure in unbound

- projects/tinygltf/Dockerfile
- projects/tinygltf/build.sh
- projects/tinygltf/project.yaml
cc @syoyo
Would you be interested in continuous fuzzing for tinygltf as well ?
I see there is already one fuzz target
> Adds tinygltf project

- projects/fast-dds/Dockerfile
- projects/fast-dds/build.sh
- projects/fast-dds/patch.diff
- projects/fast-dds/project.yaml
cc @EduPonz @MiguelCompany
Would you be interested in continuous fuzzing for fast-dds ?
This PR enables it with one simple fuzz target about `processCDRMsg` where previous bugs had been found by fuzzing
> Adds project fast-dds

- projects/kamailio/project.yaml
adds maintainer email.
@miconda - for reference, in case you want to add additional maintainers to the project in the future this PR shows how to do it.
> kamailio: Update project.yaml

- projects/dart/project.yaml
cf https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=32813
> Disables afl for dart project

- projects/envoy/build.sh
Disables instrumentation in various libraries to increase fuzzing performance. @asraa
> envoy: optimise fuzzers

- projects/boost/boost_regex_fuzzer.cc
- projects/boost/build.sh
@bshastry I noticed you were working on fixing boost here https://github.com/google/oss-fuzz/pull/4595 so I took the liberty to help a bit. This PR fixes the boost build and closes https://github.com/google/oss-fuzz/pull/4595
> boost: fix build.

- projects/tidb/build.sh
This fixes the build for TiDB.
Closes: https://github.com/google/oss-fuzz/pull/4396
> [tidb] Fix build

- projects/jackson-dataformat-xml/Dockerfile
- projects/jackson-dataformat-xml/XmlFuzzer.java
- projects/jackson-dataformat-xml/build.sh
- projects/jackson-dataformat-xml/project.yaml
@cowtowncoder Could you confirm that you want this merged?
I have found a better way to build Maven projects for OSS-Fuzz and will update the existing integrations at some point.
> [jackson-dataformat-xml] Initial integration

- projects/tidb/build.sh
I recently submitted a fix for the tidb coverage build. It fixed the build, and this PR refactors the build.
Credit to @catenacyber for giving a heads up on this.
> Refactor tidb build

- projects/binutils/fuzz_readelf.c
Upstream changed over to using stdbool.h.  s/TRUE/true/
> Fix issue 32760: binutils: Fuzzing build failure

- projects/capnproto/project.yaml
Now that it got fixed https://github.com/capnproto/capnproto/pull/1201
> Adds ubsan for capnproto

- projects/libvips/Dockerfile
- projects/libvips/build.sh
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=32999
> [libvips] remove unused giflib dependency

- projects/libreoffice/Dockerfile
> update libreoffice build-dependency cache

- projects/proftpd/Dockerfile
- projects/proftpd/build.sh
- projects/proftpd/fuzzer.c
- projects/proftpd/project.yaml
The PR provides initial integration of [proftpd](https://github.com/proftpd/proftpd).
Examples of previous CVE's can be found here: https://github.com/proftpd/proftpd/search?q=cve&type=issues
> [proftpd] Initial integration

- projects/suricata/Dockerfile
- projects/suricata/build.sh
Getting ready for https://github.com/OISF/suricata/pull/6054
> Suricata with pcre2

- projects/golang/project.yaml
This PR adds myself as maintainer for the golang integration.
The `main_repo` has also been added, as it was missing.
@josharian Can you confirm this?
> [golang] Add maintainer

- projects/postgresql/add_fuzzers.diff
- projects/postgresql/build.sh
- projects/postgresql/project.yaml
Current .patch file is breaking the build. Fixing this. Will also verify if we can get AFL to build and run.
> postgresql: fix build

- projects/flate2-rs/Dockerfile
- projects/flate2-rs/build.sh
- projects/flate2-rs/project.yaml
flate2-rs: https://crates.io/crates/flate2
Is also a front-end to https://crates.io/crates/miniz_oxide
> flate2rs initial integration.

- projects/binutils/build.sh
Should fix build failure cf https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=33312#c3
> Disables werror for binutils

- projects/linkerd2-proxy/build.sh
Generalises build script to arbitrary amount of fuzzers as a reaction to new fuzzers usptream.
> linkerd2-proxy: add a new fuzzer and fix coverage build

- projects/apache-commons/CompressSevenZFuzzer.java
- projects/apache-commons/CompressTarFuzzer.java
- projects/apache-commons/CompressZipFuzzer.java
- projects/apache-commons/Dockerfile
- projects/apache-commons/ImagingBmpFuzzer.java
- projects/apache-commons/ImagingGifFuzzer.java
- projects/apache-commons/ImagingJpegFuzzer.java
- projects/apache-commons/ImagingPngFuzzer.java
- projects/apache-commons/ImagingTiffFuzzer.java
- projects/apache-commons/build.sh
- projects/apache-commons/project.yaml
Please wait for @bodewig (who is [bodewig at apache](https://lists.apache.org/thread.html/r67968b72b85fd42046d4483c2588116b89f6fe6ede968e70d4bb0772%40%3Cdev.commons.apache.org%3E)) to sign off on this PR.
> [apache-commons] Initial integration

- projects/geos/Dockerfile
- projects/geos/build.sh
- projects/geos/patch.diff
- projects/geos/project.yaml
@strk @robe2 @dr-jts would you be interested in continuous fuzzing for geos ?
This pull request enables it with oss-fuzz with a simple fuzz target about `GEOSGeomFromWKB_buf` which could be merged in geos repository
Let me know if you have any questions
> Adds geos project

- projects/prost/Dockerfile
- projects/prost/build.sh
- projects/prost/project.yaml
https://crates.io/crates/prost Protocol buffers implementation in Rust.
Has 291 reverse dependencies: https://crates.io/crates/prost/reverse_dependencies and 3.5 million downloads.
@danburkert I have set up continuous fuzzing of Prost. I thought it would be nice to have this set up as there are a fair amount of projects relying on Prost. Is this something you would be happy to have set up? The benefits are that the fuzzers will be run on a regular basis and bug reports will be send to your email with information such as inputs that trigger the bugs, stack traces and more. If you would like to get Prost in, the only thing needed from your end is an email that will receive the bugs reports - notice this email should be attached to a Google account for you to see the reports.
> prost: initial integration.

- projects/fast-dds/build.sh
Cf https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=33526#c1
Inspired by tinyxml2 project itself
> Fix tinyxml2 build for fast-dds

- projects/hyperium/project.yaml
@seanmonstar I am adding @olix0r and @hawkw from the Buoyant team as CCs on hyperium. Can you confirm this is okay?
> hyperium: update project.yaml

- projects/skia/build.sh
See https://bugs.chromium.org/p/skia/issues/detail?id=11892
> [skia] Add API Triangulation fuzzer

- projects/capnproto/Dockerfile
- projects/capnproto/build.sh
Should fix build failure cf  https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=33558
cc @kentonv
> Use autotools for capnproto

- projects/golang/Dockerfile
- projects/golang/build.sh
- projects/golang/text_fuzzer.go
This PR adds two fuzzers for the golang text project.
@katiehockman - Can you review this PR?
> [golang] Add fuzzer

- projects/go-ethereum/project.yaml
This adds @rjl493456442 and @zsfelfoldi to the project. CC @karalabe for approval
> go-ethereum: add maintainer

- projects/bls-signatures/Dockerfile
- projects/bls-signatures/build.sh
I merged the BLS functionality into the Cryptofuzz master branch.
Future development will occur there.
> [bls-signatures] Use repository master branch

- projects/libvips/Dockerfile
- projects/libvips/build.sh
> [libvips] Add libjxl (for JPEG-XL) as a dependency

- projects/rustls/project.yaml
I'm a collaborator on the rustls project and would like to be informed.
> Add myself for the rustls project

- projects/opencensus-cpp/build.sh
Should fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=33901
> Use bazel generic script for opencensus

- docs/getting-started/new_project_guide.md
Not sure if this is helpful. Feel free to close
> doc: Explain fuzzing_engines

- projects/libvips/Dockerfile
- projects/libvips/build.sh
See the individual commits for more details.
/cc @jcupitt
> [libvips] build against lcms/libspng, fix AVIF/JXL fuzzer

- projects/oatpp/Dockerfile
- projects/oatpp/build.sh
- projects/oatpp/fuzz_mapper.cpp
- projects/oatpp/project.yaml
oatpp is an open source C++ Web Framework https://oatpp.io/. The website lists some of the customers of the project, for convenience it includes:
- https://www.eyesopen.com/
- https://www.legrand.us/
- https://milvus.io/
- https://www.radio-ip.com/en/
- https://www.icognize.de/
- https://www.deepdetect.com/
--------------------------------------
@lganzzzo would you be interested in getting oatpp into OSS-Fuzz? I did an initial integration and if you are interested, the only thing we will need from you is an email(s) that will receive bug reports from OSS-Fuzz which will be listed in the project.yaml (see the files added in this commit). I would be happy to integrate the fuzzers into the upstream repository as well.
> oatpp: initial integration.

- projects/golang/project.yaml
I work with @odeke-em at Orijtech, and also contributing to some part in Go project: https://go-review.googlesource.com/q/owner:cuong.manhle.vn%2540gmail.com
I would like to be in maintainer list, so I can help coordinate and fix found bugs for the Go project.
> projects/golang: add Cuong Manh Le as a Go maintainer

- projects/mtail/build.sh
Upstream is renaming the path in https://github.com/google/mtail/pull/515
> mtail: Fuzz target renamed

- projects/oatpp/project.yaml
solves https://github.com/google/oss-fuzz/issues/5726
> oatpp: updated email 

- infra/ci/build.py
- infra/helper.py
- projects/skcms/build.sh
This will help bitcoin use CI to verify the build works, because
the last step is trivial (so testing not really needed) but will
fill up the disk.
See https://github.com/google/oss-fuzz/issues/5729#issuecomment-834356716
> [infra] Set OSS_FUZZ_CI=1 in CI so build scripts can know

- projects/bitcoin-core/build.sh
This should make the CI build green again
> bitcoin-core: Only compile a few fuzz targets when OSS_FUZZ_CI

- projects/ffmpeg/build.sh
Based-on: 0da70e1c01e9f14d0792e0d7b64c433cdc2dbbaf
Suggested by: https://github.com/google/oss-fuzz/pull/5737#issuecomment-835375366
> [FFmpeg] Only build first 2 targets of each kind for CI

- projects/ffmpeg/build.sh
Currently the HEVC coverage is relativly poor, this should improve it
> [FFmpeg] Add small seed corpus for HEVC

- projects/envoy/project.yaml
Granting kbaichoo@google.com Envoy fuzz tests access.
> Granting kbaichoo@google.com Envoy fuzz tests access

- projects/cel-go/Dockerfile
- projects/cel-go/build.sh
- projects/cel-go/cel-go-lpm.proto
- projects/cel-go/fuzz_compile.go
- projects/cel-go/fuzz_eval.go
- projects/cel-go/go-lpm.cc
- projects/cel-go/project.yaml
@TristonianJones would you be interested in oss-fuzz for cel-go ? (in addition to cel-cpp)
This PR enables it with a simple fuzz target about `env.Compile` cf https://github.com/google/cel-go/issues/317
> Adds cel-go project

- projects/javaparser/Dockerfile
- projects/javaparser/build.sh
- projects/javaparser/parseFuzzer.java
- projects/javaparser/project.yaml
@matozoid would you be interested in continuous fuzzing with oss-fuzz for javaparser ?
This PR enables it with a simple fuzz target about `JavaParser.parse`
> Adds javaparser project

- projects/solidity/Dockerfile
- projects/solidity/build.sh
> Remove antlr deps

- projects/javaparser/project.yaml
> Adds people to the javaparser project

- infra/build/functions/build_and_run_coverage.py
@jonathanmetzman Found one more spot where Java needs to be opted in for coverage. Hope this is the final one before we see JVM coverage reports.
> [infra] Run JVM coverage builds

- projects/sql-parser/Dockerfile
- projects/sql-parser/build.sh
- projects/sql-parser/fuzz_sql_parse.cpp
- projects/sql-parser/project.yaml
Integrates https://github.com/hyrise/sql-parser
sql-parser is used by envoy-proxy.
> sql-parser: initial integration

- projects/samba/project.yaml
David is a core Samba team member who wants to write fuzz targets!
> samba: add David Mulder to auto_ccs

- projects/cel-go/fuzz_compile.go
Cf https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=34337#c2
cc @tswadell
> cel-go: relax assertion in fuzz target

- projects/geos/Dockerfile
See for instance https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=34339
> Geos: use github if main git server is failing

- projects/protobuf-java/Dockerfile
- projects/protobuf-java/ProtobufFuzzer.java
- projects/protobuf-java/build.sh
- projects/protobuf-java/project.yaml
@acozzette Would you be interested in OSS-Fuzz integration for the Protobuf Java library? This is the fuzzer that found the bugs fixed in https://github.com/protocolbuffers/protobuf/commit/4008d229aa7505775486d6a86705efd2800599b3#diff-39e30ba0f9474a5c558a5c5496dd085d7ff93ae2f3521416735287a1ae4153e3.
> [protobuf-java] Initial integration

- projects/sqlalchemy/Dockerfile
- projects/sqlalchemy/build.sh
- projects/sqlalchemy/project.yaml
- projects/sqlalchemy/sqlalchemy_fuzzer.py
Adds initial integration of [sqlalchemy](https://github.com/sqlalchemy/sqlalchemy).
This project is widely used in production by web apps.
Users of SQLAlchemy include ([src](https://www.sqlalchemy.org/#features)):
1. Yelp!
2. reddit
3. DropBox
4. The OpenStack Project
5. Survey Monkey
_________________________________________________________________________
@zzzeek Are you interested in integrating SQLAlchemy into OSS-fuzz?
This PR adds the build files and a fuzzer.
To complete the integration, a maintainers email address is needed for bug reports.
> [sqlalchemy] Initial integration

- projects/wget/Dockerfile
- projects/wget/build.sh
Hey, this PR fixes the wget build locally :-)
> Fix wget build

- projects/spdk/Dockerfile
- projects/spdk/build.sh
- projects/spdk/parse_json_fuzzer.cc
- projects/spdk/project.yaml
SPDK provides a set of open-source tools and libraries for writing high performance, scalable, user-mode storage applications. According to [SPDK's website](https://spdk.io/), the library widely deployed, powering many critical services. 
Among its users is Intel (https://software.intel.com/content/www/us/en/develop/articles/introduction-to-the-storage-performance-development-kit-spdk.html), who uses it in mission-critical products (https://spdk.io/files/QingCloud.pdf)
> [spdk] Initial integration

- projects/oak/Dockerfile
- projects/oak/build.sh
This, together with https://github.com/project-oak/oak/pull/2130, will fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=34645.
> Build Wasm modules

- infra/presubmit.py
- projects/cpp-httplib/project.yaml
- projects/openthread/project.yaml
- projects/ots/project.yaml
- projects/sudoers/project.yaml
- projects/usrsctp/project.yaml
Also remove dataflow from projects where it was removed improperly
or added improperly.
> [presubmit] Add check to ensure dataflow is specified properly.

- projects/wolfssl/build.sh
- Enable streaming AES GCM
- Enable bignum calculations with negative numbers
> [wolfssl] Several updates

- infra/presubmit.py
This makes local development better.
> [presubmit] Add option to skip slow build tests.

- projects/envoy/project.yaml
Grant pcrao and tyxia access to Envoy fuzzing. Remove rdsmith.
Signed-off-by: Kevin Baichoo <kbaichoo@google.com>
> Envoy: Grant pcrao and tyxia access to Envoy fuzzing.

- infra/cifuzz/clusterfuzz_deployment.py
- infra/cifuzz/filestore/__init__.py
Add methods that will be used for ClusterFuzzLite and Filestore but do not implement them.
> [CIFuzz][NFC] Add skeleton for ClusterFuzzLite and Filestore

- projects/gnupg/project.yaml
Should complete the fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=30198
cf #5817
> Disable afl for gnupg

- projects/libaom/Dockerfile
- projects/libaom/av1_dec_fuzzer.dict
- projects/libaom/build.sh
this was transferred from this project in:
3b1ff98b1 add examples/av1_dec_fuzzer.dict
> libaom: use upstream dict file

- projects/varnish/Dockerfile
- projects/varnish/build.sh
- projects/varnish/patch.diff
- projects/varnish/project.yaml
cc @fgsch cf #1524
Why was there only project.yaml for varnish ?
> Adds varnish project for real

- projects/openweave/Dockerfile
- projects/openweave/build.sh
- projects/openweave/project.yaml
cc @gerickson would you be interested in continuous fuzzing for openweave ?
This PR enables it with oss-fuzz with the fuzz targets and corpus already present in the upstream repository
> Adds openweave project

- projects/oak/build.sh
Some cleanups after changes in oak.
> oak - Removed unused commands

- projects/pidgin/Dockerfile
- projects/pidgin/build.sh
- projects/pidgin/pidgin_utils_fuzzer.c
- projects/pidgin/pidgin_xml_fuzzer.c
- projects/pidgin/project.yaml
This PR adds initial integration of Pidgin IM
> [pidgin] Initial integration

- projects/poco/json_parse_fuzzer.cc
Add exception. Fix formatting.
> [poco] Improve json fuzzer

- projects/simd/Dockerfile
- projects/simd/build.sh
- projects/simd/project.yaml
- projects/simd/simd_load_fuzzer.cpp
This PR adds initial integration of [Simd](https://github.com/ermig1979/Simd/). 
Simd is an image processing and machine learning library. _It provides many useful high performance algorithms for image processing such as: pixel format conversion, image scaling and filtration, extraction of statistic information from images, motion detection, object detection (HAAR and LBP classifier cascades) and classification, neural network_[[1](http://ermig1979.github.io/Simd/)].
___________________________________________________________________________________
@ermig1979 Are you interested in integrating Simd into OSS-fuzz for continuous fuzzing?
All we need to complete the integration is a maintainers email address for bug reports.
> [simd] Initial integration

- projects/solidity/Dockerfile
Fixes solidity's failing build
> Fuzz develop instead of breaking

- projects/go-snappy/project.yaml
As requested here https://github.com/google/oss-fuzz/issues/5442#issuecomment-850925681
cc @nigeltao
> Disable golang snappy project

- docs/getting-started/continuous_integration.md
cc @jonathanmetzman cf https://github.com/google/oss-fuzz/pull/5881#issuecomment-855896754
> docs: CIFuzz requires a project to be cloned with git

- projects/freeradius/build.sh
Should fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=35042
> Fixes freeradius build using OUT env variable

- projects/freeradius/patch.diff
Should fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=35073
> Fixes leak in freeradius patch for target

- projects/java-example/default.options
The JVM needs to register custom SEGV handlers.
> [java-example] Fix UBSan options

- infra/base-images/base-builder/compile
> [infra][base-builder] Clarify error messages in `compile`

- infra/base-images/base-builder/Dockerfile
- infra/base-images/base-runner/run_fuzzer
better afl++ performance due bug fixes in new commit id
> enhance afl++ performance

- projects/cel-cpp/Dockerfile
- projects/cel-cpp/fuzz_parse.cc
I'm not able to verify locally since -std=c++0x is forcefully being added somewhere on my system and abseil does not build with it.
Signed-off-by: Kuat Yessenov <kuat@google.com>
> cel-cpp: fix build

- projects/ecc-diff-fuzzer/Dockerfile
Should fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=35283
> Change quickjs repository for ecc-diff-fuzzer

- projects/lldb-eval/build.sh
An attempt to resolve coverage build issue #5909
CC: @tonkosi
> Copy libs by "value"

- infra/base-images/base-runner/run_fuzzer
- infra/ci/build.py
- infra/cifuzz/cifuzz-base/Dockerfile
- infra/helper.py
Also improve comment in cifuzz-base/Dockerfile.
> [CIFuzz] Allow run_fuzzers to use a preexisting corpus.

- projects/xmlsec/Dockerfile
- projects/xmlsec/build.sh
Build has been broken since August 2020. This fixes it.
> xmlsec: fix build.

- projects/varnish/project.yaml
> Add my gmail address

- projects/hugo/fuzz.go
Fixes hugo fuzzing build. Both ASAN build and coverage build are broken.
> [hugo] Fix build

- projects/dragonfly/Dockerfile
Dragonflys build is currently broken due to updates to dependencies. This fixes it.
> [dragonfly] Fix build

- infra/base-images/base-runner/Dockerfile
Hardcode commit hash for chromium code coverage script, till
revert happens.
Fixes #5934
> Fix code coverage regression.

- projects/freeradius/Dockerfile
- projects/freeradius/build.sh
Should fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=35389
> Freeradius ssl1.1

- projects/lldb-eval/build.sh
- projects/lldb-eval/project.yaml
* Upgrade to LLVM-12
* Enable undefined sanitizer
cc: @tonkosi
> [lldb-eval] Upgrade to LLVM-12 and enable undefined sanitizer

- projects/netcdf/project.yaml
> Adds cc people to netcdf

- projects/bitcoin-core/build_cryptofuzz.sh
- Build the [schnorr_fun](https://github.com/LLFourn/secp256kfun/tree/master/schnorr_fun) library for comparing libsecp256k1's Schnorr sign and verify output against
- Build libsecp256k1 with ECDH support, and via Cryptofuzz test it against Trezor's ECDH function
CC @sipa @MarcoFalke @real-or-random @practicalswift
> [bitcoin-core] libsecp256k1: Compare against schnorr_fun, implement ECDH

- projects/java-example/project.yaml
Coverage builds succeed and every expected finding has been found.
> [java-example] Disable project

- projects/nginx/fuzz/http_request_fuzzer.cc
This issue https://github.com/google/oss-fuzz/issues/4632 discusses a memory leak in nginx. This PR fixes it. 
Note that there are still more work to in terms of improving nginx fuzzing.
> [nginx] memory leak fix

- infra/build/functions/deploy.sh
Should fix https://github.com/google/oss-fuzz/issues/5968
> Try fix for memory exceeded

- projects/sound-open-firmware/project.yaml
> sound-open-firmware: add additional CCs

- projects/h2o/project.yaml
Hello,
Moto has been working on the h2o project with us and it would be beneficial for him to access the dashboard to obtain a snapshot of outstanding issues, etc. Could you please add him?
cc: @kazuho @mootoh 
Thank you,
Hajime
> [h2o] Add mtakayama to h2o project

- infra/cifuzz/build_fuzzers_entrypoint.py
- infra/cifuzz/cifuzz-base/Dockerfile
- infra/cifuzz/cifuzz_combined_entrypoint.py
- infra/cifuzz/cifuzz_external_entrypoint.py
- infra/cifuzz/run_fuzzers_entrypoint.py
This PR will let Prow run CIFuzz by using the CIFuzz base image
> Add CIFuzz external entrypoint for cifuzz base

- projects/h3/Dockerfile
- projects/h3/build.sh
- projects/h3/h3_fuzzer.c
- projects/h3/project.yaml
This PR adds initial integration of continuous fuzzing for [H3](https://github.com/uber/h3).
H3 is Uber's grid system for efficiently optimizing ride pricing and dispatch, for visualizing and exploring spatial data. H3 allows Uber to analyze geographic information to set dynamic prices and make other decisions on a city-wide level. H3 is used as the grid system for analysis and optimization throughout the Uber marketplaces
H3 is developed by and used at Uber [[src](https://eng.uber.com/h3/)].
> [h3] Initial integration

- projects/simdjson/project.yaml
I tried msan locally and it seemed to work ok (simdjson uses no external libraries).
cc @lemire
> [simdjson] enable msan

- infra/build/functions/update_build_status.py
Apparently GetRequestsPerMinutePerUser also need fixing, so bring this fix back.
> Bring back build status page fix until quota issues are resolved.

- infra/build/functions/update_build_status.py
Reverts google/oss-fuzz#5997
Quota was increased. Trying again.
> Revert "Bring back build status page fix until quota issues are resolved."

- projects/lldb-eval/build.sh
Also undefine `NDEBUG` to allow `assert`s.
CC: @werat
> Add lldb vs lldb-eval fuzz target

- projects/jsoup/project.yaml
> Updating the primary contact for jsoup to me

- projects/wolfssl/Dockerfile
- projects/wolfssl/build.sh
- Build additional target (normal math)
- More cross-pollination (import from Botan and other wolfSSL corpora)
> [wolfssl] Several improvements

- projects/poco/Dockerfile
The current branch no longer exists.
> [poco] Fix broken build

- projects/h3/project.yaml
> Update h3 contact email to gmail

- projects/h3/project.yaml
> Update h3 contact email: ajfriend

- projects/varnish/Dockerfile
- projects/varnish/build.sh
See https://github.com/varnishcache/varnish-cache/pull/3635
> varnish: Migration to pcre2

- projects/net-snmp/Dockerfile
- projects/net-snmp/build.sh
- projects/net-snmp/project.yaml
- projects/net-snmp/snmp_parse_fuzzer.c
- projects/net-snmp/snmp_scoped_pdu_parse_fuzzer.c
@fenner @bvanassche I would like to contribute fuzzers to the net-snmp project and help get more code coverage. In this PR I added two new fuzzers and also updated the license of the existing files, but it would be great to get access to the project page so I can see coverage on clusterfuzz so I also added myself to the auto_ccs list. 
Would you be okay with me getting access? FYI I do a lot of work here on OSS-Fuzz and contributes to many of the projects here on OSS-Fuzz as you can see from the contributors page.
> net-snmp: two new fuzzers and request access

- projects/lldb-eval/Dockerfile
- projects/lldb-eval/build.sh
- projects/lldb-eval/lldb_vs_lldb_eval_libfuzzer_test.options
Following the suggestion in #6066.
CC: @werat
> [lldb-eval] Disable leak reports

- projects/myanmar-tools/build.sh
Workaround state being preserved in build containers.
Temporary fix for #6035
> [infra][myanmar-tools] Fix myanmar-tools temporarily

- infra/base-images/base-runner/coverage
- infra/cifuzz/build_fuzzers_test.py
This is needed to upload coverage reports.
Related: #6054
> [CIFuzz][Coverage] Make coverage reports world readable

- infra/build/functions/build_project.py
- infra/build/functions/expected_build_steps.json
> [infra][build] Reset HOME using env instead of bash.

- infra/cifuzz/build_fuzzers_test.py
- infra/cifuzz/clusterfuzz_deployment.py
- infra/cifuzz/filestore/github_actions/__init__.py
- infra/cifuzz/filestore/github_actions/github_actions_test.py
We need to split the archive_path
> [CIFuzz] Fix bug in tar_directory

- projects/opensk/Dockerfile
- projects/opensk/build.sh
- projects/opensk/project.yaml
OpenSK is an open-source implementation for security keys written in Rust that supports both FIDO U2F and FIDO2 standards.
https://security.googleblog.com/2020/01/say-hello-to-opensk-fully-open-source.html
@jmichelp @ia0 @gendx is it in the interest to enable continuous fuzzing of OpenSK? There are already quite a few of Google's open source repositories on OSS-Fuzz and I thought it would be nice to get OpenSK on as well. Let me know!
> opensk: initial integration.

- infra/base-images/base-runner/coverage
- infra/cifuzz/generate_coverage_report.py
- infra/cifuzz/generate_coverage_report_test.py
> [cifuzz] Fix corpus usage in coverage reports

- infra/cifuzz/filestore/github_actions/__init__.py
- infra/cifuzz/filestore/github_actions/github_actions_test.py
To avoid issues like #6087 before they land.
> [NFC][cifuzz] Add tests for github actions.

- infra/cifuzz/actions/build_fuzzers/action.yml
- infra/cifuzz/actions/run_fuzzers/action.yml
- infra/cifuzz/external-actions/build_fuzzers/action.yml
- infra/cifuzz/external-actions/run_fuzzers/action.yml
This will be used for testing and can be moved elsewhere later.
> Add external actions.

- projects/net-snmp/build.sh
- projects/net-snmp/snmp_mib_fuzzer.c
- projects/net-snmp/snmp_octet_fuzzer.c
@bvanassche I added two more fuzzers for net-snmp. Could you take a look?
> net-snmp: add two new fuzzers and simplify build script.

- projects/tendermint/project.yaml
Adding @williambanfield, who will help field alerts on our side.
> projects/tendermint: add additional maintainer

- projects/libxml2/project.yaml
- projects/libxslt/project.yaml
I'm not involved in these projects anymore.
> [libxml2] [libxslt] Remove myself as contact

- projects/h2o/project.yaml
> update h2o/project.yml to add github:gfx

- projects/frr/Dockerfile
- projects/frr/build.sh
- projects/frr/project.yaml
@qlyoung would you be interested in continuous fuzzing for FRR ?
This enables with oss-fuzz with the fuzz targets and corpuses already present and documented
> Adds frr project

- projects/capnproto/project.yaml
> Adds an email to capnproto project

- projects/envoy/project.yaml
Granting krajshiva@google.com Envoy fuzz tests access.
> Granting krajshiva@google.com Envoy fuzz tests access

- infra/cifuzz/build_fuzzers.py
- infra/cifuzz/continuous_integration.py
- infra/cifuzz/continuous_integration_test.py
- infra/cifuzz/filestore/git/__init__.py
Fixes: #6119
Also add more tests for continuous_integration module.
> [CIFuzz] Don't overwrite the repo in external builds.

- infra/cifuzz/build_fuzzers_entrypoint.py
- infra/cifuzz/build_fuzzers_test.py
- infra/cifuzz/config_utils.py
- infra/cifuzz/fuzz_target_test.py
> [NFC][cifuzz] Improve env var handling.

- projects/frr/project.yaml
Add some more project members to the CCs list and update my own email
> [frr] Add additional CC emails

- projects/cras/project.yaml
Changes:
- Change primary_contact
- Update auto_ccs to the latest
- Increase builds per day to 2
> cras: Update project metadata

- infra/helper.py
This is better because:
1. It avoids the need to print 'ERROR:' before some messages.
2. We don't need to specify writing to stderr, this is the default.
> [helper] Switch from print to log

- infra/bisector.py
- infra/bisector_test.py
- infra/build_specified_commit_test.py
- infra/test_repos.py
Also don't confusingly call test repos "test_case", only use
testcase to refer to fuzzer testcases.
> [infra][NFC] Use "testcase" instead of test_case for consistency.

- docs/getting-started/new-project-guide/jvm_lang.md
Fixes https://github.com/google/oss-fuzz/pull/6105#issuecomment-887950308.
> [docs] Enable AWT headless mode in Java guide

- infra/base-images/base-runner/run_fuzzer
> [cifuzz] Speculative fix for issue with seed corpus/backup corpus

- projects/apache-httpd/fuzz_utils.c
Supersedes https://github.com/google/oss-fuzz/pull/6170
> apache-httpd: fix str size issue.

- projects/libavc/project.yaml
- projects/libfdk-aac/project.yaml
- projects/libhevc/project.yaml
- projects/libldac/project.yaml
- projects/libmpeg2/project.yaml
- projects/perfetto/project.yaml
Two new team members added to process reports.
> Updating contacts for report distribution

- projects/opensk/Dockerfile
We decided to fuzz our development branch to catch bugs earlier.
@jmichelp @kaczmarczyck
> Fuzz develop branch instead of stable

- projects/freetype2/project.yaml
Project member email address no longer exists.
> [freetype2] Remove CC address

- infra/build/functions/base_images.py
- infra/build/functions/build_and_run_coverage.py
- infra/build/functions/build_lib.py
- infra/build/functions/build_project.py
- infra/build/functions/project_sync.py
- infra/build/functions/project_sync_test.py
- infra/build/functions/request_build.py
- infra/build/functions/request_coverage_build_test.py
- infra/build/functions/test_utils.py
- infra/build/functions/update_build_status.py
- infra/presubmit.py
I'm refactoring build_project.py as part of #6180 and there are some things there that I don't like.
I think I'll send different PRs for these to avoid making the review too long when I upgrade the ubuntu image. WDYT?
> [infra][build] Switch to f-strings.

- infra/cifuzz/clusterfuzz_deployment.py
- infra/cifuzz/clusterfuzz_deployment_test.py
- infra/cifuzz/config_utils.py
- infra/cifuzz/fuzz_target.py
- infra/cifuzz/fuzz_target_test.py
- infra/cifuzz/generate_coverage_report.py
- infra/cifuzz/generate_coverage_report_test.py
- infra/cifuzz/run_fuzzers.py
- infra/cifuzz/workspace_utils.py
> [cifuzz] Add pruning task

- projects/tpm2-tss/Dockerfile
- projects/tpm2-tss/project.yaml
tpm2-tss: update version of tpm simulator
tpm2-tss: update outdated contact list
tpm2-tss: add main_repo section
> tpm2-tss updates

- projects/nginx/build.sh
See http://nginx.org/en/docs/dev/development_guide.html#debug_memory for details.
> Don't use nginx' internal memory allocator

- infra/base-images/base-builder/bisect_clang_test.py
- infra/base-images/base-runner/test_all_test.py
- infra/build/functions/request_build_test.py
- infra/build/functions/request_coverage_build_test.py
- infra/build/functions/update_build_status_test.py
- infra/cifuzz/affected_fuzz_targets_test.py
- infra/cifuzz/build_fuzzers_test.py
- infra/cifuzz/clusterfuzz_deployment_test.py
- infra/cifuzz/config_utils_test.py
- infra/cifuzz/continuous_integration_test.py
- infra/cifuzz/docker_test.py
- infra/cifuzz/filestore/github_actions/github_actions_test.py
- infra/cifuzz/fuzz_target_test.py
- infra/cifuzz/generate_coverage_report_test.py
- infra/cifuzz/get_coverage_test.py
- infra/cifuzz/http_utils_test.py
- infra/cifuzz/run_fuzzers_test.py
- infra/cifuzz/stack_parser_test.py
- infra/helper_test.py
- infra/utils_test.py
Add _impl suffix to functions defined to be side effects to avoid conflict.
> [infra][tests][NFC] Change mocked function prefix from "mocked_" to "mock_"

- projects/h3/h3_fuzzer.c
Fixes a build breakage on H3 relating to API changes we're making for the v4 of the library. I had some difficulty running the build locally so I am relying on CI. :)
Cc @dfellis @nrabinowitz @ajfriend
> H3: Update for functions returning error codes

- projects/smt/Dockerfile
- projects/smt/build.sh
- projects/smt/project.yaml
This project is an implementation of Sparse Merkle tree, which will be
used by Celestia, Cosmos SDK, ... and maybe other blockchain ecosystem.
We want to make sure the code is fuzzed to catch highly impacted bug as
soon as possible.
See:
- https://github.com/celestiaorg
- https://docs.cosmos.network/v0.42/
> projects: add celestiaorg/smt

- projects/upb/Dockerfile
- projects/upb/build.sh
- projects/upb/project.yaml
As of https://github.com/protocolbuffers/upb/pull/405 Bazel
now supports cc_fuzz_test() for its fuzzing target.
> Switched upb to Bazel for fuzzing.

- projects/nginx/project.yaml
@andrey-zelenkov I would like to submit fuzzers to nginx and in this context having the coverage information from clusterfuzz would be great, so I added myself on the CC list of the `project.yaml`. Are you okay with me getting access here? FYI I am regular oss-fuzz contributor and working on many different oss-fuzz projects https://github.com/google/oss-fuzz/commits?author=DavidKorczynski
> nginx: request access

- projects/nginx/project.yaml
- projects/njs/project.yaml
- projects/postgresql/project.yaml
- projects/spdlog/project.yaml
- projects/syzkaller/project.yaml
This follows conversation from here on cleaning up inactive googlers: https://github.com/google/oss-fuzz/pull/6104
> multiple projects: cleanup stale accounts.

- projects/harfbuzz/build.sh
test/shaping was renamed to test/shape.
> Fix harfbuzz fuzzer build.

- projects/libecc/build.sh
See https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=37229 for technical discussion.
> [libecc] Fix SHAKE digest

- projects/libreoffice/project.yaml
see https://github.com/google/oss-fuzz/issues/6233 for rationale
> libreoffice: disable afl fuzzer

- projects/libsndfile/Dockerfile
- projects/nginx/fuzz/http_request_fuzzer.cc
Verified the fix from here: https://github.com/google/oss-fuzz/pull/6104#issuecomment-900663664
CC @andrey-zelenkov
> nginx: fix fuzzer to avoid NULL-deref

- projects/boost-json/project.yaml
@pdimov approved this on the boost-json slack channel.
> [boost-json] add upstream author Peter Dimov to cc

- infra/ci/build.py
To fix https://github.com/google/oss-fuzz/issues/6269
> [infra] add swift build to infra/ci/build

- projects/grpc-swift/Dockerfile
- projects/swift-nio/Dockerfile
- projects/swift-protobuf/Dockerfile
> [Ubuntu upgrade][NFC] Improve message for swift projects.

- projects/assimp/Dockerfile
- projects/grpc-go/Dockerfile
- projects/libtheora/Dockerfile
- projects/mdbtools/Dockerfile
- projects/pcl/Dockerfile
- projects/tesseract-ocr/Dockerfile
- projects/wolfmqtt/Dockerfile
Many of these seem to timeout, unclear if this is a fluke.
Related #6180
> [Ubuntu upgrade] Pin projects that fail on coverage

- projects/bls-signatures/build.sh
This adds a target which builds blst with size optimizations, which activates slightly different code, that I want to test as well.
> [bls-signatures] Add target for size-optimized blst

- projects/tint/Dockerfile
- projects/tint/build.sh
- projects/tint/project.yaml
Adds a YAML file for fuzzing of the tint project.
> New project for fuzzing tint

- projects/rustls/project.yaml
CR https://github.com/google/oss-fuzz/pull/5332#issuecomment-906786193
> rustls: update maintainer

- projects/spirv-tools/Dockerfile
- projects/spirv-tools/build.sh
- projects/spirv-tools/project.yaml
Adds YAML file for a new spirv-tools project.
> Initial project file for SPIR-V Tools fuzzing

- projects/zxing/Dockerfile
- projects/zxing/MultiFormatDecodeFuzzer.java
- projects/zxing/MultiFormatEncodeFuzzer.java
- projects/zxing/build.sh
- projects/zxing/project.yaml
@srowen https://github.com/zxing/zxing/issues/1409
> [zxing] Initial Integration

- projects/openexr/build.sh
Also cleans up old cmake configure options
Signed-off-by: Kimball Thurston <kdt3rd@gmail.com>
> Add new C library for subsequent fuzz testing

- projects/clickhouse/Dockerfile
- projects/clickhouse/build.sh
> [ClickHouse] Enable coverage for memory and address sanitizer

- projects/zxing/build.sh
Fixes issues with native AWT library loading.
> [zxing] Enable AWT headless mode

- projects/bls-signatures/build.sh
This enables and tests some additional math functions
> [bls-signatures] Enable Fp2 math

- projects/qemu/project.yaml
> qemu: add Mauro to the auto_ccs

- infra/base-images/base-builder-new/cargo
- infra/base-images/base-builder-new/compile_go_fuzzer
Although i'm getting rid of this image soon. I want to fix it so I can test the clang migration.
> [base-builder-new] Fix issues

- infra/build_and_push_test_images.py
- infra/cifuzz/run_fuzzers_entrypoint.py
Fixes https://github.com/google/oss-fuzz/issues/6247
> [languages] Handle language builders in cifuzz and build_and_push_test_images.

- projects/sound-open-firmware/project.yaml
Adding more people to help fix bugs
> sound-open-firmware: add more CCs

- projects/pidgin/project.yaml
Add two additional Pidgin contributors so they can help me with this. Also removed the people that helped me set this up as I haven't heard from them since June.
> Add additional pidgin developers so they can help

- docs/advanced-topics/code_coverage.md
Cf https://github.com/google/oss-fuzz/pull/6312#issuecomment-912571588
cc @thomasvl
> Doc: adds swift to the list of languages supporting coverage

- projects/swift-protobuf/build.sh
These just landed in apple/swift-protobuf/1166
cc @catenacyber @inferno-chromium
> Copy dictionaries over to help steer fuzzing.

- docs/getting-started/new-project-guide/go_lang.md
- docs/getting-started/new-project-guide/jvm_lang.md
- docs/getting-started/new-project-guide/python_lang.md
- docs/getting-started/new-project-guide/rust_lang.md
- docs/getting-started/new_project_guide.md
> doc: use lang-specific base-builder images

- projects/netcdf/Dockerfile
Should fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=38300
> Netcdf: adds zlib dependency

- docs/getting-started/new_project_guide.md
Solves https://github.com/google/oss-fuzz/issues/6425
> doc: explicitly mention dynamic and static linking of fuzzers

- projects/mysql-server/build.sh
- projects/mysql-server/fix.diff
- projects/mysql-server/project.yaml
Should help to fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=29757
> Updates patch for mysql 8.26

- projects/bitcoin-core/Dockerfile
- projects/bitcoin-core/build_cryptofuzz.sh
> bitcoin-core: Re-enable schnorr_fun

- infra/cifuzz/clusterfuzz_deployment.py
- infra/cifuzz/filestore/__init__.py
- infra/cifuzz/filestore/git/__init__.py
- infra/cifuzz/filestore/github_actions/__init__.py
- infra/cifuzz/run_fuzzers.py
Actually remove pruned files.
Fixes #6376.
> CFLite: Fix corpus pruning for git store.

- projects/bls-signatures/project.yaml
Remove Justin per his request.
> [bls-signatures] Update CC list

- infra/helper.py
Fixes: https://github.com/google/oss-fuzz/issues/6452
> [helper] Use base-runner to check if fuzzer exists.

- projects/gvisor/Dockerfile
- projects/gvisor/build.sh
- projects/gvisor/project.yaml
- projects/gvisor/state_fuzzer.go
@amscanne @ghanan94 @fvoznika @kevinGC @nixprime @ayushr2
Are you interested in integrating gVisor into OSS-fuzz for continuous fuzzing?
To complete the integration a maintainers email address is needed for bug reports.
> [gVisor] Initial integration

- projects/tint/build.sh
To avoid sanitizer errors during corpus prepraration (and also to speed
it up) this change build an uninstrumented version of spirv-as.
> Use uninstrumented spirv-as for corpus prep

- projects/openweave/Dockerfile
- projects/openweave/build.sh
- projects/openweave/patch.diff
This one is not ready to be merged in
> openweave: fix build to work with latest base builder

- projects/nettle/Dockerfile
- projects/nettle/build.sh
Related: #6473
While I'm at it, I also noticed nettle is on the "Projects broken on Ubuntu 20.04" list, so gave it a try :-)
cc @guidovranken
> nettle: Use default focal image

- projects/cryptofuzz/Dockerfile
- projects/cryptofuzz/build.sh
NSS currently fails to compile. Disabling until it is fixed.
> [cryptofuzz] Temporarily disable NSS

- infra/base-images/base-builder/compile
Fixes: https://github.com/google/oss-fuzz/issues/6427
> Copy libc++ to /usr/local/lib instead of /usr/lib

- projects/php/build.sh
This enables the function-jit fuzzer on oss-fuzz. We have to exclude memory and undefined sanitizers as these are currently not supported.
> [php] Add function-jit fuzzer

- infra/cifuzz/fuzz_target.py
- infra/cifuzz/fuzz_target_test.py
- infra/cifuzz/requirements.txt
> Use libClusterFuzz for reproduction.

- infra/utils.py
Should fix CIFuzz failures for Java projects: https://github.com/bazelbuild/rules_fuzzing/runs/3736984782
> [infra] Add block listed target name logic from ClusterFuzz

- projects/tendermint/project.yaml
@cmwaters is the new Tendermint Core manager 🎉  replacing my contact info with his.
> update tendermint/tendermint project file

- projects/suricata/build.sh
to be used as config by a dedicated target
> suricata: default rules in out directory

- infra/templates.py
> [clusterfuzzlite] Include shebang line when generating project.

- projects/exiv2/build.sh
> Fix false positive result due to floating point divide by zero

- infra/bisector.py
A printed message after bisection should be different depending on the bisection type
> [infra] Add different messages depending on bisection type

- infra/base-images/base-runner/test_all.py
- infra/cifuzz/build_fuzzers.py
- infra/cifuzz/build_fuzzers_entrypoint.py
- infra/cifuzz/build_fuzzers_test.py
- infra/cifuzz/fuzz_target.py
- infra/cifuzz/run_fuzzers_test.py
Fixes: https://github.com/google/oss-fuzz/issues/6525
Depends on: https://github.com/google/oss-fuzz/pull/6530
> clusterfuzzlite: Upload builds after bad build check.

- infra/cifuzz/build_fuzzers.py
- infra/cifuzz/config_utils.py
- infra/cifuzz/docker.py
> [cifuzz][prow] Support docker in docker to support prow.

- infra/helper.py
Say path doesn't exist instead of the last directory in path.
Fixes: https://github.com/google/oss-fuzz/issues/6528
> [cifuzz][helper] Fix error message for nonexistent external project

- projects/suricata/build.sh
As inspired by https://github.com/rust-fuzz/cargo-fuzz/commit/b4df3e58f767b5cad8d1aa6753961003f56f3609
> Suricata sancov

- projects/freeradius/build.sh
...and hopefully fix the the coverage builds (for FreeRADIUS).
> Pass the correct flags to enable coverage profiling

- infra/cifuzz/fuzz_target.py
- infra/cifuzz/run_fuzzers.py
> Don't set seed for batch fuzzing.

- infra/templates.py
Also remove an incorrect quote in the non-external project.yaml generation.
> Write project.yaml for external generator.

- infra/helper.py
See: https://github.com/google/oss-fuzz/issues/6758
> [cfl] Temporary fix for testcase_path in reproduce.

- infra/cifuzz/config_utils.py
- infra/cifuzz/platform_config/__init__.py
- infra/cifuzz/platform_config/gcb.py
- infra/cifuzz/platform_config/prow.py
Also clean up https://github.com/google/oss-fuzz/pull/6744
> Make gsutil the default filestore on GCB.

- projects/duckdb/project.yaml
CR https://github.com/duckdb/duckdb/pull/2501#issuecomment-961901651
> duckdb: add maintainer

- projects/envoy/project.yaml
Signed-off-by: Kirtimaan <krajshiva@google.com>
> Add x-41 developers for reviewing open Envoy fuzz bugs 

- projects/suricata/Dockerfile
- projects/suricata/build.sh
Should fix CIFuzz broken builds...
> suricata: uses pcre2 release from github

- projects/opendds/project.yaml
Paging the OpenDDS maintainer: @mitza-oci (no pressure: I just want to have this off my local branch).
To @google folks:
- DDS is a standard maintained by OMG, and there are several implementors, 3 of which are open source
- ✅  Fast-DDS: already integrated in oss-fuzz
- ✅ CycloneDDS: has just been integrated
- 👆 OpenDDS: I'm working with their maintainers to have it integrated
- DDS and its implementations are used in all critical sectors
- healthcare
- transportation
- avionics
- defense
- manufacturing
- mining
- robotics
- telco
- cloud
- [more here...](https://www.omgwiki.org/ddsf/doku.php?id=ddsf:public:applications:start)
- DDS is the foundation networking layer of ROS2 (the Robot Operating System, which is basically "the Ubuntu of robotics")
- among the most notable …
> New project.yaml for OpenDDS

- projects/util-linux/Dockerfile
- projects/util-linux/project.yaml
The repository was moved recently
> [util-linux] switch to the util-linux organization

- projects/libra/project.yaml
https://github.com/google/oss-fuzz/pull/6624#issuecomment-963759684
> libra: remove contacts

- projects/teleport/project.yaml
does the same as https://github.com/google/oss-fuzz/pull/6813 but also fixes the CI
> teleport: fix project yaml and contacts

- projects/binutils/build.sh
CR https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=0d64622696e02ad649d048f4af3a3f293481f89f
> binutils: fix build

- projects/apache-httpd/Dockerfile
- projects/apache-httpd/build.sh
This is to solve https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=37001
> apache-httpd: build pcre from scratch

- projects/binutils/build.sh
- projects/binutils/fuzz_dwarf.c
> binutils: fuzz dwarf

- projects/zydis/Dockerfile
- projects/zydis/build.sh
This PR adds two new fuzzer targets and accompanying corpora for Zydis. Additionally, it introduces a `max_len` for each target to improve performance.
> zydis: Add more fuzzer targets

- projects/oak/build.sh
This should correctly fix the path and fix coverage build failures too.
> oak: Correct path fix

- projects/rustls/Dockerfile
- projects/rustls/build.sh
- projects/rustls/rustc.py
The solution of https://github.com/google/oss-fuzz/pull/6851 should also be usable here
> rustls: fix coverage build

- projects/kimageformats/Dockerfile
- projects/kimageformats/build.sh
- projects/kimageformats/kimgio_fuzzer.cc
> kimageformats: build libjxl and JXL Qt plug-in

- projects/lame/Dockerfile
- projects/lame/build.sh
> Fix lame build

- projects/systemd/Dockerfile
https://github.com/systemd/systemd/pull/21438
> [systemd] move apt-gets and pips to the systemd repository

- projects/tensorflow/Dockerfile
- projects/tensorflow/build.sh
- projects/tensorflow/project.yaml
Cf https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=35503
A better fix would be to use `bazel_build_fuzz_tests` cf https://google.github.io/oss-fuzz/getting-started/new-project-guide/bazel/#bazel-projects
> Fix tensorflow build

- projects/lighttpd/build.sh
@gstrauss this should fix the build issue
> lighttpd: match upstream changes to fix build

- projects/libvips/project.yaml
See https://github.com/libjxl/libjxl/issues/883
> (temporarily) add libjxl devs to fuzz report CC

- projects/libass/Dockerfile
Build currently fails. This fixes that.
> [libass] Bump meson version

- projects/brotli-java/Dockerfile
- projects/brotli-java/FuzzDecode.java
- projects/brotli-java/build.sh
- projects/brotli-java/project.yaml
Integrates the java code of https://github.com/google/brotli
> brotli-java: initial integration

- projects/php/project.yaml
Add @dstogov to auto_ccs for the PHP project, who will help with triaging fuzzing reports in the future.
> [php] Add Dmitry Stogov to PHP auto_ccs

- projects/libvips/build.sh
> libvips: prefer CMake options over sed replacements

- projects/opensips/Dockerfile
- projects/opensips/build.sh
https://github.com/OpenSIPS/opensips/pull/2697#issuecomment-979333736
> opensips: change build to avoid cifuzz deleting fuzzers

- projects/cyclonedds/Dockerfile
- projects/cyclonedds/build.sh
There's an integration on [cyclonedds](https://github.com/eclipse-cyclonedds/cyclonedds/tree/master/fuzz) ready for this, co-authored with the project maintainer @eboasson.
Signed-off-by: Federico Maggi <fede@maggi.cc>
> Build files for projects/cyclonedds

- projects/imageio/Dockerfile
- projects/imageio/project.yaml
Once https://github.com/imageio/imageio/pull/695  is merged this should work
Thanks to @catenacyber for the suggested Dockerfile fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=35316#c24
> imageio: fix build

- projects/wasmtime/Dockerfile
- projects/wasmtime/build.sh
REF https://github.com/bytecodealliance/wasmtime/pull/3563#issuecomment-981742852
> wasmtime: migrate build to work with CIFUzz

- projects/sigstore/build.sh
Included additional fuzzing targets for sigstore.
> sigstore-Included additional fuzzing targets

- projects/rustcrypto/Dockerfile
- projects/rustcrypto/build.sh
- projects/rustcrypto/project.yaml
RustCrypto is a large suite of cryptographic primitives, including hashes, macs, KDFs, ciphers, cipher modes and more, powering a lot of Rust software.
https://github.com/RustCrypto
Affirmation of the RustCrypto dev: https://github.com/RustCrypto/hashes/issues/326
> [rustcrypto] Initial integration

- projects/libbpf/build.sh
Hopefully it should be more stable than elfutils-0.185
with a bunch of commits on top of it
> [libbpf] point the script to elfutils-0.186

- projects/caddy/Dockerfile
- projects/caddy/build.sh
Should fix https://github.com/caddyserver/caddy/pull/4449
> caddy: update set up for cifuzz

- projects/openjpeg/Dockerfile
- projects/openjpeg/build.sh
Ref https://github.com/uclouvain/openjpeg/pull/1386
solves this issue https://github.com/google/oss-fuzz/issues/6755 for openjpeg
> openjpeg: fix build for cifuzz

- infra/base-images/base-runner/jacoco_report_converter.py
> [java][coverage] Make sure filenames is a string and not a list. 

- projects/django/Dockerfile
- projects/django/build.sh
- projects/django/project.yaml
> [django] Updated Django to use a python based fuzzer.

- projects/clamav/Dockerfile
- projects/clamav/build.sh
ref https://github.com/google/oss-fuzz/issues/6942
CC @micahsnyder
> clamav: update build to fix CIFuzz repo identification

- projects/etcd/Dockerfile
- projects/etcd/build.sh
Adds the fuzzers from https://github.com/cncf/cncf-fuzzing/tree/main/projects/etcd
> [etcd] Add cncf fuzzers

- projects/tdengine/Dockerfile
- projects/tdengine/build.sh
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=41559
> tdengine: fix build

- projects/bitcoin-core/project.yaml
> bitcoin-core: Update auto CC email

- projects/unbound/fuzz_1.c
- projects/unbound/fuzz_4.c
https://github.com/google/oss-fuzz/issues/6841
> unbound: fix new fuzzer names

- projects/brotli-java/FuzzDecode.java
As with most other compressors, brotli input could be a "bomb".
Limiting output size defuses such inputs (to avoid timeouts).
> Stop fuzzing once output size limit is reached

- infra/base-images/base-clang/checkout_build_install_llvm.sh
Fixes: #6957
CC @vanhauser-thc
> [base-clang] Use llvmorg-14-init-11072-gb1bc627e

- projects/gitea/project.yaml
change my general mail to the google specific one
> [gitea] change mail of @6543

- projects/sigstore/build.sh
- Included corpus.
- Included additional targets.
> sigstore - Included corpus

- projects/gonids/372f9bd.diff
- projects/gonids/Dockerfile
- projects/gonids/build.sh
cc @asraa cf https://github.com/golang/go/issues/49075#issuecomment-985830068
> gonids: try to test golang fix

- projects/runc/Dockerfile
- projects/runc/build.sh
Adds the fuzzers from cncf-fuzzing.
> [runc] Add more fuzzers

- projects/hunspell/project.yaml
> [hunspell] Update CC list

- projects/neomutt/Dockerfile
The test code has been merged into master.
Remove the branch reference from the Dockerfile.
I've tested the build locally under Docker, using
```
infra/helper.py build_image neomutt
infra/helper.py build_fuzzers --sanitizer address neomutt
infra/helper.py check_build neomutt
infra/helper.py run_fuzzer neomutt address-fuzz
```
> neomutt: merge test code

- projects/openvpn/build.sh
- projects/openvpn/crypto_patch.txt
- projects/openvpn/fuzz_buffer.c
- projects/openvpn/fuzz_crypto.c
This follows recent upstream updates
> openvpn: fix build

- projects/libsndfile/build.sh
Ref https://github.com/libsndfile/libsndfile/pull/796
> libsndfile: ensure no logging to reduce CIFuzz time

- projects/s2geometry/Dockerfile
- projects/s2geometry/build.sh
- projects/s2geometry/project.patch
- projects/s2geometry/s2_fuzzer.cc
We should push this upstream too as having it part of CMakeLists will prevent future breaks. We could also add CIFuzz on this one
> s2geometry: fix build

- infra/cifuzz/config_utils.py
- infra/cifuzz/fuzz_target.py
- infra/cifuzz/run_fuzzers.py
Fixes https://github.com/google/clusterfuzzlite/issues/65
> Allow projects to always upload crashes even if they are "unreportable".

- infra/cifuzz/fuzz_target.py
- infra/cifuzz/fuzz_target_test.py
Consider the testcase unreproducible.
Fixes: https://github.com/google/oss-fuzz/issues/6952
> [cifuzz] Fix timeout in reproduce.

- infra/base-images/base-builder/Dockerfile
- infra/base-images/base-builder/compile_afl
This reverts commit 95e437c59982cf242d01c53af44181e81a03e4ce.
> Revert "Update afl++ (#7008)"

- projects/etcd/project.yaml
Requested on etcd meeting 16th December 2021 - docs to meeting: https://docs.google.com/document/d/16XEGyPBisZvmmoIHSZzv__LoyOeluC5a4x353CX0SIM/edit#
> etcd: update project.yaml with group email

- projects/binutils/build.sh
- projects/binutils/fuzz_readelf.c
Coverage should be tracked on these to see if they help explore their
respective architectures under the bfd/ directory.
> binutils: add 3 new targetes readelfs

- projects/qt/Dockerfile
The sources are now taken from individual checkouts of the submodules.
> [qt] Remove super repo after copying the cmake helper scripts

- projects/elfutils/project.yaml
https://sourceware.org/bugzilla/show_bug.cgi?id=28715#c9
> [elfutils] make reports public and point OSS-Fuzz to the official mailing list

- projects/libjxl/Dockerfile
The dependency is added in
https://github.com/libjxl/libjxl/pull/1039
> libjxl: add gflags dependency

- projects/ffmpeg/Dockerfile
- projects/ffmpeg/build.sh
Replaces https://github.com/google/oss-fuzz/pull/7087
> ffmpeg: add libxml2 to build

- projects/ecc-diff-fuzzer/Dockerfile
- projects/ecc-diff-fuzzer/build.sh
Should fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=42866
> ecc-diff-fuzzer: updates gmp version

- projects/freetype2/project.yaml
Has been working on FreeType, the FreeType fuzzer, rolling FreeType into
Chromium, and fuzzing FreeType in Chromium.
> [freetype2] Add bungeman to auto_ccs.

- projects/md4c/project.yaml
(Created a new dedicated google account for oss-fuzzing. Still having issues to access the bug reports with the old one.)
> md4c: Update primary_contact e-mail

- infra/cifuzz/actions/run_fuzzers/action.yml
- infra/cifuzz/config_utils.py
- infra/cifuzz/external-actions/run_fuzzers/action.yml
- infra/cifuzz/fuzz_target.py
> [CFL] minimize crashes

- projects/openssl/Dockerfile
- projects/openssl/build.sh
> Prevent OpenSSL from randomly failing AFL++ build

- projects/etcd/project.yaml
@spzala After this PR is merged, you will have access to OSS-fuzz reports. Do allow for a grace period of about an hour for the system to pick up this update.
> [etcd] add maintainer

- projects/ecc-diff-fuzzer/Dockerfile
Should fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=42866
> Ecc mbedtls 3

- projects/croaring/Dockerfile
- projects/croaring/build.sh
- projects/croaring/croaring_fuzzer.c
- projects/croaring/croaring_fuzzer.options
- projects/croaring/project.yaml
Initial implementation to be expanded for coverage over time
> OSS_FUZZ integration for CROARING

- projects/apache-commons/ImagingBmpFuzzer.java
- projects/apache-commons/ImagingGifFuzzer.java
- projects/apache-commons/ImagingJpegFuzzer.java
- projects/apache-commons/ImagingPngFuzzer.java
- projects/apache-commons/ImagingTiffFuzzer.java
- projects/apache-commons/build.sh
Also add --no-transfer-progress to the MAVEN_ARGS to decrease log spam.
> [apache-commons] Fix build after breaking changes

- infra/build/functions/base_images.py
Adds the missing git clone step.
> Fix the separate build for introspector images

- projects/argo/project.yaml
Expanding coverage by adding more project leads and approvers.
> Update project.yaml to add more project maintainers

- projects/libplist/build.sh
As the title says, this adds a fuzzer for the recently added JSON format support in libplist.
> libplist: Add JSON fuzzer

- infra/base-images/base-runner/coverage
This can prevent the side effect reported here  #7188
> Make a separate dir to store covreport files 

- projects/arrow-java/Dockerfile
- projects/arrow-java/FuzzIpcFile.java
- projects/arrow-java/FuzzIpcStream.java
- projects/arrow-java/build.sh
- projects/arrow-java/project.yaml
Arrow-Java is the Java implementation of Apache Arrow. 
This submission is for fuzzing the Arrow Java IPC reader.
> Submit Arrow-Java for inclusion

- projects/exprtk/exprtk_fuzzer.cpp
- projects/exprtk/project.yaml
Similar to this PR: https://github.com/google/oss-fuzz/pull/7062
> Update RTC define and enable MSAN functionality

- infra/base-images/base-builder/compile
This makes compile script compatible with #7189
> Adjust to coverage reports dir renaming

- projects/spidermonkey-ufi/build.sh
avoid endless loop, same as https://github.com/google/oss-fuzz/pull/7210/commits/e60aec27623bd6459db07ae50a9a0b16bba12a81
> spidermonkey-ufi: fix build

- projects/lz4/project.yaml
- projects/zstd/project.yaml
* Remove old team members
* Add new team members
> [lz4][zstd] Update CC list

- infra/build/functions/build_and_run_coverage.py
- infra/build/functions/build_lib.py
Had to return empty list if download_coverage_data_steps fails.
> Handle error in downloading coverage data

- projects/harfbuzz/project.yaml
I have not been a Google employee for a few years...
> [harfbuzz] Remove obsolete address

- infra/cifuzz/platform_config/gitlab.py
cc @jonathanmetzman cf https://github.com/google/clusterfuzzlite/commit/08da14203d40bb2f241e797945049d7f5c913abf#r64665217
> cifuzz: gitlab filestore by default on gitlab platform

- infra/base-images/base-builder/install_go_CodeIntelligenceTesting.sh
- Include ossfuzz_coverage_runner.go again.
> Fix codeintelligencetesting image.

- infra/base-images/base-builder-go-codeintelligencetesting/Dockerfile
- infra/base-images/base-builder/install_go_CodeIntelligenceTesting.sh
- infra/ci/build.py
Addressing new comments in [PR#7191](https://github.com/google/oss-fuzz/pull/7191):
1. Avoid cding & using relative directory.
2. To include go-codeintelligencetesting to auto-checks.
3. Remove trailing empty lines
4. Correct copyright year
> Base builder go experimental

- docs/advanced-topics/reproducing.md
> Add oss-fuzz checkout instruction to reproducing.md

- projects/libecc/Dockerfile
- projects/libecc/build.sh
- Enable additional operations
- Add libgmp for comparing results against (specifically extended GCD, which Botan doesn't support)
> [libecc] Updates

- projects/jackson-core/Dockerfile
- projects/jackson-dataformat-xml/Dockerfile
- projects/jackson-dataformats-binary/Dockerfile
This is the new main development branch.
> [jackson] Fuzz the 2.14 branch

- projects/cryptofuzz/Dockerfile
- projects/cryptofuzz/build.sh
- projects/wolfssl/build.sh
wolfCrypt removed the RABBIT and IDEA ciphers, and added AES-SIV.
> [cryptofuzz,wolfssl] Update wolfCrypt configuration

- infra/cifuzz/actions/build_fuzzers/action.yml
- infra/cifuzz/config_utils.py
- infra/cifuzz/external-actions/build_fuzzers/action.yml
targets.
Fixes: https://github.com/google/clusterfuzzlite/issues/85
> This allows users to skip CIFuzz's logic to only run affected fuzz

- projects/envoy/project.yaml
> envoy: add service accounts for copybara for envoy

- projects/ossf-scorecard/project.yaml
Part of https://github.com/ossf/scorecard/issues/1618.
Signed-off-by: Stephen Augustus <foo@auggie.dev>
cc: @azeemshaikh38 @inferno-chromium @laurentsimon @naveensrinivasan
> projects: Add OpenSSF scorecard

- projects/wasmtime/project.yaml
cc: @jfoote @alexcrichton @fitzgen
> wasmtime: Add Peter Huene to the auto cc list.

- projects/skia/project.yaml
Everything compiles, links and passes the check_build locally.
> [skia] Re-enable MSAN

- projects/libecc/Dockerfile
- projects/libecc/build.sh
Add wolfCrypt for comparing against libecc's ECDH output.
> [libecc] Add wolfCrypt

- projects/unbound/build.sh
https://github.com/luisx41 is no longer available
FYI @gthess
> unbound: fix build by removing use of broken links

- projects/igraph/project.yaml
This PR adds access for @vtraag
> [igraph] include another igraph maintainer

- projects/kubernetes-cluster-api/project.yaml
Signed-off-by: killianmuldoon <kmuldoon@vmware.com>
> Add Killian Muldoon to Kubernetes Cluster API

- projects/esp-v2/build.sh
The esp-v2 build has been broken for more than half a year. This PR fixes it. The main limitation was an outdated use of bazel and fuzzing build rules.
> esp-v2: fix build

- projects/h2o/project.yaml
Hello,
Emmanuel is going to work on the h2o project with us and it would be beneficial for him to access the dashboard to obtain a snapshot of outstanding issues, etc. Could you please add him?
cc: @kazuho @mootoh
Thank you,
Hajime
> Add Emmanuel to h2o project

- projects/helm/project.yaml
Please add me to the helm fuzzing project.
Thank you.
> Add email to helm project

- projects/wolfssl/Dockerfile
- projects/wolfssl/build.sh
- Imports Wycheproof ECDH test vectors
- Imports OpenSSL's and LibreSSL's corpora for their native bignum fuzzers
> [wolfssl] Import more tests/corpora

- projects/envoy/project.yaml
DO NOT MERGE UNTIL https://github.com/google/oss-fuzz/issues/7318 IS RESOLVED
> envoy: add project wide label to envoy

- projects/apache-commons/project.yaml
- projects/fastjson2/project.yaml
- projects/jackson-core/project.yaml
- projects/jackson-dataformat-xml/project.yaml
- projects/jackson-dataformats-binary/project.yaml
- projects/java-example/project.yaml
- projects/json-sanitizer/project.yaml
- projects/kryo/project.yaml
- projects/log4j2/project.yaml
- projects/protobuf-java/project.yaml
- projects/zxing/project.yaml
@bertschneider will co-maintain Jazzer and should have access to
findings for projects integrated by Code Intelligence.
> Add new CI employee to Java projects

- infra/base-images/base-runner/coverage
First part of #7015.
Does not include Go/Java yet.
The Cloud Build changes to upload these will also come in another PR.
> Generate per-target coverage reports.

- infra/base-images/base-builder/install_swift.sh
> Pin LLVM revision used for Swift llvm-symbolizer patch.

- projects/libgit2/build.sh
Ref: https://github.com/libgit2/libgit2/pull/6133
> libgit2: fix build following libgit2 upgrade

- projects/elfutils/Dockerfile
- projects/elfutils/project.yaml
Adding myself as maintainer for `elfutils`.
I would be very happy to contribute the project. @fche are you okay with me adding myself? I have done a lot of the work in fuzzing `binutils` (https://github.com/google/oss-fuzz/tree/master/projects/binutils) and would like to assist with `elfutils`. 
elfutils was added by Googler @izzeem in: https://github.com/google/oss-fuzz/pull/6670
elfutils has an open-as-possible policy: 
https://github.com/google/oss-fuzz/blob/9b5a750c7f39a1efa194b37f5233b54ef75433c3/projects/elfutils/project.yaml#L17
https://github.com/google/oss-fuzz/blob/9b5a750c7f39a1efa194b37f5233b54ef75433c3/projects/elfutils/project.yaml#L4
> elfutils: add myself to project.yaml

- infra/build/functions/build_and_run_coverage.py
- infra/build/functions/test_data/expected_coverage_build_steps.json
> Upload per target coverage report.

- projects/ffmpeg/build.sh
> [FFmpeg] Update build.sh after config.h was split

- infra/build/functions/build_and_run_coverage.py
- infra/build/functions/test_data/expected_coverage_build_steps.json
This reverts commit a56b6259eb283b10500b6a4b6c58251ac6d04f35.
> Revert "Upload per target coverage report. (#7389)"

- infra/base-images/base-builder/Dockerfile
Ref: https://github.com/ossf/fuzz-introspector/pull/136
> infra: fuzz-introspector: force no inline
