infra/cifuzz/fuzz_target.py
infra/cifuzz/run_fuzzers.py

Even if we don't want to report them, print the stacktrace.
Related: https://github.com/google/oss-fuzz/issues/5461

[CIFuzz] Print crash stacktraces no matter what

---

projects/mupdf/pdf_fuzzer.cc

Previously the allocator handled small pointer values incorrectly
and prevented multiple executions (unexpectedly used when OSS-fuzz
uses LSAN to look for memory leaks).

[mupdf] Improve custom allocator

---

projects/capnproto/Dockerfile
projects/capnproto/build.sh
projects/capnproto/project.yaml

cc @kentonv
Are you interested in continuous fuzzing for capnproto ?
This draft PR enables it with oss-fuzz
(PS : the fuzz target quickly finds what seems to me an infinite loop (resulting in out-of-memory) that I can reproduce with `capnp convert --quiet binary:packed < oom-e188e3b0a20731dad7ed328edc8c13c3b8d09439 > /dev/null`)

Adds capnproto project

---

infra/base-images/base-builder/Dockerfile
infra/base-images/base-builder/bazel_build_fuzz_tests
projects/bazel-rules-fuzzing-test/build.sh

Before I update the documentation and other Bazel projects, I wanted to get your early input on the approach.

Implement the Bazel building recipe as a stand-alone script that can be invoked from build.sh.

---

projects/lotus/Dockerfile
projects/lotus/build.sh

Some of the fuzzers in this project can currently not be compiled with coverage. 
This fix ignores those fuzzers to avoid preventing coverage for the fuzzers that do compile.

[lotus] Fix coverage build

---

projects/httparse/Dockerfile
projects/httparse/build.sh
projects/httparse/project.yaml

[httparse](https://crates.io/crates/httparse) is a http parser user by widely-used Rust libraries e.g. Tokio-core (used by many to implement asynchronous I/O) and hyper https://crates.io/crates/httparse/reverse_dependencies. 
@seanmonstar would you be interested in integrating httparse into oss-fuzz? It will make the fuzzers run continuously and you will receive reports whenever crashes are found. If you would like to integrate, could you please provide a set of email(s) that will get access to the data produced by OSS-Fuzz, such as bug reports. The emails should be linked to a Google account in order to view the detailed reports and notice the emails affiliated with the project will be public in the OSS-Fuzz repo, as they will be part of a configuration file.

httparse: Initial integration

---

projects/rustls/Dockerfile
projects/rustls/build.sh
projects/rustls/persist.rs
projects/rustls/project.yaml

Rustls is a modern TLS library written in Rust used by production systems, e.g. the purpose-built service mesh proxy linkerd2-proxy.
@ctz @briansmith would you be interested in integrating rustls into oss-fuzz? It will make the fuzzers run continuously and you will receive reports whenever crashes are found. If you would like to integrate, could you please provide a set of email(s) that will get access to the data produced by OSS-Fuzz, such as bug reports. The emails should be linked to a Google account in order to view the detailed reports and notice the emails affiliated with the project will be public in the OSS-Fuzz repo, as they will be part of a configuration file.

rustls: initial integration.

---

projects/java-example/default.options

The JVM uses custom SIGSEGV handlers, which leads to fuzzer crashes on
ClusterFuzz when running with ASAN likely due to the
allow_user_segv_handler=1 default on the platform.

[java-example] Speculative fix for JVM segfault crashes

---

projects/libjpeg-turbo/Dockerfile

Installing the i386 libstdc++ SDK was part of a failed effort to fix the
i386 fuzz targets.  They have been fixed in a different way.

[libjpeg-turbo] Remove unneeded pkg in Dockerfile

---

infra/base-images/base-builder/bazel_build_fuzz_tests
projects/bazel-rules-fuzzing-test/build.sh
projects/cel-cpp/build.sh

This reduces the build.sh file to a single line.

Switch the cel-cpp project to the new Bazel build script.

---

projects/mupdf/Dockerfile
projects/mupdf/build.sh

This makes it easier to build the fuzzer using a locally checked
out git repo without having to manually copy the fuzzer glue code
into the locally checked out git repo first.

[mupdf] Copy fuzzer glue code to dir outside of git repo

---

projects/quick-xml/Dockerfile
projects/quick-xml/build.sh
projects/quick-xml/fuzz_target_1.rs
projects/quick-xml/project.yaml

@tafia I have set up continuous fuzzing of quick-xml. The benefits are that the fuzzer will be run on a regular basis and bug reports will be send to your email with details on the oss-fuzz.com interface about the bugs. Is this something you would be happy to have set up? If so, the only thing needed from your end is an email that will receive the bugs reports - notice this email should be attached to a Google account for you to see the reports.
I noticed you had an existing fuzzer in the repo, but I had to make a slight change to make it work as the fuzzer in your repo does not build.

quick-xml: initial integration

---

projects/hermes/project.yaml

OSS Fuzz tends to mostly find bugs in the parser, which is mostly worked on by @avp and @Huxpro.

Add a maintainer to the Hermes OSS Fuzz project

---

projects/binutils/build.sh

gdb sources have been reorganised.  Disable more directories when
building the binutils fuzzers.

Don't build parts of gdb when testing binutils

---

projects/golang/Dockerfile
projects/golang/build.sh

This PR solves two problems:
1. I am getting errors when building with coverage. These are the same errors that occur in this PR as well: https://github.com/google/oss-fuzz/pull/5437. 
2. It also cleans up the build by using gomodules and refactoring the `Dockerfile` and `build.sh`.

[golang] Refactor build

---

infra/triage-party/deploy.sh

I've already redeployed with this image, seems to be working as expected.

Store triage party image in oss-fuzz-base repo

---

infra/base-images/base-builder/compile_afl

This was accidently disabled, noticed by @vanhauser-thc

Enable generated dict in AFL++

---

projects/wasm3/Dockerfile
projects/wasm3/build.sh
projects/wasm3/project.yaml

@vshymanskyy 
Would you be interested in integrating with OSS-fuzz.
This will allow OSS-fuzz to run the fuzzer continuously and notify you via email when bugs are found.
The build script has a few debugging leftovers, but I will remove those before merging.
To complete this draft, a maintainers email address is needed for the project.yaml file.
~~Currently the AFL returns the following error (It has therefore been disabled for now). It looks unrelated to AFL itself. @vshymanskyy Do you see an easy fix here?~~

[wasm3] Initial integration

---

projects/linkerd2-proxy/Dockerfile
projects/linkerd2-proxy/build.sh
projects/linkerd2-proxy/project.yaml

https://github.com/linkerd/linkerd2-proxy
linkerd2-proxy is a proxy for the [linkerd](https://linkerd.io/) service Mesh and is used by many customers including (from https://linkerd.io/ ) Expedia, HP, GoDaddy, Walmart, ...

linkerd2-proxy: initial integration

---

projects/protobuf-c/build.sh

Fix fuzzer build after upstream changes.
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=33027
cc: @guidovranken

protobuf-c: fix build

---

projects/suricata/build.sh

Improves suricata fuzzing by having dedicated fuzz targets per protocol.
SMB had pretty ow coverage and having a dictionary for its custom fuzz target allows it to get much more coverage
Also improves `MSAN_OPTIONS` as advised in https://github.com/google/sanitizers/issues/1389

Suricata more targets

---

projects/java-example/ExampleFuzzerNative.cpp

Java native libraries should now be fuzzed correctly, but the current crash is still reported as flaky due to the multiple fixes required to make it work.
This commit should trigger a clean new finding.

[java-example] Trigger new native finding

---

projects/cilium/project.yaml

This adds three Cilium maintainers and updates one maintainer's email
address to match the Google Account email. Previously an alternative
email was used, which did not give access to the ClusterFuzz dashboard.

cilium: Update contact emails

---

projects/systemd/Dockerfile

Now that https://github.com/mesonbuild/meson/issues/8345 is closed,
it should be safe to keep rolling forward.
This reverts commit ac290e7ed7b600c685d3d6b455b58fda122b88b0.

Revert "[systemd] roll back to meson-0.56.2 (#5199)"

---

infra/cifuzz/fuzz_target.py

After https://github.com/google/oss-fuzz/pull/5473:
presubmits fail with
```
************* Module infra.cifuzz.fuzz_target
infra/cifuzz/fuzz_target.py:145:51: E0602: Undefined variable 'stderr' (undefined-variable)
infra/cifuzz/fuzz_target.py:148:34: E0602: Undefined variable 'stderr' (undefined-variable)
```
see https://github.com/google/oss-fuzz/pull/5427/checks?check_run_id=2325894288

[cifuzz] fix bug appearing in CI

---

projects/cosign/Dockerfile

We added a new Yubikey feature to cosign which depends on these packages
closes https://github.com/google/oss-fuzz/issues/5603

Install packages in cosign project to fix fuzzing error

---

projects/postgresql/project.yaml

Build never succeeded and causes ClusterFuzz exceptions.

[postgresql] Remove AFL fuzzing engine.

---

projects/draco/project.yaml

All draco builds have been broken since December.
This means that the old AFL builds are still running on ClusterFuzz.
This is causing exceptions because the old AFL builds don't work
with the ClusterFuzz code which assumes AFL++.
Fixes #5610

[draco][AFL] Disable AFL builds to stop ClusterFuzz exceptions

---

projects/golang/Dockerfile
projects/golang/build.sh
projects/golang/math_big_fuzzer.go

This PR adds two fuzzers for `math/big` of the golang standard library. The fuzzers were originally uploaded here: https://go-review.googlesource.com/c/go/+/301710, but since maintainers are not interested in adding new fuzzers upstream, I am uploading them directly to OSS-fuzz.

[golang] Added 2 fuzzers

---

projects/envoy/build.sh

cc @asraa @htuch this is a more aggressive approach to disabling coverage instrumentation. Removing the coverage instrumentation from the `test` directory in particular has impact on the speed. We can still go more aggressive IMO - but it would be good to see the effects of this PR first.

envoy: further optimisations

---

infra/cifuzz/docker.py

It's probably fine to run another one, so just do that.
Also increase the amount of time we will wait to 5 seconds.
Fixes https://github.com/google/oss-fuzz/issues/5621

[CIFuzz] Ensure we don't through exception if we can't stop container

---

projects/swift-nio/Dockerfile
projects/swift-nio/Package.swift
projects/swift-nio/build.sh
projects/swift-nio/fuzz_http1.swift
projects/swift-nio/llvmsymbol.diff
projects/swift-nio/project.yaml

@oliverchang 
Here is another swift project integration cf https://github.com/google/oss-fuzz/pull/5493
To have a good oss-fuzz integration, I think we would need to
- move the swift compiler in base-builder
- add documentation about swift project integration
- Use the swift demangler in libFuzzer output (I do not know how to do that)
- Have some utility script (to handle different sanitizers, test the coverage)
Do you see anything else ?

Adds swift-nio project

---

projects/cras/Dockerfile

Install vim to get `xxd` for source generation.
BUG=oss-fuzz:33362

[CRAS] Fix build error

---

projects/json-patch/Dockerfile
projects/json-patch/build.sh
projects/json-patch/fuzz_create_merge.go
projects/json-patch/fuzz_decode_apply.go
projects/json-patch/project.yaml

@evanphx would you be interested in continuous fuzzing for json-patch ?
This PR enables it with 2 fuzz targets inspired by the use cases from the README
It quickly finds a panic from a buffer over read in `json-patch.Patch.Apply

Adds go json-patch project

---

projects/wazuh/Dockerfile
projects/wazuh/build.sh
projects/wazuh/fuzz_xml.c
projects/wazuh/fuzz_xml.options
projects/wazuh/project.yaml

Wazuh is a free, open source and enterprise-ready security monitoring solution for threat detection, integrity monitoring, incident response and compliance. On the main homepage: https://wazuh.com/ you can see the list of users, which includes salesforce, groupon and other large organisations.
@vikman90 I have set up continuous fuzzing of wazuh.  Is this something you would be happy to have set up? The benefits are that the fuzzers will be run on a regular basis and bug reports will be send to your email with information such as inputs that trigger the bugs, stack traces and more. If you would like to get Wazuh in, the only thing needed from your end is an email that will receive the bugs reports - notice this email should be attached to a Google account for you to see the reports.

wazuh: initial integration.

---

infra/base-images/base-runner/Dockerfile

The library libXext.so.6 is required by some Java AWT classes even in
headless environments.
This fixes a crash in apache-commons:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=33489

Add missing Java AWT dependency

---

docs/further-reading/clusterfuzz.md
docs/further-reading/fuzzer_environment.md
docs/getting-started/new-project-guide/bazel.md
docs/getting-started/new_project_guide.md
docs/oss-fuzz/architecture.md
docs/reference/glossary.md

Hello,
Found a few typos reading the docs, then ran the code inspection tool from within WebStorm. Not a native speaker, so feel free to suggest edits :+1: 
The link to Jenkins was broken due to the missing protocol — Markdown link gets resolved to relative path, causing the error.
Thanks for OSS Fuzz!
Bruno

Fix typos and one link

---

projects/linkerd2-proxy/build.sh

Enable coverage for all fuzzers and remove limitation on lints. 
This is following upstream fixes, namely https://github.com/linkerd/linkerd2-proxy/pull/983 and https://github.com/linkerd/linkerd2-proxy/pull/977

clean up linkerd2 build.

---

projects/spidermonkey/Dockerfile
projects/spidermonkey/build.sh

Cc @oliverchang @inferno-chromium
This builds locally for me but of course I can't test locally if it will fix the problem.

Set rpath on js binary to properly resolve included libraries on runner

---

projects/java-example/project.yaml

`java-example` has produced all the expected findings and there are now sufficiently many Java projects with status badges that build failures caused by issues with Jazzer would be noticed quickly.

Disable java-example

---

projects/bignum-fuzzer/Dockerfile
projects/cryptofuzz/Dockerfile
projects/ecc-diff-fuzzer/Dockerfile
projects/mbedtls/Dockerfile

The default branch of https://github.com/ARMmbed/mbedtls is about to change to point to the work on the next major release (3.0). We expect frequent API changes during that time. Switch fuzzers to run on the stable major version of Mbed TLS (2.x) during the transition period.
Expected timeline:
* Default branch change to the 3.0 preview unstable branch: [April 22](https://lists.trustedfirmware.org/pipermail/mbed-tls/2021-April/000327.html)
* Stabilization of 3.0: June

Use the 2.x branch of Mbed TLS

---

projects/bls-signatures/Dockerfile
projects/bls-signatures/build.sh
projects/bls-signatures/project.yaml

Differential fuzzing of 3 BLS signature libraries
- blst https://github.com/supranational/blst
- Chia bls-signatures https://github.com/Chia-Network/bls-signatures/
- Herumi mcl https://github.com/herumi/mcl
BLS signatures are a critical security feature in cryptocurrency clients, such as:
- Ethereum 2.0
- Chia
- DFinity
- Filecoin
If this project is accepted, I will add more auto_cc's later.

[bls-signatures] Initial integration

---

projects/apache-commons/project.yaml

I'm committer of Apache Commons and I got a google account(peteralfredlee@gmail.com), so I'm adding myself to the `auto_ccs` of apache commons. And I'm working with primary contact @bodewig in apache commons.
I'm not familiar with the procedure of oss-fuzz, do I need @bodewig to sign off my PR?

Add peter's google account to apache commons

---

projects/bls-signatures/build.sh

Apologies, I forgot this initially. This scopes the operations to those offered by the BLS signature libraries, and doesn't run unrelated operations (e.g. encryption). So the purpose of this PR is that it makes fuzzing more efficient.

[bls-signatures] Scope operations

---

projects/cras/build.sh

Fix build failures:
```
error: /out/src/rate_estimator.rs: No such file or directory
warning: The file '/src/rate_estimator.rs' isn't covered.
error: /out/src/rate_estimator_bindings.rs: No such file or directory
warning: The file '/src/rate_estimator_bindings.rs' isn't covered.
```
Bug: crbug/oss-fuzz/31910
Test: {build_fuzzer, coverage} commands in infra/helper.py for cras

cras: Add rust source soft links for coverage build

---

projects/opencensus-cpp/.bazelrc
projects/opencensus-cpp/Dockerfile
projects/opencensus-cpp/WORKSPACE
projects/opencensus-cpp/build.sh
projects/opencensus-cpp/project.yaml

@g-easy would you be interested in continuous fuzzing for opencensus-cpp ?
This PR enables it with oss-fuzz with your fuzz targets.
It changes a bit the Basel build system to use https://github.com/bazelbuild/rules_fuzzing and https://google.github.io/oss-fuzz/getting-started/new-project-guide/bazel/ cf 
cc @stefanbucur could `cc_fuzz_test` support corpus like it is used here https://github.com/census-instrumentation/opencensus-cpp/blob/ba631066779a534267fdb1321b19850eb2b0c000/opencensus/tags/BUILD#L194

Adds bazel project opencensus-cpp

---

projects/lxc/project.yaml

[lxc] turn off AFL for now
It seems LXC is failing to compile with AFL with
```
../../src/lxc/storage -pthread -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -stdlib=libc++ -Wl,--as-needed -Wl,--gc-sections -Wl,-z -Wl,relro -Wl,-z -Wl,now -pie -Wl,-fuse-ld=gold -o fuzz-lxc-define-load fuzz_lxc_define_load-fuzz-lxc-define-load.o  ../lxc/.libs/liblxc.a /usr/lib/libFuzzingEngine.a -lpthread -pthread
Step #32: /usr/bin/ld: /usr/lib/libFuzzingEngine.a(aflpp_driver.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
Step #32: /usr/lib/libFuzzingEngine.a: error adding symbols: Bad value
Step #32: clang-12: [0;1;31merror: [0m[1mlinker …
```

[lxc] turn off AFL for now

---

projects/php/build.sh

It is now necessary to specify the --build architecture for -m32 builds, otherwise we'll end up using x64 assembly files.

[php] Fix i386 build

---

projects/lxc/project.yaml

This reverts commit 181b3575afc392c704ae3be02baf0c4b8150cd87.
The issue was fixed in https://github.com/google/oss-fuzz/pull/5691
It should be merged once https://github.com/google/oss-fuzz/pull/5691 lands in the base-builder image

Revert "[lxc] turn off AFL for now (#5685)"

---

projects/libheif/build.sh

It seems that since commit https://github.com/strukturag/libheif/commit/3c9e58125109cc604f953a3dbeb985a40ba2b461 libheif was unable to find the headers of libaom since they are installed in a non-standard prefix.
```
checking for aom... yes
checking aom/aom_decoder.h usability... no
checking aom/aom_decoder.h presence... no
checking for aom/aom_decoder.h... no
checking aom/aom_encoder.h usability... no
checking aom/aom_encoder.h presence... no
checking for aom/aom_encoder.h... no
<snip />
configure: libaom decoder: no
configure: libaom encoder: no
```
This PR resolves that by ensuring that autotools is aware of libaom's include directory.
/cc @fancycode

[libheif] Ensure libaom can be found

---

docs/getting-started/new_project_guide.md

Fix typo on https://google.github.io/oss-fuzz/getting-started/new-project-guide

docs: Fix syntax error typo

---

projects/bitcoin-core/build.sh
projects/bitcoin-core/project.yaml

* Add workaround for `undefined reference to '__mulodi4'`
* Add missing `git checkout --` (bugfix)
* Add i386 architecture

bitcoin-core: Add i386

---

projects/bitcoin-core/build.sh
projects/bitcoin-core/project.yaml

[bitcoin-core] Support AFL builds

---

projects/libpg_query/Dockerfile
projects/libpg_query/build.sh
projects/libpg_query/fuzz_parser.c
projects/libpg_query/project.yaml

This PR adds https://github.com/pganalyze/libpg_query
Products and clients of libpg_query:
- https://pganalyze.com/
- https://github.com/ankane/pghero
- https://github.com/ankane/dexter
- https://github.com/pganalyze/pg_query
- https://github.com/pganalyze/pg_query_go
- More listed here: https://github.com/pganalyze/libpg_query#resources
--------------------------------------------------------------------------------------------------------
@lfittl would you be interested in getting libpg_query into OSS-Fuzz? I did an initial integration and if you are interested, the only thing we will need from you is an email(s) that will receive bug reports from OSS-Fuzz which will be listed in the project.yaml (see the files added in this commit). I would be happy to integrate the fuzzers into the …

libpg_query: initial integration.

---

projects/libecc/build.sh

ECGDSA is a signature scheme supported by libecc, and this PR enables testing/fuzzing it.

[libecc] Enable ECGDSA

---

infra/base-images/base-builder/compile
infra/base-images/base-runner/Dockerfile
infra/base-images/base-runner/coverage
infra/base-images/base-runner/jacoco_report_converter.py
infra/helper.py

Coverage is collected by running the fuzz targets with the JaCoCo agent
in Jazzer's no instrumentation mode.
Since JaCoCo does not support llvm-cov style coverage reports, a simple
Python helper creates it using the information contained in the JaCoCo
XML report.
As the Java build process does not maintain a mapping between source
files and build artifacts and JaCoCo needs to be passed the root folder
of the package tree, we use the Maven directory layout convention to
heuristically detect these roots.

Add Java coverage support

---

projects/wavpack/Dockerfile

A recent update to the `autotools` build configuration for WavPack requires that the `gettext` package be installed (for the `AM_ICONV` macro). This PR addresses that and fixes the build (locally, at least) for [issue #34149](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=34149)
Thanks!

[wavpack] fix issue #34149 (new configure script requires gettext)

---

projects/grpc-swift/Dockerfile
projects/grpc-swift/Package.swift
projects/grpc-swift/build.sh
projects/grpc-swift/fuzz_pipeline_configurator.swift
projects/grpc-swift/llvmsymbol.diff
projects/grpc-swift/patch.diff
projects/grpc-swift/project.yaml

@timburks would you be interested in continuous fuzzing for grpc-swift ?
This would be the 3rd swift project on oss-fuzz
I built a fuzz target with `GRPCServerPipelineConfigurator` as is done in unit tests
So I need a small patch to make this structure public...
I tried with a TCP server, but that was like 100 times slower...
I guess a long term solution would be to have fuzz integration in swift like there is unit tests integration...
With the HTTP2 magic sequence as corpus, it finds a `Fatal error: Unexpectedly found nil while unwrapping an Optional value` in `NIOHTTP2`

Adds grpc-swift project

---

projects/njs/project.yaml

Current addresses are no longer linked to Google account.

NJS: contact email addresses changed.

---

docs/getting-started/new-project-guide/jvm_lang.md
docs/getting-started/new-project-guide/python_lang.md
projects/apache-commons/build.sh
projects/bleach/build.sh
projects/bs4/build.sh
projects/fastjson2/build.sh
projects/httplib2/build.sh
projects/imageio/build.sh
projects/jackson-core/build.sh
projects/jackson-dataformat-xml/build.sh
projects/jackson-dataformats-binary/build.sh
projects/java-example/build.sh
projects/json-sanitizer/build.sh
projects/jsonschema/build.sh
projects/pygments/build.sh
projects/python-lz4/build.sh
projects/pyyaml/build.sh
projects/scapy/build.sh
projects/tensorflow-py/build.sh
projects/ujson/build.sh
projects/urllib3/build.sh

@jonathanmetzman In response to https://github.com/google/oss-fuzz/pull/5747#discussion_r630615419.
Making fuzz targets only user executable as the root user makes them non-executable outside the container, e.g. in the oss-fuzz/build/ dir.

[all] Make fuzz targets world executable

---

infra/base-images/base-runner/Dockerfile

Builds of base-runner fail as the Chromium coverage helper script has a
transitive dependency on MarkupSafe, which as of version 2.0 requires
additional python packaging tools to be installed.
This commit installs python3-setuptools and wheels, which fixes the
build.

[infra] Fix base-runner build

---

projects/protoreflect/Dockerfile
projects/protoreflect/build.sh
projects/protoreflect/fuzz_dynamic.go
projects/protoreflect/fuzz_protoparse.go
projects/protoreflect/project.yaml

@jhump would you be interested in continuous fuzzing for protoreflect ?
This enables it with one simple target about protoparse inspired by the one from @johanbrandhorst

Adds golang protoreflect project

---

projects/caddy/Dockerfile
projects/caddy/build.sh
projects/caddy/project.yaml

This PR adds Caddy. I've tested the setup locally using the guide described in the [Setting up new project#Testing Locally](https://google.github.io/oss-fuzz/getting-started/new-project-guide/#testing-locally) page.
The coverage sanitizer doesn't seem to work nicely with Go's SIV, so we opted to not support it for now. The fix will either have to be in the shell script used for the coverage sanitizer or we figure out a hack in our `build.sh`.

caddy: add new project

---

projects/cfengine/Dockerfile
projects/cfengine/build.sh
projects/cfengine/project.yaml
projects/cfengine/string_fuzzer.c

This PR adds initial integration of [cfengine](https://github.com/cfengine/core).
Users include ([source](https://cfengine.com/)):
- Deutsche Telekom
- Panasonic
- Samsung
- Linkedin
- Pfizer
- DHL
----------------------------------------------------
@olehermanse @vpodzime 
I have been working on integrating cfengine into OSS-fuzz to take the first step with continuous fuzzing and have set up this PR with the build files and a simple fuzzer implemented by way of LibFuzzer.
OSS-fuzz is a free service offered by Google to run the fuzzers of critical open source projects free of charge. If bugs are found, maintainers on the mailing list get notified with a link to a detailed bug report. The service is offered with an implied expectation that bugs are found.
To finish the integration at least …

[cfengine] Initial integration

---

projects/duckdb/Dockerfile
projects/duckdb/build.sh
projects/duckdb/parse_fuzz_test.cpp
projects/duckdb/project.yaml

DuckDB is a an in-process SQL OLAP database management system (https://duckdb.org/) and is used in production by several projects (discussed here https://github.com/duckdb/duckdb/pull/1127).  Another list of projects that use DuckDB is shown here https://duckdb.org/docs/why_duckdb  and is developed by researchers from https://www.cwi.nl/ 
@hannesmuehleisen would you be interested in getting DuckDB into OSS-Fuzz? I can see you already spoke to Adam here https://github.com/duckdb/duckdb/pull/1127 so we completed the integration. If you are interested, the only thing we will need from you is an email(s) that will receive bug reports from OSS-Fuzz which will be listed in the `project.yaml` (see the files added in this commit).

Duckdb: initial integration

---

projects/zeek/build.sh
projects/zeek/project.yaml

This PR adds the `--enable-mobile-ipv6` option to the build for the Zeek project, since we were lacking coverage for that code.

zeek: add extra configure option

---

infra/base-images/base-runner/Dockerfile

Make sure to install MarkupSafe==0.23 instead of >=0.23 which breaks.
Probably the solution is to upgrade Jinja upstream.
Fixes https://github.com/google/oss-fuzz/issues/5763

Fix coverage script issues

---

projects/muduo/Dockerfile
projects/muduo/build.sh
projects/muduo/muduo_http_fuzzer.cpp
projects/muduo/project.yaml

Initial integration of [muduo](https://github.com/chenshuo/muduo).
About Muduo usage:
- Muduo is deployed in production to serve hundreds of millions of daily connections (https://github.com/chenshuo/muduo/pull/199#issue-71736961)
- Is considered a competitor to evpp - a project that is used to handle 1000+ billions networking communications every day in production (https://github.com/Qihoo360/evpp#benchmark)
------------------------------------------------------------
@chenshuo Are you interested in fuzzing muduo?
This PR adds sets up continuous fuzzing through OSS-fuzz. To complete the PR a maintainers email address is needed for bug reports.

[muduo] Initial integration

---

projects/znc/Dockerfile
projects/znc/build.sh
projects/znc/msg_parse_fuzzer.cpp
projects/znc/project.yaml

Initial integration of ZNC [Github](https://github.com/znc/znc) [homepage](https://wiki.znc.in/ZNC)
ZNC is an IRC network bouncer and according to Wikipedia https://en.wikipedia.org/wiki/ZNC has been in development since July 2004. It's users include popularity of iPhone users (also from Wiki) and the project is available in package managers by several common Linux distros https://wiki.znc.in/Installation and also for Mac by way of Homebrew.
It has integrations with various IRC clients, e.g. [[1](https://blog.weechat.org/post/2012/11/27/Tags-in-IRC-messages)][[2](https://hexchat.github.io/news/2.9.6.html)][[3](https://web.archive.org/web/20150127002353/http://www.mirc.com/whatsnew.txt)]

[znc] Initial integration

---

infra/base-images/base-runner/targets_list

`targets_list` should not detect `jazzer_driver` and `jazzer_driver_asan` as fuzz targets, but should consider shell scripts that contain `LLVMFuzzerTestOneInput`.
@inferno-chromium This should fix https://github.com/google/oss-fuzz/pull/5770#issuecomment-841851786.

[infra] Make `targets_list` detect JVM/Python targets

---

infra/base-images/base-builder/compile

using rustc commit-hash version
cf #5767

Rust coverage: copy stdlib to the referenced directory

---

projects/systemd/Dockerfile

For https://github.com/systemd/systemd/pull/19630:
m4 is being replaced by jinja2. Let's pull in both until the dust settles.

[systemd]: pull in jinja2

---

infra/base-images/base-runner/coverage

Creates the missing per-target `summary.json` for JVM targets.
@inferno-chromium This addresses the first point of https://github.com/google/oss-fuzz/pull/5770#issuecomment-842027559.
The logs at https://console.cloud.google.com/cloud-build/builds;region=global/92fbac4f-c6c7-474f-a3d8-e9f101d213cf;step=9;tab=detail?src=ac&project=oss-fuzz show that the missing files in `fuzzer_stats` are causing the build failure, so hopefully this PR will fix that.

[infra][jvm] Create per-target summary.json

---

projects/protoreflect/project.yaml

I get the email notices, but I cannot login to view details. This Google account (josh@bluegosling.com) is just one of several emails linked, and the main identity of the account is my gmail account. So when I login as this address (the bluegosling.com one), I get an error: 
> You (email=jhumphries131@gmail.com) are not authorized to access this page!
So I think this patch should fix that for me.

protoreflect contact: change to gmail account

---

projects/espeak-ng/project.yaml

Apparently, aliases to Google accounts do not work, even when they
are registered with Google and can be used to log in on Google sites.

Use Google accounts for espeak-ng email

---

projects/h2o/project.yaml

Hello,
Hajime is working on expanding our fuzzers for h2o. It would be helpful for him to have access to our [oss-fuzz dashboard](oss-fuzz.com) so that he can view coverage metrics, access seed files, and so on. Could you please add him?
cc @kazuho, @hfujita
Thanks,
Jon

[h2o] add Hajime Fujita

---

projects/espeak-ng/project.yaml

Confirmed via https://bugs.chromium.org/u/valdis.vitolins@gmail.com/ that this is not an alias.
/cc @valdisvi

Update another e-mail address for espeak-ng

---

infra/base-images/base-builder/compile

cc @rbehjati
Should fix #5767 
Tested with 
```
rm -Rf build/out/suricata
python3 infra/helper.py build_image --no-pull base-builder
python3 infra/helper.py build_fuzzers --sanitizer=coverage suricata
python3 infra/helper.py coverage --fuzz-target fuzz_applayerparserparse --corpus-dir path/to/somedir/ suricata
```

Right copy for rust std lib for coverage

---

infra/build_specified_commit.py
infra/helper.py

Exposing the mount location for local sources to a command-line
argument makes it possible to reproduce findings with local source
even for umbrella projects with WORKDIR $SRC/.

[infra] Make mount location configurable in build_fuzzers

---

projects/systemd/Dockerfile

It turns out that the system version of jinja2 is visible to the build
script.
From https://github.com/systemd/systemd/pull/19630#issuecomment-842983177:
> On OSS-Fuzz (and CIFuzz) the latest version of Python is built from
> scratch in the base-builder image. /usr/lib/python3/dist-packages
> (where python3-jinja2 is installed by apt-get) isn't included in
> PYTHONPATH there:
>
> ['', '/usr/local/lib/python38.zip', '/usr/local/lib/python3.8', '/usr/local/lib/python3.8/lib-dynload', '/usr/local/lib/python3.8/site-packages']

[systemd] use pip3 to install jinja2

---

projects/znc/project.yaml

Solves https://github.com/google/oss-fuzz/issues/5792
Add second email address for @DarthGandalf to access bug reports.

[znc] Add maintainers email address

---

projects/cel-go/fuzz_eval.go

Should fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=34444

cel-go: remove irrelevant panic/assert in target

---

projects/libpsl/Dockerfile
projects/libpsl/build.sh

This should fix building libpsl by amending the libidn dependency build.
Some smaller cleanups are also included.

[libpsl] Fix build

---

projects/gnupg/Dockerfile
projects/gnupg/fuzzgnupg.diff

According to https://oss-fuzz-build-logs.storage.googleapis.com/index.html#gnupg the build is failing for the last 4 months.
For example https://oss-fuzz-build-logs.storage.googleapis.com/log-57c64478-ca6d-42f7-b498-f153dad5fe1a.txt ends with:
```
Step #4: + cd gnupg
Step #4: + mkdir tests/fuzz
Step #4: + cp ../fuzz_decrypt.c ../fuzz_decrypt.options ../fuzz_import.c ../fuzz_list.c ../fuzz_list.options ../fuzz_verify.c tests/fuzz
Step #4: + git apply ../fuzz.diff
Step #4: error: patch failed: configure.ac:991
Step #4: error: configure.ac: patch does not apply
Step #4: error: patch failed: g10/Makefile.am:164
Step #4: error: g10/Makefile.am: patch does not apply
Step #4: error: patch failed: tests/Makefile.am:18
Step #4: error: tests/Makefile.am: patch does not apply
Step #4: …
```

gnupg: Try to fix build issues

---

projects/clamav/build.sh

I updated ClamAV's Mussels recipe for libxml2 to the new 2.9.12 release
and to use CMake instead of the old build system. It seems the new CMake
build system installs the headers under <prefix>/include/libxml2 though.
This commit accounts for the header path change.

[clamav] Fix build after libxml2 cmake change

---

projects/containerd/Dockerfile
projects/containerd/build.sh
projects/containerd/project.yaml

This PR adds initial integration of Containerd, an industry-standard container runtime.
Selected adopters include:
1. [Google Kubernetes Engine](https://cloud.google.com/kubernetes-engine/)
2. [IBM Cloud Kubernetes Service](https://www.ibm.com/cloud/kubernetes-service)
3. [Firecracker](https://github.com/firecracker-microvm/firecracker)
4. [Katacontainers](https://katacontainers.io/)
5. [Cloudfoundry](https://www.cloudfoundry.org/)
6. Docker
Containerd graduated CNCF in 2019.
2 fuzzers have been merged upstream here: https://github.com/containerd/containerd/pull/4841
__________________________________________________________________________________
@kzys @mxpv @cpuguy83 @estesp @AkihiroSuda
The files in this PR allows Containerd's fuzzers to be run continuously. All that is needed on this …

[containerd] Initial integration

---

projects/tailscale/Dockerfile
projects/tailscale/build.sh
projects/tailscale/project.yaml

This PR adds initial integration of [Tailscale](https://tailscale.com/).
**About Tailscale**: _Based on Google’s zero-trust BeyondCorp architecture, and built using the WireGuard protocol, Tailscale makes network security accessible to teams of any size_[[1](https://www.heavybit.com/library/blog/heavybit-welcomes-tailscale/)]. The company has around 20 employees and raised $12m in november 2020[[2](https://techcrunch.com/2020/11/10/tailscale-raises-12-million-for-its-wireguard-based-corporate-vpn)].
**Users**: One of Tailscales larger customers is VersaBank[[3](https://www.businesswire.com/news/home/20200330005192/en/VersaBank%E2%80%99s-New-High-Security-VPN-Proving-Especially-Valuable-During-COVID-19-Pandemic)] who trades on Toronto Stock Exchange.

[tailscale] Initial integration

---

projects/poco/Dockerfile
projects/poco/build.sh
projects/poco/json_parse_fuzzer.cc
projects/poco/project.yaml

This PR adds initial integration of [Poco](https://github.com/pocoproject/poco).
Users include:
- Clickhouse
- Avid
- Cisco
- Malwarebytes
- NetApp
- Oracle
- Symantec
- Sony
And more are available [here](https://pocoproject.org/about.html#users).
______________________________________________________________________________________________
We are currently working with upstream maintainers on the fuzzer here: https://github.com/pocoproject/poco/pull/3149
@obiltschnig I am tagging you to let you know of the build files in this PR. They will allow OSS-fuzz to run the json fuzzer once it has been merged in. If you have any questions, feel free to ask here or on the Poco repository. On the OSS-fuzz side, we need a maintainer email in the `project.yaml` file to complete the integration.

[poco] Initial integration

---

projects/juju/Dockerfile
projects/juju/build.sh
projects/juju/project.yaml
projects/juju/storage_fuzzer.go

Initial integration of [Juju](https://github.com/juju/juju). 
Users of Juju include [[src](https://juju.is/)]: 
- Deutsche Telekom
- IBM
- Intel
- Microsoft Azure
- Cisco
- China Telekom
- HP
- Yahoo
- Verizon
- Panasonic
- BT
- Rabobank
- Tele2
____________________________________________________________
@SimonRichardson @achilleasa @wallyworld @ycliuhw
I have been working on setting up continuous fuzzing for Juju and have set up this draft integration application with build files and a fuzzer to get things started.
Integrating with OSS-fuzz is free but is offered with an implied expectation that found bugs are fixed. Once Juju is integrated OSS-fuzz will run all Jujus fuzzers continuously and report bugs to maintainers on the mailing list. 
To finish the integration at least on email …

[juju] Initial integration

---

infra/base-images/base-runner/test_all.py
infra/base-images/base-runner/test_all_test.py

For proper support of Bazel's runfiles tree, a shell script wrapper is
also needed for C++ targets, see
https://github.com/bazelbuild/rules_fuzzing/pull/149.
This commit allows shell script fuzz targets for all languages. This
also helps to consolidate the various fuzz target checks in OSS-Fuzz
by removing a dependence on fuzzing_language.

[infra] Allow shell script targets for all languages

---

projects/fribidi/Dockerfile
projects/fribidi/build.sh
projects/fribidi/project.yaml

fribidi, the free bidi implementation used directly in Pango and https://github.com/fribidi/fribidi/blob/master/USERS and indirectly in many other places. The configuration is based on HarfBuzz's one. The try to add a fuzzer to the project itself has been fruitful as can be seen on https://github.com/fribidi/fribidi/pull/154 yet this hopefully can result in even more interesting cases.

[fribidi] Add fribidi-fuzzer

---

infra/base-images/base-builder/compile_go_fuzzer

The previous code assumes the repo URL is always the same as the path and consists of 3 segments separated by forward slash, which is not true in Go modules with modules whose version is above v1, e.g. `github.com/caddyserver/caddy/v2`.

[infra] fix handling Go's SIV in coverage santizer

---

projects/civetweb/project.yaml

DFSAN builds are failing, causing ClusterFuzz exceptions.
DFSAN isn't really supported right now anyway.

[civetweb] Disable DFSAN builds.

---

infra/base-images/base-sanitizer-libs-builder/patch_build.py

to prevent it from failing to start up with
```
NEW_FUNC[1/1]: llvm-symbolizer: symbol lookup error: /tmp/not-out/instrumented_libraries/lib/x86_64-linux-gnu/libz.so.1: undefined symbol: __msan_va_arg_overflow_size_tls
==45==WARNING: external symbolizer didn't start up correctly!
```
Closes https://github.com/google/oss-fuzz/issues/5349

infra: stop patching llvm-symbolizer

---

projects/libecc/build.sh

ECRDSA is a signature scheme supported by libecc, and this PR enables testing/fuzzing it.

[libecc] Enable ECRDSA

---

projects/caddy/build.sh

Now that building of Go's coverage sanitizer is fixed, we can enable fuzzing with the coverage sanitizer for Caddy.
Depends on #5813

[caddy] enable coverage builds

---

infra/cifuzz/fuzz_target.py
infra/cifuzz/run_fuzzers_test.py

Return the path to the corpus in FuzzResult.
Also, refactor is_reportable: move code testing crash novelty
into its own method.

[CIFuzz][fuzz_target] Prepare for ClusterFuzzLite

---

projects/libvips/Dockerfile
projects/libvips/build.sh

This PR removes a libjxl patch in libvips' fuzzer that was merged upstream with commit https://github.com/libjxl/libjxl/commit/0f6ddd4727f2c51bb2396872599d4f86f19bf064. 
It also adapts the Dockerfile to reflect the new development location of libjxl: https://github.com/libjxl/libjxl.

libvips: remove libjxl patch merged upstream

---

projects/oak/Dockerfile
projects/oak/build.sh

Recent changes in Oak require `libssl-dev` and `pkg-config` to be installed.

Install libssl-dev for Oak

---

projects/bls-signatures/build.sh
projects/cryptofuzz/build.sh
projects/libecc/build.sh
projects/libressl/build.sh
projects/relic/build.sh

No longer needed for recent versions of boost

remove unused boost workaround

---

projects/bitcoin-core/Dockerfile
projects/bitcoin-core/build.sh

I suspect that the OSS-Fuzz HDD are too slow to read/write large amounts of data (fuzz binaries and inputs), leading to the error 
```
Step #13: + sem --wait
TIMEOUT
ERROR: context deadline exceeded
```
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=34157#c5
I have no idea if the given patch fixes the issue, because I can't reproduce locally.

Revert "bitcoin-core: Run zip in parallel"

---

infra/base-images/base-runner/coverage

Specify `--additional_jvm_args` instead of `--jvm_args` so that custom target JVM args (e.g. `--enable-preview`) are preserved in coverage runs.
Fixes the coverage build for `kryo`.
@inferno-chromium This requires an update of base-builder (it needs latest Jazzer) or all coverage builds will fail.

[infra][jvm] Don't override jvm_args in coverage builds

---

projects/blackfriday/Dockerfile
projects/blackfriday/build.sh
projects/blackfriday/project.yaml
projects/blackfriday/render_fuzzer.go

I saw a PR from google autofuzz looking to get blackfriday integrated (Fixes https://github.com/google/oss-fuzz/pull/4970), but they had some troubles getting the Go fuzzing to work. This PR fixes it.

[blackfriday] Initial integration

---

projects/lldb-eval/Dockerfile
projects/lldb-eval/build.sh
projects/lldb-eval/project.yaml

lldb-eval (https://github.com/google/lldb-eval) is an LLDB-based library for evaluating expressions in debug context. It is used in Visual Studio extension for Stadia (https://github.com/googlestadia/vsi-lldb).

[lldb-eval] Initial integration

---

projects/ffmpeg/Dockerfile
projects/ffmpeg/build.sh

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=34211
Fixes build (which apparently failed due to incompatibility of unneeded distro
packages being mixed with unneeded git packages)

[FFmpeg] remove libXfixes

---

projects/eigen/solver_fuzzer.cc

It's unnecessary, and internal headers are subject to change without notice.

Remove reference to Eigen internal header.

---

infra/base-images/base-builder/compile

It should make it easier to see where all the rustc flags
come from. RUSTFLAGS along with `cargo fuzz build --verbose` should
help to track down weird issues like https://github.com/google/oss-fuzz/pull/5865#issuecomment-852685588
It's a follow-up to ecf3d384fb0b62069

infra: show RUSTFLAGS as well

---

projects/libjxl/Dockerfile
projects/libjxl/build.sh
projects/libjxl/project.yaml

libjxl is the reference implementation encoder and decoder for JPEG XL.
This patch adds the main decoder fuzzer (djxl_fuzzer) and a few other
fuzzers for internal parts of the decoder.
There's no encoder fuzzer support.

libjxl: New JPEG XL library project.

---

docs/getting-started/new-project-guide/rust_lang.md

@evverx following our short talk here https://github.com/rust-fuzz/cargo-fuzz/issues/256#issuecomment-855197457 I updated the rust documentation with details on how to integrate fuzzing logic in a test-style approach and also how to combine the two.

Docs: update rust documentation

---

projects/s2geometry/Dockerfile
projects/s2geometry/build.sh
projects/s2geometry/project.yaml
projects/s2geometry/s2_fuzzer.cc

Initial integration of S2geometry - "_the core geometric library on which Google's global geographic database is built_ "[[src](https://opensource.googleblog.com/2017/12/announcing-s2-library-geometry-on-sphere.html)].
It is used by [[src](https://blog.christianperone.com/2015/08/googles-s2-geometry-on-the-sphere-cells-and-hilbert-curve/?a=2)]:
1. Google Maps
2. MongoDB
3. Foursquare
___________________________________________________________________________________________________
@jmr Are you interested in integrating s2geometry into OSS-fuzz and get notified if any bugs are found?
To complete the integration we need a maintainers email address for bug reports.

[s2geometry] Initial integration

---

infra/base-images/base-builder/compile_go_fuzzer

Should fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=34965 build failure for json-patch
The problem is for golang projects without go.mod yet, if we are in their directory, we fail to find a directory in /root/go/pkg/ for them...

go: compiles projects without go.mod from their directory

---

projects/freeradius/Dockerfile
projects/freeradius/build.sh
projects/freeradius/patch.diff
projects/freeradius/project.yaml

@arr2036 would you be interested in continuous fuzzing for freeradius ?
This PR enables it with the fuzz targets already there.
As oss-fuzz does not allow to define environment variables before running the fuzzers, a small patch was needed to find the right directories...

Adds project freeradius

---

projects/lldb-eval/build.sh

Remove `--show-progress` option for `wget` invocations. In OSS-Fuzz logs every progress update is logged as a separate line, so the build log is looooooooong.

Make wget invocations less verbose

---

projects/gonids/Dockerfile
projects/gonids/build.sh

So that CIFuzz works
As it looks for the main repo in $SRC
cf https://github.com/google/gonids/issues/157
cc @duanehoward

Uses git clone instead of go get for gonids

---

projects/image-rs/Dockerfile
projects/image-rs/build.sh
projects/image-rs/project.yaml

cc @HeroicKatora @fintelia
In addition to image-png, would you be interested in fuzzing the whole image crate ?
This PR enables it with the libfuzzer/cargo fuzz fuzz targets
The AFL targets could be integrated. To do this, the best way I see is to make them generic as in #5798 
cc @DavidKorczynski as you did image-png integration

Adds rust image-rs project

---

projects/libvips/project.yaml

This email address is generating bounce spam.
/cc @omira-sch

[libvips] Remove no longer valid CC email address

---

projects/poppler/Dockerfile
projects/poppler/build.sh

released pango wants to download harfbuzz from a branch name that no longer exists, so use git pango
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=35010

poppler: Fix build

---

docs/getting-started/new-project-guide/jvm_lang.md
infra/base-images/base-builder/Dockerfile
infra/base-images/base-builder/compile
infra/base-images/base-runner/coverage
projects/java-example/ExampleFuzzerNative.cpp
projects/java-example/build.sh
projects/java-example/project.yaml

Jazzer support for UBSan has been added in https://github.com/CodeIntelligenceTesting/jazzer/commit/224e8d00c26d19a78de1720459e3c5b403ae36ca.
The second commit temporarily reenables the `java-example` project to confirm that UBSan findings are properly reported.

[infra][jvm] Add Jazzer UBSan support

---

projects/libjxl/build.sh

fuzzer_corpus generators emits two lines per test case generated and the
following zip command emits another line for each generated test case.
This patch makes both commands quiet which facilitates spotting error
messages.

libjxl: make the fuzzer corpus generation step quiet

---

projects/powerdns/build.sh

New fuzzing targets and their corpus directories are not always added to old branches, since the new features are usually not backported.
We still would like to be able to keep CI-fuzz enabled on these branches, so we need to properly handle missing directories.

powerdns: Better handling of missing corpus directories

---

projects/openvpn/Dockerfile
projects/openvpn/build.sh
projects/openvpn/fuzz_base64.cpp
projects/openvpn/fuzz_buffer.cpp
projects/openvpn/fuzz_dhcp.cpp
projects/openvpn/fuzz_misc.cpp
projects/openvpn/fuzz_proxy.cpp
projects/openvpn/project.yaml

@schwabe I have been doing some initial work on integrating OpenVPN into OSS-Fuzz to run fuzzers continuously on OpenVPN. I would be very happy to continue working on this and improving the integration as there are a lot more that can be done. If you are happy to integrate could you provide me with an email(s) that will receive bug reports? The email should be affiliated with a Google account.
The specific integration here is a first-step adoption of the work by @guidovranken described [here](https://guidovranken.com/2017/06/26/openvpn-fuzzers-released-notes/) - @guidovranken are you okay with me migrating your fuzzers?
@schwabe Let me know what you think as I would be very happy to get proper fuzzing integrated in OpenVPN.

openvpn: initial integration

---

projects/qemu/Dockerfile
projects/qemu/build.sh

QEMU builds are failing [1]:
"Step #4: ERROR: glib-2.56 gthread-2.0 is required to compile QEMU"
The version of glib shipped with Ubuntu 18.04 is too old. While we wait
on [2], take some inspiration from poppler [3], and build glib ourselves.
[1] https://oss-fuzz-build-logs.storage.googleapis.com/log-2a22b4e2-d7b7-4695-a4dd-25d8d8407704.txt
[2] https://github.com/google/oss-fuzz/issues/5697
[3] https://github.com/google/oss-fuzz/blob/a44547d8d6f78ad7ce02323ecc33382a1d628e39/projects/poppler/build.sh#L70

qemu: manually build glib

---

projects/rustls/build.sh

In coverage builds, disable fuzzers that wont work with coverage. A more comprehensive fix will come later.

Rustls: fix coverage

---

projects/gnutls/Dockerfile

A recent update to libtasn (https://gitlab.com/gnutls/libtasn1/-/commit/a72a8d1ef13436bf8916097f11c3fc90f07ba911 I think) caused some problems identifying versions of libtasn in the gnutls set up. This should fix it.

gnutls: Fix dockerfile and libtasn clone to work with new versioning.

---

infra/cifuzz/run_fuzzers_test.py

This is consistent with build_fuzzers_test and requires less repetition.

[CIFuzz][NFC] Put integration test decorator on class instead of test methods

---

infra/cifuzz/docker.py
infra/cifuzz/fuzz_target.py
infra/cifuzz/fuzz_target_test.py

1. Use CORPUS_DIR env var so that corpus after fuzzing can be saved.
2. Improve error messages and refactor is_crash_novel.

[CIFuzz] Improve fuzz_target.py

---

infra/base-images/base-builder/compile

Previously, JVM coverage builds for projects with native dependencies would fail: https://oss-fuzz-build-logs.storage.googleapis.com/log-9b66fe39-7e33-4058-812a-c9c52f32e0ea.txt

[infra][jvm] Provide jazzer_driver_with_sanitizer for coverage builds

---

.github/workflows/infra_tests.yml
.github/workflows/presubmit.yml
.github/workflows/project_tests.yml
infra/ci/build.py
infra/presubmit.py

`FETCH_HEAD` will actually refer to `origin/master` (aka `origin/HEAD`), and not the current pull request.

ci: Fix get_changed_files_output

---

projects/pillow/Dockerfile

Pillow recently started [building zlib on Linux in it's wheels](https://github.com/python-pillow/pillow-wheels/pull/204), and that is conflicting with the [installation of zlib1g-dev from our oss-fuzz Dockerfile.](https://github.com/google/oss-fuzz/blob/8d0531dca85230fa90518094d0d05f8c7e339469/projects/pillow/Dockerfile#L25)
> [./.libs/libpng16.so: undefined reference to `inflateValidate'](https://github.com/python-pillow/Pillow/runs/2870070374#step:4:2502)
[Copying files from here as a test](https://github.com/radarhere/docker-images/commit/d779c506965d0022f4cf29caa1108308efe017a6), it [fails with the same error](https://github.com/radarhere/docker-images/runs/2871736946?check_suite_focus=true#step:5:2528), and then [with this PR](https://github.com/radarhere/docker-images/commit/96822058 …

[Pillow] Removed zlib1g-dev installation

---

projects/bitcoin-core/build_cryptofuzz.sh

Also enable the Bitcoin crypto module (e.g. the harness in https://github.com/guidovranken/cryptofuzz/tree/master/modules/bitcoin) which I had unfortunately forgotten to enable last time.
CC @MarcoFalke

[bitcoin-core] Enable libsecp256k1 Schnorr signature fuzzing

---

.github/workflows/infra_tests.yml

GoogleCloudPlatform/github-actions/setup-gcloud is deprecated.
See warning here: https://github.com/google/oss-fuzz/actions/runs/957528283

[CI] Switch to google-github-actions/setup-gcloud

---

projects/kcodecs/Dockerfile
projects/kcodecs/build.sh

New kcodecs requires C++17, we need a newer gperf able of generating C++17
compliant code

Fix kcodecs build

---

projects/java-example/build.sh

Top-level executables are taken to be fuzz targets by the coverage script.

[java-example] Build native library in subdirectory

---

projects/cryptofuzz/Dockerfile
projects/cryptofuzz/build.sh

- Add the libraries noble-secp256k1, noble-ed25519, noble-bls12-381 (see also: https://github.com/google/oss-fuzz/issues/5945)
- Add blst for comparing noble-bls12-381 against
- Add libsecp256k1 for comparing the Schnorr component of noble-secp256k1 against
- Install nodejs/npm for building noble-bls12-381 in a way that's usable by the fuzzer
- Remove nettle because it has been having its own project for a while: https://github.com/google/oss-fuzz/tree/master/projects/nettle
The author of Noble does not have a Google account and has chosen to let me forward relevant bug reports to him, hence no modifications to the project.yaml CC list have been made.

[cryptofuzz] Add Noble libraries

---

projects/dav1d/project.yaml

Monorail seems to to detect that the email address bounces and deletes
the CC but something re-adds it regularly.

dav1d: remove dead email from vendor_ccs

---

infra/build/functions/update_build_status.py

Needed for https://github.com/google/oss-fuzz/issues/5968

Decrease number of build logs to avoid rate limits.

---

projects/libvips/build.sh

Required as a result of https://github.com/mm2/Little-CMS/commit/5ef8c971244fe4e8e376afdcfad67899a73a9285
Hopefully fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=35586

[libvips] Ensure lcms dependency generates its autotools files

---

infra/base-images/base-builder/Dockerfile
infra/base-images/base-builder/bazel_build_fuzz_tests
projects/bazel-rules-fuzzing-test-java/Dockerfile
projects/bazel-rules-fuzzing-test-java/build.sh
projects/bazel-rules-fuzzing-test-java/project.yaml

@stefanbucur There probably won't be many multi-language Bazel projects on OSS-Fuzz other than `rules_fuzzing` itself, but I believe that something along these lines is the correct way to make CI Fuzz possible for `rules_fuzzing`. Could you take a look?

[infra] Add support for rules_fuzzing's java_fuzz_test macro

---

projects/tendermint/Dockerfile
projects/tendermint/build.sh
projects/tendermint/project.yaml

The tendermint is the consensus algorithm used by cosmos-sdk (which was added in https://github.com/google/oss-fuzz/pull/5631).

projects: add tendermint project

---

projects/openvpn/build.sh
projects/openvpn/fuzz_header.h
projects/openvpn/fuzz_list.c
projects/openvpn/fuzz_mroute.c
projects/openvpn/fuzz_packet_id.c

This PR revolves around openvpn and has:
- Three new fuzzers
- Improvements to proxy fuzzer for hook fopen and fclose
- Changes to fuzz_header to ensure fgets returns an ascii printable char.

openvpn: three new fuzzers and improved proxy fuzzer

---

infra/build/functions/update_build_status.py

In this commit https://github.com/google/oss-fuzz/commit/0370821e3944a938775f45b3631a7aecf68ed138 the use of the `time` import was removed. This causes the CI to complain about `infra/build/functions/update_build_status.py:21:0: W0611: Unused import time (unused-import)` in this PR https://github.com/google/oss-fuzz/pull/5980 and the presubmit checks here https://github.com/google/oss-fuzz/pull/5980/checks?check_run_id=2941631092

infra: Remove unused import from update_build_status

---

projects/h2o/build.sh
projects/h2o/h2o-fuzzer-http3.options

Now that h2o merged a new fuzzer for http3 (https://github.com/h2o/h2o/pull/2696)
this commit adds options for running http3 fuzzer.

[h2o] Add options for http3 fuzzer

---

projects/istio/build.sh

The build script has been moved to [tests/fuzz/oss_fuzz_build.sh](https://github.com/istio/istio/blob/master/tests/fuzz/oss_fuzz_build.sh) upstream.

istio: Move build script upstream

---

infra/build/functions/build_project.py
infra/build/functions/expected_build_steps.json
infra/build/functions/request_build_test.py

Previously, a project's fuzz targets were usually built in the order:
libfuzzer, afl, honggfuzz. This can bias results if one is looking
at which engine finds bugs first.

[build/infra] Build engines in alphabetical order.

---

projects/libigl/Dockerfile
projects/libigl/build.sh
projects/libigl/igl_fuzzer.cpp
projects/libigl/project.yaml

Initial integration of [libigl](https://github.com/libigl/libigl).
Companies that use libigl include: 
- Adobe
- Electronic Arts, Inc
- Epic Games
- Microsoft Research
- Ubisoft
An list of selected users can be found here: https://libigl.github.io/#projectsuniversities-using-libigl
______________________________________________________________
@jdumas Are you interested in integrating Libigl into OSS-fuzz?
All we need is an email address for bug reports to complete this PR.
If this gets merged, then https://github.com/libigl/libigl/pull/1802 can be closed.

[libigl] Initial integration

---

projects/bitcoin-core/build_cryptofuzz.sh

CC @sipa @MarcoFalke @real-or-random @practicalswift
Updates to the Cryptofuzz libsecp256k1 module and corresponding build script updates.
- scalar math operations. Results are automatically compared against Botan and Bitcoin Core's arith_uint256.cpp. https://github.com/guidovranken/cryptofuzz/blob/fcfca5774d3519ef15fdbd0346dc9736ff1e6262/modules/secp256k1/module.cpp#L1117-L1218
- point addition. alternate between secp256k1_gej_add_ge and secp256k1_gej_add_ge_var. Results are compared against Botan. https://github.com/guidovranken/cryptofuzz/blob/fcfca5774d3519ef15fdbd0346dc9736ff1e6262/modules/secp256k1/module.cpp#L1001-L1005
- enable point multiplication. Not yet implemented but enabling this now saves a PR later
- assert that all `int`-returning functions that signal success or failure …

[bitcoin-core] Updates to libsecp256k1 Cryptofuzz build

---

infra/base-images/base-runner/coverage

Currently standard file descriptors are closed in coverage builds. This was added here https://github.com/google/oss-fuzz/commit/72b82ee08ffd39e284a7271bb556ba0e5b7b3e39 with the goal of speeding up noisy fuzz targets. However, the consequence is that the runtime environment is a bit different from when the fuzzers run which can make the coverage reports be different than what is actually exercised by the coverage. 
An example is OpenVPN where the following line https://github.com/OpenVPN/openvpn/blob/ccee09d1478aa69783926c208bfa235dcb055124/src/openvpn/console_builtin.c#L215 checks the openness of stdin and stderr. In non-coverage builds the line fails and execution continues, but in coverage builds the line evaluates to true and the fuzzer, therefore, exits. 
The alternative to removing …

[infra] do not close file descriptors in coverage runs.

---

projects/tendermint/project.yaml

While at it, also add @tessr and @tychoish to cc list, as the primary
contact is an email group, not individual Google Account.

projects/tendermint: change tendermint email to interchain.io

---

projects/wolfssl/Dockerfile
projects/wolfssl/build.sh

Uses gsutil to retrieve the latest public corpora of other Cryptofuzz-based projects and constructs the seed corpus with it.

[wolfssl] Import corpora from other projects

---

infra/base-images/base-runner/coverage

Keeps the JVM coverage libFuzzer args in sync with the change in https://github.com/google/oss-fuzz/pull/5999.

[infra] Do not close file descriptors also for JVM

---

projects/openvpn/build.sh
projects/openvpn/fuzz_header.h

These hooks are to ensure openvpn does not exit because some file descriptors may not refer to a terminal.

openvpn: hook more functions

---

projects/stb/Dockerfile

Encountered an issue similar to https://github.com/google/oss-fuzz/pull/5315. The copying of the seed corpus is done to keep it working with the old build script, the fix upstream will be on another branch instead of `master` for a week or so.
https://github.com/nothings/stb/pull/1058

[stb] update Dockerfile for CIFuzz

---

projects/tidy-html5/project.yaml

As per https://github.com/htacg/tidy-html5/issues/788#issuecomment-877266838

Set the tidy-html5 OSS-Fuzz contact info to @balthisar

---

projects/apache-commons/project.yaml

just what the subject says: we want to hand over the primary role from myself to Matt.

Change Apache Commons primary from @bodewig to @jvz

---

projects/tor/Dockerfile

It appears that libevent now requires pkg-config, which was not
previously installed from Tor's Dockerfile.  This change adds
pkg-config.
Adding this dependency should resolve oss-fuzz issue 36048
(https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=36048)

tor: Fix libevent build by installing pkg-config

---

projects/h3/project.yaml

It doesn't seem to be possible to log in and view reports without the contact email being associated with a Google account. I'm replacing my email address with a Gmail one, and adding another H3 contributor's Gmail email address as well (he's subscribed to the list that receives reports but also could not login.)
Please let me know if my understanding of how reports are made visible to some email addresses is not correct. Thanks!
cc @dfellis @nrabinowitz @ajfriend (didn't know your Gmail addresses off hand)

Update h3 contact email

---

projects/tidy-html5/build.sh

An issue with the tidy-html5 build came up here https://github.com/google/oss-fuzz/pull/6029 
This PR fixes it.

tidy-html5: fix breaking build.

---

infra/build/functions/build_project.py
infra/build/functions/expected_build_steps.json
projects/myanmar-tools/build.sh

GCB passes HOME as env var to the docker container. It sets
HOME to /builder/home which is persisted accross builds.
This issue causes build breakages in
https://github.com/google/oss-fuzz/issues/6035
and possibly https://github.com/google/oss-fuzz/issues/5317.
Perhaps more insidiously, it can cause fuzzers to be built with
the wrong instrumentation.

[infra][build] Set HOME=/root on GCB when doing fuzzer builds.

---

projects/fluent-bit/build.sh

This simple hook is to avoid ASAN issues when fuzzing

fluent-bit: deploy hook in build

---

infra/cifuzz/actions/run_fuzzers/action.yml
infra/cifuzz/affected_fuzz_targets.py
infra/cifuzz/affected_fuzz_targets_test.py
infra/cifuzz/build_fuzzers.py
infra/cifuzz/build_fuzzers_entrypoint.py
infra/cifuzz/build_fuzzers_test.py
infra/cifuzz/clusterfuzz_deployment.py
infra/cifuzz/clusterfuzz_deployment_test.py
infra/cifuzz/config_utils.py
infra/cifuzz/continuous_integration.py
infra/cifuzz/docker.py
infra/cifuzz/fuzz_target_test.py
infra/cifuzz/generate_coverage_report_test.py
infra/cifuzz/run_fuzzers_entrypoint.py
infra/cifuzz/run_fuzzers_test.py
infra/cifuzz/test_helpers.py

For external fuzzing.
This wasn't really used for external fuzzing, except to build 
docker image tags (`gcr.io/oss-fuzz/PROJECT`). We don't really need this, so we
just use a hardcoded tag (`external-project'`) in such cases instead.
Also rename the variable from `project_name` to `oss_fuzz_project_name`, to
be more explicit, and use it to determine whether or not we're running
an OSS-Fuzz project.
For #6051.

Make oss-fuzz-project-name optional.

---

infra/cifuzz/build_fuzzers_test.py
infra/cifuzz/clusterfuzz_deployment.py
infra/cifuzz/filestore/github_actions/__init__.py
infra/cifuzz/generate_coverage_report.py
infra/cifuzz/run_fuzzers_test.py

1. Allow uploading coverage reports.
2. tar artifact directories before we upload them on github actions so subdirectories can be uploaded.
3. Delete commented out code.
Related: #6054

[CIFuzz] Support uploading coverage reports

---

infra/cifuzz/clusterfuzz_deployment.py
infra/cifuzz/clusterfuzz_deployment_test.py
infra/cifuzz/filestore/github_actions/__init__.py
infra/cifuzz/fuzz_target.py
infra/cifuzz/fuzz_target_test.py

Previously, the downloaded build was uploaded instead of the new build.
This regression was introduced when the big workspace change was made.
Also, add more logging.

Fix build uploading.

---

projects/cryptofuzz/Dockerfile
projects/cryptofuzz/build.sh

I'm working with Microsoft to resolve some issues in SymCrypt. They only update the public SymCrypt repo occasionally and I want to prevent that the other subscribers to Cryptofuzz bug reports will get notifications about these bugs for months to come. So I'm disabling SymCrypt now and will enable it again once those bugs are resolved.
Also fix libsecp256k1 build.

[cryptofuzz] Fix build, disable SymCrypt

---

projects/apache-commons/build.sh

Running the fuzzers in headless mode works around missing dependencies
for the full Java AWT libraries. It is likely that the commons-imaging
only uses features available in headless mode, in which case this would
be a complete fix for the fuzzer startup crashes observed on
ClusterFuzz.

[apache-commons] Run fuzzers in headless mode

---

projects/net-snmp/build.sh
projects/net-snmp/parse_octet_hint_fuzzer.c
projects/net-snmp/read_objid_fuzzer.c
projects/net-snmp/snmp_mib_fuzzer.c
projects/net-snmp/snmp_parse_oid_fuzzer.c

Split snmp_octet_fuzzer into one fuzzer per function to make bug reports
easier to interpret. See also commit ded876646013 ("net-snmp: add two new
fuzzers and simplify build script. (#6091)").

[net-snmp] Split and improve snmp_octet_fuzzer

---

projects/rdkit/Dockerfile

Build eigen from source because the headers of the libeigen-dev package has issues with clang.

rdkit: fix build

---

infra/cifuzz/clusterfuzz_deployment.py
infra/cifuzz/clusterfuzz_deployment_test.py
infra/cifuzz/config_utils.py
infra/cifuzz/external-actions/build_fuzzers/action.yml
infra/cifuzz/external-actions/run_fuzzers/action.yml
infra/cifuzz/filestore/__init__.py
infra/cifuzz/filestore/git/__init__.py
infra/cifuzz/filestore/git/git_test.py
infra/cifuzz/filestore/github_actions/__init__.py
infra/cifuzz/filestore/github_actions/github_actions_test.py
infra/cifuzz/filestore_utils.py

- Add storage-repo, storage-repo-branch, and
storage-repo-branch-coverage fields to the actions, to indicate that
the Git filestore should be used.
- The CI provided filestore is still used for crashes and builds.
- Replace generic Filestore.upload_directory with typed upload methods
which matches the download methods.
- Rename upload_latest_build to upload_build to make it more generic.
- Make artifact name prefixes an implementation detail of the store.
For #6052.

Add a Git backed filestore.

---

infra/base-images/base-runner/Dockerfile

While installing `libxext-dev` in `base-runner` makes it available for local fuzzing via `infra/helper.py run_fuzzer`, it is not installed in the image used by ClusterFuzz to run fuzz targets. ​Fuzz targets that rely on any JDK system dependency rather have to install it manually using the method described in https://google.github.io/oss-fuzz/further-reading/fuzzer-environment/#runtime-dependencies. 
By removing this package from `base-runner`, a failure to do so will already be detected via a local `check_build` rather than only during fuzzer execution on ClusterFuzz.

Remove JDK dependency not available on ClusterFuzz

---

infra/cifuzz/config_utils.py
infra/cifuzz/config_utils_test.py

Don't assume that path is relative to workspace if it is not absolute.
Only make this assumption on GitHub where it will always be true.
Also, add tests.

[CIFuzz] Change behavior of PROJECT_SRC_PATH to be clearer.

---

infra/cifuzz/run_fuzzers_entrypoint.py

We shouldn't delete it, because we need to use it again.
This saves about 13 seconds per run.
Fixes: #5982

[cifuzz] Don't delete base-runner

---

projects/apache-httpd/Dockerfile
projects/apache-httpd/build.sh
projects/apache-httpd/fuzz_addr_parse.c
projects/apache-httpd/fuzz_parse.c
projects/apache-httpd/fuzz_tokenize.c
projects/apache-httpd/fuzz_utils.c
projects/apache-httpd/project.yaml

Integrates apache-httpd.
apr (apache runtime) and apr-util are also compiled with sanitizers. This means the code in those libraries will effectively also be analysed. For this reason following the merge of this PR I will be closing the one that proposes apr https://github.com/google/oss-fuzz/pull/6048
Topic on mailing list where oss-fuzz integration is proposed and discussed: https://mail-archives.apache.org/mod_mbox/httpd-dev/202107.mbox/%3C56a5f294-b724-7a3a-3ef3-0576862d0d92%40adalogics.com%3E

apache-httpd: initial integration

---

projects/opensk/Dockerfile
projects/opensk/build.sh

Code coverage was disabled, making the overall workflow failing.
Also adds all the fuzzing targets the project provides.

Fix project OpenSK

---

projects/libcacard/build.sh

Unbreak the build of libcacard fuzzer because of internal changes in NSS.
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=35605
And actually makes the infinite line a bit easier to read

libcacard: Update list of NSS libraries needed for build

---

projects/tor/build.sh

The openssl build process now puts objects into lib64, even if it
wasn't told to do so.  Tor's crufty old library detection code
didn't handle that.
Should fix Issue 36556 in oss-fuzz

Fix Tor build issue related to OpenSSL's use of lib64

---

projects/bitcoin-core/build.sh

This should no-longer be necessary now that https://github.com/bitcoin/bitcoin/pull/21882 has been merged upstream.
cc MarcoFalke.

bitcoin: remove i386 HAVE_BUILTIN_MUL_OVERFLOW workaround

---

projects/bleach/Dockerfile

Mozilla renamed the `master` branch `main`.

Fix bleach's build

---

infra/constants.py

I am not entirely sure about this fix since @jonathanmetzman has made a few changes recently. But coverage CI fails here: https://github.com/google/oss-fuzz/pull/6170#issuecomment-893662805 since there is no coverage sanitizer

infra: add coverage sanitizer option

---

infra/base-images/base-clang/Dockerfile

Qt now requires 3.20 or higher.

[infra] Upgrade cmake to latest release (3.21.1)

---

projects/jbig2dec/jbig2_fuzzer.cc

The JBIG2 format allows for ridiculously large images (4G x 4G
pixels!), which means that jbig2dec may use an enormous amount of
memory when it tries to decode them. OSS-fuzz currently restricts test
cases to 2.5Gbyte of memory per run, so the jbig2dec fuzzer
implemented a custom allocator to limit jbig2dec's memory usage to
1Gbyte. When the custom allocator runs out of memory jbig2dec
indicates an error, frees its resources and returns.
Limiting memory usage to 1Gbyte, below OSS-fuzz's limit of 2.5Gbyte,
eliminated the entire class of false positive OSS-fuzz issues
concerning out of memory situations. These were false positives in the
sense that a program using jbig2dec is in control of how much memory
jbig2dec uses, but the program must implement a custom jbig2dec
allocator and limit it …

[jbig2dec] Limit allocator to real world memory use, avoiding timeouts

---

projects/clamav/Dockerfile

The instructions for building libclamav-only dependencies changed.
The clamav_deps collection is now used for all clamav dependencies.
A) We don't need to waste resources building dependencies used only
by clamav programs.
B) The ncurses static build seems to be failing on this image, which
is why the build is broken/needs fixing.

[clamav] Fix build

---

projects/wasmtime/Dockerfile

In order to build the WebAssembly spec interpreter, these packages are needed.

wasmtime: provide OCaml packages for build

---

projects/opensk/project.yaml

This is to get access to fuzzing stats as per the [documentation](https://google.github.io/oss-fuzz/getting-started/new-project-guide/#primary).
FYI @jmichelp @kaczmarczyck

Update auto_ccs of opensk project

---

infra/base-images/base-builder/compile

Jazzer now links in the UBSan C++ runtime and thus support the vptr
and function sanitizer settings.

[infra] Enable Jazzer support for UBSan C++ features

---

projects/frr/project.yaml

Sorry for the churn here, I forgot you have to use a Google account to log in to CF/Monorail... :roll_eyes: 
Signed-off-by: Quentin Young <qlyoung@nvidia.com>

[frr] Change CC email

---

projects/boost-json/Dockerfile
projects/boost-json/build.sh
projects/boost-json/project.yaml

This adds boost.json. There is already a boost job. Since the boost project is huge and consists of separate projects, I think it makes sense to add a separate job for boost.json.
The fuzzers already run in CI since 2020 so I don't expect new bugs.
The upstream authors have given their consent, see https://github.com/boostorg/json/issues/592

[boost.json] initial submission

---

projects/boost-json/build.sh

I had mistakenly used "/out" instead of "$OUT" in one place. That worked fine locally.
Perhaps it would be useful to have a CI job testing using /out2/ etc to see that the build scripts are correct.

fix boost.json build error

---

docs/getting-started/continuous_integration.md

Clarify AND (not OR) for situations when crashes are reported

Clarify language in continuous_integration.md

---

infra/cifuzz/build_fuzzers.py
infra/cifuzz/build_fuzzers_test.py
infra/cifuzz/clusterfuzz_deployment.py
infra/cifuzz/clusterfuzz_deployment_test.py
infra/cifuzz/config_utils.py
infra/cifuzz/continuous_integration.py
infra/cifuzz/external-actions/build_fuzzers/action.yml
infra/cifuzz/run_fuzzers.py
infra/cifuzz/run_fuzzers_test.py
infra/cifuzz/workspace_utils.py
infra/repo_manager.py

The current way adds a lot of ordering assumptions, and doesn't fit too
well with parallel batch fuzzing either. Add a "upload-build" boolean action
input that can be added to "build_fuzzers" to upload latest builds
instead.
Builds are now uploaded by commit hash, rather than a fixed "latest" name. 
ClusterFuzzLite's download_latest_build will check the last 3 commits and download the
first available build by git hash.

Don't upload builds in run_fuzzers.

---

projects/libvips/Dockerfile
projects/libvips/build.sh

This will allow the creation of additional fuzzers to test the code paths these dependencies add.
(Also skips the `test` and `tools` subdirs when building libvips as these are not directly fuzz tested and can cause static linking problems.)

[libvips] Add imagequant and cgif dependencies

---

docs/clusterfuzzlite/build_integration.md
docs/getting-started/new_project_guide.md

- Minor clarification about this using OSS-Fuzz's build chain. Be
consistent about calling this part OSS-Fuzz (rather than
ClusterFuzzLite), since that's what the image name says.
- Add project.yaml documentation. Related: #6196
- Refer to OSS-Fuzz's guide for efficient fuzzing.

minor cflite build integration docs changes.

---

projects/clickhouse/project.yaml

I merged https://github.com/google/oss-fuzz/pull/6244
too quickly. Clickhouse fails to build.
Disable temporarily to prevent exceptions since
clickhouse is new
Change-Id: I5d99f911620d4df3a2b32c2179bca0c5afcd95c6

Disable clickhouse.

---

infra/base-images/base-builder-new/bisect_clang_new_test.py
infra/base-images/base-builder-new/detect_repo_new_test.py
infra/build_and_push_test_images.py

This is useful for testing changes to images.
I used it to test changes I made for #6180.
This does not support msan as that image is being removed.
Also lint.

[infra] Add a script for building all base-images with "-testing" suffix and pushing them to gcr.io/oss-fuzz-base.

---

docs/getting-started/new_project_guide.md

All dependencies must be built with MSAN by the project.
OSS-Fuzz will not be providing any instrumented libraries.
Related: https://github.com/google/oss-fuzz/issues/6180

[Ubuntu Upgrade][docs] Say need to build msan deps manually

---

projects/ffmpeg/Dockerfile
projects/ffmpeg/build.sh

This behavior doesn't work in Ubuntu 20.04.
Related: #6180

[ffmpeg] Don't rely on cd accepting multiple arguments.

---

projects/flatbuffers/Dockerfile

ninja-build is the intended package name. ninja-build isn't actually
needed for this project anyway.
ninja is not the build tool and isn't available in Ubuntu 20.04.
Removing this to prevent breakage.
Related: #6180

[ubuntu upgrade] Dont install ninja

---

projects/bitcoin-core/Dockerfile
projects/boost/Dockerfile
projects/grpc-httpjson-transcoding/Dockerfile
projects/http-pattern-matcher/Dockerfile
projects/libcacard/Dockerfile
projects/nettle/Dockerfile
projects/nss/Dockerfile
projects/pffft/Dockerfile
projects/tcmalloc/Dockerfile
projects/upb/Dockerfile

When we upgrade to 20.04, python wont be in base-builder and
these projects will fail unless they install it.
Until then, this change should be a noop.
Related: #6180

Install python in projects that depend on it.

---

projects/cel-cpp/Dockerfile
projects/oak/Dockerfile

When base-builder upgrades to 20.04, python wont be in and
base-builder these projects will fail unless they install it.
Until then, this change should be a noop.
Related: #6180

[Ubuntu upgrade] Install python in projects that need it: oak, cel-cpp

---

projects/skia/build.sh

This will help us catch more errors. We generally try to fail gracefully in SkSL but hitting an assertion is still a valid fuzzer discovery.

Enable SK_DEBUG when fuzzing SkSL.

---

projects/quickjs/project.yaml

The old repository is not there anymore (or not publically accessible)

Update with actual repository

---

projects/qt/project.yaml

It includes a link to the default page so no information will be lost.

[qt] Use own Readme as help_url

---

projects/cairo/Dockerfile

Do this explicitly to prevent breakage when builder is upgraded
to Ubuntu 20.04.
Related: #6180

[Ubuntu upgrade][cairo] Install libtool and autotools-dev

---

infra/base-images/base-runner/bad_build_check

Raise the threshold as honggfuzz builds in focal seem to have more
calls.
Related: #6180.

[Ubuntu Upgrade] Raise threshold MSAN calls in for bad build check.

---

projects/libspectre/project.yaml

They aren't really supported anymore and they break in
Ubuntu 20.04.
Related: #6180.

[Ubuntu upgrade][libspectre] Disable dataflow builds.

---

projects/myanmar-tools/build.sh

This prevent build from breaking when builder is upgraded to
Ubuntu 20.04.
Related: #6180.

[Ubuntu upgrade][myanmar-tools] Explicitly link against libunwind.

---

projects/glib/Dockerfile

[Ubuntu upgrade][glib] Make build work after 20.04 upgrade.

---

projects/rnp/Dockerfile
projects/rnp/build.sh

Copy all versions of the libjson shared object and install python
instead of python-minimal.
Related #6180.

[Ubuntu upgrade][rnp] Make build work on Ubuntu 20.04.

---

docs/further-reading/fuzzer_environment.md

Minijail is no longer used. Please take a look @jonathanmetzman @oliverchang @inferno-chromium in case I misunderstood.
Solves https://github.com/google/oss-fuzz/issues/6284

docs: remove minijail doc.

---

projects/lldb-eval/Dockerfile

There are still other issues preventing lldb-eval from building.
related: #6180.

[Ubuntu upgade][lldb-eval] Install python to partially fix build

---

infra/base-images/base-builder/write_labels.py

/usr/bin/python3 doesn't exist and isn't pythonic. Change shebang
to "/usr/bin/env python3"
Related: #6180

[Ubuntu upgrade][infra] Fix issue with write_labels.py

---

projects/mdbtools/build.sh

This will assist with debugging a failed CIFuzz action build:
https://github.com/mdbtools/mdbtools/pull/333/checks?check_run_id=3403232791

mdbtools: Disable silent rules when configuring

---

projects/bitcoin-core/Dockerfile
projects/gdal/Dockerfile
projects/gnutls/Dockerfile
projects/gstreamer/Dockerfile
projects/hermes/Dockerfile
projects/libarchive/Dockerfile
projects/libass/Dockerfile
projects/libphonenumber/Dockerfile
projects/libvips/Dockerfile
projects/nettle/Dockerfile
projects/osquery/Dockerfile
projects/proxygen/Dockerfile
projects/samba/Dockerfile
projects/thrift/Dockerfile
projects/tor/Dockerfile
projects/wasm3/Dockerfile
projects/wget/Dockerfile
projects/wget2/Dockerfile

This does not include coverage build failures.
Related: #6180.

[Ubuntu upgrade] Pin projects to Xenial where fuzzer build fails.

---

projects/libvips/Dockerfile
projects/libvips/build.sh

- Use libbrotli from system.
- Build libjxl without sjpeg support.
- Link fuzzers against libmount and libblkid (needed by libgio).
- Sort and remove duplicated apt-get packages.

[libvips] Upgrade to Ubuntu 20.04

---

projects/bitcoin-core/Dockerfile
projects/bitcoin-core/build_cryptofuzz.sh
projects/bitcoin-core/project.yaml

Because compiling Rust library is not possible currently:
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=37524
- https://github.com/google/oss-fuzz/issues/6268
(not applicable anymore).
I applied the changes proposed here: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=37524#c4

[bitcoin-core] Fix build

---

projects/tor/Dockerfile
projects/tor/build.sh

No need to use the EOL xenial image

tor: Use default focal image

---

projects/spirv-tools/project.yaml

Adds the Radial team to the auto-cc list.

Update auto-cc for spirv-tools

---

projects/skia/build.sh

This was broken after Swiftshader changed the names of the libraries.
See https://bugs.chromium.org/p/skia/issues/detail?id=12385 for more

[skia] Fix build after Swiftshader update

---

projects/django/Dockerfile
projects/libssh2/build.sh
projects/python3-libraries/Dockerfile

Not doing this relies on the base-builder image running apt-get
update "recently" and is a bad assumption.

[libssh2][python3-libraries][django] Run apt-get update

---

projects/tint/project.yaml

Currently there are errors building with honggfuzz. This may be because
the tint fuzz targets are not correctly configured - the tint build
system does not use the LIB_FUZZING_ENGINE environment variable and
instead hard codes various fuzzer flags. This will be fixed in due
course, but disabling honggfuzz for now to get the OSS-Fuzz build
working.

Disable honggfuzz from the tint build

---

projects/spirv-tools/build.sh

Adds corpora of SPIR-V binary and assembly shaders to the spirv-tools
project, based on shaders in the SPIRV-Tools and tint repositories.

Add corpora to the spirv-tools project

---

projects/ecc-diff-fuzzer/Dockerfile
projects/suricata/Dockerfile

Needing both rust and golang
Cf https://github.com/google/oss-fuzz/pull/6361#issuecomment-910718334
Same for Suricata needing rust

Fixes ecc-diff-fuzzer with new base-builder

---

docs/getting-started/new-project-guide/swift.md
infra/base-images/base-builder-swift/Dockerfile
infra/base-images/base-builder-swift/precompile_swift
infra/base-images/base-builder/install_swift.sh
infra/base-images/base-builder/llvmsymbol.diff
infra/build/functions/build_and_run_coverage.py
infra/constants.py
projects/grpc-swift/Dockerfile
projects/grpc-swift/build.sh
projects/grpc-swift/project.yaml
projects/swift-nio/Dockerfile
projects/swift-nio/build.sh
projects/swift-nio/project.yaml
projects/swift-protobuf/Dockerfile
projects/swift-protobuf/build.sh
projects/swift-protobuf/project.yaml

Following @asraa work to split base-builder 🙇 
- Generic script to generate `SWIFTFLAGS` as `RUSTFLAGS` or `CFLAGS`
- Support for thread sanitizer (tested build) (got `error: unsupported option '-sanitize=undefined' for target 'x86_64-unknown-linux-gnu'` for undefined )
- Support for coverage report (tested on swift-protobuf, getting a compiler internal error on grpc-swift)
- Documentation
Am I missing something ?
cc @jonathanmetzman @inferno-chromium 
How should it fit with the ubuntu upgrade ?

Swift ideal integration

---

projects/spirv-tools/build.sh

The LIB_FUZZING_ENGINE environment variable is now passed to the CMake
command of spirv-tools as an option, rather than having the environment
variable be queried in the project's CMake files.

spirv-tools: pass LIB_FUZZING_ENGINE more elegantly

---

projects/spirv-tools/project.yaml

Now that the CMake files for spirv-tools have been fixed, so that when
LIB_FUZZING_ENGINE is set, it is used as the sole way of specifying
fuzzer-related linker flags, the honggfuzz engine should work. This
change reverts the project to use the default set of fuzzing engines,
which includes honggfuzz.

spirv-tools: re-enable honggfuzz

---

projects/tint/build.sh

The LIB_FUZZING_ENGINE environment variable is now passed to tint's
CMake command as an option, rather than having the environment variable
be queried in the project's CMake files.

tint: pass LIB_FUZZING_ENGINE more elegantly

---

projects/tint/project.yaml

Now that the CMake files for int have been fixed, so that when
LIB_FUZZING_ENGINE is set, it is used as the sole way of specifying
fuzzer-related linker flags, the honggfuzz engine should work. This
change reverts the project to use the default set of fuzzing engines,
which includes honggfuzz.

tint: re-enable honggfuzz

---

.github/CODEOWNERS
projects/librawspeed/project.yaml

I was not notified about that change, which i believe to be errneous.
The fuzzers built here do *not* link to *any* outside libraries.
Refs. https://github.com/google/oss-fuzz/pull/6281
Refs. https://github.com/google/oss-fuzz/issues/6294

[RawSpeed] Reenable errneously disabled MSan build

---

infra/base-images/base-builder-swift/precompile_swift
projects/grpc-swift/Dockerfile

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=38116
Another fix could be to keep zlib1g-dev after installing swift
```
diff --git a/infra/base-images/base-builder/install_swift.sh b/infra/base-images/base-builder/install_swift.sh
index d88a7b5c..6934f65c 100755
--- a/infra/base-images/base-builder/install_swift.sh
+++ b/infra/base-images/base-builder/install_swift.sh
@@ -62,5 +62,5 @@ cd $SRC
rm -rf llvm-project llvmsymbol.diff
-apt-get remove --purge -y wget zlib1g-dev
+apt-get remove --purge -y wget
apt-get autoremove -y
```

grpc-swift needs zlib

---

projects/zydis/build.sh

Now that we've been running in OSS-Fuzz for a while and haven't seen any crashes for quite a bit, we figured that it'd be a good idea to step it up a bit and build with assertions enabled to additionally verify all of our internal assumptions.
In addition to that, this PR also enables more verbose printing during the build to make it easier to see what flags are actually passed in the logs.
Related Zydis PRs: 
- https://github.com/zyantific/zydis/pull/217
- https://github.com/zyantific/zycore-c/pull/29
CC @flobernd

Zydis: Enable assertions during fuzzing

---

projects/qemu/default.options

Close fds, and disable leak detection

qemu: add default fuzzing options

---

projects/samba/Dockerfile

Per #6302 and https://github.com/google/oss-fuzz/issues/6301#issuecomment-911705365 Samba needed, and now did upgrade the build scripts to run on Ubuntu 20.04.
See https://github.com/samba-team/samba/commit/4366c3bb71fe9c083dedeae8798547b64a64d2b4

Samba builds now expect Ubuntu 20.04

---

projects/libass/Dockerfile
projects/libass/build.sh
projects/libass/project.yaml

libass got a new [coverage build failure](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=38511) which I don’t really understand. When I tried to search whether other people had reported similar cases, I stumbled upon https://github.com/google/oss-fuzz/issues/6291 and discovered libass was one of the remaining Ubuntu 16.04 projects. Perhaps the Ubuntu 16.04 environment has gotten somehow borked.
This PR upgrades libass to Ubuntu 20.04 and cleans up the build script. (In particular, this should make future upgrades smoother, hopefully.)
While I was at it, I also updated our contact list:
* One address is removed because the person has severed all contact with the development team and deleted their GitHub account. The bugs.chromium.org/p/oss-fuzz UI also shows they have “never” …

libass: fix build, upgrade Ubuntu, update contacts

---

infra/base-images/base-builder-swift/precompile_swift

ld.gold is default and works better than ld
Should fix swift projects builds after clang 14 update
cf https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=38503

swift: no explicit linker

---

projects/lighttpd/build.sh

lighttpd: update build.sh objs
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=38330

lighttpd: update build.sh objs

---

projects/skia/build.sh

These deprecated warnings were making it hard to determine what the actual swiftshader compile error was.
There was an extra copy-assignment constructor that Clang 14 isn't happy about. That should be fixed with https://swiftshader-review.googlesource.com/c/SwiftShader/+/57028
This PR silences the deprecated-declaration warnings, which are not treated as errors, but are noisy.

[skia] Make swiftshader build less noisy

---

docs/advanced-topics/bug_fixing_guidance.md

The specific goal of this is to resolve the issue here: https://github.com/google/oss-fuzz/issues/2095 and in particular this comment https://github.com/google/oss-fuzz/issues/2095#issuecomment-636471561
I ended up writing a bit more as I thought it would be appropriate having some guidance on how to deal with bugs. I did this partly because there are other issues related to this, e.g. https://github.com/google/oss-fuzz/issues/2519. The page could be further extended, e.g. language-specific guidance, but thought I would start with this. Let me know if you think a page like this should exist and if you agree on the content.

doc: add light guidance on bug fixing

---

infra/build/functions/base_images.py

To guard against major/breaking image migrations in the future.
Part of #6324.

Tag all base images with :v1.

---

projects/janus-gateway/project.yaml

Disable the memory sanitizer in janus-gateway due to [glib not supporting](https://github.com/google/oss-fuzz/blob/master/projects/glib/project.yaml#L12) the sanitizer in oss-fuzz after the upgrade to Ubuntu 20.04.
Please close the monorail issues:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=38786
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=38819
And the related oss-fuzz reports:
https://oss-fuzz.com/testcase-detail/4853666004205568
https://oss-fuzz.com/testcase-detail/6197317464621056

janus-gateway: disable memory sanitizer

---

projects/etcd/Dockerfile
projects/etcd/build.sh
projects/etcd/project.yaml
projects/etcd/wal_fuzzer.go

Initial integration of [etcd](https://github.com/etcd-io/etcd).
etcd is a consistent and highly-available key value store used as Kubernetes' backing store for all cluster data.
_____________________________________________________________
@ptabor Are you interested in integrating etcd into OSS-fuzz for continuous fuzzing? This PR adds the build files and the first fuzzer.
To complete the PR an email address is needed for bug reports.

[etcd] Initial integration

---

projects/libass/libass_fuzzer.cc

AddressSanitizer/LeakSanitizer has begun to report partial leaks due to the library being initialized but never finalized. It’s not clear why only part of the memory is reported and why this hasn’t happened before now, but this is a somewhat legitimate report, so add finalization calls to release all memory.
The libFuzzer API provides no shutdown cleanup hook, so use a static variable with a C++ destructor.
Fixes https://github.com/google/oss-fuzz/issues/6440.
Review with “hide whitespace changes” to minimize the diff.

libass: release library memory on shutdown

---

projects/spirv-tools/build.sh
projects/spirv-tools/project.yaml

Using an instrumented version of spirv-as for corpus preparation is very
slow, and can also lead to issues where a bug in spirv-as gets picked up
by instrumentation and causes corpus preparation to fail when we would
rather it succeeded despite the bug.

Use uninstrumented spirv-as for corpus prep

---

infra/helper.py
infra/helper_test.py

infra/helper.py build_image foobar should, when asked to pull base
images, only pull the generic images as well as the base-builder for the
language declared in foobar.

infra: Only pull images corresponding to project language

---

projects/skia/build.sh

Requires https://skia-review.googlesource.com/c/skia/+/449576/ to land first

[skia] Use fuzzer constraints

---

projects/gdal/Dockerfile

I've committed changes into GDAL master that make it build with the
20.04 base-builder image
refs #6291
Fixes coverage build failure of https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=38508

[GDAL] Use Ubuntu 20.04 base-builder image

---

projects/nettle/build.sh

This is a fix-up of commit f369375419035b9a8cbb2a488a76b78525e2978c.
During simplification I misused realpath: after a clean checkout,
PREFIX/lib would not exist yet and thus realpath fails.
Sorry about that; now I have properly checked it with:
```console
$ python infra/helper.py build_fuzzers --sanitizer coverage nettle
```

nettle: Avoid calling realpath on non-existing path

---

projects/gnutls/Dockerfile

The gnutls build should be fixed with:
https://gitlab.com/gnutls/gnutls/-/commit/c3137e17356c798ea4c9327a37c0693a500571ae
I have also confirmed with:
```console
$ python infra/helper.py build_image gnutls
$ python infra/helper.py build_fuzzers --sanitizer coverage gnutls
```
Fixes: #6473

gnutls: Use default focal image (#6473)

---

projects/opensk/Dockerfile

With a recent push on our develop branch, we now need to install pkg-config and libssl-dev before building. Tested with:
```
python infra/helper.py build_image opensk
python infra/helper.py build_fuzzers --sanitizer address --engine libfuzzer --architecture x86_64 opensk
```

Fix OpenSK build problem

---

projects/bitcoin-core/build.sh

Fix for https://oss-fuzz-build-logs.storage.googleapis.com/log-c7c2bcec-feaf-459d-ae58-143cca72f738.txt
```
Step #40 - "build-check-libfuzzer-undefined-x86_64": BAD BUILD: /tmp/not-out/process_message_getaddr seems to have either startup crash or exit:
Step #40 - "build-check-libfuzzer-undefined-x86_64": /tmp/not-out/process_message_getaddr -rss_limit_mb=2560 -timeout=25 -seed=1337 -runs=4 < /dev/null
Step #40 - "build-check-libfuzzer-undefined-x86_64": init.cpp:476:29: runtime error: member call on address 0x55ec4342a908 which does not point to an object of type 'WalletInitInterface'
Step #40 - "build-check-libfuzzer-undefined-x86_64": 0x55ec4342a908: note: object has invalid vptr
Step #40 - "build-check-libfuzzer-undefined-x86_64":  00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 …
```

bitcoin-core: Temp workaround for UBSan build failure

---

infra/helper.py
infra/helper_test.py
infra/templates.py

- Add ":v1" suffix to Dockerfile template.
- Support relative paths for external project directories.

Helper fixes for external projects.

---

projects/libavif/build.sh

Run dav1d_oss_fuzz.sh instead of dav1d.cmd to build dav1d.
dav1d_oss_fuzz.sh is a copy of dav1d.cmd, with the only difference being
that it applies a patch to the dav1d source tree to work around a bug in
Meson's symbols_have_underscore_prefix() function when oss-fuzz
specifies -fprofile-instr-generate in CFLAGS in the coverage build.
Part 2 of the fix for https://crbug.com/oss-fuzz/38512.

libavif: run dav1d_oss_fuzz.sh to build dav1d

---

projects/libavif/Dockerfile

Install nasm as a Linux package rather than download and build it from
source code. This is what projects/dav1d/Dockerfile does.

libavif: install nasm as a Linux package

---

projects/spdk/Dockerfile

Install nasm as a package rather than compiling from source. This was inspired by https://github.com/google/oss-fuzz/pull/6502

spdk: simplify build

---

projects/lldb-eval/Dockerfile
projects/lldb-eval/build.sh

An attempt to resolve google/oss-fuzz#6302 and google/lldb-eval#172.
CC: @werat

[lldb-eval] Fix build failure after upgrade to Ubuntu 20.04

---

projects/systemd/project.yaml

Apparently the dependencies aren't used at runtime by the
fuzz targets so it seems it should be safe to bring MSAn back.
I'd keep https://github.com/systemd/systemd/issues/20542 open though
(at least until the dependencies are either linked properly or
maybe even removed somehow).

[systemd] turn MSAn on

---

projects/pyyaml/fuzz_loader.py

`sys.argv` is not accessible unless `sys` is imported.

Undefined name: import sys for line 33

---

infra/base-images/base-builder/cargo
infra/base-images/base-runner/coverage
infra/base-images/base-runner/gocoverage/llvm-cov-rel/llvm-profraw-relative.go
projects/suricata/project.yaml

Fixes #6268
Replaces #6449 
Introduces lvm-cov-rel, a tool to convert profraw files from version 5 and 7/clang-13 to version 7/clang-14
cc @jonathanmetzman @inferno-chromium 
Tested with
```
python3 infra/helper.py build_image --no-pull base-builder
python3 infra/helper.py build_image --no-pull base-builder-rust
python3 infra/helper.py build_image --no-pull base-runner
export PROJECT=suricata
python3 infra/helper.py build_image --no-pull $PROJECT
python3 infra/helper.py build_fuzzers --sanitizer coverage $PROJECT
python3 infra/helper.py coverage --no-corpus-download $PROJECT
```
with projects suricata, image-rs and swift-nio

Fix for rust and swift coverages

---

projects/protobuf-java/project.yaml

This makes kfm@google.com the primary contact and allows access for some
more protobuf team members.

protobuf-java: update contact information

---

infra/cifuzz/config_utils.py

Otherwise incomplete builds may be uploaded.
Fixes: https://github.com/google/oss-fuzz/issues/6529
Related: https://github.com/google/oss-fuzz/issues/6525

[clusterfuzzlite] Keep unaffected fuzzers when uploading a build.

---

projects/sudoers/build.sh

Sudo does not link executables using CFLAGS, only LDFLAGS.  When building with UBSan, the compiler warns that the object size sanitizer has no effect at -O0 but is explicitly enabled.

sudoers: set optimization flag in LDFLAGS for the object size sanitizer

---

infra/base-images/base-runner/gocoverage/llvm-cov-rel/llvm-profraw-relative.go

Following #6517 
Since then, the new LLVM 14 commit b9f547e8e51182d32f1912f97a3e53f4899ea6be https://reviews.llvm.org/D110365
added a new change (adding a padding and erroring if a field size is not a multiple of sizeof(uint64))
cc @jonathanmetzman

rust coverage: fix binary ids padding

---

infra/cifuzz/cifuzz-base/Dockerfile

We will use github_actions_toolkit to upload artifacts in the future.

ClusterFuzzLite: Install nodejs in cifuzz-base.

---

projects/freeradius/Dockerfile
projects/freeradius/build.sh

This was fairly tedious to debug, the issues boiled down to the call to `ac_fn_c_try_link` here:
https://github.com/FreeRADIUS/freeradius-server/blob/288880a63b510fe83c215f8e54648625500b9ac7/configure#L8247 
resulted in the following errors:
```
$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5   
/usr/bin/ld: /usr/local/lib/clang/14.0.0/lib/linux/libclang_rt.asan-x86_64.a(sanitizer_unwind_linux_libcdep.cpp.o): in function `__sanitizer::BufferedStackTrace::UnwindSlow(unsigned long, unsigned int)':                                                       
/src/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_unwind_linux_libcdep.cpp:130: undefined reference to `_Unwind_Backtrace'
/usr/bin/ld: /usr/local/lib/clang/14.0.0/lib/linux/libclang_rt.asan-x86_64.a(s …
```

freeradius: fix build

---

infra/cifuzz/build_fuzzers.py

Builds shouldn't be uploaded if the check fails.
Fixes: https://github.com/google/oss-fuzz/issues/6667

[clusterfuzzlite] Upload builds after doing bad build check

---

infra/cifuzz/build_fuzzers.py
infra/cifuzz/build_fuzzers_entrypoint.py
infra/cifuzz/build_fuzzers_test.py
infra/cifuzz/cifuzz_combined_entrypoint.py
infra/cifuzz/clusterfuzz_deployment.py
infra/cifuzz/clusterfuzz_deployment_test.py
infra/cifuzz/config_utils.py
infra/cifuzz/config_utils_test.py
infra/cifuzz/continuous_integration.py
infra/cifuzz/filestore/github_actions/github_actions_test.py
infra/cifuzz/logs.py
infra/cifuzz/run_fuzzers_entrypoint.py
infra/cifuzz/run_fuzzers_test.py

1. Remove obsolete comments.
2. Remove unused function get_pr_ref
3. Correct comment on git_sha
4. Rename commit_sha to git_sha
5. Make base_commit, pr_ref, and base_ref non-github specific and move to
CiEnvironment.
6. Hoist get_diff_base to base class to allow diffing
7. Fix downloading coverage on non-Github.
8. Add TODO so that we don't assume github actions is run on github.com
(enterprise users)
9. Rename repo_url to git_url.
10. Add missing git_url method base class.
11. Clarify what git_url, git_sha, and pr_ref are for and leave TODOs about how
we can eliminate them.
12. Fix typos.

Fix diffing on non-GitHub and improve config

---

infra/cifuzz/continuous_integration.py

Share more code between the 4 implementations of `prepare_for_fuzzer_build`.
This simplifies the code of these implementations, reduces repetition and makes them easier to
understand.
Create helper functions/methods for:
1. Creating a failed `BuildPreparationResult`: `get_build_preparation_failure`
2. Building an external project docker image: `_build_external_project_docker_image` 
3. Cloning a repo and checking out the specified commit/pr: `_clone_repo_and_checkout`
4. Detecting the main repo `_detect_main_repo`
5. Creating a repo manager from an existing checkout: `_create_repo_manager_for_project_src_path`
Change `ExternalGeneric` implementation of `prepare_for_fuzzer_build` to:
1. Call `_create_repo_manager_for_project_src_path`
2. Call `_build_external_project_docker_image`
Change …

Abstract away duplicate code in prepare_for_fuzzer_build

---

projects/net-snmp/build.sh

This is a fix to allow the fuzzer to run further for now, as our preference is more important bugs than leaks.

net-snmp: disable leak checking for api fuzzer

---

projects/libdwarf/fuzz_init_path.c

libdwarf: ensure error is a valid pointer to avoid early exit

---

projects/glib/project.yaml

Add Sebastian Dröge as an additional CC to oss-fuzz issues for GLib. He’s a maintainer (see https://gitlab.gnome.org/GNOME/glib/-/blob/main/docs/CODEOWNERS and https://gitlab.gnome.org/sdroege).

Add additional maintainer CC to GLib configuration

---

projects/php/project.yaml

We have some fuzzers that are security-critical (json, exif), but
these haven't found anything genuinely new in a long time. It seems
unlikely that they will find something that is not a regression in
a pre-release version (and as such okay to be public).
The other fuzzers are not classified as security-critical by the
the PHP project (unserialize, unserializehash, parser, execute,
function-jit, tracing-jit). The latter three produce the vast
majority of new reports.
I think it would be more valuable to make fuzzing reports public
and have a larger set of people who can work on them.
@smalyshev What do you think about this?

[php] Make reports public

---

projects/yara/Dockerfile

Some PRs require parsers to be rebuilt. Fix oss-fuzz failures for
those cases.

Add bison, flex

---

projects/inchi/inchi_input_fuzzer.c

GetINCHIfromINCHI calls strlen on szOptions, which leads to undefined behavior as it's not a valid null-terminated byte string.
Explicitly NULL out the char* to avoid this.

Avoid calling strlen on uninitialized data

---

infra/helper.py

argparse.REMAINDER is too greedy and will consume known optional
arguments as well.
Fixes #6686.

Use nargs='*' instead of REMAINDER for helper.py.

---

infra/templates.py

Found this incorrect command in the generated Dockerfile when testing clusterfuzzlite

fix Dockerfile COPY command

---

docs/getting-started/new_project_guide.md

As far as I can tell this statement is no longer valid, i.e. the files of seeds do not need to be named with the sha1 of their contents. At least not in the OSS-Fuzz infrastructure, but am not sure if Clusterfuzz does some checking on the names?

docs: remove statement on naming seed with sha1 values

---

projects/boost-json/build.sh

This is an attempt to fix the coverage build which has been broken since the initial submission. It works locally, following the https://google.github.io/oss-fuzz/advanced-topics/code-coverage/#generate-code-coverage-reports instructions.

[boost-json] fix coverage build

---

projects/json-java/Dockerfile
projects/json-java/JsonJavaFuzzer.java
projects/json-java/build.sh
projects/json-java/project.yaml

Initial integration of JSON-java. 
The JSON-java package is used by ~4400 repositories in Maven https://mvnrepository.com/artifact/org.json/json and is the 4th most used json library in Java following jackson, gson and fastjson https://mvnrepository.com/open-source/json-libraries - on Maven the releases of JSON-java date back to 2007. 
The repositories on Maven that uses this parser are listed here https://mvnrepository.com/artifact/org.json/json/usages?p=1 and includes various Google repositories. 
@inferno-chromium @jonathanmetzman @oliverchang this one is ready for review!

json-java: initial integration

---

projects/gson/FuzzParse.java
projects/gson/FuzzReader.java

This should fix:
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=40795
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=40787

gson: catch highest level exceptions

---

projects/libdwarf/Dockerfile
projects/libdwarf/build.sh
projects/libdwarf/fuzz_init_binary.c
projects/libdwarf/fuzz_init_path.c

Thanks to David Anderson for letting me know about header file inclusion in libdwarf

libdwarf: add seeds and cleanup fuzzers to only used public headers

---

projects/dng_sdk/Dockerfile
projects/dng_sdk/build.sh

Currently execution is scarce in areas where image-specific data is
considered. This PR tries to overcome that by including more seeds
in the corpus, with the hope that these images contain examples of
the given data.

dng_sdk: extend with more seeds

---

infra/cifuzz/run_fuzzers.py
infra/cifuzz/run_fuzzers_test.py
infra/utils.py

Coverage uses a different mechanism for determining if a file
is a fuzz target: It considers any executables in the top level
of /out as fuzz targets.
Fixes #6768

[ClusterFuzzLite] Fix fuzz target search for coverage

---

projects/duckdb/build.sh

In duckdb/duckdb#2563 we are moving to bundle any included DuckDB extensions with the main library. As by default the Parquet extension is enabled, this is now resulting in linking errors in CI Fuzz ([relevant CI](https://github.com/duckdb/duckdb/runs/4151827093?check_suite_focus=true)). This PR should fix that by linking to the extension libraries as well.

duckdb: link to any built extensions as well

---

projects/apache-httpd/fuzz_addr_parse.c
projects/apache-httpd/fuzz_tokenize.c

Using apr_terminate() causes leaks (e.g. Issue 37165).

apr_pool_initialize() pairs with apr_pool_terminate()

---

infra/base-images/base-builder/Dockerfile

This updates afl++ which has a good efficiency increase.
Caveat: cmplog/redqueen binaries still work with previous afl-fuzz but there might be a slight impact.
The new afl-fuzz however requires that cmplog binaries were made with the current (or future) afl-cc/afl-clang-fast.
So - where does afl-fuzz in clusterfuzz come from? If that is from the oss-fuzz target package then this is fine.
If clusterfuzz uses its own afl-fuzz then this should be a coordinated update.

update afl++ commit id (warning)

---

projects/num-bigint/Dockerfile
projects/num-bigint/build.sh
projects/num-bigint/project.yaml

num-bigint is the most widely used bignum library for Rust.
Crate page: https://crates.io/crates/num-bigint
It currently has 367 first grade reverse dependencies: https://crates.io/crates/num-bigint/reverse_dependencies
This fuzzer recently found a security vulnerability: https://github.com/rust-num/num-bigint/security/advisories/GHSA-v935-pqmr-g8v9
The maintainer is aware of this integration and his address is included in the `project.yaml`.

[num-bigint] Add project

---

projects/apache-httpd/Dockerfile
projects/apache-httpd/build.sh

Fix build of apache-httpd because patches no longer apply. We now avoid using patches that made the parser cleanly return instead of hitting asserts following https://github.com/apache/httpd/commit/a6e5a92b0d0e74ead5a43f20f81f5cf880ea4fb8
CC @ylavic

apache-httpd: fix build by updating patch to mainstream

---

projects/clamav/Dockerfile

Switch over to the base-builder-rust image to build Rust modules (static libs) in ClamAV

[clamav] add rust toolchain

---

projects/oak/build.sh
projects/oak/project.yaml

- Update paths in build.sh following the changes in https://github.com/project-oak/oak/pull/2361.
- Changes sanitizers in project.yaml to `coverage`. The CI fails (possibly due to OOM error) for `address` and `undefined` sanitizers, even though the builds pass locally.

oak: fix path

---

infra/cifuzz/docker.py
infra/cifuzz/docker_test.py
infra/helper.py

This is a follow-up to https://github.com/google/oss-fuzz/commit/14582175d07c8a66adf3f9087a464612f2a3f630#diff-f7cbd58a5ead1f30c3790c91e50ab1667afba5b26d0562a601b9d048c9e5da88, which changed the code to pass `--cap-add SYS_PTRACE` into `docker_run`, which again appends `--privileged`. `--privileged` already covers all capabilities, so there is no need to add specific ones. See https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities . In fact, using both will result in errors on alternative docker implementations:
```
Error: invalid config provided: CapAdd and privileged are mutually exclusive options

infra: Remove redundant --cap-add SYS_PTRACE

---

projects/njs/Dockerfile
projects/njs/build.sh
projects/njs/project.yaml

PCRE2 support was added recently for NJS http://hg.nginx.org/njs/rev/728c3741f556.
This pull request replaces PCRE with PCRE2. 
It also fixed MSAN issue.

[njs] Build pcre2 dependency manually and enable MSan.

---

projects/envoy/build.sh

Envoy's PR [18732](https://github.com/envoyproxy/envoy/pull/18732/files) set the clang/clang++ compilers when using the `clang` build config.
This prevents the underlying oss-fuzz infra from using other types of compilers (e.g., afl++), and we get the following linking error:
```
Step #3 - "compile-afl-address-x86_64": ld.lld: error: undefined symbol: __afl_manual_init
Step #3 - "compile-afl-address-x86_64": >>> referenced by aflpp_driver.c:258
Step #3 - "compile-afl-address-x86_64": >>>               aflpp_driver.o:(main) in archive external/rules_fuzzing_oss_fuzz/oss_fuzz_engine.a
Step #3 - "compile-afl-address-x86_64": >>> referenced by aflpp_driver.c:273
Step #3 - "compile-afl-address-x86_64": >>>               aflpp_driver.o:(main) in archive …
```

Envoy: overriding CC and CXX when building in oss-fuzz

---

projects/libjxl/build.sh

Currently Clang hangs on compiling some libjxl files.

Temporarily disable SSSE3 target

---

projects/libvips/build.sh

Corresponds to the fix introduced in PR #6837.

libvips: temporarily disable the SSSE3 target

---

projects/config-validator/Dockerfile
projects/config-validator/build.sh
projects/config-validator/project.yaml

I successfully ran the following commands from the [guide](https://google.github.io/oss-fuzz/getting-started/new-project-guide/#testing-locally):
```sh
python infra/helper.py build_image config-validator
python infra/helper.py build_fuzzers --sanitizer address config-validator
python infra/helper.py check_build config-validator
python infra/helper.py run_fuzzer config-validator fuzz_config_validator
```

Forseti Config Validator: initial integration

---

projects/libteken/project.yaml

It does not seem relevant and makes the build fail
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=38471

Removes DFSan for libteken

---

projects/harfbuzz/Dockerfile

Upstream is going to require it soon (https://github.com/harfbuzz/harfbuzz/pull/3302).

[harfbuzz] Build with meson 0.56.0

---

projects/opensk/build.sh

so that coverage works because we use the cargo wrapper
which looks for fuzz build argument at the beginning
cc @kaczmarczyck

opensk: do not specify nightly

---

projects/linkerd2/Dockerfile
projects/linkerd2/build.sh
projects/linkerd2/fuzzers.go
projects/linkerd2/project.yaml

Linkerd2 is security-first service mesh for Kubernetes used by companies like Godaddy, HP, Walmart and Expedia [[https://linkerd.io](https://linkerd.io)]
The project graduated the CNCF in july this year [[https://linkerd.io/2021/07/28/announcing-cncf-graduation/](https://linkerd.io/2021/07/28/announcing-cncf-graduation/)] 
This PR adds the projects main repo.

[linkerd2] Initial integration

---

projects/orbit/Dockerfile
projects/orbit/build.sh
projects/orbit/default.options

We recently added a new fuzzer that prints a lot to stdout due to
how error messages are handled. With this change we suppress this
output.
The understanding is that useful output from asan, etc. goes to
stderr, which we do not suppress.

[orbit] Suppress stdout output for fuzzers in projects/orbit

---

projects/neomutt/Dockerfile
projects/neomutt/build.sh

- Split corpus into new repo:
https://github.com/neomutt/corpus-address
- Use shallow git clones to save net traffic
- Drop unnecessary installs
- Rename files for consistency
I've tested the build locally under Docker, using
```sh
infra/helper.py build_image neomutt
infra/helper.py build_fuzzers --sanitizer address neomutt
infra/helper.py check_build neomutt
infra/helper.py run_fuzzer neomutt address-fuzz
```
---
I've signed the Google CLA.

neomutt: reorganise build

---

projects/sigstore/Dockerfile
projects/sigstore/build.sh
projects/sigstore/project.yaml

Included sigstore/sigstore project

Fuzzing sigstore

---

docs/getting-started/continuous_integration.md

@jonathanmetzman The CIFuzz docs has a section about `fuzz-time` that is not mentioned elsewhere in the docs or the examples.
Should it also be changed for ClusterfuzzLite? https://github.com/google/oss-fuzz/blob/master/docs/clusterfuzzlite/running_clusterfuzzlite.md#configuration-options

[cifuzz] Small correction to docs

---

projects/pigweed/build.sh

Use correct compilation directory in the coverage mapping.
Bug: https://crbug.com/oss-fuzz/38518

pigweed: Fix coverage build failure

---

projects/libbpf/build.sh

All the issues that check was supposed to catch should be
caught by the libbpf testsuite when it's run under UBSan
so it doesn't seem to make much sense to add it to the compiler
flags on OSS-Fuzz.

[libbpf] remove an out-of-date comment

---

projects/bleach/project.yaml

Supersedes https://github.com/google/oss-fuzz/pull/6925 (set commit author address in CLA earlier PR used the GH web UI and a GH noreply email address)  
Update bleach maintainers primary contact to @willkg (listed on https://github.com/mozilla/bleach/blob/ad0004f682655a541ae05b726161b2a359d301a5/CONTRIBUTORS#L8) and move @g-k to personal email address

bleach: update maintainers

---

projects/libbpf/Dockerfile
projects/libbpf/build.sh

Looks like --disable-libdebuginfod works now so it seems
it can safely be used instead of installing libcurl and
letting ./configure find and ignore it.

[libbpf] use --disable-libdebuginfod while building libelf

---

infra/cifuzz/build_fuzzers.py
infra/cifuzz/build_fuzzers_test.py
infra/cifuzz/continuous_integration.py
projects/cifuzz-example/Dockerfile
projects/cifuzz-example/build.sh

Do this instead of cloning repo anew.
Fixes: #6755

[cifuzz] Copy repo from image before checking out. 

---

infra/base-images/base-clang/checkout_build_install_llvm.sh

`=llvmorg-14-init-11072-gb1bc627e` corresponds to commit b1bc627e7e9965e6ec15e106ee4b2c21f6c36923, which includes commit 89eb85ac6eaab6431ef72ef705d560c72c5ed71f3 (the commit causing afl++ compile failures).
Thus, set it to `llvmorg-14-init-8033-gabb2a91b`, which compiles afl++ still fine.
For reference:
* https://chromium.googlesource.com/chromium/src/tools/clang/+log/refs/heads/main/scripts/update.py

[base-clang] Change OUR_LLVM_REVISION

---

infra/base-images/base-clang/checkout_build_install_llvm.sh

This version is confirmed to fix the AFL++ issues and was the last version we
used prior to the breakages on December 2nd.

Use llvmorg-14-init-7378-gaee49255 for LLVM

---

projects/elfutils/build.sh

to make it easier to figure out why configure fails with something like
```
Step #3 - "compile-afl-address-x86_64": configure: error: in `/src/elfutils':
Step #3 - "compile-afl-address-x86_64": configure: error: C compiler cannot create executables
Step #3 - "compile-afl-address-x86_64": See `config.log' for more details
```

[elfutils] show config.log when ./configure fails

---

projects/cryptofuzz/Dockerfile
projects/cryptofuzz/build.sh

- Enable Mozilla NSS fuzzer again
- Enable libgmp debug asserts
- Build libgmp with MSAN
- Remove LibreSSL (moved to the 'libressl' project some time ago)
- Don't pipe output to /dev/null (this was necessary for some previous version of the OSS-Fuzz build system)

[cryptofuzz] Update

---

projects/neomutt/project.yaml

The issue found by CIFuzz here https://github.com/neomutt/neomutt/pull/3144 seems to be a false positive. Removing MSAN to make things work.

neomutt: remove MSAN as it introduces false positives

---

projects/suricata/build.sh

cc @inferno-chromium @jonathanmetzman 
In facts, I would like the fuzzing engines to automatically get these words for the dictionaries.
That is when the rust function `tag` (from nom crate) is called, the first string should be provided as a feedback to the fuzzing engine so that it can put it in the dictionary.
This way, the dictionaries entries will be automatically used by the relevant fuzz targets.
With this precomputed generic dictionary, I do not know which patterns are useful for which targets (like `bitstring_overflow` is useful for `fuzz_siginit` but `EPRT` is useful for `fuzz_sigpcap` or ftp targets)
Is there a way to do that ?
PS : I do not have control over the rust function `tag` from nom crate which ends up comparing the chars one by one cf `let pos = …

suricata: uses better dictionaries

---

projects/elfutils/project.yaml

to prevent OSS-Fuzz from reporting bugs that have already been fixed

[elfutils] build elfutils more often

---

projects/binutils/build.sh

A lot of updates has recently happened in the OSS-Fuzz integration, and
the build script got a bit excessive. This tries to limit the complexity
of the build script and also removes guards previously had for AFL
builds.

binutils: cleanup build

---

projects/cryptofuzz/build.sh

I was accidentally building libgmp with assembly in the MSAN build.

[cryptofuzz] Fix libgmp MSAN

---

projects/envoy/project.yaml

Using AFL leads to out-of-space on the device.
Possible solution suggested in: https://github.com/bazelbuild/rules_fuzzing/issues/185
This PR disables AFL until we get this sorted out.

Envoy: disable AFL engine

---

projects/skia/project.yaml

So that this service account has view access.
@oliverchang Is that the best way to give this service account access to skia bugs?

Add skia-bugs-central@skia-public.iam.gserviceaccount.com to auto_ccs

---

projects/freetype2/Dockerfile

This will allow the FreeType fuzzer to use ninja for some of the build
steps.

Add ninja-build to freetype2 image.

---

infra/cifuzz/fuzz_target.py

Fixes https://github.com/google/clusterfuzzlite/issues/66

[cifuzz] Don't enforce OOM limit when no OOMs aren't reported

---

projects/spicy/project.yaml

Hi,
I am one of the maintainers of [Zeek](https://github.com/zeek/zeek), which is already being fuzzed by OSS-Fuzz (https://github.com/google/oss-fuzz/tree/master/projects/zeek).
We created a new subproject, called [Spicy](https://github.com/zeek/spicy), which is a standalone toolchain for generating parsers for network protocols/file formats. Spicy currently is not used by Zeek by default - however it will be in the future.
We would like to add Spicy to OSS-Fuzz, to see if any issues can be found with fuzzing. It would be especially nice if we could do this before it gets used by Zeek by default.
I am submitting a minimal PR to check and make sure that it is OK for us to submit a subproject to OSS fuzz that currently might not have a large user-base yet; the project will immediately have …

Add project.yaml for Spicy

---

infra/cifuzz/CHANGELOG
infra/cifuzz/affected_fuzz_targets.py
infra/cifuzz/affected_fuzz_targets_test.py

Fixes affected fuzz targets by normalizing path names.
Fixes: https://github.com/google/oss-fuzz/issues/7011

[CIFuzz] Fix affected fuzz targets.

---

projects/log4j2/Dockerfile
projects/log4j2/Log4jFuzzer.java
projects/log4j2/build.sh
projects/log4j2/project.yaml

[log4j2] intitial integration

---

projects/libbpf/build.sh

to make it easier to figure out why it fails to compile with AFL

[libbpf] show config.log when configure fails

---

projects/libjxl/Dockerfile

Recently the dependency on lodepng was removed from libjxl, so `third_party/lodepng` no longer exists in the project.

libjxl: lodepng dependency was removed

---

projects/freetype2/project.yaml

The upstream freetype-testing project now pulls llvm-project and builds
libcxx and libcxx-abi and statically links against them to support the
use of C++ in the fuzzer driver.

[freetype2] Add MemorySanitizer

---

projects/qt/Dockerfile

The super-repo qt5.git contains the revisions which were last tested successfully with all
submodules together. That is much older.
The super repo can be removed as soon as the build script was updated in upstream repo.

[qt] Clone the latest combination of qtbase and qtsvg which passed upstream CI

---

projects/envoy/build.sh

The `check_build` step fails on one of the fuzzers because some of the code is built with sanitizers and some of the libraries without.
This PR builds the googletest dependency with sanitizers.

[envoy] Build googletest with sanitizers

---

projects/wget/Dockerfile
projects/wget/build.sh

- Fix AFL build by using $CC instead of $CXX
- Avoid 2x indirect git cloning of gnulib submodules
- Smaller cleanups in build.sh

[wget] Fix AFL build

---

projects/cairo/Dockerfile
projects/cairo/build.sh

Sometimes the current ftp site has timeouts which causes the build
to fail. This switches it to the upstream repo (as oss-fuzz glib
integration itself) to make it more stable.

cairo: update glib source and version

---

projects/monero/Dockerfile

Monero builds hav failed in the last 5 out of 7 days, but a bit
on-and-off. The reason is a missing yacc binary during unbound
compilation, this fixes it.

monero: fix and stabilise coverage build

---

projects/osquery/Dockerfile

osquery now requires CMake version 3.21.4 at least, but on the base image
only 3.21.1 is available so the build fails.
Download a CMake prebuilt binary with the correct version.

[osquery] Fix build due to new CMake requirements

---

projects/selinux/project.yaml

Waiting for https://lore.kernel.org/selinux/CAJ2a_DcbGirAaWFZFuk6z4SsbVpZSY8WfeCDJKkVPWpzE3f1WA@mail.gmail.com/T/#u.
@fishilico @WOnder93 could you take a look? @cgzones added a fuzz target that started finding bugs. I don't think those bugs reports should be hidden from @cgzones :-)

[selinux] add Christian Göttsche's email address

---

projects/argo/Dockerfile
projects/argo/build.sh
projects/argo/normalizer_fuzzer.go
projects/argo/project.yaml
projects/argo/workflow_validation_fuzzer.go

Argo is a CNCF incubating project that offers a suite of gitops and continuous delivery tools. 
Argo is used by Tesla, IBM, Intuit, Nextdoor, Redhat and Skyscanner amongst [many others](https://github.com/argoproj/argo-cd/blob/master/USERS.md).

[argo] Initial integration

---

projects/tink/Dockerfile
projects/tink/build.sh

There is an issue with the existing coverage due to symbolic links. This fixes it

tink: fix coverage

---

projects/swift-protobuf/project.yaml

The testing isn't calling all the generated apis, it is focused on ensuring all
the parsing/serialization code paths are covered; so don't count these files in
the stats.

Ignore the files generated from the protos in the coverage data.

---

projects/envoy/build.sh

Adding more sanitization to prevent mixing non-ASAN and ASAN code.

[envoy] Fix antlr sanitization

---

infra/cifuzz/filestore/no_filestore/__init__.py

I was about to add support for GitLab to Clusterfuzzlite (https://github.com/google/clusterfuzzlite/issues/55) and wanted to start with a minimal example with no filestore, but noticed during CI run that `NoFilestore::upload_corpus()` is missing the `BaseFilestore` interface's `replace` parameter, which makes Clusterfuzzlite throw an exception when using the `NoFilestore`.

[Clusterfuzzlite] Add missing replace param to upload_corpus()

---

projects/libjxl/build.sh

* cmake uses cached values
* linker complaints about rpaths
* ninja compiles differently - cmake does not detect problem with "no-rtti" flag

libjxl: fix "local reproduce" problems

---

projects/gnupg/Dockerfile
projects/gnupg/build.sh

Ensure the gettext version in `Makefile.in.in` of libgpg-error is valid in the oss-fuzz environment

gnupg: fix build

---

projects/libvips/Dockerfile

This will fix the failing build.
Required since https://github.com/libjxl/libjxl/pull/1039
As fixed for libjxl via https://github.com/google/oss-fuzz/pull/7063

libvips: add gflags dependency for libjxl

---

projects/gson/build.sh

Gson minimum Java target version has been increased to Java 7 (https://github.com/google/gson/pull/2043), it should therefore no longer be necessary to manually overwrite it here.

Remove Gson Java version overwrite

---

projects/distribution/Dockerfile
projects/distribution/build.sh
projects/distribution/project.yaml

Adds initial integration of Distribution.
Distribution is a core library for many registry operators including Docker Hub, GitHub Container Registry, GitLab Container Registry and DigitalOcean Container Registry, as well as the CNCF Harbor Project, and VMware Harbor Registry.
__________________________________________________
@dmcgowan Can we also integrate Distribution into OSS-fuzz? No changes are needed at this point upstream, just an email address for bug reports.

[distribution] Initial integration

---

projects/swift-protobuf/project.yaml

cc @thomasvl 
We are talking regex, not bash here ;-)

swift-protobuf: fix regex for coverage exclusion

---

projects/testing-native-go-fuzzing/Dockerfile
projects/testing-native-go-fuzzing/build.sh
projects/testing-native-go-fuzzing/fuzzers/ast_fuzzer_test.go
projects/testing-native-go-fuzzing/fuzzers/parser_fuzzer_test.go
projects/testing-native-go-fuzzing/fuzzers/tablet_manager_fuzzer_test.go
projects/testing-native-go-fuzzing/native_ossfuzz_coverage_runnger.go
projects/testing-native-go-fuzzing/project.yaml

This PR has the purpose to set up a demo project for testing the native Go fuzzing integration.
The integration is now set up in `build.sh` and not in the base image. Eventually it will move to a base image, but for rapid testing it is kept in `build.sh` for now.
At the time of this PR, the following is being tested:
- Native fuzzers can be built and run.
- Go-fuzz fuzzers can be built and run (in the same project).
- Coverage works for both native fuzzers and go-fuzz fuzzers.
- Native fuzzers and go-fuzz fuzzers can be built using the same api. This api is for now called `build_go_fuzzer` but will replace `compile_go_fuzzer` later.
The goal of this PR is testing the integration in a controlled production setting. The Vitess project is used as demo project.
Development of the integration …

Test drive native fuzzing

---

projects/cpython3/build.sh

Based on a conversation in https://github.com/python/cpython/pull/30529 when fixing an issue oss-fuzz identified, we'd like assert statements to fire in oss-fuzz builds. This _should_ do that.

Enable C asserts in the cpython3 oss-fuzz build.

---

projects/igraph/project.yaml

igraph builds on 32-bit platforms. Fuzzing on 32-bit may be beneficial as some error-handling code paths, related to hitting limits, are only likely to be covered on 32-bit.

[igraph] enable fuzzing on i386

---

projects/fluxcd/Dockerfile
projects/fluxcd/build.sh
projects/fluxcd/project.yaml

Changes target the official fluxcd repository now that the fuzzing implementation has been merged. It also delegates to each repository the responsibility of its own build/setup via a file called `oss_fuzz_build.sh`.
The primary contact is now the official security contact via cncf.io.

Update fluxcd setup and contact details

---

projects/simd/build.sh
projects/simd/project.yaml

simd: force use of a single CPU during compilation

---

projects/kubernetes/project.yaml

The primary contact for Kubernetes should be the official vulnerability reporting email address, `security@kubernetes.io`.
Adding myself as an auto-CC so that I may view details in my role as SRC member.

update Kubernetes contacts

---

projects/opensk/build.sh

The bug occured first in our [GitHub workflow](https://github.com/google/OpenSK/pull/424), and was then [automatically reported](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=43876). OpenSK pins the nightly for its builds, and that is necessary for the build script here as well.

Fix OpenSK build problem (nightly version)

---

projects/lzo/lzo_compress_target.c

Some fuzzing drivers invoke this function with zero size, which causes creation of a zero-size VLA (variable-length array). In C99 VLA size must not be zero. Clang started enforcing this in https://github.com/llvm/llvm-project/commit/b2715660ed0f821619f51158fb92cd8bddd105d8 (when compiled with -fsanitize=vla-bound).

Ensure VLA of zero size is never created in LLVMFuzzerTestOneInput().

---

projects/xpdf/Dockerfile
projects/xpdf/build.sh
projects/xpdf/fuzz_pdfload.cc

- Check the certificate when downloading the source code archive
- Don't use Qt, since it's only used for the xpdf GUI
- Be less verbose when unpacking the xpdf source code
- Install libpng, freetype and zlib to increase coverage
- Explicitly disable multithreading
- Exercise more codepaths

Improve xpdf's PDF fuzzer

---

infra/base-images/base-builder/install_java.sh

Jazzer updated Bazel to 5 in https://github.com/CodeIntelligenceTesting/jazzer/commit/d6bc8f7de91b7e31748432a2ad7d5b0cfdf93053 which seems to be causing issues with our CI tests.

Pin Jazzer to pre-Bazel 5 update

---

infra/base-images/base-builder/Dockerfile
infra/base-images/base-builder/install_python.sh
infra/base-images/base-clang/Dockerfile
infra/base-images/base-clang/checkout_build_install_llvm.sh

0. Don't clone fuzz-introspector to /src since it breaks builds.
1. Install packages in python install script properly. Previously
pip install atheris>=2.0.6 was interpreted as "redirect the output
from pip install atheris" to the file "=2.0.6".
3. Clean up some miscellanious issues.

Clean up build infra issues.

---

projects/spidermonkey/build.sh

An eternal loop exists here https://github.com/mozilla/gecko-dev/blob/78963fe42f8d5f582f84da84a5e78377b6c1fc32/python/mozboot/mozboot/bootstrap.py#L527-L558 which is triggered in the current build set up. This fixes it.

spidermonkey: fix build by avoiding eternal loop

---

projects/urllib3/build.sh

We switched from setuptools to Flit, and running setup.py is deprecated anyway.

Fix urllib3 install procedure

---

infra/base-images/base-builder/compile
infra/build/functions/build_and_run_coverage.py
infra/build/functions/deploy.sh
infra/build/functions/project_sync.py
infra/build/functions/project_sync_test.py

- Point `compile` to the right `fuzz-introspector` location (since it's no longer checked out in $SRC).
- Rename build tag to "introspector" to be more consistent with other
tags.
- Fix bad merge in deploy.sh script.
- Add introspector setup to project sync.
- Enable more logging for project sync cron.

Fuzz introspector build fixes.

---

infra/build/functions/build_and_run_coverage.py

Fixes https://github.com/google/oss-fuzz/issues/7225

[build] Don't assume textcov reports exist for non-C/C++ projects

---

infra/build/functions/build_project.py

To address issues like #7228 where introspector builds are taking too long.
This is temporary until we fix other fast failing builds.

Setting a shorter timeout for introspector builds temporarily

---

projects/skia/Dockerfile
projects/skia/build.sh

Addresses https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=44132
The legacy OpenGL ES targets were removed in https://swiftshader.googlesource.com/SwiftShader.git/+/4625f84e8d56feaf9ba0122f49a04f9cccbad909
I experimented with removing the swiftshader build entirely and the skia fuzzers appear to still compile, link, and run locally, but that did not translate to actually running the fuzzers in the runtime container.
Using the Vulkan endpoints, just like we do in [Skia proper](https://skia-review.googlesource.com/c/skia/+/437149), is a better solution.
Procedure for testing this locally (and iterating):
1. In oss-fuzz checkout, run `python infra/helper.py shell skia` to pull up local interactive version of Dockerfuzzer build image.
2. Run `compile` in fuzzer shell. Stop after the …

[skia] Compile Vulkan Swiftshader instead of OpenGL ES

---

infra/build/functions/project_sync.py
infra/build/functions/project_sync_test.py

This gives enough time for coverage build to finish and then interospector can use the coverage report. It eliminates the chance of incomplete reports on introspector when there is no coverage report. Until we implement the method for getting the latest coverage reports from GCB.

Separating introspector build schedule from coverage build

---

projects/qt/Dockerfile

QtSynchronizeRepo.cmake used to do that when a dependency was
missing but since 8a94d1e it just ignores missing checkouts.
--depth 5000 clones about a year of history and reduces the size
of the repository by over 200MB. Cloning even less history would
further reduce the size by less than 15MB.

[qt] Explicitly clone qtbase

---

projects/xpdf/Dockerfile
projects/xpdf/build.sh
projects/xpdf/fuzz_pdfload.cc

- Do not fail silently on compilation issues
- Use a static version of freetype
- Render the PDF on a bitmap, to exercise more code paths.
- I'm planning on adding more outputs (maybe in new fuzzers) for Postscript for example
- Exercise more metadata gathering functions
- Use a stream instead of a file, to speed the fuzzer up
- Allocate the PDFDoc on the stack instead of the heap
- Don't install recommended packages

Improve the xpdf pdf fuzzer

---

infra/base-images/base-builder/install_go_CodeIntelligenceTesting.sh

The patched Go version adds a new runtime function `runtime.LibfuzzerInitializeCounters()` to register 8bit counters when initializing the fuzz target. This is needed to register those counters with libFuzzer and get real edge coverage and is implemented in the provided fork. The change is meant to be a temporary change until the Go patches are accepted upstream. Then, we will create a pull request for go114-fuzz-build

Add Code Intelligence go114-fuzz-build fork

---

infra/base-images/base-builder/compile_native_go_fuzzer

Installing the dependencies in the script does not work with go projects that vendor their dependencies. Removing it for now to get the first set of Kubernetes' fuzzers working here: https://github.com/cncf/cncf-fuzzing/pull/92
Removing it from here means that users have to install them themselves. 
It is a bit annoying to do it manually (for now) but it is necessary at this stage to support vendored projects.

native go fuzzing: Remove installation of dependencies

---

projects/flac/fuzzer_exo.cpp

readBuffer returns -1 in return type size_t, which wraps. Because of that, the comparison was not triggering when it should
Credit: Oss-Fuzz
Issue: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=24002

Fix infinite loop in fuzzer_exo

---

projects/ossf-scorecard/Dockerfile
projects/ossf-scorecard/build.sh
projects/ossf-scorecard/yaml_fuzzer.go

Adds the first fuzzer for ossf-scorecard to get the fuzzing started.
@justaugustus @naveensrinivasan

[ossf-scorecard] Add first fuzzer

---

infra/base-images/base-runner/Dockerfile
infra/base-images/base-runner/coverage

Use Go 1.18 beta 2 for base-runner to fix coverage reports.

---

docs/getting-started/new-project-guide/go_lang.md

Due to changes in go-118-fuzz-build, this will no longer be an issue.

native Go fuzzing: Update docs

---

projects/igraph/Dockerfile

This is to finally enable the GraphML reader in igraph, according to the suggestions in #7284

[igraph] install additional dependencies

---

projects/circl/Dockerfile
projects/circl/build.sh
projects/circl/project.yaml

Integration of the Cloudflare open source cryptographic library circl (https://github.com/cloudflare/circl)
OSS-Fuzz team: ask @armfazh any questions you may have about this library.

[circl] Project integration

---

projects/helm/Dockerfile
projects/helm/build.sh
projects/helm/project.yaml

Adds initial integration of Helm. 
Helm is a graduated CNCF-project [[src](https://www.cncf.io/projects/helm/)] and a widely adopted package manager for Kubernetes.
@scottrigby @mattfarina

[helm] Initial integration

---

projects/bitcoin-core/build.sh

Since https://github.com/bitcoin/bitcoin/pull/24301 our Boost usage is header-only.
Enable building sqlite in our dependency builder.

bitcoin-core: remove unused boost cxxflags and enable sqlite

---

projects/icu/project.yaml

Adds Elango Cheran (ICU team member at Google) to the auto_ccs list of

---

projects/libigl/Dockerfile
projects/libigl/build.sh

libigl introduced breaking changes in
https://github.com/libigl/libigl/pull/1805 This fixes the OSS-Fuzz set
up.

libigl: fix build following upstream major update

---

projects/grpc/Dockerfile
projects/grpc/build.sh

Grpc has been broken for half a year or so. The reasons being it (1) relied on an old package repository, (2) used deprecated bazel and commands and (3) referred to files in the upstream repo that no longer exists.

grpc: fix build

---

projects/flac/build.sh

libogg has had a build option to disable crc checking since 2019, but it wasn't used here. This should massively improve fuzzing FLAC-in-ogg

[flac] Disable CRC checks in ogg container

---

projects/serenity/Dockerfile
projects/serenity/build.sh

This replaces the manual CMake invocations, as the project will now
build code generator tools in a first stage build to enable fuzzing
generated code too.
~~Creating as Draft until upstream https://github.com/SerenityOS/serenity/pull/12677 is merged.~~
This PR will fix the serenity build now that 12667 is merged.

serenity: Use in-tree BuildFuzzers.sh script to build fuzz targets

---

projects/libvips/Dockerfile
projects/libvips/build.sh

- Remove unused dependencies.
- Prefer `.git` URLs in git clone invocations.
- Use the `--static` flag of pkg-config for all invocations.
- Remove suspicious `LDFLAGS` environment variable.
- Disable NLS in libexif.
- Make libc++ a private dependency of libheif and libjxl.
- Build libspng with Meson.
- Ninja does not require a `-j` flag.
- Re-order linker flags.

libvips: migrate build to Meson

---

projects/libvips/Dockerfile
projects/libvips/build.sh

Many Rails users will shortly be switching to libvips pdfium load for
PDF rendering. pdfium is well tested and doesn't need fuzzing itself,
but we do need to fuzz the code that links libvips to pdfium.
This PR adds pdfium nightly builds to the libvips fuzzer.

libvips: add pdfium to build

---

infra/build/functions/build_lib.py

Introspector build has no need to use signed url to download coverage reports as the coverage bucket is public.

Avoid using signed url when downloading coverage reports

---

infra/cifuzz/filestore/github_actions/__init__.py
infra/cifuzz/filestore/github_actions/github_actions_test.py
infra/cifuzz/filestore/github_actions/github_api.py
infra/cifuzz/filestore/github_actions/github_api_test.py

Discovered as part of #7324. Artifacts downloading from private repos was likely failing. 
The wrong token was being passed. The correct one is [ACTIONS_RUNTIME_TOKEN](https://github.com/actions/toolkit/blob/fcb8c4ca798bd0d81a9b07e2f7dffee8397c4707/packages/artifact/src/internal/config-variables.ts#L34) (which is undocumented).

Pass the correct token for artifacts downloading.

---

projects/go-coredns/project.yaml

Currently oss-fuzz uses go-coredns as the project name. However,
there is no main_repo in project file, and it looks like
the OSSF's scoreboard will not be able to find the coredns project
from oss-fuzz.
Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

Add main_repo to coredns

---

projects/openvpn/build.sh

Changes upstream caused it to fail. This should be refined down the
line.

openvpn: disable forward fuzzer

---

projects/wasmtime/Dockerfile

This adds some more ocaml-related dependencies to support fuzzing
against a different spec interpreter recently landed in Wasmtime at
https://github.com/bytecodealliance/wasmtime/pull/3843

Update Wasmtime's docker image

---

projects/wasmtime/build.sh

It looks like Wasmtime's fuzzers are failing to run due to them being to
large, so this is a quick band-aid fix to reduce the size of the
binaries. It looks like Rust's `cargo fuzz` tool by default links in
dead code for code coverage purposes (ish, I'm not 100% sure on this),
so the size of fuzzers are reduced by stripping dead code. In a local
build this reduces the size of Wasmtime's output directory from 6.8G to
3.4G and should buy us some time to implement deeper fixes (such as
having one shared library that all of the fuzzers call into instead of
duplicating statically-linked Wasmtime amongst all the fuzzer binaries).

wasmtime: Shrink size of compiled fuzzers

---

infra/base-images/base-builder/compile
infra/base-images/base-clang/Dockerfile

Had to set it at Dockerfile otherwise bazel builds could not see the environment variable.
Also bumping up introspector.

Set ENV in Dockerfile to make it visible to bazel builds

---

projects/wasmtime/Dockerfile
projects/wasmtime/build.sh
projects/wasmtime/differential_spec.options

This uses an OCaml backend and we're getting leak messages from OCaml
which we don't have control over so suppress them for now for this
specific fuzzer.

Ignore leaks in Wasmtime's differential_spec fuzzer

---

projects/wasmtime/Dockerfile
projects/wasmtime/differential_spec.options

This commit takes an alternative approach to #7358 where instead of
specifically ignoring leaks we use a build of OCaml that doesn't have
the leak to begin with. It looks like the leak was introduced in the
4.12 -> 4.13 update (and Wasmtime is currently using the latest of
4.13). This should also help improve reproducibility by always using the
same OCaml version on oss-fuzz runs. We're mostly interested in fuzzing
Rust code, not OCaml code, so our goal is to just get a working OCaml
reference somehow.
---
As an aside I apologize for all the issues/PRs related to Wasmtime recently, I didn't mean to be so noisy! We happened to have a lot of stuff happen at once but I hope that this is one of the last changes needed for our ocaml spec interpreter fuzzer.

Pin Wasmtime's OCaml version to 4.11.2

---

infra/base-images/base-builder/write_labels.py

Joint with https://github.com/google/clusterfuzz/pull/2571 that pulls the wildcard label field into a project labels at setup.
Part of https://github.com/google/oss-fuzz/issues/7318

infra: add handling for a wildcard label applying to all fuzz targets in a project

---

projects/go-coredns/project.yaml

Hi, I am a coredns maintainer (see https://github.com/coredns/coredns/blob/master/CODEOWNERS and https://github.com/yongtang)
and I used to receive oss-fuzz issues through `security@coredns.io`.
Recently I tried to address some of the security issues received, but then I noticed that
I can only access the list with google login. Since security@coredns.io
is a mailing list it will not be possible to login.
So adding my email to this list.
Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

Update coredns with additional auto_ccs

---

projects/go-coredns/project.yaml

I noticed that an alternate email alias in google account does not work
https://github.com/google/oss-fuzz/blob/master/docs/faq.md#why-do-you-require-a-google-account-for-authentication
For that the email has been updated to use the main google email instead.
cc @DavidKorczynski
Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

Update email to use google email (not an alias email)

---

infra/base-images/base-builder/Dockerfile
infra/base-images/base-builder/bazel.bazelrc
infra/base-images/base-builder/bazel_build_fuzz_tests
projects/abseil-cpp/Dockerfile

There is a need to pass environment variables to fuzz introspector -- like where to store the collected profiles. These changes enable bazel based project to build correctly under fuzz introspector.

Pass FuzzIntrospector environment variables to bazel builds

---

projects/igraph/Dockerfile

This is to work around a crash in ICU, see https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=44854 and https://unicode-org.atlassian.net/browse/ICU-21932

[igraph] build libxml2 without ICU

---

infra/base-images/base-runner/coverage

Both the JaCoCo .exec file and the XML report are very useful for
automated analysis of coverage data and IDE integration, so serve them
just like the HTML report.

[infra] Serve raw JaCoCo coverage reports

---

projects/wireshark/build.sh

Pass -DBUILD_fuzzshark=ON to CMake in case upstream disables it by
default.

Wireshark: Explicitly build fuzzshark.

---

projects/wasmtime/build.sh

Our coverage build for Wasmtime has been broken for a bit so this is a
bit of a shot in the dark to try and fix that. The broken build comes
from OCaml sources not being available and I couldn't figure out how to
get the coverage to not ask for the OCaml sources so this attempts to
copy the OCaml sources to the output directory for the coverage code to
use. We're not really interested in the coverage of OCaml itself, but
this should hopefully serve to appease the coverage gods.

wasmtime: Try to fix coverage build

---

projects/pygments/fuzz_guesser.py
projects/pygments/fuzz_lexers.py

- Use atheris.instrument_all(), since pygments uses a custom importer
- Get rid of the useless main(), to make the two fuzzers similar
- Narrow an expected exception type

Modernize a bit the pygments fuzzer

---

infra/base-images/base-builder/install_swift.sh

1. Reduce image size by 1.6GB by deleting unneeded directory containing
swift tools that were already copied to /usr.
2. Use apt-get instead of apt to avoid warnings.

[base-builder-swift] Reduce size 1.6GB and misc improvements

---

projects/gstreamer/Dockerfile

Fixes build error:
./../src/gstreamer/meson.build:1:0: ERROR: Meson version is 0.59.0 but project requires >= 0.60.0
Requires: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/1975
Requires: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/1976
Requires: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/1984

gstreamer: update meson version requirements

---

projects/binutils/fuzz_as.c

macro_init needs to be called.
Ref: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=43790#c2

binutils: fix fuzz_as

---

infra/base-images/base-builder/install_go.sh

A bit more work is required to upgrade to Go 1.18.
#7410

Pin Go back to 1.17

---

infra/build/functions/build_and_run_coverage.py
infra/build/functions/test_data/expected_coverage_build_steps.json

Only upload per-target reports for C/C++.
This reverts commit 1ae57df24d9d0146d6a2486bdb6e01ca7157ccef.

Reland "Upload per target coverage report. (#7389)" (#7400)"

---

docs/advanced-topics/reproducing.md

Issues like https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=45628
aren't always reproducible with libFuzzer so to really trigger them using
the OSS-Fuzz toolchain they should be built and run with engines used to
trigger them originally. `reproduce` supports them now.

docs: drop out-of-date paragraph

---

projects/bitcoin-core/build.sh

* Hopefully fixes the build-failure https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=45852
* Hopefully prepares bitcoin-core (a bit) for Fuzz-Intorspector. For example, it should make debugging https://github.com/ossf/fuzz-introspector/issues/48#issue-1148097528 easier.

bitcoin-core: Rework link stage

---

.github/workflows/infra_tests.yml

This silences a warning when using the action.

Pin setup gcloud action to v0 because master branch is deprecated.

---

projects/lwan/Dockerfile
projects/lwan/project.yaml

GitHub deprecated the unencrypted GIT protocol, so use HTTPS instead.

Lwan: Use HTTPS protocol in GIT repository URI

---

projects/libidn2/Dockerfile
projects/libidn2/build.sh

This should make the libidn2 fussing build again, and also make future debugging of self-check failures easier to perform.

libidn2: Fix build (git-version-gen doesn't handle shallow) and have verbose self checks.

---

projects/elfutils/project.yaml

https://sourceware.org/pipermail/elfutils-devel/2022q1/004784.html
I think it should wait for the other MSan-related PRs to land so that the bogus issues can be closed properly. Though if the flag doesn't affect issues that have already been opened I think it should be good to go.

[elfutils] prevent MSan from reporting issues for now

---

projects/elfutils/build.sh

Closes:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=45647
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=45676
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=45706
It was tested in https://github.com/evverx/elfutils/pull/73
with CFLite. Combined with https://github.com/google/oss-fuzz/pull/7401
it fixes all the issues MSan has reported.

[elfutils] turn off FORTIFY_SOURCE with MSan

---

projects/igraph/project.yaml

No problems or false positives with MSAN, disable experimental mode.

[igraph] disable experimental mode for MSAN

---

projects/elfutils/build.sh

Unlike fuzz-dwfl-core, the new fuzz targets actually use zlib so
instead of just linking against zlib to make them compile they
should use the library instrumented with MSan. Without it OSS-Fuzz
reports bogus issues like https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=45630
and https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=45631.
To hopefully make it easier to figure out how to add new fuzz targets
going forward I also added the following comment to the build script
```
When new fuzz targets are added it usually makes sense to notify the maintainers of
the elfutils project using the mailing list: elfutils-devel@sourceware.org. There
fuzz targets can be reviewed properly (to make sure they don't fail to compile with -Werror
for example), their names can be chosen accordingly …
```

[elfutils] build zlib with MSan

---

projects/libavif/build.sh

It is no longer necessary to use dav1d_oss_fuzz.sh.

libavif: go back to using dav1d.cmd to build dav1d

---

infra/base-images/base-builder/Dockerfile

This reverts commit ba7f8eb9bfd49eba410cef8ae73b2cc4a1ac8cc5.
Need this reverted to have `jsonnet` succeed.

Revert "infra: fuzz-introspector: force no inline (#7413)"

---

projects/elfutils/project.yaml

Now that all the false positives are gone and MSan reports real
issues like https://sourceware.org/bugzilla/show_bug.cgi?id=29000
confirmed by Valgrind it should be safe to bring MSan back.
It reverts https://github.com/google/oss-fuzz/commit/6e6d6068aee8552ff62053b338767a572cf2dc40

[elfutils] bring MSan back

---

projects/cras/build.sh

featured [1] is a ChromeOS specific daemon that's not available in gcr.io/oss-fuzz-base/base-builder-rust.
Disable it to fix the build [2].
[1] https://chromium.googlesource.com/chromiumos/platform2/+/HEAD/featured/
[2] https://crbug.com/oss-fuzz/45744

cras: Disable featured in configure

---

infra/cifuzz/filestore/github_actions/__init__.py
infra/cifuzz/filestore/github_actions/github_actions_test.py
infra/cifuzz/filestore/github_actions/github_api.py
infra/cifuzz/filestore/github_actions/github_api_test.py

This reverts commit 9553ab10d770ef7aeba47829e3e7dbd71dc6af6c.
The commit does the opposite of what was intended.
Here is CFL with the commit: https://github.com/jonathanmetzman/cifuzz-external-example/runs/5726826920?check_suite_focus=true (bad creds)
Here is CFL in a public repo without the commit (works): https://github.com/jonathanmetzman/cifuzz-external-example/runs/5726869794?check_suite_focus=true
Here I made the repo private and without the commit (works): https://github.com/jonathanmetzman/cifuzz-external-example/runs/5727044959?check_suite_focus=true
Fixes: https://github.com/google/clusterfuzzlite/issues/91

Revert "Fix run_fuzzers_test::CoverageReportIntegrationTest. (#7325)"

---

projects/elfutils/build.sh

to make sure all the fuzz targets use the same version of zlib.

[elfutils] always build zlib

---

projects/opensips/patch.diff

OpenSIPS runs on a custom memory allocator, which makes use of a
pre-allocated, large heap chunk, so buffer read overflows are harmless
and allow for some SIP parsing optimizations.
By enabling FUZZ_BUILD for the fuzzer runs, we add extra runtime checks,
so the fuzzer should no longer crash due to ASan detecting
false-positive buffer read overflows in the SIP parser.

opensips: Add support for -DFUZZ_BUILD

---

projects/libarchive/build.sh

Set --enable-static for libxml2. This was set to false by default in a
recent commit

Fix libarchive build.

---

projects/bignum-fuzzer/Dockerfile
projects/cryptofuzz/Dockerfile
projects/ecc-diff-fuzzer/Dockerfile
projects/mbedtls/Dockerfile
projects/mbedtls/project.yaml

Replace references to ARMmbed organisation with the new org, Mbed-TLS, following project migration. The new home
for Mbed TLS is:
https://github.com/Mbed-TLS
Signed-off-by: Dave Rodgman <dave.rodgman@arm.com>

Mbed TLS: update references to old Github org

---

projects/zlib-ng/build.sh
projects/zlib-ng/project.yaml

This PR fixes the broken zlib-ng fuzzing builds in oss-fuzz. 
Now use cmake instead of configure for building fuzzing outputs.
@Dead2

[zlib-ng] build fixes and improvements

---

projects/ngolo-fuzzing/Dockerfile
projects/ngolo-fuzzing/build.sh

So that fixes appear before the next release like https://github.com/golang/go/issues/52035

ngolo-fuzzing: use latest go from git

---

infra/base-images/base-builder/compile
infra/base-images/base-clang/Dockerfile
infra/helper.py
projects/fluent-bit/build.sh
projects/libarchive/build.sh

- removes use of `git_repo_url` from fuzz-introspector
- adds examples of fuzz-introspector configs for excluding project-specific code from analysis
- bumps fuzz-introspector
This supersedes https://github.com/google/oss-fuzz/pull/7494

infra: fuzz-introspector updates and bump

---

projects/tensorflow-py/build.sh

numpy has issues when installing with oss-fuzz flags so am clearing them while installing numpy. Also, removes copying several shared libraries to OUT as they no longer exist.

tensorflow-py: fix build

---

infra/base-images/base-builder/compile

This is to make sure fuzz-introspector can run in local builds.
Ref:
https://github.com/ossf/fuzz-introspector/issues/48#issuecomment-1087513497
Ref:
https://github.com/ossf/fuzz-introspector/issues/67#issuecomment-1087518856

infra: fuzz-introspector: ensure COVERAGE_URL exists

---

infra/base-images/base-runner/coverage

Similar to the main report make all target reports readable. This is
currently a blocker on fuzz-introspector for running locally.

infra: make per-target coverage reports readable

---

projects/xpdf/fuzz_pdfload.cc

Changing the fuzzer logic to go through each stream in the input file and call reset on it. This allows to actually reach `JBIG2Stream::readTextRegionSeg`

Fuzz JBIG2 code by checking on each object in PDF file

---

projects/dnsmasq/fuzz_dhcp.c
projects/dnsmasq/fuzz_header.h
projects/dnsmasq/fuzz_rfc1035.c
projects/dnsmasq/fuzz_util.c
projects/dnsmasq/project.yaml

Some fuzzing failures happen because extract_name always uses in real
dnsmasq code daemon->namebuff of size at least MAXDNAME. Provide long
enough data also to fuzzed functions.

Attempt to fix insufficient extract_name buffer

---

projects/systemd/project.yaml

It should hopefully make it easier to keep track of them.
It was discussed in https://github.com/google/oss-fuzz/issues/7023

[systemd] report OSS-Fuzz bugs on GitHub as well

---

projects/binutils/fuzz_disas_ext.c
projects/binutils/fuzz_disassemble.c

Upstream changed init_disassemble_info
Ref:
https://github.com/bminor/binutils-gdb/commit/60a3da00bd5407f07d64dff82a4dae98230dfaac

binutils: align fuzzers with upstream

---

projects/libjpeg-turbo/Dockerfile
projects/libjpeg-turbo/build.sh

libjpeg-turbo uses a stable mainline branch model, so the main branch is
always stable and feeds into the current release series.  The next-gen
evolving release series is developed in the dev branch, and bug fixes
are cherry-picked into stable branches for past release series.
It is desirable to fuzz the dev branch to ensure that bugs are caught
before the evolving code is merged down into main (which generally
occurs in conjunction with a beta release) and also to allow for the
fuzzers themselves to evolve along with the libjpeg-turbo feature set.
It is also desirable to fuzz the stable branch from the most recent
release series (2.0.x at the moment) to ensure that the same quality is
maintained from when that code occupied the main branch.
Note that both the Dockerfile and multi-branch …

[libjpeg-turbo] Fuzz multiple code branches

---

projects/gstreamer/Dockerfile

Build libvorbis, libogg and libtheora ourselves.  That means we need to
download them though so do that.
Also move the corpus generation to the build script.
Requires: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/2123

gstreamer: rely on less system libriares

---

infra/build/functions/build_and_push_test_images.py
infra/build/functions/build_lib.py

Do this to make trial builds more interactive. By using buildkit caching, we won't need to rebuild every single image when a change is made to the PR.

[trial-builds] Use buildkit caching

---

projects/icu/build.sh

Fuzz-introspector uses LDFLAGS to force linking by way of the gold
linker. We need to use it when linking fuzzers.

icu: set LDFLAGS to fix fuzz-introspector

---

infra/base-images/base-builder/compile

This solves build issues for several projects, including hiredis.

fuzz-introspector: add -lto to ldflags

---

projects/lxml/fuzz_html_parse.py
projects/lxml/fuzz_sax.py

fuzz_html_parse can also throw SerialisationError:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=46579
Forces the fuzzers to catch highest lxml exception for now.

lxml: catch highest exception

---

infra/base-images/base-builder/compile
infra/base-images/base-clang/checkout_build_install_llvm.sh

This fixes various current build failures across projects that use nm as
part of their build process.
Fixes include jansson and apache-httpd, and probably other projects too.

fuzz-introspector: force use of llvm-nm

---

infra/base-images/base-clang/Dockerfile

Main changes in fuzz-introspector:
- reduce logging in fuzz-introspector as some oss-fuzz build logs are
huge.
- insert links in the html reports to the newly added doc.

fuzz-introspector: bump

---

projects/tpm2-tss/build.sh

This way we don't need additional dependencies not needed for fuzz
tests.
Signed-off-by: William Roberts <william.c.roberts@intel.com>

tpm2-tss: disable policy from fuzz

---

projects/cri-o/Dockerfile
projects/cri-o/build.sh
projects/cri-o/project.yaml

This adds initial integration of cri-o. Cri-o is a CNCF-hosted implementation of the Kubernetes Container Runtime Interface and is used as the container runtime on many Kubernetes clusters. cri-o's users include:
* [Red Hat's Openshift Container Platform](https://www.openshift.com/) 
* [SUSE CaaS Platform](https://www.suse.com/products/caas-platform)
* [openSUSE Kubic](https://kubic.opensuse.org)
* [Digital Science](https://www.digital-science.com/) (used by Astra Zeneca, the UK NHS, University of Oxford)
* [HERE Technologies](https://here.com) (handles 100b+ API calls/month)
__________________________________________
@haircommander @saschagrunert for info

[cri-o] Initial integration

---

projects/wasmtime/Dockerfile
projects/wasmtime/build.sh

We are currently (bytecodealliance/wasmtime#3989) switching over to a
new register allocator in Cranelift/wasmtime. This PR switches our
fuzzing setup to start fuzzing the new allocator instead of the old one.

wasmtime: update regalloc fuzzer to use regalloc2.

---

infra/base-images/base-builder/Dockerfile
infra/base-images/base-builder/compile

The use of LDFLAGS does not really follow the policy of OSS-Fuzz. This
moves the linker flags into the sanitizer flags.
Ref:
https://github.com/google/oss-fuzz/issues/7540#issuecomment-1094500094

fuzz-introspector: remove use of LDFLAGS

---

projects/ngolo-fuzzing/build.sh

so that `runtime` gets only patterns from `runtime` and not from `runtime/debug`

ngolo-fuzzing: better exclude pattern

---

projects/spirv-tools/build.sh

The spirv-tool project uses some test cases from the tint project, which
was recently merged with the dawn project. This change updates paths
accordingly.

Fix tint paths in spirv-tools project

---

projects/knot-dns/Dockerfile

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=46482
Inspired by https://github.com/google/oss-fuzz/commit/88ca7c42141f6c99f30724d2179bb26b0fa84d0b

[knot-dns] fix build of the gnutls dependency

---

projects/cosmos-sdk/Dockerfile

cosmos-sdk fuzz tests are being converted to native Go format, but the
base-builder-go-codeintelligencetesting image doesn't have `gotip`.

projects/cosmos-sdk: change base image to base-builder-go for Go 1.18

---

projects/ostree/Dockerfile
projects/ostree/build.sh
projects/ostree/fuzz-bsdiff.c
projects/ostree/fuzz-repo.c
projects/ostree/project.yaml

ostree, aka libostree, is a library for committing and downloading
bootable filesytem trees.
Ostree is used by https://github.com/containers/image which is a library
that's used by https://github.com/cri-o/cri-o which is an implementation
of the Kubernetes container runtime interface
(https://kubernetes.io/blog/2016/12/container-runtime-interface-cri-in-kubernetes/).
In this sense, ostree is library that's used by many Kubernetes
deployments to manage their container runtime.
Integrating this as it's a dependency to Kubernetes components that is
written in C.

ostree: initial integration

---

projects/python3-libraries/build.sh

The purpose of this fuzzer is to find any Python program whose parsing procedure is non-deterministic (for example due to accessing uninitialized memory), which consequently leads to variable execution outcomes. Such a bug can affect bona fide programs, or be harnessed to implement backdoors as seemingly harmless code.
CC @alex @ammaraskar

[python3-libraries] Add AST parser fuzzer

---

infra/base-images/base-clang/checkout_build_install_llvm.sh

This fix makes base-clang work again due to https://github.com/google/oss-fuzz/issues/7617 
Am not sure if it's preferable to merge this -- it's a fix to a problem that (I assume) will be resolved once LLVM is updated

infra: fix base-clang temporarily

---

projects/boringssl/build.sh

BoringSSL is trying to upgrade to C++14. Since that's default for Clang
and GCC for about five years now, just remove the explicit -std flag.
Hopefully that'll save some fuss later on when C++17 is the default
and we want to move there.
https://crbug.com/oss-fuzz/46932

boringssl: Remove -std=c++11

---

infra/base-images/base-runner/coverage

The recently integrated python coverage failed on all projects as far as I can tell. This PR should fix this. Specifically, two fixes:
- coverage reports are put in the right directory (`REPORT_PLATFORM_DIR` instead of `REPORT_ROOT_DIR`)
- in the event a fuzzer fails to generate coverage (e.g. if it exited wrongly) then the coverage logic is discontinued for that particular fuzzer
Ref: https://github.com/google/oss-fuzz/issues/7615

infra: fix python coverage logic

---

infra/base-images/base-builder/compile_python_fuzzer
infra/base-images/base-builder/python_coverage_helper.py
projects/django/build.sh

Enable passing arguments to pyinstaller. This is used by, e.g. Django.
Ref:
https://github.com/google/oss-fuzz/commit/0cb820e5af64f279f66d0c0d3c93b7437ecabe91#commitcomment-72063587

infra: enable argument passing to compile_python_fuzzer

---

projects/envoy/build.sh

Envoy has introduced a temporary http_parser lib (see: https://github.com/envoyproxy/envoy/issues/19749).
This PR adds the files needed for coverage.

envoy: add http_parser external lib coverage

---

projects/gson/build.sh

Removes the `-X` flag to avoid debug logging. I assume it was initially added when the Gson build caused issues, but now the build seems to work reliably so debug logging should probably not be necessary anymore.
Could additionally also specify `--no-transfer-progress` to prevent the log output for all the downloaded Maven artifacts during build, if desired.

Remove Maven debug logging for Gson build

---

infra/build/functions/base_images.py

This was removed when moving project builds to private pools.

Restore machine type for base images.

---

.gitattributes

Resolves partially #7613
Unfortunately this won't cover all Linux shell script files because some seem to have no file extension, e.g. `infra/base-images/base-builder-swift/precompile_swift`.

Add .gitattributes to specify LF as .sh line terminator

---

projects/logback/JoranFuzzer.java

Ignoring class injection as it is an expected behavior: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=47102

logback: update fuzz target to ignore class injection

---

projects/pigweed/build.sh
projects/pigweed/filter_cipd.py

Updates oss-fuzz to correctly parse Pigweed's updated CIPD JSON format
to fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=44445. Also
restores bloaty to the list of required CIPD packages to allow
post-bootstrap checks to pass.

pigweed: Update to new json format

---

projects/ecdsa-python/Dockerfile
projects/ecdsa-python/build.sh
projects/ecdsa-python/fuzz_private_key.py
projects/ecdsa-python/project.yaml

In draft: I have not yet reached out to maintainers about this
Notice,  the set up in this PR uses some of the helper functionality from https://github.com/google/oss-fuzz/pull/7298 which is waiting to be reviewed/merged

ecdsa-python: initial integration

---

projects/json/build.sh

In https://github.com/nlohmann/json/pull/3462 we renamed the folder "test" to "tests".

project json: fix build: adjust tests directory

---

infra/base-images/base-builder/install_python.sh

Upgrade pyinstaller major version. This is needed to pack projects e.g. numpy.

infra: upgrade pyinstaller from 4.1 to 5.0.1

---

projects/flac/build.sh

oss-fuzz has reported numerous signed integer overflow problems in flac that cannot be reasonably fixed. The problem is that flac uses some math that is numerically unstable when fed with random data, and as these are only audio samples, this overflow is not a problem. Therefore, I added `__attribute__((no_sanitize("signed-integer-overflow")))` to a few functions in the flac sources.
However, while a decoder fed with random data has this problem, a decoder that is being used to verify an encoder fed with random data should never overflow. As the same functions are used, the flac sources should be compiled twice: once with the mentioned attributes for the decoder fuzzers, and once without them for the encoder fuzzers.
Note that the define passed in this code is not yet integrated in …

flac: only disable signed integer sanitizing on decoder fuzzers

---

projects/zlib/compress_fuzzer.c
projects/zlib/example_dict_fuzzer.c
projects/zlib/example_flush_fuzzer.c
projects/zlib/example_large_fuzzer.c
projects/zlib/example_small_fuzzer.c
projects/zlib/minigzip_fuzzer.c

When running libFuzzer without fork mode, zlib targets just exit fuzzing on malformed seeds.

Fix zlib - do not exit() from libFuzzer, just return from function

---

projects/llvm/build.sh

clang-pseudo-fuzzer fuzzes clang-pseudo, which is a heuristic parser
based on clang's lexer.
This is a new effort and we'd like to keep it fuzz-clean from the beginning.

[llvm] Add clang-pseudo fuzzer

---

projects/llvm/build.sh
projects/llvm/project.yaml

This generated dictionary consists of keywords and significant punctuation.
It's useful for fuzzers were inputs are C/C++/ObjC source code.
See https://reviews.llvm.org/D125166

[llvm] Generate a dictionary for clang fuzzers.

---

infra/base-images/base-runner/run_fuzzer

The current run_fuzzer will fail when multiple libfuzzer options are
specificed in a .options file. Currently, if there are multiple options
then none of the options will be used, but rather an issue about a
"binary operator expected" will occur. One implication of this is that
check_build fails to use it and may, therefore, report erroneously. This
fixes it by enabling the use of zero, one and many libfuzzer options.

infra: enable run_fuzzer to accept multiple options

---

infra/base-images/base-clang/Dockerfile

This adds a feature where multiple focus functions are output by fuzz-introspector (https://github.com/ossf/fuzz-introspector/pull/252). 
Can confirm the fuzz-introspector oss-fuzz integration tests (https://github.com/ossf/fuzz-introspector/tree/main/oss_fuzz_integration#testing-before-bumping-oss-fuzz) pass.

infra: bump fuzz-introspector

---

projects/xs/Dockerfile
projects/xs/build.sh
projects/xs/xst.options

Adds the XS fuzzer implementation to oss-fuzz.  Tested on debian/x86 infrastructure with the steps located at https://google.github.io/oss-fuzz/getting-started/new-project-guide/

Add XS fuzzer implementation

---

projects/ghostscript/Dockerfile

The latest freetype release adds a new source file, the gs build has been updated to include it, but oss-fuzz was pulling in an old freetype release, so the build failed. We want to use up-to-date code, anyway.

Fix 47322: Build failure - use latest freetype release

---

infra/base-images/base-builder/compile_python_fuzzer

The current implementation will append rather than overwrite
coverage_wrapper.py which holds the coverage stub. The effect of the
appending is that the coverage_wrapper.py will include X amount of
coverage stubs when a project has X amount of fuzzers. We just need a
single coverage stub at the top of each fuzzer. This ensure we only add
a single coverage stub.

infra: fix python coverage

---

projects/bad_example/bad_example_fuzzer.cc
projects/bad_example/build.sh

Makes fuzz-introspector work with the bad_example project. This was
brought up as an issue on the fuzz-introspector repo.
Ref: https://github.com/ossf/fuzz-introspector/issues/257

bad_example: make fuzz-introspector work and fix build

---

infra/build/build_status/update_build_status.py

The length of line causes issues in presubmit checks of https://github.com/google/oss-fuzz/pull/7720 and https://github.com/google/oss-fuzz/pull/7721

infra: reduce length of line to fix CI

---

projects/flac/build.sh

In PR #7687 I tried to add a define by adding it to CFLAGS, but that didn't work without rerunning configure. By adding the define to config.h, rerunning configure is not necessary

Fix addition of define

---

projects/zeek/Dockerfile
projects/zeek/build.sh

The Zeek project recently added a new dependency, which in turn requires us to actually link against the libraries for `flex`. This PR adds the necessary library to the Dockerfile. It also removes a now-deprecated flag from the build, silencing a warning there.

zeek: Add libfl-dev dependency, remove mobile-ipv6 flag

---

infra/base-images/base-builder/compile_python_fuzzer
infra/base-images/base-runner/coverage

Some python coverage reports gets clobbered because non-fuzz targets are
included in FUZZ_TARGETS. The problem is we use a wrapper script to call into python
packages where a package is an executable generated by pyinstaller, and both the script
and the package is executable. Thus, there are two executables per fuzzer -- we should only
have one and it should be the wrapper script. This PR fixes it.

infra: use only valid targets for python coverage

---

infra/build/functions/requirements.txt
infra/cifuzz/requirements.txt

pin the version of `protobuf` to fix infra test errors.

pin the version of protobuf

---

projects/kubeedge/Dockerfile
projects/kubeedge/build.sh
projects/kubeedge/project.yaml

KubeEdge is an open source system for extending native containerized application orchestration capabilities to hosts at Edge. It is a CNCF project that is being used by several large and publicly traded companies in China includig Huawei and Raisecom.
A non-exhaustive list of adopters can be found here: https://github.com/kubeedge/kubeedge/blob/master/ADOPTERS.md
CNCF profile: https://www.cncf.io/projects/kubeedge/

[kubeedge] Initial integration

---

projects/junrar/Dockerfile
projects/junrar/JunrarFuzzer.java
projects/junrar/build.sh
projects/junrar/project.yaml

Adds the [junrar](https://github.com/junrar/junrar) fuzzer implementation to oss-fuzz. Passed testing on ubuntu 18.04 X64 following this [link](https://google.github.io/oss-fuzz/getting-started/new-project-guide/).

Initial integration of Junrar

---

projects/zip4j/Dockerfile
projects/zip4j/Zip4jFuzzer.java
projects/zip4j/build.sh
projects/zip4j/project.yaml

Adds the [zip4j](https://github.com/srikanth-lingala/zip4j) fuzzer implementation to oss-fuzz. Passed testing on ubuntu 18.04 X64 following this [link](https://google.github.io/oss-fuzz/getting-started/new-project-guide/).

initial integration for fuzzing zip4j

---

projects/systemd/project.yaml

https://github.com/systemd/systemd/issues/23532
Since this stuff is fragile I think it would be great if CIFuzz supported i386.

[systemd] turn on i386

---

infra/base-images/base-runner/test_one.py

It should make it easier to figure out why exactly
`./infra/helper.py check_build project fuzz-target` fails
by turning
```
INFO: performing bad build checks for /tmp/not-out/tmpa4lph9dr/fuzz-bus-message
ERROR:root:Check build failed.
```
into something like
```
INFO: performing bad build checks for /tmp/not-out/tmpa4lph9dr/fuzz-bus-message
BAD BUILD: /tmp/not-out/tmpa4lph9dr/fuzz-bus-message seems to have either startup crash or exit:
/tmp/not-out/tmpa4lph9dr/fuzz-bus-message -rss_limit_mb=2560 -timeout=25 -seed=1337 -runs=4 < /dev/null
/tmp/not-out/tmpa4lph9dr/fuzz-bus-message: error while loading shared libraries: libcap.so.2: cannot open shared object file: No such file or directory
ERROR:root:Check build failed.
```

[base-runner] no longer fail silently in test_one.py

---

infra/experimental/sanitizers/ExecSan/Makefile
infra/experimental/sanitizers/ExecSan/execSan.cpp

Send SIGABRT to the root process being fuzzed to generate a stacktrace.
Also distinguish between syscall enter and exit.

Print sanitizer stacktrace for execSan bugs.

---

projects/tensorflow/build.sh

Hi! Current version of tensorflow cannot be built with `-fsanitize=undefined` because of some ubsan reports in `external/nasm`. Here is a fix, I've checked, it works.

[tensorflow] Fix libfuzzer-undefined build.

---

infra/build/functions/build_project.py

Now that Fuzz Introspector is more mature, we can give the builds same amount of time to finish as fuzzing or coverage builds.

Give introspector builds a timeout same as other builds

---

infra/experimental/sanitizers/ExecSan/Makefile
infra/experimental/sanitizers/ExecSan/README.md
infra/experimental/sanitizers/ExecSan/execSan.cpp

Inspect the buffer of the `write` syscalls after `execve` for syntax errors, which is an indicator of potential shell injection

Detect shell injection based on syntax errors

---

projects/ngolo-fuzzing/build.sh

By removing runtime target which times out the whole coverage

ngolo-fuzzing: try to get coverage

---

infra/experimental/sanitizers/ExecSan/README.md
infra/experimental/sanitizers/ExecSan/execSan.cpp
infra/experimental/sanitizers/ExecSan/target.cpp

1. Some error messages from `dash` mismatches with our pattern:
1. Our previous pattern (i.e. `: Syntax error`) is designed to reduce false positives, but it relies on `dash` to print out an error message within one `write` syscall. E.g. `sh: 1: Syntax error: "invalid_command" unexpected`.
2. However, in some cases, `dash` breaks the message into multiple `write` syscalls. E.g. it invokes 2 `writes` whose buffers respectively contain `sh: 1:`, ` Syntax error: "invalid_command" unexpected`.
3. The PR removes the `: ` prefix in our previous pattern to capture case ii and reduce false negatives. 
4. Fix outdated wording.

Execsan syntax error (minor fixes)

---

projects/cosmos-sdk/Dockerfile

The cosmos-sdk fuzz tests have been merged to the main branch in
https://github.com/cosmos/cosmos-sdk/pull/12152
CC @odeke-em

projects/cosmos-sdk: use main branch

---

.allstar/binary_artifacts.yaml

These binaries are necessary and are only run during testing.
Fixes https://github.com/google/oss-fuzz/issues/7802

Opt out of allstar binary artifacts check

---

infra/cifuzz/actions/build_fuzzers/action.yml
infra/cifuzz/base_runner_utils.py
infra/cifuzz/build_fuzzers.py
infra/cifuzz/config_utils.py
infra/cifuzz/continuous_integration.py
infra/cifuzz/docker.py
infra/cifuzz/docker_test.py

to mostly make sure that fuzz targets are buildable with
architecture=i386. Ideally CIFuzz should also download the
latest builds using the "clusterfuzz-builds-i386" links but
it kind of works even without that.
It was tested in https://github.com/evverx/oss-fuzz/pull/13
by pointing https://github.com/evverx/systemd/pull/110 to
that fork of the oss-fuzz repository. To judge from
https://github.com/evverx/systemd/actions/runs/2406321298 it
seems to be working more or less. The "i386" job failed there
because https://github.com/systemd/systemd/commit/89b6a3f13e5f3b8a375dc82cb2a1c2c204a5067e was reverted there to test "i386" as much as possible.

infra: allow passing architecture=i386 to CIFuzz

---

projects/ngolo-fuzzing/build.sh

for instance for image/jpeg which needs DecodeConfig
before Decode is called, otherwise arbitrary allocation is
possible
Will fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=47584

ngolo: applies special patches

---

projects/mergo/project.yaml

imdario/mergo is a merging helper library used by Docker, Kubernetes, Github CLI, etc. According to [Open Source Insights](https://deps.dev/go/github.com%2Fimdario%2Fmergo/v0.3.13/versions), at least 40.000 repositories are using it direct or indirectly.

mergo: initial integration

---

infra/experimental/sanitizers/ExecSan/Makefile
infra/experimental/sanitizers/ExecSan/PoEs/pytorch-lightning-1.5.10/Dockerfile
infra/experimental/sanitizers/ExecSan/PoEs/pytorch-lightning-1.5.10/Makefile
infra/experimental/sanitizers/ExecSan/PoEs/pytorch-lightning-1.5.10/build.sh
infra/experimental/sanitizers/ExecSan/PoEs/pytorch-lightning-1.5.10/fuzz_pytorch_lightning.py
infra/experimental/sanitizers/ExecSan/PoEs/pytorch-lightning-1.5.10/vuln.dict

Show `execSan` can spot a shell injection error in `pytorch-lightning-1.5.10`.
This PoC is extended from [a report in GitHub Advisory Database](https://github.com/advisories/GHSA-r5qj-cvf9-p85h):
The original report documents an exploit using a specific environment variable,
we show a way to achieve the same exploit with an arbitrary env variable.

A PoC of `execSan` with `pytorch-lightning-1.5.10`

---

infra/experimental/sanitizers/ExecSan/execSan.cpp

Replacing `execv` with `execvp` so that it will search in `$PATH` for the binary in the parameter.
This is useful when the binary to execute is not available in the current directory.
This change should not have any other side-effects.

Allow searching for the binary to execute in `$PATH`

---

projects/jsonschema/build.sh

This follows https://github.com/python-jsonschema/jsonschema/pull/965
coverage is only enabled when using `compile_python_fuzzer`

jsonschema: refine build to enable coverage

---

projects/fabric/Dockerfile
projects/fabric/build.sh
projects/fabric/persistence_fuzzer.go
projects/fabric/project.yaml

This PR adds initial integration of Hyperledger Fabric. Hyperledger Fabric is an enterprise-grade permissioned distributed ledger framework for developing solutions and applications. Its modular and versatile design satisfies a broad range of industry use cases. It offers a unique approach to consensus that enables performance at scale while preserving privacy.
It is used by [a number of companies](https://www.hyperledger.org/learn/case-studies), including: 
- Bosch
- Walmart
- Honeywell
- German stock exchange group
- Sony Global Education
____________________________________________________________________
@sykesm @andrew-coleman @bestbeforetoday @lindluni @mastersingh24 Are you interested in integrating Hyperledger Fabric into OSS-fuzz for continuous fuzzing?
This PR adds the build …

Hyperledger Fabric: Initial integration

---

projects/lxc/Dockerfile

By analogy with 8d762775ac3c04f1 it should make it easier
to change the build script when new build dependencies like
meson are introduced.
lxc is switching to meson in https://github.com/lxc/lxc/pull/4142
so it's expected that it should fail to build on OSS-Fuzz.
cc @brauner

[lxc] move apt-gets and pips to the lxc repository

---

projects/apache-commons-codec/Dockerfile
projects/apache-commons-io/Dockerfile
projects/brotli-java/Dockerfile
projects/cbor-java/Dockerfile
projects/gson/Dockerfile
projects/jettison/Dockerfile
projects/jsign/Dockerfile
projects/jul-to-slf4j/Dockerfile
projects/slf4j-api/Dockerfile
projects/snakeyaml/Dockerfile
projects/stringtemplate4/Dockerfile
projects/xstream/Dockerfile
projects/zip4j/Dockerfile

The 3.8.5 is no longer available so project builds are failing for those
in this commit. This fixes it.

java-projects: update maven 3.8.5 to 3.8.6

---

infra/build/functions/base_images.py

This PR fixes a hidden logical error in building introspector images which were causing base-builder:introspector pick up the latest changes with one day delay wrt base-clang:introspector.
The issue was that `docker 
tag gcr.io/oss-fuzz-base/base-clang:introspector gcr.io/oss-fuzz-base/base-clang:latest` is before building the `clang:introspector`
This causes the `base-builder` to have out-dated fuzzintrospector code!
Build Summary
5 Steps
0: gcr.io/cloud-builders/git
clone https://github.com/google/oss-fuzz.git
1: gcr.io/cloud-builders/docker
pull gcr.io/oss-fuzz-base/base-clang:introspector
**2: gcr.io/cloud-builders/docker
tag gcr.io/oss-fuzz-base/base-clang:introspector gcr.io/oss-fuzz-base/base-clang:latest**
3: gcr.io/cloud-builders/docker
build --build-arg introspector=1 -t …

Fix build image steps for introspector

---

projects/dbus-broker/project.yaml

Prompted by https://github.com/bus1/dbus-broker/issues/291
I have a fuzz target targeting the code parsing DBus messages that can trigger all those crashes but I think it should be added once all shallow issues are gone.
cc @dvdhrm @mrc0mmand

[dbus-broker] initial integration

---

projects/croniter/fuzz_iter.py

The Croniter build is having some troubles with coverage and I'm not
entirely sure why. It seems like the corpus is not there and I'm not
entirely sure if this has to do with some instrumentation underlyings.
Locally the end-to-end process of running, collecting seeds and
generating coverage works for me. The effort in this PR is to make the
setup similar to pyyalm where the coverage visualisation works -- the
only difference I could spot between fuzzers from the two projects is
that croniter does not have its fuzzer entry function instrumented.

croniter: instrument fuzzing function

---

infra/base-images/base-runner/run_fuzzer

to make it easier to catch issues like
https://github.com/google/honggfuzz/issues/465.
With -V when unreproducible crashes are triggered honggfuzz shows something like
```
[2022-06-10T15:21:12+0000][W][2373157] subproc_checkTimeLimit():532 pid=2374490 took too much time (limit 30 s). Killing it with SIGKILL
Sz:280 Tm:30,021,052us (i/b/h/e/p/c) New:0/0/0/0/0/3, Cur:0/0/0/0/0/591
Launching verifier for HASH: 1b859677dd (iteration: 1 out of 5)
[2022-06-10T15:21:13+0000][E][2373157] fuzz_runVerifier():280 Verifier stack mismatch: (original) 1b859677dd != (new) 0
```

infra: let honggfuzz verify crashes

---

infra/build/functions/build_and_run_coverage.py

- Propagate changes from #7764 to update `build_lib.download_corpora_steps()`
- Adjust to #7856 by setting `PROJECT_NAME` env var

Set PROJECT_NAME env and update download_corpora_step()

---

projects/binutils/fuzz_dwarf.c
projects/binutils/fuzz_ranlib_simulation.c
projects/binutils/fuzz_windres.c

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=47990 is a leak in project/binutils/fuzz_dwarf.c

Don't leak in binutils test infrastructure

---

projects/grpc-gateway/build.sh

The removed logic is not needed anymore. The build script is simplified in this PR to build the fuzzer with fewer lines of code.

grpc-gateway: refactor

---

projects/openh264/build.sh
projects/openh264/decoder_fuzzer.cpp

att. 
Change the test code to re-enable the fuzzy test for openh264.

fix openh264 folder rename issue

---

projects/dovecot/Dockerfile

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=48089
The error happened due to: https://github.com/dovecot/core/commit/6b0b7141a8a50ffc99ad51b4f27c75f876e58616

dovecot: fix build

---

projects/ruby/build.sh

This will hopefully fix [issue 48193](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=48193). The problem is that it can't find `libruby.so.3.2`, which should be in `$OUT/lib`. I previously used `-rpath` with a relative address, but that won't work if the current directory isn't `$OUT`, which is my best guess as to why the build is failing. If so, `$ORIGIN` should fix it.

Use $ORIGIN in the rpath linker argument

---

projects/xs/Dockerfile
projects/xs/build.sh
projects/xs/target.c

Implements xst_jsonparse target, and closes: #7708 
Tested with
```
python infra/helper.py build_image xs
python infra/helper.py build_fuzzers xs
python infra/helper.py check_build xs
INFO:root:Running: docker run --rm --privileged -i -e FUZZING_ENGINE=libfuzzer -e SANITIZER=address -e ARCHITECTURE=x86_64 -e FUZZING_LANGUAGE=c -v /home/ari/oss-fuzz/build/out/xs:/out -t gcr.io/oss-fuzz-base/base-runner test_all.py.
INFO: performing bad build checks for /tmp/not-out/tmprhip3ypu/xst_jsonparse
INFO: performing bad build checks for /tmp/not-out/tmprhip3ypu/xst
INFO:root:Check build passed.
```
and manually validated a crashing testcase that was fixed, with a previous version of xs using the new wrapper to verify it still crashes when wrapped

XS: implement xst_jsonparse target, and wrap fuzzing binaries

---

projects/sqlalchemy-utils/project.yaml

switch to gmail. From internal discussions with primary contact

sqlalchemy-utils: update primary contact email

---

projects/spdk/Dockerfile

For some reason, there's a local python3 installation on the
oss-fuzz-base image with a pretty old pip version, 19.2.3, which doesn't
have up-to-date wheel platform tags, so, when installing SPDK
dependencies, it tries to compile them instead of using the wheels. The
compilation fails on the grpcio package for some reason.
So, to resolve this, upgrade the local pip version when building the
SPDK image, so that it's able to fetch the pre-compiled packages.  This
is a workaround for #7914.

spdk: upgrade pip

---

projects/xs/Dockerfile
projects/xs/build.sh
projects/xs/target.c

In this PR:
* Fixes coverage builds for all xs targets: fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=48453, failing due to new wrappers
* xst: Introduces seed corpus for js, seeded from test262 parser tests, dictionary for javascript
* xst_jsonparse: Introduces seed corpus for json; dictionary for json
* Comments are fixed in target.c
Tested with:
```
python infra/helper.py build_image --pull xs 
python infra/helper.py build_fuzzers --sanitizer address xs
python infra/helper.py check_build xs
mkdir -p /tmp/corpus1
mkdir -p /tmp/corpus2
python infra/helper.py run_fuzzer --corpus-dir=/tmp/corpus1 xs xst
python infra/helper.py run_fuzzer --corpus-dir=/tmp/corpus2 xs xst_jsonparse
python infra/helper.py build_fuzzers --sanitizer coverage xs
python infra/helper.py coverage xs …
```

fix: XS coverage builds, and add dictionaries and corpus seeds

---

projects/openssl/build.sh

As part of https://github.com/openssl/openssl/pull/18355 "Add Reproducible Error Injection"
I want to add an executable testrun.sh script to the fuzz directory.
Ideally I would like to set the executable bit on that file,
but unfortunately this confuses the CIFuzz build.
This excludes *.sh from the find command in build.sh

openssl: Don't find sh scripts in fuzz directory

---

projects/itoa/Dockerfile
projects/itoa/build.sh
projects/itoa/project.yaml
projects/ryu/Dockerfile
projects/ryu/build.sh
projects/ryu/project.yaml

These two libraries are used by serde_json which, in turn, is used as the
standard JSON parser in various higher level projects. Both itoa and ryu
contain unsafe code, which this fuzzes.

Submit itoa and ryu.

---

projects/harfbuzz/project.yaml

Closes 7919
I need it to check OpenType MATH fuzz stats e.g.
https://github.com/harfbuzz/harfbuzz/issues/3688

Add fwang@igalia.com to HarfBuzz

---

projects/libidn/Dockerfile
projects/libidn/build.sh

This should fix the failing build -- it actually was broken before, but we recently added a self-check to check for this kind of failure (version number errors) and it broke the fuzz build.  I also dropped download of *.po files on every bootstrap...

libidn: fix build.

---

projects/lzo/all_lzo_compress.cc

The compression function appears to account for the possibility that the
buffer contains random values, but msan does not realize that.
Initializing the buffer would be another option, but mere unpoisoning
maintains the ability to detect flaws in the way that the library
handles such uninitialized buffers. (Although, arguably, perhaps this
would be better served by separate fuzzing, which would also make such
findings more reproducible.)
This fixes b/154387018.

lzo: unpoison the working buffer

---

infra/experimental/sanitizers/ExecSan/execSan.cpp

This causes race conditions with stacktrace printing and does not return
the same exit code as the child process.
Just send the SIGABRT and let our tracing handle the exit.

execSan: Don't exit on reporting a bug.

---

projects/flac/build.sh

For the rationale behind adding _FORTIFY_SOURCE=0 see issue #7898

[flac] Add fuzzer_metadata

---

projects/cryptofuzz/build.sh

wolfCrypt uses a a slightly different ECDH algorithm than Trezor and libsecp256k1. This leads to spurious reports like this one https://oss-fuzz.com/testcase-detail/4776022191505408
To prevent these reports, this PR disables running ECDH in libsecp256k1 and Trezor in the `cryptofuzz` project. This is OK because Trezor and libsecp256k1 are tested against each other in the `bitcoin-core` project, so bugs in either library will transpire there.

[cryptofuzz] Disable special ECDH

---

projects/flask/Dockerfile
projects/flask/build.sh

Builds Werkzeug from latest, which is also needed for proper fuzzing.
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=49025

flask: fix build

---

projects/libwebsockets/project.yaml

Google requires the primary_contact is not the alternate email on a google
account.
https://github.com/google/oss-fuzz/issues/7985

projects: libwebsockets: change primary_contact

---

projects/flac/build.sh

Since adding fuzzer_metadata in #7975, there are about ~100 unreproducible crashes each day. I do not encounter these when running that fuzzer on my own device (with the provided images through docker) so I cannot work out what the problem is. However, seeing I had problems with _FORTIFY_SOURCE and MSAN earlier and the combination of _FORTIFY_SOURCE and ASAN can produce weird behaviour, it seems best to force _FORTIFY_SOURCE off for all sanitizers anyway.

[flac] Disable _FORTIFY_SOURCE for all sanitizers

---

infra/cifuzz/continuous_integration_test.py
infra/cifuzz/docker.py
infra/cifuzz/docker_test.py

Unintended consequences of this are it will make debugging harder and it will make it harder to delete these images from disk.
Fixes #7897

[CFL] Give docker images unique names to support parallel fuzzing

---

projects/crossplane/Dockerfile
projects/crossplane/build.sh
projects/crossplane/fuzz.go
projects/crossplane/project.yaml

Crossplane is a framework for building cloud native control planes without needing to write code. It has a highly extensible backend that enables users to build a control plane that can orchestrate applications and infrastructure no matter where they run, and a highly configurable frontend that puts you in control of the schema of the declarative API it offers.
Crossplane is a [CNCF](https://www.cncf.io/) project. It is used by companies like:
- Alibaba
- Redhat
- GitLab
- Microsoft
[[reference](https://crossplane.io/#:~:text=Started%20by%20Upbound%20and%20adopted%20by%20the%20Cloud%20Native%20community)]
____________________________________________________________
@hasheddan @negz @muvaf Are you interested in integrating Crossplane into OSS-fuzz for continuous fuzzing?
This PR adds the …

[crossplane] Initial integration

---

projects/ghostscript/build.sh
projects/ghostscript/gs_device_pdfwrite_fuzzer.cc
projects/ghostscript/gs_device_pgmraw_fuzzer.cc
projects/ghostscript/gs_device_png16m_fuzzer.cc
projects/ghostscript/gs_device_ps2write_fuzzer.cc
projects/ghostscript/gs_device_tiffsep1_fuzzer.cc
projects/ghostscript/gs_fuzzlib.h

Similar to all other devices with exception it writes to file instead of
/dev/null. This is needed because tiff writing requires seek abilities.

ghostscript: add tiff fuzzer

---

projects/git/build.sh
projects/git/project.yaml

Due to upstream changes, the Git fuzzers must now link against
common-main.o; however, this breaks the build in two ways:
1) Linking with common-main.o causes main() to have multiple
definitions, one in common-main.o and one from the fuzzing engine.
2) To avoid #1, the Git Makefile specifically excludes common-main.o
from the fuzzer build rule.
To work around these issues, we can override FUZZ_CXXFLAGS (add
"-Wl,--allow-multiple-definition" to fix #1) and LIB_FUZZING_ENGINE (add
"common-main.o" to fix #2).
Once we can get a Makefile fix into Git's upstream, we can remove the
override for LIB_FUZZING_ENGINE.

git: workaround new requirement to use common-main

---

projects/mosh/Dockerfile
projects/mosh/build.sh

Update Mosh’s `build.sh` to pass appropriate configure options when coverage is requested, as well as to pass `CXXFLAGS` through to the actual build. These fix ClusterFuzz code coverage reports.
Along the way, enable verbose build rules, since they’re useful for debugging build failures.

mosh: fix code coverage

---

projects/g-api-auth-library-python/build.sh
projects/g-api-auth-library-python/fuzz_jwt_roundtrip.py

Split the existing fuzzer. This adds significant speedup in one of the
code areas being tested. Also refines the setup to add more code paths
in the encoding logic.

g-api-auth-library-python: refine set up

---

projects/lcms/build.sh

Current build fails because of the use of linking to dynamically shared libaries in examples of lcms. This conflicts with fuzz introspector and I assume this is because the creation of the dynamically shared libraries makes the lto-compiled objects into binary executables. This fixes it by forcing static linking for all compiled examples in the lcms build process.
I would like to contribute fuzzers to lcms and also use fuzz introspector to assess the current state of lcms fuzzing. This fix is related to that.

lcms: fix fuzz introspector builds

---

projects/istio/Dockerfile

This is required to use the Go 1.18 native fuzzing

istio: switch to standard base-builder-go

---

projects/llvm/project.yaml

I lost access to the Google account associated with my corporate e-mail
address. Switch to using the one I use for contributing to LLVM, which I
should've done from the beginning.

[llvm] Use my commit email address instead of the corp one

---

projects/dbus-broker/Dockerfile
projects/dbus-broker/build.sh
projects/dbus-broker/fuzz-message.c
projects/dbus-broker/project.yaml

Now that https://github.com/bus1/dbus-broker/issues/291 is fixed the fuzz target can be rolled out.
@dvdhrm I haven't added the fuzz target yet (but I got it to build on i386 in the meantime :-)). I wonder if it would make sense to add it now or once `dbus-broker` with that commit included is released? Once the fuzz target is public it can be used to get those dbus messages in a couple of seconds or so.

[dbus-broker] add build script and fuzz target

---

projects/dbus-broker/build.sh

By analogy with https://github.com/google/oss-fuzz/commit/8747524f04b1b906d4a21a6ade87f7803b3f9b8c
it should help to somewhat cover architectures where unaligned access
can either crash code or be too expensive in terms of performance.

[dbus-broker] turn on the alignment check

---

docs/getting-started/continuous_integration.md

GitHub redirects it to the main branch but it keeps saying that
the branch was renamed and it's distracting.

[docs] point to the right systemd branch

---

projects/grok/build.sh

I've changed how my cmake options function, so I need to modify the cmake command for the fuzzer.

[grok] disable full codec and shared libs in cmake command

---

projects/cras/build.sh

When running fuzzers with local source tree,
```
python3 infra/helper.py build_fuzzers --sanitizer address cras
<source_tree>
```
will generate lots of root permission artifacts to local source tree.
Change to out-of-tree build, then
```
python3 infra/helper.py build_fuzzers --clean --sanitizer address cras
<source_tree>
```
could always start from a clean build.

cras: Change to out-of-tree build

---

projects/file/Dockerfile
projects/file/build.sh

This PR adds elf and pe samples to file's corpus. They are the same ones used in the libdwarf and binutils targets.
Fuzz introspector [shows ](https://storage.googleapis.com/oss-fuzz-introspector/file/inspector-report/20220724/fuzz_report.html#Optimal-target-analysis) the file project doesn't have any coverage of elf files.
This is because the current seed corpus uses file's existing test cases, which don't have any elf (or pe) binaries.

file: Add elf and pe seeds

---

projects/wolfssl/build.sh

This reverts https://github.com/google/oss-fuzz/pull/7956 to fix the build again.
That PR was an adjustment to something turned out to be a configuration bug in wolfSSL as explained in https://github.com/wolfSSL/wolfssl/issues/5344

[wolfssl] Fix build

---

projects/g-api-auth-library-python/build.sh
projects/g-api-auth-library-python/fuzz_jwt.py
projects/g-api-auth-library-python/fuzz_jwt_roundtrip.py

This fixes:
https://github.com/google/oss-fuzz/issues/8030#issuecomment-1194645711

g-api-auth-library-python: embed .pem files in pyinstalled exec

---

projects/qemu/default.options

QEMU coverage builds have been failing for a long time. Maybe this is
occuring due to the inputs being too large and timing out. Limit the
input size, in an attempt to fix this.

qemu: limit input size to avoid timeouts

---

projects/wuffs/Dockerfile

Fixes broken build: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=49507
Existing corpus link is no longer accessible. Switching to a reliable source.
Fixing this also to unbreak Fuzz Introspector tests here https://github.com/ossf/fuzz-introspector/issues/412#issuecomment-1195537545

wuffs: fix build by fixing corpus link

---

projects/cras/build.sh

To fix https://crbug.com/oss-fuzz/49371,
passing HAVE_FUZZER flag during library build stage.
And by pass DBus usage in https://crrev.com/c/3787999.
BUG=oss-fuzz:49371

cras: Support -DHAVE_FUZZER

---

projects/pest/project.yaml

Can't access the page with a non-primary Google Account email address, so here's my GA primary.

Switch to primary Google Account email address

---

projects/cras/build.sh
projects/cras/project.yaml

- In oss-fuzz, to build with MemorySanitizer, Rust part needs to use
```
CARGO_BUILD_TARGET="x86_64-unknown-linux-gnu"
```
to resolve libc `MemorySanitizer: use-of-uninitialized-value` error
according to https://github.com/google/oss-fuzz/issues/3469.
- This change will work after https://crrev.com/c/3788003 get merged
- Change builds_per_day to 4
- Add new member to auto_cc

[MSAN] Enable memory sanitizer build

---

projects/hermes/project.yaml
projects/lz4/project.yaml
projects/osquery/project.yaml
projects/proxygen/project.yaml
projects/rocksdb/project.yaml
projects/zstd/project.yaml

I'll no longer be working on fuzzing at Meta, so updating the ownership lists to add more folks from my team.
I added the vendor_cc list where it was missing.
I also removed a few employees that no longer are at Meta from the proxygen project list.

Update ownership of Meta projects.

---

projects/lcms/build.sh
projects/lcms/cms_transform_extended_fuzzer.c

Add a fuzzer that target various output formats when transforming. There
are more oppournities to extend this further but will let this fuzzer
run for a while to see how it goes.

lcms: extend fuzzing suite

---

projects/e2fsprogs/fuzz/ext2fs_check_directory_fuzzer.cc
projects/e2fsprogs/fuzz/ext2fs_image_read_write_fuzzer.cc
projects/e2fsprogs/fuzz/ext2fs_read_bitmap_fuzzer.cc

Move fuzzers to properly use memfd_create. memfd_create doesn't create a file on disk that's reference-able. It can only be accessed by /proc/self/fd/, and it will only have a number. The name is purely for debugging purposes and is also not unique.  Closing it also deletes it, so move the close to the end of the test case.
Also disable checksum fatal errors, making fuzzing a bit easier, and specify random open flags per test case.

Improve e2fsprogs fuzzers 

---

projects/libvips/Dockerfile
projects/libvips/build.sh

- Remove `libgflags-dev`, no longer needed by libjxl.
- Remove CMake options that are already default.
- Split long build options across multiple lines.
- Use the `RelWithDebInfo` build type for CMake builds.
- Use the `debugoptimized` build type for Meson builds (except for libvips itself).
- Avoid using the bundled lcms2 dependency in libjxl.
- Ensure libjxl builds against the static zlib library.
/cc @jcupitt

libvips: build improvements

---

projects/pest/project.yaml

As with https://github.com/google/oss-fuzz/pull/8090 https://github.com/google/oss-fuzz/pull/8097
I cannot access the pages with oss-fuzz bug reports (e.g. links in https://github.com/pest-parser/pest/issues/674).
I am one of maintainers (you can verify my address by checking the recent pest repository git log entries).

pest: Add my Google Account email address

---

projects/libvips/build.sh

This is needed after commit https://chromium.googlesource.com/webm/libwebp/+/3fe15b67737d0b4d436b9af484d890f18f59da79, which builds `libsharpyuv` as a separate installable library rather than a convenience one.

libvips: add missing linker flag for sharpyuv

---

infra/experimental/sanitizers/ExecSan/Makefile
infra/experimental/sanitizers/ExecSan/execSan.cpp
infra/experimental/sanitizers/ExecSan/target.cpp
infra/experimental/sanitizers/ExecSan/target_file.cpp
infra/experimental/sanitizers/ExecSan/vuln.dict

execscan: detect arbitrary file open

---

projects/cloud-hypervisor/build.sh

New fuzzers for the cmos and serial devices along with fuzzing of the
http API frontend have been added.
Signed-off-by: Rob Bradford <robert.bradford@intel.com>

cloud-hypervisor: Add newly added fuzzers

---

infra/base-images/base-runner-debug/Dockerfile

This will speed up trial builds noticeably as well.

Reduce base-builder-debug build time from 18 to 2 minutes

---

projects/iniconfig/fuzz_parse.py

The file operations had issues with file not found. This will trigger the same parsing routines but without file operations.
Fixes: https://github.com/pytest-dev/iniconfig/issues/41

iniconfig: fix fuzzer

---

projects/libwebp/build.sh

Fixes build after:
a3b68c19 Build libsharpyuv as a full installable library.
Bug: oss-fuzz:49778

libwebp: add libsharpyuv to link line

---

projects/e2fsprogs/fuzz/ext2fs_image_read_write_fuzzer.cc
projects/e2fsprogs/fuzz/ext2fs_read_bitmap_fuzzer.cc
projects/e2fsprogs/project.yaml

Add myself to auto_ccs and remove usage of EXT2_FLAG_NOFREE_ON_ERROR.
EXT2_FLAG_NOFREE_ON_ERROR leads to lots of memory leaks. Not necessary to file issues for these.

Add myself to auto_ccs and remove usage of EXT2_FLAG_NOFREE_ON_ERROR

---

projects/libvips/build.sh

This reverts commit https://github.com/google/oss-fuzz/commit/912251824c51541ec0bc2085612e5463e1e68429, which was introduced in PR https://github.com/google/oss-fuzz/pull/6845.
See: https://github.com/libjxl/libjxl/issues/858#issuecomment-1200389177.

libvips: enable the SSSE3 target

---

docs/getting-started/new-project-guide/go_lang.md

Suggested in https://github.com/google/oss-fuzz/pull/7906#issuecomment-1204104081.
Credit to @hickford for suggesting this addition.

Docs: Add info about golang dependencies

---

projects/e2fsprogs/fuzz/ext2fs_image_read_write_fuzzer.cc
projects/e2fsprogs/fuzz/ext2fs_read_bitmap_fuzzer.cc

Keep the consumeInt such that the existing corpus still works exactly. This also ensures that open bugs still repro with the latest fuzzers.

Small change to maintain the existing corpus

---

projects/dropbear/Dockerfile
projects/dropbear/build.sh

The corpus repository seems to not be available anymore which breaks the whole build.

dropbear: fix broken build

---

infra/base-images/base-builder/Dockerfile
infra/constants.py

Note that these targets still fail immediately.
Related: #8164

[Incomplete] Support building targets with HWAsan

---

projects/cloud-hypervisor/project.yaml

I am one of the main contributors/committers to the Cloud Hypervisor (CH) project, and would like to have access to the ClusterFuzz website interface for the statistics of fuzzing CH.
\cc @rbradford @sboeuf
Signed-off-by: Bo Chen <chen.bo@intel.com>

[cloud-hypervisor] Add @likebreath to auto_ccs list

---

projects/nghttp2/Dockerfile
projects/nghttp2/build.sh

Keeping this in draft until upstream PR is reviewed, some things will have to change once the upstream PR is merged.

nghttp2: update build to fit new fuzzer

---

projects/flask/fuzz_env_jinja_lexer.py
projects/flask/fuzz_jinja_compile_expr.py
projects/flask/fuzz_werkzeug_http.py

Extends fuzzing by catching more exceptions that seem to be irrelevant. This closes various issues found and lets the fuzzers focus more on flask/jinja/werkzeug specific code.

flask: extend fuzzing

---

projects/oak/Dockerfile

Our builds and coverage often fail because of a mismatch between the rust version that Oak supports, and the latest nightly version that is installed in the `base-builder-rust` image. This PR fixes the [rust version to the one that we currently support for Oak](https://github.com/project-oak/oak/blob/f9ddfa82dd9fc2717accb11abceea68683d043eb/Dockerfile#L198-L226).

Oak: Use the same version of rust the we use internally

---

projects/fluent-bit/Dockerfile

fluent-bit is transitioning from mbedtls to openssl making the latter mandatory and completely remove the former.
Signed-off-by: Leonardo Alminana <leonardo@calyptia.com>

fluent-bit: added dependency (openssl)

---

projects/fluxcd/project.yaml

Updating contact details based on current members of the Flux Security Team:
https://github.com/fluxcd/.github/blob/main/SECURITY.md#security-team
cc: @stefanprodan @hiddeco @scottrigby @squaremo

fluxcd: Update Flux Security Team details

---

projects/ghostscript/build.sh
projects/ghostscript/gs_device_eps2write_fuzzer.cc

eps2write is one of the high-level devices currently not targeted by the
fuzzing suite. This adds a fuzzer for this high-level device.

ghostscript: extend with eps2write device fuzzer

---

infra/base-images/base-builder/compile_native_go_fuzzer

Projects containing words starting with Fuzz in non-go files break `compile_native_go_fuzzer` with the error:
`sed: -e expression #1, char 15: unknown option to 's'`

native go fuzzing: Restrict fuzzer lookup to `*.go`

---

infra/base-images/base-builder/install_java.sh

All latest builds seem to be broken with:
```
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
INFO: Loaded 112 hooks from com.code_intelligence.jazzer.runtime.TraceCmpHooks
INFO: Loaded 4 hooks from com.code_intelligence.jazzer.runtime.TraceDivHooks
INFO: Loaded 2 hooks from com.code_intelligence.jazzer.runtime.TraceIndirHooks
INFO: Loaded 4 hooks from com.code_intelligence.jazzer.runtime.NativeLibHooks
INFO: Loaded 8 hooks from com.code_intelligence.jazzer.sanitizers.Deserialization
INFO: Loaded 5 hooks from com.code_intelligence.jazzer.sanitizers.ExpressionLanguageInjection
INFO: Loaded 70 hooks from com.code_intelligence.jazzer.sanitizers.LdapInjection
INFO: Loaded 46 hooks from …
```

Pin Jazzer to older revision

---

docs/getting-started/new-project-guide/rust_lang.md
projects/cryptofuzz/README.md

docs/getting-started/new-project-guide/rust_lang.md:132: depedencies ==> dependencies
projects/cryptofuzz/README.md:12: seperate ==> separate

Fix typos in rust_lang.md and cryptofuzz readme

---

projects/oak/Dockerfile

Follow up on #8217. This makes the paths consistent with those in the base image.

Oak: Fix paths in Dockerfile

---

projects/tomcat/Http11ProcessorDefaultServletFuzzer.java

Sorry I made a dumb mistake in my fuzz target, there should be no FuzzerSecurityIssueHigh thrown after catching the IOException. 
Sorry again for my mistake.
Thank you!

Tomcat: Delete unnecessary code.

---

projects/burntsushi-toml/fuzz.go

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=50415
- Adds early return on too big fuzz test case

burntsushi-toml: Fixes out-of-memory crash
