google/oss-fuzz

infra/build/functions/base_images.py

Replace use of sed with docker tag

---

docs/getting-started/new_project_guide.md

Fixes: https://github.com/google/oss-fuzz/issues/7421
Related: https://github.com/google/oss-fuzz/issues/2746

Mention i386 false positives.

---

.github/workflows/infra_tests.yml
.github/workflows/presubmit.yml
.github/workflows/project_tests.yml

Fix permissions on Github Actions jobs

---

infra/ci/build.py
projects/elfutils/project.yaml

Fixes: https://github.com/google/oss-fuzz/issues/7432

Make CI build experimental jobs.

---

projects/django/build.sh

This fixes https://oss-fuzz.com/testcase-detail/6112062398398464

[django] Fixed pyinstaller creation to include neccessary translations.

---

projects/nettle/project.yaml

This fuzzer works fine with MSAN.

[Nettle] Enable MSAN

---

projects/bitcoin-core/build.sh

Hopefully fixes the bitcoin-core msan oss-fuzz issue reports.

bitcoin-core: Fix msan

---

infra/base-images/base-clang/Dockerfile

Following fix of https://github.com/ossf/fuzz-introspector/issues/154

infra: bump fuzz-introspector

---

projects/xpdf/fuzz_pdfload.cc

Adding fuzz target to exercise JBIG2 code.

Fuzzing for JBIG2 streams

---

projects/libspng/Dockerfile

Update zlib URL

---

docs/getting-started/new_project_guide.md

Fix link in new_project_guide.md

---

infra/base-images/base-builder/install_java.sh

Pin Jazzer to older revision.

---

projects/opensk/project.yaml

Add OpenSK member

---

projects/exiv2/project.yaml

@piponazo is one of the main contributors/maintainers of Exiv2, and would like to be added to the notify list for Exiv2.

Add @piponazo to Exiv2 auto_ccs

---

projects/woodstox/Dockerfile
projects/woodstox/XmlFuzzer.java
projects/woodstox/build.sh
projects/woodstox/project.yaml

[woodstox] Initial Integration

---

infra/repo_manager.py

This fix includes a few updates for infra/repo_manager.py:
* Add step for updating submodules while commit checkout
* Add step for updating submodules while PR checkout
Fixes #7493

Consider submodules while commit and PR checkout

---

projects/lxml/Dockerfile
projects/lxml/build.sh
projects/lxml/fuzz_xml_parse.py
projects/lxml/project.yaml

This integrates the lxml library.
lxml generates a substantial amount of native code during compilation

lxml: initial integration.

---

projects/joda-time/Dockerfile
projects/joda-time/TimeFuzzer.java
projects/joda-time/build.sh
projects/joda-time/project.yaml

Initial integration for [joda-time](https://github.com/JodaOrg/joda-time). @oliverchang @kyakdan

joda-time integration

---

projects/jettison/Dockerfile
projects/jettison/JsonFuzzer.java
projects/jettison/build.sh
projects/jettison/project.yaml

Initial integration for Jettison. @kyakdan @oliverchang

[jettison] initial integration

---

projects/aiohttp/Dockerfile
projects/aiohttp/build.sh
projects/aiohttp/fuzz_http_parser.py
projects/aiohttp/fuzz_payload_url.py
projects/aiohttp/project.yaml

Integration of the aiohttp parser: https://github.com/aio-libs/aiohttp
Waiting for upstream.

aiohttp: initial integration.

---

projects/protobuf-python/Dockerfile
projects/protobuf-python/build.sh
projects/protobuf-python/fuzz_protobuf.py
projects/protobuf-python/project.yaml

@acozzette Would you be interested in getting the python-protobuf fuzzed? This PR sets up an initial integration and we could expand with more fuzzers down the line if you're happy with integrating.

python-protobuf: initial integration

---

projects/libbpf/project.yaml

to hopefully make it easier to keep track of them.

[libbpf] report bugs on GitHub and make them public by default

---

infra/build/build_status/update_build_status.py

It made sense to have this logic where build status is being checked.

Generate an index of successful projects for introspector

---

projects/xpdf/Dockerfile
projects/xpdf/build.sh

Had to update Dockerfile and build.sh to copy fuzz_JBIG2.options

Copy around options

---

infra/build/build_status/update_build_status.py

Regarding https://github.com/google/oss-fuzz/issues/7552

log an error instead of raising an exception if log file missing

---

projects/libbpf/project.yaml

https://github.com/libbpf/libbpf/issues/478#issuecomment-1097587752

[libbpf] add more libbpf contributors

---

projects/logback/Dockerfile
projects/logback/JoranFuzzer.java
projects/logback/build.sh
projects/logback/logback.xml
projects/logback/project.yaml

Initial integration for logback. @kyakdan @oliverchang

logback: Initial integration

---

projects/llhttp/build.sh

This will shorten the build time and make it compatible with fuzz-introspector builds.

llhttp: refine build

---

projects/hdrhistogram/Dockerfile
projects/hdrhistogram/LogReaderWriterFuzzer.java
projects/hdrhistogram/build.sh
projects/hdrhistogram/project.yaml

[hdrhistogram] Initial Integration

---

projects/libusb/Dockerfile

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=45925

libusb: fix build

---

projects/gnutls/Dockerfile

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=46480

gnutls: fix build

---

projects/wget/Dockerfile
projects/wget2/Dockerfile

Fixes:
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=46501
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=46485

wget, wget2: fix builds

---

projects/teleport/project.yaml

**What is the purpose of this pull request? (put an "X" next to item)**
[ ] Documentation update
[ ] Bug fix
[ ] New feature
[X] Other, please explain: Project contact updates
**What changes did you make? (Give an overview)**
Updating the contacts for the teleport project
**Which issue (if any) does this pull request address?**
N/A
**Is there anything you'd like reviewers to focus on?**
Nope

Update contacts for teleport

---

projects/snakeyaml/Dockerfile
projects/snakeyaml/YamlFuzzer.java
projects/snakeyaml/build.sh
projects/snakeyaml/project.yaml

[snakeyaml] initial integration

---

projects/javassist/ClassFuzzer.java
projects/javassist/Dockerfile
projects/javassist/build.sh
projects/javassist/project.yaml

[javassist] Initial Integration

---

projects/jackson-databind/Dockerfile
projects/jackson-databind/ObjectReaderFuzzer.java
projects/jackson-databind/build.sh
projects/jackson-databind/project.yaml

jackson-databind: Initial integration

---

projects/xmlpull/Dockerfile
projects/xmlpull/XmlFuzzer.java
projects/xmlpull/build.sh
projects/xmlpull/project.yaml

xmlpull: Initial integration

---

projects/apache-commons-jxpath/Dockerfile
projects/apache-commons-jxpath/JXPathFuzzer.java
projects/apache-commons-jxpath/build.sh
projects/apache-commons-jxpath/project.yaml

[apache-commons-jxpath] Initial Integration

---

projects/apache-commons-io/Dockerfile
projects/apache-commons-io/InputXmlFuzzer.java
projects/apache-commons-io/build.sh
projects/apache-commons-io/project.yaml

Have not heard back from maintainers yet, but will update when we do if needed. @kyakdan @oliverchang

[apache-commons-io] initial integration.

---

projects/apache-commons-codec/BinaryEncodingFuzzer.java
projects/apache-commons-codec/Dockerfile
projects/apache-commons-codec/build.sh
projects/apache-commons-codec/project.yaml

[apache-commons-codec] initial integration

---

projects/apache-commons-lang/Dockerfile
projects/apache-commons-lang/EscapeHtmlFuzzer.java
projects/apache-commons-lang/StringEscapeUtilsFuzzer.java
projects/apache-commons-lang/build.sh
projects/apache-commons-lang/project.yaml

apache-commons-lang: Initial integration

---

infra/base-images/base-clang/Dockerfile

Fixes https://github.com/google/oss-fuzz/issues/7635

fuzz-introspector: bump

---

projects/flask/fuzz_env_jinja_lexer.py
projects/flask/fuzz_werkzeug_url.py

jinja and werkzeug previous initial integration suggestions.
Ref: https://github.com/google/oss-fuzz/pull/4761
Ref: https://github.com/google/oss-fuzz/pull/4998

flask: migrate fuzzers from previous PRs

---

projects/flac/build.sh

See https://github.com/xiph/flac/commit/b52734242e2b2e4c69441392189c3eb97389aa64

flac: Add second (more thorough) encoder fuzzer

---

projects/urllib3/project.yaml

This is following discusisons in Ref: https://github.com/google/oss-fuzz/pull/7645

urllib3: set myself as primary contact

---

projects/ngolo-fuzzing/build.sh

Will solve Fps like https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=46174

ngolo-fuzzing: more generic arguments for fuzz targets building

---

projects/jsign/AuthenticodeCabSignerFuzzer.java
projects/jsign/AuthenticodeExeSignerFuzzer.java
projects/jsign/AuthenticodeMsiSignerFuzzer.java
projects/jsign/Dockerfile
projects/jsign/build.sh

jsign: fuzzing for exe, msi and cab files

---

infra/base-images/base-runner/coverage

The python coverage has not started working on oss-fuzz.com yet. This is
an effort to fix this.
Build logs all say the same:
pyyaml: https://oss-fuzz-build-logs.storage.googleapis.com/log-c07c6460-d36e-4e45-9859-6167fa24092d.txt
```
- [36/36 files][  3.4 MiB/  3.4 MiB] 100% Done                                  
Step #7: Operation completed over 36 objects/3.4 MiB.                                     
Finished Step #7
Starting Step #8
Step #8: Already have image (with digest): gcr.io/cloud-builders/gsutil
Step #8: CommandException: 1 files/objects could not be removed.
Finished Step #8
Starting Step #9
Step #9: Already have image (with digest): gcr.io/cloud-builders/gsutil
Step #9: CommandException: No URLs matched. Do the files you're operating on exist?
Finished Step #9
```
lxml: …

infra: fix python coverage

---

projects/abseil-cpp/WORKSPACE

Signed-off-by: Piotr Sikora <piotrsikora@google.com>

[abseil-cpp] Add missing @bazel_skylib dependency.

---

projects/flask/fuzz_werkzeug_formparser.py
projects/flask/fuzz_werkzeug_url.py

Following the addition of coverage visualisation it's now easier to
detect missing pieces. This extends flask fuzzing to cover missing
areas. A nice next step in flask fuzzing is to create more end-to-end
fuzzers.

flask: extend fuzzers

---

projects/ngolo-fuzzing/build.sh

With the fuzz targets which work already.
The LPM fuzz targets do not support coverage yet...

ngolo-fuzzing get some coverage

---

projects/requests/Dockerfile
projects/requests/build.sh
projects/requests/fuzz_server.py
projects/requests/project.yaml

Need to move the fuzz target to the upstream repository

Adds python project requests

---

projects/cbor-java/Dockerfile
projects/cbor-java/FuzzDec.java
projects/cbor-java/build.sh
projects/cbor-java/project.yaml

Integrating cbor-java. I mainly integrated this because it's part of the external libraries on the Android platform (https://android.googlesource.com/platform/external/cbor-java)

cbor-java: initial integration

---

projects/nfstream/project.yaml

This PR is at add NFStream project. (https://github.com/nfstream/nfstream)
If accepted, I will add requirements following your provided documentation.
Best regards,
Zied

Add NFStream project.

---

projects/xstream/Dockerfile
projects/xstream/XmlFuzzer.java
projects/xstream/build.sh
projects/xstream/project.yaml

@kyakdan @oliverchang 
Maintainer of xstream is currently too busy to handle any discovered bugs.

Initial integration files for xstream

---

projects/slf4j-api/Dockerfile
projects/slf4j-api/LoggingFuzzer.java
projects/slf4j-api/build.sh
projects/slf4j-api/project.yaml

[slf4j-api] initial integration

---

projects/ngolo-fuzzing/build.sh

ngolo-fuzzing: fix coverage build

---

projects/qt/Dockerfile

To actually test it, changes in the build script are needed.

[qt] Clone qtimageformats

---

projects/config-validator/Dockerfile
projects/dgraph/Dockerfile
projects/dragonfly/Dockerfile
projects/etcd/Dockerfile
projects/fluxcd/Dockerfile
projects/go-sqlite3/Dockerfile
projects/hcl/Dockerfile
projects/lotus/Dockerfile
projects/prometheus/Dockerfile
projects/protoreflect/Dockerfile
projects/quic-go/Dockerfile
projects/syzkaller/Dockerfile
projects/teleport/Dockerfile

add base-builder-go-codeintelligencetesting for next 13 projects

---

projects/jul-to-slf4j/BridgeFuzzer.java
projects/jul-to-slf4j/Dockerfile
projects/jul-to-slf4j/build.sh
projects/jul-to-slf4j/project.yaml

[jul-to-slf4j] initial integration

---

projects/xs/project.yaml

Hello oss-fuzz team!
This PR introduces a project spec for fuzzing Moddable's XS JavaScript engine.  The XS JavaScript engine implements the [2021 JavaScript language standard](http://www.ecma-international.org/ecma-262/11.0/index.html) with better than 99% conformance, and is primarily designed to run on microcontrollers. [[1](https://github.com/Moddable-OpenSource/moddable#footnotes)]  This engine is also used as the core runtime for the Agoric blockchain, where developers can create smart contracts in JavaScript.
Agoric and Moddable have already integrated another fuzzer (fuzzilli) as well, however this integration is targeting the libFuzzer integration.   If there is a way to also add on fuzzilli down the road, that would be cool. 😄 
Once the fuzzing harness is in the public branch of …

Introduce Moddable XS as a fuzzing target

---

infra/helper.py
infra/helper_test.py

Fixes https://github.com/google/clusterfuzzlite/issues/98

[CFL] Handle project language properly

---

projects/opendnp3/Dockerfile
projects/opendnp3/build.sh

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=47296
Following https://github.com/dnp3/opendnp3/pull/444

opendnp3: fix build

---

projects/tensorflow/build.sh

Hi! We added new targets for Tensorflow from `tensorflow/core/kernels/fuzzing`, which we tried to build earlier here tensorflow/tensorflow#55183, discussing it with @mihaimaruseac.

[tensorflow] New fuzzing targets from core/kernels/fuzzing

---

projects/wazuh/build.sh
projects/wazuh/fuzz_xml.c

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=47414

wazuh: fix build

---

projects/flask/cors_fuzz_flask.py

We must ensure proper thread exit in coverage mode. We do this by
counting how many seeds are left.

flask: fix flask_cors coverage

---

projects/libgit2/build.sh

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=46031

libgit2: fix build

---

projects/flask/project.yaml

flask: add vendor ccs

---

projects/dovecot/Dockerfile

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=47556

dovecot: fix build

---

projects/boringssl/build.sh
projects/giflib/build.sh
projects/jsoncpp/build.sh
projects/libpng-proto/build.sh
projects/nginx/make_fuzzers
projects/xerces-c/build.sh

Ref: https://github.com/google/oss-fuzz/issues/7736

libprotobuf-mutator projects: fix builds

---

projects/cel-go/build.sh

Ref: https://github.com/google/oss-fuzz/issues/7736

cel-go: fix libprotobuf-mutator

---

projects/jsign/AuthenticodeCabSignerFuzzer.java
projects/jsign/AuthenticodeExeSignerFuzzer.java
projects/jsign/AuthenticodeMsiSignerFuzzer.java

This fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=47229

jsign: load the keystore from the classpath

---

projects/libvips/build.sh

libvips: enable WebP/JPEG support in libtiff

---

projects/pyxdg/build.sh
projects/pyxdg/fuzz_desktop_entry.py
projects/pyxdg/fuzz_icon.py
projects/pyxdg/fuzz_mime.py

Adds 3 new fuzzers and build pyxdg by way of pip3 install rather than
python3 setup.py

pyxdg: refine build and extend fuzzers

---

projects/airflow/Dockerfile
projects/airflow/build.sh
projects/airflow/dag_fuzz.py
projects/airflow/project.yaml

airflow-py: initial integration

---

projects/ansible/Dockerfile
projects/ansible/build.sh
projects/ansible/parse_fuzz.py
projects/ansible/playtask_fuzz.py
projects/ansible/project.yaml
projects/ansible/task_fuzz.py

ansible: initial integration

---

projects/gdk-pixbuf/build.sh

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=47473

gdk-pixbuf: fix build

---

projects/tomcat/Dockerfile
projects/tomcat/HttpParserFuzzer.java
projects/tomcat/build.sh
projects/tomcat/project.yaml

Initial integration of Apache Tomcat.

Tomcat: initial integration

---

projects/janet/build.sh

Following
https://github.com/janet-lang/janet/commit/c9f33bbde03b804e8a62d0d90e4f56307347124f

janet: fix build

---

projects/envoy/project.yaml

Updating the Envoy project members list.
cc @alyssawilk
@asraa LMK if you wish to also be removed from the list.

envoy: updating members list

---

projects/tensorflow-py/project.yaml
projects/tensorflow/project.yaml

Since I left TF, moving to primary another person in TF Security team. Also adding another TF Security team member to CC, as well as myself.
Will probably send new updates as new members join :)

Update TensorFlow emails (for both projects)

---

infra/build/functions/build_lib.py

[infra] Increase build timeout.

---

projects/ansible/build.sh

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=47849

ansible: fix build

---

projects/jul-to-slf4j/Dockerfile

Ref: https://github.com/google/oss-fuzz/commit/3d1858edb22ae1a7e51c81d867553439d607b891#commitcomment-76137646

jul-to-slf4j: fix build

---

infra/base-images/base-runner/run_fuzzer

Revert "infra: let honggfuzz verify crashes"

---

infra/base-images/base-runner-debug/Dockerfile

Install gdb 12 from source

---

projects/apache-commons-configuration/Dockerfile
projects/apache-commons-configuration/INIConfigurationReadFuzzer.java
projects/apache-commons-configuration/INIConfigurationWriteFuzzer.java
projects/apache-commons-configuration/JSONConfigurationReadFuzzer.java
projects/apache-commons-configuration/JSONConfigurationWriteFuzzer.java
projects/apache-commons-configuration/XMLConfigurationLoadFuzzer.java
projects/apache-commons-configuration/YAMLConfigurationReadFuzzer.java
projects/apache-commons-configuration/YAMLConfigurationWriteFuzzer.java
projects/apache-commons-configuration/build.sh
projects/apache-commons-configuration/ini.dict
projects/apache-commons-configuration/project.yaml

Added fuzz targets for apache-commons-configuration

apache-commons-configuration: initial integration

---

projects/bc-java/CMSEnvelopedDataParserFuzzer.java
projects/bc-java/Dockerfile
projects/bc-java/EncodingFuzzer.java
projects/bc-java/build.sh
projects/bc-java/project.yaml

[bc-java] initial commit

---

projects/gonids/Dockerfile
projects/gonids/build.sh

cf https://github.com/golang/go/issues/49075
Try to git bisect this unreproducible bug
@AdamKorcz can this be merged to get the commit responsible for https://github.com/golang/go/issues/49075 ?

gonids: recompile go to hunt bug

---

projects/kimageformats/Dockerfile

These are merely just new versions of dependencies.

kimageformats: upgrade libaom and libavif

---

projects/sqlalchemy_jsonfield/Dockerfile
projects/sqlalchemy_jsonfield/build.sh
projects/sqlalchemy_jsonfield/fuzz_basic.py
projects/sqlalchemy_jsonfield/project.yaml

sqlalchemy_jsonfield: initial integration

---

projects/rocksdb/build.sh

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=48489

rocksdb: build with c++17

---

projects/ftfy/Dockerfile
projects/ftfy/build.sh
projects/ftfy/fuzz_fix.py
projects/ftfy/fuzz_format.py
projects/ftfy/project.yaml

- Create initial integration
- Add fuzzer for fixing function
- Add fuzzer for formatting function

python ftfy: initial integration

---

projects/gonids/build.sh

Getting closer on https://github.com/golang/go/issues/49075 (10 commits left to bisect)
Will fix build failure during the first 5 days
cc @AdamKorcz

gonids: fix off by one in git bisect logic

---

projects/numpy/Dockerfile
projects/numpy/build.sh
projects/numpy/fuzz_loader.py
projects/numpy/project.yaml

Initial integration of numpy. Thread on the numpy mailing list discussing integrating with OSS-Fuzz https://mail.python.org/archives/list/numpy-discussion@python.org/thread/MR2BKUFZMGIB7IJOK4ME7Q46VUVEV3BT/

numpy: initial integration

---

projects/libwebsockets/project.yaml

As suggested on https://github.com/warmcat/libwebsockets/issues/2687 I'd
like to add lws to oss-fuzz.

projects: add libwebsockets

---

infra/constants.py
infra/helper.py

Remove dataflow support from helper.py

---

projects/flac/project.yaml

Maintenance has been picked up by the FLAC maintainer so I no longer need to receive bug reports.

[flac] Remove myself from project

---

projects/libphonenumber/build.sh

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=48949

libphonenumber: fix build

---

infra/build/functions/build_and_run_coverage.py
infra/build/functions/build_lib.py
infra/build/functions/build_project.py

Remove build-infra support for DFSan.

---

projects/g-api-py-api-common-protos/Dockerfile
projects/g-api-py-api-common-protos/build.sh
projects/g-api-py-api-common-protos/fuzz_api.py
projects/g-api-py-api-common-protos/project.yaml

Initial integration of https://github.com/googleapis/python-api-common-protos

g-api-py-api-common-protos: initial integration

---

projects/g-api-python-client/Dockerfile
projects/g-api-python-client/build.sh
projects/g-api-python-client/fuzz_mimeparser.py
projects/g-api-python-client/project.yaml

Initial integration of https://github.com/googleapis/google-api-python-client

g-api-python-client: initial integration

---

projects/wasmtime/project.yaml

Add another cc for the Wasmtime project

---

projects/abseil-cpp/build.sh

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=48948

abseil-cpp: fix build

---

projects/ostree/build.sh

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=46923

ostree: fix build

---

projects/g-api-python-cloud-core/Dockerfile
projects/g-api-python-cloud-core/build.sh
projects/g-api-python-cloud-core/fuzz_helpers.py
projects/g-api-python-cloud-core/project.yaml

Initial integration of https://github.com/googleapis/python-cloud-core

python-cloud-core: initial integration

---

projects/g-api-auth-library-python/Dockerfile
projects/g-api-auth-library-python/build.sh
projects/g-api-auth-library-python/fuzz_jwt.py
projects/g-api-auth-library-python/project.yaml

Initial integration of
https://github.com/googleapis/google-auth-library-python

google-auth-library-python: initial integration

---

projects/gcloud-error-py/Dockerfile
projects/gcloud-error-py/build.sh
projects/gcloud-error-py/fuzz_util.py
projects/gcloud-error-py/project.yaml

Create util fuzzer
Add project settings

GCloud Error Python: initial integration

---

projects/g-api-auth-library-python/project.yaml

Ref:
https://github.com/googleapis/google-auth-library-python/issues/1082#issuecomment-1188384851

g-api-auth-library: add google members

---

projects/mosh/project.yaml

mosh: update email addresses for a couple of maintainers

---

projects/antlr4-java/Dockerfile
projects/antlr4-java/GrammarFuzzer.java
projects/antlr4-java/build.sh
projects/antlr4-java/project.yaml

Initial commit [antlr4]

---

projects/opencensus-cpp/build.sh

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=48950

opencensus-cpp: fix build

---

infra/constants.py

[wycheproof] Support wycheproof as an engine in presubmit

---

projects/bc-java-wycheproof/project.yaml

[wycheproof] Add example integration

---

infra/base-images/base-builder/compile

[wycheproof] Get compilation working

---

infra/build/functions/build_lib.py
projects/bc-java-wycheproof/project.yaml

[wycheproof] Add build infra support

---

.github/workflows/project_tests.yml

[wycheproof] Add CI support

---

projects/zeek/build.sh

This should fix the recent build failures of the zeek project.

zeek: Fix installation of filesystem module

---

projects/bc-java-wycheproof/build.sh

Resolving symlinks makes the test start executing.
However, locally I still got some test failures, which I don't know if are expected or not. But still, it is some progress.
Signed-off-by: Mihai Maruseac <mihaimaruseac@google.com>

Use `rsync` instead of `cp -r` and resolve symlinks.

---

projects/swift-protobuf/project.yaml

Update Cory's requested address.

---

projects/pidgin/Dockerfile
projects/pidgin/build.sh

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=49148

pidgin: fix build

---

projects/golang/project.yaml

I am stepping back from most of my Go-related maintainership.

remove josharian from cc list

---

projects/gcp-python-cloud-storage/project.yaml

Ref: https://github.com/googleapis/python-storage/issues/828#issuecomment-1192029879

gcp-python-cloud-storage: add primary matiainer

---

projects/fast-dds/Dockerfile

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=49240

fast-dds: fix build

---

projects/lcms/project.yaml

This is approved from internal conversation with LCMS maintainer @mm2 and @oliverchang

lcms: add myself in auto_ccs

---

projects/nettle/project.yaml

Per this person's request I'm updating his e-mail details.

[nettle] Update auto_ccs

---

projects/apache-commons/Dockerfile
projects/apache-commons/MathClusteringFuzzer.java
projects/apache-commons/MathDistanceMeasureFuzzer.java
projects/apache-commons/MathSimplexSolverFuzzer.java
projects/apache-commons/build.sh
projects/apache-commons/project.yaml

Bring in some fuzz targets for Clustering, DistanceMetrics
and Linear Optimization

[apache-commons] Add some fuzz-targets for commons-math

---

projects/oauth2/Dockerfile
projects/oauth2/build.sh
projects/oauth2/fuzz_basic.py
projects/oauth2/fuzz_helpers.py
projects/oauth2/project.yaml

oauth2client: initial integration

---

projects/libmodbus/project.yaml

You (email=***) are not authorized to access this page!

Fix mail authorization.

---

projects/git/project.yaml

Following internal discussions with @steadmon and @oliverchang

git: add myself to auto_ccs

---

infra/base-images/base-builder/compile
infra/base-images/base-clang/Dockerfile
infra/base-images/base-clang/checkout_build_install_llvm.sh

This only has to be merged after successful trial_build

Bump FI and adjust the path to main.py in compile

---

infra/base-images/base-builder/Dockerfile
infra/build/functions/trial_build.py

Do this by appending the branch to the test image suffix.

Support concurrent trial builds.

---

projects/jackson-core/project.yaml
projects/jackson-databind/project.yaml

Jackson -core and -databind: add maintainers

---

projects/jackson-core/Dockerfile
projects/jackson-core/FuzzParseNextToken.java
projects/jackson-core/UTF8GeneratorFuzzer.java

jackson-core: add 2 fuzzers

---

projects/pest/build.sh

cleared RUSTFLAGS for bootstrap
closes https://github.com/pest-parser/pest/issues/676

pest: fix build failure

---

projects/jackson-core/Dockerfile
projects/jackson-core/ParseNextTokenFuzzer.java
projects/jackson-core/UTF8GeneratorFuzzer.java

jackson-core: Extend fuzzers

---

projects/jackson-databind/Dockerfile
projects/jackson-databind/ObjectWriterFuzzer.java

jackson-databind: add writer fuzzer

---

projects/woff2/build.sh

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=47208

woff2: fix afl++ build

---

projects/gnupg/Dockerfile

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=49476

gnupg: fix build

---

projects/jackson-databind/Dockerfile
projects/jackson-databind/ReadTreeFuzzer.java
projects/jackson-databind/build.sh

jackson-databind: add fuzzer

---

projects/bc-java/project.yaml
projects/fastjson2/project.yaml
projects/guava/project.yaml
projects/guice/project.yaml
projects/hdrhistogram/project.yaml
projects/httpcomponents-client/project.yaml
projects/httpcomponents-core/project.yaml
projects/jackson-core/project.yaml
projects/jackson-dataformat-xml/project.yaml
projects/jackson-dataformats-binary/project.yaml
projects/jackson-modules-java8/project.yaml
projects/java-example/project.yaml
projects/javassist/project.yaml
projects/jersey/project.yaml
projects/joda-time/project.yaml
projects/json-sanitizer/project.yaml
projects/jsoup/project.yaml
projects/jul-to-slf4j/project.yaml
projects/kryo/project.yaml
projects/log4j2/project.yaml
projects/protobuf-java/project.yaml
projects/servo-core/project.yaml
projects/slf4j-api/project.yaml
projects/spring-boot-actuator/project.yaml
projects/spring-cloud-commons/project.yaml
projects/stringtemplate4/project.yaml
projects/woodstox/project.yaml
projects/zxing/project.yaml

Add code intelligence email address for several jvm projects

Add code intelligence email address for several jvm projects

---

projects/pydateutil/Dockerfile
projects/pydateutil/build.sh
projects/pydateutil/fuzz_parser.py
projects/pydateutil/fuzz_prop_isoparse.py
projects/pydateutil/project.yaml

Adds python project dateutil

---

projects/jackson-core/DataInputFuzzer.java
projects/jackson-core/build.sh

jackson-core: add fuzzer

---

projects/jackson-databind/Dockerfile
projects/jackson-databind/ObjectWriterFuzzer.java

Adds randomization of mapper settings.

jackson-databind: Improve write fuzzer

---

projects/jackson-core/DataInputFuzzer.java
projects/jackson-core/Dockerfile

jackson-core: Extend DataInput fuzzer

---

projects/spidermonkey/build.sh

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=49667

spidermonkey: fix build

---

projects/jackson-core/DataInputFuzzer.java

Adds coverage of `readBinaryValue()`.

jackson-core: improve DataInput fuzzer

---

projects/asn1crypto/Dockerfile
projects/asn1crypto/build.sh
projects/asn1crypto/fuzz_parse.py
projects/asn1crypto/project.yaml

Initial integration of: https://github.com/wbond/asn1crypto

asn1crypto: initial integration

---

infra/base-images/base-builder/Dockerfile
infra/constants.py

Related: https://github.com/google/oss-fuzz/issues/8164

[NFC] Add initial support for AArch64

---

projects/jackson-databind/ObjectWriterFuzzer.java

jackson-databind: Add copyright header

---

projects/e2fsprogs/fuzz/ext2fs_image_read_write_fuzzer.cc
projects/e2fsprogs/fuzz/ext2fs_read_bitmap_fuzzer.cc

Only set IGNORE_CSUM_ERRORS until we understand what flags are ok.

[e2fsprogs] Only set one flag for now

---

projects/gvisor/state_fuzzer.go

gvisor: fix broken build

---

projects/ossf-scorecard/build.sh
projects/ossf-scorecard/yaml_fuzzer.go

scorecard: fix broken build

---

projects/jackson-core/DataInputFuzzer.java
projects/jackson-core/UTF8GeneratorFuzzer.java

Increases coverage of two fuzzers.

jackson-core: improve fuzzers

---

projects/jackson-databind/ConvertValueFuzzer.java
projects/jackson-databind/Dockerfile
projects/jackson-databind/build.sh

Increases coverage of the `ReadTreeFuzzer` and adds a `ConvertValueFuzzer`.

jackson-databind: increase coverage

---

projects/pulumi/config_fuzzer.go

pulumi: fix broken build

---

projects/go-redis/build.sh

go-redis: fix broken build

---

projects/tdengine/build.sh

tdengine: fix broken build

---

infra/base-images/base-runner/bad_build_check

Support AArch64 in bad_build_check

---

infra/base-images/base-runner/Dockerfile
infra/base-images/base-runner/install_deps.sh
infra/base-images/base-runner/install_go.sh
infra/base-images/base-runner/install_java.sh

Support building base-runner on aarch64.

---

projects/nghttp2/build.sh

New fuzzer in upstream. Updating build.

nghttp2: extend build to match upstream fuzzers

---

infra/base-images/base-builder/Dockerfile
infra/base-images/base-builder/install_deps.sh
infra/base-images/base-clang/Dockerfile
infra/base-images/base-clang/checkout_build_install_llvm.sh
infra/base-images/base-image/Dockerfile

Support C/C++ projects on AArch64.

---

projects/skcms/Dockerfile

Since I use this for testing ARM and other changes remove some
unnecessary things to speedup builds.

[skcms] Speed up image build slightly.

---

infra/base-images/base-image/Dockerfile

[aarch64] Set random_tags=0

---

projects/g-api-resumable-media-python/project.yaml

Ref: https://github.com/googleapis/google-resumable-media-python/issues/342#issuecomment-1209778753

g-api-resumable-media-python: add primary contact

---

projects/sigstore/build.sh

sigstore: fix broken build

---

projects/wasmtime/project.yaml

Apologies for the duplicates at https://github.com/google/oss-fuzz/pull/8212 and https://github.com/google/oss-fuzz/pull/8214. My prior signing of the CLA makes it easiest for me to add new folks at Fastly to the list here so we're just trying to figure out who to pass the baton to.

Add Trevor Elliot to Wasmtime

---

infra/build/build_status/update_build_status.py

re this list: http://oss-fuzz-introspector.storage.googleapis.com/index.html

Make sure projects list is sorted on the public index

---

projects/ftfy/fuzz_fix.py

fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=50062

ftfy: capture unicode encode errors

---

projects/pyyaml/fuzz_loader.py
projects/pyyaml/fuzz_reader.py

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=50061

pyyaml: catch recursion exceptions

---

infra/manifest.py

Add script to make manifests pointing to docker images for different
platforms.
Related: https://github.com/google/oss-fuzz/issues/8164

[arm] Add manifest script

---

projects/golang/Dockerfile
projects/golang/build.sh
projects/golang/elf_fuzzer.go
projects/golang/fuzz_tar_reader.go
projects/golang/fuzz_tar_reader.options

golang: add fuzzers

---

projects/jackson-core/project.yaml
projects/jackson-databind/project.yaml

Apologies for possibly doing this wrong, but I would like to give (at least read) access to fuzz issues to PJ Fanning.
I am the primary contact for these projects.
If there is a better way to request/grant access, please let me know.

Add "fanningpj@gmail.com" as auto_cc for jackson-core, jackson-databind

---

projects/llvm/build.sh

llvm: fix broken build

---

projects/golang/build.sh

golang: use tar reader options file

---

projects/golang/build.sh

Adds fuzzers from the std lib repo.

golang: build upstream fuzzers

---

projects/hsqldb/project.yaml

Fixes https://github.com/google/oss-fuzz/issues/8251

Update maintainer email for hsqldb 

---

projects/wget2/project.yaml

Add rootkea to wget2 project

---

projects/g-cloud-logging-py/Dockerfile
projects/g-cloud-logging-py/fuzz_entries.py
projects/g-cloud-logging-py/fuzz_helpers.py
projects/g-cloud-logging-py/fuzz_resources.py

Add mocking to resources fuzzer and simplify others. This fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=49098

g-cloud-logging: refine fuzzing set up

---

projects/gc-iam/Dockerfile
projects/gc-iam/build.sh
projects/gc-iam/fuzz_credentials.py
projects/gc-iam/project.yaml

gc-iam:initial integration

---

projects/apache-commons-cli/Dockerfile
projects/apache-commons-cli/ParserFuzzer.java
projects/apache-commons-cli/build.sh
projects/apache-commons-cli/project.yaml

[apache-commons-cli] Initial Integration

---

projects/bc-java/X509CertPairParserFuzzer.java

adding X509CertPairParser fuzz test for [bc-java]

---

projects/bc-java/PEMParserFuzzer.java

adding PEMParser fuzz test for [bc-java]

---

projects/tomcat/Dockerfile
projects/tomcat/ELEvaluationFuzzer.java
projects/tomcat/FileHandlerFuzzer.java
projects/tomcat/WsPingPongFuzzer.java
projects/tomcat/build.sh

Fix the build failed issue and added 2 fuzz targets for tomcat juli and websocket. Also modified the fuzz target for expression language injection.

Tomcat: Fix build issue and add fuzz targets.

---

projects/burntsushi-toml/project.yaml
projects/mxj/project.yaml
projects/orjson/project.yaml

Hi, this pr disables file_github_issue until explicitly mentioned by maintainers.
Edit: These projects were integrated by me: maxnair.dev@gmail.com.

Disables file github issue flag

---

projects/golang/build.sh
projects/golang/math_big_fuzzer.go

Add `FuzzFloat64SpecialCases` and run `gofmt`.

golang: add fuzzer

---

projects/orjson/fuzz_orjson.py

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=50417

orjson: catch recursion limit exception

---

projects/jackson-databind/ObjectReader2Fuzzer.java

jackson-databind: Catch IllegalArgumentException

---

projects/spirv-tools/project.yaml

Add new member of shader compilers team to ACLs.

Update auto-cc for spirv-tools

---

projects/coveragepy/project.yaml

Ref: https://github.com/google/oss-fuzz/pull/8161#issuecomment-1220522232

coveragepy: update primary contact

---

projects/pydateutil/fuzz_parser.py
projects/pydateutil/fuzz_prop_isoparse.py

cc @DavidKorczynski to complete #8133 
Should fix the coverage build failure (cf ujson which has also an `hypothesis` fuzz target)

Pydateutil v2

---

projects/jackson-databind/ObjectReaderRandomClassFuzzer.java

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=50514

jackson-databind: catch false positive

---

projects/jackson-databind/ObjectReaderRandomClassFuzzer.java

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=50529

jackson-databind: Catch another exception

---

infra/build/functions/requirements.txt

Reverts google/oss-fuzz#7447
To see if it helps with #8307

Revert "build(deps): update google-cloud-datastore requirement from <2.0 to <3.0 in /infra/build/functions"

---

infra/build/build_status/cloudbuild.yaml

Increase timeout

---

infra/build/functions/base_images.py

[arm] Add manifest steps to base-images

---

projects/skcms/project.yaml

Now that #8271 is landed, this should work.
Related: #8164

[aarch64][skcms] Reenable build

---

projects/grpc-py/project.yaml

Ref: https://github.com/google/oss-fuzz/pull/7756#issuecomment-1224354772

grpc-py: add primary contact

---

infra/base-images/base-builder-javascript/Dockerfile
infra/base-images/base-builder/Dockerfile
infra/base-images/base-builder/install_javascript.sh
infra/build/functions/base_images.py
infra/build/functions/build_and_push_test_images.py
infra/build/functions/build_lib.py
infra/build/functions/test_data/expected_trial_build_steps.json
infra/build/functions/trial_build_test.py
infra/ci/build.py
infra/cifuzz/run_fuzzers_entrypoint.py
infra/constants.py
infra/helper.py

Prepare for JavaScript fuzzing

---

projects/skcms/project.yaml

[skcms] Disable aarch64

---

projects/idna/project.yaml

Ref: https://github.com/kjd/idna/issues/122#issuecomment-1224979490

idna: update primary contact

---

projects/dovecot/Dockerfile

dovecot: Update dependencies to make Dovecot build again

---

infra/base-images/base-clang/checkout_build_install_llvm.sh
projects/bearssl/Dockerfile
projects/bitcoin-core/Dockerfile
projects/circl/Dockerfile
projects/cryptofuzz/Dockerfile
projects/libecc/Dockerfile
projects/libressl/Dockerfile
projects/nettle/Dockerfile
projects/num-bigint/Dockerfile
projects/orbit/Dockerfile
projects/relic/Dockerfile
projects/rustcrypto/Dockerfile
projects/wolfssl/Dockerfile

This is incremental roll meant to break less than #8108

Roll clang to llvmorg-15-init-1464-gbf7f8d6f

---

projects/skia/project.yaml

Planning to address COLRv1 typeface rendering fuzzing issues.

[skia] Add myself to Skia CC list

---

projects/tomcat/JNDIRealmFuzzer.java
projects/tomcat/build.sh

Modify JNDIRealmFuzzer and disable expression language detector to avoid false positive of ELEvaluationFuzzer.

Tomcat: Modify one fuzz target and disable bug detector

---

projects/spring-security/EncodingUtilsConcatenateFuzzer.java
projects/spring-security/HexFuzzer.java
projects/spring-security/InMemoryUserDetailsManagerChangePasswordFuzzer.java
projects/spring-security/Utf8Fuzzer.java
projects/spring-security/build.sh
projects/spring-security/project.yaml

Added fuzz targets for:
- crypto.util.EncodingUtils.concatenate
- crypto.codec.Hex.encode and crypto.codec.Hex.decode
- crypto.codec.Utf8.encode and crypto.codec.Utf8.decode
- provisioning.InMemoryUserDetailsManager.changePassword

Expand spring-security fuzzing

---

projects/plexus-utils/Dockerfile
projects/plexus-utils/MXParserFuzzer.java
projects/plexus-utils/MXParserFuzzer.options
projects/plexus-utils/XmlStreamReaderFuzzer.java
projects/plexus-utils/XmlStreamReaderFuzzer.options
projects/plexus-utils/build.sh
projects/plexus-utils/project.yaml

[plexus-utils] initial integration

---

infra/helper.py

This is probably a lot of what is needed for CFL support (though there's probably a lot of other stuff left).
Related: https://github.com/google/oss-fuzz/issues/8164

[aarch64] Add ARM support to helper.py

---

projects/spring-framework/Dockerfile
projects/spring-framework/JdbcCoreMapperFuzzer.java
projects/spring-framework/JdbcCoreMapperFuzzerBeans.xml
projects/spring-framework/add-shadow-context.diff
projects/spring-framework/add-shadow-core.diff
projects/spring-framework/add-shadow-jdbc.diff
projects/spring-framework/add-shadow-orm.diff
projects/spring-framework/add-shadow-test.diff
projects/spring-framework/add-shadow-tx.diff
projects/spring-framework/add-shadow-web.diff
projects/spring-framework/add-shadow-webmvc.diff
projects/spring-framework/build.sh
projects/spring-framework/jdbc/DataAccessObject.java
projects/spring-framework/jdbc/Mapper.java
projects/spring-framework/jdbc/MapperFuzzerServer.java
projects/spring-framework/jdbc/PersistentClass.java
projects/spring-framework/jdbc/Server.java
projects/spring-framework/jdbc/Template.java
projects/spring-framework/project.yaml

Also has some commits to clean up the Docker/build.sh in preparation

[spring-framework] Intial Integration for jdbc

---

projects/ffmpeg/Dockerfile
projects/libarchive/Dockerfile

Similar to: https://github.com/google/oss-fuzz/pull/8365

ffmpeg, libarchive: bump automate to fix builds

---

projects/dom4j/DOMReaderFuzzer.java
projects/dom4j/Dockerfile
projects/dom4j/build.sh
projects/dom4j/project.yaml

[dom4j] initial integration

---

projects/golang/build.sh
projects/golang/h2c_fuzzer.go

Mock HTTPWriter.
Do not randomize request headers.

golang: modify fuzzer

---

projects/tomcat/ELEvaluationFuzzer.java
projects/tomcat/WsPingPongFuzzer.java

Add exceptions needed to catch and remove unnecessary security warnings.

Tomcat: Improve fuzz targets

---

projects/msquic/project.yaml

Hi team,
Please kindly review our integration

[msquic] initial integration

---

projects/tomcat/ConnectorSendFileFuzzer.java
projects/tomcat/FileHandlerFuzzer.java
projects/tomcat/Http11ProcessorDefaultServletFuzzer.java
projects/tomcat/RestCsrfPreventionFilterFuzzer.java
projects/tomcat/WsPingPongFuzzer.java

Second PR for improvement in Tomcat fuzz targets. Fix for logical issue and incorrect level of warning. Fixed some issues I did not notice in my previous PR, sorry about that!

Tomcat: Improve fuzz targets 2

---

projects/libressl/Dockerfile
projects/libressl/build.sh

Add libgmp and Botan for comparing LibreSSL's output against.

[libressl] Add libgmp, Botan

---

projects/golang/Dockerfile
projects/golang/build.sh

golang: clone in Dockerfile instead of build.sh

---

projects/golang/build.sh

golang: add corpora

---

projects/groovy/Dockerfile
projects/groovy/TestFuzzer.java
projects/groovy/add-shadow-to-test.diff
projects/groovy/build.sh

We're using / containing #8407 . Opening it as draft for now.

[groovy-test] Initial Integration

---

projects/bluez/fuzz_textfile.c

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51072

bluez: minor fix

---

projects/golang/webp_fuzzer.go

Fixes:
- https://oss-fuzz.com/testcase-detail/5941690732511232
- https://oss-fuzz.com/testcase-detail/4509882887307264
- https://oss-fuzz.com/testcase-detail/5941690732511232

golang: fix false positive

---

projects/golang/Dockerfile
projects/golang/build.sh
projects/golang/filepath_fuzzer.go
projects/golang/glob_fuzzer.options

golang: add glob fuzzer

---

projects/golang/build.sh

This PR builds many of the existing fuzzers against the latest master branch in addition to the Go version used by OSS-Fuzz.

golang: Run fuzzers against latest master

---

projects/lcms/cms_universal_transform_fuzzer.c

Create intents and flags based on fuzzer-derived data and ensure size of input/output buffers matches the upper bound of the transformation functions in lcms.

lcms: extend universal transform fuzzer

---

projects/flask/Dockerfile

- Upgrades pip to fix build error.

flask: fix build error

---

projects/librdkafka/build.sh

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51115

librdkafka: fix build

---

projects/jetty/Dockerfile
projects/jetty/ServerHandlersFuzzer.java
projects/jetty/build.sh
projects/jetty/pom.patch
projects/jetty/project.yaml

Initial integration of Jetty project, only contains a fuzz target of jetty-server part for now.

Jetty: Initial integration

---

projects/tensorflow-py/Dockerfile

- Upgrades pip to fix build error.

tensorflow-py: fix build error

---

projects/jackson-databind/ObjectReader2Fuzzer.java

jackson-databind: minor modification

---

projects/go-toml/fuzz.go

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51162

go-toml: fix build error

---

projects/hunspell/project.yaml

to remove security@documentfoundation.org
similar to
commit 9a7567d9cdc6d81419dc63bdd867f46c0f033704
Author: Caolán McNamara <caolanm@redhat.com>
Date:   Tue May 10 19:53:09 2022 +0100
update libreoffice auto_cc (#7693)

update hunspell auto_ccs

---

projects/envoy/project.yaml

Granting new members oss-fuzz access for our project.
cc @botengyao

[envoy] adding Alan and Boteng

---

projects/poppler/build.sh

Fixes https://oss-fuzz-build-logs.storage.googleapis.com/log-ebdc298b-25bf-47d8-8a6d-896e09c43f7f.txt

Fix poppler build

---

infra/base-images/base-builder/Dockerfile
infra/base-images/base-builder/precompile_centipede

Pin centipede to a commit that builds.
Also remove 1.3GB of image bloat it adds
CC @ussuri @Alan32Liu 
Fixes #8458

[centipede] Fix centipede

---

projects/nfstream/build.sh

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=50578

[nfstream] Fix build.

---

projects/zstd/project.yaml

Update to reflect team membership changes.

[zstd] Update auto_ccs list

---

infra/base-images/base-builder/install_deps.sh

Don't install git via ppa

---

projects/xmltodict/Dockerfile
projects/xmltodict/build.sh
projects/xmltodict/project.yaml
projects/xmltodict/unparse_parse_fuzzer.py

supersedes https://github.com/google/oss-fuzz/pull/6633
Made a new PR based on the comment https://github.com/google/oss-fuzz/pull/6633#issuecomment-1245409077

xmltodict: initial integration

---

projects/oauthlib/Dockerfile

Install all dependencies to fix
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51337

oauthlib: fix deps

---

projects/kafka/Dockerfile
projects/kafka/fuzz_consumer.py

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51338

kafka: fix consumer

---

projects/bluez/Dockerfile

Install systemd in Dockerfile to fix current build

bluez: fix build

---

projects/janino/Dockerfile
projects/janino/ExpressionEvaluatorFuzzer.java
projects/janino/build.sh
projects/janino/project.yaml

[janino] initial commit

---

projects/golang/build.sh

golang: rename fuzzer

---

projects/containerd/Dockerfile

containerd: Use custom bug detectors

---

projects/file/Dockerfile
projects/file/build.sh

Fixes: https://github.com/google/oss-fuzz/issues/8513

file: fix build

---

projects/g-api-py-oauthlib/fuzz_config.py

In an effort to avoid spurious errors e.g.
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=50820
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51094

g-api-py-oauthlib: refactor fuzzer

---

projects/tensorflow-py/project.yaml
projects/tensorflow/project.yaml

Adds new cc to tensorflow and tensorflow-py projects.

added myself

---

infra/build/functions/build_and_run_coverage.py
infra/build/functions/build_and_run_coverage_test.py
infra/build/functions/build_lib.py
infra/build/functions/build_project.py
infra/build/functions/build_project_test.py
infra/build/functions/ci_trial_build.py
infra/build/functions/request_build.py
infra/build/functions/trial_build.py
infra/build/functions/trial_build/cloudbuild.yaml

Fix https://github.com/google/oss-fuzz/issues/8273

[trial builds] Support forks

---

infra/ci/build.py

Fixes: https://github.com/google/oss-fuzz/issues/8508

[CI] Allow projects to opt-out of running tests.

---

projects/mapserver/project.yaml

updating the mail ID of Mr. @geographika

Update Mail ID

---

projects/file/magic_fuzzer.cc

- MAGIC_COMPRESS: If the file is compressed, unpack it and look at the contents.
- MAGIC_CONTINUE:  Return all matches, not just the first.

Process compressed files and analyse as much as possible

---

infra/base-images/base-builder/install_java.sh
infra/base-images/base-runner/coverage

infra: Update Jazzer to fix coverage build failures

---

projects/libevent/project.yaml

libevent: adding myself as auto_ccs

---

projects/jupyter_server/Dockerfile
projects/jupyter_server/build.sh

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51399

jupyter_server: install npm to fix build

---

projects/mongoose/build.sh

Fixes: https://github.com/google/oss-fuzz/issues/8549

mongoose: refine build

---

infra/cifuzz/actions/run_fuzzers/action.yml
infra/cifuzz/config_utils.py
infra/cifuzz/external-actions/run_fuzzers/action.yml
infra/cifuzz/fuzz_target.py

Related: https://github.com/google/clusterfuzzlite/issues/105

[CFL] Support parallel fuzzing

---

projects/apache-felix-dev/Dockerfile
projects/apache-felix-dev/JSONParserFuzzer.java
projects/apache-felix-dev/build.sh
projects/apache-felix-dev/project.yaml

Main is not fuzzable. Fuzzing target is a JSON parser which is used in webconsole. The webconsole is an installable bundle.

[apache.felix.main] initial integration

---

projects/ruby/project.yaml

👋 Hello.
We'd like to include these additional Ruby Core team members in emails and viewing results

Add additional CCs for Ruby

---

projects/lcms/cms_profile_fuzzer.c

lcms: update profile fuzzer

---

projects/lotus/Dockerfile

lotus: fix broken build

---

projects/git/Makefile.diff
projects/git/build.sh
projects/git/fuzz-cmd-base.c
projects/git/fuzz-cmd-base.h
projects/git/fuzz-command.c

List of git commands covered
GIT_ADD
GIT_BRANCH
GIT_COMMIT
GIT_CONFIG
GIT_DIFF
GIT_DIFF_FILES
GIT_DIFF_INDEX
GIT_DIFF_TREE
GIT_LS_FILES
GIT_LS_TREE
GIT_MV
GIT_RERERE
GIT_STATUS
GIT_VERSION

git: Combine multiple git command fuzzer to one

---

projects/ruby/project.yaml

Add the address of nobu, and change the addresses of hsbt and mame

Tweak CCs of ruby

---

projects/spdk/project.yaml

Michal's e-mail address was changed some time ago (dropped the X at the end), so update it here too.

spdk: update Michal Berger's e-mail

---

projects/gc-iam/fuzz_credentials.py

Remove fuzzing for internally controlled functions
- 50290 (https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=50290)

gc-iam: Fix issue 50290

---

projects/kafka/fuzz_consumer.py
projects/kafka/fuzz_producer.py

Fix error handling or other false-positive bugs reported for projects issues.
- 51491 (https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51491) 
- 51493 (https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51493)

kafka Fix missing error handling for null byte checking in issue 51491 51493

---

projects/retry/fuzz_retry.py

Fix error handling for retry limit reached.
Issue 49635 (https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=49635)

retry: fix error handling when retry limit reached - Issue 49635

---

projects/git/fuzz-cmd-base.h
projects/git/fuzz-command.c

Add loop for git command fuzzing, allowing more coverage.

[git]: add loop for the cmd fuzzing

---

projects/angus-mail/ASCIIUtilityFuzzer.java
projects/angus-mail/BASE64EncoderStreamFuzzer.java
projects/angus-mail/Dockerfile
projects/angus-mail/build.sh
projects/angus-mail/project.yaml

[angus-mail] initial integration

---

projects/suricata/Dockerfile
projects/suricata/build.sh
projects/suricata/project.yaml

with zlib compiled with MSAN
Should fix #8574 cc @jonathanmetzman

suricata: build with memory sanitizer

---

projects/openpyxl/fuzz_comment.py
projects/openpyxl/fuzz_formulae.py

Fix exception handling for issues.
48488 (https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=48488)
48506 (https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=48506)y

[openpyxl]: fix exception control for internal error

---

projects/git/fuzz-command.c

Add in more test cases for git diff
Fix git base work tree allowing more coverage for git diff and other commands.

Fix git structure and git diff testcase

---

projects/wolfssl/project.yaml

Add jordan to wolfSSL auto_ccs.

[wolfssl] Update auto_ccs

---

projects/git/build.sh

Fix build script to avoid detecting leak

[git]: Fix build script

---

projects/mapserver/project.yaml

Cf https://github.com/google/oss-fuzz/blob/master/projects/gdal/project.yaml#L3

mapserver: update my email address to my @gmail.com one

---

projects/lldpd/Dockerfile
projects/lldpd/FuzzDecode.c
projects/lldpd/build.sh
projects/lldpd/project.yaml

Hello @vincentbernat 
Can you check this PR?
oss-fuzz team. 
Application usage in router: 
- Unifi,
- Cambium Networks,
- oVirt,
- OpenWrt,
- Poly,
- MikroTik,
- Cumulus,
- ASUS.
It is possibly used in other places as well.

[lldpd] initial integration

---

projects/jakarta-mail-api/Dockerfile
projects/jakarta-mail-api/HeaderTokenizerFuzzer.java
projects/jakarta-mail-api/build.sh
projects/jakarta-mail-api/project.yaml

[jakarta-mail-api] initial integration

---

projects/sigstore/project.yaml

This new group includes previous members along with additional security response team members.

Update Sigstore fuzz contacts

---

projects/adal/fuzz_util.py

Fix for issue
51964 (https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51964)

[adal]: Fix error handling

---

projects/kafka/fuzz_consumer.py
projects/kafka/fuzz_producer.py

Fix two issues for kafka fuzzing
51986 (https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51986)
51996 (https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51996)

[Kafka]: Fix issue 51986 51996

---

projects/okhttp/build.sh
projects/okhttp/pom.xml
projects/okhttp/src/main/java/ossfuzz/LoggingInterceptorFuzzer.java
projects/okhttp/src/main/java/ossfuzz/NullLogger.java

[okhttp] Add fuzz target for LoggingInterceptor

---

projects/oauth2/fuzz_helpers.py

Fix unicode error for issue
51990 (https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51990)

[oauth2]: Fix unicode error

---

projects/git/fuzz-cmd-base.c

[git]: Remove system() call in code

---

projects/sigstore/project.yaml

Groups do not seem to grant access to the issues.

Update sigstore contacts to be individual members

---

projects/pyxdg/Dockerfile
projects/pyxdg/fuzz_desktop_entry.py
projects/pyxdg/fuzz_menu.py

Enabling pysecsan for 2 of the fuzzers.

pyxdg: enable pysecsan

---

projects/gstreamer/Dockerfile

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51814

gstreamer: fix build by updating meson to latest stable release (0.63.2)

---

projects/toml_edit/Dockerfile
projects/toml_edit/build.sh
projects/toml_edit/project.yaml

This relands 6088406 (https://github.com/google/oss-fuzz/pull/8524)
This reverts commit 940112608af3cf9916f3b62a692d3255cec1c116.
CC @manunio

Reland 6088406

---

projects/git/Dockerfile
projects/git/build.sh
projects/git/fuzz-cmd-base.c
projects/git/fuzz-cmd-diff.c

Fix error handling and increase base seed size to avoid early ending from errors.

[git]: increase code coverage

---

projects/toml_edit/build.sh

Hi, This fixes build error caused by toml_edit fuzz refactoring.

toml_edit: Fixes build error

---

projects/pupnp/Dockerfile
projects/pupnp/FuzzIxml.c
projects/pupnp/build.sh
projects/pupnp/project.yaml

Hello, @mrjimenez
Any thoughts on PR?
Other harnesses are not included due to test failure of :
[test_UpnpHttpHeaderList.cpp](https://github.com/pupnp/pupnp/blob/branch-1.14.x/gtest/test_UpnpHttpHeaderList.cpp)
[test_upnpapi.cpp](https://github.com/pupnp/pupnp/blob/branch-1.14.x/gtest/test_upnpapi.cpp)

[pupnp] initial integration

---

projects/qemu/Dockerfile

qemu: add libslirp dependency

---

projects/gpsd/fuzzer/FuzzJson.c

Fix of https://github.com/google/oss-fuzz/issues/8666

[GPSD] fix json bugs.

---

projects/libarchive/build.sh

- Add corkami's repository of weird formats/archives
- Speed up compilation a bit

Improve a bit libarchive's corpus

---

projects/sleuthkit/build.sh

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51119

sleuthkit: fix build

---

projects/minizip/Dockerfile
projects/minizip/build.sh

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51117

minizip: fix build

---

projects/hsqldb/SqlPreparedStatementFuzzer.java

[hsqldb] fix typo

---

projects/libarchive/Dockerfile
projects/libarchive/build.sh

Make use of libarchive uuencoded testfiles

---

projects/ron/Dockerfile
projects/ron/build.sh
projects/ron/project.yaml

Hi, [RON](https://github.com/ron-rs/ron) is a simple readable data serialization format that looks similar to Rust syntax. It's designed to support all of [Serde's data model](https://serde.rs/data-model.html), so structs, enums, tuples, arrays, generic maps, and primitive values.
- It has 3 million+ downloads as per [crates.io](https://crates.io/crates/ron).
- It's being used by projects like:
- [bevy](https://github.com/bevyengine/bevy)
- [egui](https://github.com/emilk/egui)
- [Fyrox](https://github.com/FyroxEngine/Fyrox)
- [orbtk](https://github.com/redox-os/orbtk)
- [wgpu](https://github.com/gfx-rs/wgpu)
- [gitui](https://github.com/extrawurst/gitui)
- [insta](https://github.com/mitsuhiko/insta)
- [serde_with](https://github.com/jonasbb/serde_with)

ron: initial integration

---

projects/fabric/Dockerfile
projects/fabric/FuzzExtractFileEntries.options
projects/fabric/FuzzParseChaincodePackage.options
projects/fabric/FuzzPersistence.options
projects/fabric/build.sh
projects/fabric/ccprovider_fuzzer.go
projects/fabric/fabenc_fuzzer.go
projects/fabric/msp_fuzzer.go
projects/fabric/persistence_fuzzer.go
projects/fabric/policydsl_fuzzer.go

Adds more fuzzers for hyperledger fabric.

fabric: add more fuzzers

---

projects/python-tabulate/project.yaml

Ref: https://github.com/astanin/python-tabulate/issues/191

python-tabulate: update contact

---

projects/unit/build.sh
projects/unit/fuzzer/Fuzz_http.c

fix memory leak in ```nxt_http_fields_hash```

[unit] fix memory leak

---

projects/git/fuzz-cmd-diff.c

- Enable more calls to diff
- Add environment variable specifying git template dir

git: refine diff fuzzer

---

projects/oak/build.sh

https://github.com/project-oak/oak/commit/83c9565ac073ae565e3c85fe8ec8a32d746fda23 added a new fuzz target, which will be used going forward

Fix directory for Oak fuzzing

---

projects/spring-integration/Dockerfile
projects/spring-integration/build.sh
projects/spring-shell/Dockerfile
projects/spring-shell/build.sh

Fix two build issues for spring-integration and spring-shell
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52119
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52225

[spring-integration -shell] Fix issues 52119 52225

---

projects/mongoose/build.sh

Ref: https://github.com/google/oss-fuzz/issues/8601#issuecomment-1273528189

mongoose: tmp disable netdriver fuzzer

---

projects/grpc/project.yaml

This is long overdue - removing contacts who aren't there anymore, and adding new people in.

Updating gRPC contacts

---

projects/golang/build.sh
projects/golang/math_big_fuzzer.go

golang: add 2 fuzzers

---

projects/golang/language_fuzzer.go

golang: add target to fuzzer

---

projects/unbound/build.sh
projects/unbound/project.yaml

Fixes: https://github.com/google/oss-fuzz/issues/8748

unbound: update build and project.yaml

---

projects/httplib2/Dockerfile

httplib2: fix build

---

projects/gpac/build.sh

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51111

gpac: fix build

---

projects/cloud-hypervisor/build.sh

New fuzzer is added for virtio-mem.
Signed-off-by: Bo Chen <chen.bo@intel.com>

cloud-hypervisor: Add new fuzzer

---

infra/base-images/base-runner/Dockerfile
infra/base-images/base-runner/coverage
infra/base-images/base-runner/install_go.sh

Runner without go

---

projects/go-containerregistry/project.yaml

As requested here: https://github.com/google/oss-fuzz/pull/8627#discussion_r984079271
@mattmoor: for info
@jonjohnsonjr do you also want to receive bug reports for go-containerregistry by any chance?

go-containerregistry: add contact

---

projects/spring-data-keyvalue/Dockerfile
projects/spring-data-keyvalue/KeyValueTemplateFuzzer.java
projects/spring-data-keyvalue/build.sh
projects/spring-data-keyvalue/project.yaml

[spring-data-keyvalue] initial commit

---

projects/protobuf-java/project.yaml

Bug component does not work from outside senders.

Replace bug component with protobuf-oss-fuzz group

---

projects/airflow/build.sh

Fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=50710

airflow: include cron_descriptor locale data in fuzzer executable

---

projects/proj4/Dockerfile

Speculative fix for proj4 in CIFuzz.

---

projects/ngolo-fuzzing/Dockerfile
projects/ngolo-fuzzing/build.sh

cc @AdamKorcz for the latest x/text CVE ;-)

ngolo-fuzzing: fuzz golang x packages

---

projects/python-tabulate/project.yaml

Ref:
https://github.com/astanin/python-tabulate/issues/191#issuecomment-1277610774

python-tabulate: fix primay maintainer email

---

projects/git/fuzz-cmd-diff.c

Create empty template directory instead of using /tmp/. This is because there are lots of other stuff in /tmp/.
To avoid errors like:
https://storage.cloud.google.com/git-logs.clusterfuzz-external.appspot.com/libFuzzer_git_fuzz-cmd-diff/libfuzzer_asan_git/2022-10-14/03%3A28%3A22%3A198498.log

git: create empty template directory

---

projects/libarchive/libarchive_fuzzer.cc

Exercise archive_entry related functions

Increase a bit the coverage of libarchive

---

projects/jackson-databind/ObjectReader2Fuzzer.java

Will resolve https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51219 which is a false positive.

jackson-databind: remove Pattern class for deserialization

---

projects/asn1crypto/project.yaml

ref: https://github.com/wbond/asn1crypto/issues/234#issuecomment-1281715842

asn1crypto: add primary contact

---

projects/ruby/fuzz_ruby_gems.c

ruby: extend fuzzing to hit regex

---

projects/jackson-databind/AdaLObjectReader3Fuzzer.java
projects/jackson-databind/ObjectReader2Fuzzer.java
projects/jackson-databind/ObjectReaderRandomClassFuzzer.java
projects/jackson-databind/build.sh

1. Add more target APIs
2. Group target types together
3. Add more settings

jackson-databind: Improve fuzzers

---

projects/libraw/project.yaml

As asked by upstream here: https://github.com/LibRaw/LibRaw/issues/295#issuecomment-637604541
cc @LibRaw

Fill issues on github for libraw

---

infra/base-images/base-clang/Dockerfile

To fetch various improvements, e.g.
- https://github.com/ossf/fuzz-introspector/pull/528
- https://github.com/ossf/fuzz-introspector/pull/546
- https://github.com/ossf/fuzz-introspector/pull/548
- https://github.com/ossf/fuzz-introspector/pull/549

Bump fuzz introspector

---

projects/golang/Dockerfile
projects/golang/build.sh
projects/golang/strings_fuzzer.go

golang: add strings split fuzzer

---

projects/jetty/build.sh

Fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51784
Delete some not needed jar.

jetty: Fix build failure

---

projects/textwrap/Dockerfile
projects/textwrap/build.sh
projects/textwrap/project.yaml

textwrap is a very popular library for rust. It has 75 million downloads from crates.io . It is also used as a dependency for a lot of very popular libraries.

initial intigraion of textwrap

---

projects/git/build.sh

Aim to solve issue e.g. https://storage.cloud.google.com/git-logs.clusterfuzz-external.appspot.com/libFuzzer_git_fuzz-cmd-diff/libfuzzer_asan_git/2022-10-20/00%3A10%3A58%3A417288.log

git: add timeout for locking files

---

projects/golang/Dockerfile
projects/golang/build.sh
projects/golang/encoding_fuzzer.go

golang: add encoding fuzzer

---

projects/libraw/project.yaml

Per upstream request here: https://github.com/LibRaw/LibRaw/issues/496

Grant maintainer access to libraw issues

---

projects/lcms/cmsIT8_load_fuzzer.c

lcms: expand load fuzzer to write it8 profile

---

projects/jackson-databind/AdaLObjectReader3Fuzzer.java

Adds a few more targets.
Improve formatting of the fuzzer.

jackson-databind: improve fuzzer

---

projects/golang/encoding_fuzzer.go

golang: refactor encoding fuzzer

---

projects/bluez/build.sh
projects/bluez/fuzz_hci.c

bluez: extend fuzzing

---

projects/bzip2/bzip2_fd.c

With the addition of these 2 fuzz drivers, all valid functions in BZIP2 should be covered

filename and file descriptor fuzz drivers to hit I/O in bzlib.c

---

projects/libraw/project.yaml

Per https://github.com/LibRaw/LibRaw/issues/496, I need to directly view libraw issues and aid the maintainer to figure out how to repro.

Adding myself to view libraw issues

---

projects/perfetto/project.yaml

Removing old vendor_ccs, adding new ones, and alphabetizing the list.

Update project.yaml CCs

---

projects/bluez/fuzz_hci.c

bluez: avoid hci_commandtostr

---

projects/libspng/Dockerfile

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52459

libspng: fix build

---

projects/netcdf/build.sh

Effort to fix: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=47295

netcdf: fix build

---

projects/moby/Dockerfile
projects/moby/build.sh
projects/moby/mounts_fuzzer.go
projects/moby/project.yaml

This PR is an initial integration of the Moby project which is essentially Docker.
______________________________________
@thaJeztah  Would you like to integrate Moby into OSS-Fuzz? If yes, we need at least one maintainers email address for the `project.yaml` file. This emali address will receive bug reports if any issues are found.

[docker] Initial integration

---

projects/clickhouse/project.yaml

A wrong email has been provided for me

[clickhouse] Correct email in maintainers contacts

---

projects/libdwarf/Dockerfile

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52842

libdwarf: fix build

---

projects/moby/Dockerfile
projects/moby/archive_fuzzers.go
projects/moby/build.sh
projects/moby/jsonfilelog_fuzzer.go
projects/moby/tailfile_fuzzer.go

moby: add more fuzzers

---

projects/oracle-py-cx/Dockerfile
projects/oracle-py-cx/build.sh

This is an effort to fix: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51298

oracle-py-cx: fix build

---

projects/pyrsistent/project.yaml

Ref: https://github.com/tobgu/pyrsistent/issues/255#issuecomment-1296137669

pyrsistent: upate project.yaml

---

infra/base-images/base-builder/install_python.sh

Upgrade Atheris

---

projects/antlr4-java/build.sh

[antlr4-java] fix build failure

---

projects/moby/Dockerfile
projects/moby/FuzzAdd.options
projects/moby/build.sh
projects/moby/etchosts_fuzzer.go

moby: add fuzzer

---

projects/moby/Dockerfile
projects/moby/build.sh
projects/moby/jsonlogbytes_fuzzer.go
projects/moby/oci_fuzzer.go

moby: add 2 fuzzers

---

projects/tensorflow/build.sh

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51443

tensorflow: fix build

---

infra/base-images/base-clang/Dockerfile

Fixes: https://github.com/google/oss-fuzz/issues/8913

infa: bump fuzz introspector

---

projects/protobuf-java/project.yaml

Similar setup as https://github.com/google/oss-fuzz/blob/master/projects/envoy/project.yaml

Add copybara to cc's and and label

---

projects/pyparsing/project.yaml

Ref: https://github.com/pyparsing/pyparsing/issues/441#issuecomment-1304457341

pyparsing: update project yaml

---

projects/boost-json/Dockerfile

This should fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52484

[boost.json] update the list of dependencies

---

projects/rekor/project.yaml

@bobcallaway @loosebazooka
Gives @DavidKorczynski and me access to bug reports for Rekor.

rekor: add maintainers

---

infra/cifuzz/fuzz_target.py

Fixes https://github.com/google/oss-fuzz/issues/8588

[CFL] Don't print fuzzing logs in realtime

---

projects/java-example/build.sh
projects/jetty/build.sh
projects/jmh/build.sh
projects/mysql-connector-j/build.sh
projects/protobuf-java/build.sh
projects/retrofit/build.sh
projects/rxjava/build.sh
projects/spring-amqp/build.sh
projects/spring-boot-actuator/build.sh
projects/spring-boot/build.sh
projects/spring-cloud-commons/build.sh
projects/spring-data-jpa/build.sh
projects/spring-data-keyvalue/build.sh
projects/spring-data-mongodb/build.sh
projects/spring-data-redis/build.sh
projects/spring-framework/build.sh
projects/spring-integration/build.sh
projects/spring-ldap/build.sh
projects/spring-retry/build.sh
projects/spring-security/build.sh
projects/spring-shell/build.sh
projects/tomcat/build.sh

These issues were missed in 5b1953b20174adca72d06a8b4e893a46591b7f4a and prevent the new logic from applying correctly for some projects.

java: Fix bash escaping in memory setting logic

---

projects/snakeyaml/DefaultYamlFuzzer.java
projects/snakeyaml/Dockerfile
projects/snakeyaml/SecureYamlFuzzer.java

Add DefaultYamlFuzzer to test default snakeyaml behavior.

snakeyaml: Add DefaultYamlFuzzer

---

projects/ghostscript/project.yaml

Adding bmgordon@ who is currently looking after printing.

Add another Google maintainer for ghostscript

---

projects/hibernate-orm/build.sh

Fix build failure for https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51159

hibernate-orm: Fix build failure

---

projects/moby/Dockerfile
projects/moby/build.sh

moby: add extended instrumentation

---

projects/fabric/Dockerfile

fabric: use latest instrumentation

---

infra/base-images/base-builder/compile_python_fuzzer
infra/base-images/base-clang/Dockerfile

Bumps fuzz introspector and updates the way python fuzzers are build for introspector builds.

infra: bump and refine introspector

---

projects/jackson-databind/build.sh

Update roaster jar version
Signed-off-by: Arthur Chan <arthur.chan@adalogics.com>

[jackson-databind]: Fix dependency version

---

projects/glom/build.sh
projects/glom/fuzz_glom.py
projects/idna/build.sh
projects/pyyaml/build.sh

This variable is no longer needed by fuzz-introspector python version for these projects.

idna, pyyaml, glom: cleanup build

---

infra/cifuzz/fuzz_target.py
infra/cifuzz/run_fuzzers.py

Make sure testcase has correct permissions

---

projects/libressl/project.yaml

Please add @botovq as a LibreSSL fuzz contact

[libressl] add fuzz contact

---

infra/build/functions/build_lib.py

With the python projects enabled, we need to broaden the coverage file names that should to be downloaded.
This PR changes `download_coverage_data_steps()` function to download all the contents of `textcov_reports` dir from the coverage bucket.

Simplify download coverage steps

---

infra/build/functions/build_and_run_coverage.py

Skip per_target coverage copy for python.

Fix Python Coverage Build

---

projects/bignum-fuzzer/Dockerfile
projects/cryptofuzz/Dockerfile
projects/ecc-diff-fuzzer/Dockerfile
projects/mbedtls/Dockerfile

Fix mbed TLS builds

---

projects/u-root/build.sh
projects/u-root/project.yaml

Addition of one more fuzzing test of the project and update of contact info 
Signed-off-by: Fabian Wienand <fabian.wienand@9elements.com>

u-root: gosh-fuzzing

---

projects/openssl/Dockerfile
projects/openssl/build.sh
projects/openssl/project.yaml

See https://github.com/openssl/openssl/issues/19642
Do not merge yet, maybe the OpenSSL team would like some changes to this pr.

[openssl] Targets for OpenSSL 1.1.1 branch and 32 bit

---

projects/tarantool/Dockerfile
projects/tarantool/build.sh

Ninja could significantly speedup building in comparison to Make.

[tarantool] Use Ninja in building

---

infra/build/functions/ci_trial_build.py

Allow skipping trial builds

---

projects/containerd/project.yaml

Hello! 
I am a [new security advisor](https://github.com/containerd/project/pull/97) for the containerd project and am requesting access to the oss-fuzz test cases. 
/cc @samuelkarp

Add Craig Ingram to containerd project

---

projects/miniz_oxide/build.sh

Fix miniz_oxide coverage build

---

projects/croniter/fuzz_iter.py

This is to make it work with fuzz introspector.
Ref: https://github.com/ossf/fuzz-introspector/pull/613

croniter: refine fuzzer

---

projects/u-root/build.sh

Signed-off-by: Fabian Wienand <fabian.wienand@9elements.com>

u-root: esxi, ipxe & smbios fuzz

---

projects/rekor/build.sh

rekor: add fuzzer to build script

---

projects/fabric/build.sh

fabric: fix broken build

---

projects/krb5/fuzzing/Fuzz_chpw.c
projects/krb5/project.yaml

Fixes: https://github.com/google/oss-fuzz/issues/9028

krb5: refine set up

---

projects/bc-java-wycheproof/build.sh

Related: https://github.com/google/oss-fuzz/issues/8034

Fix wycheproof build

---

projects/libpg_query/project.yaml

As requested @lfittl -- also, feel free to make any such changes like this with additional team members in the future

libpg_query: add maintainer

---

projects/jackson-databind/build.sh

jackson-databind: fix broken build

---

projects/ngolo-fuzzing-x/Dockerfile
projects/ngolo-fuzzing-x/build.sh
projects/ngolo-fuzzing-x/project.yaml
projects/ngolo-fuzzing/build.sh

This should consume less hard drive space for the build...

ngolo-fuzzing: cleans while building

---

projects/apache-commons-imaging/build.sh

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=53633.

[apache-commons-imaging]: Fix UnsatisfiedLinkError in java.awt.*

---

infra/base-images/base-builder/compile
infra/base-images/base-builder/install_java.sh

Reverts google/oss-fuzz#9027
per @fmeum request.

Revert "[infra] Update Jazzer to latest main"

---

projects/etcd/Dockerfile

etcd: fix broken build

---

projects/moby/Dockerfile
projects/moby/build.sh
projects/moby/daemon_fuzzer.go

moby: add daemon fuzzer

---

projects/hcl/Dockerfile
projects/hcl/build.sh

hcl: fix broken build

---

projects/containerd/Dockerfile

containerd: Use latest instrumentation

---

projects/jsonnet/convert_jsonnet_fuzzer_multi.cc
projects/jsonnet/convert_jsonnet_fuzzer_regular.cc
projects/jsonnet/convert_jsonnet_fuzzer_stream.cc

Fixes build with respect to recent commit:
https://github.com/google/jsonnet/commit/66a000684767bf0e2de7152ca38e5f3d75635d46
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52816

jsonnet: fix build

---

projects/kubeedge/Dockerfile
projects/kubeedge/build.sh

kubeedge: fix broken build

---

projects/tidb/Dockerfile
projects/tidb/build.sh
projects/tidb/fuzzMarshalJSON.go

tidb: fix broken build

---

projects/binutils/build.sh

fix binutils build breakage

---

projects/protobuf-c/Dockerfile
projects/protobuf-c/build.sh
projects/protobuf-c/project.yaml

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=50129

protobuf-c: fix build

---

projects/tendermint/project.yaml

Use new Informal Systems contacts in charge of maintaining Tendermint.

projects/tendermint: update project contacts

---

projects/argo/Dockerfile

argo: clone in Dockerfile instead of build script

---

projects/u-root/build.sh

cc @RiSKeD 
One fuzzer needs a bit of modification. If https://github.com/u-root/u-root/pull/2571 can be merged, then it can be uncommented from the build script and it should work. 

u-root: fix build

---

projects/apache-commons-bcel/project.yaml
projects/apache-commons-beanutils/project.yaml
projects/apache-commons-cli/project.yaml
projects/apache-commons-codec/project.yaml
projects/apache-commons-collections/project.yaml
projects/apache-commons-compress/project.yaml
projects/apache-commons-configuration/project.yaml
projects/apache-commons-geometry/project.yaml
projects/apache-commons-imaging/project.yaml
projects/apache-commons-io/project.yaml
projects/apache-commons-jxpath/project.yaml
projects/apache-commons-lang/project.yaml
projects/apache-commons-logging/project.yaml
projects/apache-commons-math/project.yaml
projects/tomcat/project.yaml

Update primary_contact and auto_ccs as requested by apache commons.

apache-commons: update project.yaml

---

infra/cifuzz/http_utils.py

Fixes https://github.com/google/oss-fuzz/issues/9079

[cifuzz] Add timeout to http requests.

---

projects/bottleneck/Dockerfile

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=53879

bottleneck: fix build

---

projects/pycparser/Dockerfile
projects/pycparser/build.sh
projects/pycparser/fuzz_c_parser.py
projects/pycparser/project.yaml

pycparser: initial integration

---

projects/python-markdown/Dockerfile
projects/python-markdown/build.sh
projects/python-markdown/fuzz_convert.py
projects/python-markdown/project.yaml

python-markdown: initial integration

---

projects/msgpack-python/Dockerfile
projects/msgpack-python/build.sh
projects/msgpack-python/fuzz_unpack.py
projects/msgpack-python/project.yaml

msgpack-python: initial integration

---

projects/lcms/cms_universal_transform_fuzzer.c

Ref: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51128#c3

lcms: simplify universal fuzzer

---

projects/mxj/build.sh

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=53906

mxj: Fix build

---

projects/pcapplusplus/build.sh

Ref: https://github.com/google/oss-fuzz/issues/9112
CC @sashashura

pcapplusplus: enable fuzz introspector

---

projects/gonids/Dockerfile
projects/gonids/build.sh

Now that the commit has been identified
cf https://github.com/golang/go/issues/49075

gonids: remove the git bisect logic for golang compiler

---

projects/isodate/Dockerfile
projects/isodate/build.sh
projects/isodate/fuzz_parse.py
projects/isodate/project.yaml

isodate: initial integration

---

projects/pasta/Dockerfile
projects/pasta/build.sh
projects/pasta/fuzz_parse.py
projects/pasta/project.yaml

pasta: initial integration

---

projects/ijson/Dockerfile
projects/ijson/build.sh
projects/ijson/fuzz_parser.py
projects/ijson/project.yaml

ijson: initial integration

---

projects/wabt/project.yaml

wabt: update primary_contact and add auto_ccs

---

projects/fuzztest-raksha/Dockerfile
projects/fuzztest-raksha/raksha-fuzztest.diff

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=53966

fuzztest-raksha: fix build

---

projects/u-root/build.sh

Signed-off-by: Fabian Wienand <fabian.wienand@9elements.com>

u-root: add fuzz target for ip cmd

---

projects/libcst/Dockerfile
projects/libcst/build.sh
projects/libcst/fuzz_transformer.py
projects/libcst/project.yaml

libcst: initial integration

---

projects/libcst/fuzz_transformer.py

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=54087

libcst: catch recursion issues

---

projects/istio/build.sh

istio: fix CI issue

---

projects/soupsieve/Dockerfile
projects/soupsieve/build.sh
projects/soupsieve/fuzz_select.py
projects/soupsieve/project.yaml

soupsieve: initial integration

---

projects/jmespathpy/Dockerfile
projects/jmespathpy/build.sh
projects/jmespathpy/fuzz_parse.py
projects/jmespathpy/project.yaml

jmespath: initial integration

---

projects/simplejson/Dockerfile
projects/simplejson/build.sh
projects/simplejson/fuzz_decode.py
projects/simplejson/project.yaml

simplejson: initial integration

---

projects/mrab-regex/Dockerfile
projects/mrab-regex/build.sh
projects/mrab-regex/fuzz_regex.py
projects/mrab-regex/project.yaml

mrab-regex: initial integration

---

projects/sqlparse/Dockerfile
projects/sqlparse/build.sh
projects/sqlparse/fuzz_format.py
projects/sqlparse/fuzz_parse.py
projects/sqlparse/project.yaml

sqlparse: initial integration

---

infra/base-images/base-builder/compile

Fixes: https://github.com/ossf/fuzz-introspector/issues/674

infra: add project name to python FI reports

---

projects/suricata/build.sh

I hope it can fix https://github.com/OISF/suricata/actions/runs/3651897995/jobs/6169653264

suricata: avoid backslashes in dictionary

---

projects/jmespathpy/fuzz_parse.py

Fixes e.g.: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=54198 and https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=54196

jmespathpy: catch recursion errors

---

projects/wget2/Dockerfile

This should at least fix the ./configure step.

[wget2] Add libz-dev to fix the build

---

infra/base-images/base-builder/compile

Add analytic tag for FuzzIntrospector.

---

projects/sqlparse/fuzz_parse.py

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=54212

sqlparse: avoid recursion issues

---

projects/cloud-hypervisor/build.sh

New fuzzers are added for linux-loader
Signed-off-by: Bo Chen <chen.bo@intel.com>

cloud-hypervisor: Add new fuzzers

---

infra/experimental/SystemSan/SystemSan.cpp

Fix multiple bugs with shell detection:
1. We weren't correctly extracting the argument to be passed to readlink. We needed to take the null terminator into account, as we extract this string from memory.
2. readlink does **not** null terminate the output. Fix this.
3. `binary_name.compare(0, 2, "sh")` for detecting if the binary is "sh" was too liberal, and included "shell_injection_poc_fuzzer" because the prefix matched.
Also reduce some very noisy debug logging.

SystemSan fixes.

---

projects/yarl/Dockerfile
projects/yarl/build.sh
projects/yarl/fuzz_url.py
projects/yarl/project.yaml

yarl: initial integration

---

projects/rekor/build.sh

rekor: fix broken build

---

projects/chardet/Dockerfile
projects/chardet/build.sh
projects/chardet/fuzz_detector.py
projects/chardet/project.yaml

chardet: initial integration

---

projects/markupsafe/Dockerfile
projects/markupsafe/build.sh
projects/markupsafe/fuzz_encoding.py
projects/markupsafe/project.yaml

markupsafe: initial integration

---

projects/tcmalloc/Dockerfile

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=5284

tcmalloc: fix build

---

projects/pjsip/project.yaml

Adding PJSIP team members to access bug reports.

[PJSIP] update e-mail access.

---

projects/soupsieve/fuzz_select.py

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=54276

soupsieve: catch NotImplementedError

---

projects/abseil-py/Dockerfile
projects/abseil-py/build.sh
projects/abseil-py/fuzz_argparse.py
projects/abseil-py/project.yaml

abseil-py: initial integration

---

infra/experimental/SystemSan/SystemSan.cpp
infra/experimental/SystemSan/inspect_dns.cpp
infra/experimental/SystemSan/inspect_utils.cpp
infra/experimental/SystemSan/inspect_utils.h
projects/gdal/project.yaml

Demonstrate usage to stop false postive from happening.

[SystemSan] Add feature for opting out.

---

projects/tomli/Dockerfile
projects/tomli/build.sh
projects/tomli/project.yaml

tomli: initial integration

---

projects/cryptofuzz/Dockerfile
projects/cryptofuzz/build.sh

Test Zig's built-in bignum and cryptography. This harness has found a few bugs previously: https://github.com/ziglang/zig/issues/10932

[cryptofuzz] Add Zig

---

projects/clickhouse/project.yaml

Hello, here I've added @santrancisco

Add San to ClickHouse CC

---

projects/fonttools/Dockerfile
projects/fonttools/build.sh
projects/fonttools/fuzz_compile.py
projects/fonttools/fuzz_ttfont.py
projects/fonttools/project.yaml

fonttools: initial integration

---

projects/gast/Dockerfile
projects/gast/build.sh
projects/gast/fuzz_roundtrip.py
projects/gast/project.yaml

gast: initial integration

---

projects/oscrypto/Dockerfile
projects/oscrypto/build.sh
projects/oscrypto/fuzz_asymmetric_load.py
projects/oscrypto/fuzz_keys.py
projects/oscrypto/project.yaml

oscrypto: initial integration

---

projects/pydantic/Dockerfile
projects/pydantic/build.sh
projects/pydantic/fuzz_date.py
projects/pydantic/fuzz_network.py
projects/pydantic/project.yaml

pydantic: initial integration

---

projects/proto-plus-python/Dockerfile
projects/proto-plus-python/build.sh
projects/proto-plus-python/fuzz_json_serialization.py
projects/proto-plus-python/project.yaml

proto-plus-python: initial integration

---

projects/botocore/Dockerfile
projects/botocore/build.sh
projects/botocore/fuzz_serialization.py
projects/botocore/project.yaml

botocore: initial integration

---

infra/base-images/base-clang/Dockerfile

The main purpose of this is to fix https://github.com/ossf/fuzz-introspector/issues/729

infra: bump fuzz introspector

---

projects/fonttools/fuzz_compile.py

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=54500

fonttools: add another error to catch

---

projects/knative/Dockerfile
projects/knative/build.sh

knative: move fuzzers to cncf-fuzzing

---

projects/astro-compiler/Dockerfile
projects/astro-compiler/build.sh
projects/astro-compiler/project.yaml

cc @natemoo-re
I'm currently trying to set up fuzz testing to augment the existing unit tests in https://github.com/withastro/compiler. Once this is accepted, I'll try to integrate CIFuzz for quick feedback on PRs
Using these guides for setup:
- https://google.github.io/oss-fuzz/getting-started/new-project-guide/
- https://google.github.io/oss-fuzz//getting-started/new-project-guide/go-lang/
I suppose I should try running the Dockerfile locally to see if it works?

Add withastro/compiler project

---

projects/fonttools/fuzz_woff2.py

fonttools: add new fuzzer

---

projects/proto-plus-python/fuzz_json_serialization.py

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=54566

proto-plus-python: catch recursion errors

---

projects/pyasn1-modules/Dockerfile
projects/pyasn1-modules/build.sh
projects/pyasn1-modules/fuzz_decode.py
projects/pyasn1-modules/project.yaml

pyasn1-modules: initial integration

---

projects/pymysql/Dockerfile
projects/pymysql/build.sh
projects/pymysql/fuzz_connection.py
projects/pymysql/project.yaml

pymysql: initial integration

---

projects/uritemplate/Dockerfile
projects/uritemplate/build.sh
projects/uritemplate/fuzz_expand.py
projects/uritemplate/project.yaml

uritemplate: initial integration

---

projects/lldb-eval/build.sh
projects/opencensus-cpp/build.sh

Provide necessary python file.
Tried to fix lldb-eval which has the same issue, however, other failures came up for that project so am skipping it here.

opencensus-cpp: fix builds

---

projects/docutils/Dockerfile
projects/docutils/build.sh
projects/docutils/fuzz_rst_parse.py
projects/docutils/project.yaml

docutils: initial integration

---

projects/ntpsec/project.yaml

Fixes: https://github.com/google/oss-fuzz/issues/9306

ntpsec: remove email from project.yaml

---

projects/ply/Dockerfile
projects/ply/build.sh
projects/ply/fuzz_lex_yacc.py
projects/ply/project.yaml

ply: initial integration

---

projects/wheel/Dockerfile
projects/wheel/build.sh
projects/wheel/fuzz_wheel.py
projects/wheel/project.yaml

wheel: initial integration

---

projects/packaging/Dockerfile
projects/packaging/build.sh
projects/packaging/fuzz_packaging.py
projects/packaging/project.yaml

packaging: initial integration

---

projects/fribidi/Dockerfile

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=54467

fribidi: fix build

---

projects/fluent-bit/build.sh

The fuzz-introspector build of fluent-bit is failing since some processes are killed https://oss-fuzz-build-logs.storage.googleapis.com/log-27d388fe-0493-473c-bad6-47e514519641.txt. The current build builds a lot of internal tests that we don't need and the `-j$(nproc)` may cause a memory overhead for introspector runs . This change avoids building the tests we don't need and avoids parallel linking in introspector runs.

fluent-bit: refine build

---

projects/pycparser/build.sh
projects/pycparser/fuzz_c_parser.py

pycparser: generalise fuzzer and add corpus

---

projects/pasta/fuzz_parse.py

The type of issue is not interesting.
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=54419

pasta: catch recursion error

---

projects/simplejson/fuzz_encode.py

simplejson: add encoder fuzzer

---

projects/libfido2/Dockerfile

- bump libcbor to v0.10.1
- bump zlib to v1.2.13

libfido2: bump dependencies

---

projects/distlib/Dockerfile
projects/distlib/build.sh
projects/distlib/fuzz_marker.py
projects/distlib/fuzz_metadata.py
projects/distlib/project.yaml

distlib: initial integration

---

projects/cairo/build.sh

Fixes: https://github.com/google/oss-fuzz/issues/9326

cairo: add new fuzzer

---

projects/g-api-python-bigquery-storage/Dockerfile
projects/g-api-python-bigquery-storage/build.sh
projects/g-api-python-bigquery-storage/fuzz_avroparser.py
projects/g-api-python-bigquery-storage/project.yaml

python-bigquery-storage: initial integration

---

projects/setuptools/Dockerfile
projects/setuptools/build.sh
projects/setuptools/fuzz_config_pyprojecttoml.py
projects/setuptools/project.yaml

setuptools: initial integration

---

projects/angus-mail/Dockerfile
projects/antlr4-java/Dockerfile
projects/apache-commons-cli/Dockerfile
projects/apache-commons-codec/Dockerfile
projects/apache-commons-io/Dockerfile
projects/h2database/Dockerfile
projects/jakarta-mail-api/Dockerfile
projects/janino/Dockerfile
projects/jettison/Dockerfile
projects/jetty/Dockerfile
projects/jsign/Dockerfile
projects/jul-to-slf4j/Dockerfile
projects/plexus-utils/Dockerfile
projects/slf4j-api/Dockerfile
projects/snakeyaml/Dockerfile
projects/spring-data-jpa/Dockerfile
projects/spring-data-keyvalue/Dockerfile
projects/spring-ldap/Dockerfile
projects/stringtemplate4/Dockerfile
projects/xstream/Dockerfile
projects/zip4j/Dockerfile

the permalink to maven archive will fix multiple build issues on a long-term basis

add permalink to maven archive

---

projects/gitdb/Dockerfile
projects/gitdb/build.sh
projects/gitdb/fuzz_gitdb.py
projects/gitdb/project.yaml

gitdb: initial integration

---

projects/networkx/Dockerfile
projects/networkx/build.sh
projects/networkx/fuzz_graph6.py
projects/networkx/fuzz_graphml.py
projects/networkx/fuzz_sparse6.py
projects/networkx/project.yaml

networkx: initial integration

---

projects/tinyusb/Dockerfile
projects/tinyusb/build.sh
projects/tinyusb/project.yaml

tinyusb: initial integration

---

projects/botan/project.yaml

Update auto_ccs of Botan project

---

projects/h5py/Dockerfile
projects/h5py/build.sh
projects/h5py/fuzz_h5f.py
projects/h5py/project.yaml

h5py: initial integration

---

projects/toolbelt/Dockerfile
projects/toolbelt/build.sh
projects/toolbelt/fuzz_multipart.py
projects/toolbelt/project.yaml

toolbelt: initial integration

---

projects/gitpython/Dockerfile
projects/gitpython/build.sh
projects/gitpython/fuzz_config.py
projects/gitpython/fuzz_tree.py
projects/gitpython/project.yaml

gitpython: initial integration

---

projects/more-itertools/Dockerfile
projects/more-itertools/build.sh
projects/more-itertools/fuzz_mi.py
projects/more-itertools/project.yaml

more-iteratools: initial integration

---

projects/pytest-py/Dockerfile
projects/pytest-py/build.sh
projects/pytest-py/fuzz_source.py
projects/pytest-py/project.yaml

pytest-py: initial integration

---

projects/pynacl/Dockerfile
projects/pynacl/build.sh
projects/pynacl/fuzz_hash.py
projects/pynacl/fuzz_signing.py
projects/pynacl/project.yaml

pynacl: initial integration

---

projects/iniconfig/fuzz_parse.py

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=54925

iniconfig: fix build

---

projects/libhtp/Dockerfile
projects/libhtp/build.sh
projects/libhtp/multiple.txt
projects/libhtp/project.yaml

We are transitioning from libhtp C to libhtp in rust
So, here is the update of the project to fuzz the coming rust version, and also do differential fuzzing between them to check that they have the same behavior...

Differential fuzzing for libhtp-rs

---

projects/dnspython/Dockerfile
projects/dnspython/build.sh
projects/dnspython/fuzz_message.py
projects/dnspython/fuzz_token.py
projects/dnspython/project.yaml

dnspython: initial integration

---

projects/scipy/Dockerfile
projects/scipy/build.sh
projects/scipy/fuzz_io_mio5.py
projects/scipy/fuzz_io_wavfile.py
projects/scipy/project.yaml

scipy: initial integration

---

projects/azure-sdk-for-python/Dockerfile
projects/azure-sdk-for-python/build.sh
projects/azure-sdk-for-python/fuzz_mgmt_serialization.py
projects/azure-sdk-for-python/project.yaml

azure-sdk-for-python: initial integration

---

projects/filesystem_spec/Dockerfile
projects/filesystem_spec/build.sh
projects/filesystem_spec/fuzz_http.py
projects/filesystem_spec/project.yaml

filesystem_spec: initial integration

---

projects/fuzztest-raksha/raksha-fuzztest.diff

fuzztest-raksha: enable new fuzzers

---

projects/suricata/Dockerfile
projects/suricata/build.sh

As is done for openssl for instance
cc @victorjulien

suricata: fuzz branch master6

---

projects/keras/Dockerfile
projects/keras/build.sh
projects/keras/fuzz_serialization.py
projects/keras/project.yaml

keras: initial integration

---

projects/binutils/fuzz_as.c

Upstream gas has changed, resulting in issues like https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=48997

Update binutils/fuzz_as initialisation

---

projects/itsdangerous/Dockerfile
projects/itsdangerous/build.sh
projects/itsdangerous/fuzz_itsdangerous.py
projects/itsdangerous/project.yaml

itsdangerous: initial integration

---

projects/hiredis-py/Dockerfile
projects/hiredis-py/build.sh
projects/hiredis-py/fuzz_reader.py
projects/hiredis-py/project.yaml

hiredis-py: initial integration

---

projects/suricata/build.sh

Follows #9391 to fix FPs https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=55027

suricata: do not run MSAN for branch 6

---

projects/keras/Dockerfile
projects/keras/build.sh
projects/keras/fuzz_model.py

keras: add model loading fuzzer

---

projects/tensorflow-py/project.yaml

Ref: https://github.com/google/oss-fuzz/pull/9401#issuecomment-1378842623

tensorflow-py: add myself as contact

---

projects/notary/project.yaml

As requested in https://github.com/google/oss-fuzz/pull/6867#issuecomment-1381670756
cc @justincormack

notary: Add maintainer

---

projects/rustls/build.sh

rustls: copy out fuzzers in general manner

---

projects/rekor/project.yaml

swap an email address for rekor maintainer

Update email for rekor maintainer

---

projects/crossplane/project.yaml

Signed-off-by: Philippe Scorsolini <p.scorsolini@gmail.com>

Add p.scorsolini@gmail.com to Crossplane auto_ccs

---

projects/libhtp/project.yaml

libhtp: adds people

---

infra/base-images/base-clang/Dockerfile

This is to include silencing of some HTML report generation that is WIP: https://github.com/ossf/fuzz-introspector/pull/777

bump introspector

---

projects/markupsafe/build.sh

Matches recent markupsafe updates

markupsafe: update build

---

projects/libvnc/project.yaml

A google account to access https://bugs.chromium.org/p/oss-fuzz/issues/

libvnc: add one more mail address for contacts

---

projects/envoy/project.yaml

Hi,
I am removing myself and a coworker from the Envoy project as we are no longer tracking/working on fuzzing it.

envoy: remove mails from contacts

---

projects/html5lib-python/Dockerfile
projects/html5lib-python/build.sh
projects/html5lib-python/fuzz_parse.py
projects/html5lib-python/project.yaml

html5lib-python: initial integration

---

projects/markdown-it-py/Dockerfile
projects/markdown-it-py/build.sh
projects/markdown-it-py/fuzz_markdown.py
projects/markdown-it-py/project.yaml

markdown-it-py: initial integration

---

projects/jupyter-nbconvert/Dockerfile
projects/jupyter-nbconvert/build.sh
projects/jupyter-nbconvert/fuzz_markdown_converter.py
projects/jupyter-nbconvert/project.yaml

jupyter-nbconvert: initial integration

---

projects/parso/Dockerfile
projects/parso/build.sh
projects/parso/parso_fuzz.py
projects/parso/project.yaml

parso: initial integration

---

projects/ndpi/project.yaml

nDPI: add support for centipede

---

projects/paramiko/fuzz_packetizer.py

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=55341

paramiko: fix fuzzer

---

projects/skia/build.sh

This was added in https://skia-review.googlesource.com/c/skia/+/633476

[skia] Add cubic_quad_roots fuzzer

---

projects/glib/project.yaml

Implements https://github.com/google/oss-fuzz/pull/9508

Change email to google account

---

projects/skia/project.yaml

Please add me to the CC list. Thanks!

Add jvanverth to CC list

---

projects/python-fastjsonschema/Dockerfile
projects/python-fastjsonschema/build.sh
projects/python-fastjsonschema/fuzz_compile.py
projects/python-fastjsonschema/project.yaml

python-fastjsonschema: initial integration

---

projects/tomlkit/Dockerfile
projects/tomlkit/build.sh
projects/tomlkit/fuzz_parser.py
projects/tomlkit/project.yaml

tomlkit: initial integration

---

projects/mdurl/Dockerfile
projects/mdurl/build.sh
projects/mdurl/fuzz_mdurl.py
projects/mdurl/project.yaml

mdurl: initial integration

---

projects/httpx/Dockerfile
projects/httpx/build.sh
projects/httpx/fuzz_api.py
projects/httpx/fuzz_decoders.py
projects/httpx/fuzz_url.py
projects/httpx/project.yaml

httpx: initial integration

---

projects/pyjson5/Dockerfile
projects/pyjson5/build.sh
projects/pyjson5/fuzz_json.py
projects/pyjson5/project.yaml

pyjson5: initial integration

---

projects/jedi/Dockerfile
projects/jedi/build.sh
projects/jedi/fuzz_script.py
projects/jedi/project.yaml

jedi: initial integration

---

projects/rich/Dockerfile
projects/rich/build.sh
projects/rich/fuzz_markdown.py
projects/rich/project.yaml

rich: initial integration

---

projects/pyjson5/fuzz_json.py

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=55458

pyjson5: ignore recursion errors

---

projects/pendulum/Dockerfile
projects/pendulum/build.sh
projects/pendulum/fuzz_parse.py
projects/pendulum/project.yaml

pendulum: initial integration

---

projects/cras/build.sh

This change corresponds to https://crrev.com/c/4127648.
Which will allow us to migrate away from autotools.

cras: Build fuzzers with bazel

---

docs/advanced-topics/fuzz_introspector.md
infra/build/build_status/update_build_status.py

Fixes: https://github.com/google/oss-fuzz/issues/9444

docs: add extended Fuzz Introspector doc

---

projects/gitoxide/Dockerfile
projects/gitoxide/build.sh
projects/gitoxide/project.yaml

gitoxide: initial integration

---

projects/libecc/Dockerfile
projects/libecc/build.sh

[libecc] Fix build

---

projects/python-email-validator/build.sh

Fixes run_fuzzer not picking up corpus :|

python-email-validator: fix no corpus issue

---

projects/mosquitto/Dockerfile
projects/mosquitto/build.sh
projects/mosquitto/project.yaml

There is currently a different PR open (#8793), but the mosquitto project would prefer this implementation.

mosquitto: initial integration

---

README.md
docs/index.md
docs/reference/useful_links.md

I added the recent blog post to the relevant sections and I updated our trophy numbers to reflect the latest numbers that were seen in the recent blog.

Update README and Docs to add recent blog article and update trophy stats

---

projects/trafficserver/fuzzer/FuzzEsi.cc

Need to init the Utils. Otherwise there are some failures in the tests.

[trafficserver] Fix on Esi Fuzzer

---

projects/ecc-diff-fuzzer/Dockerfile
projects/ecc-diff-fuzzer/build.sh

To fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=55001

ecc-diff-fuzzer: fix build with new repo for libecc

---

projects/bz2file/Dockerfile
projects/bz2file/build.sh
projects/bz2file/fuzz_bz2file.py
projects/bz2file/project.yaml

bz2file: initial integration

---

projects/babel/Dockerfile
projects/babel/build.sh
projects/babel/fuzz_lexer.py
projects/babel/fuzz_profile.py
projects/babel/project.yaml

babel: initial integration

---

projects/notary/project.yaml

update email addresses to view bugs using google accounts
Signed-off-by: Yi Zha <zhayi@outlook.com>

update email addresses to view bugs

---

projects/boringssl/project.yaml

Adding @bob-beck to the BoringSSL CC list.

Update CC list for BoringSSL

---

projects/apache-httpd/build.sh
projects/gpac/build.sh
projects/libiec61850/build.sh
projects/libredwg/build.sh
projects/libressl/Dockerfile
projects/libssh/build.sh
projects/lldpd/build.sh

Link fuzz targets with CXX instead of CC

Make fuzzers centipede-compatible

---

projects/defusedxml/Dockerfile
projects/defusedxml/build.sh
projects/defusedxml/fuzz_etree_parse.py
projects/defusedxml/fuzz_parseString.py
projects/defusedxml/fuzz_parse_string.py
projects/defusedxml/project.yaml

defusedxml: initial integration

---

projects/httpretty/Dockerfile
projects/httpretty/build.sh
projects/httpretty/fuzz_httpretty_e2e.py
projects/httpretty/project.yaml

httpretty: initial integration

---

projects/python-rison/Dockerfile
projects/python-rison/build.sh
projects/python-rison/fuzz_decode.py
projects/python-rison/fuzz_roundtrip.py
projects/python-rison/project.yaml

python-rison: initial integration

---

projects/wtforms/Dockerfile
projects/wtforms/build.sh
projects/wtforms/fuzz_validators.py
projects/wtforms/project.yaml

wtforms: initial integration

---

projects/nbformat/Dockerfile
projects/nbformat/build.sh
projects/nbformat/fuzz_read.py
projects/nbformat/project.yaml

nbformat: initial integration

---

projects/python-ecdsa/Dockerfile
projects/python-ecdsa/build.sh
projects/python-ecdsa/fuzz_ecdsa.py
projects/python-ecdsa/fuzz_eddsa.py
projects/python-ecdsa/fuzz_keys.py
projects/python-ecdsa/project.yaml

python-ecdsa: initial integration

---

projects/multidict/Dockerfile
projects/multidict/build.sh
projects/multidict/fuzz_md.py
projects/multidict/project.yaml

multidict: initial integration

---

projects/rfc3967/Dockerfile
projects/rfc3967/build.sh
projects/rfc3967/fuzz_rfc3986.py
projects/rfc3967/project.yaml

rfc3986: initial integration

---

projects/validators/Dockerfile
projects/validators/build.sh
projects/validators/fuzz_validators.py
projects/validators/project.yaml

validators: initial integration

---

projects/h11/Dockerfile
projects/h11/build.sh
projects/h11/fuzz_h11.py
projects/h11/project.yaml

h11: initial integration

---

infra/base-images/base-builder-fuzzbench/Dockerfile
infra/base-images/base-builder/fuzzbench_build
infra/helper.py

It shouldn't fail anymore now that the image is pushed. But just to be safe, I removed it from the images.

Reland #9646

---

projects/parso/parso_diff_fuzz.py

parso: extend suite

---

projects/black/Dockerfile
projects/black/build.sh
projects/black/fuzz_format_filecontents.py
projects/black/fuzz_lib2to3_parse.py
projects/black/fuzz_raw_format_filecontents.py
projects/black/project.yaml

black: initial integration

---

projects/rekor/build.sh

rekor: do not chmod upstream build script

---

projects/ghostscript/Dockerfile

Update should fix 49687 and 53321.

Update freetype for ghostscript to 2.13.0

---

projects/wolfssl/Dockerfile
projects/wolfssl/build.sh

'heapmath' is yet another bignum implementation in wolfssl that we would like to test.

[wolfssl] Add heapmath fuzzer

---

projects/tokio/Dockerfile
projects/tokio/build.sh
projects/tokio/project.yaml

tokio: Initial integration

---

projects/configparser/Dockerfile
projects/configparser/build.sh
projects/configparser/fuzz_dict.py
projects/configparser/fuzz_read.py
projects/configparser/project.yaml

configparser: initial integration

---

projects/dill/Dockerfile
projects/dill/build.sh
projects/dill/fuzz_dumps.py
projects/dill/project.yaml

dill: initial integration

---

projects/face/Dockerfile
projects/face/build.sh
projects/face/fuzz_command.py
projects/face/fuzz_parse.py
projects/face/project.yaml

face: initial integration

---

projects/aniso8601/Dockerfile
projects/aniso8601/build.sh
projects/aniso8601/fuzz_aniso8601.py
projects/aniso8601/project.yaml

aniso8601: initial integration

---

projects/mdit-py-plugins/Dockerfile
projects/mdit-py-plugins/build.sh
projects/mdit-py-plugins/fuzz_containers.py
projects/mdit-py-plugins/fuzz_plugins_individually.py
projects/mdit-py-plugins/project.yaml

mdit-py-plugins: initial integration

---

projects/python-pathspec/Dockerfile
projects/python-pathspec/build.sh
projects/python-pathspec/fuzz_pathspec.py
projects/python-pathspec/project.yaml

pathspec: initial integration

---

projects/pyyaml/fuzz_emitter.py

pyyaml: add emitter fuzzer

---

projects/tensorflow/build.sh
projects/tensorflow/fuzz_patch.patch

tensorflow: add more fuzztests

---

projects/tpm2-tss/build.sh

Fixes: https://github.com/google/oss-fuzz/issues/9695

tpm2-tss: extend build

---

projects/apache-commons-csv/build.sh
projects/apache-commons-csv/project.yaml

[apache-commons-csv] Updating project.yaml

---

projects/oak/Dockerfile

To match https://github.com/project-oak/oak/pull/3696

Update Rust version for Oak project

---

projects/dill/fuzz_dumps.py

Fixes e.g. 
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=55923
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=55984

dill: catch recursion errors

---

projects/tailscale/Dockerfile

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=55690

tailscale: build with Go 1.20.1

---

infra/helper.py
projects/vulnerable-project/solution.seed

[fuzzbench] Get crash detection working

[fuzzbench] Get crash detection working

---

projects/binutils/fuzz_as.c

Correct binutils/fuzz_as.c fakeArgc

---

projects/validators/fuzz_validators.py

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=56185

validators: fix build

---

docs/_config.yml

Updated Documentation google analytics from UA to GA4
Resolves #9743

Updated Google Analytics

---

projects/ngolo-fuzzing-x/build.sh
projects/ngolo-fuzzing/build.sh

Should allow to find new bugs such as https://github.com/golang/go/issues/58642

ngolo-fuzzing: generate corpus for targets

---

projects/ngolo-fuzzing-x/build.sh
projects/ngolo-fuzzing/build.sh

More corpus for ngolo-fuzzing
By running `go test` in a dummy package copying the files from the real package, so as to avoid imports cycles

Ngolo coverage through corpus

---

projects/php/project.yaml

@dstogov Can you confirm that this is ok?

Add myself (Ilija Tovilo) to PHP project

---

projects/libecc/build.sh

This is another hash function supported by libecc

[libecc] Support BASH hash

---

infra/base-images/base-builder-go/ossfuzz_coverage_runner.go
infra/base-images/base-runner/coverage
infra/base-images/base-runner/gocoverage/gocovsum/gocovsum.go

@AdamKorcz what do you think of these commits ?
cf https://github.com/google/oss-fuzz/pull/8937 and should fix https://github.com/google/oss-fuzz/issues/9808

infra: Golang coverage fixes

---

infra/build/build_status/update_build_status.py
infra/build/build_status/update_build_status_test.py

Add main_repo to build status.json

---

projects/markdown-it-py/project.yaml

markdown-it-py: add primary contributor

---

projects/croaring/croaring_fuzzer_cc.cc

@silvergasp contributed a great test function in https://github.com/google/oss-fuzz/pull/9794
It quickly found a new bug. Great.
Unfortunately, it is now running out of memory without bugs, causing false-positive reports. The problem is that a single bitmap may use slightly over 512 MB, furthermore, the function serialize the bitmap to a 32-bit array, which may lead to gigabytes of memory usage.
I propose to replace the unbounded `ConsumeIntegral<uint32_t>()` throughout by `ConsumeIntegralInRange<uint32_t>(range_start, range_end)` for reasonable range values. This should avoid unreasonable memory usage in the normal course of operation. That is, we want that an out-of-memory error has to do with a bug.
cc @K2  @DavidKorczynski

croaring: fix cpp fuzz harness

---

projects/apache-cxf/.gitignore
projects/apache-cxf/Dockerfile
projects/apache-cxf/build.sh
projects/apache-cxf/project-parent/fuzz-targets/pom.xml
projects/apache-cxf/project-parent/fuzz-targets/src/test/java/com/example/AttachmentDeserializerFuzzer.java
projects/apache-cxf/project-parent/fuzz-targets/src/test/java/com/example/AttachmentSerializerDeserializerFuzzer.java
projects/apache-cxf/project-parent/fuzz-targets/src/test/java/com/example/JsonMapObjectReaderWriterFuzzer.java
projects/apache-cxf/project-parent/fuzz-targets/src/test/java/com/example/XMLStreamReadersFuzzer.java
projects/apache-cxf/project-parent/pom.xml
projects/apache-cxf/project.yaml

Initial integration of Apache CXF.

Apache-CXF: Initial integration.

---

projects/aiohttp/fuzz_web_request.py
projects/azure-sdk-for-python/fuzz_mgmt_serialization.py
projects/black/fuzz_format_filecontents.py
projects/bz2file/fuzz_bz2file.py
projects/distlib/fuzz_metadata.py
projects/docutils/fuzz_rst.py
projects/flask-wtf/fuzz_flask_wtf.py
projects/flask/fuzz_json.py
projects/g-api-secret-manager/fuzz_parser.py
projects/g-cloud-logging-py/fuzz_helpers.py
projects/glom/fuzz_core.py
projects/glom/fuzz_mutation.py
projects/httpx/fuzz_decoders.py
projects/looker-sdk/fuzz_looker.py
projects/markdown-it-py/fuzz_markdown_extended.py
projects/markupsafe/fuzz_encoding.py
projects/mrab-regex/fuzz_match.py
projects/mrab-regex/fuzz_search.py
projects/multidict/fuzz_md.py
projects/netaddr-py/fuzz_parsing.py
projects/openapi-schema-validator/fuzz_general.py
projects/openpyxl/fuzz_basic.py
projects/packaging/fuzz_packaging.py
projects/pycparser/fuzz_c_parser.py
projects/pynacl/fuzz_hash.py
projects/python-ecdsa/fuzz_eddsa.py
projects/python-ecdsa/fuzz_keys.py
projects/sqlparse/fuzz_format.py
projects/tinycss2/fuzz_components.py
projects/validators/fuzz_validators.py

The argument to various consume functions eats up all of the data, am changing so not all data is used before the last part of the fuzzer.
Ref: https://github.com/google/oss-fuzz/pull/9864 https://github.com/google/oss-fuzz/pull/9864#pullrequestreview-1326908396

Python projects: Fixup string lengths

---

projects/fabric/build.sh

fabric: refactor build script

---

projects/golang/build.sh

golang: refactor build script

---

projects/moby/build.sh

moby: refactor build script

---

projects/ngolo-fuzzing-x/build.sh
projects/ngolo-fuzzing/build.sh

They will be used for coverage

ngolo-fuzzing-x: do not remove generated fuzz targets

---

projects/ipykernel/fuzz_serialization_roundtrip.py
projects/ipykernel/fuzz_unpack_roundtrip.py

Changes made:
- Made buffers more variable
- Change input of `deserialized_obj` to be more appropriate
- Fixed a spelling mistake of the variable `deserialized_obj`

ipykernel: improves code coverage

---

projects/kubernetes/Dockerfile
projects/kubernetes/build.sh

The git clone and wget calls have been removed from the build script.

kubernetes: wget and git clone in Dockerfile

---

projects/fonttools/project.yaml

Ref: https://github.com/fonttools/fonttools/issues/3041#issuecomment-1468613631
Ref: https://github.com/fonttools/fonttools/issues/3041#issuecomment-1468616607
CC @anthrotype @behdad

fonttools: add maintainers

---

projects/hermes/project.yaml

Update email addresses, and remove an inactive email address.

Change email addresses to @meta.com

---

projects/struts/project.yaml

Closes [WW-5291](https://issues.apache.org/jira/browse/WW-5291)

Apache Struts: Adds proper contact details

---

projects/sigstore-java/Dockerfile
projects/sigstore-java/build.sh
projects/sigstore-java/project.yaml

Adds initial integration of the sigstore java client.

sigstore-java: initial integration

---

projects/arrow/project.yaml

I am a committer and PMC member of Arrow:
https://arrow.apache.org/committers/
See email as example from:
https://github.com/apache/arrow/commit/8732b2785804d3c75c2e7c551ebec5e787214b47

Add Will Jones to arrow ccs

---

projects/istio/Dockerfile
projects/istio/build.sh

istio: bump Go
