- projects/flac/build.sh
- projects/flac/fuzzer_exo.cpp
This is an intermediate step towards fuzzing of out-of-memory conditions, which will be accomplished by making the Nth malloc/calloc/realloc fail. With this intermediate step, hopefully no oss-fuzz build failures will occur
> [flac] Intermediate step towards OOM fuzzing

- projects/uint256/Dockerfile
- projects/uint256/project.yaml
This PR adds https://github.com/holiman/uint256 to oss-fuzz.
`uint256` is a 256-bit math library in golang, and is used primarily within the Ethereum ecosystem, by projects such as [go-ethereum](https://github.com/ethereum/go-ethereum) and [erigon](https://github.com/ledgerwatch/erigon)
> projects: add uint256

- projects/skia/Dockerfile
- projects/skia/build.sh
Add fuzzer for COLRv1 glyph rendering, locally tested to run at >400
runs/s. Corpus file colrv1_seed_corpus.zip uploaded to bucket. The
corpus is mostly identical to the freetype2-testing COLRv1 corpus [2].
Fuzzer code for COLRv1 added in Skia in [1].
[1] https://skia-review.googlesource.com/c/skia/+/571934
[2] https://github.com/freetype/freetype2-testing/tree/master/fuzzing/corpora/colrv1
> [skia] Add COLRv1 fuzzer from upstream

- projects/bottleneck/Dockerfile
- projects/bottleneck/build.sh
- projects/bottleneck/fuzz_bn.py
- projects/bottleneck/project.yaml
Bottleneck has a lot of native code and this is also targetted by the fuzzers.
> bottleneck: initial integration

- .github/workflows/project_tests.yml
This uses emulation and depends on:
https://github.com/google/oss-fuzz/pull/8332
Related: #8164
> [aarch64] Add ARM support to GHA CI.

- .github/workflows/project_tests.yml
This reverts commit 5ccb903f178c42392090d729f3888926293edae8.
> Revert "[aarch64] Add ARM support to GHA CI. (#8333)"

- projects/hunspell/build.sh
- projects/hunspell/project.yaml
msan works fine, and using a project-side build script makes it more
flexible to extend hunspell's fuzzing
> hunspell: enable msan and use project build script

- projects/containerd/Dockerfile
- projects/containerd/build.sh
The only fuzzer we have there is containerd_import_structured_fuzzer.go
but it is ignored by build.sh since
https://github.com/cncf/cncf-fuzzing/pull/220.
Signed-off-by: Kazuyoshi Kato <katokazu@amazon.com>
> [containerd] remove cncf-fuzzing

- projects/go-toml/Dockerfile
- projects/go-toml/build.sh
- projects/go-toml/fuzz.go
- projects/go-toml/project.yaml
- projects/guice/build.sh
Hi,
[go-toml](https://github.com/pelletier/go-toml) is Go library for the [TOML](https://toml.io/en/) format. As per github's [network dependents](https://github.com/pelletier/go-toml/network/dependents), it is being used by projects like 
- [vercel/turborepo](https://github.com/vercel/turborepo), 
- [containrrr/watchtower](https://github.com/containrrr/watchtower),
- [cloudflare/cloudflare-go](https://github.com/cloudflare/cloudflare-go),
- [uber/cadence](https://github.com/uber/cadence),
- [hashicorp/terraform-provider-google](https://github.com/hashicorp/terraform-provider-google).
Edit: Also used by projects like
- [spf13/viper](https://github.com/spf13/viper) 
- [gohugo](https://gohugo.io/)
> go-toml: initial integration

- projects/uint256/Dockerfile
Fixes the build issue:
```
New issue 50607 by ClusterFuzz-External: uint256: Fuzzing build failure
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=50607
```
> uint256: fix failing build

- projects/lcms/cms_transform_extended_fuzzer.c
srcFormats of double was supported but never actually hit, which is due
to the bits in the srcFormat not actually being accurate, e.g.
T_BYTES(srcFormat) == 0 would never be satisfied. This includes in the
cms_transform_fuzzer. This is an effort to overcoming this.
> lcms: extend to have double as source format

- projects/containerd/project.yaml
https://github.com/containerd/project/blob/main/MAINTAINERS
Per https://google.github.io/oss-fuzz/faq/#why-do-you-require-a-google-account-for-authentication, these are all Google accounts.
> containerd: add some maintainers to auto_ccs

- infra/helper.py
To fix the following error:
```
File "/path/to/oss-fuzz/infra/helper.py", line 1178, in <module>
sys.exit(main())
File "/path/to/oss-fuzz/infra/helper.py", line 174, in main
result = run_fuzzer(args)
File "/path/to/oss-fuzz/infra/helper.py", line 972, in run_fuzzer
return docker_run(run_args, architecture=args.architecture)
AttributeError: 'Namespace' object has no attribute 'architecture'
```
> Add `architecture` to `run_fuzzer_parser`'s namespace

- projects/openssh/build.sh
These seem to clash with the oss-fuzz environment leading to weird
crashes like monorail #50678
@daztucker
> [openssh] Turn off toolchain hardening flags in configure

- projects/fluxcd/Dockerfile
The project recently started moving into Go fuzz native, and using the codeintelligencetesting variant is causing the error below:
`/usr/local/bin/compile_native_go_fuzzer: line 35: addimport: command not found`
Once that is fixed by reinstalling `addimport`, the resulting fuzzers error with:
`ERROR: no interesting inputs were found`
This PR reverts https://github.com/google/oss-fuzz/pull/7683 for fluxcd which fixes the issue.
> fluxcd: Revert to base-builder-go to fix build

- projects/golang/fuzz_tiff_decode.options
- projects/golang/h2c_fuzzer.go
The `fuzz_tiff_decode` fuzzer seems to quickly progress to 4000-ish MB so bumping the limit. 
> golang: minor updates

- projects/cryptofuzz/build.sh
mini-gmp is an alternative, self-contained version of libgmp (but maintained within the same project).
This builds the OpenSSL-based fuzzers with the regular libgmp, and the BoringSSL-based fuzzers with mini-gmp.
> [cryptofuzz] Add mini-gmp

- projects/golang/h2c_fuzzer.go
Fixes https://oss-fuzz.com/testcase-detail/5265203150848000 which is a false positive.
> golang: fix false positive

- projects/igraph/Dockerfile
With the release of igraph 0.10, most development will happen on the master branch for a while, so I'd like to switch OSS-fuzz over.
> igraph: switch to master branch and update libxml2 dependency

- projects/apache-commons-configuration/INIConfigurationReadFuzzer.java
- projects/apache-commons-configuration/INIConfigurationWriteFuzzer.java
- projects/apache-commons-configuration/JSONConfigurationReadFuzzer.java
- projects/apache-commons-configuration/JSONConfigurationWriteFuzzer.java
- projects/apache-commons-configuration/XMLConfigurationWriteFuzzer.java
- projects/apache-commons-configuration/YAMLConfigurationReadFuzzer.java
- projects/apache-commons-configuration/YAMLConfigurationWriteFuzzer.java
- projects/httpcomponents-client/ByteArrayBodyWriteToFuzzer.java
- projects/httpcomponents-client/Dockerfile
- projects/httpcomponents-client/FileBodyWriteToFuzzer.java
- projects/httpcomponents-client/FormBodyPartBuilderBuildFuzzer.java
- projects/httpcomponents-client/HttpFuzzer.java
- projects/httpcomponents-client/InputStreamBodyWriteToFuzzer.java
- projects/httpcomponents-client/StringBodyWriteToFuzzer.java
- projects/httpcomponents-client/build.sh
- projects/httpcomponents-client/project.yaml
Disclaimer: this PR includes changes to 2 different projects because I opened my PRs to the same Code Intelligence branch by mistake and nobody noticed until after the merge.
In genereal, I added missing copyright headers.
`commons-configuration`:
- removed logging
- improved temporary file creation and deletion
- added fuzz target for `XMLConfiguration.write`
- added option to fuzz multiple overloaded `YAMLConfiguration.read` methods
`httpmime`:
new fuzz targets for:
- `ByteArrayBody.writeTo`
- `FileBody.writeTo`
- `InputStreamBody.writeTo`
- `StringBody.writeTo`
- `FormBodyPartBuilder.build`
> Changes to apache-commons-configuration and new fuzz targets for httpmime

- infra/base-images/base-builder/compile_centipede
- Replace newlines with spaces in centipede/clang-flags.txt. Build
systems don't like them.
- Fix a missing newline in output logs.
> Centipede fixes.

- projects/crossplane/project.yaml
This PR proposes to add `alper.oss.fuzz@gmail.com` to the `auto_ccs` list for the Crossplane project. I'd like to be able to access the relevant resources/documents on the https://oss-fuzz.com site with the `Sign in with Google` option and authenticate as `alper.oss.fuzz@gmail.com` via SSO. Thank you.
cc. @jbw976
> Add alper.oss.fuzz@gmail.com to Crossplane auto_ccs

- projects/tpm2-tss/Dockerfile
No need for python stuff and libsqlite, so remove it.
Signed-off-by: William Roberts <william.c.roberts@intel.com>
> Dockerfile: drop unused packages

- projects/xs/Dockerfile
Removes the parser tests from seed corpus, and adds actual test262 builtins
> fix(xs): add test262 built-ins for seed corpus

- projects/util-linux/project.yaml
to make it easier to keep track or them and turn off i386 for now to let it compile everywhere else until https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51067 is fixed.
> [util-linux] file issues on GitHub as well 

- infra/base-images/base-clang/checkout_build_install_llvm.sh
It's unneeded and adds 100MB of unneeded bloat.
> Don't install clang-repl

- infra/base-images/base-builder/compile_honggfuzz
- infra/base-images/base-runner/run_fuzzer
- projects/mongoose/Dockerfile
- projects/mongoose/build.sh
- projects/mongoose/fuzz_netdriver_http.c
Adds an example with the mongoose webserver
> infra: add support for netdriver fuzzing with honggfuzz

- projects/php/Dockerfile
The php i386 build is broken since the last clang roll, due to a bug on the clang side. This should get fixed when clang is updated again, but for now pin to an older version.
FYI I also submitted https://github.com/AFLplusplus/AFLplusplus/pull/1516 to hopefully unblock the clang 15 update.
> Pin php to older clang version

- projects/dbus-broker/build.sh
It should be passed to meson as well to build `dbus-broker` with the alignment check.
> [dbus-broker] fix the alignment check

- infra/base-images/base-builder/Dockerfile
- infra/base-images/base-runner/run_fuzzer
Update `Centipede` to fix [the SegFault when using `AddressSanitizer` with `address_space_limit_mb`](https://github.com/google/centipede/issues/166).
Also set `address_space_limit_mb` as the issue has been fixed.
> Update Centipede to fix SegFault

- projects/toml_edit/Dockerfile
- projects/toml_edit/build.sh
- projects/toml_edit/project.yaml
Hi, [toml_edit](https://github.com/ordian/toml_edit) crate allows you to parse and modify toml documents, while preserving comments, spaces and relative order or items. 
- It has 2 million+ downloads as per [crates.io](https://crates.io/crates/toml_edit).
- It's being used by projects like [cargo](https://github.com/rust-lang/cargo), [diem](https://github.com/diem/diem), [lapce](https://github.com/lapce/lapce), [materialize](https://github.com/MaterializeInc/materialize), [clap](https://github.com/clap-rs/clap), [foundry](https://github.com/foundry-rs/foundry) as per [github's dependent graph](https://github.com/ordian/toml_edit/network/dependents?dependent_type=PACKAGE&package_id=UGFja2FnZS0zMjE3NzcwMjM2) and [crates.io's reverse …
> toml_edit: initial integration

- projects/cloud-hypervisor/build.sh
New fuzzers since last update: virtio-{balloon, pmem, rng, watchdog}
Signed-off-by: Rob Bradford <robert.bradford@intel.com>
> cloud-hypervisor: Add additional fuzzers

- projects/igraph/Dockerfile
I have moved the libxml2 download to the build script from the Dockerfile, so I can more easily update the version, and related operations would not be split up. Is this okay with you?
See https://github.com/igraph/igraph/commit/5a89bbc76c8016de44fd273d06cce809e2c45316
> igraph: move libxml2 download to build script

- infra/base-images/base-builder/Dockerfile
A recent commit allows `Centipede` to add timestamps to its log, which can be very helpful for debugging.
This PR intends to update `Centipede` to add that commit.
> Pin Centipede to a more recent version

- projects/cilium/Dockerfile
Ciliums fuzzers break with the testing image. Changing to get them running.
> cilium: change base image

- infra/base-images/base-builder/install_go.sh
Most projects have upgraded to 1.19 which is the latest version.
This upgrades Go to 1.19 in the base-image.
> infra: bump Go to 1.19

- projects/cel-go/fuzz_eval.go
With the most recent update to cel-go, the legacy proto package has been completely replaced
by the v2 proto API. This change updates the import to reflect code present in the cel-go vendor
directory.
> Update proto dep to v2 api

- infra/build/functions/deploy.sh
- infra/build/functions/project_sync.py
- infra/build/functions/project_sync_test.py
- infra/build/functions/requirements.txt
Download the zip and unzip it instead. There should be enough memory for this on the tmpfs environment on Cloud Functions, but bump up the memory to 4GB just in case.
Create a `OssFuzzRepo` which replicates the GitHub client library to avoid changing too many things. 
Fixes #8565
> Don't use GitHub API for project syncs.

- projects/spdk/build.sh
Recently, isa-l become a hard dependency in SPDK (dd2c08d2d) and the `--without-isal` option was removed, so we also need to remove it here.
> spdk: remove --without-isal option

- infra/experimental/SystemSan/SystemSan.cpp
cc @oliverchang 
This allows to get rid of false positives such as https://github.com/google/oss-fuzz/blob/master/projects/phmap/phashmap_fuzz.cc#L33 and others which try to scan non-existing directories such as /config
> SysSan: stricter file open detection

- projects/golang/h2c_fuzzer.go
The fuzzer triggers this crash, https://oss-fuzz.com/testcase-detail/5149758935400448, which I cannot reproduce locally. This PR is an attempt to fix it.
> golang: modify h2c fuzzer

- projects/xmltodict/unparse_parse_fuzzer.py
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51810
> xmltodict: don't fail on recursion error

- projects/cryptography/fuzz_dh.py
Fix error handling or other false-positive bugs reported for projects issues.
- 48484 (https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=48484)
> pyca-cryptography: Fix issue 48484 integer overflow

- projects/oauth2/fuzz_helpers.py
Fix error handling for issue
51904 (https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51904)
> [oauth2]: fix unicode error and other error handling for issue 51904

- projects/retry/fuzz_retry.py
Add in empty ValueError handling for solving issue 
51692 (https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51962)
> [retry]: Fix empty message handling

- projects/go-containerregistry/Dockerfile
- projects/go-containerregistry/build.sh
- projects/go-containerregistry/fuzz.go
- projects/go-containerregistry/project.yaml
go-containerregistry is a golang library for working with container registries. It is used by several projects already integrated in OSS-Fuzz like [Istio](https://github.com/istio/istio/blob/master/pkg/wasm/cache.go#L32) and [Crossplane](https://github.com/crossplane/crossplane/blob/dd87bfb23c83442fb72d0c3c0e20d5979d9d3a92/internal/xpkg/fetch.go#L28-L32).
__________________________________________________________
@imjasonh Do you prefer integrating with OSS-Fuzz instead of merging https://github.com/google/go-containerregistry/pull/1421? If so, here is the PR for that
> go-containerregistry: intitial integration

- projects/apache-httpd/Dockerfile
- projects/libyang/Dockerfile
pcre2 is now on Github. Fixes both builds.
> apache-httpd, libyang: fix pcre2 location

- projects/selinux/Dockerfile
The SELinux userspace has been ported to default to build with PCRE2[1].
[1]: https://github.com/SELinuxProject/selinux/commit/4ffe2dfc782465ab3807db49d0f6f67bce9e3e72
> [selinux] replace PCRE by PCRE2

- projects/git/Dockerfile
- projects/git/Makefile.diff
- projects/git/build.sh
- projects/git/fuzz-cmd-base.c
- projects/git/fuzz-cmd-base.h
- projects/git/fuzz-cmd-diff.c
- Match with latest upstream changes where some fuzzing PRs have gone through (https://github.com/git/git/commit/600f45a53b508698ba81a2266d0b9acdca1d51eb)
- Add checks on return values from cmd_add and cmd_git to avoid proceeding in the event something erroneous happen
- Refine fuzz-cmd-diff
- Add leak detection
- Adds some patching in the git code to avoid exit. This should be okay -- at least the fuzzers continue to run on my system. Let's see if down the line some type of state gets cluttered.
This makes the diff and command fuzzer run well on my machine and we have no dependencies on executables on the platform besides standard linux utilities.
> git: refine set up

- projects/mapserver/project.yaml
- Remove Max Kellerman who is not in the project team and has indicated not being interested to receive messages
- Add Steve Lime, who is the project lead (cf https://www.osgeo.org/foundation-news/steve-lime/)
> [MapServer] Update contacts

- projects/gpsd/project.yaml
The maintainer does not want these reports.
Fixes https://github.com/google/oss-fuzz/issues/8658
> Disable ubsan for gpsd

- projects/mapserver/project.yaml
It causes false positives due to a number of mapserver dependencies not being rebuilt with it.
Also rely on default settings for the sanitizers and fuzzing_engines section
> [mapserver] Disable memory sanitizer

- projects/git/build.sh
- projects/git/fuzz-cmd-diff.c
Reset git system config for each iteration and print debug message of folder construction.
Allowing error message to display.
> [git]: Remove git system config and add debug message

- projects/samba/project.yaml
Add primary email for Andrew Bartlett to the Samba Project to allow GitHub authentication
> Add abartlet's primary e-mail to Samba project

- projects/msquic/Dockerfile
- projects/msquic/build.sh
- cmake 3.16 (default version) might not work as expected with -Static option
- Specifying exactly three option `-DisableTest -DisableTools -DisablePerf` doesn't generate libmsquic.a, then link error for fuzzing code
> Fix link issue

- projects/cryptsetup/Dockerfile
- projects/cryptsetup/build.sh
- projects/cryptsetup/project.yaml
This patch adds fuzzers built for the upstream cryptsetup project.
Initially, we try to fuzz LUKS2 on-disk format using various binary and JSON header modification methods.
This produces basic coverage on on-disk header parsing code.
Fuzzers for other formats like LUKS1 will be added later.
Currently, we enable only binary fuzzer and plain JSON mutator with a pre-generated corpus from previous experiments.
Changes based on Daniel Zatovic's work.
> [cryptsetup] Initial integration for cryptsetup

- projects/h3/project.yaml
Adds [nrabinowitz](https://github.com/nrabinowitz) to the list of maintainers for https://github.com/uber/h3
cc @isaacbrodsky
> [h3] Add @nrabinowitz to the list of H3 maintainers

- projects/file/magic_fuzzer.cc
- projects/file/magic_fuzzer_fd.cc
Having libmagic fork and call `exit` in the children angers and saddens oss-fuzz's infra.
> Don't allow libmagic to fork

- projects/python-tabulate/fuzz_tabulate.py
To avoid e.g. recursion errors as well, since this is irrelevant to python-tabulate.
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=49986
> python-tabulate: avoid any exceptions from json

- projects/kcodecs/build.sh
To build translations we need more qt stuff, so just delete translations
> kcodecs: Fix build

- projects/unrar/project.yaml
I'm working on moving the fuzzing for unrar from OSS-Fuzz to the Chromium repo (https://crrev.com/c/3939973), and need to copy the existing corpus between repos. https://google.github.io/oss-fuzz/advanced-topics/corpora/#obtain-access indicates that I need auto_cc access in order to do this.
> Add drubery@chromium.org as auto_cc for unrar

- projects/git/fuzz-cmd-base.c
- projects/git/fuzz-cmd-diff.c
This should fix:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52080
Maintains a bit of debug logic in order to understand the logs from oss-fuzz runtime better.
> git: avoid config commands and use environment variables

- projects/libarchive/libarchive_fuzzer.cc
Taken from https://github.com/libarchive/libarchive/blob/1385cd9c5126d9b681b7396ad2f353779ad143ba/libarchive/test/test_write_format_zip_large.c#L293 while waiting for https://github.com/libarchive/libarchive/issues/1788
> Ignore crc32 in zip files in libarchive

- projects/rust-brotli/Dockerfile
- projects/rust-brotli/build.sh
- projects/rust-brotli/fuzz/Cargo.toml
- projects/rust-brotli/fuzz/fuzz_targets/decompress.rs
- projects/rust-brotli/fuzz/fuzz_targets/roundtrip.rs
- projects/rust-brotli/project.yaml
Rust-brotli is a popular compressor and decompressor for rust. It has 6 million downloads with 35k downloads every day. It is also a dependency for a lot of rust libraries.
> initial integration of rust-brotli

- projects/libecc/build.sh
For certain technical reasons I want to use an older version of wolfSSL here. However, this older version contains a bug, which was found by this OSS-Fuzz project (https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52254). This PR patches the bug in the old version.
> [libecc] Patch wolfSSL

- projects/libarchive/build.sh
This should increase coverage by making libarchive ignore some crc computation results.
> Add two defines to libarchive's build

- projects/skia/Dockerfile
After https://skia-review.googlesource.com/c/skia/+/589411, we need python3 to properly sync deps.
Both this change and https://skia-review.googlesource.com/c/skia/+/590538 should resolve the issue.
> [skia] Force python3 for syncing third-party deps

- projects/protobuf-python/project.yaml
auto_cc individual google accounts and bug component for triage.
Per https://google.github.io/oss-fuzz/getting-started/new-project-guide/#primary, Google accounts are needed for full access, which is why individuals are listed explicitly instead of using groups.
This PR is similar to https://github.com/google/oss-fuzz/pull/8758 which does the same for protobuf-java.
> Update protobuf-python to +cc protobuf team

- projects/protobuf-java/project.yaml
auto_cc individual google accounts and bug component for triage.
Per https://google.github.io/oss-fuzz/getting-started/new-project-guide/#primary, Google accounts are needed for full access, which is why individuals are listed explicitly instead of using groups.
> Update protobuf-java to +cc protobuf team

- projects/upb/project.yaml
Per
https://google.github.io/oss-fuzz/getting-started/new-project-guide/#primary, Google accounts are needed for full access, which is why individuals are also listed explicitly instead of using groups.
> Update upb to +cc protobuf-oss-fuzz and team

- projects/pyjwt/fuzz_jwt.py
jwt functions like jwt.decode could raise PyJWTError exceptions (e.g. ExpiredSignatureError if the token is expired)
Fix error handling for issue:
- 50696 (https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=50696)
> pyjwt: catch PyJWTError exceptions

- projects/ghostscript/build.sh
- projects/ghostscript/gs_device_bmpmono_fuzzer.cc
- projects/ghostscript/gs_device_eps2write_fuzzer.cc
- projects/ghostscript/gs_device_faxg3_fuzzer.cc
- projects/ghostscript/gs_device_pdfwrite_opts_fuzzer.cc
- projects/ghostscript/gs_device_pgmraw_fuzzer.cc
- projects/ghostscript/gs_device_png16m_fuzzer.cc
- projects/ghostscript/gs_device_ps2write_fuzzer.cc
- projects/ghostscript/gs_device_psdcmyk_fuzzer.cc
- projects/ghostscript/gs_device_pxlcolor_fuzzer.cc
- projects/ghostscript/gs_device_pxlmono_fuzzer.cc
- projects/ghostscript/gs_device_tiffsep1_fuzzer.cc
- projects/ghostscript/gs_device_xpswrite_fuzzer.cc
- projects/ghostscript/gs_fuzzlib.h
Fuzzer that will randomise more options for the ghostscript. First try this out with interpolation, where the goal is to increase coverage of base/gxiscale.c
> ghostscript: add pdfwrite options fuzzer

- projects/protobuf-python/Dockerfile
- projects/protobuf-python/build.sh
We currently have 3 implementations of protobuf-python (pure python, C++, and upb).  upb has been the default implementation since 21.x though, and we should be fuzzing against that one.  The other two will eventually be turned down.
> Move protobuf python to upb

- infra/experimental/SystemSan/SystemSan.cpp
cc @oliverchang @Alan32Liu 
This patch is meant for `tgkill` to use the right thread, so that we get the right stack trace every time
> SystemSan: use tgkill on precise pid

- projects/git/fuzz-cmd-diff.c
Fixes various early exits atm:
- https://storage.cloud.google.com/git-logs.clusterfuzz-external.appspot.com/libFuzzer_git_fuzz-cmd-diff/libfuzzer_asan_git/2022-10-17/05%3A05%3A41%3A777284.log
- https://storage.cloud.google.com/git-logs.clusterfuzz-external.appspot.com/libFuzzer_git_fuzz-cmd-diff/libfuzzer_asan_git/2022-10-17/05%3A05%3A36%3A470438.log
> git: fix branch name during diffing

- projects/xs/project.yaml
This PR adds Raphael to the oss-fuzz perms for XS
CC: @raphdev
> fix(xs): Add Raphael to oss-fuzz perms

- projects/bzip2/bzip2_filename.c
Should increase functional coverage of BZIP2 from 60% to 80%
> BZIP2: new BZ2_bzWrite & BZ2_bzRead fuzz driver.

- projects/golang/Dockerfile
- projects/golang/build.sh
- projects/golang/multipart_fuzzer.go
Adds an updated version of [this fuzzer](https://github.com/AdamKorcz/go-fuzz-corpus/blob/master/multipart/main.go) that invokes the garbage collector manually. 
This prevents _some_ incorrect OOM crashes reported by OSS-Fuzz, for example https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52536
> golang: fix multipart fuzzer

- projects/miniz_oxide/Dockerfile
- projects/miniz_oxide/build.sh
- projects/miniz_oxide/project.yaml
Hi, [miniz_oxide](https://github.com/Frommi/miniz_oxide) is a pure rust replacement for the [miniz](https://github.com/richgel999/miniz) deflate/zlib encoder/decoder using no unsafe code.
- It has 60 million+ downloads as per [crates.io](https://crates.io/crates/miniz_oxide).
- It is being used by projects like:
- [backtrace-rs](https://crates.io/crates/backtrace)
- [flate2](https://crates.io/crates/flate2)
- [deflate-rs](https://crates.io/crates/deflate)
- [image-png](https://crates.io/crates/png)
> miniz_oxide: initial integration

- projects/ruby/project.yaml
We'd like to receive notification from oss-fuzz by our dedicated mail alias.
> Add oss-fuzz@ruby-lang.org to ruby

- projects/solidity/Dockerfile
Fixes failing build after https://github.com/google/libprotobuf-mutator/pull/207 was merged and source branch deleted.
> solidity: Revert to upstream LPM.

- projects/exiv2/Dockerfile
Call exiv2's `install_dependencies.sh` script rather than using a hard-coded list of packages. This should make the build less fragile when we add new dependencies to exiv2. (Example: https://github.com/Exiv2/exiv2/pull/2381.)
> Use the install_dependencies.sh script from the exiv2 repo

- projects/karchive/build.sh
- projects/kimageformats/build.sh
To build translations we need more qt stuff, so just delete translations
> kimageformarts/karchive: Fix build

- projects/abseil-cpp/project.yaml
- projects/alembic/project.yaml
- projects/arduinojson/project.yaml
- projects/aspell/project.yaml
- projects/skcms/project.yaml
Continuing #8690.
Given that `Centipede` passed CI tests of the 5 projects in #8690, we will gradually roll it out to let more real-world fuzzing targets benefit from it.
The second round contains the following 5 projects, **some of which are not from Google** (unlike round 1):
1. `skcms`,
2. `abseil-cpp`,
3. `alembic`,
4. `arduinojson`,
5. `aspell`.
Projects are selected because:
1. They are `C++` projects.
There will be another round (of 10 projects) as soon as we can confirm that Centipede works fine in this round.
> [Rolling out Centipede] Project 6 - 10

- projects/jackson-databind/AdaLObjectReader3Fuzzer.java
Fixes false positive that was reported due to insufficient checks in subtype validator in fuzzer.
> jackson-databind: fix false positive

- projects/swc/project.yaml
Hi. I'm the creator of the swc project. It stands for speedy web compiler.
https://swc.rs
SWC is used by some famous open-source projects like next.js, Parcel (v2), and Deno.
Lots of web developers use SWC indirectly via those open-source projects, and lots of web developers use `@swc/core` directly.
These users include ByteDance, Tencent, Shopify, Discord, Slack, and vscode
> swc: Initial integration

- docs/faq.md
- docs/getting-started/new_project_guide.md
Fix grammar, wording, and make it clearer what fuzz introspetor offers.
(make changes suggested in https://github.com/google/oss-fuzz/pull/8800)
> Improve fuzz introspector documentation.

- infra/base-images/base-builder/precompile_centipede
- projects/envoy/Dockerfile
- projects/libraw/Dockerfile
- projects/librdkafka/Dockerfile
We can't simply autoremove the packages it installs and it adds 500 MB to the image size.
> Don't use centipede's install script

- infra/base-images/base-clang/Dockerfile
CMake 3.21.1 is known to cause issues when building Qt.
> [infra] Upgrade cmake to latest release (3.24.2)

- projects/bluez/Dockerfile
- projects/bluez/build.sh
- projects/bluez/fuzz_hci.c
The current coverage of fuzz_hci is blocked. The coverage of the project works, but doesn't show up for fuzz_hci. Am not entirely sure why the reason is, but this commit should fix it.
> bluez: refine set up

- projects/containerd/Dockerfile
The repo is very small and Containerd needs to access older, stable versions ad-hoc.
> containerd: don't do shallow clone

- projects/kubeedge/Dockerfile
Signed-off-by: vincentgoat <linguohui1@huawei.com>
install go1.17 for KubeEdge when building fuzzers
Fix issue https://github.com/cncf/cncf-fuzzing/issues/232
cc @AdamKorcz
> install go1.17 for KubeEdge when building fuzzers

- projects/jwt-verify-lib/project.yaml
Initial integration steps following https://google.github.io/oss-fuzz/getting-started/accepting-new-projects/. Note this is a Google-owned project that is used in production, primarily via Envoy proxy.
> add new project jwt-verify-lib

- projects/clickhouse/build.sh
This is needed to add a new target in a separate PR in the ClickHouse repository.
> [clickhouse] Add more fuzzer targets

- infra/base-images/base-builder/compile
This avoids compiling certain parts of matplotlib, which speeds up runtime of fuzz-introspector runs locally by a significant (~5-10min) time.
Ref: https://github.com/ossf/fuzz-introspector/pull/579#issuecomment-1300339783 Ref: https://github.com/ossf/fuzz-introspector/issues/465
> infra: fuzz-introspector; install matplotlib from binary

- projects/libvips/Dockerfile
- projects/libvips/build.sh
- projects/libvips/project.yaml
The image formats we've selected to fuzz test libvips with are typically those likely to originate from untrusted sources, and this very much includes the web.
libjxl was added as a dependency of libvips around 18 months ago in anticipation the JPEG-XL format being adopted for the web. A year ago we added a couple of the libjxl maintainers to help triage OSS-Fuzz issues as its inclusion generated a relatively large number of new problems, including one that was later issued a CVE.
https://bugs.chromium.org/p/oss-fuzz/issues/list?q=libvips%20libjxl&can=1
The libvips maintainers would love for JPEG-XL to succeed as a format and we hope to add libjxl back soon, but for now we would like to remove it to help reduce the support overhead.
/cc @jcupitt
> libvips: remove libjxl dependency

- projects/trafficserver/Dockerfile
- projects/trafficserver/build.sh
- projects/trafficserver/fuzzer/FuzzEsi.cc
- projects/trafficserver/fuzzer/FuzzHTTP.cc
- projects/trafficserver/fuzzer/Makefile
- projects/trafficserver/project.yaml
Hello oss-fuzz Team,
FuzzHTTP is not deployed right now due to broken compile system against coverage and undefined sanitizer.
bug:https://github.com/apache/trafficserver/issues/9158
> [trafficserver] initial integration

- projects/protobuf-python/Dockerfile
Same temporary fix as https://github.com/google/oss-fuzz/pull/8914
Seems to be affected by https://github.com/google/oss-fuzz/issues/8915 per failures in https://github.com/google/oss-fuzz/actions/runs/3396815368/jobs/5648300142
> Add sha256 to Dockerfile

- projects/protobuf-java/project.yaml
- projects/protobuf-python/project.yaml
- projects/upb/project.yaml
Avoid clashing with labels used by envoy in https://github.com/google/oss-fuzz/blob/master/projects/envoy/project.yaml.
> Change label prefix for protobuf projects

- infra/base-images/base-builder/compile
Wrap wildcards in quotes as otherwise the script will autocomplete if there is a e.g. .json file in the current directory. This causes the wrong files to be moved, which means `all_cov.json` will not be moved to the introspector folder and thus wrong (no) coverage data will be used.
This error happens in e.g. g-api-auth-library-python
> infra: base-builder: compile: wrap find names in quotes

- projects/ngolo-fuzzing/build.sh
Was this the only project where this happened ?
Meant to fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52844
> ngolo-fuzzing: fix build by using python3

- infra/base-images/base-builder/compile_python_fuzzer
- infra/base-images/base-clang/Dockerfile
This is a follow-up to https://github.com/google/oss-fuzz/pull/8952
This bump is needed to have the Python projects work properly. Scan should be done for all projects now, so have switched it on by default in fuzz introspector.
Bump also contains
- Fix for util-linux where per-target coverage report links were broken.
- Reduced logging.
> infra: bump introspector and update python compile script

- infra/experimental/SystemSan/SystemSan.cpp
> SystemSan: log c_str to avoid additional buffered zeroes

- projects/util-linux/project.yaml
Let's add Thomas Weißschuh (https://github.com/t-8ch) to CC.
> add t-8ch to util-linux CC

- infra/build/functions/build_and_run_coverage.py
Skip using `-testing` bucket as it breaks coverage download under `trial_build`.
> Fix Introspector trial build

- infra/base-images/base-clang/Dockerfile
This has a fix for coverage urls for per-fuzzer coverage reports: https://github.com/ossf/fuzz-introspector/pull/605
> infra: bump fuzz introspector

- infra/helper.py
Currently if you make a coverage build for a particular architecture (e.g. aarch64), running the coverage command doesn't work as it assumes `x86_64`. This PR adds the `--architecture` flag present in other commands for parity, allowing to run coverage reports built for the matching architecture. 
Tested by running `build_fuzzers` and then `coverage` works as expected with defaults (x86_64).
Now `build_fuzzers` and then `coverage` also work when `--architecture aarch64` is used.
> added architecture flag to coverage helper command

- projects/xs/xst.options
The `detect_stack_use_after_return=1` option in `ASAN_OPTIONS` set by the runner seemed to cause the fuzzer to not pick up any coverage. 
I'm not quite sure why this happens. Any guidance would be appreciated. The fuzzer seems stuck with this flag set:
`python infra/helper.py run_fuzzer --corpus-dir ../corpus_xst_json/ xs xst_jsonparse -- seed=1`
```
INFO: seed corpus: files: 1728 min: 1b max: 131336b total: 336638b rss: 92Mb
#64	pulse  cov: 322 ft: 323 corp: 1/1b exec/s: 32 rss: 92Mb
#128	pulse  cov: 322 ft: 323 corp: 1/1b exec/s: 25 rss: 92Mb
#256	pulse  cov: 322 ft: 324 corp: 2/8b exec/s: 23 rss: 93Mb
#512	pulse  cov: 322 ft: 324 corp: 2/8b exec/s: 22 rss: 93Mb
#1024	pulse  cov: 322 ft: 324 corp: 2/8b exec/s: 22 rss: 93Mb
```
However disabling it seems to make progress, with the same …
> [xs] Disable stack-use-after-return detection

- projects/flac/build.sh
This PR adds to the flac fuzzer build script to include fuzzer_reencoder, which is a fuzzer for which the fuzz input is first decoded and then re-encoded. Additional coverage beyond what is currently achieved is fuzzing of metadata input to the encoder (which is copied from the decoded fuzz input) and the use of very large empty inputs
> [flac] Add fuzzer_reencoder

- infra/base-images/base-builder/Dockerfile
It takes up space, is uneeded and causes irrelevant data to be displayed in revisions.
> Remove centipede's .git

- projects/teleport/project.yaml
@jentfoo needs access to Teleport's OSS-Fuzz results.
> teleport: Add @jentfoo to `auto_ccs`

- projects/libarchive/libarchive_fuzzer.cc
archive_read_support_format_gnutar isn't' called in archive_read_support_format_all.
> Enable support for gnu-tar archive in libarchive

- projects/muparser/set_eval_fuzzer.cc
The recent versions of muparser are using `mu::ParserError`.
> Fix muparser

- projects/libarchive/Dockerfile
- projects/libarchive/build.sh
This makes the coverage reporting for lxml go away.
Ref:
https://github.com/ossf/fuzz-introspector/issues/580#issuecomment-1318961239
> libarchive: compile libxml without instrumentation

- projects/libwebsockets/build.sh
The current build applies ASAN flags always which hinders it from extracting coverage and fuzz introspector reports. This PR fixes it.
> libwebsockets: generalise build.

- projects/util-linux/project.yaml
Looks like util-linux no longer fails to compile on Ubuntu Focal due to https://oss-fuzz-build-logs.storage.googleapis.com/log-86fe7f9b-945a-4514-84ce-8f435b34dce0.txt so it should be possible to bring 32-bit builds back.
> [util-linux] bring back 32-bit builds

- projects/golang/build.sh
A couple of the packages in the latest upstream master make api calls that are not yet included in the Go binary used by OSS-Fuzz. This PR disables those fuzzers. They should work again with Go 1.20
> golang: fix broken build

- infra/base-images/base-builder/compile
- infra/base-images/base-builder/compile_python_fuzzer
- Pass coverage_url to both c/c++ and python report generation.
- Remove a double calling of introspector report generation.
> infra: base-builder: refine fuzz-introspector building

- projects/bazel-rules-fuzzing-test-java/Dockerfile
- projects/bazel-rules-fuzzing-test/Dockerfile
rules_fuzzing uses Bazel 4, which still expects `python` in `PATH`.
Work towards https://github.com/bazelbuild/rules_fuzzing/pull/212#issuecomment-1317260421
> bazel-rules-fuzzing-test: Link python to python3

- infra/base-images/base-builder/compile_centipede
Some projects use `-Werror` to turn all warnings into errors.
This affects `Centipede` as we do not separate build and linking flags as it expects, which leads to `unused-command-line-argument` warnings.
This PR disables turning that specific warning into errors and keeps the rest the same.
> Disable -Werror on unused-command-line-argument

- projects/pyodbc/fuzz_curs_exec.py
This is in contrast to writing it in /etc/, which the fuzzer does not have permission to in the bots.
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51308
> pyodbc: write .odbcinst.init file in /tmp/

- projects/javassist/Dockerfile
- projects/javassist/build.sh
- projects/javassist/pom.xml.diff
The default source and test source directory for maven project are src/main/java and src/test/java respectively. The author of Javassist does specify a non-traditional location for the source and test source and manually set it in the pom.xml. Although it does not affect the normal project build, it does affect jacoco coverage report generator to extract the source code of the project because Jacoco will not read the pom.xml settings and only scan the default source and test source directory for source code file. To remedy, this fix aim to do some folder movement to move the source and test source back to the default directory while pointing the pom.xml settings to the default directory. These changes allow the project compile and execute as normal and also allow jacoco correctly retrieve …
> [Javassist] Fix project directory and maven build script

- infra/base-images/base-builder/compile
- infra/base-images/base-builder/install_java.sh
Reuses the previous Jazzer file names so that no changes to ClusterFuzz are required.
> [infra] Update Jazzer to latest main

- projects/resiprocate/Dockerfile
Avoid building libfmt from source and just use a package. This is particularly needed to make CIFuzz faster: https://github.com/resiprocate/resiprocate/pull/283#issuecomment-1325218011
> resiprocate: speed up build

- projects/cryptofuzz/Dockerfile
The cryptofuzz build has been failing for a few days at the [install_go.sh](https://github.com/google/oss-fuzz/blob/41f9210a290a535d8b241c634359133334916240/projects/cryptofuzz/Dockerfile#L20) step. Removing the base-builder-rust commit, making it equivalent to [ecc-diff-fuzzer which uses the same code](https://github.com/google/oss-fuzz/blob/41f9210a290a535d8b241c634359133334916240/projects/ecc-diff-fuzzer/Dockerfile#L17-L20) (and whose builds succeeds), seems to fix the issue.
I'm not sure why cryptofuzz had the specific base-builder-rust commit in the first place?
> [cryptofuzz] Fix build

- projects/tarantool/build.sh
Add a line to `CMakeLists.txt` to ensure `-lc++` is added after `$LIB_FUZZING_ENGINE`.
This is done in the same way as the other two existing modifications.
We could probably request the project owners to add this (that code block is only used by `OSS-Fuzz`), but I suppose this also ensures it only affects `Centipede`.
> [tarantool] Append -lc++ after $LIB_FUZZING_ENGINE

- projects/fluxcd/Dockerfile
- projects/fluxcd/build.sh
Add support for auto discovery and build for all Go Native fuzz targets that exist within the range of Flux org repos defined.
Support for faster CI checks by only targeting the specific project when running against PRs.
(cc: @stefanprodan @hiddeco)
---
Would there be interest on having `loop_through_org_repositories` as part of infra?
This would enable Go Native projects to have auto discovery of fuzzers without the need of calling `compile_native_go_fuzzer` for each fuzzer they add into their repos.
> fluxcd: Add auto discovery for Go Native fuzz targets

- projects/envoy/build.sh
Following the Envoy-Mobile [project merge](https://github.com/envoyproxy/envoy/pull/24104) this PR fixes the bazel query to fetch the fuzzers.
> envoy: fixing build path after Envoy-Mobile was added

- projects/libevent/build.sh
Refine the libevent build. Currently, fuzz-introspector is broken due to a segfault that happens in LTO mode (probably a case of https://github.com/ossf/fuzz-introspector/issues/504 -- see https://oss-fuzz-build-logs.storage.googleapis.com/index.html#libevent and https://oss-fuzz-build-logs.storage.googleapis.com/log-73424dc1-43b3-4a1d-844e-a98d2f7f84db.txt) 
The fault only happens when building one of the tests.
This pr fixes it by not building tests and samples when building the project, which has a nice side effect of speeding it up too which will be helpful for the recent cifuzz integration https://github.com/libevent/libevent/pull/1382. 
CC @azat
> libevent: speed up build and fix fuzz-introspector

- projects/powerdns/build.sh
See https://github.com/PowerDNS/pdns/pull/9709
> powerdns: Build the YaHTTP target first, needed for the new fuzzing target

- projects/boringssl/Dockerfile
This is to fix https://crbug.com/oss-fuzz/53701, a build failure.
The Go from apt is old (1.13). Instead, use base-builder-go to pick up oss-fuzz's copy of Go. We're technically a C/C++ project, but since C/C++ is part of the baseline, we can just use the Go one.
If we ever need two languages, we can follow the advice in https://google.github.io/oss-fuzz/getting-started/new-project-guide/#dockerfile to run install_lang.sh. (Although after https://crbug.com/boringssl/542, we may not need Go anyway.)
> boringssl: Switch Docker base image to base-builder-go

- projects/powerdns/build.sh
Now that https://github.com/PowerDNS/pdns/pull/9709 has been merged.
> powerdns: Use the HTTP corpus for the YaHTTP fuzzing target

- projects/ndpi/build.sh
With MSAN sanitizer we need to instrument all the dependencies. See #9088
> nDPI: fix MSAN support

- projects/rnp/build.sh
Upcoming version of rnp (https://github.com/rnpgp/rnp/pull/1943) depends on a new library https://github.com/rnpgp/sexp cmake script can load and build it via FetchContent but this option is disabled by defauly An extra flag is required to enable it
cc: @ronaldtse
This is a contribution from [RNP](https://www.rnpgp.org) ([GitHub](https://github.com/rnpgp)), a product of [Ribose](https://www.ribose.com) ([GitHub](https://github.com/riboseinc)).
> cmake flag to support upcoming rnp changes

- projects/firefox/Dockerfile
Attempting to fix broken build:
```
Step #3 - "compile-libfuzzer-address-x86_64": [34m 1:59.04(B[m /work/obj-fuzz/dist/bin/firefox -unittest --gtest_death_test_style=threadsafe(B[m(B[m
Step #3 - "compile-libfuzzer-address-x86_64": XPCOMGlueLoad error for file /work/obj-fuzz/dist/bin/libmozgtk.so:
Step #3 - "compile-libfuzzer-address-x86_64": libgtk-3.so.0: cannot open shared object file: No such file or directory
Step #3 - "compile-libfuzzer-address-x86_64": Couldn't load XPCOM.
Step #3 - "compile-libfuzzer-address-x86_64": ********************************************************************************
Step #3 - "compile-libfuzzer-address-x86_64": Failed to build.
Step #3 - "compile-libfuzzer-address-x86_64": To reproduce, run:
Step #3 - "compile-libfuzzer-address-x86_64": python …
```
> [firefox] Add missing dep

- projects/libevent/Dockerfile
- projects/libevent/build.sh
- projects/libevent/fuzz_request_cb.c
- projects/libevent/parse_query_fuzzer.cc
- projects/libevent/utils_fuzzer.cc
Minor extensions to existing libevent fuzzer and a minor fuzzer that targets utils code. The utils fuzzer should be extended in the near future.
The honggfuzz netdriver is the main addition. This is relatively new addition in oss-fuzz (supporting netdriver fuzzers) so will start small and extend after observing how it runs.
> libevent: extend fuzzing suite

- projects/lxml/Dockerfile
- projects/lxml/build.sh
The dependencies coming from base-builder-python might be old, let's use the upstream ones that are downloaded by the setup.py script.
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=47038
> lxml: use upstream static dependencies

- infra/experimental/SystemSan/SystemSan.cpp
This is currently too noisy, and may mask our other sanitizers.
We can re-enable this once we have flag/options support.
> Disable arbitrary file read sanitizer.

- infra/experimental/SystemSan/Makefile
- infra/experimental/SystemSan/SystemSan.cpp
- infra/experimental/SystemSan/inspect_dns.cpp
- infra/experimental/SystemSan/inspect_dns.h
- infra/experimental/SystemSan/inspect_utils.cpp
- infra/experimental/SystemSan/inspect_utils.h
- infra/experimental/SystemSan/target_dns.cpp
- infra/experimental/SystemSan/vuln.dict
cc @oliverchang @Alan32Liu after #9100 and #8448
After compiling locally, I can see that
`./SystemSan ./target_dns -dict=vuln.dict`
crashes in a few seconds with
```
===BUG DETECTED: Arbitrary domain name resolution===
===Domain resolved: .f.z===
===DNS request type: 0, class: 256===
==315== ERROR: libFuzzer: deadly signal
#0 0x539131 in __sanitizer_print_stack_trace /src/llvm-project/compiler-rt/lib/asan/asan_stack.cpp:87:3
#1 0x457c48 in fuzzer::PrintStackTrace() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerUtil.cpp:210:5
#2 0x43c923 in fuzzer::Fuzzer::CrashCallback() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:233:3
#3 0x7fa57940041f  (/lib/x86_64-linux-gnu/libpthread.so.0+0x1441f) (BuildId: 7b4536f41cdaa5888408e82d0836e33dcf436466)
#4 0x7fa5793ff7db in send …
```
> SystemSan: arbitrary DNS resolution detection

- projects/kimageformats/build.sh
This should help to solve/avoid issues like https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=54130
> kimageformats: do not install documentation for libzip

- projects/knative/Dockerfile
- projects/knative/build.sh
- projects/knative/fuzz_activatornet.go
- projects/knative/fuzz_pkg_metrics.go
- projects/knative/fuzz_pkg_websocket.go
- projects/knative/json_fuzzer.go
- projects/knative/project.yaml
Knative is an incubating CNCF project that is the foundation of Googles Cloud Run: https://cloud.google.com/blog/products/serverless/knative-based-cloud-run-services-are-ga.
Other cloud providers line IBM Cloud Code Engine and Red Hat Openshift Serverless  offer managed Knative solutions: https://knative.dev/docs/install/knative-offerings.
> knative: initial integration

- projects/xs/build.sh
- projects/xs/xst.options
Previously in #7910 we added a wrapper that injected `detect_leaks=0` into our fuzz targets, as certain runs of the targets did not disable and it did not behave well with the allocator and gc (#7708). As far as I can tell this is no longer needed as most runs of the fuzzing target binary seem to use the options file to construct its arguments.
* The `run_fuzzer` command respects options.
* The `reproduce` command respects options (locally and in [reproducer reports](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=53429)).
Therefore, we should remove it. I've tested this running, reproducing, debugging, and coverage with no observed changes.
> [xs] Remove xs wrapper stub

- projects/ruby/fuzz_ruby_gems.c
I made a mistake when I implemented this workaround:
https://github.com/google/oss-fuzz/blob/6e299b2e237bde05759d55009084097f0869c244/projects/ruby/fuzz_ruby_gems.c#L288-L291
To ensure that the workaround code won't get dead-code-eliminated by a clever compiler optimization, I decided to feed bytes from the test data in as an argument:
https://github.com/google/oss-fuzz/blob/6e299b2e237bde05759d55009084097f0869c244/projects/ruby/fuzz_ruby_gems.c#L404-L406
But that code only gets run on the first iteration (it's protected by a static variable). That means that the code behaves differently when you're trying to reproduce a testcase. This PR fixes the bug by rewinding the bytestream back to the beginning after it's been used for the workaround code.
> Fix bug that affects reproducibility

- projects/cras/Dockerfile
* Switch from FTP to HTTPS
* Check checksum
* Simplify tarball unpack
Fixes https://crbug.com/oss-fuzz/54159.
cc @b92paul
> cras: Fix alsa-lib download

- projects/mrab-regex/fuzz_regex.py
They are uninteresting.
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=54203
> mrab-regex: avoid recursion error exceptions

- infra/helper.py
The corpus URL generated for fuzztest fuzzers is invalid due to the use of `@` and `.` characters in the fuzzer names.
The current URL created is e.g. `gs://fuzztest-raksha-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/fuzztest-raksha_value_test@NumberTest.RoundTripNumberThroughDatalogString/` whereas the correct URL is `gs://fuzztest-raksha-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/fuzztest-raksha_value_test-NumberTest-RoundTripNumberThroughDatalogString/`.
> infra: replace characters to fuzztest coverage urls

- projects/isodate/fuzz_parse.py
This is to make the introspector reports more clear, due to a current limitation in control-flow extraction in Python.
> isodate: make call to parse_date explicit

- infra/cifuzz/build_fuzzers.py
- infra/cifuzz/build_fuzzers_test.py
- infra/cifuzz/config_utils.py
They can do this by prefix the env var with CFL_EXTRA_. E.g. `CFL_EXTRA_BUILD_SERVICE_TOKEN=<redacted>`.
Fixes: https://github.com/google/oss-fuzz/issues/9170
> [CFL] Allow users to specify custom env vars for building/running

- infra/build/functions/build_lib.py
This is a follow-up to https://github.com/google/oss-fuzz/pull/9167 -- the change should also be applied in the build functions that are responsible for downloading the corpus.
> infra: build: provide correct corpus name

- projects/ndpi/build.sh
Enabling them in 3baf95b6ec9425509b1ea370621c82ad180a2f7a wasn't a great idea
> nDPI: disable debug logs

- projects/fluent-bit/build.sh
The build can take quite a while, which is a time drainer when testing fixes and new fuzzers. This improves it a lot.
> fluent-bit: speed up the build

- projects/knative/project.yaml
(Both my work and personal email addresses.)
I'm the main recipient of `security@knative.dev` emails at the moment, and it turns out by using the mailing list we'll need to get each recipient added here.
> Grant Evan access to Knative fuzzing repots

- projects/fluxcd/Dockerfile
- projects/fluxcd/build.sh
Main changes:
- Fixes issues caused by go-118-fuzz-build's dependencies causing `go.sum` to become out of sync, which results in broken build.
- Auto detects when a single project is being targeted (e.g. CI).
- Remove libgit2 dependencies that are no longer needed.
> fluxcd: Fix go.sum issues and improve CI support

- projects/glib/project.yaml
He’s an upstream maintainer:
https://gitlab.gnome.org/GNOME/glib/-/blob/ded3099afca49234f407f67d96b99e684a8ff336/glib.doap#L49-L55
Signed-off-by: Philip Withnall <pwithnall@endlessos.org>
> Add additional maintainer to GLib project configuration

- projects/resiprocate/Dockerfile
The resiprocate project switched its build system from autotools to CMake. The fuzzer build changes are [there](https://github.com/resiprocate/resiprocate/commit/9e84cc44b9a2dedefed7b1cd7183454749788410).
> [resiprocate]: build with CMake

- projects/cryptofuzz/Dockerfile
- projects/cryptofuzz/build.sh
Tests OpenJDK bignum and some cryptographic operations. Harness will be extended to support more crypto ops.
It doesn't have code coverage at the Java level but it rides on the coverage of other libraries, so it will process meaningful inputs and find bugs.
Only building for UBSAN because ASAN reports memory leaks that I think is just the JVM object that is created at startup and must be retained for the duration of the run, and ASAN doesn't make sense here anyway.
Any bugs found I will report privately to the OpenJDK project.
I had some issues getting this to work properly, if it causes too many spurious crashes I might disable it again.
> [cryptofuzz] Add OpenJDK

- infra/helper.py
by passing the "o" option to unzip to prevent it from asking whether files should be overwritten or not when it's run a few times in a row.
It's a follow-up to 7556698dbcf5fd06c37f10b46a73ee7ff397bfd1
Closes https://github.com/google/oss-fuzz/issues/9234
@DavidKorczynski could you take a look?
> [infra] make coverage work and make it less chatty

- projects/wireshark/Dockerfile
- projects/wireshark/build.sh
The "wireshark", "logray", and "sharkd" targets all depend on SpeexDSP (Wireshark commit ae14849864), so disable them. Don't install bison; we haven't needed it since 2020 (Wireshark commit f21cd2e23f).
Signed-off-by: Gerald Combs <gerald@wireshark.org>
> Wireshark: Update build options and dependencies.

- projects/libbpf/project.yaml
even though libbpf bug reports on Monorail are public and mirrored on GitHub it's necessary to have access to oss-fuzz.com to view full backtraces/statistics and so on.
cc @shunghsiyu
> [libbpf] add more libbpf contributors

- infra/helper.py
Make it possible to do a full run of introspector locally. This will make it a lot easier for users to integrate it into the fuzzer building workflow.
To trigger, just run: `python3 infra/helper.py introspector PROJ_NAME`
Other example commands:
`python3 infra/helper.py introspector --public-corpora PROJ_NAME` : will download the latest public corpus for project PROJ_NAME and use that when collecting coverage
`python3 infra/helper.py introspector --seconds=X PROJ_NAME`: will run the fuzzers for X seconds for corpus collection
`python3 infra/helper.py introspector PROJ_NAME LOCAL_PATH` will do the introspector run using the LOCAL_PATH as source code folder (for testing modifications)
CC @evverx -- please let me know if there are other features you might like.
Ref: …
> infra: make it possible to do a full introspector run

- projects/brpc/build.sh
using `-Wl,-rpath,'\$ORIGIN/lib'` in `LINKER_FLAGS` Fix Coverage Build failure.
base: https://github.com/google/oss-fuzz/pull/9233 fix `Issue 54390 in oss-fuzz: coturn: Coverage build failure`
> [brpc] Remove patchelf

- infra/helper.py
Those directories aren't empty usually so `rmdir` fails with
```
INFO:fuzz_introspector.json_report:Finish handling sections that need json output
INFO:__main__:Ending fuzz introspector report generation
INFO:__main__:Ending fuzz introspector post-processing
File "/home/vagrant/oss-fuzz-2/./infra/helper.py", line 1513, in <module>
sys.exit(main())
File "/home/vagrant/oss-fuzz-2/./infra/helper.py", line 192, in main
result = introspector(args)
File "/home/vagrant/oss-fuzz-2/./infra/helper.py", line 1243, in introspector
os.rmdir(introspector_dst)
OSError: [Errno 39] Directory not empty: '/home/vagrant/oss-fuzz-2/build/out/dbus-broker/introspector-report'
```
It should make it possible to run `introspector` a few times in a row when for example fuzz …
> [infra] delete directories with FI reports with rmtree

- projects/tpm2-tss/build.sh
Disable "Lets Trust TPM2Go" TCTI for fuzz testing as the only TCTI
Signed-off-by: William Roberts <william.c.roberts@intel.com>
> tpm2-tss: disable spi lt2go TCTI

- projects/bls-signatures/build.sh
This is the correct way to build without assembly optimizations, according to the maintainer, and this will resolve https://oss-fuzz.com/testcase-detail/5324515452518400
> [bls-signatures] Improve blst MSAN build

- projects/binutils/Dockerfile
Fixes the current error:
```
Step #3 - "compile-afl-address-x86_64": checking for the correct version of gmp.h... no
Step #3 - "compile-afl-address-x86_64": configure: error: Building GDB requires GMP 4.2+, and MPFR 3.1.0+.
Step #3 - "compile-afl-address-x86_64": Try the --with-gmp and/or --with-mpfr options to specify
Step #3 - "compile-afl-address-x86_64": their locations.  If you obtained GMP and/or MPFR from a vendor
```
> binutils: fix build

- infra/helper.py
The reports are written into `oss-fuzz/build/out/PROJECT/introspector-report/inspector/`
> Fix the introspector report directory in helper.py

- projects/fuzztest-raksha/build.sh
- projects/fuzztest-raksha/raksha-fuzztest.diff
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=54490
Related to https://github.com/google/oss-fuzz/issues/9261
Raksha updated googletest to avoid an old version that referenced the outdated platforms dependency.
Raksha still has some references to `@bazel_tools//platforms` e.g. https://github.com/google-research/raksha/blob/3205399ca08af4b69bbd306a664181aca0b56e6e/gcb/rbe/configs/path/config/BUILD#L23 but we can avoid these by limiting the bazel query for targets to the `src` folder using `export FUZZTEST_TARGET_FOLDER="//src/...`
> fuzztest-raksha: fix build

- projects/tcmalloc/build.sh
This resolves the current issues caused by
https://github.com/google/oss-fuzz/issues/9261
tcmalloc fails because of rules_fuzzing having issues with the above issues.
> tcmalloc: fix build by setting bazel to 5.4.0

- projects/cras/build.sh
https://crrev.com/c/4123919 caused -Werror,-Wmacro-redefined, due to ./configure passing -DHAVE_FUZZER=0 when not configured with --enable-fuzzer.
To fix that:
1. Use ./configure --enable-fuzzer instead of -DHAVE_FUZZER to avoid multiple definitions of the macro.
2. The default make rule would try to build the fuzzer itself. So instead we selectively build just the cras binary, which is enough to produce libcrasserver.a and libcras_rust.a.
3. The build dependency of cras_dbus_bindings.h in the Makefile is not properly specified, so we build it manually first.
Fixes https://crbug.com/oss-fuzz/54641.
> cras: Use --enable-fuzzer to pass -DHAVE_FUZZER=1

- projects/cryptsetup/project.yaml
The builds_per_day set to 2 seems to fit better cryptsetup project metadata.
Signed-off-by: Milan Broz <gmazyland@gmail.com>
> cryptsetup: increase builds_per_day

- projects/bignum-fuzzer/Dockerfile
- projects/bignum-fuzzer/build.sh
- projects/bls-signatures/Dockerfile
- projects/cryptofuzz/Dockerfile
- projects/cryptofuzz/build.sh
- projects/libecc/Dockerfile
- projects/libressl/Dockerfile
- projects/nettle/Dockerfile
- projects/nettle/build.sh
The certificate of https://gmplib.org/ has expired. The website displays the following message:
```
YES, THE CERTIFICATE IS EXPIRED. Sorry about that. We're working on the renewal process. Unfortunately, our SSL provider changes the renewal interface each year, and it is always a challenge to figure out what to do. Now the only actions are REGENERATE (actiually not, as the cert is expired), REVOKE (well, not desirable) and INTERMEDIATE CERTIFICATE (which is not an action but a thing, oh well.
```
But this is breaking a lot of builds and this still hasn't been fixed after a few days, so with this PR I'm instead downloading the libgmp source archive and bypass the certificate check and manually verify the sha256 hash of the downloaded file.
Only the `cryptofuzz` and `bignum-fuzzer` projects …
> Fix libgmp download in multiple projects

- infra/build/functions/trial_build/cloudbuild.yaml
We can make this public if we want.
You can observe the logs in real time by clicking on "details" of trial build, getting `$BUILD_ID` and then doing
`gsutil cat gs://oss-fuzz-trialbuild-logs/log-$BUILD_ID.txt`
> Log base-image part of trial builds to bucket

- projects/fonttools/fuzz_compile.py
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=54618
> fonttools: import correct module

- infra/base-images/base-builder/compile_centipede
Related: https://github.com/google/oss-fuzz/issues/9299
> [centipede] Turn off warnings during compilation.

- projects/bignum-fuzzer/Dockerfile
- projects/bignum-fuzzer/build.sh
- projects/cryptofuzz/Dockerfile
- projects/cryptofuzz/build.sh
I recently configured several projects to use a stable source archive of libgmp, instead of cloning from the repository, because the certificate gmplib.org had expired: https://github.com/google/oss-fuzz/pull/9314
gmplib.org have fixed their certificate so with this PR I'm cloning from the repo again.
> [cryptofuzz, bignum-fuzzer] Use libgmp repo again

- projects/quic-go/Dockerfile
- projects/quic-go/build.sh
The `qpack` repo was moved to https://github.com/quic-go/qpack
> quic-go: fix build because the qpack repo was moved

- projects/tinyusb/Dockerfile
- projects/tinyusb/build.sh
- projects/tinyusb/project.yaml
> tinyusb: initial integration

- projects/binutils/fuzz_bfd.c
- projects/binutils/fuzz_bfd_ext.c
- projects/binutils/fuzz_objcopy.c
bfd_init doesn't do much at the moment, but I'm planning on changing it to re-initialise static state, with the aim of getting rid of some of the flaky crashes reported by oss-fuzz.
> Call bfd_init on each test file

- projects/dgraph/build.sh
The `gql` package was renamed to `dql`
https://github.com/dgraph-io/dgraph/commit/186c9c23c46d4e4da3c30d4f2eb5820dc8c19985
> dgraph: fix build

- projects/etcd/Dockerfile
The `raft` package was moved into a dedicated repo https://github.com/etcd-io/raft
This PR is currently a draft because we should wait until the corresponding fix is merged in `cncf-fuzzing` (https://github.com/cncf/cncf-fuzzing/pull/271)
> etcd: clone the raft repo when building etcd

- projects/gitea/build.sh
gitea's fuzz targets now use Go native fuzzing, and they were moved into a dedicated `fuzz` package (https://github.com/go-gitea/gitea/pull/22376).
> Fix gitea's native fuzzers

- projects/libvnc/Dockerfile
- projects/libvnc/build.sh
- projects/libvnc/project.yaml
@bk138 would you be interested in continuous fuzzing for libvncserver ?
This PR can enable it with oss-fuzz.
If you are interested, I would be happy to see if we can improve and merge the libvnc patch to make it fuzzable.
(instead of using sockets to read from, we directory read from a buffer)
> Adds libvnc project

- projects/containerd/project.yaml
Kazuyoshi Kato is a containerd maintainer and has been working with @AdamKorcz to port fuzzers from cncf-fuzzing to containerd itself.
Signed-off-by: Kazuyoshi Kato <katokazu@amazon.com>
> Add Kazuyoshi Kato on containerd

- projects/helm/build.sh
heml specifies Go 1.17 as the minimum Go version, and this causes go mod tidy to fail because Go 1.17 and Go 1.16 would select different versions of a dependency (github.com/mattn/go-isatty). By default, tidy acts as if the -compat flag were set to the version prior to the one indicated by the 'go' directive in the go.mod file.
Since we use Go 1.19 to instrument the code, we patch the minimum version in go.mod.
> helm: fix build by patching Go minimum version in go.mod

- infra/bisector.py
The `run_function` is passed an `architecture` keyword argument:
https://github.com/google/oss-fuzz/blob/a8cb9370f0dddf33111b1a7ce6d715633d5400df/infra/helper.py#L1357
This makes the `run_function` passed in the bisector ignore all keyword arguments. 
Related: https://github.com/google/osv.dev/issues/963
> Fix exception in bisector.py

- projects/tensorflow/build.sh
Reduce the mount of CPUs for building Fuzztest fuzzers as this is causing the build to exhaust resources: https://oss-fuzz-build-logs.storage.googleapis.com/log-1f5769dc-3170-4205-bcda-17cd48c52985.txt
```
...
/src/tensorflow/tensorflow/core/kernels/BUILD:1038:18: Compiling tensorflow/core/kernels/pad_op.cc failed: (Killed): clang-15 failed: error executing command 
Step #12 - "compile-libfuzzer-undefined-x86_64":   (cd /root/.cache/bazel/_bazel_root/1c025c2968c1aa16bac5eca67aaf21d1/sandbox/linux-sandbox/3063/execroot/org_tensorflow && \
```
> tensorflow: limit CPUs used for fuzztest fuzzers

- projects/notary/Dockerfile
- projects/notary/build.sh
- projects/notary/fuzz_trustmanager_test.go
- projects/notary/project.yaml
Notary is an implementation of the TUF specification. It is a tool for publishing and managing trusted collections of content. Publishers can digitally sign collections and consumers can verify the integrity and origin of content.
Initially, Notary was sponsored by Docker who uses Notary for signing and verifying container images. Notary joined the CNCF in 2017 and is today used by companies such as:
- Amazon
- Docker
- Microsoft
______________________________________________________________________
@justincormack @marcofranssen @cyli @toddysm Are you interested in integrating notary into OSS-fuzz for continuous fuzzing?
This PR adds the build files for the cryptoservice fuzzer to be run continuously.
To complete this integration, one or more maintainers email addresses are needed.
> [notary] Initial integration

- projects/tensorflow/build.sh
Build only status_fuzz fuzztest for now in addition to all the non-fuzztest fuzzers. The build will be extended to new fuzztest fuzzers once the overall build starts passing again.
Recent commits on Tensorflow made the build not work  e.g. https://github.com/tensorflow/tensorflow/commit/77e348099872c2065c39267f4d309c54aed661a4 and the reason is we need proper diffing in place (e.g. remove `no_oss` in the BUILD tag).  These should be included in the build, but will handle that after the current build starts working agains.
> tensorflow: specify explicit fuzztest to build

- projects/tensorflow/build.sh
The build on the bots continue to exhaust memory usage as far as I can tell: https://oss-fuzz-build-logs.storage.googleapis.com/log-6f2d0692-4002-45b2-a1f4-01471de13add.txt However, the build is getting further now than before.
> tensorflow: reduce cpu usage further

- infra/base-images/base-builder/Dockerfile
Update Centipede to [its latest commit eb91dd2](https://github.com/google/centipede/commit/eb91dd2157710e6c82579f8be19d7fab9423b781), which added some new features and fixed runtime bugs found in recent FuzzBench experiments.
> Update Centipede to eb91dd2

- projects/rustls/build.sh
I am removing one of the existing fuzzers in https://github.com/rustls/rustls/pull/1171 (which should be subsumed by one of the existing ones). However, the fuzzing CI job that we run is currently failing because the build script hard codes the fuzzer names. Make an attempt at copying whatever the fuzzer builds instead.
I am not very experienced at shell stuff, but in some local testing this seems to do the job.
cc @ctz
> rustls: update build script to avoid hardcoding fuzzer names

- projects/fast-dds/Dockerfile
Should fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=53025 by fixing the asio version to the one used on Fast DDS as submodule. We could probably revert this after https://github.com/chriskohlhoff/asio/issues/1188 is solved.
> [fast-dds] Fix asio version to 1-18-1

- projects/imageio/build.sh
In order for code coverage to work we need to use `compile_python_fuzzer` when building the fuzzers
Fixes: https://github.com/google/oss-fuzz/issues/9442
> imageio: fix coverage build

- projects/libarchive/libarchive_fuzzer.cc
Some more codepaths were added to the fuzzer in
https://github.com/google/oss-fuzz/pull/9003 However, these paths are only valid to call in the event `archive_read_open_memory` returns `ARCHIVE_OK` -- the fuzzer is currently blocked due to this and is why the coverage decreased between 17th Nov to 19th Nov (https://storage.googleapis.com/oss-fuzz-coverage/libarchive/reports/20221117/linux/src/libarchive/report.html vs
https://storage.googleapis.com/oss-fuzz-coverage/libarchive/reports/20221119/linux/src/libarchive/report.html)
Am looking to get the coverage back up as I'm writing some documentation about
https://github.com/ossf/fuzz-introspector/issues/580#issuecomment-1318961239
@jvoisin could you help review?
> libarchive: handle erroneous archives

- infra/base-images/base-clang/Dockerfile
- infra/base-images/base-clang/checkout_build_install_llvm.sh
The main changes are:
- improvements to code injection sink analyser
- output of data about all functions into summary.json. This is useful for e.g. comparing reports and making historical analysis.
> infra: bump introspector

- projects/xs/build.sh
XS is a JavaScript engine, the typical timeouts aren't necessarily bugs -- it's expected that code will run for a long time. Over time the fuzzer has generated quite a few timeouts, near-infinite loops. 
We added metering to the XS fuzz target to cap execution to a number of steps. In this PR we set the limits to reduce the amount of timeouts. Timeouts that still reported are more likely to be bugs we should fix (either in engine or in metering feature itself).
> [xs] Set metering limits in xs fuzzer

- projects/hdf5/build.sh
This should enable fuzz introspector builds to run smoothly
> hdf5: simplify build

- projects/hermes/Dockerfile
- projects/hermes/build.sh
Currently, the Hermes setup does not use [a dictionary to help mutate input](https://google.github.io/oss-fuzz/getting-started/new-project-guide/#dictionaries). This PR adds JS dictionaries and edits the fuzzing setup to use `hermes.dict` during fuzzing.
> [hermes] Add JS dictionary to improve fuzzing efficiency

- projects/tensorflow/fuzz_patch.patch
Recent updates in upstream caused the latest build to fail. Am pushing these patches to ensure the build runs at the moment. The proper next step is to get rid of the patching but will do that later.
> tensorflow: update patch to match recent upstream changes

- projects/suricata/build.sh
The protocol needs to be the last item for fuzz_applayerparserparse
> suricata: good targets naming for version 6

- projects/suricata/build.sh
Rust MSAN produces false positives when C clang version is not up to the latest version.
See https://github.com/rust-lang/rust/issues/107149
Will fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=55239&q=label%3AProj-suricata and such
Should the fix be generic for other projects ?
> suricata: fix rust+C MSAN build

- infra/experimental/SystemSan/inspect_dns.cpp
by skipping final null byte of domain name
cc @Alan32Liu
> SystemSan: log correct dns type and class

- projects/quic-go/Dockerfile
- projects/quic-go/build.sh
- projects/quic-go/project.yaml
We recently moved the repo into its own org. See https://github.com/quic-go/quic-go/issues/3611 for motivation and tracking.
> quic-go: update repo path to quic-go/quic-go

- projects/bind9/build.sh
`isc__initialize()` is a libisc function that is marked with `__attribute__((constructor))`; it works as expected when the library is linked dynamically, but it gets stripped away in static builds prepared by OSS-Fuzz as it is not called directly by any of the fuzzers. However, one of the fuzzers (`fuzz/dns_message_checksig.c`) calls `dns_view_create()`, which calls `isc_file_sanitize()`, which in turn calls `isc_md(ISC_MD_SHA256, ...)`.  The latter does not work unless `isc__md_initialize()` is called beforehand and that function is in turn expected to be called by `isc__initialize()`.  Since the latter is absent from OSS-Fuzz builds, the `dns_message_checksig` fuzzer crashes on every input.
Since this is only an issue for static builds, which BIND 9 currently does not support except for …
> bind9: fix build by force-linking two symbols

- infra/cifuzz/fuzz_target.py
Just because nonzero is reported doesn't mean there's a crash.
Related: https://github.com/google/oss-fuzz/issues/9470 https://github.com/google/oss-fuzz/issues/9318
https://github.com/prometheus/prometheus/issues/11810
> [cifuzz] Dont report crash on process timeout.

- projects/parso/parso_fuzz.py
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=55379
> parso: catch recursion errors

- projects/wolfssl/build.sh
Cryptofuzz has a built-in corpus of inputs that can detect historic and/or hard to find bugs. https://github.com/guidovranken/cryptofuzz/blob/master/builtin_tests_importer.cpp
This change includes those inputs in the seed corpus.
> [wolfssl] Include Cryptofuzz built-in tests in seed corpus

- projects/ndpi/Dockerfile
- projects/ndpi/build.sh
We don't need libjson anymore since 3baf95b6
> nDPI: use dictionaries and remove libjson

- .github/workflows/presubmit.yml
- .github/workflows/project_tests.yml
Signed-off-by: jongwooo <jongwooo.han@gmail.com>
Updated workflows to cache dependencies using [actions/setup-python](https://github.com/actions/setup-python#caching-packages-dependencies). `setup-python@v3` or newer has caching **built-in**.
```yaml
- name: Setup python environment
uses: actions/setup-python@v3
with:
python-version: 3.8
```
```yaml
- name: Setup python environment
uses: actions/setup-python@v3
with:
python-version: 3.8
cache: pip
cache-dependency-path: |
infra/ci/requirements.txt
infra/build/functions/requirements.txt
infra/cifuzz/requirements.txt
```
- [https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows)
- …
> Use setup-python action to cache dependencies

- projects/libavc/Dockerfile
- projects/libavc/project.yaml
- projects/libhevc/Dockerfile
- projects/libhevc/project.yaml
- projects/libmpeg2/Dockerfile
- projects/libmpeg2/project.yaml
libavc, libhevc and libmpeg2 now have an upstream project and the fuzzers will be built from these paths from now on.
> [libavc, libhevc, libmpeg2]: Update repository paths

- infra/build/build_status/fuzz_introspector_page_gen.py
Some old reports e.g.
https://storage.googleapis.com/oss-fuzz-introspector/upb/inspector-report/20221025/summary.json have deprecated data. We should not display this information. Only show if the percentage numbers make sense.
> introspector_page: only display if numbers are accurate

- projects/skia/Dockerfile
- projects/skia/build.sh
This moves the fetching to the Dockerfile creation step, for better caching.
Note that gn is downloaded to skia/bin/gn, but ninja is downloaded to skia/third_party/ninja/ninja (for compatibility with depot_tools).
> [skia] Fix build by downloading and using ninja

- projects/gitoxide/build.sh
The previous configuration had a hardecoded list of fuzz harnesses. This was neccesary as some of the existing fuzz harnesses where broken and wouldn't compile. As these are now fixed, we can switch over to searching for new fuzz tests.
> feat(gitoxide): Adds autodetection of new fuzzers

- projects/croaring/build.sh
This is an effort to stabilise the fuzz introspector build which seems to segfault for some of the tests on-and-off
> croaring: do not build tests

- projects/muduo/build.sh
The examples are not needed. This reduces the build and helps avoid an error that affects the Fuzz Introspector build.
> muduo: do not build examples

- projects/spirv-tools/Dockerfile
SPIRV-Tools now requires some history to determine its version. This is done using tags on the current branch. Using --depth=1 was preventing the version to be generated correctly.
Using --filter=tree:0 should still limit the amount of fetch data, while giving us tags.
> spirv-tools: partially unshallow spirv-tools clone

- projects/c-blosc/build.sh
Do not build binaries that are not needed: tests, benchmarks and shared libraries. This will stabilise the Fuzz Introspector build which has been a bit spurious lately.
> c-blosc: simplify build

- projects/cmark/Dockerfile
- projects/cmark/build.sh
Generate seed corpus from our own test suite instead of relying on an external repo.
Also remove redundant $SRC/cmark from paths.
> cmark: Update seed corpus

- projects/tensorflow/build.sh
- projects/tensorflow/fuzz_patch.patch
The current coverage build of Tensorflow is broken because the rsync commands used copy all files build during the build process to OUT. This includes a lot of binaries that are not needed for coverage reports, and this added content causes ~100GB of data to be stored, which is why the current coverage build fails to due disk space limitations: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=47817
The coverage reports only need textual files. This PR fixes these isssues by using rsync with appropriate filters, which should make the coverage build work again.
Also fixes up the patch.
> tensorflow: enable coverage build

- projects/libjpeg-turbo/Dockerfile
- projects/libjpeg-turbo/build.sh
Use the contents of branches.txt in
https://github.com/libjpeg-turbo/fuzz to determine which libjpeg-turbo branches to build and fuzz.  This allows the libjpeg-turbo maintainer to control which branches will be tested with OSS-Fuzz, since that will change as new releases are added and support for old stable branches is dropped.
> [libjpeg-turbo] Use external repo to specify fuzz branches

- projects/c-ares/build.sh
The tests are not needed for fuzzing and avoiding to compile them makes the build Fuzz Introspector compatible
> c-ares: disable tests to make build fuzz introspector compatible

- projects/hiredis/build.sh
The dynamically shared libraries are not needed. This makes the build Fuzz Introspector compatible.
> hiredis: only build static libraries

- projects/crossplane/Dockerfile
- projects/crossplane/build.sh
Once https://github.com/crossplane/crossplane/pull/3671 all test cases will have been moved to `crossplane/crossplane`, so we can switch the build script to use that directly.
Signed-off-by: Philippe Scorsolini <p.scorsolini@gmail.com>
> crossplane: moved tests to project repository

- projects/tinyxml2/build.sh
Currently OSS-Fuzz flags are not set when building the tinyxml2 library due to https://github.com/leethomason/tinyxml2/blob/e05956094c27117f989d22f25b75633123d72a83/Makefile#L13. Consequentially, coverage is low (only that which is in the fuzzer source file). This fixes it by avoiding to overwrite the CXXFLAGS in the build.
> tinyxml2: make OSS-Fuzz flags are used in build

- projects/libvips/build.sh
The libvips build is currently failing due to an API change in `libjpeg-turbo` that "unlocked" a previously-unused feature of `libtiff`, which means the dependency order between the two must now change.
https://oss-fuzz-build-logs.storage.googleapis.com/index.html#libvips
> libvips: link with tiff before jpeg

- projects/qpdf/build.sh
qpdf's build has been failing with errors within its own build of libjpeg-turbo because of lack of position-independent code. This change forces libjpeg-turbo to build with PIC even though we continue to build only static libraries. I have reproduced the build failure locally using the fuzz docker images and have reproduced locally that this fixes it.
> Build qpdf's libjpeg-turbo with position-independent code

- projects/bitcoin-core/build.sh
After some changes we made upstream, passing the flags in this way *should* no-longer be required.
> bitcoin-core: drop additional dependency cflags passing

- projects/cgif/project.yaml
Enable memory sanitizer for [cgif](https://github.com/dloebl/cgif). I already found one small issue testing it locally (timeout crash reported by oss-fuzz):
```
$ ./build/fuzz/cgif_fuzzer_standalone clusterfuzz-testcase-cgif_fuzzer-6560939899224064
==26604==WARNING: MemorySanitizer: use-of-uninitialized-value
#0 0x7f6a00f022ba  (/home/dbl/projects/cgif/build/fuzz/../libcgif.so.0+0x162ba) (BuildId: 41f9aa2f4c1d42966ca54004a6e73b2e1bb38d78)
[...]
SUMMARY: MemorySanitizer: use-of-uninitialized-value (/home/dbl/projects/cgif/build/fuzz/../libcgif.so.0+0x162ba) (BuildId: 41f9aa2f4c1d42966ca54004a6e73b2e1bb38d78) 
Exiting
```
Fixed with https://github.com/dloebl/cgif/pull/57.
> cgif: enable memory sanitizer

- projects/wolfssl/Dockerfile
- projects/wolfssl/build.sh
Previously, fastmath was the default option, and the build script created a fuzzer without fastmath.
Some time ago, wolfSSL changed this so that no fastmath is the default option, and this PR creates a dedicated fuzzer for fastmath.
> [wolfssl] Create fastmath fuzzer

- projects/hermes/Dockerfile
Since libfuzzer, honggfuzz and AFL mutate at the byte level, mutating on bytes in JS comments likely won't cause any meaningful crashes, so this commit removes JS comments from files before we include them in the seed corpus
> [hermes] Strip comments from files in seed corpus

- projects/bluez/build.sh
- projects/clib/build.sh
- projects/croaring/build.sh
- projects/h3/build.sh
- projects/hdf5/build.sh
- projects/hiredis/build.sh
- projects/kamailio/build.sh
- projects/libdwarf/build.sh
- projects/libpg_query/build.sh
- projects/libucl/build.sh
- projects/libyang/build.sh
- projects/llhttp/build.sh
- projects/md4c/build.sh
- projects/postfix/build.sh
Previously, they would break because they incorrectly used $CC to link fuzz targets.
> Make many projects centipede compatible

- infra/base-images/base-runner/bad_build_check
- infra/base-images/base-runner/run_fuzzer
$OUT gets zipped up and included as part of the build.
Fixes #9345
> [centipede] Use /tmp for a workdir.

- infra/base-images/base-builder/compile
It's pointless and has these drawbacks:
1. It add useless instrumentation not used by centipede that slows down the target
2. It adds instrumentation that expects an implementation at link time (__sancov_lowest_stack) which can break projects builds.
Fixes https://github.com/google/oss-fuzz/issues/9609
Related: https://github.com/google/oss-fuzz/issues/9299 https://github.com/google/oss-fuzz/issues/9583
> Don't use -fsanitize=fuzzer-no-link with centipede

- infra/base-images/base-builder/Dockerfile
Waste of space in the 5MB limited logs.
> [NFC] Don't print output when untarring honggfuzz

- infra/base-images/base-builder/compile_centipede
1. Don't use trace-loads as it is not fully supported in LLVM and breaks many projects (see https://github.com/google/centipede/commit/9383870160a8cb1d10ec15e9ca85d4b589c8151e)
2. Use -Wl for link time options so they aren't unnecessarily used (also fixes meson based projects).
> Fix centipede compilation

- projects/cras/build.sh
For https://crrev.com/c/4218434.
Also fix Rust build to silence warning.
> cras: Use --config=fuzzer to set extra flags

- projects/serde_urlencoded/build.sh
- projects/serde_urlencoded/fuzz/Cargo.toml
- projects/serde_urlencoded/fuzz/fuzz_targets/reverse_roundtrip.rs
- projects/serde_urlencoded/fuzz/fuzz_targets/roundtrip.rs
The original fuzzer makes some assumptions on specific properties. Namely that Deserialise->Serialise->Deserialise was completely symmetrical. However support for some parts of the API only includes Serialising, so to fix this I've added the reverse/inverse fuzzer, which improves code coverage substantially.
> perf(serde_urlencoded): Add new fuzzer, to improve coverage

- infra/build/functions/build_lib.py
This is needed for Jazzer.js: #8324
> Add 'none' as a supported sanitizer for libFuzzer.

- projects/zeek/project.yaml
I was only able to test these paths by passing them as arguments to `infra/helper.py` but not built-in to the image itself locally. I'm not sure if that's intentional, but passing them as arguments did what I wanted it to do.
> zeek: Ignore some paths in the coverage output

- projects/gitoxide/project.yaml
> gitoxide: Filter out rustc from coverage reports

- projects/wasmer/project.yaml
This is temp fix for https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=55302. Coverage build is failing with following error:
```
: /workspace/out/libfuzzer-coverage-x86_64/rustc/bd39bbb4bb92df439bf6d85470e296cc6a47ffbd/library/std/src/thread/local.rs: No such file or directory
```
This pr ignores `/rustc/` from coverage report for now.
> wasmer: fix coverage build

- projects/pillow/Dockerfile
Over at python-pillow, our CIFuzz job has [started failing](https://github.com/python-pillow/Pillow/actions/runs/4147683686/jobs/7174854267#step:4:7800) -
> depends/install_extra_test_images.sh: line 6: ./download-and-extract.sh: No such file or directory
This is because we recently merged https://github.com/python-pillow/Pillow/pull/6918, which changes `depends/install_extra_test_images.sh` to call `./download-and-extract.sh`, which exists inside [`depends`](https://github.com/python-pillow/Pillow/tree/main/depends). So when
https://github.com/google/oss-fuzz/blob/00b08f6592b90d438e113138c64cd4025fbb3bdf/projects/pillow/Dockerfile#L41
runs, it can't find `./download-and-extract.sh`, because it is running from the base Pillow directory.
So this PR changes the command to run from inside …
> Fixed installing extra test images

- projects/libevent/Dockerfile
Given that the cmake build system is used, we shouldn't have to install the dependencies to use autotools.
> libevent: remove autotools dependencies

- projects/bitcoin-core/Dockerfile
Remove duplicate deps (automake, bsdmainutils, pkg-config).
Remove bison (built with NO_QT=1).
Remove binutils-gold (unneeded).
> bitcoin-core: remove duplicate dependencies

- projects/expat/Dockerfile
Expat is built using cmake, so autotools and friends should not be required.
> expat: remove autotools build dependencies

- projects/elfutils/build.sh
The elfutils build system no longer passes `--no-undefined` explicitly so it should be dropped by overwriting the NO_UNDEFINED variable instead.
It's a follow-up to https://sourceware.org/git/?p=elfutils.git;a=commitdiff;h=3fa98a6f29b0f370e32549ead7eb897c839af980
Closes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=55999
> [elfutils] drop --no-undefined using NO_UNDEFINED

- projects/tensorflow/build.sh
The changes introduced in https://github.com/google/oss-fuzz/pull/9357 for limiting instrumentation in third party libraries are no longer needed, I think. This is because we now specify the explicit fuzz target to compile in the CI, which is much smaller in size than the targets that were built as part of the CI when instrumentation-limitation changes were made. It would be nice to remove these as they add a lot of unnecessary complexity in the build script.
> tensorflow: reduce build script size

- projects/envoy/project.yaml
PR #9653 added a "none" sanitizer that broke Envoy's build.
This PR explicitly lists the allowed sanitizers (address, memory, and undefined).
> envoy: prevent building with none sanitizer

- projects/zip-rs/build.sh
- projects/zip-rs/fuzz/Cargo.toml
- projects/zip-rs/fuzz/fuzz_targets/fuzz_zip.rs
- projects/zip-rs/fuzz/fuzz_targets/roundtrip.rs
- projects/zip-rs/fuzz/fuzz_targets/structured_fuzz_reader.rs
Adds two new fuzz harnesses;
- Structured roundtrip.
- Structured reader.
The read/write functionality implementation level is
not symmetrical and some functions plugins e.g.
zipcrypt is only supported for decompressing. Hence
why we need both a "roundtrip" and a reader harness.
Adds a seed-corpus for;
- The existing from_zip harness.
- The new structured reader harness.
> zip-rs: Improves code coverage

- projects/envoy/project.yaml
In PR #9719 I accidentally added the memory sanitizer, which brakes the oss-fuzz build:
```
Step #23 - "compile-libfuzzer-memory-x86_64": ld.lld: error: undefined symbol: __msan_param_tls
Step #23 - "compile-libfuzzer-memory-x86_64": >>> referenced by gtest-internal.h:522 (external/com_google_googletest/googletest/include/gtest/internal/gtest-internal.h:522)
Step #23 - "compile-libfuzzer-memory-x86_64": >>>               bazel-out/k8-fastbuild-ST-d2373e19ffe2/bin/test/common/router/_objs/config_impl_test_lib/config_impl_test.pic.o:(testing::internal::SuiteApiResolver<Envoy::Router::(anonymous namespace)::RouteMatcherTest>::GetSetUpCaseOrSuite(char const*, int))
Step #23 - "compile-libfuzzer-memory-x86_64": >>> referenced by gtest-internal.h:543 …
```
> Envoy: remove memory sanitizer

- projects/firefox/ContentParentIPC.options
- projects/firefox/build.sh
These targets are being removed from the codebase.
> [firefox] Remove targets to prevent further breakage

- projects/elfutils/build.sh
It should be turned off explicitly now.
It's a follow-up to
https://sourceware.org/git/?p=elfutils.git;a=commitdiff;h=77d237798c8f262d618bd3ed2db8864022bfcacb https://sourceware.org/git/?p=elfutils.git;a=commitdiff;h=73e212b0a778c6dbe84f79b7eb2647dea50ea16f
Closes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=56085
> [elfutils] disable demangler

- projects/sudoers/build.sh
A space was being removed from CFLAGS when SANITIZER_FLAGS was empty, resulting in a build error.
> sudoers: fix build with --sanitizer none

- projects/libical/Dockerfile
- projects/libical/build.sh
- projects/libical/libical_extended_fuzzer.cc
Hi @tsdgeos @winterz 
Would you be okay adding the fuzzer of this PR?
I'm developing on Fuzz Introspector (https://github.com/ossf/fuzz-introspector) and was looking at the libical report, where I spotted `icalcomponent_normalize` has a lot of uncovered code. You can find this from the publicly available Fuzz Introspector report in the function table sorting by column `Accummulate cyclomatic complexity`: https://storage.googleapis.com/oss-fuzz-introspector/libical/inspector-report/20230217/fuzz_report.html#Project-functions-overview As such, I thought it would be a nice target to fuzz since it will likely give the fuzzer a lot of code to explore.
> libical: add extended fuzzer

- infra/base-images/base-builder/compile_fuzztests.sh
- projects/tensorflow/build.sh
This is needed to avoid having to potentially run `bazel build` multiple times, which is the current situation in Tensorflow. This will make the process simpler and also reduce build speed, which is needed if we want to build all of the FuzzTest fuzzers + non-FuzzTest fuzzers in Tensorflow.
> infra: enable fuzztest compile script to build non-fuzztest fuzzers

- projects/ngolo-fuzzing-x/build.sh
Means to fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=53810&q=label%3AProj-ngolo-fuzzing
Also renames the fuzz targets from `fuzz_x_tiff` to `fuzz_x_image_tiff`
> ngolo-fuzzing: fix coverage build for x packages

- projects/urllib3/fuzz_urlparse.py
This is an improvement to the urllib3 utils functions fuzzing. This is my first attempt at contributing to oss-fuzz so feedback appreciated on whether this custom mutator approach is ok.
- `parse_url` function
We now have a custom mutator that drives more url like structures. I originally developed this using Hypothesis, but the quality of fuzzing wasn't good (seems to be a known issue https://github.com/google/atheris/issues/20). Because of this I've used a 3rd party library `exrex` that can generate test data from regular expressions.
> Improving urllib3 utils coverage

- infra/helper.py
pipes got deprecated in
https://github.com/python/cpython/commit/2551a6c92f247eed8121b14f151acd95432dff9e and Python3.11 complains about it:
```
infra/helper.py:27: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
import pipes
```
The pipes module just uses shlex.quote so it can be used direcly instead.
> [helper] replace pipes.quote with shlex.quote

- projects/flac/build.sh
- projects/flac/fuzzer_exo.cpp
A number of fuzzer names to be copied is removed from the build script. The naming of various files in FLACs oss-fuzz directory has been changed so all files that belong in $OUT have the same prefix.
Also, some defaults have changed because of this ticket: https://github.com/xiph/flac/issues/546 Other projects relying on libFLAC being fuzzed can now rely on default settings.
> [flac] Simplify build script

- projects/go-toml/build.sh
This is a temporary fix, Will remove this once upstream supports go native fuzzing.
> go-toml: fix coverage

- projects/cras/Dockerfile
Similar to https://github.com/google/oss-fuzz/pull/9317, we'd be using bindgen so we need libclang.so on the image.
> cras: Add libclang for bindgen

- projects/hdf5/Dockerfile
- projects/hdf5/build.sh
- projects/hdf5/h5_extended_fuzzer.options
The fuzzer runs into them quickly and it would be nice to have it explore more code for now.
> hdf5: disable leak detection for extended fuzzer

- infra/base-images/base-builder/compile
rustc errors with
error: incorrect value `none` for unstable option `sanitizer`
Should fix at least ecc-diff-fuzzer build failure cf https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=55912
> rust: do not use none sanitizer

- infra/base-images/base-builder/compile_javascript_fuzzer
This fixes the issue of running Jazzer.js fuzzer using an absolute path such as `/out/fuzzer`. 
@oliverchang We needed a minor fix in Jazzer.js (https://github.com/CodeIntelligenceTesting/jazzer.js/pull/341), so you would need to rebuild the project so that the latest version (1.4.0) is fetched from npm.
> infra: use an absolute path to the JavaScript fuzz test file

- projects/tensorflow/build.sh
Includes some new fuzzers that are placed outside `security/fuzzing`, e.g. `saved_model_fuzzer`
> tensorflow: enable more targets

- projects/binutils/fuzz_as.c
Fix an error passing argv to gas_early_init.  &fakeArgv isn't correct.  The address of a pointer of type char** must be passed. That char*** will be passed on to expandargv, which possibly modifies the char** (although it won't be with current args), which is why the call to perform_an_assembly_pass is changed too.
> binutils/fuzz_as.c gas_early_init

- projects/cctz/build.sh
This is required for the CI to work on
https://github.com/google/cctz/pull/241
> cctz: disable benchmark build

- projects/urllib3/fuzz_requests.py
- projects/urllib3/fuzz_urlparse.py
This change added a new fuzzer `fuzz_requests`. This fuzzes the `.request` method in urllib3, which opens a lot more coverage.
I have created a python `HTTPServer` that provides fuzzed responses to all the different request types. And I try and drive different combinations of requests including mixes of headers, bodies and request types. This gives a nice improvement on current coverage levels [urllib3 fuzz inspector report 2023-02-23](https://storage.googleapis.com/oss-fuzz-introspector/urllib3/inspector-report/20230223/fuzz_report.html).
> Adding urllib3 requests coverage

- projects/llvm/build.sh
llvm build has been broken, the reason is that
1.  [`LLVM_ENABLE_PROJECTS` for libc++, libc++abi was deprecate](https://reviews.llvm.org/D112724)
2. compiler-rt is also a runtime according to the [llvm-docs](https://llvm.org/docs/CMake.html#llvm-related-variables)
> llvm: fix build deprecate LLVM_ENABLE_PROJECTS

- projects/glib/project.yaml
Todd Cullum is on the Red Hat security team and has been vouched for by Michael Catanzaro. He is not a GLib upstream maintainer.
> Add additional CC to GLib project configuration

- projects/toml/fuzz_loads.py
To make the fuzz introspector nicer: https://github.com/google/oss-fuzz/pull/9834#issuecomment-1450019886
> toml: call loads with explicit path

- projects/wabt/build.sh
wabt moved from C++11 to C++17 about a year ago (https://github.com/WebAssembly/wabt/pull/1825), but the oss-fuzz repo includes external fuzzers that were built with C++11. A recent commit (https://github.com/WebAssembly/wabt/pull/2152) broke the build.
> wabt: fix build of external fuzzers with `-std=c++17`

- projects/rtpproxy/Dockerfile
- projects/rtpproxy/build.sh
- projects/rtpproxy/project.yaml
This patch adds OSS-Fuzz integration for the RTPProxy project. The RTPProxy is a companion software used by many of the SIP application servers (OpenSIPS, Kamailio, Sipppy B2BUA etc) to handle RTP streams. We have completed integration on our side already, e.g. https://github.com/sippy/rtpproxy/actions/runs/4226614295/jobs/7340239205.
> rtpproxy: initial integration.

- projects/lzo/lzo_compress_target.c
The target allocates 2*size buffers on the stack.
Stack is not always infinite. If we allocate on the stack,
we need to cap input size.
> lzo: fix crash on large inputs

- .github/header-checker-lint.yml
This pr
- Removes duplicate extension from sourceFileExtensions
- Adds `swift` extension as its a oss-fuzz supported language and there exists a project with .swift extension files.  https://github.com/google/oss-fuzz/tree/master/projects/swift-nio
> Update header lint source extension

- projects/binutils/fuzz_as.c
> Issue 56429 binutils/fuzz_as

- .github/workflows/project_tests.yml
- projects/bitcoin-core/build.sh
My understanding is that basically only `git docker.io python` are needed for oss-fuzz, so 5 GB of the largest packages and 20+ GB of folders can be dropped from the CI image to make room for other stuff.
> ci: Double free space from 30 GB to 60 GB

- projects/mvel/.gitignore
- projects/mvel/Dockerfile
- projects/mvel/build.sh
- projects/mvel/project-parent/fuzz-targets/pom.xml
- projects/mvel/project-parent/fuzz-targets/src/test/java/com/example/MvelFuzzer.java
- projects/mvel/project-parent/pom.xml
- projects/mvel/project.yaml
> MVEL: Initial integration.

- projects/qpid-proton/build.sh
* https://github.com/google/oss-fuzz/issues/9857
> qpid-proton: workaround #9857 and link ar and ranlib for afl

- projects/compress/Dockerfile
- projects/compress/build.sh
- projects/compress/project.yaml
- projects/compress/setup_dicts.go
@klauspost - I have the build working with all fuzzers except the `s2` fuzzers which require more work. I would prefer to get the fuzzers running first without those first and include them later.
Your fuzzing suite does some reading of files on disk at runtime which won't work in OSS-Fuzz. I have mitigated that by creating a slice of all the files in a new file that gets created in `./zstd` which is available to the fuzzer at runtime. See `build.sh` for details.
Can you please leave your email address in this PR to get it finalized?
> compress: initial integration

- projects/mdurl/fuzz_mdurl.py
This change removes `sys.maxsize` and uses a defined string size so that the data is not consumed all at once when first used. This results in increased code coverage.
> mdurl: fix early string consumer exhaustion

- projects/packaging/fuzz_packaging.py
Catch an exception thrown by the code and remove invalid operators.
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=56761
> packaging: fix fuzzer

- projects/qpid-proton/build.sh
@astitcher The issue is https://github.com/google/honggfuzz/issues/336#issuecomment-1458427538, for some reason the weak symbol from honggfuzz (placeholder function that prints help message and kills the fuzzer) gets used instead of our LLVMFuzzerTestOneInput.
I think that disabling LTO is a good temporary fix, to at least get all the fuzz builds working.
> qpid-proton: disable LTO to fix honggfuzz linking

- projects/opensk/build.sh
OpenSK moved its CTAP code into a library, and all fuzzing has moved with it. As an advantage, we are now independent of other dependencies that restricted the compiler versions we could use. Therefore, we are now fuzzing on the latest nightly, hopefully fixing some issues that came with the compiler restriction before.
The corresponding PR on our GitHub is https://github.com/google/OpenSK/pull/602
> OpenSK fuzzing path

- projects/toml/Dockerfile
- projects/toml/atheris_dict.py
- projects/toml/fuzz_dump.py
- projects/toml/fuzz_dumps.py
- projects/toml/fuzz_load.py
This change fuzzes random dictionaries at the different toml encoders to get coverage of `toml/encoder.py`. The dictionary fuzzing technique (`atheris_dict.py`) is derivative of another library [python-dict](github.com/abc), which is attributed in the source code.
Doing some local runs this takes `toml/encoder.py` from `16%` to `64%` statement coverage when using libfuzz.
Interestingly I'm finding for certain parameters like the `ENCODER` selection Python random `choice()` statements are a lot more effective at getting coverage that the `fdp.PickValueInList()` getting an extra 9% coverage. For now I've kept everything as the atheris fuzzer but can switch this over if you think it's worth doing.
The introspector call graphs and coverage don't look right, which is likely related to the …
> Add coverage for toml encoder

- projects/mrab-regex/fuzz_regex.py
Avoid exhausting the fuzz data on the first call to `ConsumeUnicodeNoSurrogates`.
> mrab-regex: avoid sys.maxsize

- projects/libjpeg-turbo/Dockerfile
Our "cjpeg" fuzz target, which tests rarely-used compression code paths, inputs only TARGA images (because that's a rarely-used compression code path as well), so the lack of those images in the seed corpus was preventing the rarely-used compression code paths from being fuzz-tested at all.  This should improve the overall coverage.
> [libjpeg-turbo] Add TGA images to compression seed corpus

- projects/duckdb/build.sh
This should enable assertion checking, and sets it up so DuckDB calls `abort()` on any assertion trigger, which should lead to more effective fuzzing.
> duckdb: Compile in relassert mode and enable CRASH_ON_ASSERT for fuzzing

- projects/libxml2/build.sh
- projects/libxslt/build.sh
- Enable integer sanitizer
- Update autoconf options
- Enable XInclude fuzzer
- Simplify libxslt build script
- Fix libxslt build after recent changes
> libxml2: Update build script

- projects/bottleneck/fuzz_bn.py
`ValueError` are raised various places, e.g. https://github.com/pydata/bottleneck/blob/ffb2fe8cf201ec24b6a263cf65e040bf02ae1010/bottleneck/src/move_template.c#L974
Fixes e.g. https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=50587
> bottleneck: catch some known exceptions

- projects/configparser/fuzz_dict.py
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=56168
> configparser: catch another exception

- projects/croniter/fuzz_match.py
- projects/croniter/fuzz_range.py
`fuzz_iter.py`
- Added coverage of optional `hash_id` parameter
- Added call to `is_valid` method
- Added call to `get_next` & `get_prev` methods for the returned croniter iterator
`fuzz_match.py`
- Added fuzzing of `croniter.match`
`fuzz_range.py`
- Added fuzzing of `croniter.range`
> Improving coverage for croniter

- projects/ngolo-fuzzing/build.sh
This should fix build of ngolo-fuzzing even when the corpus for one target is empty.
net/http does not give a corpus because of `use of internal package net/http/internal not allowed` in the tests...
> ngolo: fix build even when there is no corpus

- projects/xs/project.yaml
As titled, adds another member of the Moddable team to allow reviewing OSS-Fuzz stats.
> [xs] Add ps from Moddable

- projects/jackson-core/Dockerfile
- projects/jackson-databind/Dockerfile
- projects/jackson-dataformat-xml/Dockerfile
- projects/jackson-dataformats-binary/Dockerfile
As per title, development has moved to 2.15 from 2.14 for next version.
> Update Jackson branches to latest 2.x, 2.15 (from 2.14)

- projects/wasmtime/default.options
Recently Wasmtime switched code generator tactics for the implementation of integer division. This means that Wasmtime expects to receive SIGFPE for divide-by-zero traps and similar. This is similar to other signals that Wasmtime is expected to handle in JIT code.
This commit adds an option for Wasmtime to let it handle signals in the same manner that it's allowed to handle SIGILL and SIGSEGV currently.
> wasmtime: Allow Wasmtime to handle SIGFPE

- projects/croniter/fuzz_iter.py
- projects/croniter/fuzz_match.py
- projects/croniter/fuzz_range.py
The current exceptions caught are not the top-level croniter ones. This changes it to be that.
Fixes, e.g.: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=57122
> croniter: catch top-level exceptions

- infra/helper.py
`infra/helper.py shell project` used to open docker container with different volumes mounted than `infra/helper.py build_fuzzers project` Use the same logics in shell for project workdir calculation as it's used during build procedure. This way we may easier troubleshoot build issues in shell.
> helper.py: make shell compatible with build_*

- projects/urllib3/fuzz_requests.py
I've managed to recreate the issue that was stopping the `fuzz_requests` coverage on `urllib3` ( see #9863 )
The issues not visible running introspector locally but can be see in clusterfuzzlite which is a port binding error. This change randomises the port that's used and ensures that it can bind to it before fuzzing starts. Change is tested and demonstrated as working here [sg3-141-592/urllib3 - ClusterFuzzLite PR fuzzing](https://github.com/sg3-141-592/urllib3/actions/runs/4466205991/jobs/7844093473?pr=1).
Also I've changed the style of the main block and atheris to be consistent with the other fuzzers added lately.
> Fixing urllib3 port binding crash

- projects/xz/build.sh
- projects/xz/project.yaml
Let me know if you would rather have the commits squashed into one, or separated into multiple PRs. This should address:
- Changing the primary contact email address. This will give the XZ Utils maintainers access to the filed bugs in the issue tracker since the previous primary contact email address was not associated with a Google account.
- Updated the main repository URL. The project recently moved to GitHub as the main repository. The old repository will still be a mirror, but it will be updated with a slight delay.
- Fixed [build issue](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=57241) by adding an extra argument to the autogen.sh script.
> XZ updates

- projects/binutils/fuzz_addr2line.c
- projects/binutils/fuzz_objcopy.c
fuzz_objcopy.c calls copy_main that calls getopt.  Without reinitialisation of optind, this means that of the 100 iterations per sample only the first would see the fake command line options.  And if another sample was then tested in the same running process, no iteration would see the command line options.  Fix this by setting optind.  Do so every second iteration because it's usefull to test with default options too.
fuzz_addr2line set up five command line addresses but then only used two.  Fix that too, and use xmalloc/xstrdup so that malloc fails are fatal.
> binutils fuzzer trouble with getopt

- projects/spring-data-keyvalue/build.sh
the spring-data-keyvalue project version is set now via maven-help plugin to prevent similar build issue in the future
> [spring-data-keyvalue] fix build issue

- projects/cachetools/Dockerfile
- projects/cachetools/build.sh
- projects/cachetools/fuzz_cached.py
- projects/cachetools/project.yaml
This is a proposed initial integration of the [cachetools](https://github.com/tkem/cachetools) library into oss-fuzz.
I think this is might be a suitable project for OSS-Fuzz because it is the 22nd most downloaded Python package from pypi https://hugovk.github.io/top-pypi-packages/ and generates a [criticality score](https://github.com/ossf/criticality_score) of 0.54756.
```
repo.url: https://github.com/tkem/cachetools
repo.language: Python
repo.license: MIT License
repo.star_count: 1601
repo.created_at: 2014-03-22T10:09:33Z
repo.updated_at: 2023-03-17T22:10:49Z
legacy.created_since: 109
legacy.updated_since: 0
legacy.contributor_count: 9
legacy.org_count: 5
legacy.commit_frequency: 0.52
legacy.recent_release_count: 4
legacy.updated_issues_count: 187
legacy.closed_issues_count: 183 …
```
> Integration of cachetools into oss-fuzz

- projects/asn1crypto/project.yaml
- projects/cffi/project.yaml
- projects/dask/project.yaml
- projects/decorator/project.yaml
- projects/html5lib-python/project.yaml
- projects/mako/project.yaml
- projects/networkx/project.yaml
- projects/parso/project.yaml
- projects/pasta/project.yaml
- projects/pem/project.yaml
- projects/pytables/project.yaml
- projects/python-rison/project.yaml
- projects/rich/project.yaml
- projects/tinycss2/project.yaml
- projects/tomlkit/project.yaml
- projects/toolz/project.yaml
- projects/uritemplate/project.yaml
The projects do not build any native code. No need for two sanitizers.
> python-projects: cleanup UBSAN from project.yaml

- projects/black/project.yaml
- projects/bz2file/project.yaml
- projects/charset_normalizer/project.yaml
- projects/configparser/project.yaml
- projects/croniter/project.yaml
- projects/dill/project.yaml
- projects/glom/project.yaml
- projects/idna/project.yaml
- projects/isodate/project.yaml
- projects/jsmin/project.yaml
- projects/markupsafe/project.yaml
- projects/more-itertools/project.yaml
- projects/olefile/project.yaml
- projects/ply/project.yaml
- projects/pyjwt/project.yaml
- projects/python-future/project.yaml
- projects/rfc3967/project.yaml
- projects/six/project.yaml
- projects/toml/project.yaml
- projects/tomli/project.yaml
- projects/tqdm/project.yaml
- projects/underscore/project.yaml
These projects do not have native code compiled. No need to have multiple sanitizers.
> python projects: remove UBSAN

- projects/skia/build.sh
SkMalloc.h no longer includes SkTypes.h which aliased SK_BUILD_FOR_LIBFUZZER into SK_BUILD_FOR_FUZZER.
This fixes this.
> [skia] Define SK_BUILD_FOR_FUZZER also

- infra/base-images/base-builder/sanitizers/pysecsan/pysecsan/command_injection.py
- infra/base-images/base-builder/sanitizers/pysecsan/pysecsan/sanlib.py
Based on #10014:
`pylint` prints false positive error messages complaining about `unsubscriptable-object`.
This PR suppresses these messages.
> Suppress pylint false positive

- projects/bind9/Dockerfile
- projects/bind9/build.sh
This fixes FTBFS due to missing internal (convenience) libtest library.
> [bind9] Build internal libtest and link with it as needed

- projects/suricata/Dockerfile
- projects/suricata/build.sh
Meant to fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=57490&q=label%3AProj-suricata
Cf https://github.com/rust-lang/rust/issues/107149
When will oss-fuzz use clang 16 for C ?
> Suricata rust clang16

- projects/wasmer/Dockerfile
- projects/wasmer/build.sh
- Updates wasmer to use llvm 14+ 
- Pinned rust version as it was crashing the build, fix  copied from (https://github.com/google/oss-fuzz/pull/10019)  
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=56795
> wasmer: fix build

- projects/urllib3/fuzz_requests.py
We've still got an issue with crashes on the urllib3 requests test that uses the mock HTTP server.
Fix #9958 to handle port mapping errors didn't resolve it.
I got a feeling there's an ordering issue. Looking at the error logs [https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=56500#c2](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=56500#c2) there appears to be an issue where we're throwing exceptions before the coverage completes.
```
=== Uncaught Python exception: ===
--
  | MaxRetryError: HTTPConnectionPool(host='localhost', port=8011): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4cdf33d1f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
  | Traceback (most recent call last): …
```
> Attempted fix for urllib3 crashes

- projects/ffmpeg/Dockerfile
- projects/ffmpeg/build.sh
libXext build fails, it seems needing autoconf 2.70 which seems unavailable in ubuntu 20.04 which seems what ossfuzz docker uses.
It appears things still work fine after this removial
> [FFmpeg] Drop libXext

- projects/tarantool/project.yaml
The teammates are working on the relevant tarantool components and should be informed about new problems found by fuzzers.
> tarantool: add more tarantool developers to CC

- projects/urllib3/fuzz_requests.py
We're having the issue where the introspector isn't able to see renamed imports (e.g. `from .poolmanager import PoolManager, ProxyManager, proxy_from_url`).
I've called `urllib3.poolmanager.PoolManager` instead of `urllib3.PoolManager` which has included the `PoolManager` coverage in the analysis.
> Updating calling of urllib3 pool manager

- projects/suricata/Dockerfile
- projects/suricata/build.sh
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=57763
The `compile` script was not using the right rustc toolchain for source copy for coverage report 
cf rustch=`rustc --version --verbose | grep commit-hash | cut -d' ' -f2` in compile
> suricata: fix coverage build by using right rustc

- projects/neomutt/Dockerfile
- projects/neomutt/project.yaml
Add `pkgconf` package to the Docker build so that NeoMutt builds.
Six months ago, we updated our build to use `pkg-config` and the fuzzer has been working correctly.
Some time in the last couple of days, the fuzzer stopped working because the build couldn't find `pkg-config`.
The problem only seems to exist for the GitHub actions.
Locally, I can run the fuzzer without problems.
---
**Update**:
I've dropped honggfuzz from the config as it doesn't work.
> neomutt: add pkgconf to build

- projects/croniter/project.yaml
I've had approval today from the croniter maintainer to be added to the croniter 
`project.yaml`, see [https://github.com/kiorky/croniter/issues/32](https://github.com/kiorky/croniter/issues/32).
I need this to see what the current issue is that's stopping `fuzz_iter.py` running on the croniter project.
> Updating croniter project.yaml

- projects/neomutt/Dockerfile
NeoMutt now uses IDN2 by default.
Sorry, another NeoMutt update.
Thanks.
> neomutt: install libidn2

- projects/croniter/fuzz_iter.py
Fix for an incorrect call to `get_next` that was stopping the Croniter `fuzz_iter` executing, see [https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=57139#c2](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=57139#c2).
It was being called with a `datetime` object instead of a `datetime` class as it's `ret_type` argument causing a type error.  I've removed the argument that's fixed it.
Also I've added the `undefined` sanitizer as it was missing from the `project.yaml`. I've done a local run and it works fine with it enabled.
> Croniter get_next fix

- projects/gss-ntlmssp/Dockerfile
- projects/gss-ntlmssp/build.sh
- projects/gss-ntlmssp/fuzzing/Makefile
- projects/gss-ntlmssp/fuzzing/fuzz-accept-sec-context.c
- projects/gss-ntlmssp/fuzzing/fuzz-accept-sec-context.dict
- projects/gss-ntlmssp/project.yaml
This PR adds a new gss-ntlmssp project. [gss-ntlmssp](https://github.com/gssapi/gss-ntlmssp) is a mechglue plugin for [krb5](https://github.com/krb5/krb5) that implements NTLM authentication via GSSAPI.
The plugin is available in the Debian, Ubuntu and Suse package repositories.
cc @simo5 as the gss-ntlmssp maintainer.
> gss-ntlmssp: New project

- projects/woff2/build.sh
It currently runs into:
```
Step #6 - "compile-libfuzzer-introspector-x86_64": clang-15: ␛[0;1;35mwarning: ␛[0m␛[1moptimization flag '-fno-tree-vrp' is not supported [-Wignored-optimization-argument]␛[0m
Step #6 - "compile-libfuzzer-introspector-x86_64": llvm-ar crf src/convert_woff2ttf_fuzzer.a  src/font.o  src/glyph.o  src/normalize.o  src/table_tags.o  src/transform.o  src/woff2_dec.o  src/woff2_enc.o  src/woff2_common.o  src/woff2_out.o  src/variable_length.o \
Step #6 - "compile-libfuzzer-introspector-x86_64":       brotli/bin/obj/c/common/*.o brotli/bin/obj/c/enc/*.o brotli/bin/obj/c/dec/*.o src/convert_woff2ttf_fuzzer.o
Step #6 - "compile-libfuzzer-introspector-x86_64": llvm-ar: ␛[0;1;31merror: ␛[0munknown option f
Step #6 - "compile-libfuzzer-introspector-x86_64": OVERVIEW: LLVM …
```
> woff2: fix introspector build

- projects/vitess/Dockerfile
- projects/vitess/build.sh
> vitess: bump go

- infra/base-images/base-builder/Dockerfile
This reverts commit e3fdcc25ec5ad39538301d7f9b8ef8622649fd29 to temporarily avoid [the issues](https://github.com/google/oss-fuzz/pull/10021#issuecomment-1505301564) mentioned in #10021 during further investigation.
Backward-compatibility of `Centipede` is validated by https://github.com/google/clusterfuzz/pull/2999.
> Revert "Update Centipede to 7a20b4e (#10021)"

- projects/xs/xst.options
This PR instructs ASAN to not check for leaks at exit (i.e., after fuzzing is done), and use only the detection in libfuzzer using lsan's non-destructive checks.
Currently, the fuzzer reports leaks that only occur because it's in-process, so they are not true positives. When XS expects to exit (no `free` immediately before exit), it doesn't actually exit and continues to the next case. A comprehensive fix would be expensive. 
To reduce the amount of false-positives we suppress LSAN in abort paths, since any allocation would be short lived. However, the at-exit leak detection still reports non-reproducible leaks when fuzzer is exiting. We are disabling while we explore other alternatives to fix comprehensively (a possible one is #7347).
> [xs] disable leak check at exit

- projects/urllib3/fuzz_requests.py
While investigating the urllib3 performance with the `fuzz_requests` I saw that a lot of tests had been failing with timeouts. I had some misunderstandings about how oss-fuzz works and that you need light and quick implementations for the fuzzer to work effectively.
Doing some local testing a single iteration of the fuzzer was taking as long as 90 seconds.
This change updates the `urllib3` timeouts to be far shorter and reduces the number of requests the fuzzer tries to do in a single iteration. This should bring us under the 25 second timeout and hopefully get this fuzzer closer to working.
> urllib3 performance improvements

- projects/tarantool/Dockerfile
Option breaks checkouts for certain commits in branches.
> tarantool: remove --depth in git clone

- infra/helper.py
Don't use extend since it breaks python versions below 3.8
> Fix python3.7 support.

- docs/advanced-topics/ideal_integration.md
- docs/advanced-topics/reproducing.md
- docs/faq.md
- docs/getting-started/new_project_guide.md
- docs/oss-fuzz/architecture.md
- docs/reference/useful_links.md
- infra/base-images/base-clang/Dockerfile
- infra/cifuzz/test_data/external-project/do_stuff_fuzzer.cpp
- infra/cifuzz/test_data/external-project/do_stuff_fuzzer.dict
- projects/example/my-api-repo/README.md
- projects/example/my-api-repo/do_stuff_fuzzer.cpp
- projects/example/my-api-repo/do_stuff_fuzzer.dict
These all already redirect to the new locations.
> doc: replace libfuzzer.info links with llvm.org

- projects/mutagen/fuzz_parser.py
Mutagen isn't able to write to the BytesIO it's operating on, so we need to pass it something to write into.
> Fix the Mutagen fuzzer

- projects/libplist/build.sh
As the test suite currently fails building for coverage due to this error:
```
Step #3 - "compile-libfuzzer-coverage-x86_64":   CXXLD    plist_test++
Step #3 - "compile-libfuzzer-coverage-x86_64": /usr/bin/ld: .libs/plist_test++: hidden symbol `atexit' in /usr/lib/x86_64-linux-gnu/libc_nonshared.a(atexit.oS) is referenced by DSO
Step #3 - "compile-libfuzzer-coverage-x86_64": /usr/bin/ld: final link failed: bad value
```
I thought I'd add an option to allow disabling building those - and use this option here - since the test case binaries are not really required for fuzzing.
> libplist: Do not build test suite

- projects/python-email-validator/fuzz_validator.py
Disables dns deliverability check hence avoids dns package from code coverage, as underlying dns-python is already being fuzzed in oss-fuzz.
> python-email-validator: disable dns check

- projects/bignum-fuzzer/Dockerfile
- projects/cryptofuzz/Dockerfile
- projects/cryptofuzz/build.sh
The libgmp Mercurial server is frequently down, and this causes builds to fail. Unfortunately they do not have a Github mirror.
This PR causes the Dockerfile to revert to downloading the latest libgmp stable release if the Mercurial clone doesn't work.
> [cryptofuzz, bignum-fuzzer] Fix libgmp download

- infra/cifuzz/cifuzz-base/Dockerfile
- infra/cifuzz/requirements.txt
Install is much smaller than web instructions and
doesn't include anthos bloat.
This cuts pull time in half (about 30 seconds).
> [cifuzz] Install gsutil using pip.

- projects/tarantool/build.sh
Follows up https://github.com/tarantool/tarantool/issues/8488
Follows up https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=57298
CC: @ylobankov
> tarantool: fix non-zero exit code when corpus dir doesn't exist

- projects/cras/Dockerfile
- projects/cras/build.sh
We have a unified Cargo workspace now, so we don't have to build inside the rust specific directory
> cras: Build Rust code from ${SRC}/adhd

- projects/rustls/Dockerfile
- projects/rustls/build.sh
Adds a seed corpus for the `client` fuzzer which results in ~ 11% code coverage increase.
rustls maintainer has agreed to this: https://github.com/rustls/rustls/issues/1287#issuecomment-1524724234
> [rustls] Add seed corpus

- projects/tarantool/build.sh
- LUA_USE_ASSERT turns on all assertions inside Lua.
- LUA_USE_APICHECK turns on several consistency checks on the C API.
> tarantool: enable debug compile options

- .github/workflows/project_tests.yml
It adds an unsupported and unused libfuzzer-none build. We already have a centipede-none build explicitly there.
> Remove none build from CI.

- projects/openh264/build.sh
The shared libraries are not needed. Creating only the static libraries speeds up the build and fixes introspector for openh264.
> openh264: only build static libraries

- projects/xvid/build.sh
- Only build static library needed for the fuzzer
- This enables fuzz introspector
> xvid: refine build

- projects/croniter/build.sh
- projects/croniter/fuzz_iter.py
- projects/croniter/fuzz_match.py
- projects/croniter/fuzz_range.py
Work around for issue resolving croniter function names, see https://github.com/ossf/fuzz-introspector/issues/1010 .
Setting the `PYFUZZPACKAGE` environment variable takes coverage from `2/48` functions reachable to an improved `22/48` reachable. I've also updated how croniter is imported to have a higher number of matches.
There are still some issues in the callgraph analysis but this is a big improvement in the metrics.
> croniter PYFUZZPACKAGE reachability analysis workaround

- projects/bind9/build.sh
`./configure` picked the membarrier flavor but was asked to link with qsbc:
/usr/bin/ld: /usr/bin/ld: DWARF error: invalid or unhandled FORM value: 0x25
lib/isc/.libs/libisc.a(libisc_la-loop.o): in function `quiescent_cb':
loop.c:(.text+0x833a): undefined reference to `urcu_memb_read_ongoing'
/usr/bin/ld: /usr/bin/ld: DWARF error: invalid or unhandled FORM value: 0x25
lib/isc/.libs/libisc.a(libisc_la-thread.o): in function `isc_thread_main':
thread.c:(.text+0x156): undefined reference to `urcu_memb_register_thread'
/usr/bin/ld: thread.c:(.text+0x161): undefined reference to `urcu_memb_unregister_thread'
/usr/bin/ld: lib/isc/.libs/libisc.a(libisc_la-thread.o): in function `thread_run':
thread.c:(.text+0x88e): undefined reference to `urcu_memb_register_thread'
/usr/bin/ld: …
> bind9: Fix liburcu linking

- projects/libheif/build.sh
libheif has deprecated the old autotools-based build system and switched to cmake. The autotools build files will be removed soon.
This PR switch to the cmake build.
> libheif: use new cmake build system instead of deprecated autotools

- projects/neomutt/project.yaml
Fixes #10143.
`Centipede` runs into a timeout error when running the build tests on the unsanitized binary of the project.
This is likely caused by `Centipede` as [a similar issue](https://github.com/google/oss-fuzz/pull/10021#issuecomment-1519206462) was observed on a different project.
But given most projects work fine on `Centipede`, the most straightforward solution is to disable `Centipede` on the project for now.
> Disable Centipede on Project `neomutt`

- projects/ada-url/Dockerfile
- projects/ada-url/project.yaml
Ada URL parser is the default URL parser for Node.js 18 (LTS version), 19, and 20. Node.js is used by millions of applications worldwide. 
The download statistics for Node.js [can be found from here](https://nodejs.org/metrics/).
> ada-url: initial integration

- projects/systemd/project.yaml
centipede doesn't support more than one instrumented DSO currently and it leads to crashes like
https://github.com/google/oss-fuzz/pull/10021#issuecomment-1505301564.
It partially reverts 439d0bc2c625eb8d022bfb7a41c4a541b99f1eaf
> [systemd] turn off centipede

- infra/helper.py
This lets users importing helper override the log levels just for the helper.
Part of https://github.com/google/osv.dev/issues/1273.
This should mostly be a NFC. The only difference to the log output is that we now get:
```
ERROR:__main__:fad does not seem to exist. Please run build_fuzzers first.
```
Instead of:
```
ERROR:fad does not seem to exist. Please run build_fuzzers first.
```
> helper: log using a Logger object instead.

- projects/bitcoin-core/project.yaml
Attempt to work around the build timeout for now ( https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=58304 )
> bitcoin-core: Remove centipede for now

- infra/build/webapp-fuzz-introspection/Dockerfile
This Dockerfile is meant to be build as part of the GCP project. I tried to make it as simple as possible to make deployment easy.
I've deployed this on a simple gcp project using:
```
git clone https://github.com/ossf/fuzz-introspector
gcloud builds submit --tag gcr.io/${GOOGLE_CLOUD_PROJECT}/webapp-fuzz:1.0.4 .
gcloud run deploy --image=gcr.io/${GOOGLE_CLOUD_PROJECT}/webapp-fuzz:1.0.4 --platform managed
```
Deployment as created by this Dockerfile: https://webapp-cl76vg7p7a-ey.a.run.app/
~~I've limited the number of projects in the above instance to `--max-projects=150`, where this should be set to `--max-projects=10000`. However, I had some issues with resources when doing this on my gcp project, although I think that's just due to me using a small gcp project.~~ I've now set it as how …
> infra: add Dockerfile for fuzz introspection web app

- projects/bs4/bs4_fuzzer.py
> AttributeError: 'bytes' object has no attribute 'pop'
> Fix bs4 fuzzer

- projects/wasmtime/build.sh
This is an attempt to investigate #10186 by moving Rust from the latest nightly to what is in theory a good nightly from when we weren't seeing startup crashes. If this works then it seems like Rust's own nightly compiler is the culprit. If it doesn't I'm hoping I'll figure out what's next best to try after that.
> Temporarily pin Wasmtime to an older nightly Rust

- projects/bitcoin-core/build.sh
- projects/bitcoin-core/project.yaml
Looks like LTO is now confirmed to be the problem, see https://github.com/google/oss-fuzz/pull/10252#issuecomment-1535998849, so revert it.
Also, re-try centipede.
>  bitcoin-core: Revert (thin)LTO due to build timeout, try centipede fuzzing engine

- projects/connectedhomeip/Dockerfile
- projects/connectedhomeip/build.sh
This fixes compilation errors of the form:
```
...
Step #3 - "compile-centipede-address-x86_64": [1m../../src/platform/Linux/ConnectivityManagerImpl.h:211:46: [0m[0;1;31merror: [0m[1m'guarded_by' attribute requires arguments whose type is annotated with 'capability' attribute; type here is 'std::mutex' [-Werror,-Wthread-safety-attributes][0m
Step #3 - "compile-centipede-address-x86_64":     static GDBusWpaSupplicant mWpaSupplicant CHIP_GUARDED_BY(mWpaSupplicantMutex);
Step #3 - "compile-centipede-address-x86_64": [0;1;32m                                             ^
Step #3 - "compile-centipede-address-x86_64": [0m[1m../../src/system/SystemMutex.h:75:49: [0m[0;1;30mnote: [0mexpanded from macro 'CHIP_GUARDED_BY'[0m
Step #3 - "compile-centipede-address-x86_64": #define …
```
> Disable thread safety analysis checks for connectedhomeip

- projects/bs4/bs4_fuzzer.py
In some cases, `soup.css` can be `None`.
> Fix bs4 fuzzer, again

- projects/wget2/build.sh
gnutls is compiled without libdane and wget2 should do this as well to avoid build errors.
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=58348
> wget2: fix build

- projects/open5gs/Dockerfile
- projects/open5gs/build.sh
Update build.sh to use root dir for sed patch.
https://github.com/google/oss-fuzz/issues/10300
> [open5gs] fixing Issue 58803

- projects/envoy/Dockerfile
- projects/envoy/WORKSPACE
Due to a [recent PR](https://github.com/envoyproxy/envoy/pull/27233), Envoy uses the `python_register_toolchains` macro that prevents using python under the root user. This prevents the [build of the fuzzers](https://oss-fuzz-build-logs.storage.googleapis.com/log-c98579dd-6bc2-4b97-8c41-7ca4e37c219c.txt) with the following error:
```
Error in fail: The current user is root, please run as non-root when using the hermetic Python interpreter
```
This PR overrides the WORKSPACE file, allowing the building of the fuzzers with the root user.
> envoy: add WORKSPACE file to override the default

- projects/bind9/build.sh
Fixes a linking issue:
Step #3 - "compile-afl-address-x86_64": /usr/bin/ld: /usr/bin/ld: DWARF error: invalid or unhandled FORM value: 0x25
Step #3 - "compile-afl-address-x86_64": lib/dns/.libs/libdns.a(libdns_la-rbtdb.o): in function `free_rbtdb':
Step #3 - "compile-afl-address-x86_64": rbtdb.c:(.text+0x2bca): undefined reference to `cds_wfs_destroy'
...
> bind9: Also link with -lurcu-common

- projects/crosvm/build.sh
- projects/crosvm/project.yaml
Crosvm was updated to follow a more standard `cargo fuzz` layout. So the build script here can be simplified.
Also addition a few more people interested in our fuzzer results.
Tested with `presubmit.py` and `helper.py build crosvm`
> crosvm: Fix build and add additional cc's to the project

- infra/base-images/base-builder-go/Dockerfile
- infra/base-images/base-builder-go/gosigfuzz.c
- infra/base-images/base-builder/compile_libfuzzer
- infra/base-images/base-builder/install_go.sh
- projects/golang/build.sh
libfuzzer needs to have its signal handler with SA_ONSTACK because golang stacks are small and not guarded against overflows
Waiting for the clang libfuzzer patch cf https://reviews.llvm.org/D150231, we can fix the signal handlers with the help of `LLVMFuzzerInitialize`
Long story : https://github.com/golang/go/issues/49075
cc @randal77
cc @DavidKorczynski for go119build
I hope it will improve the stability of all golang projects
> golang: fixes libfuzzer signal handling

- projects/flac/build.sh
Currently coverage for some flac fuzzers is missing for some complicated inputs. I'd like to add a few seeds manually for this.
I am assuming that adding a (cherry-picked) seed corpus will result in it being 'added' to the existing corpus, not replacing it. Please let me know whether that assumption is correct.
BTW, the `|| exit 0` is because I'd like to test the seed corpora with CI-Fuzz, which means I cannot add them before this change is merged, and makes sure the build doesn't fail despite no seed corpora being present yet.
> [flac] Prepare for addition of seed corpora

- projects/bitcoin-core/build.sh
This is no-longer required after project changes. See: https://github.com/bitcoin/bitcoin/pull/27699.
> bitcoin-core: remove MSAN workaround

- projects/sound-open-firmware/Dockerfile
- projects/sound-open-firmware/build.sh
- projects/sound-open-firmware/project.yaml
[First submission to oss-fuzz.  Not sure if I'm checking all the correct boxes to get this submitted successfully.  Be gentle.]
SOF has a new fuzzing framework that leverages the underlying Zephyr OS's native_posix integration to get a more complete build than just the protocol layer.  In theory all the non-hardware-specific code is reachable from the fuzzer inputs.
Also adds support for the newer "IPC4" protocol as a separate target.
> projects/sound-open-firmware: New fuzzing framework

- projects/ffms2/build.sh
You can't use /out as this does not exist in our production builds. Use $OUT instead.
> Fix ffms2 build

- projects/sound-open-firmware/Dockerfile
The srcmap tool assumes that all git trees will have been pulled from a remote named "origin", which is not true for west.  Hack in a duplicate remote to conform to convention.
> projects/sound-open-firmware: Fix remote name to be "origin"

- docs/getting-started/new_project_guide.md
It is not clear what sanitizers could be specified in `sanitizers` field in project.yaml. Patch adds a list of available sanitizers to a "New project guide".
> docs: add a list with available sanitizers

- projects/openh264/build.sh
The dynamic library is not used and this will enable fuzz introspector
> openh264: only build static library

- projects/jsonnet/build.sh
We only need to build the static library in jsonnet so am restricting the build to do that. This enables Fuzz Introspector
> jsonnet: only build required libraries

- projects/cmark/build.sh
Only build the static library required by the fuzzer
> cmark: enable fuzz introspector

- projects/sqlite3/build.sh
This makes it work with Fuzz Intropector
> sqlite3: only build needed libraries

- projects/cmake/build.sh
Only build the static library needed for the fuzzers.
> cmake: fix up fuzz introspector build

- projects/jbig2dec/Dockerfile
- projects/jbig2dec/build.sh
.zip folders are no longer available.
> jbig2dec: fix build and make introspector work

- projects/pistache/build.sh
This enables fuzz introspector
> pistache: only build required library

- infra/base-images/base-builder/compile_javascript_fuzzer
- projects/javascript-example/build.sh
- projects/ua-parser-js/build.sh
This causes issues in two cases:
1. using other package managers than npm, e.g., yarn.
2. fuzzing pure ECMAScript projects. In this case, we have to transform those projects into CommonJS projects so that they can be instrumented properly.
> Do not install Jazzer.js in the compile_javascript_fuzzer script

- projects/bitcoin-core/Dockerfile
- projects/bitcoin-core/build.sh
LTO=1 temporarily disabled due to https://github.com/google/oss-fuzz/pull/9461#issuecomment-1568189633
Also, avoid wasting storage space on a docker layer by merging the two layers.
cc @dergoegge @fanquake
> bitcoin-core: Temporarily disable LTO=1

- projects/zip4j/build.sh
The Maven build process requires fetching dependency libraries from the central repository with Apache Wagon. This fetching action will fail because of an unstable connection or connection rest by the repository server because there are too many fetching requests. By default, maven build does not retry the fetching if it is not an error in the request-sending methods. Thus these failing dependency fetching will cause maven project fail to build randomly. This PR fixes the build script to configure the maven wagon parameter to force it to retry when failing and also increases the timeout and retry count to decrease the chance of build failure from dependencies fetching failure cases.
> zip4j: Add retry handler setting for maven build

- projects/bitcoin-core/project.yaml
centipede passes locally and in the GitHub Actions CI in this repo, but not on OSS-Fuzz. :man_shrugging: 
Disable it for now @dergoegge @fanquake
> bitcoin-core: Temporarily disable centipede

- docs/advanced-topics/ideal_integration.md
**PR Summary**:
The PR contains a fix to a broken hyperlink found in the docs. The relevant page of the docs can be found [here](https://google.github.io/oss-fuzz/advanced-topics/ideal-integration/#fuzz-target).
> FIX: update broken hyperlink in the docs

- projects/tint/build.sh
`spirv-tools` now requires `abseil-cpp` in order to build.
Fetch this into the `spirv-tools/external` directory to fix the build of `tint`.
Bug: [oss-fuzz:59403](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=59403)
> tint: Add abseil-cpp dependency to fix build

- projects/freerdp/build.sh
- projects/freerdp/project.yaml
Depends on PR https://github.com/FreeRDP/FreeRDP/pull/9019
> [FreeRDP] Pass CMake flag BUILD_TESTING and use a target for building fuzzers

- .github/workflows/pr_helper.yml
[PR helper failed ](https://github.com/google/oss-fuzz/actions/runs/5193059405/jobs/9364838612)on fork branch as the [maximum access for pull requests from public forked repositories is read](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token). 
Convert to [pull_request_target ](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target).
Difference between pull_request and pull_request_target: [github blog](https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/), [stack overflow](https://stackoverflow.com/questions/74957218/what-is-the-difference-between-pull-request-and-pull-request-target-event-in-git#:~:tex …
> Update pr helper trigger on pull_request_target

- projects/clamav/build.sh
We had been using an un-released bzip2 1.1.0 version that had the incorrect library name (libbz2_static.a).
We're switching to the released 1.0.8 (completed here: https://github.com/Cisco-Talos/clamav-mussels-cookbook/pull/36) , and now we have to switch to the correct static library name in any build instructiosn that use the dependencies built by those recipes.
> [clamav] Change library name of bz2 dependency in build script

- projects/hostap/build.sh
dataflow was removed, trying to build it is an error:
```
helper.py build_fuzzers: error: argument --sanitizer: invalid choice: 'dataflow' (choose from 'address', 'none', 'memory', 'undefined', 'thread', 'coverage', 'introspector', 'hwaddress')
> hostap: Remove unused dataflow workaround

- projects/ndpi/build.sh
Since https://github.com/ntop/nDPI/commit/96340ccea22fc5deeba6a4fd523a6d0d0fbde5cb the script for building oss-fuzz stuff is available directly in the nDPI project. This way, we can easily update it, without bothering oss-fuzz guys...
> nDPI: use upstream build script

- projects/wasmtime/build.sh
The latest nightly breaks the build for one of our dependencies so pin it to an older version which works while our dependency updates.
> Pin Wasmtime to an older nightly build

- infra/base-images/base-runner/coverage
Currently there is no consistent logging or information about the number of fuzz targets for a given project. This PR adds a file in the fuzzer stats directory with such information by way of the coverage runner.
The use of this comes making https://introspector.oss-fuzz.com where we'd like to display how many fuzzers exist for each project. This is to make https://introspector.oss-fuzz.com available to all projects with successful coverage builds, whereas currently it's only for projects with successful introspector builds, which is too limiting. Once we have the number of fuzzers for each project then we have enough to switch https://introspector.oss-fuzz.com into showing data about all projects with coverage builds, including those that fail introspector builds and also …
> infra: dump names of all fuzz targets used in coverage analysis

- infra/base-images/base-runner/coverage
When running fuzz targets we check for validity by checking if `LLVMFuzzerTestOneInput` exists in the target file: https://github.com/google/oss-fuzz/blob/8d1f1306fda3464fb3a7ec8b4227308d315ed495/infra/base-images/base-runner/coverage#L307-L314 However, this is not done in the post processing step of the coverage utility: https://github.com/google/oss-fuzz/blob/8d1f1306fda3464fb3a7ec8b4227308d315ed495/infra/base-images/base-runner/coverage#L415-L418
This causes coverage build issues e.g.
https://oss-fuzz-build-logs.storage.googleapis.com/log-b8d4899d-ecc3-498c-8485-2e88d162dc57.txt
```
Step #5: [INFO] Loading execution data file /workspace/out/libfuzzer-coverage-x86_64/dumps/OpenSSHConfigFuzzer.exec.
Step #5: [INFO] Analyzing 3 classes.
Step #5: [INFO] Loading execution data file …
```
> base-runner: check fuzz target validity for jvm targets

- projects/asteval/fuzz_eval.py
This exception is raised spuriously, which causes some issues wrt. coverage builds and trial builds. They are failing on-and-off.
> asteval: catch additional exception

- projects/cryptofuzz/Dockerfile
- projects/cryptofuzz/build.sh
Different Go versions can have different bugs. This builds Go 1.19, 1.20 and the dev branch into the binaries for NSS, OpenSSL and BoringSSL respectively.
> [cryptofuzz] Fuzz Go 1.19, 1.20 and dev branch

- infra/pr_helper.py
1. Don't repeat criticality score for each file, only for each project.
2. Don't link to past issues to avoid notifying people unnecessarily
3. Don't @-mention people so we don't send more notifications.
> Fix issues with PR helper

- projects/lotus/Dockerfile
- projects/lotus/build.sh
Lotus is enforcing a minimum Go version in its build system, which makes the build currently fail on OSS-Fuzz.
This should fix it.
> Lotus: fixing build issues by using right Go version

- projects/libgit2/Dockerfile
> libgit2: remove autotools deps

- projects/giflib/Dockerfile
binutils is in the base image.
CMake is used otherwise.
> giflib: prune dockerfile deps

- projects/bzip2/Dockerfile
bzip2 invokes the compiler directly, neither using autotools, or wget.
> bzip2: drop dependencies

- infra/build/functions/build_lib.py
- infra/build/functions/target_experiment.py
This launches a GCB build for a project, runs a specified fuzz target with specified arguments, and uploads the output to a specified path.
e.g.
```
python infra/build/functions/target_experiment.py --project=libxml2 --target xml \
--output_log gs://oss-fuzz-gcb-experiment-run-logs/output.log -- -max_total_time=30
```
> Add target experiment script.

- projects/wolfssl/Dockerfile
- projects/wolfssl/build.sh
dataflow was removed, trying to build it is an error:
```
helper.py build_fuzzers: error: argument --sanitizer: invalid choice: 'dataflow' (choose from 'address', 'none', 'memory', 'undefined', 'thread', 'coverage', 'introspector', 'hwaddress')
```
Also, unpin image
> wolfssl: Cleanups

- projects/bitcoin-core/build.sh
cc @MarcoFalke @dergoegge
Builds locally with:
```bash
python3 infra/helper.py build_fuzzers bitcoin-core --engine libfuzzer --sanitizer address --architecture i386
```
> bitcoin-core: re-enable DEBUG=1 for 32-bit builds

- projects/zlib/build.sh
- projects/zlib/project.yaml
This was disabled 4 years ago, due to issues with MSAN.
I currently cannot reproduce under MSAN.
If the issue does reproduce, we could better document what it is.
> zlib: re-enable "make check"

- projects/avro/project.yaml
I cannot login and see the reports with my @apache.org email. OSS-Fuzz supports only OAuth login via GMail and Github
Related-to: https://github.com/google/oss-fuzz/pull/10453
> Update the email of the primary contact for Apache Avro

- infra/pr_helper.py
Update repo_url as criticality score does not support url ends with '.git'. 
Example: 
~/go/bin$ `./criticality_score --format json -gcp-project-id=clusterfuzz-external https://github.com/kubernetes/kubernetes.git`
2023-06-21 14:27:39.583	INFO	Preparing default scorer
2023-06-21 14:27:41.007	INFO	deps.dev signal source enabled
`2023-06-21 14:27:41.869	WARN	Repo cannot be collected	{"worker": 0, "url": "https://github.com/kubernetes/kubernetes.git", "error": "repo failed: not found: https://github.com/kubernetes/kubernetes.git"}`
> Update pr_helper criticality score

- docs/getting-started/accepting_new_projects.md
- infra/pr_helper.py
The PR Helper workflow complains if a new project doesn't include a main_repo, so I've added that to the accepting new projects page.
I also added links from there to the specific fields in the new project guide.
I also changed a reference in the workflow output to refer to the yaml field name visible to submitters, rather than to the internal python name for the same field which doesn't match.
> Add main_repo and language to new project doc, and links to field explanations. Fix workflow reference to repo_url.

- projects/tensorflow/build.sh
The build is currently failing in UBSAN since a target is not compatible. This fixes it.
> tensorflow: fix UBSAN build

- projects/fluxcd/Dockerfile
- projects/fluxcd/build.sh
We're migrating all Flux controllers to Go 1.20 and we're blocked by `cr.io/oss-fuzz-base/base-builder-go` which comes with Go 1.19. This PR installs Go 1.20 over 1.19 and adds `export CXX="${CXX} -lresolv"` to the build script to avoid:
```
Building ./internal/controller/gitrepository_controller_fuzz_test.go.FuzzRandomGitFiles into FuzzRandomGitFiles
+ echo 'Building ./internal/controller/gitrepository_controller_fuzz_test.go.FuzzRandomGitFiles into FuzzRandomGitFiles'
+ compile_native_go_fuzzer ./internal/controller FuzzRandomGitFiles FuzzRandomGitFiles
/usr/bin/ld: /usr/bin/ld: DWARF error: invalid or unhandled FORM value: 0x25
FuzzRandomGitFiles.a(000020.o): in function `_cgo_cbcce81e6342_C2func_res_search':
cgo_unix_cgo_res.cgo2.c:(.text+0x32): undefined reference to `__res_search' …
```
> Update fluxcd to Go 1.20

- docs/getting-started/new-project-guide/swift_lang.md
- docs/getting-started/new_project_guide.md
All other language-specific guide files are named `foo_lang.md`, as distinct from `bazel.md` which is not for an implementation language (and should probably get its own suffix, maybe bazel_build.md, but that's another matter).
> Rename swift.md for consistency with _lang.md pattern

- docs/getting-started/new_project_guide.md
This seems to have been left out when `javascript_lang.md` was created and support for `language: javascript` was added.
> Add javascript to new project guide

- infra/base-images/base-builder/bazel_build_fuzz_tests
- infra/base-images/base-builder/compile
- infra/base-images/base-builder/install_java.sh
This reverts commit cac7ccd85bfefe90dc51d251567df73ad14654e1.
> Reland "[infra] Update Jazzer to v0.17.1" (#10537)"

- projects/promise-polyfill/Dockerfile
- projects/promise-polyfill/babel.config.json
- projects/promise-polyfill/build.sh
- projects/promise-polyfill/fuzz.js
- projects/promise-polyfill/project.yaml
[promise-polyfill] initial integration
> [promise-polyfill] initial integration

- projects/tslib/Dockerfile
- projects/tslib/build.sh
- projects/tslib/fuzz.js
- projects/tslib/project.yaml
> [tslib] initital integration

- projects/igraph/Dockerfile
- projects/igraph/project.yaml
Two changes:
- Simplify Dockerfile, do not install packages which are no longer used as dependencies
- Remove `fuzzing_engines` from `project.yaml` to ensure that all fuzzing engines are used, including centipede
> igraph: remove unused dependencies, enable centipede

- projects/libfido2/Dockerfile
- projects/libfido2/build.sh
With OpenSSL 1.1's imminent EOL, switch libfido2 to OpenSSL 3.0. While here, update libcbor to 0.10.2. Tested locally with asan/msan and libFuzzer, Honggfuzz, and AFL.
> [libfido2] Switch to OpenSSL 3.0, update libcbor

- infra/base-images/base-runner/coverage
- infra/helper.py
This turns off the http report serving after a successful generation.
> Add a --no-serve option to the helper coverage command.

- infra/build/fuzz-introspector-webapp/cloudbuild.yaml
The webapp was down due to OOM.
> Bump memory on fuzz introspector webapp.

- infra/helper.py
For example, ANSI colors will not be used when `stdin` is mapped to `DEVNULL`.
> disable ANSI color in the output of `build_fuzzers` when stdin's file descripter is not a terminal

- infra/build/functions/build_project.py
`tee` will override the compile return code.
> Don't tee build logs.

- projects/wasmtime/build.sh
Upstream issues have been fixed and fuzzers can now build again with the latest nightly release.
> Unpin Wasmtime's rust compiler version

- projects/powerdns/build.sh
This is now required for the build to pass.
See https://github.com/PowerDNS/pdns/pull/12931
> powerdns: Build the arcrandom target first

- projects/xz/build.sh
Indirect function support was added to xz on machines that support it for function dispatching. ifunc is not compatible with -fsanitize=address, so this should be disabled for fuzzing builds.
> xz: Disable ifunc to fix Issue 60259.

- projects/mp4san/Dockerfile
- projects/mp4san/build.sh
- projects/mp4san/project.yaml
This adds a new project, the Rust crate [mp4san](https://github.com/privacyresearchgroup/mp4san), which is used in the popular Signal messaging app: https://github.com/signalapp/libsignal/blob/main/rust/media/Cargo.toml.
> Add new project: mp4san

- projects/wuffs/Dockerfile
Per https://github.com/google/oss-fuzz/issues/10610 "MozillaSecurity/fuzzdata to be decomissioned soon".
Updates #10610
> [wuffs] use fork of MozillaSecurity/fuzzdata

- projects/keycloak/project.yaml
@arthurscchan @AdamKorcz @jonathanmetzman we created a dedicated mailing list for oss-fuzz and I would like us to change it. The change aims to have a focused communication channel for build failures and potential alerts about it. Could you please review?
//cc @stianst
> Update the Keycloak contacts

- projects/libjpeg-turbo/Dockerfile
Because of 5cc77a3fde7edc0b6fbb88636811185214d2d963, $SRC/libjpeg-turbo/ no longer exists, so the test images from the libjpeg-turbo source tree have not been added to the seed corpora .zip files since then.  This commit causes the test images from the source trees of all supported libjpeg-turbo branches to be added to the seed corpora .zip files.
> [libjpeg-turbo] Re-add libjpeg-turbo test images to seed corpora

- infra/presubmit.py
Currently a `project.yaml` with wrong key names will result in the following error:
```
...
return all([check(changed_files) for check in checks])
File "infra/presubmit.py", line 229, in check_project_yaml
return all([_check_one_project_yaml(path) for path in paths])
File "infra/presubmit.py", line 229, in <listcomp>
return all([_check_one_project_yaml(path) for path in paths])
File "infra/presubmit.py", line 223, in _check_one_project_yaml
return checker.do_checks()
File "infra/presubmit.py", line 131, in do_checks
check_function()
File "infra/presubmit.py", line 179, in check_valid_section_names
self.error(f'{name} is not a valid section name ({valid_names})')
NameError: name 'valid_names' is not defined
```
This fixes it.
> infra: fix presubmit when project.yaml fails

- infra/build/functions/target_experiment.py
- Fix coverage report generation. The wrong corpus was being used.
- Delete the corpus.zip after we upload it.
> target_experiment: fixes.

- projects/bls-signatures/Dockerfile
- projects/bls-signatures/build.sh
- Remove Chia because it now uses the blst library, which this project already fuzzes
- Add Constantine, which is a BLS signature library written in Nim
> [bls-signatures] Remove Chia, add Constantine

- projects/libecc/Dockerfile
- projects/libecc/build.sh
Compile wolfCrypt (which serves as an oracle to libecc) with support for the SM2 and SM3 algorithms.
Also make wget quiet
> [libecc] Support SM2, SM3

- projects/connectedhomeip/Dockerfile
This fixes the CHIP build, since python cryptography requires PEP 517 which in turn requires a more recent pip. Several issues seem to have compounded here:
- cryptography requires PEP517, basically needing a newer pip
- oss-fuzz docker image has 2 pythons installed (/usr/bin and /usr/local/bin)
- oss-fuzz deactivates the build environment for the actual build, losing some python setup
Changes:
- upgrade pip
- ensure `/usr/bin` takes precedence over `/usr/local/bin` to use the right updated python
- install build requirements since the build script seems to deactivate the chip build environment (and that breaks ninja build requirements)
> [connectedhomeip] Update PIP to latest in Dockerfile

- projects/sound-open-firmware/project.yaml
Add Flavio Ceolin from Intel. Remove Harsha who is no longer active.
This PR replaced https://github.com/google/oss-fuzz/pull/10654
> sound-open-firmware: update additional CCs

- projects/pulumi/Dockerfile
- projects/pulumi/build.sh
> pulumi: bump Go

- projects/powerdns/build.sh
Branches for stable versions do not have the ext/arc4random directory so they no longer build properly.
> powerdns: Fix the build on old branches

- projects/bignum-fuzzer/Dockerfile
- projects/cryptofuzz/Dockerfile
- projects/ecc-diff-fuzzer/Dockerfile
- projects/libressl/Dockerfile
- projects/mbedtls/Dockerfile
- projects/nettle/Dockerfile
mbedtls needs jsonschema which needs rpds-py which needs pip>=20 or a Rust toolchain. The base oss-fuzz image has pip 19, resulting in an error when installing rpds-py:
```
ERROR: Could not build wheels for rpds-py which use PEP 517 and cannot be installed directly
```
Fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=60485, https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=60492, https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=60429
> Fix mbedtls build

- projects/bignum-fuzzer/Dockerfile
- projects/cryptofuzz/Dockerfile
- projects/libressl/Dockerfile
- projects/nettle/Dockerfile
At some point we downloaded gmp from gmplib.org which had expired certificates for a while. Now that we're not downloading from gmplib.org, this is no longer needed.
> Remove workaround for gmp download

- infra/build/functions/project_experiment.py
This allows us to run arbitrary scripts inside project containers on GCB.
All files in `/workspace/out` are upload to a specified GCS path at the end. 
Usage:
```bash
$ python project_experiment.py --project libxml2 --command 'python3 /workspace/hello.py' \
--experiment_name test-ochang \
--upload_output gs://BUCKET/to/upload/NAME
```
(Where /workspace is the OSS-Fuzz repository).
> Add project_experiment.py

- projects/go-dhcp/Dockerfile
- projects/go-dhcp/build.sh
- projects/go-dhcp/project.yaml
The DHCP library is used by many [PublicProjects](https://github.com/insomniacslk/dhcp#public-projects-that-use-it).
Merged PR : https://github.com/insomniacslk/dhcp/pull/508
My Proposal https://github.com/insomniacslk/dhcp/pull/508#discussion_r1268886577
> [go-dhcp] initial integration

- projects/inih/Dockerfile
- projects/inih/build.sh
- projects/inih/project.yaml
Old PR: https://github.com/google/oss-fuzz/pull/1525
My inih PR: https://github.com/benhoyt/inih/pull/153
IniH is a default library for INI parsing in Red Hat based systems. It is installed by default in Fedora for parsing INI files. 
According to program, it is also used in embedded systems.
Can the OSS-Fuzz team accept this project for mainstream fuzzing?
> [inih] initial integration

- infra/build/functions/project_experiment.py
Copy the content in `/workspace/out/` only.
No need to copy the parent `out` directory level.
> Minor fix `project_experiment.py`

- projects/apache-poi/Dockerfile
- projects/apache-poi/build.sh
- projects/apache-poi/src/main/java/org/apache/poi/XLSX2CSVFuzzer.java
The initial fuzzing of Apache POI seems to be broken (or did not work at all until now).
This PR adds the necessary versions of JDK 8 and 11 for building Apache POI.
They also adjust the fuzz-target slightly to not quickly fail during fuzzing due to another type of
"expected" exception.
Also the checkout can be done shallow to reduce the amount of downloaded data.
This hopefully closes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=56337&can=1&q=poi (and maybe https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=54562&can=1&q=poi as well)
> Fix apache poi

- infra/base-images/base-builder/build_jcc.bash
- infra/base-images/base-builder/jcc.go
Otherwise results in a linking error.
> Link "fixed" C to C++ targets with libc++.

- projects/libjxl/Dockerfile
jpegli fuzzer target now depends on third_party/libjpeg-turbo files
> Fix libjxl

- projects/immer/Dockerfile
- install pkg-config, available as distro package
- install Catch2 from sources, as it is not available in Ubuntu 20.04
> immer: install pkg-config & Catch2

- projects/cpython3/build.sh
`Modules/_xxtestfuzz/fuzzer.c` in CPython started using private API in https://github.com/python/cpython/commit/89f987544860d1360e6232b6f52b8ced92a4d690#diff-a22ac7579f23068e0c6bcacf1086ee962fdf8e68725cf0510b42d0a389cf1efd.
This made fuzzing builds fail https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=60831.
Including needed header files fixes the error.
> Fix building CPython after python/cpython#107026

- projects/apache-poi/pom.xml
- projects/apache-poi/project.yaml
- projects/apache-poi/src/main/java/org/apache/poi/EncryptDecryptFuzzer.java
- projects/apache-poi/src/main/java/org/apache/poi/POIFuzzer.java
- projects/apache-poi/src/main/java/org/apache/poi/POIHDGFFuzzer.java
- projects/apache-poi/src/main/java/org/apache/poi/POIHMEFFuzzer.java
- projects/apache-poi/src/main/java/org/apache/poi/POIHPBFFuzzer.java
- projects/apache-poi/src/main/java/org/apache/poi/POIHPSFFuzzer.java
- projects/apache-poi/src/main/java/org/apache/poi/POIHSLFFuzzer.java
- projects/apache-poi/src/main/java/org/apache/poi/POIHSSFFuzzer.java
- projects/apache-poi/src/main/java/org/apache/poi/POIHWPFFuzzer.java
- projects/apache-poi/src/main/java/org/apache/poi/POIOldExcelFuzzer.java
- projects/apache-poi/src/main/java/org/apache/poi/POIVisioFuzzer.java
- projects/apache-poi/src/main/java/org/apache/poi/POIXSLFFuzzer.java
- projects/apache-poi/src/main/java/org/apache/poi/POIXSSFFuzzer.java
- projects/apache-poi/src/main/java/org/apache/poi/POIXWPFFuzzer.java
- projects/apache-poi/src/main/java/org/apache/poi/XLSX2CSVFuzzer.java
After getting project apache-poi to mostly build fine, we can add more
fuzz targets to cover much more of the library.
The currently used `XLSX2CSV` is only a small example usage of Apache POI 
and does not cover much actual functionality.
Therefore this PR adds a number of fuzz targets which will trigger fuzzing of the various 
supported formats of Apache POI. 
Many expected exceptions are already handled so that we should only get very 
few additional ones which we can either fix in the library or in the fuzz targets.
Also rework XLSX2CSVFuzzer as it is strange that it uses an string input
when the expected data is actually binary.
Finally move from @gmx.at to @gmail.com in CCS to be able to open bug-reports
for Apache POI
> Apache poi more fuzz targets

- projects/graphql-java/build.sh
Fix missing slf4j dependencies for the GraphqlFuzzer.
> graphql-java: Fix missing dependency

- projects/rdf4j/ParserFuzzer.java
In https://github.com/eclipse/rdf4j/blob/main/core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/BaseDeclProcessor.java#L73, the method throws an IllegalArgumentException when the input does not fulfil some of the conditions which could happen when we fuzz the project. This PR fixes the fuzzer by capturing the exception.
> rdf4j: Fix exception handling for ParserFuzzer

- projects/apache-poi/build.sh
- projects/apache-poi/src/main/java/org/apache/poi/POIFuzzer.java
- projects/apache-poi/src/main/java/org/apache/poi/POIHSMFFuzzer.java
- projects/apache-poi/src/main/java/org/apache/poi/XLSX2CSVFuzzer.java
- projects/apache-poi/src/main/resources/log4j2.xml
Now that fuzzing and introspector is working again, we can improve the fuzzing itself by adding seed corpus archives for all the fuzzers.
Also let's reduce output during fuzzing and add/adjust fuzzers some more.
> Apache POI: Add seed corpus, remove logging, add HSMF

- projects/libavc/project.yaml
- projects/libhevc/project.yaml
- projects/libmpeg2/project.yaml
undefined sanitizer was so far marked experimental for libavc, libhevc and libmpeg2. 
That experimental tag is now removed in this.
> [libavc, libhevc, libmpeg2]: Remove experimental tag on ubsan

- projects/p11-kit/Dockerfile
p11-kit build infrastructure will require Python for code generation: https://github.com/p11-glue/p11-kit/pull/537
> p11-kit: install python3 in the base image

- projects/apache-poi/src/main/java/org/apache/poi/POIHSSFFuzzer.java
- projects/apache-poi/src/main/java/org/apache/poi/POIVisioFuzzer.java
- projects/apache-poi/src/main/java/org/apache/poi/POIXSSFFuzzer.java
The new fuzz-targets for Apache POI combined with the seed-corpus now lead to a number of interesting new exceptions!
But some of them are actually expected. Partly because the Docker image does not provide a full font-setup for the JDK.
See also previous discussion at #7380 
This PR should resolve bugs 61247, 61244, 61253.
> Apache POI: more expected exceptions

- projects/ohc/OhcFuzzer.java
This PR fixes a possible buffer underflow for the implied ReadableByteChannel in the OhcFuzzer.
> ohc: Fix possible buffer underflow

- projects/keycloak/Dockerfile
Add jdk 17 installation in the dockerfile for keycloak project which depends on JDK 17. The new approach uses apt install instead of plain download of JDK-17 to avoid missing native dependencies.
> keycloak: Install JDK 17 for keycloak project

- projects/matio/Dockerfile
- projects/matio/project.yaml
The git repository in sf wasn't updated more than a year.
@tbeu Do you approve?
> Change matio repository from sf to github

- projects/apache-poi/src/main/java/org/apache/poi/POIVisioFuzzer.java
- projects/apache-poi/src/main/java/org/apache/poi/XLSX2CSVFuzzer.java
Another round of oss-fuzz runs showed two more Exceptions which are expected with some input.
This should fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=61293 and https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=61302
> apache-poi: Add some more expected exceptions

- docs/index.md
Add two paragraphs from blog post (https://security.googleblog.com/2022/09/fuzzing-beyond-memory-corruption.html) explaining the project's history.
> Olivekl add project history

- projects/lua/build.sh
Corpus for test lua_loadbuffer_proto is huge, it contains about 80k files and zip reports an error on compression: `/usr/bin/zip: Argument list too long`. The patch fixes that by passing a list of files via stdin.
Disable leak detection: 
- https://github.com/ligurio/lua-c-api-tests/issues/25
- https://github.com/ligurio/lua-c-api-tests/issues/28
> [lua] read a list of files via stdin

- projects/typescript/Dockerfile
- projects/typescript/build.sh
- projects/typescript/fuzz_json_parser.js
- projects/typescript/fuzz_scanner.js
- projects/typescript/fuzz_transpile_module.js
Adds 3 additional fuzzing harnesses targeting the transpiler, JSON config parser, and the scanner compiler API.
> [typescript]: add additional harnesses

- projects/kyverno/Dockerfile
- projects/kyverno/build.sh
I have recently moved the fuzzers upstream. This PR builds them from there instead of cncf-fuzzing.
> kyverno: build upstream fuzzers

- docs/research/target_generation.md
I thought we might like to link back to the blog from the research report. 
[See preview](https://hayleycd.github.io/oss-fuzz/research/llms/target_generation/)
> Link to blog from research report

- projects/keycloak/Dockerfile
This PR adds additional environment variable for the keycloak project. This environment variable specify its target package prefix for fuzz-introspector frontend to exclude analysing dependencies.
> keycloak: Add target package prefix for keycloak

- projects/lua/Dockerfile
- projects/lua/build.sh
- projects/lua/fuzz_lua.c
- projects/lua/project.yaml
- lua: support i386 architecture
- lua: fix compiler warning
- lua: fix homepage url
> Support i386 in Lua

- projects/apache-poi/pom.xml
- projects/apache-poi/src/main/java/org/apache/poi/POIFuzzer.java
- projects/apache-poi/src/main/java/org/apache/poi/POIXSLFFuzzer.java
A few new types of Exceptions popped up when fuzzing Apache POI. Let's ignore those as well.
Also add dependency to log4j-core to not have log4j log everything to stdout instead of suppressing log-output completely as intended.
Should fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=61363 and https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=61446
> Apache poi more expected exceptions and reduce logging some more

- projects/freerdp/build.sh
Enabling SWSCALE by default broke a build.
Broken by commit 67bc4565 ("[cmake] default to require FFMPEG and SWCALE").
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=60211#c33
> freerdp: fix building

- projects/aspectj/Dockerfile
Add TARGET_PACKAGE_PREFIX environment variable for fuzz-introspector to ignore analysing on dependency classes.
> aspectj: Fix target package prefix for aspectj

- projects/apache-poi/Dockerfile
Add TARGET_PACKAGE_PREFIX environment variable for fuzz-introspector to ignore analysing on dependency classes.
> apache-poi: Add target package prefix

- projects/typescript/Dockerfile
- projects/typescript/fuzz_ast.js
- projects/typescript/fuzz_compiler.js
- projects/typescript/fuzz_json_parser.js
- projects/typescript/fuzz_scanner.js
- projects/typescript/fuzz_transpile_module.js
- projects/typescript/fuzz_util.js
This cleans up the harnesses some more and refactors some common helper functions in a `fuzz_utils.js` while also ignoring a certain bug class that, after discussion with the TypeScript team, is not interesting, so we treat it as a blocker and will ignore those now.
> [typescript]: remove fuzz blockers and cleanup harnesses

- projects/lua/build.sh
This enables fuzz introspector for lua.
The [current build](https://oss-fuzz-build-logs.storage.googleapis.com/log-95e09fbf-701e-4adf-ad25-8629c7dd5f8a.txt) fails with:
```
Step #6 - "compile-libfuzzer-introspector-x86_64": [Log level 1] : 10:13:22 : This means a main function is in the source code rather in the libfuzzer library, and thus we do not care about it. We only want to study the actual fuzzers. Exiting this run.
Step #6 - "compile-libfuzzer-introspector-x86_64": /usr/bin/ld.gold: internal error in read_header_prolog, at ../../gold/dwarf_reader.cc:1678
Step #6 - "compile-libfuzzer-introspector-x86_64": clang-15: fatal error: linker command failed with exit code 1 (use -v to see invocation)
Step #6 - "compile-libfuzzer-introspector-x86_64": make: *** [makefile:119: lua] Error 1 …
```
> lua: enable fuzz introspector

- infra/base-images/base-builder/compile_native_go_fuzzer
It appears that `gofuzz` was removed from the default tagspec in the main branch of go-118-fuzz-build [^1] to `gofuzz_libfuzzer` and `libfuzzer`.  To keep compatibility with the go build scripts, this change adds the gofuzz tag to the go-118-fuzz-build invocation. 
[^1]: https://github.com/AdamKorcz/go-118-fuzz-build/pull/9/files#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261L35
> fix: add gofuzz tags to build

- infra/base-images/base-builder/jcc/jcc.go
Tested on `ada-url`.
Does not work on `bzl` projects (e.g. `abseil-cpp` for now.
> Generate AST of the target file while building project.

- projects/libstdcpp/Dockerfile
- projects/libstdcpp/build.sh
- projects/libstdcpp/project.yaml
this adds a fuzzer for format in the gnu standard C++ library
this particular fuzzer has found several bugs which have been reported upstream and fixed. ([110860](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=110860), [110862](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=110862) and [110868](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=110868))
the code is partially based on the fuzzers I made for the {fmt} library already on oss-fuzz.
I have contacted Jonathan Wakely @jwakely from upstream who has agreed to be a mail cc and is OK with this work taking place.
since fuzzing a standard library while using another one is a bit weird, I am not sure I got everything right but this is a place to start and improve from. in particular, memory sanitizer does not work so I disabled it.
> [libstdc++] initial integration

- projects/brpc/build.sh
We only need to link the executables used for fuzzing. brpc has a lot of unit tests that need linking, and because of -j(nproc) the cloud builders are currently being killed due to resource exhaustion. This focuses the build more on what we need and enables fuzz introspector.
> brpc: enable fuzz introspector

- infra/base-images/base-builder/compile_native_go_fuzzer
Add the tagspec to the coverage build as well to include the correct files.  
ref: https://github.com/google/oss-fuzz/pull/10884
> fix: add tags to go test as well

- projects/apache-poi/src/main/java/org/apache/poi/POIXSSFFuzzer.java
- projects/apache-poi/src/main/java/org/apache/poi/POIXWPFFuzzer.java
One more expected exception when font-libraries are missing and add slightly more coverage.
This should fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=61501
> apache-poi: expect one more exception

- projects/mutagen/Dockerfile
This should fix the following issue:
```
Step #1:  ---> 22f958f99cac
Step #1: Step 2/4 : RUN git clone 	--depth 1 	--branch master 	https://github.com/quodlibet/mutagen
Step #1:  ---> Running in 77c762382f3f
Step #1: [91mCloning into 'mutagen'...
Step #1: [0m[91mwarning: Could not find remote branch master to clone.
Step #1: fatal: Remote branch master not found in upstream origin
Step #1: The command '/bin/sh -c git clone 	--depth 1 	--branch master 	https://github.com/quodlibet/mutagen' returned a non-zero code: 128
Finished Step #1
ERROR
ERROR: build step 1 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 128
Step #1: [0m
```
> Don't specify the branch for mutagen

- projects/powerdns/build.sh
PowerDNS recently [1] refactored the way fuzzing targets were handled, and decided to split them per-product inside the monorepo. We thus now need to build the DNSDist targets separately from the Authoritative Server's ones.
[1]: https://github.com/PowerDNS/pdns/pull/13145
> powerdns: Build the DNSDist fuzzing target again

- projects/apache-poi/src/main/java/org/apache/poi/POIXWPFFuzzer.java
- projects/apache-poi/src/main/java/org/apache/poi/XLSX2CSVFuzzer.java
Add two more Exceptions which popped up when running fuzzing at large scale.
There is one more place where font-handling is triggered, but not available
on the VMs that run fuzzing
> apache-poi: expect 2 more exceptions

- projects/powerdns/build.sh
Stable branches do not have the recent per-product split that was introduced in #10926, and thus CI Fuzz fails on them. This commit checks that there actually is at least one fuzzing target in the `dnsdistdist/` directory before trying to build them, so that this step can be skipped on older branches.
> powerdns: Fix CI Fuzz on stable branches

- infra/base-images/base-builder/install_javascript.sh
- infra/base-images/base-runner/install_javascript.sh
Migrate the Node.js setup to the currently recommended way and version. The previously used installation scripts are no longer maintained.
Fixes #10936
> Update Node.js setup for JavaScript projects

- projects/kyverno/Dockerfile
My fork of Kyverno contains two new fuzzers that should run for a bit on OSS-Fuzz before they are merged upstream.
This PR temporarily points Kyvernos OSS-Fuzz integration to my fork to collect runtime and performance metrics over the next few days.
> kyverno: temporarily clone fork

- infra/base-images/base-builder/compile_native_go_fuzzer
Fixes https://github.com/google/oss-fuzz/issues/10916
> Fix broken Go coverage reports

- projects/lua/Dockerfile
- projects/lua/build.sh
Commit 0736b5b08f61be9ff9f62f885912f934c7df5aed ("[Lua]initial integration. (#4653)") introduces a test that used a Lua library built from source code. Tests [1] added later builds its own Lua library and as a result we have two directories with the same source code and code coverage report (and probably Fuzz Introspector) accounts overall code coverage separately.
The patch switches fuzz_lua test to using Lua library build by additional tests [1].
1. https://github.com/ligurio/lua-c-api-tests
2. https://storage.googleapis.com/oss-fuzz-coverage/lua/reports/20230911/linux/src/testdir/build/lua-master/source/report.html
3. https://storage.googleapis.com/oss-fuzz-coverage/lua/reports/20230911/linux/src/lua/report.html
> lua: use common Lua library by tests

- infra/pr_helper.py
PR helper fails when author information is null. Adding a check before get login name.
https://github.com/google/oss-fuzz/issues/10955
> fix PR helper when commits have no author.

- infra/build/functions/project_experiment.py
Mitigates the known issue where we don't automatically change to the `WORKDIR` defined in `Dockerfile` when running cloud experiments.
Question:
Would it be preferred if I introduce a flag for this?
(e.g., `--use_workdir` or `--workdir=/src/<project>`)
While this gives more flexibility, I feel `cd` to `WORKDIR` should always be preferred if we want the cloud experiments to behave the same as local ones.
> Change to `WORKDIR` before running commands in cloud project experiments.

- infra/base-images/base-builder/jcc/jcc.go
We only need to make sure that if the wrapped compiler (clang) prints something to stderr, we report that to stderr in the wrapper, __even if__ the compiler exits with 0. This is because when starting up, Bazel invokes the compiler with various flags to detect what features are available and what flags to pass during regular compilation. The detection is based on the stderr of the compiler invocation, so we need to make sure we are properly printing out stderr. Finally, Bazel uses stderr to determine if the compiler is clang / gcc or a third option. If we don't report stderr, then Bazel considers we are using a generic compiler and then gets confused about what to generate in the toolchain.
Currently, this is the diff from the toolchain autoconfig when Bazel starts up:
```diff
--- …
```
> Fix bazel invocations with jcc

- projects/burntsushi-toml/fuzz.go
Removing input limit as this target have not found anything notable yet, mostly because of large cap.
> burntsushi-toml: remove input limit

- projects/apache-poi/src/main/java/org/apache/poi/POIHWPFFuzzer.java
- projects/apache-poi/src/main/java/org/apache/poi/POIVisioFuzzer.java
- projects/apache-poi/src/main/java/org/apache/poi/POIXSSFFuzzer.java
Ignore one more case where java.awt is missing native libs and other expected exceptions
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=62275 https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=62333 https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=62354
> apache-poi: Some more expected exceptions

- projects/powerdns/build.sh
96b8b80172c6bc333919cac4422f88e4ac1b9eb8 did not properly fix the issue because on older branches, where dnsdist does not have its own fuzzing targets, we do not properly go back to the checkout directory and thus the next step fails.
> powerdns: Go back to the correct working directory on old branches

- projects/fastify/Dockerfile
- projects/fastify/build.sh
- projects/fastify/project.yaml
Fastify is a javascript web framework and it's a foundation project from [OpenJS](https://openjsf.org/). It's used by a lot of [organisations](https://fastify.dev/organisations/) (50+ listed on its website), including:
- Microsoft
-  [Net-a-porter](https://www.net-a-porter.com/en-gb/) (fyi, this is a large UK e-commerce website with 1.8 billion in revenue)
- [Amerisave](https://www.amerisave.com/)
Maintainers are happy to integrate this and is listed as primary contact.
> fastify: initial integration

- projects/apache-poi/Dockerfile
- projects/apache-poi/build.sh
- projects/apache-poi/src/main/java/org/apache/poi/POIFuzzer.java
- projects/apache-poi/src/main/java/org/apache/poi/POIHSSFFuzzer.java
- projects/apache-poi/src/main/java/org/apache/poi/POIXSSFFuzzer.java
- projects/apache-poi/src/main/java/org/apache/poi/XLSX2CSVFuzzer.java
These changes add some additional .so files to the container so that loading some classes from java.awt works.
See #10933 and #7380 for related discussions.
Also decrease "Xmx" as it seems we get native OOM in Jazzer-runs otherwise.
> Apache POI: install libraries for awt and adjust xmx

- projects/proton-bridge/Dockerfile
- projects/proton-bridge/build.sh
- projects/proton-bridge/project.yaml
[proton-bridge](https://github.com/ProtonMail/proton-bridge) use by [protonMail](https://proton.me/mail) e-mail clients.
@LBeernaertProton Ping, Dose this look good?
> [proton-bridge] initial integration

- projects/hdf5/build.sh
Test files used for seed corpus are moved to a new folder
> hdf5: fix build

- projects/lua/build.sh
> lua: introduce fuzz introspector config

- projects/suricata/Dockerfile
- projects/suricata/build.sh
One random build out of 10 adds a LLVM Custom Mutator to find quadratic complexities
> suricata: adds quadfuzz

- projects/unbound/build.sh
- projects/unbound/fuzz_1.c
- projects/unbound/fuzz_4.c
- projects/unbound/project.yaml
Fixes: https://github.com/google/oss-fuzz/issues/11056
> unbound: fix build

- infra/cifuzz/filestore/gitlab/__init__.py
When using ClusterFuzzLite with GitLab filestore, using a cache, and doing a prune, the previous corpus items do not get removed when the new corpus gets uploaded.
cc @jonathanmetzman
> cifuzz: prune old corpus from gitlab filestore

- projects/lua/build.sh
- projects/tarantool/build.sh
Tarantool's Fuzz Introspector report is not generated at all, see [^1]
Lua's Fuzz Introspector config is missed all tests except `fuzz_lua`, see [^2].
Proposed patches fixes that.
[^1]: https://introspector.oss-fuzz.com/project-profile?project=tarantool
[^2]: https://storage.googleapis.com/oss-fuzz-introspector/lua/inspector-report/20230930/fuzz_report.html
Follows up https://github.com/google/oss-fuzz/pull/11040
Follows up https://github.com/google/oss-fuzz/pull/11041
> Fix fuzz introspector config

- projects/memcached/Dockerfile
- projects/memcached/build.sh
- projects/memcached/fuzzer_proxy.c
- projects/memcached/fuzzer_proxy.options
- projects/memcached/generate_corpus.py
- projects/memcached/patch.diff
Initial memcached integration. This currently only targets the proxy with a minimal corpus, but this will change and be expanded. Tested successfully locally.
> memcached: initial fuzzer integration

- projects/roaring-bitmap/build.sh
This PR fixes a bug in the build script for copying a non-existent jar library.
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=62748
> roaring-bitmap: Fix build script

- tools/vscode-extension/package.json
- tools/vscode-extension/src/commands/cmdEndToEndCoverage.ts
- tools/vscode-extension/src/coverageHelper.ts
- tools/vscode-extension/src/extension.ts
- tools/vscode-extension/src/utils.ts
Extends the command that runs a full build-fuzzers; run-fuzzers; collect code coverage; to also now do a comparison of the local code coverage to the code coverage by Clusterfuzz. Any gains are highlighted.
> vscode: add comparison of local vs remote coverage

- projects/mp4san/build.sh
The `webpsan` crate in this project is planned to be used by Signal Messenger to address CVE-2023-4863.
I tested this change via:
```
$ python infra/helper.py pull_images
$ python infra/helper.py build_image mp4san
$ python infra/helper.py build_fuzzers --sanitizer address --engine libfuzzer --architecture x86_64 mp4san
$ python infra/helper.py check_build   --sanitizer address --engine libfuzzer --architecture x86_64 mp4san mp4san-sanitize
$ python infra/helper.py check_build   --sanitizer address --engine libfuzzer --architecture x86_64 mp4san webpsan-sanitize
```
> mp4san: fuzz all project crates

- infra/base-images/base-builder/jcc/jcc.go
Some projects (e.g., `mosh`) do not report the root build error sent to `stderr`.
Saving the errors to a file so that we won't miss any and can always access them later.
Reproduce:
```bash
PROJECT=mosh; \
echo -e "\nENV CC=/usr/local/bin/clang-jcc\nENV CXX=/usr/local/bin/clang++-jcc\nENV FUZZING_LANGUAGE=c++\nENV JCC_GENERATE_AST_DIR=/workspace/out/$PROJECT" >> "projects/$PROJECT/Dockerfile"; \
python infra/helper.py build_image "$PROJECT" --pull && \
docker run -ti gcr.io/oss-fuzz/$PROJECT /bin/bash
```
```bash
wget https://storage.googleapis.com/clusterfuzz-builds/jcc/clang-jcc -O /usr/local/bin/clang-jcc && wget https://storage.googleapis.com/clusterfuzz-builds/jcc/clang++-jcc -O /usr/local/bin/clang++-jcc && compile
```
With this change, we can see errors like:
```
conftest.cpp:12:10: …
```
> JCC writes build errors to a file for reliable future access.

- projects/libzip/project.yaml
It does not support using other libraries (openssl, zlib) correctly
> libzip: disable memory sanitizer

- projects/skia/Dockerfile
This breaks local builds on ARM Macs and appears to be redundant with zlib1g-dev.
> Remove unnecessary lib32z1-dev install.

- projects/xmldom/build.sh
Fixes: https://github.com/google/oss-fuzz/pull/11036#issuecomment-1759249910
CC @karfau 
To test this from outside the containers:
```
python3 infra/helper.py build_fuzzers xmldom
python3 infra/helper.py run_fuzzer xmldom dom-parser.xml.target
python3 infra/helper.py run_fuzzer xmldom dom-parser.html.target
```
> xmldom: fix build by copying corpus to OUT

- projects/apache-poi/build.sh
- projects/apache-poi/src/main/java/org/apache/poi/POIVisioFuzzer.java
After removing some other "roadblocks" by providing some additional .so-files, fuzzing now hits some code which is missing installed fonts. 
Apache POI already provides a system property to handle this gracefully where possible. 
So let's add this property.
We can also remove one leftover exception handling which should not appear now.
> apache-poi: Allow missing fonts

- projects/cloud-custodian/Dockerfile
- projects/cloud-custodian/build.sh
- projects/cloud-custodian/fuzz_query_parser.py
- projects/cloud-custodian/fuzz_resources_parser.py
- projects/cloud-custodian/fuzz_resources_validate.py
- projects/cloud-custodian/project.yaml
Initial integration of Cloud Custodian, a rules engine for cloud platforms such as Google Cloud, AWS, Azure and Kubernetes. Users write YAML-based policies to query, filter and take actions on cloud resources. It is used in production by companies such as:
1. HBO Max
2. JP Morgan
3. Capital One
4. Siemens
5. Zapier
And [others](https://github.com/cloud-custodian/cloud-custodian/blob/main/ADOPTERS.md).
Cloud Custodian is a Cloud Native Computing Foundation project.
> cloud-custodian: initial integration

- projects/kyverno/Dockerfile
We temporarily used a fork for Kyverno while testing out some new fuzzers. These fuzzers are now merged upstream, so reverting the repo to clone as well.
> Kyverno: Clone upstream repo

- projects/re2/project.yaml
Currently, https://deps.dev/project/github/google%2Fre2 indicates that RE2 isn't fuzzed. I'm guessing that this configuration is the reason for that.
> Update `homepage` and `main_repo` for RE2.

- projects/fluent-bit/Dockerfile
This is to use the latest dependencies where patches are made to avoid having to wait for Fluent-bit's master branch to update.
> fluent-bit: update lib deps

- projects/cras/project.yaml
The coverage builder complains that rust stdlib sources is missing.
```
Step #5: [0;31merror: /workspace/out/libfuzzer-coverage-x86_64/rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/panic.rs: No such file or directory
Step #5: [0m[0;31mwarning: The file '/rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/panic.rs' isn't covered.
Step #5: [0m[2023-10-04 06:50:42,764 DEBUG] Finished generating per-file code coverage summary.
Step #5: [2023-10-04 06:50:42,764 DEBUG] Generating file view html index file as: "/workspace/out/libfuzzer-coverage-x86_64/report/linux/file_view_index.html".
Step #5: Traceback (most recent call last):
Step #5:   File "/opt/code_coverage/coverage_utils.py", line 829, in <module>
Step #5:     sys.exit(Main())
Step #5:   File …
```
> cras: Declare "language: rust"

- projects/urllib3/Dockerfile
- projects/urllib3/build.sh
- projects/urllib3/fuzz_requests.py
I've been trying to use a Python `HTTPServer` on a seperate thread to drive coverage of urllib3. There are technical issues with it #10235 that mean it's not running properly.
I have created an alternative approach that uses a Python socket mocking framework `httpretty` to fuzz urllib3's request handling. I'd like to switch us over to this new approach to see if we can start fuzzing urllib3's request handling.
> Changing urllib3 fuzzing to use httpretty

- projects/libcue/project.yaml
Just noticed that the memory sanitizer is not enabled by default.
> Enable memory sanitizer for libcue

- projects/libcue/project.yaml
Wycheproof causes [build break](https://oss-fuzz-build-logs.storage.googleapis.com/log-760a7a28-01ef-4046-88fe-5003a4a99fbf.txt). Disabling it unless someone knows what is missing for it to work.
Edit: Also just learned wycheproof purpose is to fuzz cryptography, so it is irrelevant for this project.
> Disable wycheproof for libcue

- projects/memcached/build.sh
- projects/memcached/fuzzer_proxy.c
Update memcached build script to link to `memcached-proxy_ratelim` and update fuzzer API to match the newly minted 1.6.22.
> [memcached] Update fuzzer to support 1.6.22

- projects/ecc-diff-fuzzer/build.sh
so that compile error in tests do not bother fuzzing
Meant to fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=63198
> ecc-diff-fuzzer: only build botan libs

- projects/avahi/project.yaml
to make it possible to start testing patches like
https://github.com/lathiat/avahi/commit/b448c9f771bada14ae8de175695a9729f8646797 as soon as possible.
> [avahi] build the fuzz targets more often

- projects/suricata/project.yaml
Suricata's homepage was updated a while ago to https://suricata.io/
> [suricata] update project homepage

- projects/gstreamer/Dockerfile
We need at least 1.1 to build gstreamer as of this weekend.
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=63487
> gstreamer: Bump meson requirement to 1.2.3

- projects/pugixml/build.sh
This is defined as valid by clang and by IEEE-754; XPath evaluation requires a IEEE conformant floating point division operator.
> pugixml: Disable float-divide-by-zero

- projects/cups/Dockerfile
- projects/cups/build.sh
- projects/cups/fuzzer/Makefile
build fail due to newly added [dnssd.c](https://github.com/OpenPrinting/cups/blob/master/cups/dnssd.c) file.
> [cups] fix build

- projects/pillow/Dockerfile
- projects/pillow/build_depends.sh
Two changes for the pillow project.
1. Pillow previously had a separate repository for wheel building scripts - https://github.com/python-pillow/pillow-wheels
However, that has been incorporated into the main repository for simplicity - https://github.com/python-pillow/Pillow/pull/7418
So this PR updates the project here to use the new location.
2. Pillow's oss-fuzz CI job is [currently failing because pip is too old](https://github.com/python-pillow/Pillow/actions/runs/6666944851/job/18119459590#step:4:9947). So this PR updates it.
cc @hugovk
> [Pillow] pillow-wheels has been incorporated into Pillow

- projects/urllib3/fuzz_requests.py
- projects/urllib3/fuzz_urlparse.py
Recent PR #11120 was successful in improving the runtime coverage, but changed how we call urllib3 no longer creating a `PoolManager` object, This removed a lot of code from the reachability analysis (introspector seems to struggle with urllib3s package structure).
This change reads the `PoolManager` returning this reachability.
This change also changes how `parse_url` is called. There's an issue with the introspector (PyCG more specifically) not mapping `urllib3.util.parse_url` correctly, but does map `urllib3.util.url.parse_url`. When I change to `urllib3.util.url.parse_url` and run PyCG I get a full callgraph from this method.
**Before**
```
Call tree
.........fuzz_urlparse.TestOneInput / -1
atheris.FuzzedDataProvider .........fuzz_urlparse 22
fdp.ConsumeUnicode .........fuzz_urlparse …
```
> Updating how urllib3 is called to improve reachability

- projects/bitcoin-core/build.sh
This has been removed upstream: https://github.com/bitcoin/bitcoin/pull/27896.
> bitcoin-core: remove --with-seccomp

- projects/openh264/Dockerfile
- projects/openh264/build.sh
The fuzzdata repository is no longer available.
Use corpus-replicator instead (https://github.com/MozillaSecurity/corpus-replicator)
> openh264: Use corpus-replicator to create seed corpus

- projects/libldac/Dockerfile
Fuzzdata is no longer available. See https://github.com/google/oss-fuzz/issues/10610 for more context.
> libldac: Use corpus-replicator to generate seed corpus

- projects/surrealdb/project.yaml
Add the [official security contact for SurrealDB](https://surrealdb.com/.well-known/security.txt) to the `auto_ccs` recipients.
> surrealdb: update auto_ccs

- projects/openslide/project.yaml
[OpenSlide](https://openslide.org/) is a C library that provides a simple interface to read whole-slide images (also known as virtual slides) used in digital pathology.  It implements support for a [variety of file formats](https://openslide.org/#about-openslide) and is sometimes deployed in multi-user slide management systems where it is exposed to untrusted data.  OpenSlide is used by multiple image-processing frameworks, including [libvips](https://www.libvips.org/), [MONAI](https://monai.io/), [QuPath](https://qupath.github.io/), and [VTK](https://vtk.org/), and has language bindings to [C](https://github.com/j-hudecek/OpenslideCs)[#](https://github.com/yigolden/OpenSlideNET), [Java](https://github.com/openslide/openslide-java), [MATLAB](https://github.com/fordanic/openslide-matlab), …
> openslide: add project definition

- projects/opennavsurf-bag/project.yaml
The Bathymetric Attributed Grid ([BAG](https://en.wikipedia.org/wiki/Bathymetric_attributed_grid)) is an open specification and C++/Python library for representing bathymetric data as grids of the best available characterization of the true depth of the seafloor.
The [BAG specification](https://bag.readthedocs.io/en/master/fsd/index.html) has been in use for conveying and archiving bathymetry, uncertainty, and metadata by [NOAA Office of Coast Survey](https://www.ngdc.noaa.gov/mgg/bathymetry/hydro.html) for close to 20 years. The BAG format was developed and is maintained by the [Open Navigation Surface Working Group](https://www.opennavsurf.org/), a collaboration between NOAA, [UNH JHC/CCOM](https://ccom.unh.edu) as well as other interested parties. The format is used by the US Navy as …
> Add Open Navigation Surface BAG library

- projects/wt/project.yaml
The auto_cc emails can also be used to access the oss-fuzz.com dashboard. This will grant access to the current maintainer of Wt and the head of the emweb organization.
> Add additional CC emails to the Wt project

- projects/skia/Dockerfile
In https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=64153, we are seeing the syncing of DEPS fail for mysterious reasons. One hypothesis is that we are overwhelming the server or otherwise running out of quota.
Thus, we are trying shallow clones and avoiding downloading emscripten to reduce unnecessary bandwidth.
See also:
https://skia-review.googlesource.com/c/skia/+/780137
https://skia-review.googlesource.com/c/skia/+/779916
> [skia] Try downloading less data

- projects/envoy/build.sh
A recent code-change executes CEL code, and the fuzzer detect false positives.
Enabling CEL sanitization to solve the issue.
> envoy: enable sanitization of Cel code

- projects/pillow/build_depends.sh
pillow has started using [cibuildwheel](https://github.com/pypa/cibuildwheel) - https://github.com/python-pillow/Pillow/pull/7552
This moved the script for building wheel dependencies from `wheels/config.sh`, a more natural location for [multibuild](https://github.com/multi-build/multibuild), to just under GitHub Actions instead, at [.github/workflows/wheel-dependencies.sh](https://github.com/python-pillow/Pillow/blob/main/.github/workflows/wheels-dependencies.sh)
It also now includes `wheels/multibuild/library_builders.sh` [by itself](https://github.com/python-pillow/Pillow/blob/e2ddd27500cdd4c8156bc0d5fe0bfa050408c707/.github/workflows/wheels-dependencies.sh#L10), and rearranged the code to run immediately, instead of needing `pre_build` to be called separately.
cc @hugovk
> pillow: Updated script path

- projects/apache-commons-codec/LanguageStringEncoderFuzzer.java
This PR adds an additional catch for an expected IllegalArgumentException thrown from the [Soundex](https://github.com/apache/commons-codec/blob/5bbb66994f8e6d04509cbd297c6bf5dc77d328bb/src/main/java/org/apache/commons/codec/language/Soundex.java#L287) class. This fixes a false positive issue reported in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=64513.
> apache-commons-codec: Catch expected IllegalArgumentException

- projects/apache-commons-compress/ArchiverArFuzzer.java
- projects/apache-commons-compress/ArchiverArjFuzzer.java
- projects/apache-commons-compress/ArchiverCpioFuzzer.java
- projects/apache-commons-compress/ArchiverTarStreamFuzzer.java
- projects/apache-commons-compress/ArchiverZipStreamFuzzer.java
- projects/apache-commons-compress/BaseTests.java
- projects/apache-commons-compress/CompressSevenZFuzzer.java
- projects/apache-commons-compress/CompressZipFuzzer.java
- projects/apache-commons-compress/CompressorBZip2Fuzzer.java
- projects/apache-commons-compress/CompressorDeflate64Fuzzer.java
- projects/apache-commons-compress/CompressorGzipFuzzer.java
- projects/apache-commons-compress/CompressorLZ4Fuzzer.java
- projects/apache-commons-compress/CompressorSnappyFuzzer.java
- projects/apache-commons-compress/CompressorZFuzzer.java
- projects/apache-commons-compress/Dockerfile
- projects/apache-commons-compress/README.md
- projects/apache-commons-compress/build.sh
This PR expands coverage for more compression types in this library as well as trying to read all of the files in archivers. This work is being tracked on the project side here:
https://issues.apache.org/jira/browse/COMPRESS-632
> apache-commons-compress: Adding more coverage (COMPRESS-632)

- projects/apache-commons-lang/SerializationUtilsFuzzer.java
This PR removes the storing of return values to avoid ClassCastException. This PR fixes a false positive issues reported in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=64486.
> apache-commons-lang: Fix ClassCastException for wrong return type

- projects/apache-commons-lang/SerializationUtilsFuzzer.java
Some methods in [SerializationUtils](https://github.com/apache/commons-lang/blob/4fc2ab4d1474b77b63b646631b38893fbb4ff411/src/main/java/org/apache/commons/lang3/SerializationUtils.java#L200) will throw NullPointerException and it is documented in the Javadoc. Thus this PR aims to capture this known exception which is reported in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=64491.
> apache-commons-lang: Catch known NullPointerException

- projects/xz/Dockerfile
The old URL is still kept as a mirror, but it is not always up to date since the primary repository is on GitHub. This now matches the 'main_repo' entry in the corresponding project.yaml.
> xz: Change Dockerfile clone URL to match project.yaml entry.

- projects/jackson-datatypes-collections/EclipseCollectionsDeserializerFuzzer.java
- projects/jackson-datatypes-collections/GuavaDeserializerFuzzer.java
This PR catches some known exceptions which are missed before. This PR solves https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=64612, https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=64614, https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=64640 and https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=64642.
> jackson-datatypes-collections: Catch known exceptions

- projects/avahi/Dockerfile
- projects/avahi/project.yaml
It was moved: https://github.com/avahi/avahi/commit/94e1ffdfbe7a1b7036b9902bab15ea0ef8b24eb4
> [avahi] switch to the avahi organization

- projects/opencv/build.sh
OpenCV library now doesn't build QUIRC by default - it uses own QR decoder.
Build error:
```
Step #3 - "compile-afl-address-x86_64": + for fuzzer in core_fuzzer filestorage_read_file_fuzzer filestorage_read_filename_fuzzer filestorage_read_string_fuzzer generateusergallerycollage_fuzzer imdecode_fuzzer imencode_fuzzer imread_fuzzer readnetfromtensorflow_fuzzer
Step #3 - "compile-afl-address-x86_64": + /src/aflplusplus/afl-clang-fast++ -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -stdlib=libc++ /usr/lib/libFuzzingEngine.a core_fuzzer.cc -std=c++11 -I/work/install-address/include/opencv4 -L/work/install-address/lib -L/work/install-address/lib/opencv4/3rdparty -lopencv_dnn -lopencv_objdetect …
```
> opencv: fix build error - link with quirc

- projects/llvm/build.sh
The coverage build is still getting killed on the cloud server even when only 1 process is used. This commit tries to build the smaller fuzzers first in order to (1) verify at least some fuzzers can be built with coverage sanitizer; (2) see if having build some of the lighter fuzzers will make it easier to build the larger fuzzers later. A bit of a guess with respect to (2).
> llvm: reorder fuzzer builds

- projects/jackson-dataformats-binary/DeserializerFuzzer.java
This PR catches the expected IonException during deserialization process. This PR solves https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=64715.
> jackson-dataformats-binary: Catch expected IonException

- projects/opencv/Dockerfile
Trying to fix OOM issues in `imread`/`imdecode` tests.
OpenCV has mechanism for input image size limiting controlled via environment variables:
https://github.com/opencv/opencv/blob/b2593427376f75fc70eaf6b79c4d4a3082da6aad/modules/imgcodecs/src/loadsave.cpp#L67-L81
In this PR we set lower than default (`1<<30` ~ 1Gpix ~ 3072Mb) total pixel limit since runner has its own limits (2048Mb?).
**cc** @vrabaud , @opencv-alalek
> opencv: set pixel limit for imread

- projects/abseil-cpp/BUILD
- projects/abseil-cpp/Dockerfile
- projects/abseil-cpp/WORKSPACE
- projects/abseil-cpp/build.sh
In `Dockerfile`, remove cruft that probably wasn't needed before and certainly isn't needed now.
In `WORKSPACE`, take a dependency on `rules_fuzzing` and, while I'm here, update the dependency on `bazel_skylib`.
In `BUILD`, use `cc_fuzz_test()`.
In `build.sh`, replace cruft that was complex (and unmaintained) and simply use `bazel_build_fuzz_tests` instead.
> Overhaul `abseil-cpp`... and get it working again.

- projects/halide/build.sh
- projects/halide/project.yaml
A few of the builds that where originally working locally had gone out of sync for sometime and are now breaking. I've just removed these fuzzing engines/sanitizers for now.
> halide: Remove broken builds

- projects/apache-commons-lang/build.sh
This PR fixes the build.sh for apache-commons-lang to exclude the guava dependency from the jacoco coverage report.
> apache-commons-lang: Fix build.sh

- projects/llvm/Dockerfile
- projects/llvm/build.sh
- projects/llvm/coverage_patcher.py
Coverage build are struggling to build as processes are being killed. This is another attempt to fix this.
If this doesn't work in the cloud builds then I think the next step is to try and limit coverage flags for certain files.
> llvm: try getting coverage to work

- projects/jackson-dataformats-binary/DeserializerFuzzer.java
- projects/jackson-dataformats-binary/SerializerFuzzer.java
- projects/jackson-dataformats-text/DeserializerFuzzer.java
This PR fixes the fuzzer problem for https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=64729 which is deserialising an unsupported type. This PR also fixes some logic in the fuzzers to increase coverage in project jackson-dataformats-binary and jackson-dataformats-text.
> jackson-dataformats-{binary, text}: fix exception blockers for fuzzers

- projects/jackson-datatypes-collections/GuavaSerializerFuzzer.java
This PR fixes 3 false positive issues in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=64623, https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=64625 and https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=64634 which accidentally loops a very large byte array for too many times.
In `GuavaSerailizerFuzzer` case 11. The logic uses a combination of `Iterables.cycle(T...)` and `Iterables.limit(Iterable, int)` to create an iterator for the fuzzing process. But there is a bug in the creation causing OOM.
In Java, the generic type application is only possible for non-primitive type. For example, if the following code is run, the result is 2 and `elements[0] = 1` and `elements[1] = 2` inside `genericTest(T...)` because the generic type retrieves the Integer type successfully and …
> jackson-datatypes-collections: Fix OOM on Iterable creation of primitive byte array

- projects/llvm/build.sh
The most recent coverage build got close but got killed at the last fuzzer (clangd-fuzzer) [log](https://oss-fuzz-build-logs.storage.googleapis.com/log-5a5b1493-2f55-47cf-8c59-f13bd20ed59d.txt). Am disabling this fuzzer in coverage builds for now.
> llvm: fix coverage build

- projects/glib/Dockerfile
It’s now a dependency of GLib.
See https://gitlab.gnome.org/GNOME/glib/-/merge_requests/3740
> glib: Install packaging Python module

- projects/nokogiri/project.yaml
@stevecheckoway is a co-maintainer of Nokogiri and the libgumbo fork.
> nokogiri: add steve checkoway to the project

- projects/util-linux/project.yaml
By removing the explicit list of fuzzers the project falls back to the default configuration which is all fuzzers.
Especially this enables the centipede fuzzer today.
Cc @karelzak
> util-linux: use all fuzzers

- projects/nodejs/Dockerfile
- projects/nodejs/build.sh
- projects/nodejs/project.yaml
Switches the node build to my fork which contains fixes for Nodes currently broken fuzzer and 2 new fuzzers. The PRs for the fix and the new fuzzers have been made upstream. This change in repo is temporary until Nodejs merges in the changes.
> nodejs: temporarily use fork with fixes and new fuzzers

- projects/gpac/build.sh
- projects/gpac/project.yaml
Hello, 
We would like to update the build.sh for gpac to allow us to add fuzzers on our side without rewriting the script each time. 
I took inspiration from the way libssh is doing it. 
thanks
cc @jeanlf
> gpac: extend build.sh to allow for more fuzzers

- projects/apache-commons-codec/NetCodecFuzzer.java
In https://issues.apache.org/jira/browse/CODEC-314, we push a fix upstream to capture an unexpected IndexOutOfBoundException. The new logic will wrap the unexpected IndexOutOfBoundException and throw an IllegalArgumentException instead. This PR fixes the original fuzzer to capture the new IllegalArgumentException to meet the new logic. This PR should close https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=64362.
> apache-commons-codec: Catch new IllegalArgumentException

- projects/jackson-dataformats-text/DeserializerFuzzer.java
This PR wraps known IllegalStateException which fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=65028.
> jackson-dataformats-text: Wrap known IllegalStateException

- projects/jackson-dataformats-binary/AvroParserFuzzer.java
- projects/jackson-dataformats-binary/CborParserFuzzer.java
- projects/jackson-dataformats-binary/IonParserFuzzer.java
- projects/jackson-dataformats-binary/ProtobufParserFuzzer.java
- projects/jackson-dataformats-binary/SmileParserFuzzer.java
This PR adds looping for calling methods of different parsers in the jackson-dataformats-binary project to simulate multiple method calling for the same initialized parser.
> jackson-dataformats-binary: Add loops to parser method calling

- tools/vscode-extension/package-lock.json
- tools/vscode-extension/package.json
- tools/vscode-extension/src/commands/cmdBuildFuzzerFromWorkspaceCFLite.ts
- tools/vscode-extension/src/commands/cmdDispatcherGenerateClusterfuzzLite.ts
- tools/vscode-extension/src/commands/cmdTestFuzzerCFLite.ts
- tools/vscode-extension/src/extension.ts
- tools/vscode-extension/src/ossfuzzWrappers.ts
- tools/vscode-extension/src/projectIntegrationHelper.ts
Adds helpers to:
- Generate files needed for a CFLite set up (the content of `.clusterfuzzlite`, not the GH workflow)
- Test fuzzers in a CFLite set up
Only CPP support for now.
Follow-up PRs will:
- Add support for the rest of the languages
- Add support for code coverage generation
- Add support for yaml generation.
> vscode: add CFLite helper for C++

- projects/nodejs/build.sh
Nodejs's coverage build exhausts memory. Have tried building this on a 96GB RAM machine which also ran out of memory. Attempted to build with a single core which seems to have done the job. It takes a lot longer, but at least it completes. The coverage build consumes a lot of disk space as well, so this PR may not fix it entirely.
Doing this experimentally to see if it works out in the cloud infrastructure.
> nodejs: Attempt to fix broken coverage build

- tools/vscode-extension/package.json
- tools/vscode-extension/src/projectIntegrationHelper.ts
- prefixes CFLite generate command
- Removes licenses from Dockerfile/Build in CFLite mode -- the rational is that users will likely not want to use those license in their own code base, and they are not needed as the code won't be put in OSS-Fuzz's repo.
- Removes unused fields from `project.yaml` -- these are not relevant in CFLite
> vscode: refine various places

- projects/dropbear/build.sh
Dropbear now distributes a pre-built configure script in the repo (built with autoconf 2.71).  An intermittent failure seems to occur only using the older autoconf in Ubuntu 20.04 from oss-fuzz, it sometimes doesn't find src/install-sh which is in AC_CONFIG_AUX_DIR
Previously install-sh was in the top directory, changed in https://github.com/mkj/dropbear/commit/e49f2012adb3e062b0c2fb57ca575ceedb2eae58
```
/src/dropbear/configure --enable-fuzz --disable-harden --disable-zlib 
...
checking for _FILE_OFFSET_BITS value needed for large files... no 
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."
```
Intermittent cifuzz:
Failure https://github.com/mkj/dropbear/actions/runs/7237504504/job/19717245388
Successful retry …
> dropbear: Don't run autoconf

- projects/libressl/Dockerfile
- projects/libressl/project.yaml
LibreSSL has moved from https://github.com/libressl-portable/ to https://github.com/libressl/
This pull request updates repository URLs accordingly.
> libressl: use new github org

- projects/jackson-dataformats-binary/AvroParserFuzzer.java
- projects/jackson-dataformats-binary/CborParserFuzzer.java
- projects/jackson-dataformats-binary/IonParserFuzzer.java
- projects/jackson-dataformats-binary/ProtobufParserFuzzer.java
- projects/jackson-dataformats-binary/SmileParserFuzzer.java
In Java, modulo operations are done with absolute value first, then the negative sign will be added to the modulo result if either of the left or right operands is negative. Thus if the choice is negative, the modulo result will always be negative and it automatically goes to the default branch for all the fuzzers. This makes the choice very unbalance and there are less than half chances to execute the other 18 branches. This PR fixes the bias problem by taking the absolute value of the integer choice before the modulo operation to ensure the result must be 0~18 inclusively.
> jackson-dataformats-binary: Fix looping condition

- projects/apache-commons-lang/ClassFuzzerBase.java
This PR fixes the class list size for the `ClassFuzzerBase` which is used for both `AnnotationUtilsFuzzer` and `RelfectUtilsFuzzer` to possibly solve a class list loading problem.
> apache-commons-lang: Fix class list size

- projects/fastify/Dockerfile
This PR fixes the Dockerfile for project fastify by switching the default nodejs version to 19.2 to avoid a strange failing of npm build in Docker as mentioned in https://github.com/nodejs/docker-node/issues/1912.
> Fastify: fix dockerfile to downgrade nodejs to version 19.2

- projects/icu/project.yaml
nrunge is no longer working for google since Jan 2023. That email is no longer valid.
Replace with ftang@google.com
> Remove  nrunge@google.com from icu/project.yaml

- projects/opensc/project.yaml
While discussing adding new people to the project, in OpenSC/OpenSC#2966 I would like to send the first change, adding Peter to the CC for the oss-fuzz reports.
> opensc: Add Peter to the CC

- projects/django/Dockerfile
- projects/django/build.sh
This seems to be required otherwise the coverage helper scripts will use python 3.8 leading to syntax errors.
> [Django] Force python3 to point to python3.10.

- projects/libevent/buffer_add_file_fuzzer.cc
- projects/libevent/bufferevent_fuzzer.cc
- projects/libevent/dns_config_fuzzer.cc
Hi! This pull request extends the previous pull request https://github.com/google/oss-fuzz/pull/11257 and brings some improvements.
> libevent: Fuzzing Coverage Expansion #2

- tools/vscode-extension/src/projectIntegrationHelper.ts
Currently `CFLAGS` was used, whereas we need to use `CXXFLAGS`.
> vscode: project gen: adjust CXXFLAGS for cpp builds

- projects/jackson-dataformats-binary/AvroGeneratorFuzzer.java
- projects/jackson-dataformats-binary/AvroParserFuzzer.java
- projects/jackson-dataformats-binary/CborGeneratorFuzzer.java
- projects/jackson-dataformats-binary/CborParserFuzzer.java
- projects/jackson-dataformats-binary/IonGeneratorFuzzer.java
- projects/jackson-dataformats-binary/ProtobufParserFuzzer.java
- projects/jackson-dataformats-binary/SmileGeneratorFuzzer.java
This PR fixes multiple fuzzers in project jackson-dataformats-binary. The fixes majorly focus on some exception blockers of fuzzers due to insufficient initialisation of the objects.
> jackson-dataformats-binary: fix fuzzer blockage

- projects/wasmtime/project.yaml
I believe that Rainy is no longer looking to get cc'd on these issues.
> Remove a cc for fuzz bugs for Wasmtime

- projects/icu/build.sh
ICU4C nowadays requires C11 & C++17 so it'd be better if the oss-fuzz configuration didn't hardcode the standard versions required.
> Get -std=... from runConfigureICU instead of hardcoding it

- projects/tendermint/Dockerfile
- projects/tendermint/project.yaml
We maintain security for cometbft which forked off from tendermint and cometbft is maintained by the teams that use the cosmos-sdk and that powers the Cosmos/Interchain ecosystem.
> Update from tendermint to new cosmos-sdk dependency cometbft

- projects/libheif/Dockerfile
The x265 project has changed their repository location, the old one is not accessible anymore.
Source: https://www.videolan.org/developers/x265.html
https://github.com/strukturag/libheif/pull/1099#issuecomment-1884035385
> libheif: repository of x265 dependency changed

- infra/base-images/base-builder/compile
Fixes: https://github.com/google/oss-fuzz/issues/11466
> infra: base-builder: fix introspector builds

- projects/fasthttp/build.sh
See: https://github.com/valyala/fasthttp/pull/1687
> fasthttp: update fuzz targets

- projects/bitcoin-core/build.sh
This is going to be removed upstream: https://github.com/bitcoin/bitcoin/pull/29185.
Skip `CFLAGS` for now. It looks like previously this was not getting properly applied, but would now run into a (fixed in later versions) LLVM bug.
Set `NM` & `STRIP` to `llvm-*` so we are consistently using LLVM tools.
> bitcoin: remove `--enable-lto` usage
