google/oss-fuzz

projects/skia/build.sh
Result of http://review.skia.org/649523
=> [skia] Use non-deprecated GN flag

projects/python-ecdsa/fuzz_keys.py
This change:
- fixes incorrect data type from string to byte in the `target4` function.
- adds `SigningKey` fuzz targets to `fuzz_keys.py`.
=> python-ecdsa: improves code coverage of fuzz_keys

projects/urllib3/project.yaml
cc @DavidKorczynski @sg3-141-592
=> Add sean@compactcloud.co.uk to urllib3 project.yaml

projects/toolz/fuzz_itertoolz.py
This change improves code coverage by adding fuzz tests for:
- functoolz
- dicttoolz
- sandbox
=> toolz: adds fuzz tests for more functions

projects/rnp/Dockerfile
=> Support git submodules in rnp source tree

projects/tarantool/project.yaml
=> tarantool: update auto-ccs

projects/gwt/.gitignore, projects/gwt/Dockerfile, projects/gwt/build.sh, projects/gwt/pom.xml, projects/gwt/project-parent/fuzz-targets/pom.xml, projects/gwt/project-parent/fuzz-targets/src/test/java/com/example/JsParserFuzzer.java, projects/gwt/project-parent/fuzz-targets/src/test/java/com/example/JsonFuzzer.java, projects/gwt/project-parent/pom.xml, projects/gwt/project.yaml
Initial integration of Google Web Toolkit into OSS-Fuzz
=> gwt: Initial integration

projects/tarantool/project.yaml
Seems Google workspace emails doesn't work.
=> tarantool: update cc's

projects/closure-compiler/.gitignore, projects/closure-compiler/Dockerfile, projects/closure-compiler/build.sh, projects/closure-compiler/project-parent/fuzz-targets/pom.xml, projects/closure-compiler/project-parent/fuzz-targets/src/test/java/com/example/ParserFuzzer.java, projects/closure-compiler/project-parent/pom.xml, projects/closure-compiler/project.yaml
Initial integration of closure compiler into OSS-Fuzz.
=> closure-compiler: Initial integration

projects/apache-commons-fileupload/build.sh, projects/apache-commons-text/build.sh, projects/apache-cxf/build.sh, projects/g-http-java-client/build.sh, projects/gwt/build.sh, projects/itext7/build.sh, projects/jboss-logging/build.sh, projects/jetty/build.sh, projects/json-simple/build.sh, projects/mvel/build.sh, projects/opencensus-java/build.sh
This fix aims to solve multiple build issues in ClusterFuzz related to absolute path invocation of java dependencies.
=> fix multiple java build issues in ClusterFuzz

projects/trust-dns/build.sh
This PR along with https://github.com/bluejekyll/trust-dns/pull/1911 attempts to fix: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=57350
=> trust-dns: fix build

projects/cloud-hypervisor/project.yaml
Update the auto_css list with valid emails of Cloud Hypervisor maintainers.
=> [cloud-hypervisor] Update auto_css list

projects/closure-compiler/build.sh, projects/closure-compiler/project-parent/fuzz-targets/pom.xml, projects/closure-compiler/project.yaml, projects/g-http-java-client/build.sh, projects/g-http-java-client/project-parent/fuzz-targets/pom.xml, projects/opencensus-java/project-parent/fuzz-targets/pom.xml, projects/opencensus-java/project.yaml
Fix issues in g-http-java-client, closure-compiler and opencensus-java.
=> Fix multiple build failures for different projects

projects/cloud-hypervisor/project.yaml
Add two engineers from Microsoft's security response team.
=> [cloud-hypervisor] update CC list

projects/cryptofuzz/Dockerfile, projects/cryptofuzz/build.sh
Unfortunately it's not working.
https://github.com/google/oss-fuzz/issues/9255
=> [cryptofuzz] Remove Java

infra/helper.py
Fixes https://github.com/google/oss-fuzz/issues/10043
=> [helper] Hide fuzzbench arguments

projects/pygments/build.sh
Example files are now in folders
=> Fix pygment's corpus creation

projects/unit/fuzzer/Makefile
Fix : https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=57574#c1
=> [unit] Issue 57574 build failure

projects/pytables/build.sh
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=57762
=> pytables: fix build

projects/opencsv/.gitignore, projects/opencsv/Dockerfile, projects/opencsv/build.sh, projects/opencsv/project-parent/fuzz-targets/pom.xml, projects/opencsv/project-parent/fuzz-targets/src/test/java/com/example/CSVReaderFuzzer.java, projects/opencsv/project-parent/pom.xml, projects/opencsv/project.yaml
Initial integration of opencsv into OSS-Fuzz.
=> opencsv: Initial integration

projects/connectedhomeip/Dockerfile, projects/connectedhomeip/build.sh, projects/connectedhomeip/project.yaml
This PR is to bring existing fuzzers in the connectedhomeip project to OSS-Fuzz.
CC: @gmarcosb, @andy31415
=> connectedhomeip: initial integration

projects/skia-ftz/Dockerfile
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=55584
=> skia-ftz: fix build

projects/nats/project.yaml
Hi! Adding more members to the list to be able to investigate NATS issues.
=> Update NATS maintainers

projects/go-toml/Dockerfile, projects/go-toml/build.sh, projects/go-toml/fuzz.go
- Removes unneeded dependency
- Adds round trip similar to native fuzz
cc @pelletier
=> go-toml: add roundtrip

projects/bitcoin-core/Dockerfile, projects/bitcoin-core/build.sh
Previous attemp in https://github.com/google/oss-fuzz/pull/8384, however I can't see the logs there, for what the issues were, and we've had some build simplifications since then. Retry and see what fails.
=> bitcoin-core: enable LTO (take 2)

projects/faad2/Dockerfile, projects/faad2/build.sh, projects/faad2/project.yaml
This supersedes https://github.com/google/oss-fuzz/pull/6046
Fuzzers merged upstream: https://github.com/knik0/faad2/pull/73
FYI @eustas
=> faad2: initial integration

projects/java-jwt/.gitignore, projects/java-jwt/Dockerfile, projects/java-jwt/build.sh, projects/java-jwt/project-parent/fuzz-targets/pom.xml, projects/java-jwt/project-parent/fuzz-targets/src/test/java/com/example/JWTFuzzer.java, projects/java-jwt/project-parent/pom.xml, projects/java-jwt/project.yaml
Initial integration of Java JSON Web Tokens into OSS-Fuzz.
=> java-jwt: Initial integration

projects/bitcoin-core/Dockerfile, projects/bitcoin-core/build.sh
Maintain using ThinLTO.
Follow up to #10123.
=> bitcoin-core: return to using bitcoin/bitcoin

projects/mutagen/fuzz_parser.py
A file modifier and saved by mutagen should be openable by mutagen.
=> Add a roundtrip to mutagen's fuzzer

projects/jupyter_server/build.sh
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=58197
=> jupter_server: fix build

projects/pdfbox/.gitignore, projects/pdfbox/Dockerfile, projects/pdfbox/build.sh, projects/pdfbox/project-parent/fuzz-targets/pom.xml, projects/pdfbox/project-parent/fuzz-targets/src/test/java/com/example/PDFStreamParserFuzzer.java, projects/pdfbox/project-parent/fuzz-targets/src/test/java/com/example/PDFWriteReadFuzzer.java, projects/pdfbox/project-parent/pom.xml, projects/pdfbox/project.yaml
Integrating pdfbox into OSS-Fuzz.
=> pdfbox: Initial integration

projects/jsqlparser/.gitignore, projects/jsqlparser/Dockerfile, projects/jsqlparser/build.sh, projects/jsqlparser/project-parent/fuzz-targets/pom.xml, projects/jsqlparser/project-parent/fuzz-targets/src/test/java/com/example/JSqlParserFuzzer.java, projects/jsqlparser/project-parent/pom.xml, projects/jsqlparser/project.yaml
Initial integration of JSqlParser into OSS-Fuzz
=> JSqlParser: Initial integration

projects/python-tabulate/fuzz_tabulate.py
This PR:
- Adds helper functions to allow different inputs in to passed into `tabulate`.
- Fuzzes `simple_separated_format`
=> python-tabulate: improves coverage of fuzzer

projects/libjxl/Dockerfile, projects/libjxl/build.sh
This will add fuzzing for jpegli decoder.
Needed for https://github.com/libjxl/libjxl/pull/2427
=> Update libjxl build.sh and Dockerfile.

projects/yamlbeans/.gitignore, projects/yamlbeans/Dockerfile, projects/yamlbeans/build.sh, projects/yamlbeans/project-parent/fuzz-targets/pom.xml, projects/yamlbeans/project-parent/fuzz-targets/src/test/java/com/example/YamlReaderFuzzer.java, projects/yamlbeans/project-parent/fuzz-targets/src/test/java/com/example/YamlWriterFuzzer.java, projects/yamlbeans/project-parent/pom.xml, projects/yamlbeans/project.yaml
Integrating yamlbeans into OSS-Fuzz
=> yamlbeans: Initial integration

projects/gluon/Dockerfile, projects/gluon/build.sh, projects/gluon/project.yaml
[Gluon](https://github.com/ProtonMail/gluon) is used by [ProtonMail](https://proton.me/mail).
PR for fuzzing harness: https://github.com/ProtonMail/gluon/pull/341
=> [gluon] initial integration

infra/base-images/base-clang/Dockerfile
Includes various bug fixes and refinements in python analysis and code coverage logic.
=> infra: update fuzz introspector

infra/run_fuzzers.Dockerfile
=> [cifuzz] remove test code.

projects/cryptofuzz/project.yaml
Remove some people from the Cryptofuzz CC list as discussed here: https://github.com/openssl/openssl/issues/20821#issuecomment-1525064394
=> [cryptofuzz] Remove some OpenSSL CCs

projects/openssl/project.yaml
Related: https://github.com/openssl/openssl/issues/20821#issuecomment-1525064394
=> Change Matt's email.

.github/CODEOWNERS
This CODEOWNERS file doesn't do anything when the owners are not project maintainers.
=> Remove useless file

projects/myanmar-tools/build.sh
See https://github.com/google/oss-fuzz/issues/2947
=> Statically link libunwind in myanmar-tools

projects/unbound/Dockerfile, projects/unbound/build.sh
Fixes: https://github.com/google/oss-fuzz/issues/10199
=> unbound: fix build

projects/zt-zip/.gitignore, projects/zt-zip/Dockerfile, projects/zt-zip/build.sh, projects/zt-zip/project-parent/fuzz-targets/pom.xml, projects/zt-zip/project-parent/fuzz-targets/src/test/java/com/example/UnpackFuzzer.java, projects/zt-zip/project-parent/pom.xml, projects/zt-zip/project.yaml
Integrating zt-zip into OSS-Fuzz.
=> zt-zip: Initial integration

projects/arrow-py/project.yaml
Hi there,
I'm one of the maintainers of [arrow-py](https://github.com/arrow-py/arrow) and would like to add myself as a primary contact.
Thanks to @DavidKorczynski for the initial lift off and getting arrow fuzzy tested!
=> Add primary contact for arrow-py

docs/getting-started/continuous_integration.md, infra/cifuzz/affected_fuzz_targets_test.py, infra/cifuzz/fuzz_target.py, infra/cifuzz/run_fuzzers.py, infra/cifuzz/sarif_utils.py, infra/cifuzz/sarif_utils_test.py
Improve docs, fix bugs, add tests.
=> Improve sarif

projects/librdkafka/build.sh
- use cmake
- only build static libraries
- enbles fuzz introspector
=> librdkafka: refine build

projects/python3-libraries/project.yaml
Add Python team member per their request: https://github.com/python/cpython/issues/104016#issuecomment-1531925253
=> [python3-libraries] Add Python team member

infra/base-images/base-runner/python_coverage_runner_help.py
- Fix up so the dictionary follows the right structure using a list rather than a dictionary.
- Adds some of the statics corresponding to the stats given by summary.json for C/C++ targets, namely the line coverage stats.
- Sets some stat fields to 0 to have the same keys as C/C++ targets, but where we don't have the data for Python projects.
Fixes: https://github.com/google/clusterfuzz/issues/2971
=> base-runner: refine python's summary.json

projects/wuffs/Dockerfile
Actually using this corpus will be separate (other repo) commit to
https://github.com/google/wuffs/blob/main/fuzz/c/std/seed_corpora.txt
=> [wuffs] add libjpeg_turbo_corpus

projects/kimageformats/build.sh
It should fix problem reported in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=58614
=> kimageformats: fix build

projects/ua-parser-js/Dockerfile, projects/ua-parser-js/build.sh, projects/ua-parser-js/project.yaml
UAParser.js is a popular open-source project based on JavaScript and is considered as a critical project based on OSSF list.
Project link: https://github.com/faisalman/ua-parser-js
=> ua-parser-js: initial integration

projects/bs4/Dockerfile, projects/bs4/bs4_fuzzer.py
- Don't install 2to3 anymore
- Fuzz the css selector as well
=> Improve a bit the bs4 fuzzer

projects/tint/project.yaml
This CL updates the list of members in the CC for the Tint project to match the current team members.
=> Update the tint CCs.

projects/dapr/Dockerfile
Clones another dapr repo in the Dockerfile.
=> dapr: clone repo in Dockerfile

projects/tensorflow/build.sh
Ref: https://github.com/google/oss-fuzz/issues/9792
=> tensorflow: avoid shallow fuzzers to reduce disk size

projects/ntopng/Dockerfile, projects/ntopng/build.sh, projects/ntopng/project.yaml
This a new project proposal to start fuzzing ntopng.
The project it is still in early stage but in the near future we plan to enable other sanitizers and fuzzing engines
cc @lucaderi
=> Add ntopng project

projects/solidity/Dockerfile
"Fixes" solidity build until #10237 is resolved
=> Use hard-coded LPM commit that does not fail solidity build.

projects/bs4/bs4_fuzzer.py
As suggested in https://github.com/google/oss-fuzz/pull/10303#issuecomment-1545625074 by @leonardr
=> Handle soupsieve exceptions

projects/go-toml/project.yaml
Enabling file_github_issue to making it easier for project maintainers to track issues.
cc @pelletier
=> go-toml: file github issues

projects/ipfs/project.yaml, projects/lotus/project.yaml
Adding myself as a new user to the Protocol Labs projects, since I'm planning to look into our oss-fuzz pipelines a bit more in details. (As well as why our Lotus builds fail at the moment.)
=> Add new user to lotus and ipfs

projects/bs4/bs4_fuzzer.py
See https://github.com/google/oss-fuzz/pull/10316#issuecomment-1546746264
=> Accept yet another exception for bs4 fuzzer

projects/async-http-client/.gitignore, projects/async-http-client/Dockerfile, projects/async-http-client/build.sh, projects/async-http-client/project-parent/fuzz-targets/pom.xml, projects/async-http-client/project-parent/fuzz-targets/src/test/java/com/example/AsyncHttpClientFuzzer.java, projects/async-http-client/project-parent/pom.xml, projects/async-http-client/project.yaml
Integrating async-http-client into OSS-Fuzz.
=> async-http-client: Initial integration

projects/open5gs/Dockerfile, projects/open5gs/build.sh
error: https://oss-fuzz-build-logs.storage.googleapis.com/index.html#open5gs
=> [open5gs] remove multiple use of  WORKDIR and using pushd and popd.

projects/apache-commons-imaging/project.yaml
=> Add garydgregory to project.yaml

projects/tablesaw/.gitignore, projects/tablesaw/Dockerfile, projects/tablesaw/build.sh, projects/tablesaw/project-parent/fuzz-targets/pom.xml, projects/tablesaw/project-parent/fuzz-targets/src/test/java/com/example/ReaderFuzzer.java, projects/tablesaw/project-parent/pom.xml, projects/tablesaw/project.yaml
Integrating tablesaw into OSS-Fuzz.
=> tablesaw: Initial integration

projects/apache-commons-imaging/project.yaml
Fixes: https://github.com/google/oss-fuzz/issues/10339
=> Add Gary's google account

projects/skia/build.sh
Follow-up to https://skia-review.googlesource.com/c/skia/+/699788
=> [skia] Split fuzzer into cubic and quad target

projects/bitcoin-core/build.sh
take 3, along with a revival of a previous hack to run LTO only once
=>  bitcoin-core: enable LTO (take 3) 

projects/apache-commons-imaging/ImagingBmpFuzzer.java, projects/apache-commons-imaging/ImagingGifFuzzer.java, projects/apache-commons-imaging/ImagingJpegFuzzer.java, projects/apache-commons-imaging/ImagingPngFuzzer.java, projects/apache-commons-imaging/ImagingTiffFuzzer.java, projects/apache-commons-imaging/build.sh
Also silences the highly verbose Maven download progress output.
=> [apache-commons-imaging] Fix build

infra/base-images/base-builder/install_go.sh
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=59153 : ecc-diff-fuzzer: Fuzzing build failure
And https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=59157 cel-go: Coverage build failure
Fixes https://github.com/google/oss-fuzz/pull/10314 cc @Alan32Liu
=> Golang signal handler builds fixes

projects/ion-java/.gitignore, projects/ion-java/Dockerfile, projects/ion-java/build.sh, projects/ion-java/project-parent/fuzz-targets/pom.xml, projects/ion-java/project-parent/fuzz-targets/src/test/java/com/example/IonReaderFuzzer.java, projects/ion-java/project-parent/fuzz-targets/src/test/java/com/example/IonWriterFuzzer.java, projects/ion-java/project-parent/pom.xml, projects/ion-java/project.yaml
Integrating ion-java to OSS-Fuzz.
=> ion-java: Initial integration

projects/bitcoin-core/Dockerfile
No idea, but this hopefully fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=59309
=> bitcoin-core: Try to work around out-of-space error

projects/ntopng/build.sh
Copy the `.options` file to be able to specify some options to the fuzzer (as mentioned here https://github.com/google/oss-fuzz/issues/10323#issuecomment-1560074310)
=> [ntopng] Add options to the fuzzer

projects/univocity-parsers/.gitignore, projects/univocity-parsers/Dockerfile, projects/univocity-parsers/build.sh, projects/univocity-parsers/project-parent/fuzz-targets/pom.xml, projects/univocity-parsers/project-parent/fuzz-targets/src/test/java/com/example/CsvParserFuzzer.java, projects/univocity-parsers/project-parent/fuzz-targets/src/test/java/com/example/TsvParserFuzzer.java, projects/univocity-parsers/project-parent/pom.xml, projects/univocity-parsers/project.yaml
Integrating univocity-parsers into OSS-Fuzz
=> univocity-parsers: Initial integration

projects/json-flattener/.gitignore, projects/json-flattener/Dockerfile, projects/json-flattener/build.sh, projects/json-flattener/project-parent/fuzz-targets/pom.xml, projects/json-flattener/project-parent/fuzz-targets/src/test/java/com/example/FlattenFuzzer.java, projects/json-flattener/project-parent/fuzz-targets/src/test/java/com/example/UnflattenFuzzer.java, projects/json-flattener/project-parent/pom.xml, projects/json-flattener/project.yaml
Integrating json-flattener into OSS-Fuzz.
=> json-flattener: Initial integration

projects/freerdp/Dockerfile, projects/freerdp/build.sh, projects/freerdp/project.yaml
Issue: https://github.com/FreeRDP/FreeRDP/issues/5063
How To Build: https://github.com/awakecoding/FreeRDP-Manuals/blob/master/Developer/FreeRDP-Developer-Manual.markdown
=> [freerdp] initial integration

projects/github_scarecrow/project.yaml
Test for https://github.com/google/oss-fuzz/pull/10376
=> Update contact list for scarecrow project

infra/build/functions/trial_build/cloudbuild.yaml
Addresses [@jonathanmetzman's suggestion](https://github.com/google/oss-fuzz/pull/10409#issuecomment-1571166932).
=> Increase trial build timeout to 7 hours

projects/async-http-client/project-parent/fuzz-targets/pom.xml, projects/async-http-client/project.yaml
Update project async-http-client based on https://github.com/AsyncHttpClient/async-http-client/issues/1881#issuecomment-1565219182
=> async-http-client: Update project.yaml and pom.xml

projects/pcapplusplus/Dockerfile, projects/pcapplusplus/build.sh, projects/pcapplusplus/project.yaml
https://oss-fuzz-build-logs.storage.googleapis.com/index.html#pcapplusplus
=> Fix pcapplusplus build

projects/librawspeed/build.sh
https://github.com/google/oss-fuzz/issues/10458
=> [librawspeed] Sink `build.sh` into the project's repository

infra/base-images/base-builder/compile, infra/base-images/base-runner/python_coverage_runner_help.py
Fixes: https://github.com/google/oss-fuzz/issues/10350
=> base-runner: adjust python cov helper to py 3.9

infra/build/build_status/cloudbuild.yaml
Fix https://github.com/google/oss-fuzz/issues/10366
=> Increase build status timeout time.

projects/qdox/.gitignore, projects/qdox/Dockerfile, projects/qdox/build.sh, projects/qdox/project-parent/fuzz-targets/pom.xml, projects/qdox/project-parent/fuzz-targets/src/test/java/com/example/JavaProjectBuilderFuzzer.java, projects/qdox/project-parent/pom.xml, projects/qdox/project.yaml
Integrating qdox into OSS-Fuzz.
=> qdox: Initial integration

projects/jolt/Dockerfile, projects/jolt/JsonUtilsFuzzer.java, projects/jolt/build.sh, projects/jolt/project.yaml
This PR initialises the fuzzing for JsonUtils class of Jolt project.
=> Jolt: project initialization

projects/checkstyle/CheckstyleFuzzer.java, projects/checkstyle/Dockerfile, projects/checkstyle/build.sh, projects/checkstyle/project.yaml
This PR initialises the fuzzing for checkstyle project.
=> Checkstyle: project initialization

projects/pandas/build.sh
Fixes: https://github.com/google/oss-fuzz/issues/10476
=> pandas: fix build

projects/avro/.gitignore, projects/avro/Dockerfile, projects/avro/build.sh, projects/avro/project-parent/fuzz-targets/pom.xml, projects/avro/project-parent/fuzz-targets/src/test/java/com/example/AvroSerializationFuzzer.java, projects/avro/project-parent/pom.xml, projects/avro/project.yaml
Integrating Apache Avro into OSS-Fuzz.
=> avro: Initial integration

infra/build/fuzz-introspector-webapp/cloudbuild.yaml
Set min instance 1 to reduce cold start latency.
=> Add min/max instances for fuzz introspector app.

projects/cctz/build.sh
This is an attempt to fix the error displayed in:
https://github.com/google/cctz/actions/runs/5198238431/jobs/9384171641?pr=258
=> Make the src "cp" command a little more specific

projects/python-email-validator/Dockerfile, projects/python-email-validator/build.sh
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=59689
=> python-email-validator: fix build

projects/bitcoin-core/build.sh
This should make it easier to catch undefined behavior.
=> bitcoin-core: Enable -D_LIBCPP_ENABLE_ASSERTIONS=1 via DEBUG=1

projects/hadoop/.gitignore, projects/hadoop/Dockerfile, projects/hadoop/build.sh, projects/hadoop/project-parent/fuzz-targets/pom.xml, projects/hadoop/project-parent/fuzz-targets/src/test/java/com/example/FileUtilFuzzer.java, projects/hadoop/project-parent/fuzz-targets/src/test/java/com/example/JavaSerializationFuzzer.java, projects/hadoop/project-parent/pom.xml, projects/hadoop/project.yaml
Integrating Apache Hadoop into OSS-Fuzz
=> hadoop: Initial integration

projects/php/Dockerfile, projects/php/cosmic.list
No longer used after commit 6c140759865d6c09581c8dac1e267516d693c00d
=> php: Remove unused cosmic.list

projects/leveldb/Dockerfile
=> leveldb: remove autotools deps

projects/libdwarf/Dockerfile
=> libdwarf: remove autotools deps

infra/base-images/base-builder/bazel_build_fuzz_tests, infra/base-images/base-builder/compile, infra/base-images/base-builder/install_java.sh
Reuses the previous Jazzer file names so that no changes to ClusterFuzz are required.
=> [infra] Update Jazzer to v0.17.1

infra/base-images/base-builder/bazel_build_fuzz_tests, infra/base-images/base-builder/compile, infra/base-images/base-builder/install_java.sh
=> Revert "[infra] Update Jazzer to v0.17.1"

projects/calcite/.gitignore, projects/calcite/Dockerfile, projects/calcite/build.sh, projects/calcite/project-parent/fuzz-targets/pom.xml, projects/calcite/project-parent/fuzz-targets/src/test/java/com/example/CalciteFuzzer.java, projects/calcite/project-parent/fuzz-targets/src/test/java/com/example/SqlParserFuzzer.java, projects/calcite/project-parent/pom.xml, projects/calcite/project.yaml
Integrating Apache Calcite into OSS-Fuzz.
=> calcite: Initial integration

projects/c-blosc2/Dockerfile
This project uses CMake & make.
=> c-blosc2: drop autotools deps

projects/golang/Dockerfile, projects/golang/build.sh
=> golang: bump go

projects/g-auth-library-java/.gitignore, projects/g-auth-library-java/Dockerfile, projects/g-auth-library-java/build.sh, projects/g-auth-library-java/project-parent/fuzz-targets/pom.xml, projects/g-auth-library-java/project-parent/fuzz-targets/src/test/java/com/example/CredentialsFuzzer.java, projects/g-auth-library-java/project-parent/fuzz-targets/src/test/java/com/example/TokenVerifierFuzzer.java, projects/g-auth-library-java/project-parent/pom.xml, projects/g-auth-library-java/project.yaml
Integrating Google Open source Auth client library for Java into OSS-Fuzz.
=> g-auth-library-java: Initial integration

projects/p11-kit/project.yaml
=> p11-kit: Add new member to project

projects/jsign/AuthenticodeAppxSignerFuzzer.java, projects/jsign/Dockerfile
This is an additional fuzzer for the APPX/MSIX files signed by Jsign
=> jsign: fuzzing for appx/msix files

projects/postgresql/project.yaml
Fixes https://github.com/google/oss-fuzz/issues/10603
=> [postgresql] Disable AFL build

projects/canvg/Dockerfile, projects/canvg/babel.config.json, projects/canvg/build.sh, projects/canvg/fuzz.js, projects/canvg/package.patch, projects/canvg/project.yaml
=> [canvg] initial integration

projects/pako/Dockerfile, projects/pako/build.sh, projects/pako/fuzz.js, projects/pako/project.yaml
=> [pako] initial Integration

projects/turf/Dockerfile, projects/turf/build.sh, projects/turf/fuzz.js, projects/turf/package.json, projects/turf/project.yaml
=> [turf] initial integration

projects/closure-library/Dockerfile, projects/closure-library/build.sh, projects/closure-library/fuzz.js, projects/closure-library/project.yaml
[closure-library] initial integration
=> [closure-library] initial integration

projects/lodash/Dockerfile, projects/lodash/build.sh, projects/lodash/fuzz.js, projects/lodash/project.yaml
=> [lodash] initial integration

projects/hive/.gitignore, projects/hive/Dockerfile, projects/hive/build.sh, projects/hive/project-parent/fuzz-targets/pom.xml, projects/hive/project-parent/fuzz-targets/src/test/java/com/example/DeserializeFuzzer.java, projects/hive/project-parent/pom.xml, projects/hive/project.yaml
Integrating Apache Hive into OSS-Fuzz.
=> Apache Hive: Initial integration

projects/quickjs/project.yaml
=> Disable ochang_js_fuzzer for quickjs

projects/lodash/build.sh, projects/lodash/fuzz.js
Observed 2 crashes overnight that were non-security issues. This PR ensures that the harness properly runs without reaching these non-issue states early on.
=> [lodash] improve error handling, formatting, and async

projects/sharp/Dockerfile, projects/sharp/build.sh, projects/sharp/fuzz.js, projects/sharp/project.yaml
=> [sharp] initial integration

projects/fast-xml-parser/Dockerfile, projects/fast-xml-parser/build.sh, projects/fast-xml-parser/fuzz.js, projects/fast-xml-parser/project.yaml
[fast-xml-parser] initial integration
=> [fast-xml-parser] initial integration

projects/jimp/Dockerfile, projects/jimp/build.sh, projects/jimp/fuzz.js, projects/jimp/project.yaml
=> [jimp] initial integration

projects/htmlunit/htmlunit-fuzzer/src/main/java/ossfuzz/HtmlParserFuzzer.java
this is a valid scenario for HtmlUnit.
=> add com.code_intelligence.jazzer.api.BugDetectors.allowNetworkConnections();

projects/protobuf-js/Dockerfile, projects/protobuf-js/build.sh, projects/protobuf-js/fuzz.js, projects/protobuf-js/project.yaml
[protobuf.js] initial integration
=> [protobuf.js] initial integration

projects/jpeg-js/Dockerfile, projects/jpeg-js/build.sh, projects/jpeg-js/fuzz_decode.js, projects/jpeg-js/fuzz_encode.js, projects/jpeg-js/project.yaml
Integrating jpeg-js into OSS-Fuzz.
=> jpeg-js: Initial integration

projects/moby/Dockerfile, projects/moby/build.sh, projects/moby/daemon_fuzzer.go
Fixes the build and improves the daemon fuzzer.
=> moby: fix broken build

infra/build/functions/build_project.py, infra/build/functions/target_experiment.py
Also update build_project.Config to be a dataclass instead of namedtuple.
=> Upload corpus and coverage in target_experiment.py

projects/node-xml2js/Dockerfile, projects/node-xml2js/build.sh, projects/node-xml2js/fuzz_parseString.js, projects/node-xml2js/project.yaml
Integrating node-xml2js into OSS-Fuzz.
=> node-xml2js: Initial integration

infra/build/functions/build_project.py
Previously the cloud build exited before we upload the logs. Now we write a file to record build success and report the failure later after uploading the log if there was one.
=> target_experiment: upload build log properly when the build failed.

projects/spring-cloud-config/Dockerfile, projects/spring-cloud-config/build.sh, projects/spring-cloud-netflix/Dockerfile, projects/spring-cloud-netflix/build.sh
=> [spring-cloud-config,spring-cloud-netflix] Do not run `apt` in `build.sh`

projects/json-flattener/project.yaml
Add primary contact email to project.yaml
=> json-flattener: Add primary contact

projects/brotli-java/build.sh
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=60452
=> brotli-java: fix build

projects/geos/patch.diff
Fixes https://github.com/google/oss-fuzz/issues/10661 cc @jonathanmetzman
=> geos: fix buikld with rebased patch

infra/build/functions/build_lib.py
To avoid contention when production builds are running.
=> Use a separate buildpool for experiments.

projects/gvisor/state_fuzzer.go
bufferv2 has been renamed to buffer.
=> Fix gvisor builds

projects/connexion/Dockerfile, projects/connexion/build.sh
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=60486
=> connexion: fix build

projects/nbclassic/Dockerfile, projects/nbclassic/build.sh
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=60493
=> nbclassic: fix build

projects/bitcoin-core/build.sh
For merge after https://github.com/google/oss-fuzz/pull/10427, which fixes the issue we saw with AFL++: https://github.com/google/oss-fuzz/pull/9461#issuecomment-1568670289.
cc @MarcoFalke @dergoegge
=> bitcoin-core: re-enable LTO (take 4)

projects/wolfssl/Dockerfile, projects/wolfssl/build.sh
Support several more cryptographic algorithms that were recently implemented in wolfSSL.
=> [wolfssl] Support for SM2/SM3/SM4

projects/java-uuid-generator/Dockerfile, projects/java-uuid-generator/GeneratorsFuzzer.java, projects/java-uuid-generator/build.sh, projects/java-uuid-generator/project.yaml
Initial integration for java-uuid-generator.
=> java-uuid-generator: Initial integration

projects/exp4j/Dockerfile, projects/exp4j/ExpressionBuilderFuzzer.java, projects/exp4j/build.sh, projects/exp4j/project.yaml
Initial integration for exp4j.
=> exp4j: Initial integration

projects/evo-inflector/Dockerfile, projects/evo-inflector/EnglishFuzzer.java, projects/evo-inflector/build.sh, projects/evo-inflector/project.yaml
Initial integration for evo-inflector.
=> evo-inflector: Initial integration

projects/jansi/Dockerfile, projects/jansi/JansiFuzzer.java, projects/jansi/build.sh, projects/jansi/project.yaml
Initial integration of project jansi.
=> jansi: Initial integration

projects/open-json/Dockerfile, projects/open-json/JsonTokenerFuzzer.java, projects/open-json/build.sh, projects/open-json/project.yaml
Initial integration for open-json.
=> open-json: Initial integration

infra/build/functions/target_experiment.py
Named experiments will be tagged: `branch-$EXPERIMENT_NAME`
=> Support named experiments

projects/jq/build.sh
Depends on https://github.com/jqlang/jq/pull/2760
=> jq: add compile fuzzer

projects/jq/build.sh
Depends on https://github.com/jqlang/jq/pull/2762
=> jq: add file load fuzzer

projects/graphql-java/Dockerfile, projects/graphql-java/GraphqlFuzzer.java, projects/graphql-java/build.sh, projects/graphql-java/project.yaml
Initial integration for project graphql-java.
=> graphql-java: initial integration

projects/json-simple/build.sh, projects/json-simple/project-parent/fuzz-targets/pom.xml, projects/json-simple/project-parent/fuzz-targets/src/test/java/com/example/JsonParserFuzzer.java
Fixing coverage build failure for json-simple.
=> json-simple: Fix coverage build failure

projects/fuzzywuzzy/DiffUtilsFuzzer.java, projects/fuzzywuzzy/Dockerfile, projects/fuzzywuzzy/FuzzySearchFuzzer.java, projects/fuzzywuzzy/build.sh, projects/fuzzywuzzy/project.yaml
Initial integration for fuzzywuzzy.
=> fuzzywuzzy: initial integration

projects/java-xmlbuilder/Dockerfile, projects/java-xmlbuilder/XmlBuilderFuzzer.java, projects/java-xmlbuilder/build.sh, projects/java-xmlbuilder/project.yaml
Initial integration for project java-xmlbuilder.
=> java-xmlbuilder: initial integration

projects/inih/Dockerfile
=> [inih] fix using official repo

projects/jflex/Dockerfile, projects/jflex/JflexFuzzer.java, projects/jflex/build.sh, projects/jflex/project.yaml
Initial integration for project jflex.
=> jflex: initial integration

infra/base-images/base-builder/jcc.go
- Print error properly when compiling for C++ to begin with. Previously we were masking errors when compiling for C++ at first.
- Use the return code from clang.
- Prefer printing the C++ error over the C error.
- Use Go naming conventions.
=> jcc fixes.

infra/build/functions/build_project.py
To make it more convenient to browse results on GCB.
=> target_experiment: Print build logs.

projects/caddy/Dockerfile, projects/caddy/build.sh
Same problem described in #10642
=>  caddy: install go1.20.6 in Dockerfile

projects/ohc/Dockerfile, projects/ohc/OhcFuzzer.java, projects/ohc/build.sh, projects/ohc/project.yaml
Initial integration for project ohc.
=> ohc: initial integration

projects/apache-poi/Dockerfile, projects/apache-poi/build.sh, projects/apache-poi/pom.xml, projects/apache-poi/project.yaml, projects/apache-poi/src/main/java/org/apache/poi/XLSX2CSVFuzzer.java
This PR applies a few changes to the project apache-poi to improve the setup and make build-logs a bit easier to analyze:
* One more expected exception that showed up locally
* Instruct fuzzer to only look at coverage of classes of the project itself
* Reduce log-spam by disabling progress-output from downloading dependencies
* Adjust mainClass in pom.xml, although this likely has no impact
This also adds myself to CCS (both @apache.org and @gmx.at addresses to allow linking to Github account and access to bug-reports), I am Apache POI committer and PMC chair and would like to be informed about new findings.
Please let me know if adding myself is ok this way or if it needs some other process/steps.
=> Adjust project apache poi

infra/build/functions/target_experiment.py
This makes them easier to manipulate.
=> target_experiment: Upload raw coverage data.

.github/workflows/pr_helper.yml, infra/pr_helper.py
Details: https://github.com/google/oss-fuzz/pull/10758#issuecomment-1658574212
=> PR helper removes maintainers from known contributors.

projects/feign/BodyTemplateFuzzer.java
=> feign: Fix feign fuzzer

projects/jts/JtsFuzzer.java
Fix the exception handling of JtsFuzzer.
=> jts: Fix fuzzer for jts

projects/joni/RegexMatcherFuzzer.java
Fix exception handling for fuzzer of project joni.
=> joni: Fix fuzzer for project joni

projects/ohc/OhcFuzzer.java
Fix exception handling of ohc fuzzer.
=> ohc: Fix ohc fuzzer

projects/graphql-java/GraphqlFuzzer.java
Fix exception handling for GraphqlFuzzer.
=> graphql-java: Fix exception handling for fuzzer

projects/joni/AddrListFixFuzzer.java, projects/joni/RegexMatcherFuzzer.java
Fix exception handling for RegexMatcherFuzzer and AddrListFixFuzzer.
=> joni: Fix exception handling for fuzzer

projects/jansi/JansiFuzzer.java
Fix exception handling for JansiFuzzer.
=> jansi: Fix exception handling for fuzzer

projects/graphql-java/build.sh
Fix dependency inclusion for the graphql-java project fuzzer.
=> graphql-java: Fix dependency jars discovery

projects/ohc/OhcFuzzer.java
Fix a bug in ByteBuffer handling.
=> ohc: Fix bug in fuzzer

projects/numpy/Dockerfile
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=61003
=> numpy: fix build

projects/threetenbp/Dockerfile, projects/threetenbp/ThreetenbpFuzzer.java, projects/threetenbp/build.sh, projects/threetenbp/project.yaml
Initial integration for project threetenbp.
=> threetenbp: initial integration

projects/twitter4j/Dockerfile, projects/twitter4j/TwitterObjectFactoryFuzzer.java, projects/twitter4j/build.sh, projects/twitter4j/project.yaml
Initial integration for project twitter4j.
=> twitter4j: initial integration

projects/pyvex/project.yaml
This is my first contribution to OSSFuzz, so I would greatly appreciate any feedback and confirmation that I have configured my project.yaml correctly! 
Thank you for your time and your review!
=> Project Acceptance Request: PyVex

projects/joni/AddrListFixFuzzer.java
Catching exceptions that are explicitly thrown by the project code.
=> joni: Add missing exception handling

projects/gnutls/Dockerfile, projects/gnutls/build.sh, projects/gnutls/project.yaml
This updates the email address of an existing member and also adds a new project member.
=> gnutls: Update auto_ccs

projects/oss-fuzz-example/Dockerfile, projects/oss-fuzz-example/build.sh, projects/oss-fuzz-example/project.yaml
This integrates oss-fuzz-example for continuous fuzzing. I'm a maintainer of the oss-fuzz-example library.
=> oss-fuzz-example: initial integration

projects/opendal/Dockerfile, projects/opendal/build.sh, projects/opendal/project.yaml
part of https://github.com/apache/incubator-opendal/issues/2551
=> opendal: initial integration

projects/sharp/fuzz.js
Cleans up and improves the fuzz harness for the JavaScript library `sharp` a bit, as the earlier harness had some issues like e.g.: faulty API calls
=> [sharp]: update fuzz harness

infra/cifuzz/run_fuzzers.py
corrected a typo found when reading a function documentation
I read the contributing.md, the code of conduct and signed the Google Individual Contributor License Agreement.
=> corrected a typo

projects/sharp/project.yaml
...as I've just been made aware that sharp, which I maintain, is now being tested via OSS Fuzz.
=> [sharp] Add myself as primary_contact

projects/lodash/fuzz.js
Fixed an introduced recursion bug and randomized the fuzzed API instead of chaining them all
=> [lodash]: improve lodash harness

projects/js-yaml/build.sh, projects/js-yaml/fuzz.js
Make the harness a tad more extensive with fuzzy options
=> [js-yaml] harness improvement

projects/calcite-avatica/Base64Fuzzer.java, projects/calcite-avatica/ConnectStringParserFuzzer.java, projects/calcite-avatica/Dockerfile, projects/calcite-avatica/build.sh, projects/calcite-avatica/project.yaml
Initial integration of project calcite-avatica.
=> calcite-avatica: initial integration

projects/go-ldap/Dockerfile, projects/go-ldap/build.sh, projects/go-ldap/project.yaml
Project: https://github.com/go-ldap/ldap
used in : [authelia](https://github.com/authelia/authelia) [casdoor](https://github.com/casdoor/casdoor) [quay](https://github.com/quay/quay) [bytebase](https://github.com/bytebase/bytebase)  [others](https://github.com/go-ldap/ldap/network/dependents)
ping @cpuschma for upstream approval.
=> [go-ldap] initial integration

docs/_sass/color_schemes/wider.scss, docs/assets/css/just-the-docs-wider.scss, docs/research/target_generation.md
1. Merge Prompt, Fixes, and Targets into one column.
2. Make the page wider to fit all column.
=> Fix LLM report benchmark table.

projects/libxaac/Dockerfile, projects/libxaac/build.sh, projects/libxaac/project.yaml
This is initial integration of libxaac codecs
=> [libxaac] Initial integration

projects/libvips/Dockerfile
In preparation for https://github.com/libvips/libvips/pull/3618.
=> libvips: add highway as a dependency

projects/json2avro/Dockerfile, projects/json2avro/build.sh
Add TARGET_PACKAGE_PREFIX environment variable for fuzz-introspector to ignore analysing on dependency classes.
=> json2avro: Fix target package prefix for json2avro

projects/dpp/project.yaml
requesting merge of this project so that i may use the fuzz suite.
=> new: dpp project

projects/libraw/project.yaml
I'm leaving the Photos team so removing myself from receiving the libraw issue notifications.
=> Removing myself from viewing libraw issues

projects/frr/Dockerfile, projects/frr/build.sh
=> frr: add missing protobuf dep

projects/opendal/project.yaml
https://github.com/apache/incubator-opendal/issues/2925
=> opendal: add more opendal committers to auto ccs

projects/icalendar/Dockerfile, projects/icalendar/build.sh, projects/icalendar/corpus/calendar_with_unicode.ics, projects/icalendar/enhanced_fdp.py, projects/icalendar/ical_fuzzer.py, projects/icalendar/project.yaml
This is my first contribution to OSS-Fuzz! I would greatly appreciate any feedback and confirmation that I have configured my project.yaml correctly. 
Thank you for your time and review!
=> Initial project skeleton for icalendar

projects/g-auth-library-java/build.sh, projects/rome/build.sh
Fix instrumentation issues in g-auth-library-java and build failure in rome.
=> Fix issues

infra/base-images/base-builder/jcc/jcc.go
Applying Jonathan's patch to allow jcc take value from `stdin`.
=> Take stdin

projects/cras/project.yaml
=> cras: Update contacts

projects/ecc-diff-fuzzer/build.sh
Should fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=61637
=> ecc-diff-fuzzer: fix build with libecc

projects/igraph/project.yaml
See https://github.com/google/oss-fuzz/pull/10622#issuecomment-1714795863
=> igraph: enable centipede

projects/libwebp/build.sh
This was added in:
https://chromium.googlesource.com/webm/libwebp/+/a35ea50de40066a6382b88b288ff0956ec7d0dc7
a35ea50d Add a fuzzer for ReadHuffmanCodes
=> libwebp: add huffman_fuzzer

projects/dropwizard/DefaultServerFactoryFuzzer.java, projects/dropwizard/Dockerfile, projects/dropwizard/build.sh, projects/dropwizard/project.yaml
Initial integration for dropwizard.
=> dropwizard: initial integration

projects/unirest-java/Dockerfile, projects/unirest-java/JacksonEngineFuzzer.java, projects/unirest-java/JsonArrayFuzzer.java, projects/unirest-java/build.sh, projects/unirest-java/project.yaml
Initial integration for project unirest-java.
=> unirest-java: initial integration

projects/roaring-bitmap/Dockerfile, projects/roaring-bitmap/RoaringBitmapFuzzer.java, projects/roaring-bitmap/build.sh, projects/roaring-bitmap/project.yaml
Initial integration for project RoaringBitmap.
=> roaring-bitmap: initial integration

projects/libwebp/project.yaml
=> [libwebp] Enable centipede

projects/textwrap/project.yaml
I just realized that I don't have access to a dashboard because my non-Gmail address was used here.
=> Use my Gmail address for textwrap

projects/javacpp/Dockerfile, projects/javacpp/JavacppFuzzer.java, projects/javacpp/build.sh, projects/javacpp/project.yaml
Initial integration for project javacpp.
=> javacpp: initial integration

projects/apache-cxf/Dockerfile, projects/apache-cxf/build.sh, projects/async-http-client/build.sh, projects/avro/build.sh, projects/avro/project-parent/fuzz-targets/src/test/java/com/example/AvroSerializationFuzzer.java, projects/calcite/build.sh, projects/g-http-java-client/build.sh, projects/gwt/build.sh, projects/hadoop/build.sh, projects/hive/build.sh, projects/ion-java/build.sh, projects/java-jwt/build.sh, projects/jdom/Dockerfile, projects/jose4j/build.sh, projects/json-flattener/build.sh, projects/jsqlparser/Dockerfile, projects/jsqlparser/build.sh, projects/mvel/build.sh, projects/opencensus-java/build.sh, projects/opencsv/build.sh, projects/pdfbox/build.sh, projects/presto/build.sh, projects/qdox/build.sh, projects/qdox/project-parent/fuzz-targets/src/test/java/com/example/JavaProjectBuilderFuzzer.java, projects/tablesaw/build.sh, projects/univocity-parsers/build.sh, projects/yamlbeans/build.sh, projects/zt-zip/build.sh
Previous Jazzer version only instrument code under the same package as the fuzz test, this PR adds `--instrumentation_includes` to several projects.
Also fix build failures in jdom and jsqlparser, fix fuzzing blocker in qdox and avro, delete not needed file in apache-cxf
=> Fix issues for multiple projects

projects/avahi/project.yaml
to make it easier to keep track of them.
=> [avahi] file issues on GitHub

projects/undertow/Dockerfile, projects/undertow/RedirectHandlerFuzzer.java, projects/undertow/build.sh, projects/undertow/project.yaml
Initial integration of project undertow.
=> undertow: initial integration

infra/base-images/base-builder/jcc/jcc.go
Whenever we fail, ensure there's a proper stderr written to stderr. Also, only write stderr to stderr never to stdout
=> Improve stdout/stderr handling and make sure errors are debuggable

projects/libzip/project.yaml
=> libzip: add two maintainers to auto_ccs

projects/dav1d/Dockerfile
=> dav1d: Fix fuzzer seed corpus url

projects/scrapy/Dockerfile, projects/scrapy/build.sh, projects/scrapy/fuzz_crawl.py, projects/scrapy/project.yaml
Initial integration of scrapy.
@wRAR do you agree with this?
=> scrapy: initial integration

projects/spatial4j/Dockerfile, projects/spatial4j/SpatialContextFuzzer.java, projects/spatial4j/build.sh, projects/spatial4j/project.yaml
Initial integration for projects spatial.
=> spatial: initial integration

projects/mybatis-3/Dockerfile, projects/mybatis-3/PooledDataSourceFuzzer.java, projects/mybatis-3/ResolverUtilFuzzer.java, projects/mybatis-3/build.sh, projects/mybatis-3/project.yaml
Initial integration for project mybatis-3.
=> mybatis-3: initial integration

projects/java-diff-utils/DiffUtilsFuzzer.java, projects/java-diff-utils/Dockerfile, projects/java-diff-utils/build.sh, projects/java-diff-utils/project.yaml
Initial integration for project java-diff-utils.
=> java-diff-utils: initial integration

projects/markdown-it-js/project.yaml
initial integration for javascript **markdown-it** library
=> markdown-it-js : initial integration

projects/tarantool/build.sh
=> tarantool: introduce fuzz introspector config

projects/quartz/CronScheduleBuilderFuzzer.java, projects/quartz/Dockerfile, projects/quartz/build.sh, projects/quartz/project.yaml
Initial integration for project quartz.
=> quartz: initial integration

projects/docker-client/Dockerfile, projects/docker-client/RegistryAuthFuzzer.java, projects/docker-client/build.sh, projects/docker-client/project.yaml
Initial integration for project docker-client.
=> docker-client: initial integration

projects/swagger-core/Dockerfile, projects/swagger-core/YamlFuzzer.java, projects/swagger-core/build.sh, projects/swagger-core/project.yaml
Initial integration for project swagger-core.
=> swagger-core: initial integration

projects/kie-soup/CronExpressionFuzzer.java, projects/kie-soup/Dockerfile, projects/kie-soup/build.sh, projects/kie-soup/project.yaml
Initial integration for project kie-soup.
=> kie-soup: initial integration

projects/markdown-it-js/Dockerfile, projects/markdown-it-js/build.sh, projects/markdown-it-js/fuzz.js
Fuzzing environment (`Dockerfile`-`build.sh`) and target(`fuzz.js`) created.
=> markdown-it-js : build project and fuzzer

projects/libzip/Dockerfile, projects/libzip/build.sh
and install a couple more optional dependencies
=> libzip: adapt to ossfuzz build script move

projects/gpsd/fuzzer/FuzzPacket.c
Fixes: https://github.com/google/oss-fuzz/issues/11050
=> gpsd: fix build

projects/fastify/Dockerfile
This PR clones more fastify sub-projects. Additional fuzzers on these newly cloned sub-projects will be added soon.
=> fastify: Clone more fastify sub-projects

projects/g-oauth-java-client/Dockerfile, projects/g-oauth-java-client/OauthSignerFuzzer.java, projects/g-oauth-java-client/build.sh, projects/g-oauth-java-client/project.yaml
Initial integration for project google-oauth-java-client.
=> google-oauth-java-client: initial integration

projects/mariadb-connector-j/Dockerfile, projects/mariadb-connector-j/MariaDbPoolDataSourceFuzzer.java, projects/mariadb-connector-j/build.sh, projects/mariadb-connector-j/project.yaml
Initial integration for project mariadb-connector-j.
=> mariadb-connector-j: initial integration

projects/twelve-monkeys/Dockerfile, projects/twelve-monkeys/WildcardStringParserFuzzer.java, projects/twelve-monkeys/build.sh, projects/twelve-monkeys/project.yaml
Initial integration for project twelve-monkeys.
=> twelve-monkeys: initial integration

projects/lucene/project.yaml
Closes #11067
Me: https://lucene.apache.org/whoweare.html also available at dsmiley@apache.org
=> Lucene: Adding David Smiley

projects/sketches-core/Dockerfile, projects/sketches-core/FdtSketchFuzzer.java, projects/sketches-core/MurmurHash3AdaptorFuzzer.java, projects/sketches-core/build.sh, projects/sketches-core/project.yaml
Initial integration for project sketches-core.
=> sketches-core: initial integration

projects/jooq/Dockerfile, projects/jooq/GenerationToolFuzzer.java, projects/jooq/build.sh, projects/jooq/project.yaml
Initial integration of project jooq.
=> jooq: initial integration

projects/sqlite-jdbc/Dockerfile, projects/sqlite-jdbc/SqliteConnectionFuzzer.java, projects/sqlite-jdbc/build.sh, projects/sqlite-jdbc/project.yaml
Initial integration of project sqlite-jdbc.
=> sqlite-jdbc: initial integration

projects/flyway/Dockerfile, projects/flyway/LocationFuzzer.java, projects/flyway/build.sh, projects/flyway/project.yaml
Initial integration for project flyway.
=> flyway: initial integration

projects/wasmer/Dockerfile, projects/wasmer/build.sh
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=62998
=> wasmer: fix build

tools/vscode-extension/src/commands/cmdBuildFuzzerFromWorkspace.ts, tools/vscode-extension/src/commands/cmdCreateOSSFuzzSetup.ts, tools/vscode-extension/src/commands/cmdEndToEndCoverage.ts, tools/vscode-extension/src/commands/cmdReproduceTestcase.ts, tools/vscode-extension/src/coverageHelper.ts, tools/vscode-extension/src/projectIntegrationHelper.ts, tools/vscode-extension/src/utils.ts
Set notifications at bottom of VSCode to indicate progress in commands that have a lot of steps.
=> vscode: add status bar updates

projects/libultrahdr/Dockerfile, projects/libultrahdr/build.sh, projects/libultrahdr/project.yaml
This is initial integration of libultrahdr codecs.
=> [libultrahdr] Initial Integration

projects/libxaac/project.yaml
Added few contributors to auto_ccs
=> [libxaac]: update auto_ccs

projects/cloud-custodian/fuzz_resources_validate.py
Add in more validate function calls from different classes in the resources packages to fuzz_resources_validate fuzzer for project Cloud-Custodian.
=> Cloud-custodian: Add more function calls to fuzz_resources_validate fuzzer

projects/cryptofuzz/build.sh
- Enable `-D_LIBCPP_DEBUG=1` to find bugs like https://github.com/randombit/botan/issues/3734
- Compile wolfCrypt with AES EAX ciphermode
=> [cryptofuzz] Updates

projects/pcapplusplus/project.yaml
=> Exclude third party libs from PcapPlusPlus coverage report

projects/skia/Dockerfile, projects/skia/build.sh
Requires https://skia-review.googlesource.com/c/skia/+/767976 to land first
=> [skia] Add skcolorspace fuzzer

projects/u-root/build.sh
Currently, 3 fuzzing targets fail in the CI, until the underlying issue is fixed, the targets have been commented out.
=> u-root: fixup build

projects/avahi/project.yaml
It's prompted by https://github.com/lathiat/avahi/issues/491
=> [avahi] add more contributors

projects/cloud-custodian/fuzz_resources_parser.py
This PR adds an error handling to capture expected ValueError/TypeError thrown from the code.
=> Cloud Custodian: Fix error handling for fuzzer

projects/wt/Dockerfile, projects/wt/build.sh, projects/wt/project.yaml
My PR https://github.com/emweb/wt/pull/203
=> [wt] emweb initial integration

projects/util-linux/Dockerfile
Add flex to the list of the required packages.
=> Update util-linux dockerfile

projects/icalendar/project.yaml
I would like to have access to the FUZZ results of icalendar. I am a maintainer.
see discussion here:
collective/icalendar#578
=> Add @niccokunzmann to icalendar

projects/lcms/Dockerfile, projects/lcms/build.sh, projects/lcms/cms_cgats_fuzzer.c, projects/lcms/cms_cie_cam02_fuzzer.c, projects/lcms/cms_devicelink_fuzzer.c, projects/lcms/cms_dict_fuzzer.c, projects/lcms/cms_gdb_fuzzer.c, projects/lcms/cms_md5_fuzzer.c, projects/lcms/cms_postscript_fuzzer.c, projects/lcms/cms_transform_extended_fuzzer.c, projects/lcms/cms_virtual_profile_fuzzer.c
Hi! This pull request expands fuzzing coverage of Little-CMS by adding 7 new fuzz targets and modifying 1 existing fuzz target (cms_transform_extended_fuzzer).
Docker file includes 7 new ICC profiles derived from Little-CMS/testbed and build.sh is modified and added with new fuzz targets and their seed corpuses.
=> Fuzzing Coverage Expansion of Little-CMS

projects/orjson/Dockerfile
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=63225
=> orjson: fix build

projects/libhtp/build.sh, projects/libhtp/multiple.txt
Meant to fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=63257&q=label%3AProj-libhtp
=> libhtp: build rust in release mode

projects/cloud-custodian/fuzz_gcp_actions_validate_process.py, projects/cloud-custodian/fuzz_gcp_filters_validate_process.py
This PR fixes the fuzz_gcp_filters_validate_process fuzzer for the following issues.
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=63412
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=63821
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=63904
=> Cloud-custodian: Fix fuzzer

projects/icalendar/project.yaml
see https://github.com/google/oss-fuzz/issues/11199
=> change gmail -> googlemail

projects/openssl/build.sh
=> openssl: only build single branch in introspector mode

projects/gdk-pixbuf/Dockerfile
Fuzzdata is no longer available.
=> gdk-pixbuf: Use corpus-replicator to generate seed corpus

projects/pcapplusplus/project.yaml
=> Adding myself to pcapplusplus

projects/surrealdb/project.yaml
Add individual SurrealDB employees as contacts so they can access the issue tracker.
=> surrealdb: update auto_ccs

projects/gobgp/Dockerfile, projects/gobgp/build.sh, projects/gobgp/project.yaml
[GoBGP](https://osrg.github.io/gobgp/) is a major Golang implementation of BGP.
Used by: `CloudWan`, `Tele2`, `Sakura`, `NexusGuard`, `FastNetMon`, `DigitalOcean`.
@fujita Does this look good?
=> [gobgp] initial integration

projects/gosnmp/Dockerfile, projects/gosnmp/build.sh, projects/gosnmp/project.yaml
@SuperQ @TimRots does this look good?
=> [gosnmp] initial integration

projects/openssl/project.yaml
See https://github.com/google/oss-fuzz/pull/11223
I'm submitting this because I've signed the CLA and the others have not.
=> [openssl] Add CCs

projects/skipper/Dockerfile, projects/skipper/build.sh, projects/skipper/project.yaml
=> add: project skipper

projects/metallb/Dockerfile, projects/metallb/build.sh, projects/metallb/project.yaml
Target: https://metallb.universe.tf 
@fedepaol dose this look good?
=> [Metallb] initial integration

projects/suricata/Dockerfile, projects/suricata/build.sh
As development towards suricata 8 just started
cc @victorjulien
=> suricata: fuzz 7 branch

projects/skipper/project.yaml
skipper: add auto_cc to access ClusterFuzz webinterface
=> skipper: add auto_cc

projects/linkerd2/project.yaml
CC @olix0r
Ref: https://github.com/google/oss-fuzz/pull/11219
=> linkerd2: update project yaml

tools/vscode-extension/package-lock.json, tools/vscode-extension/src/projectIntegrationHelper.ts
Adds template creation support for C, C++ and Java
=> vscode: extend project template creation

projects/time/Dockerfile, projects/time/build.sh, projects/time/project.yaml
[time](https://github.com/facebook/time) library by meta.
usage: [opentelemetry-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib), [Time-Appliance-Project](https://github.com/opencomputeproject/Time-Appliance-Project), [aperture](https://github.com/fluxninja/aperture) .
@abulimov does this look good?
=> [time] initial integration

projects/quantlib/project.yaml
This is an attempt to fix #11234, not sure if I'm right about this being the problem. If this is the problem it'd be nice if small typos like this are caught somehow by the CI.
=> Quantlib: fix minor typo

projects/apache-commons-codec/project.yaml, projects/apache-commons-io/project.yaml, projects/apache-commons-lang/project.yaml
We'd like to start contributing fuzzers to the projects and this has been approved through email with Apache maintainers.
=> apache-commons-{io, codec, lang}: add Ada Logics folks

projects/harfbuzz/project.yaml
Remove cchapman@adobe.com from list of CC recipients.
=> [harfbuzz] Remove a an auto CC recipient

projects/apache-commons-codec/ChecksumFuzzer.java, projects/apache-commons-codec/CryptFuzzer.java, projects/apache-commons-codec/DigestUtilsFuzzer.java, projects/apache-commons-codec/HmacUtilsFuzzer.java, projects/apache-commons-codec/LanguageStringEncoderFuzzer.java, projects/apache-commons-codec/MurmurHashFuzzer.java, projects/apache-commons-codec/NetCodecFuzzer.java, projects/apache-commons-codec/PhoneticEngineFuzzer.java
This PR adds new fuzzers for the apache-commons-codec project.
=> Apache-commons-codec: add new fuzzers

projects/skcms/build.sh, projects/skcms/project.yaml
A new .cc file was added to skcms; this updates the build steps in oss-fuzz to match.
=> Fix skcms fuzzer build step

projects/time/project.yaml
Give pcullen@meta.com access to OSS-Fuzz reports.
=> Issue #11243 Update project.yaml to update access to reports

projects/apache-commons-io/Dockerfile, projects/apache-commons-io/FileComparatorFuzzer.java, projects/apache-commons-io/FileFilterFuzzer.java, projects/apache-commons-io/InputStreamFuzzer.java, projects/apache-commons-io/OutputStreamFuzzer.java, projects/apache-commons-io/PathUtilsFuzzer.java, projects/apache-commons-io/ReaderFuzzer.java, projects/apache-commons-io/WriterFuzzer.java
This PR adds new fuzzers to the project apache-commons-io.
=> Apache-commons-io: add new fuzzers

projects/apache-commons-lang/ArrayUtilsFuzzer.java, projects/apache-commons-lang/CharUtilsFuzzer.java, projects/apache-commons-lang/ConversionFuzzer.java, projects/apache-commons-lang/DateUtilsFuzzer.java, projects/apache-commons-lang/FractionFuzzer.java, projects/apache-commons-lang/LocaleUtilsFuzzer.java, projects/apache-commons-lang/MathUtilsFuzzer.java, projects/apache-commons-lang/SerializationUtilsFuzzer.java, projects/apache-commons-lang/StringUtilsFuzzer.java
This PR adds new fuzzers for project apache-commons-lang.
=> Apache-commons-lang: Add new fuzzers

tools/vscode-extension/package.json, tools/vscode-extension/src/projectIntegrationHelper.ts
Also changes the use of `.c++` to `.cpp` suffix for CPP template creation
=> vscode: clean-up command interface

projects/pcapplusplus/project.yaml
=> Add myself to PcapPlusPlus project.yaml

projects/pandas/project.yaml
Ref: https://github.com/google/oss-fuzz/issues/11253
=> pandas: add NumFOCUS security contact

projects/jq/build.sh
Ref: https://github.com/jqlang/jq/pull/2959
=> jq: add new fuzzer

projects/jackson-dataformat-xml/Dockerfile, projects/jackson-dataformat-xml/XmlDeserializerFuzzer.java, projects/jackson-dataformat-xml/XmlSerializerFuzzer.java, projects/jackson-dataformat-xml/build.sh, projects/jackson-dataformat-xml/project.yaml
Add more fuzzers for project jackson-datatype-xml and add more vender_ccs emails.
=> jackson-datatype-xml: add more fuzzers

projects/jackson-dataformats-binary/DeserializerFuzzer.java, projects/jackson-dataformats-binary/Dockerfile, projects/jackson-dataformats-binary/SerializerFuzzer.java, projects/jackson-dataformats-binary/build.sh, projects/jackson-dataformats-binary/project.yaml
Add more fuzzers for project jackson-dataformats-binary.
=> jackson-dataformats-binary: add more fuzzers

projects/apache-commons-io/FileUtilsFuzzer.java, projects/apache-commons-io/GeneralUtilsFuzzer.java
Add more fuzzers to project apache-commons-io.
=> apache-commons-io: Add more fuzzers

projects/opencensus-cpp/project.yaml, projects/opencensus-go/project.yaml, projects/opencensus-java/project.yaml, projects/opencensus-python/project.yaml
cf https://opentelemetry.io/blog/2023/sunsetting-opencensus/
cc @jsuereth
PS : cpp build has been failing cf https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=63224
=> opencensus: disabling project in all languages

projects/lzo/lzo_compress_target.c, projects/lzo/lzo_decompress_target.c
Drive-by: reformat and use more clear variable names
=> Do not store buffers on stack

projects/jackson-dataformat-xml/FromXmlParserFuzzer.java, projects/jackson-dataformat-xml/ToXmlGeneratorFuzzer.java
This PR adds fuzzers to proejct jackson-dataformat-xml to increase code coverage.
=> jackson-dataformat-xml: Add more fuzzers to increase coverage

projects/apache-commons-lang/ClassFuzzerBase.java, projects/apache-commons-lang/ReflectUtilsFuzzer.java
This PR fixes a possible unexpected end of fuzzer execution for ReflectUtilsFuzzer in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=64856.
=> apache-commons-lang: Fix fuzzers

projects/wget/build.sh
Add `--disable-openssl` configure flag to nettle build.
=> [wget] Fix nettle build

projects/wget2/build.sh
Add `--disable-openssl` configure flag to nettle build.
=> [wget2] Fix nettle build

projects/nokogiri/project.yaml
:wave: I'm the maintainer of Nokogiri. I'm moving myself to primary contact (but keeping fuzzy.boiiii23a as a CC), and CCing a project mailing list.
=> Update nokogiri project contact info

projects/jackson-dataformats-binary/AvroGeneratorFuzzer.java, projects/jackson-dataformats-binary/AvroParserFuzzer.java, projects/jackson-dataformats-binary/CborGeneratorFuzzer.java, projects/jackson-dataformats-binary/CborParserFuzzer.java, projects/jackson-dataformats-binary/IonGeneratorFuzzer.java, projects/jackson-dataformats-binary/IonParserFuzzer.java, projects/jackson-dataformats-binary/ProtobufParserFuzzer.java, projects/jackson-dataformats-binary/SmileGeneratorFuzzer.java, projects/jackson-dataformats-binary/SmileParserFuzzer.java
This PR adds more fuzzers for generators and parsers of different dataformats in the project jackson-dataformats-binary.
=> jackson-dataformats-binary: Add new fuzzers for generators and parsers

projects/openssl/project.yaml
Fixes: https://github.com/google/oss-fuzz/issues/11358
=> openssl: add maintainer

tools/vscode-extension/src/projectIntegrationHelper.ts
Also adds such that files are only generated in the CFLite set up if they don't already exist.
=> vscode: fix bugs and add CFLite .yml generation

projects/libjxl/project.yaml
graphicsmagick with i386 got some findings for our project
=> Add i386 arch to libjxl

projects/apache-commons-io/GeneralUtilsFuzzer.java
This PR adds more branches for GeneralUtilsFuzzer to increase fuzzer coverage for the IOUtils class.
=> apache-commons-io: Add branchers to GeneralUtilsFuzzer to increase fuzzer coverage

projects/apache-commons-lang/LocaleUtilsFuzzer.java
This PR fixes a possible GC overhead reported in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=64919 for `LocalUtilsFuzzer` of project apache-commons-lang.
=> apache-commons-lang: Fix GC overhead

projects/gitoxide/build.sh
This should speed up the build signficantly.
=> gitoxide: Share cache between fuzz crates

tools/vscode-extension/src/commands/cmdTemplate.ts, tools/vscode-extension/src/projectIntegrationHelper.ts
Deduplicates a lot of the template generation.
=> vscode: refactor CFLite integration

projects/fastify/Dockerfile
This PR adds cloning for another Fastify-plugin in the Dockerfile.
=> fastify: Add repository in Dockerfile

projects/wuffs/Dockerfile
Actually using this corpus will be separate (other repo) commit to https://github.com/google/wuffs/blob/main/fuzz/c/std/seed_corpora.txt
=> [wuffs] add xz_corpus

projects/nodejs/build.sh
Use test files from nodes source tree for the seed. Filter out small and large files.
=> nodejs: improve seed

projects/llvm/build.sh
This follows updates to opt fuzzer:
https://github.com/llvm/llvm-project/pull/76474
=> llvm: extend opt fuzzer with new passes

projects/lua/build.sh
Follows up commit cd98f0c6bbde ("lua: enable aarch64 (#11389)").
=> lua: update aarch64 packages

projects/libevent/bufferevent_fuzzer.cc
Hi! This pull request makes some changes to the previous pull request https://github.com/google/oss-fuzz/pull/11377. In detail, all **printf** statements were replaced with assertions.
@DavidKorczynski please check when you have a time.
Fyi @azat.
=> libevent: Fuzzing Coverage Expansion #3

projects/nodejs/build.sh
The latest build exceeded resources. Limiting to 1 job
=> nodejs: limit resources in coverage build

projects/libavif/project.yaml
This is to assist debugging issues with FuzzTest setup
CC @vrabaud
=> libavif: add my email to project.yaml

projects/md4c/project.yaml
The title says it all actually.
=> md4c: Enable file_github_issue

projects/icu/project.yaml
Add Rich Gillam from Apple to the project so Apple could know the most updated issue and code review our fix.
=> Add richard_gillam@apple.com to icu/project.yaml

projects/openyurt/Dockerfile
The old yurt-app-manager project is archived, change to openyurt.
=> openyurt: fix fuzz test repo

projects/apache-commons-compress/project.yaml, projects/apache-commons-geometry/project.yaml, projects/apache-commons-imaging/project.yaml, projects/apache-commons-math/project.yaml, projects/fastjson2/project.yaml, projects/jackson-core/project.yaml, projects/jackson-dataformat-xml/project.yaml, projects/jackson-dataformats-binary/project.yaml, projects/java-example/project.yaml, projects/json-sanitizer/project.yaml, projects/kryo/project.yaml, projects/log4j2/project.yaml, projects/protobuf-java/project.yaml, projects/zxing/project.yaml
I no longer work on oss-fuzz project maintenance.
=> Remove myself from CCs

projects/qpdf/project.yaml
Adding M. Holger to the qpdf project so he can see private issues.
=> Grant M. Holger access to qpdf project issues

projects/curl/project.yaml
We'd like to add @icing to the list of CCs for the curl project.
=> Add icing to curl CCs

projects/pydateutil/fuzz_tzstr.py
See https://dateutil.readthedocs.io/en/stable/tz.html#dateutil.tz.tzstr
=> Add a fuzzer for dateutil's tzstr parser

projects/naga/project.yaml
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=64966
=> naga: fix coverage build

projects/cairo/Dockerfile, projects/cairo/build.sh
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=63669
=> [cairo] Fix broken build

projects/nestegg/Dockerfile, projects/nestegg/build.sh
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=65676
=> [nestegg] Fix build failure

projects/librosa/project.yaml
Librosa is a powerful Python library for audio analysis and manipulation. It is used to analyze and manipulate audio files in a variety of formats such as WAV, OGG, MP3, FLAC, etc. It is used to extract features from audio files, manipulate audio in various ways, and build machine learning models for speech recognition, music genre classification and  instrument recognition. It has a large user base with nearly 6,500 stars on Github and referenced in numerous research papers. This project is important to be fuzzed as it depends on user input which can be used to exploit crashes in the Python code to achieve malicious ends such as DoS.
=> Initial project skeleton for librosa

infra/cifuzz/platform_config/github.py, infra/cifuzz/platform_config/github_test.py
Related: https://github.com/google/oss-fuzz/issues/11536
=> [cifuzz] Allow using Github enterprise servers

projects/avahi/Dockerfile
to make it easier to change them.
Depends on https://github.com/avahi/avahi/pull/559
=> [avahi] move build deps upstream

projects/opendal/build.sh
fix: https://github.com/apache/opendal/issues/4164
=> opendal: fix build

projects/jackson-dataformats-binary/project.yaml
(feel free to change if there is a better way)
=> Add Tyler Gregg (maintainer of `jackson-dataformat-ion`) into project.yaml to give access

projects/jackson-core/Dockerfile, projects/jackson-databind/Dockerfile
Addresses: https://github.com/google/oss-fuzz/pull/9946#issuecomment-1936716262
The other repos from that PR are already using latest.
=> jackson-core,jackson-databind: rely on latest branches

projects/xz/project.yaml
The homepage for XZ projects changed recently. The old URLs redirect to the new ones so nothing has been broken :)
=> xz: Update project homepage.

projects/libxml2/project.yaml
Same as https://github.com/google/oss-fuzz/pull/11596
=> libxml2: fix quote in project yaml

projects/ntopng/build.sh
Updating lua dependency. This is needed to fix a building issue.
=> [ntopng] Update lua dependency

projects/wasmtime/project.yaml
I would like to be notified of any issues uncovered by fuzzing in Winch
=> Add Jeff Charles to Wasmtime

projects/mongo-go-driver/build.sh
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=66632
=> mongo-go-driver: fix build

projects/crow/project.yaml
I am requesting permission to integrate [Crow](https://github.com/CrowCpp/Crow) into OSSFuzz. I believe that this project is a good candidate for OSS-Fuzz integration as it is a C++ implementation of a HTTP / websocket framework that enjoys a large user-base. Being written in C++ and being exposed to the network, fuzzing could be applied to uncover potential bugs and / or security concerns in the parsing of incoming HTTP requests.
=> Crow: Initial project request

projects/unblob/Dockerfile, projects/unblob/build.sh, projects/unblob/project.yaml
[unblob](https://unblob.org) is an accurate, fast, and easy-to-use extraction suite. It parses unknown binary blobs for more than 30 different archive, compression, and file-system formats, extracts their content recursively, and carves out unknown chunks that have not been accounted for.
unblob is mostly used by reverse engineers and pentesters alike, we don't have exact numbers on active users but we see  ~1700 monthly downloads from PyPi, which is not the only distribution channel since unblob is also available on Kali Linux packages repository and through docker registries.
unblob comes with [367 integration files](https://github.com/onekey-sec/unblob/tree/main/tests/integration) covering all formats currently supported. These files are [zipped …
=> unblob: initial integration

projects/gpac/Dockerfile, projects/gpac/build.sh
* use testsuite as submodule
* update workdir to work with local source mounts
=> [gpac] small script changes to facilitate local debug

projects/rustls/project.yaml
Hello :wave:
Just a small metadata update to add myself to the list of folks cc'd for Rustls findings. I help with [project maintenance](https://github.com/rustls/rustls?tab=readme-ov-file#project-membership).
=> projects: add cpu to rustls auto_ccs

infra/base-images/base-builder/install_java.sh
Fixes: https://github.com/google/oss-fuzz/issues/11623
Ref: https://github.com/CodeIntelligenceTesting/jazzer/issues/896
=> infra: bump jazzer to latest

projects/skia/project.yaml
Fixes https://github.com/google/oss-fuzz/issues/11601
=> Fix help_url

.clusterfuzzlite/coverage_atheris_fuzzer.py
Unblocks the fuzzer causing CI issues e.g. https://github.com/google/oss-fuzz/pull/11644
Fixes: https://github.com/google/oss-fuzz/issues/11648
=> ClusterFuzzLite: fix fuzzer

projects/qt/Dockerfile
I will remove this hack as soon as the issue is fixed upstream.
=> [qt] Pin configure script to older version to fix build

projects/trafficserver/Dockerfile
the project build made a change that requires pkg-config
=> trafficserver: fix build problem since 02/29

projects/libaom/project.yaml, projects/libvpx/project.yaml
add jingning@, jianj@ and wtc@ consistently; remove departed team member
johannkoenig@.
=> lib{aom,vpx}/project.yaml: update cc list

projects/servo/Dockerfile, projects/servo/build.sh
Adds a fuzz target for the servo rust-cssparser.
=> servo: add rust-cssparser target

projects/systemd/project.yaml
Add Ronan as discussed in
https://github.com/systemd/systemd/pull/30952#issuecomment-1982633296
Should finally address https://github.com/google/oss-fuzz/issues/10637
=> [systemd] more contributors

projects/ffmpeg/build.sh
Connect a fuzzer thingy specifically for libswscale
=> [FFmpeg] build.sh: Add tools/target_sws_fuzzer

projects/fastcsv/CsvReaderFuzzer.java, projects/fastcsv/Dockerfile, projects/fastcsv/build.sh, projects/fastcsv/project.yaml
Initial integration of [FastCSV](https://github.com/osiegmar/FastCSV).
=> FastCSV: initial integration

infra/cifuzz/sarif_utils.py, projects/cifuzz-example/build.sh
=> [CIFuzz] Make writing stacks in sarif more robust

projects/harfbuzz/Dockerfile
HarfBuzz is going to require it.
=> [harfbuzz] Build with meson 0.60.0

projects/libfido2/Dockerfile, projects/libfido2/build.sh
While here, bump the libcbor and zlib versions.
cc @kongeo
=> libfido2: seed recently added fuzzer

projects/dgraph/project.yaml
Updating current Dgraph contacts
=> Update Dgraph project.yaml

projects/wolfssl/project.yaml
Removing Tim from the CC's list.
=> [wolfssl] update user's list

projects/lua/build.sh
Need for debugging AArch64 build.
Needed for https://github.com/ligurio/lua-c-api-tests/issues/72
=> lua: enable verbose mode

projects/libyang/build.sh
Should also fix the build error.
=> libyang: simplify options and include dirs

projects/hsqldb/Dockerfile
Fixes: https://github.com/google/oss-fuzz/issues/11808
=> hsqldb: fix build

projects/suricata/build.sh
cc @jonathanmetzman did I get it right ?
=> suricata: build cifuzz only against master branch

projects/bitcoin-core/build.sh
Related to https://github.com/bitcoin/bitcoin/pull/29837.
=> bitcoin-core: disable `_FORTIFY_SOURCE` for MSAN

projects/freerdp/Dockerfile, projects/freerdp/build.sh, projects/freerdp/project.yaml
* install apt dependencies from nightly package control file
* get CMake configuration from toolchain file
=> [freerdp] install dependencies from nightly control

projects/cups/Dockerfile, projects/gpsd/Dockerfile, projects/krb5/Dockerfile, projects/libmodbus/Dockerfile, projects/ntpsec/Dockerfile, projects/ntpsec/fuzz/setup.c, projects/pupnp/Dockerfile, projects/unit/Dockerfile
Hello oss-fuzz team,
As I already told @jonathanmetzman, That my GitHub account '0x34d' is flagged. So i will be using this one instead.
Sorry boys :)
=> [Build fix] cups, gpsd, krb5, libmodbus, ntpsec, pupnp, unit

projects/pcapplusplus/project.yaml
@seladb @clementperon @sashashura
=> Add new cc contact to PcapPlusPlus list

projects/pistache/build.sh
The fuzzing for pistachio/pistache project has been improved and now has a corpus. Please let me know if I add it correctly to this MR
=> pistache: add fuzzer corpus

projects/gdal/project.yaml
@AbelPau is the maintainer of the GDAL Miramon driver
=> [GDAL] Add new contributor

projects/cryptofuzz/Dockerfile, projects/cryptofuzz/build.sh
Update to newer version of libgpg-error that is needed by libgcrypt.
=> [cryptofuzz] Fix build

CITATION.cff
=> Add a CITATION.cff

projects/bitcoin-core/build.sh, projects/bitcoin-core/project.yaml
=> bitcoin-core: Re-try centipede, skip  build_cryptofuzz.sh in introspector build

projects/leveldb/Dockerfile, projects/leveldb/build.sh
=> leveldb: Use latest builder

projects/msquic/Dockerfile, projects/msquic/build.sh
Use `-Wno-error=invalid-unevaluated-string`
=> msquic: Use latest builder

projects/bitcoin-core/build.sh, projects/bitcoin-core/project.yaml
Also, track remaining free storage space
=> bitcoin-core: Re-enable msan

projects/skia/Dockerfile, projects/skia/build.sh
Added in https://skia-review.googlesource.com/c/skia/+/849831
=> [skia] Use new parse_path fuzzer

projects/tinyusb/Dockerfile, projects/tinyusb/project.yaml
update Dockerfile dependencies and auto_css
=> tinyusb: update Dockerfile and auto_css

projects/ffmpeg/build.sh
Code is based on the target_dec_fuzzer specific code
=> [FFmpeg] Add Support for tools/target_enc_fuzzer

projects/ada-url/project.yaml
=> ada-url: Enable memory sanitizer

projects/golang/build.sh
Ref https://github.com/google/oss-fuzz/pull/11677#issuecomment-2090979176
=> fix broken golang build

infra/base-images/base-clang/Dockerfile
Main contribution is fix to https://github.com/google/oss-fuzz/issues/11706
=> infra: bump introspector

projects/opensk/build.sh
Needed because of https://github.com/google/oss-fuzz/issues/11626#issuecomment-2092460968
=> opensk: Fix build

projects/librsvg/Dockerfile, projects/librsvg/build.sh, projects/librsvg/render_document.options
=> librsvg: initial fuzz_target integration

projects/krb5/Dockerfile, projects/krb5/project.yaml
My base PR has been merged in krb5: https://github.com/krb5/krb5/pull/1346. Can you merge this?
=> [krb5] update repo and maintainer email

projects/pacemaker/build.sh
I am getting errors when building Pacemaker locally. This should fix it.
=> pacemaker: fix broken build

projects/wamr/Dockerfile, projects/wamr/build.sh
=> [wamr] update the working directory

projects/fontations/project.yaml
We got our first issue (hooray!) and it made me realize I didn't add enough auto ccs.
=> Add to Fontations auto-cc list

projects/circl/project.yaml
=> circl: Update CIRCL contact emails.

projects/askama/build.sh
This pr updates build logic to match upstream refactor.
=> askama: update build

projects/mpv/build.sh
An attempt to fix two issues:
- sporadic `No space left on device` during build check
- `/usr/local/bin/compile: line 333: 11681 Killed python3 /fuzz-introspector/src/main.py report $REPORT_ARGS`
Disabling FFmpeg filters is unfortunate, as it reduces coverage of filtering code, but lets focus on stabilizing the core code first.
Introspector fail is likely an OOM error, not sure if this commit will help with it.
Generally mpv is not that big project, so those failures are not expected, but lets try to workaround the limitations.
=> mpv: reduce the build size a little

projects/libavif/Dockerfile
=> libavif: Remove outdated comment about base-builder

projects/mpv/build.sh
Doesn't affect final binaries as they wouldn't link not needed objects, but we can make the build skip some not needed targets that would otherwise be build by meson.
=> mpv: add introspector exclusion config and make build smaller

projects/openssl/project.yaml
Ref: https://github.com/google/oss-fuzz/pull/12130
=> openssl: remove contact from auto_ccs

projects/karchive/karchive_fuzzer.cc
previous commit was half useful only ^_^
=> karchive: Actually fuzz the Zstd compression device

projects/libssh/build.sh
https://github.com/google/oss-fuzz/issues/10136
=> Debug libssh issue.

infra/build/functions/base_images.py, infra/build/functions/build_and_push_test_images.py, infra/build/functions/build_lib.py, infra/build/functions/test_data/expected_trial_build_steps.json
https://github.com/google/oss-fuzz/issues/11967
=> Teach build infra about ruby

infra/base-images/base-builder/Dockerfile, infra/base-images/base-builder/compile_centipede, infra/base-images/base-builder/precompile_centipede, infra/build/functions/test_data/expected_trial_build_steps.json, projects/arrow/project.yaml, projects/file/project.yaml, projects/hermes/project.yaml, projects/libultrahdr/project.yaml, projects/lua/project.yaml
Reverts google/oss-fuzz#11151 as it breaks the base builder
Ref: https://github.com/google/oss-fuzz/pull/11151#issuecomment-2208641953
=> Revert "Update Centipede"

projects/bitcoin-core/build.sh, projects/bitcoin-core/project.yaml
It's broken anyway, so might as well give https://github.com/google/oss-fuzz/issues/12142#issuecomment-2204027194 a try.
=> bitcoin-core: Temporarily disable AFL, fix build

projects/pdfminersix/Dockerfile, projects/pdfminersix/project.yaml
This feature was requested by the project maintainer, as seen [here](https://github.com/pdfminer/pdfminer.six/pull/949#issuecomment-2211808723)
=> Updated pdfminer yaml to file github issues for bugs

projects/openssl/project.yaml
I'll be one of the reviewers of extent and future issues.
=> Add viktor@openssl.org to openssl project at oss-fuzz

projects/libheif/Dockerfile
Required for https://github.com/strukturag/libheif/pull/1208
@farindk
=> libheif: add compression libs

infra/build/functions/trial_build.py
Consider "ruby" a language before a project.
=> [trial_build] Fix handling of languages.

projects/bson-rust/Dockerfile
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=70187
=> bson-rust: fix build

projects/ron/Dockerfile
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=70218
=> ron: fix build

projects/askama/Dockerfile
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=70185
=> askama: fix build

projects/ffmpeg/Dockerfile
build failed because of incorrect clone link. This will correct it
=> Fix ffmpeg dockerfile 

projects/cockroachdb/Dockerfile, projects/cockroachdb/build.sh, projects/cockroachdb/project.yaml
CockroachDB is a distributed SQL database built on a transactional and strongly-consistent key-value store. It scales horizontally; survives disk, machine, rack, and even datacenter failures with minimal latency disruption and no manual intervention; supports strongly-consistent ACID transactions; and provides a familiar SQL API for structuring, manipulating, and querying data.
=> cockroachdb: initial integration

projects/bitcoin-core/project.yaml
For https://github.com/google/oss-fuzz/issues/12142#issuecomment-2204027194
=> bitcoin-core: Enable AFL again

projects/mbedtls/build.sh
FIx https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=70335
=> Fix the build after data_files move to framework

projects/lima/project.yaml
Updates @jandubois 's email address.
=> lima: update maintainers email

projects/bson-rust/Dockerfile, projects/bson-rust/build.sh
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=70387
=> bson-rust: fix coverage build

projects/ron/Dockerfile, projects/ron/build.sh
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=70388
=> ron: fix coverage build

projects/librsvg/Dockerfile, projects/librsvg/build.sh
- Pin serde to fix coverage builds
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=70418
- Expand the seed corpus to increase coverage
=> librsvg: coverage fixes

projects/lima/build.sh
Add 3 more fuzzers from Limas source tree.
=> lima: add upstream fuzzers

projects/bitcoin-core/project.yaml
Test https://github.com/google/oss-fuzz/issues/12142
=> bitcoin-core: selective_unpack: true

projects/cockroachdb/project.yaml
Add `test-eng@cockroachlabs.com` to auto_ccs
=> cockroachdb: update maintainers' email alias

projects/graphicsmagick/Dockerfile
Add libzip to GraphicsMagick build and anchor the base directory.
=> Add libzip to GraphicsMagick build

projects/lima/build.sh
=> lima: run more upstream fuzzers

projects/lima/build.sh
=> lima: run upstream fuzzers

projects/opensk/build.sh
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=70211#c2
Related issue https://github.com/google/oss-fuzz/issues/12168
Fix inspired by https://github.com/google/oss-fuzz/commit/037a2b0dbcc9402512c06805ad06637c6003bf79
=> Pins serde version to fix fuzz build failure

projects/servo/build.sh
This should address https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=70228 based on #1268.
=> Pin serde to working version.

projects/karchive/Dockerfile
=> karchive: Update xz

projects/zeek/build.sh
The Zeek project has started to include real-world analyzers written with [Spicy](https://github.com/zeek/spicy), start building support into it to fuzz these analyzers (LDAP, QUIC).
=> zeek: Build with Spicy enabled

projects/toml_edit/build.sh
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=70913
=> toml_edit: fix coverage build

projects/llamacpp/build.sh
=> llamacpp: simplify build

projects/libtheora/project.yaml, projects/opus/project.yaml, projects/opusfile/project.yaml, projects/vorbis/project.yaml
I currently have access to `speex` and `tremor` (the fixed-point version of `vorbis`)
=> Add myself to several xiph projects

projects/tarantool/build.sh
=> tarantool: add debug for aarch64

projects/sqlite3/Dockerfile
=> sqlite3: fix building

projects/simdutf/project.yaml
This adds myself to the cc list.
Upstream approves: https://github.com/simdutf/simdutf/pull/488#issuecomment-2278533117
=> [simdutf] add paul dreik as cc

projects/haproxy/fuzz_cfg_parser.c
Ref: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=71078#c1
=> haproxy: adjust harness to latest upstream

projects/llamacpp/build.sh
This is to avoid running into large allocations
=> llamacpp: patch target calloc

projects/ffmpeg/build.sh
Few issues where found in FFv1, this small seed corpus may help to find more
=> [FFmpeg] Use ffv1/testset/ as seed corpus for ffv1 testing

projects/opentelemetry/Dockerfile, projects/opentelemetry/build.sh
Adds a recently added fuzzer to opentelemetrys build
=> opentelemetry: add fuzzer

projects/suricata/Dockerfile
Will fix Suricata build broken 2 days ago
=> suricata: pin cbindgen version

projects/haproxy/project.yaml
=> haproxy: extend CC list

projects/openh264/Dockerfile
Fixes: https://github.com/google/oss-fuzz/issues/12343
=> openh264: fix build

projects/xs/project.yaml
This PR adds members of the Agoric team to help with project maintenance.
=> xs: update agoric ownership

projects/gdk-pixbuf/Dockerfile, projects/libldac/Dockerfile, projects/tremor/Dockerfile, projects/vorbis/Dockerfile
=> fix multiple projects using corpus-replicator

projects/suricata/project.yaml
Follow up on https://github.com/google/oss-fuzz/pull/9764
=> suricata: fuzz also on aarch64

projects/ngolo-fuzzing/project.yaml
To save some disk space ?
Aims to fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=67724 cf https://github.com/google/oss-fuzz/issues/12142
=> ngolo-fuzzing: use selective_unpack

projects/sigstore-go/Dockerfile, projects/sigstore-go/build.sh, projects/sigstore-go/project.yaml
Should wait for https://github.com/sigstore/sigstore-go/pull/272
@codysoyland @haydentherapper @bobcallaway @davidkorczynski for info
=> sigstore-go: initial integration

projects/cosign/Dockerfile
Switch to cosigns upstream repo
=> cosign: clone upstream

projects/sigstore-go/Dockerfile
@haydentherapper @bobcallaway @codysoyland @DavidKorczynski for info
=> sigstore-go: use upstream repo

projects/cxxopts/project.yaml
Updates my email for the cxxopts project.
=> cxxopts: Update auto_ccs email

projects/poco/Dockerfile, projects/poco/build.sh, projects/poco/date_time_fuzzer.cc
New fuzzing target for Poco::DateTime library: DateTimeParser.
=> poco: DateTime parser fuzzing

projects/rnp/build.sh
As title says, nothing to add.
=> rnp: enable fuzzing for PQC code

projects/matio/Dockerfile
This is a test if https://github.com/tbeu/zlib/commit/68370a6aeeeaa1f52d809f2d452feec968c0d550 remedies https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=70617 and https://github.com/madler/zlib/issues/997.
Since I cannot reproduce locally I try directly here via oss-fuzz. This is a temporary change to be reverted later.
=> matio: Test possible downstream zlib fix in inflate / inflateCopy

projects/chrono/Dockerfile, projects/chrono/build.sh
=> chrono: fuzz

projects/arrow/project.yaml
Disclaimer: I'm a arrow committer and would working on the fuzz testing
=> arrow: Add Xuwei to ccs

projects/xen/project.yaml
Allows Andrew to see the full bug reports
=> Update an auto_ccs email for Xen

projects/bitcoin-core/build.sh
Log https://oss-fuzz-build-logs.storage.googleapis.com/log-d97d491d-d95a-4210-8eab-fc058f83fd56.txt
=> bitcoin-core: Fix build failure "fuzz_seed_corpus: No such file or directory"

infra/experimental/chronos/chronos.sh
This can happen when the project [uses `make` or `cmake`](https://github.com/google/oss-fuzz/issues/12411#issuecomment-2332982907) to build fuzz targets.
=> Let recompile become compile if Chronos did not intercept any command

projects/poco/Dockerfile, projects/poco/build.sh, projects/poco/jwt_decode_fuzzer.cc
New fuzzing target for Poco::JWT library that covers tokens decoding and signature verification
=> poco: JWT decode fuzzing

projects/libvips/Dockerfile
See: https://gitlab.com/libtiff/libtiff/-/merge_requests/645.
=> libvips: add autoconf-archive bootstrap dependency

projects/cert-manager/build.sh
Build a fuzzer that was recently added upstream.
=> cert-manager: add fuzzer

projects/skia/project.yaml
These reflect some team changes as of late.
=> [skia] Update cc list

projects/connectedhomeip/Dockerfile, projects/connectedhomeip/build.sh
- previous PR #12461 was integrated before being complete.
=> [Connectedhomeip] Pulling correct Repo branch

projects/grpc/project.yaml
It never worked and is causing exceptions.
=> Disable honggfuzz on grpc

projects/cert-manager/build.sh
The vault fuzzer was renamed and another fuzzer was added.
=> cert-manager: add upstream fuzzer

projects/libconfig/project.yaml
I am requesting permission to integrate [libconfig](https://github.com/hyperrealm/libconfig) into OSS-Fuzz. I believe that this project is a good candidate for OSS-Fuzz integration as it serves as a preeminent library for parsing and reading configuration files. The [Linux](https://github.com/torvalds/linux/blob/master/tools/thermal/thermometer/thermometer.c) kernel, [Janus WebRTC Server](https://github.com/meetecho/janus-gateway), and the [SSLH](https://github.com/yrutschle/sslh) project are just a few examples of high-impact and security relevant projects that utilize this library. In addition to the possibility of uncovering edge-cases and bugs in the parsing of configuration files, there is the possibility of a malicious actor crafting a corrupted config file for an elevated service …
=> Initial project proposal

projects/pcre2/Dockerfile
Fixes fuzzer build following https://github.com/PCRE2Project/pcre2/pull/443. cc @PhilipHazel
=> PCRE2 fuzz build fix

projects/hiredis/build.sh
Ref: https://github.com/google/oss-fuzz-gen/issues/635
=> hiredis: avoid mv in build

projects/wuffs/Dockerfile
Actually using this corpus will be separate (other repo) commit to https://github.com/google/wuffs/blob/main/fuzz/c/std/seed_corpora.txt
=> [wuffs] add webp_corpus

projects/wolfssl/project.yaml
@kareem-wolfssl
Adding the wolfSSL engineer Kareem to the email list (and hopefully access to the oss-fuzz reports)
=> [wolfssl] add Kareem to email list

projects/open62541/project.yaml
=> Update maintainers of open62541

projects/kimageformats/Dockerfile, projects/kimageformats/build.sh, projects/kimageformats/kimgio_fuzzer.cc
Added JXR, PFM and PXR plugins to fuzzer tests.
=> KImageFormats: added missing handlers

projects/opentelemetry/Dockerfile, projects/opentelemetry/build.sh
This builds more of fuzzers that are recently added upstream.
=> opentelemetry: add more upstream fuzzers

projects/servo/build.sh
Propagate to OSS fuzz from https://github.com/servo/html5ever/pull/557.
=> [servo] fuzz xml5ever

projects/neomutt/Dockerfile
Add package `libsqlite3-dev` to fix autocrypt.
=> neomutt: install libsqlite3-dev

projects/wabt/project.yaml
@sbc100 @binji @shravanrn @SoniEx2
=> wabt: add SoniEx2 to auto_ccs

projects/llvm/project.yaml
As Reid Kleckner requested, since they are getting email bounces and complaining
=> Remove llvm-bugs

projects/serenity/project.yaml
It's been a while since I've paid any attention to these emails. :sweat_smile: 
cc: @ADKaster @awesomekling
=> serenity: Remove myself from the mailing list

projects/llvm/project.yaml
It's been fun folks, I've moved on from $COMPANY and the volume of emails for this project has gone up substantially.
=> Remove mitchp from llvm oss-fuzz

projects/sentencepiece/build.sh
=> sentencepiece: extend build

projects/lz4_flex/Dockerfile, projects/lz4_flex/build.sh
=> [lz4_flex] finalize

projects/data-encoding/project.yaml
This is a follow-up of #12622. Otherwise I don't have access to the build status.
=> Add contacts for data-encoding

projects/bitcoin-core/build.sh
See https://github.com/bitcoin/bitcoin/pull/31130.
See also https://github.com/bitcoin/bitcoin/pull/30043.
=> bitcoin: drop no-longer existent depends options

infra/build/functions/build_project.py, infra/build/functions/target_experiment.py
=> target_experiment: Properly propagate real name.

projects/vulkan-loader/project.yaml
Ref: https://github.com/KhronosGroup/Vulkan-Loader/pull/1590
CC: @charles-lunarg
=> vulkan-loader: update contacts

projects/sqlite3/build.sh, projects/sqlite3/project.yaml
Fixes: https://github.com/google/oss-fuzz/issues/12709
=> sqlite3: fix build

projects/surrealdb/build.sh
Remove unnecessary logic from build script.
=> surrealdb: update build script

projects/wasmedge/build.sh
* Remove `-fuse-ld=lld` option
=> wasmedge: fix build failure (#379122775)

projects/cilium/project.yaml
In order to receive fuzz-related notifications, adding myself to the mailing list.
=> Update project.yaml with my email

projects/cpython3/Dockerfile
=> cpython3: Run apt update in the same RUN layer as install

projects/upx/build.sh, projects/upx/fuzzers/build.patch, projects/upx/fuzzers/decompress_packed_file_fuzzer.cpp, projects/upx/fuzzers/list_packed_file_fuzzer.cpp, projects/upx/fuzzers/test_packed_file_fuzzer.cpp
Ref: https://github.com/google/oss-fuzz/issues/12759
=> upx: fix build

projects/cert-manager/build.sh
Adds two more upstream fuzzers to cert-managers build.
=> cert-manager: run more upstream fuzzers

infra/build/build_status/Dockerfile
=> Replace pip with pip3 in builds status cron.

projects/fluxcd/project.yaml
Part of https://github.com/fluxcd/community/issues/419
=> Add @matheuscscp to the Flux Security team

projects/libigl/project.yaml
Follow-up to https://github.com/google/oss-fuzz/pull/12812
=> libigl: update contacts

projects/kubevirt/Dockerfile, projects/kubevirt/build.sh, projects/kubevirt/fuzz_loadInstallStrategyFromBytes_test.go
Adds another fuzz test for the Kubevirt project.
=> kubevirt: add harness

projects/kimageformats/build.sh, projects/kimageformats/kimgio_fuzzer.cc
We have reintroduced the DDS plugin into KImageFormats and it is now back in the tests.
=> Added DDS plugin test to KImageFormats

infra/experimental/chronos/build_cache_local.sh
This is useful when evaluating and testing the setup.
=> chronos: add local builder

infra/experimental/chronos/build_cache_local.sh
Support validating if replay scripts work and whether ccache builds work
=> infra: chronos: extend local cache builder

infra/build/functions/build_lib.py, infra/build/functions/build_project.py, infra/build/functions/test_data/expected_build_steps.json, infra/build/functions/test_data/expected_centipede_build_steps.json, infra/build/functions/test_data/expected_coverage_build_steps.json, infra/build/functions/test_data/expected_trial_build_steps.json
=> Revert "Save docker images for C/C++"

infra/base-images/base-builder-jvm/Dockerfile
=> Update Jazzer to the latest version (Apache 2.0)

projects/cloud-hypervisor/project.yaml
Switch to use my personal gmail for future oss-fuzz related communications.
=> [cloud-hypervisor] Update contact information

projects/golang/ecdsa_fuzzer.go
Avoid https://issues.oss-fuzz.com/issues/388081047
=> golang: avoid false positive in fuzzer

projects/libsoup/Dockerfile, projects/libsoup/build.sh, projects/libsoup/project.yaml
This contains the initial build files for the project.
=> libsoup: Configure project

projects/pcre2/build.sh
I'm "decluttering" the root of the PCRE2 repository, so I'd like to move these six files to a new location.
See https://github.com/PCRE2Project/pcre2/pull/661
=> PCRE2: Update build.sh with moved config file locations

projects/monero/Dockerfile
https://github.com/monero-project/monero/issues/9699
=> monero: fix boost / openssl link 

projects/apache-logging-log4cxx/project.yaml
Adding myself to `project.yaml` so I can keep an eye on runtime data and found crashes.
@swebb2066: I am working with @raboof on improving the fuzzing efforts of Log4CXX.
=> apache-logging-log4cxx: update project.yaml

infra/base-images/base-builder/bash_parser.py
Sample usages: 
https://github.com/search?q=repo%3Agoogle%2Foss-fuzz%20cmake%20--build&type=code
=> bash_parser: Retain "cmake --build"

projects/wolfssl/Dockerfile, projects/wolfssl/build.sh
Cryptofuzz has been removed, but added here:
https://github.com/MozillaSecurity/cryptofuzz
=> wolfssl: fix build

projects/circl/Dockerfile
Cryptofuzz has been removed/moved
=> circl: fix build

projects/tarantool/build.sh
Needed for https://github.com/tarantool/tarantool/pull/10911
=> tarantool: update find pattern

projects/apache-logging-log4cxx/build.sh
As discussed in https://github.com/apache/logging-log4cxx/pull/460#discussion_r1930188937
cc @ swebb2066 and @rm5248 for info.
=> apache-logging-log4cxx: add seed corpus

projects/unrar/project.yaml
=> Update contact email in unrar/project.yaml

projects/cgif/Dockerfile, projects/cgif/build.sh
Adds a new fuzzer. Improves the code coverage.
For reference: dloebl/cgif#74
=> cgif: add file fuzzer

projects/apache-logging-log4cxx/project.yaml
This PR allows me to help address bugs found by oss-fuzz - I am a PMC for Apache Logging PMC – see [the team list](https://logging.apache.org/team-list.html)
=> Add to log4cxx cc list

projects/cert-manager/Dockerfile, projects/cert-manager/build.sh
The fuzzers have been merged into upstream cert-manager.
=> cert-manager: build upstream fuzzers

projects/opus/Dockerfile
This branch contains changes that are intended to be merged into main.
=> opus: fuzz the ossfuzz branch

projects/kubevirt/Dockerfile, projects/kubevirt/build.sh
=> kubevirt: add more upstream fuzzers

projects/java-xmlbuilder/build.sh, projects/jflex/build.sh, projects/open-json/build.sh, projects/threetenbp/build.sh
This PR follows #13033 to fix more JVM project build script.
=> JVM: Fix build script for some jvm projects

projects/unirest-java/JacksonEngineFuzzer.java, projects/unirest-java/build.sh
This PR fixes the build and fuzzer for unirest-java following the update in the upstream project.
=> unirest-java: Fix build

projects/flyway/Dockerfile, projects/flyway/build.sh
This PR fixes the build for project flyway following requirement changes of dependencies upstream.
=> flyway: Fix build

projects/jackson-dataformat-xml/build.sh, projects/jansi/build.sh, projects/joni/build.sh, projects/jts/build.sh
This PR fixes more jvm project build for new Fuzz-Introspector following #13034.
=> [JVM] Fix project build for new FI

projects/rustls/Dockerfile, projects/rustls/build.sh
This reinstates the corpus source, now living at
rustls/rustls-fuzzing-corpora.
=> Reapply "[rustls] Add seed corpus (#10179)" (#12750)

projects/msgpack-c/Dockerfile
Update boost libraries download URL.
=> Fix https://issues.oss-fuzz.com/issues/386860173

projects/jooq/Dockerfile, projects/jooq/build.sh
This PR fixes the build for project jooq following upstream repository update.
=> jooq: Fix build

projects/exp4j/build.sh, projects/fuzzywuzzy/build.sh, projects/jsemver/build.sh
This PR fixes more JVM project build following updated FI.
=> jvm: Fix more JVM project build

projects/feign/Dockerfile, projects/feign/build.sh, projects/feign/toolchains.xml
This PR fixes the build for project feign following upstream repository.
=> feign: Fix project build

projects/args/Dockerfile, projects/args/build.sh, projects/args/project.yaml
Initial integration support for a well-maintained and popular command-line argument parsing library written in C++. [args](https://github.com/Taywee/args) attempts to be compatible with the functionality of the Python standard argparse library.
Approval from the maintainer can be found in this [pull request](https://github.com/Taywee/args/pull/128) that was merged.
=> args: initial integration

projects/swagger-core/Dockerfile, projects/swagger-core/build.sh
This PR fixes the build for swagger-core following upstream repository update.
=> swagger-core: Fix build

projects/mybatis-3/Dockerfile, projects/mybatis-3/build.sh
This PR fixes the build for mybatis3 following upstream repository update.
=> mybatis3: Fix build

projects/kie-soup/build.sh, projects/quartz/build.sh, projects/spatial4j/build.sh, projects/sqlite-jdbc/build.sh
This PR fixes more JVM project build following FI update.
=> JVM: Fix project build for new FI

projects/tyrus/Dockerfile, projects/tyrus/build.sh
This PR fixes the project build for project tyrus following upstream repository.
=> tyrus: Fix build

projects/antlr3-java/build.sh, projects/antlr4-java/build.sh, projects/xstream/build.sh, projects/xz-java/build.sh, projects/zip4j/build.sh
This PR continues to fix more JVM project build for the updated FI.
=> jvm: Fix more project build for new FI

projects/undertow/build.sh, projects/woodstox/build.sh, projects/xerces/build.sh
This PR fixes more JVM projects built following FI update.
=> jvm: Fix project build

projects/python-multipart/Dockerfile, projects/python-multipart/build.sh, projects/python-multipart/fuzz_form.options
This will most probably fix the non-reproducible oom issue with this project.
=> python-multipart: fix oom

projects/kubevirt/FuzzAdmitter.options, projects/kubevirt/FuzzWebhookAdmitters.options, projects/kubevirt/FuzzWebhookMutators.options
The timeout is on the edge on my local machine and it might be too low for a cloud machine with fewer resources. Bumping to experimentally see if it eliminates all timeouts.
=> kubevirt: increase timeout

infra/cifuzz/filestore/github_actions/upload.js, infra/cifuzz/package.json, infra/run_fuzzers.Dockerfile
Need to upgrade npm package.
We need to test this first by rebuilding the docker image. 
Fixes https://github.com/google/clusterfuzz/issues/4654
=> Fix artifact uploading.

projects/bitcoin-core/build.sh
Required after https://github.com/bitcoin/bitcoin/pull/31161.
=> bitcoin-core: Adjust built target directory

projects/powsybl-java/Dockerfile, projects/powsybl-java/ImporterFuzzer.java, projects/powsybl-java/build.sh, projects/powsybl-java/project.yaml
This PR initialises  the fuzzing for multiple java modules for powsybl projects.
PowSyBl is an open-source set of Power System Blocks dedicated to grid analysis, visualization, and simulation of power grids.
PowSyBl is used by companies like [coreso](https://www.coreso.eu/), [Baltic RCC](https://baltic-rcc.eu/), [emsys](https://www.emsys-renewables.com/), [neon research](https://neonresearch.nl/) and [RTE](https://www.rte-france.com/en/home) and by tools such as [LF Energy Dynawo](https://dynawo.github.io/), [GridSuite](https://www.gridsuite.org/), [farao](https://farao-community.github.io/),
=> powsybl-java: project initialisation

projects/libxslt/project.yaml
I'm not involved in libxslt anymore.
=> libxslt: Remove myself as contact

projects/onednn/project.yaml
This PR updates the project details for the [oneDNN](https://github.com/uxlfoundation/oneDNN) repo including the homepage and website. It also updates the list of contacts by adding the `primary_contact` and the `auto_ccs` list.
=> onednn: update project.yaml

projects/powsybl-java/LoadFlowFuzzer.java, projects/powsybl-java/MetrixFuzzer.java, projects/powsybl-java/OpenRaoFuzzer.java
This PR fixes the fuzzers for powsybl-java to avoid some early exit in OpenRaoFuzzer and LoadFlowFuzzer. This PR also fixes the MetrixFuzzer following upstream repository update.
=> powsybl-java: update fuzzers

projects/timestamp-authority/Dockerfile, projects/timestamp-authority/build.sh
https://github.com/sigstore/timestamp-authority/pull/1013 has merged, re-running checks should pass now
=> add dockerfile and build script for sigstore/timestamp-authority

projects/powsybl-java/MatrixFuzzer.java
This PR renames the `MatrixFuzzer` for the *powsybl-java* project. It also adds variations of different matrix initialisations to the logic, allowing the fuzzing of different matrix types.
=> powsybl-java: fix matrix fuzzer

projects/powsybl-java/DeserializeFuzzer.java
Modifies the fuzzer slightly so it can better use the seed corpus.
=> powsybl-java: modify fuzzer

projects/powsybl-java/ParseFuzzer.java, projects/powsybl-java/build.sh
Adds corpus and dict to a fuzzer.
=> powsybl-java: add corpus to fuzzer

projects/powsybl-java/OpenRaoFuzzer.java
This PR fixes the blockers of fuzzing OpenRaoFuzzer.
=> powsybl-java: fix OpenRaoFuzzer

projects/powsybl-java/LoadFlowFuzzer.java, projects/powsybl-java/MatrixFuzzer.java
This PR fixes the NPE handling for two fuzzers of powsybl-java project.
=> powsybl-java: Add NPE handling to fuzzers

projects/powsybl-java/project.yaml
Adding project maintainers to powsybl-javas OSS-Fuzz integration.
For info @olperr1 @So-Fras @rolnico
=> powsybl-java: add project maintainers

projects/gateway/Dockerfile, projects/gateway/build.sh, projects/gateway/project.yaml
[Envoy Gateway](https://github.com/envoyproxy/gateway) manages **Envoy Proxy** as a Standalone or Kubernetes-based Application Gateway.  Since [Envoy Proxy](https://github.com/envoyproxy/envoy/tree/main/test/fuzz) already benefits from extensive fuzz testing, we are applying the same approach to Envoy Gateway to ensure similar robustness and reliability.
Fuzzing integration in envoygateway is tracked in https://github.com/envoyproxy/gateway/issues/5425. 
Note: This work is sponsored by the [Linux Foundation Mentorship](https://mentorship.lfx.linuxfoundation.org/project/44020e81-1218-49aa-95e0-ee3e03998eb3) program.
```bash
python3 infra/helper.py build_image gateway
python3 infra/helper.py build_fuzzers gateway 
python3 infra/helper.py run_fuzzer gateway <Fuzzer Name>
```
- Canva
- …
=> Envoy Gateway initial integration

projects/ffmpeg/Dockerfile
Needed after https://gitlab.xiph.org/xiph/theora/-/commit/34bf876678f87614ebe24d78c037601d9e01052e
=> ffmpeg: update autoconf to 2.72 to fix build

infra/base-images/base-clang/checkout_build_install_llvm.sh
readelf is a symlink to readobj
=> Keep readobj

projects/neqo/Dockerfile
Checking if this fixes the build when run by the fuzzer.
CC @jonathanmetzman
=> projects/neqo: Download all to $SRC

projects/neqo/Dockerfile
=> projects/neqo: Avoid `ADD` in `Dockerfile`

projects/fontations/project.yaml
cc @rsheeter to approve on behalf of fontations.
=> projects/fontations: Add self to CC

projects/globaleaks/project.yaml
Hello! Thank you for your attention and cool work!
This pull request is to request the addition of the globaleaks project.
Following the getting-started guidelines we are first proposing and we will proceed adding the configuration for the fuzzing: https://google.github.io/oss-fuzz/getting-started/
=> Add GlobaLeaks project

projects/openkruise/Dockerfile, projects/openkruise/build.sh, projects/openkruise/project.yaml
OpenKruise is an extended component suite for Kubernetes, which mainly focuses on automated management of large-scale applications, such as deployment, upgrade, ops and availability protection. #13219
=> feat: add OpenKruise project

projects/solidity/project.yaml
The fuzzer maintainers for this project have changed. Hence this PR.
=> Solidity: Change primary contact.

projects/wamr/Dockerfile, projects/wamr/build.sh, projects/wamr/project.yaml
- classic-interp
- llvm-jit
- aot-compiler
- loader -> fast-interp
=> [wamr] Add more fuzzing targets

infra/base-images/base-builder/Dockerfile
=> Upgrade patchelf to 0.18.0

projects/dbus-broker/build.sh
to fix build failures caused by https://github.com/mesonbuild/meson/issues/14533
=> [dbus-broker] pin meson to 1.7.2 for now

projects/httparse/build.sh
These fuzzers were not included into OSS-Fuzz project
=> httparse: Add missing fuzzers

projects/bitcoin-core/build.sh
=> bitcoin-core: remove NO_BDB

projects/mpv/Dockerfile, projects/mpv/build.sh
* mpv: pin Meson to 1.7.2 for now
* mpv: download all sources in Dockerfile
* mpv: --disable-postproc doesn't exist anymore in ffmpeg config
=> mpv: pin Meson to 1.7.2 for now

projects/ossf-scorecard/Dockerfile, projects/ossf-scorecard/build.sh, projects/ossf-scorecard/probes_fuzzer.go
Adds a fuzzer for the Scorecard probes.
=> Scorecard: add probes fuzzer

projects/ossf-scorecard/project.yaml
This will allow me to see Scorecards bug reports.
@spencerschrock @justaugustus @raghavkaul please confirm this is alright.
=> Scorecard: add myself as cc

projects/ossf-scorecard/probes_fuzzer.go
Adds more calls to the probes fuzzer.
=> Scorecard: add more targets to probes fuzzer

projects/ffmpeg/project.yaml
John doesn't work on this project anymore. Thank you for your contributions!
=> Remove jrummell@google.com from project.yaml

infra/base-images/base-builder/indexer/clang_wrapper.py
lld does not link against /usr/local/lib by default, unlike lld which it is replacing.
=> Fix issues with forcing lld.

projects/golang/project.yaml
=> [golang] update access config

infra/base-images/base-builder/indexer/README.md
Add missing step to download the indexer binary.
=> fix indexer development instructions

projects/mysql-server/Dockerfile, projects/mysql-server/build.sh
=> mysql: use upstream fuzz targets

projects/mysql-server/build.sh
Follow-up on https://github.com/google/oss-fuzz/pull/13339
Next step would be to re-add the previous fuzz targets (if they are not covered by the current ones)
=> mysql-server: compile all project

infra/base-images/base-builder/indexer/README.md, infra/base-images/base-builder/indexer/clang_wrapper.py, infra/base-images/base-builder/indexer/index_build.py, infra/base-images/base-builder/indexer/index_build_test.py
Also disable tests by default, because they don't work on GitHub actions.
=> indexer: more minor cleanup.

projects/ossf-scorecard/probes_fuzzer.go
Adds 10 more probe targets to the probes fuzzer.
=> ossf-scorecard: add more probes to probes fuzzer

projects/ossf-scorecard/probes_fuzzer.go
=> ossf-scorecard: add more calls to to probes

projects/ossf-scorecard/probes_fuzzer.go
deduplicates the creation of branches.
=> ossf-scorecard: deduplicate probes fuzzer

projects/vlc/project.yaml
Add Marvin: https://code.videolan.org/ePirat/
=> vlc: add a Cc

infra/base-images/base-builder/Dockerfile
This be required by a future indexer change.
=> Add some new Python dependencies to base-builder.

infra/base-images/base-builder/indexer/README.md
Use newly introduced docker passthrough flags
=> Update indexer README with better instructions.

infra/tools/hold_back_images.py, projects/astroid/Dockerfile, projects/bs4/Dockerfile, projects/dill/Dockerfile, projects/httpx/Dockerfile, projects/msal/Dockerfile, projects/packaging/Dockerfile, projects/pybind11/Dockerfile, projects/pyodbc/Dockerfile, projects/setuptools/Dockerfile, projects/tomli/Dockerfile
Needed for https://github.com/google/oss-fuzz/pull/13404
=> Hold back images of projects that can't use python3.11

infra/base-images/base-builder/Dockerfile, infra/base-images/base-runner/Dockerfile
=> Upgrade Python to 3.11

projects/aptos-core/Dockerfile, projects/aptos-core/project.yaml
Changes:
- Set RUSTUP_TOOLCHAIN to nightly-2024-09-05 in Dockerfile.
- Change primary contact email
- Add VM team to auto_ccs in project.yaml
Thanks.
=> Update Dockerfile and project.yaml for Aptos Core

projects/cups/project.yaml
Add one new member to help triage bug reports of cups.
=> [cups] update contact info

infra/base-images/base-builder/compile
This is to enable https://github.com/google/oss-fuzz/pull/13427
=> Chronos replay: Allow overriding replay scripts.

projects/fluxcd/project.yaml
xref: https://github.com/fluxcd/.github/pull/33
=> Add Stefan Prodan to Flux CD project

projects/php/Dockerfile, projects/php/replay_build.sh
php: Compile times: Vanilla=62; Replay=2;
=> php: add replay script

projects/clamav/Dockerfile, projects/clamav/build.sh, projects/clamav/replay_build.sh
clamav: Compile times: Vanilla=123; Replay=8;
=> clamav: add replay_build script

projects/nss/project.yaml
Adding ckerschbaumer@mozilla.com and moving from my email to mailing list for primary contact
=> NSS - Update Primary Contact and CCs

projects/vulkan-loader/.vscode/settings.json, projects/vulkan-loader/build.sh, projects/vulkan-loader/fuzzers/instance_enumerate_fuzzer.c
=> vulkan-loader: optimize existing harness and add new

projects/fsnotify/Dockerfile, projects/fsnotify/build.sh, projects/fsnotify/fuzz_test.go
Replaces the current fuzzer with a fuzzer for the fsnotify watcher.
=> fsnotify: replace current fuzz test

projects/pidgin/Dockerfile, projects/pidgin/build.sh
Add a few more dependencies that libffi depends on, build against latest libffi and upgrade automake
=> pidgin: fix broken build

infra/build/functions/base_images.py
Add back missing step that was accidentally removed.
=> Fix base build.

projects/brotli/build.sh, projects/brotli/run_tests.sh
Results of `infra/experimental/chronos/check_tests.sh brotli c`:
```
Test project /src/brotli
Start  1: roundtrip/tests/testdata/alice29.txt/1
1/73 Test  #1: roundtrip/tests/testdata/alice29.txt/1 ........................   Passed    0.03 sec
Start  2: roundtrip/tests/testdata/alice29.txt/6
2/73 Test  #2: roundtrip/tests/testdata/alice29.txt/6 ........................   Passed    0.05 sec
Start  3: roundtrip/tests/testdata/alice29.txt/9
3/73 Test  #3: roundtrip/tests/testdata/alice29.txt/9 ........................   Passed    0.07 sec
Start  4: roundtrip/tests/testdata/alice29.txt/11
4/73 Test  #4: roundtrip/tests/testdata/alice29.txt/11 .......................   Passed    0.77 sec
Start  5: roundtrip/tests/testdata/asyoulik.txt/1
5/73 Test  #5: roundtrip/tests/testdata/asyoulik.txt/1 …
```
=> brotli: add run_tests.sh

projects/libtiff/Dockerfile, projects/libtiff/run_tests.sh
Adds `run_tests.sh` for the libtiff project.
The last lines of `infra/experimental/chronos/check_tests.sh libtiff c` are:
```
Test project /src/libtiff
Start   1: test_signed_tags
1/159 Test   #1: test_signed_tags ............................................   Passed    0.02 sec
Start   2: ascii_tag
2/159 Test   #2: ascii_tag ...................................................   Passed    0.01 sec
Start   3: long_tag
3/159 Test   #3: long_tag ....................................................   Passed    0.01 sec
Start   4: short_tag
4/159 Test   #4: short_tag ...................................................   Passed …
```
=> libtiff: add run_tests.sh

projects/go-attestation/build.sh
some fuzzers changed their names.
=> go-attestation: fix broken build

projects/cgif/run_tests.sh
Adds `run_tests.sh` to the expat project.
Output of ./infra/experimental/chronos/check_tests.sh cgif c:
```
ninja: Entering directory `/src/cgif/build'
ninja: no work to do.
1/211 all_optim                                                                        OK              0.29s
2/211 alpha                                                                            OK              0.28s
3/211 animated_interlaced                                                              OK              0.25s
4/211 animated_single_pixel                                                            OK              0.23s
5/211 animated_snake …
```
=> cgif: add run_tests.sh

projects/tinyxml2/run_tests.sh
Adds `run_tests.sh` to the tinyxml2 project.
Last few lines of the output of ./infra/experimental/chronos/check_tests.sh tinyxml2 c++:
```
[pass] Issue 302. Subsequent success in saving [XML_SUCCESS][XML_SUCCESS]
[pass] Should be no error initially [false][false]
[pass] No such file - should fail [true][true]
[pass] Error should be cleared [false][false]
[pass] parse errors occur - should fail [true][true]
[pass] Error should be cleared [false][false]
[pass] Test that the code changes do not affect normal parsing [false][false]
[pass] Test that the second declaration is allowed [false][false]
[pass] Test that declaration after self-closed …
```
=> tinyxml2: add run_tests.sh

projects/lodepng/run_tests.sh
`infra/experimental/chronos/check_tests.sh lodepng c++`
```
...
doTestHuffmanCodeLengths: 1 30 31 32
doTestHuffmanCodeLengths: 1 2 3 4 5 6 7 500
testCustomZlibCompress
testCustomZlibCompress2
testCustomDeflate
testCustomZlibDecompress
testCustomInflate
testChunkUtil
testGetFilterTypes
test successful
```
=> lodepng: add run_tests

projects/ndpi/Dockerfile, projects/ndpi/run_tests.diff, projects/ndpi/run_tests.sh
`infra/experimental/chronos/check_tests.sh ndpi c`
```
sha256:a72333481d219c8d9a6a507ff125e4c2216e3dbb3c578a5832da586e3354df59
/src/ndpi/tests/unit /src
serializerUnitTest                      OK
serializeProtoUnitTest                      OK
/src
```
=> ndpi: add run_tests.sh

projects/spdlog/build.sh, projects/spdlog/run_tests.sh
`infra/experimental/chronos/check_tests.sh spdlog c`
```
Test project /src/spdlog                                                                                                                13:06:09 [23/1817]
Start 1: spdlog-utests                                                   
1/1 Test #1: spdlog-utests ....................   Passed    5.55 sec                                                                                      
100% tests passed, 0 tests failed out of 1                                                                                                                
Total Test time (real) =   5.55 sec
```
=> spdlog: add run_tests.sh

projects/lz4/run_tests.sh
Adds `run_tests.sh` to the lz4 project.
`infra/experimental/chronos/check_tests.sh lz4 c`:
```
...
Starting benchmark for function: LZ4_decompress_fast()
Starting suite B:  Highly compressible text.
Starting benchmark for function: LZ4_compress_default()
Starting benchmark for function: LZ4_compress_fast()
Starting benchmark for function: LZ4_compress_fast_extState()
Starting benchmark for function: LZ4_decompress_safe()
Starting benchmark for function: LZ4_decompress_fast()
+--------------+------------------------------+--------------+----------------+--------------+--------------+
|Source        |Function Benchmarked          | Total …
```
=> lz4: add run_tests.sh

projects/brunsli/run_tests.sh
```
$ ./infra/experimental/chronos/check_tests.sh brunsli c++
Start 18: HuffmanTree.Limited                                                                                                                                                                          
18/29 Test #18: HuffmanTree.Limited ................................   Passed    0.01 sec                                                                                                                                                      
Start 19: HuffmanTree.SimpleLiteral …
```
=> brunsli: add run_tests.sh

projects/bind9/Dockerfile, projects/bind9/build.sh, projects/bind9/run_tests.sh
```
$ ./infra/experimental/chronos/check_tests.sh bind9 c++
...
...
65/87 bind:isc / ratelimiter               OK               1.76s                                                                                                                                                             
66/87 bind:isc / tcp                       OK               1.60s                                                                                                                                                             
67/87 bind:ns / query                      OK               0.52s …
```
=> bind9: add run_tests.sh

infra/experimental/chronos/check_tests.sh
sample:
```
$ ./infra/experimental/chronos/check_tests.sh jsonnet c++
...
--------------------------------------------------------
Total time taken to replay tests: 127
```
=> chronos: check-test: log total test replay time

infra/experimental/chronos/check_tests.sh
[Noted](https://github.com/google/oss-fuzz/pull/13621#discussion_r2212314317) during #13621.
=> Add `--network none` to the tests execution of check_tests.sh

projects/libcue/run_tests.sh
`infra/experimental/chronos/check_tests.sh libcue c`
```
Running tests...                                                                                 
Test project /work                                                                               
Start 1: standard_cue_test                                                                   
1/6 Test #1: standard_cue_test ................   Passed    0.01 sec                             
Start 2: single_file_idx_00_test                                                             
2/6 Test #2: single_file_idx_00_test ..........   Passed    0.01 sec                             
Start 3: …
```
=> libcue: add run_tests.sh

projects/helm/Dockerfile, projects/helm/build.sh
Refactors the build file and bumps go11fb
=> helm: refactor and fix broken build

projects/charset_normalizer/Dockerfile, projects/charset_normalizer/project.yaml
I'm the maintainer of charset-normalizer.
The details for charset-normalizer Python package were outdated.
=> Update charset-normalizer repo & contact details

projects/libmicrohttpd2/fuzz_connection.cpp
This PR fixes the fuzz_connection fuzzer for libmicrohttpd2 to unblock fuzzing.
=> libmicrohttpd2: Fix fuzz_connection

projects/v8/build.sh
=> v8: delete d8 before building again.

projects/libmicrohttpd2/build.sh, projects/libmicrohttpd2/connection_helper.cpp, projects/libmicrohttpd2/connection_helper.h, projects/libmicrohttpd2/fuzz_daemon_connection.cpp
This PR adds a new fuzzer targeting daemon/connection processing functions in libmicrohttpd2 project.
=> libmicrohttpd2: Add new fuzzer

projects/libcacard/build.sh
ref: https://github.com/google/oss-fuzz/pull/13915
=> libcacard: make ready for llvm 21

projects/samba/build.sh
Ref: https://github.com/google/oss-fuzz/pull/13915
=> samba: prepare for llvm 21

projects/nss/build.sh
ref:
https://github.com/google/oss-fuzz/pull/13915#issuecomment-3250384177
=> nss: prepare for llvm 21

projects/rtpproxy/build.sh
ref:
https://github.com/google/oss-fuzz/pull/13915#issuecomment-3250384177
=> rtpproxy: prepare build for llvm 21

infra/experimental/chronos/manager.py
the arg is not available from the parser
=> chronos: minor fix

infra/base-images/base-builder/Dockerfile, infra/base-images/base-builder/afl_llvm22_patch.diff
ref: https://github.com/google/oss-fuzz/pull/13915#issuecomment-3270162311
=> infra: bump afl++ to enable llvm 22

projects/angle/Dockerfile, projects/angle/build.sh, projects/angle/fuzzer_profile
This PR fixes the general and coverage build for the project angle.
=> angle: Fix build

infra/experimental/chronos/manager.py
=> Fix chronos

projects/syzkaller/project.yaml
Update CC list to current project members.
CC @a-nogikh @tarasmadan
=> syzkaller: update CC list

projects/icu/project.yaml
=> add grhoten@gmail.com  to icu project 

projects/suricata/build.sh
instead of just level 1 directories
=> suricata: use suricata-verify subdirectories for corpus

projects/jsoup/CssHtmlFuzzer.java, projects/jsoup/CssHtmlFuzzer.options, projects/jsoup/Dockerfile, projects/jsoup/build.sh
Using the optional re2j regex engine so we don't enable backtracking (and timeouts)
=> jsoup: added a CSS selector fuzzer

projects/nodejs/build.sh
during recent refactoring, I have removed some fuzzers. removing them from the build script.
=> nodejs: remove some fuzzers

infra/experimental/chronos/logic_error_patch.py, infra/experimental/chronos/manager.py
clean up warnings and improve display of integrity tests
=> chronos: refactor and improve test integrity logging
